### ISSUE TITLE
Bolt - 1.16 ércek, blokkok

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3676]
**Szerver**: Survival, Savsziget

**Comment by MrZero1** [comment]
Nehéz beárazni ezeket. Nincs mihez igazítani, ha pedig hasraütésszerűen árazom, megint csak a probléma lesz mindenki részéről. Na meg az, hogy mi legyen bent, mi legyen eladható, vehető, az is jó kérdés.
Ötleteket szívesen várok erre.

**Comment by VdszHun** [comment]
Majd próbálok segíteni, pl. hol található az adott blokk/anyag, farmolható-e vagy limitált, mekkora mennyiségben van átlag, stb. 
Ráérek minden nap 14-22 között :)

**Comment by andris155** [comment]
@MrZero1 akkor nem fognak bekerülni ilyen tárgyak a boltba?

**Comment by MrZero1** [comment]
Tervben van, de még mindig nincs viszonyítási alap. Meg amúgy is, ezt egy óra alatt nem lehet megcsinálni, erre minimum fél napot rá kellene szánni, viszont nekem hétközben ilyenekre nincs időm. Majd gondolkozok az árakon.

**Comment by MrZero1** [comment]
A szülinap után lesz időm ezzel is foglalkozni, szóval akinek van kedve segíteni az árazásban, akár egy word doksiba összeírja, szerinte melyik tárgy/blokk kerüljön be, eladásra és/vagy vásárlásra, tervezett árral, mennyiséggel, az nekem is hatalmas segítség lenne.

**Comment by MrZero1** [comment]
Bekerültek az új dolgok, többekközött a cserekereskedőkhöz is.
Ha bármi hiba lenne (pl. árrés) nyugodtan írjatok privátba.
