### ISSUE TITLE
Event Bug

### ISSUE THREAD

**Issue by KriszLOW** [TheOld-Crafters/Minecraft-servers#3830]
Savsziget.

Shulkup automatikus eventen néha nem adja meg a fly efektet. A célban nem veszi le néha az efektet. Nem érzékeli a helyezést elég gyakran csak ha kilép az egyik játékos aki beért már a célba!

**Comment by andris155** [comment]
@poma123 ? Vagy az volt az ékezetes név miatt?

**Comment by poma123** [comment]
Nem, még nem néztem meg, de meg fogom :)

**Comment by andris155** [comment]
Előre is köszi.

**Comment by poma123** [comment]
Nem sikerült reprodukálni, többször kipróbáltam, és semmi.

**Comment by poma123** [comment]
Sikerült végül mégis reprodukálni, köszi a jelentést!

**Comment by poma123** [comment]
Javítva
