### ISSUE TITLE
Parancsblokkok és az ékezetes nevű játékosok krónikája

### ISSUE THREAD

**Issue by poma123** [TheOld-Crafters/Minecraft-servers#3831]
**Szerver**: Survivalon jött elő

Szóval. Vannak az eventek, és ott van pár olyan hely ahol effektet ad egy gomb. Na, ha ezt egy ékezetes nevű játékos nyomja meg, nem fog kapni semmit, a parancs hibát ír. Viszont ha a cmd blockba beírom a minecraft: prefixet az effect parancs elé, minden működik ahogy kell. A futamot "javítottam" ott még nem tudtam, hogy ez a baja. A kalandrafalnál feladtam. Passzolom a dolgot.

**Comment by andris155** [comment]
A Minecraft parancsok nem támogatják az ékezetes parancsokat sajnos. Erre max az a megoldás, ha külön plugin oldja meg az effektet a Spigot api-n keresztül (?)

**Comment by poma123** [comment]
De ha nem támogatják, akkor a /minecraft:effect miért jó?

**Comment by andris155** [comment]
Ha ott a megoldás a kérdésben akkor nem lényegtelen? :D

**Comment by andris155** [comment]
Egyébként fogalmam sincs. De az jó dolog, ha a minecraft:-al megy. Esetleg megírjam a Paper-nek?

**Comment by andris155** [comment]
Vagy a Spigot-nak? Gondolom abban is jelen van a hiba.

**Comment by poma123** [comment]
Hát jó lenne megtudni mi a baja, mert szerintem nincs itt olyan akit rá lehet venni arra h átírjon 100+ cmd blokkot

**Comment by andris155** [comment]
<img width="582" alt="Capture" src="https://user-images.githubusercontent.com/8324198/89740289-aad8da80-da87-11ea-9deb-d4bb3a7d0526.PNG">
Nekem pedig a teszt szerveren működik ékezetes névvel is minecraft: nélkül is.

**Comment by andris155** [comment]
Ez miatt nem működik minecraft: nélkül.
https://www.spigotmc.org/resources/commandhook.61415/

**Comment by poma123** [comment]
Közben én is rájöttem xd. Akkor ez nem kell már?

**Comment by andris155** [comment]
Ha nem használunk selector-t nem Minecraft-os parancsokban, akkor nem kell.

**Comment by poma123** [comment]
Mintha az EssentialsX azóta már megoldotta volna, hogy lehessen. Le kell ezt is tesztelni. pl /warp valami @p[distance=..5]

**Comment by andris155** [comment]
Nem fog működni egyik parancsban sem enélkül a @p, ami Minecraft-os elvileg.

**Comment by andris155** [comment]
Csak sajnos a vanilla parancsok a legjobb tudomásom szerint nem tudnak világ név alapján teleportálni játékost.

**Comment by andris155** [comment]
Bár [warp] táblával meglehet oldani. Szerintem most teljesen mindegy, hogy gombot nyomnak, vagy táblára jobb klikkelnek.

**Comment by poma123** [comment]
Ha nagyon kell, már lehet amúgy az execute-ben dimenziót állítani, és a világokat is támogatja. 
![image](https://user-images.githubusercontent.com/25465545/89740594-68fd6380-da8a-11ea-9fe5-b3dff0d71473.png)

**Comment by andris155** [comment]
Akkor döntsd el mi legyen erre a megoldás. :D

**Comment by poma123** [comment]
Hát gondolom akkor kerüljön ki a plugin, és ha van olyan hely ahol nem megy a parancs, ott táblával kell megoldani, vagy ``execute in {világ} run tp @p x y z``

**Comment by andris155** [comment]
Egyetértek. De arról döntsetek ti melyik a jobb. Lehet a táblás egyszerűbb lenne.

**Comment by andris155** [comment]
Kivettem a plugint, ha elmondjátok hol vannak ezek a warp parancsblokkok szívesen megcsinálom. De inkább tényleg a tábla lenne egyszerűbb, meg azt nem befolyásolja az sem, ha áthelyezésre kerül a warp. + más szerverekről ismerik a kék Essentials táblákat. A játékosok szeretik a megszokott dolgokat, mert tudják hogy működik.
Egyébként az adminok is megtudják csinálni akár.
[warp]
warpnév
Támogatja a menő új táblákat is.

**Comment by poma123** [comment]
Minden kikúrt eventnél majdnem régi fajta cmd blokkok vannak, ahogy az általad kitörölt kommentben írtam, senki se fogja átírni őket.

**Comment by poma123** [comment]
Mindenképpen vissza kell tenni a CommandHookot, kitalálok erre valami más megoldást.

**Comment by andris155** [comment]
Sikerült kitalálni valamit?

**Comment by andris155** [comment]
A Lucky block-os Minecraft parancsok sem támogatják az ékezetes karaktereket. De itt viszont nem megoldás a minecraft: sem. Amit lehet le kellene cserélni EssentialsX parancsokra amit meg nem arra fogalmam sincs mi a megoldás.

**Comment by andris155** [comment]
Meg amúgy a Chestshop sem működik ékezetes névvel. Lehet inkább tiltani kellene az ékezetes neveket? Talán 1-2 ha ezt használja. Vagy annyi se csak poénból léptek be valami névvel.

**Comment by poma123** [comment]
Igen, jó lenne, ha loginra se engedne fel ékezetes névvel. A luckyblock-os vanilla parancsoknak kellene támogatniuk egyébként, majd arra is ránézek. De mivel nincs sok ilyen játékos, tényleg alacsony a prioritása ennek.

**Comment by andris155** [comment]
Szerintem legyen egy poszt erről, hogy mikor nem lehet már ékezetes névvel játszani és akkor addig lenne idejük nevet váltani.

**Comment by andris155** [comment]
Mondjuk egy hónap időt adnánk erre vagy valami ilyesmi.

**Comment by andris155** [comment]
Neked is ha van időd inkább hasznosabb dolgokkal foglakozz. Ne ezzel szerintem. Biztosan van még más plugin is ami nem nagyon tud mit kezdeni az ékezetes névvel.

**Comment by andris155** [comment]
https://www.oldcrafters.net/2020/08/27/ekezetes-nevek-tamogatasanak-megszuntetese/

**Comment by andris155** [comment]
Már nem lehet felmenni ékezetes nevekkel a szerverre.
