### ISSUE TITLE
Hirdetés

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#3842]
**Szerver**: Survival, de amúgy Sav is 

Lehetne egy olyan jog, amivel hirdetést tudnak feladni vagy beállítani a szerveren, például ha hirdetni szeretnék a boltjukat.
![D8EC17D2-E62E-4235-9F75-334D1C47C7E6](https://user-images.githubusercontent.com/29709854/89944477-2f5e6100-dc20-11ea-872d-343106082c8b.jpeg)

Hasonló módon, mint a képen, pwarp jog adott úgyis, ez a hirdetős jog is lehetne egy rangtól.

**Comment by mnb124** [comment]
Külön lehetve venni pl 330-508 ocd között a jogot. Lehet valaki hirdetni akar de rangot nem vagy valami

**Comment by MrZero1** [comment]
Akár az is, de akár lehetne rangban is. Feltéve ha megoldható ez a fajta hirdetéses dolog.

**Comment by poma123** [comment]
https://www.spigotmc.org/resources/premiumads-player-based-announcements.53683/?

**Comment by poma123** [comment]
Ha ez jó, akkor kellene pár dolog a beállításhoz. 
- A jogon kívül kelljen pénz/token/hirdetés credit a hirdetéshez? Ha igen, melyik, és mennyi?
- Hogy nézzek ki a kiírás? Nekem bejön amúgy az alap beállítás, de érdekel a ti véleményetek is.
- Hány perc cooldown legyen a hirdetések között? Az alapbeállítás 1 perc.

**Comment by MrZero1** [comment]
Az lenne a legjobb, ha tokenért meglehetne venni külön a jogot, rangon kívül, a hirdetésért meg levonna pl. 1500$ pénzt (random számot írtam). 

A hirdetés csak egyszer jelenik meg?

Én az Elit rangba raknám be, de a pénzösszeg ugyanúgy lenne érvényes rá is.

Szerintem 3-5 perc ideálisabb lenne. 
 A fentiek CSAK ÖTLETEK, mielőtt a torkomnak estek, ugyanúgy leírhatja más is a véleményét.

**Comment by poma123** [comment]
> A hirdetés csak egyszer jelenik meg?

A hirdetés akkor jelenik meg amikor beírja az /advertise <üzenet> parancsot, és utána csak a cooldown lejárta után lehet újból hirdetni.

**Comment by MrZero1** [comment]
Aha, akkor a 3-5 perc vagy aközötti idő lenne a legjobb. 3 perc talán azért is ideális, mert nem addigra elpörög a chat, nem tűnik spamnak

**Comment by embervagyok2** [comment]
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1

**Comment by embervagyok2** [comment]
![image](https://user-images.githubusercontent.com/69633425/90135082-69d81300-dd72-11ea-8c09-ff79b299b71f.png)

**Comment by MrZero1** [comment]
Akkor lesz ebből valami? :D

**Comment by poma123** [comment]
nem mindenre válaszoltál amit kérdeztem, plusz akkor kellene egy konkrét válasz rá, nem csak egy random szám hogy mennyibe kerüljön stb stb

**Comment by MrZero1** [comment]
Azt hittem, másoknak is van véleménye. Ha megint egyedül döntök, akkor beüt a diktatórikushelyzetvan jelenség, de nekem mindegy, dönthetek én is

**Comment by poma123** [comment]
Nem volt egyértelmű, hogy az "akkor lesz ebből valami" kinek szólt.

**Comment by MrZero1** [comment]
Itt a válasz, remélem kielégítő:

> A jogon kívül kelljen pénz/token/hirdetéskredit a hirdetéshez? Ha igen, melyik, és mennyi?
Válasz: Minden hirdetés feladásért 3000$ kerüljön levonásra, szerintem ez egy igen csekély összeg. 

> Hogy nézzen ki a kiírás? Nekem bejön amúgy az alapbeállítás, de érdekel a ti véleményetek is.
Válasz: Nekem is megfelel az alap beállítás. 
> Hány perc cooldown legyen a hirdetések között? Az alapbeállítás 1 perc.
Válasz: 3 perc.
> Melyik rangtól legyen jog rá? Ez már kacifántosabb kérdés.
Válasz: Elit rangtól, Elit rangtól van jog a pwarp lerakásra is, így a 2 jogot össze tudják "kapcsolni".


Amennyiben valamelyik pont nem megfelelő (kinézet, ár a hirdetésért) úgyis lehet változtatni.

**Comment by poma123** [comment]
Bekerült Survira, a fenti válaszok alapján. Ha valaki hozzá szeretne szólni, javaslata van, írja le, ha 1 nap múlva nem lesz itt semmi, akkor ezt lezárom.

**Comment by Komjatius** [comment]
Sajnos korábban erről nem tudtam...

Ha egy plusz lehetőség, hogy a figyelmet jobban felhívó hirdetéseket lehessen megjeleníteni, akkor elvben oké. Ha ez elvenné  a lehetőséget, hogy rang nélkül, simán a chatben lehessen hirdetni, akkor teljesen elfogadhatatlan.
Bár, megjegyzem, mivel a rang adja a színes írás jogát, amivel már elég jól ki lehet tűnni a sok chat üzenet közül, nem igazán értem, mi szükség van rá, olyanoknak, akiknek van rangja. Esetleg rang nélküli, sima tagok számára van értelme, akiknek a hirdetése - mint az enyém is - simán beleolvad az üzenetkbe. Ebben a formában a 3000 $ ár is, a 3 perces limit is OK szerintem.
A pwarp és a hirdetés összekapcsolása értelmetlen és valótlan felvetés, hiszen a pwarp megmarad a rang lejárata után is, de ettől még a bolt tovább működik, ergo a hirdetés esetleges szükségessége is.

Jó lenne, ha nem születne olyan megoldás, ami okkal vagy ok nélkül azt a látszatot keltené, hogy pénzéhség a motiváció.

**Comment by MrZero1** [comment]
Ebben semmi pénzéhség nincs, csupán egy plusz jog, ami a rangokban elérhető. 
Fentebb  meg írtam, hogy esetlegesen tokenért is lehetne venni ilyen jogot.

**Comment by MrZero1** [comment]
Akkor még annyit lehetne, hogy a TokenSHOP-ba berakni a jogot, 150 tokenért, és akkor bárki szabadon tudná használni, értelmes kereten belül.

**Comment by poma123** [comment]
Savra is? mennyi ideig tartson a jog?

**Comment by MrZero1** [comment]
Savra is, 15 nap

**Comment by poma123** [comment]
Kész.

**Comment by MrZero1** [comment]
Köszönöm
