### ISSUE TITLE
Delfinek 2.0

### ISSUE THREAD

**Issue by WolterFox** [TheOld-Crafters/Minecraft-servers#3847]
**Szerver**:Survival
Andris, mindent megpróbáltam amit csak tehettem, de nem működik. Átváltoztattam a biomot Deep Warm Oceanra és most mindenhol squid és trópusi hal van, be van kapcsolva a mobspawns szóval tudnak mobok spawnolni, nem tudom mi lehet.

**Comment by embervagyok2** [comment]
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155
![image](https://user-images.githubusercontent.com/69633425/90134518-950e3280-dd71-11ea-90a1-311665de4d35.png)

**Comment by embervagyok2** [comment]
![image](https://user-images.githubusercontent.com/69633425/90134911-29789500-dd72-11ea-9ef1-3666e3344b0e.png)

**Comment by embervagyok2** [comment]
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155

**Comment by embervagyok2** [comment]
![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123

**Comment by andris155** [comment]
Tudsz küldeni képet hol vannak a delfinek, vagy esetleg egy otthon nevet?

**Comment by andris155** [comment]
A hibát egyelőre így nem tudtam reprodukálni. Lehet valami fontos részletről nem tudok.
