### ISSUE TITLE
Ötlet#1: AFK szabályzat, és minden ami azzal kapcsolatos

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#3861]
Habár továbbra is azt a véleményt osztom, hogy egy játékba/szerverre nem AFKolni jár fel az ember, hanem játszani, “dolgozni”, tevékenykedni, ennek ellenére itt és most, közösen beszéljük át az AFK-olásra vonatkozó szabályzatot.

Amit már a mai napon délután 4 után felhoztam az Adminos csoportba, meg amúgyis folyton téma, most akkor kikérve a játékosok, saját érdekektől mentes (tehát ne azért írj, hogy kifejezetten neked legyen jó, hanem minden játékosnak) véleményét, beszéljük át a dolgot.

Tiszta sor, hogy ha dolga akad az embernek, akkor el kell mennie, hirtelen is. Ez rendben van. De ha valaki azért jön fel, majd afkol ki, hogy előnyökhöz jusson, azt már annyira nem preferálom, mert - első sorom - nem afkolni járj fel a szerverre, hanem játszani. 
Itt az órák után kapott játékpénz, levédésblokk is kérdőjel, afkolok aztán kapom a pénzt meg a blokkokat is? Persze, miért ne. 

Nyilván olyan sosem lesz, hogy az mindenkinek jó legyen, de mint eddig is, ezután is arra törekszünk, hogy megtaláljuk a legjobb megoldást. Ez a helyzet volt OldVillage-n az antiafkos plugin, meg a warp afk is.
Hibázunk, belátjuk, újrapróbálkozunk.

🟥Túl hosszú lett, szóval itt van annak röviden, aki lusta elolvasni a fentieket: AFK a szervereken, vele kapcsolatos szabályok újragondolása, megbeszélése.

**Comment by skrisz0101** [comment]
Szerintem ki lehetne próbálni azt az Old Villages plugint, poma aszonta állítható vele minden
@poma123

**Comment by Sanszi** [comment]
Szerintem, amint kiírja valakinél a "Most már nem vagy gépnél" üzenetet, eldobhatná automatikusan /warp afkra az illetőt.

**Comment by DiaGamer321** [comment]
Sanszi  az a probléma, hogy az Afk plugin azt nézi, hogy a személy mikor kattintott utoljára. Sokszor napi eventeken is megjártam, hogy "Nagyba nyomom a jump eventet, és kiítja hogy nem vagyok gépnél". Szerintem nagy szivatás lenne, ha az event közepén elteleportálna.

De ez a módja jobb mint a "Nem mozgós afk plugin", hisz ez megakadályozza az Afk gépek használatát.

**Comment by DiaGamer321** [comment]
De igaz, hogy a "Mozgós afk plugin"  jobb lenne, és mivel már 8-9 segítő van a szerveren, így biztos van idejük meglesni a playereket hajnalba, hogy ne afk gépezzenek, így ez segítene kiszürni a szerverről a becsületlen playereket.

**Comment by andris155** [comment]
Engedélyezzem, hogy nézze a mozgást is @MrZero1 ?

**Comment by Komjatius** [comment]
Mint a viták egyik kirobbantója, akkor most itt is kifejteném a véleményemet, elsődleges, másodlagos stb. javaslataimmal együtt.
Először is, azt gondolom, hogy a jelenlegi AFK szabály teljesen életszerűtlen, a valósággal köszönőviszonyban sincs. A célját ugyan értem: ne legyen ingyen pénz, ingyen levédés, és ne legyen a SF miatt lag. De ezek a szempontok még nem teszik semmissé a tényeket, a valóságot.
Előjáték: amikor volt a szavazás, hogy Vanilla vagy SF plugin, felületesen utánanéztem a SF-nak, néztem pár videót, és ellene szavaztam. Mivel a játék technikai részéhez, főleg a szerverszintű kérdésekhez nem értek, ebben nem a potenciális lag motivált, egyszerűen csak nem éreztem a MC-ba valónak ezt a plugint. Ez a véleményem azóta sem változott, de most már megértem a másik oldalt, skrisz01 szempontjait, miért javasolta, hogy kerüljön be. Pár hónap után én is beadtam a derekam, és nekiálltam.
Azt gondolom, mára már nagyjából átlátom a SF működését, nem a plugin fejlesztésre gondolok, hanem felhasználói szinten, mik a lehetőségek, mit lehet kihozni belőle, hogyan lehet használni, mik a korlátai. Amiket most leírok, nem önös érdekből írom, mert szerintem mindenki számára egyformán érvényes szempontok, aki hasonló területen mozog a SF-ban.
1.) A SF egyik szeletét képezik az androidok. Pl. carbonado gyártás nincs woodcutter androidok nélkül. Sajnálatos módon, a woodcutter androidból nincs uranium hajtású, csak alap kivitelű. Ha lenne empowered változat, ez a pont teljesen okafogyottá válna. Mióta a legutóbbi plugin frissítésnek visszaállították a programmable androidoknál a block of coal üzemidejét, a korábbi 10 perc 20 másodpercről 1 perc 20 másodpercre, így nem nagyon maradt más lehetőség, mint az androidok blaze roddal való üzemeltetése. A blaze rod beszerzésének pedig, amíg nincsenek electric spawnerek, nincs más alternatívája, mint egy kiterjedtebb farm reinforced spawnerekkel. Viszont a hagyományos spawnerek korlátja, hogy 15 blokkos rádiuszon belül kell tartózkodni, hogy működjenek. És ez mind horizontálisan, mind vertikálisan értendő. A kiterjedtebb farm, amit írtam, gyakorlatilag azt jelenti, hogy egy kb. 5*5 blokk területű területen kell lenni ahhoz, hogy minden spawner belül legyen a rádiuszon és működjön. Tehát nem mehetek el máshová, a gyáramon belül, kézzel craftolni, árut pakolgatni, fejleszteni, bővíteni, építeni stb. Ott kell rostokolnom azon az 5*5-ös területen. Még ha a farm termelékenysége a duplája is az androidok mennyiségéből eredő össz fogyasztásnak, ez akkor is azt jelenti, hogy ugyananyi időt kell ácsorognom a spawnerek alatt/fölött, mint amennyi időt a gyáramban, vagy a gyáram környékén, de ezen a területen kívül eltöltök. Tehát, a tényszerű valóság az, hogy amennyi időt aktív tevékenységgel töltök a játékban, pont ugyanannyi időt vagyok kénytelen AFK-val tölteni a blaze farm alatt. Nem a 10 percenkénti pénz miatt, nem szorulok rá... Nem a levédésblokkok miatt, nem szorulok rá... Szerintem senki, aki eljut egy értékelhető SF gyár megépítéséig, nem szorul rá arra, hogy ezek miatt AFK-zzon. Egyszerűen a rendszer jelenlegi követelményei miatt van ez így, és ez a valóság. 
Van-e erre a problémára megoldás? Igen, kettő is.
a.) Empowered woodcutter android - mivel uranium végtelen mennyiségben állítható elő sima dust gyárhoz illesztve, ez teljesen megszüntetné a blaze rod szükségességét, ergo nem kellene blaze farm, ergo nem kellene AFK-zni a blaze farm alatt.
b.) Electric spawner - mivel ez, ha jól tudom, ugyanolyan gép, mint a többi SF gép, nem kell rádiuszon belül lenni, csak az a lényeg, hogy a chunk legyen betöltve, tehát nyugodtan lehetne aktívan tenni-venni a gyárban vagy a közvetlen közelében. Hogy ne legyen mob áradat, és ebből eredő lag, meg kellene oldani, hogy ne legyen kraftolható, csak bizonyos számű reinforced spawnerre lehessen beváltani, gyakorlatilag a meglévő spawnereket váltaná ki, így nem okozna mob többletet.
Amíg ez probléma nincs megoldva, a jelenlegi AFK szabály teljesen rossz, védhetetlen, kb. a lapos föld teória szintjén áll.
2.) A SF másik szeletét képezik az ilyen-olyan gyárak. Értelemszerűen, a dust gyár mindenképpen az alap, hiszen ha nem lehetne készen megvenni az utolsó csavarig mindent mnb124, schmekkels, skrisz01, icecroft stb. boltjában, akkor is ezzel kellene kezdeni, hogy aztán a dustokat felhasználva le lehessen craftolni minden mást. De mivel a warp bolt a SF termékek közül csak a dustokat vásárolja normális formában, így itt, a szerveren ez hangsúlyosan igaz. Ettől függetlenül, az árammal működő gépek, az azokból felépülő gyárak lényege, hogy automatikusan, de lassan dolgoznak. A kézi gyártás, amuális gépekkel, mindenben sokkal gyorsabb. De nem automatikus. Szóval, ha hajlandóak vagyunk szembenézni a valósággal, bármennyire is nem illik az esetlege prekoncepciónkba, az elektromos gyárak lényege, hogy belefektetünk pénzt, időt, energiát, megépítjük őket, aztán "a gép forog, az alkotó pihen", míg a gyár dolgozik, ott AFK-zunk a gyárban, hogy be legyen töltve a chunk, és működjön a gyár. Hiába szeretnénk közben valami mást csinálni, a vadon egy másik pontján építeni valamit, vagy akár csak geominerezni/olajat gyűjteni, nem igazán tehetjük meg, mert ha nem vagyunk ott, eltűnik a chunk, megáll a gyár, amiben benne áll pénzünk, időnk, energiánk.
Van-e erre a problémára megoldás? Igen, legalább egy.
a.) Elvben a SF-ban létezik chunk loader, ha jól tudom, csak itt a szerveren nem elérhető. Szigorú szabályok mellett - 1 ember csak 1-et tehet le - meg lehetne oldani, hogy ne legyenek a SF-ozó játékosok röghöz kötve, a gyárukba bebetonozva, elmehessenek a vadonban kalandozni stb, ergo nem kellene AFK-zni a gyárban.
Azt gondolom, hogy ezt a problémát is meg kellene oldani, mielőtt alkalmazni lehetne a jelenlegi, a jelen helyzetben teljesen rossz AFK szabályt.
És akkor most beszélgessünk a kvázi kompromisszumos javaslatokról. Hogy - a korábban nekem szegezett gyanúsításokat cáfolva - mutassam, hogy nem ragaszkodom bármi áron a saját igazamhoz. Bár ez nem jelenti azt, hogy ne lennék meggyőződva róla, hogy nekem van igazam. :D
Elvben most is van egy olyan funkció, hogy valemennyi idő után azt mondja a játék, hogy "most nem vagy a gépnél". Ebben a státuszban nem jár a 10 percenkénti pénz sem, és gondolom, a levédés blokk sem. Szerintem ennek tükrében végképp nincs értelme arról beszélni, hogy az AFK az ingyen pénz és ingyen levédés miatt lenne probléma. De, ezen túlmenően, ha már mindenáron az okkal vagy ok nélkül AFK-zó játékosok életének megnehezítése a cél, ehhez az időfigyelmeztetéshez lehetne társítani, hogy elrakja a játékost automatikusan az AFK warpra. Mivel azonban az érzékelés nagyon fogyatékos, csak a blokkok lerakása/kiütése, ládák megnyitása és ilyenek számítanak aktív tevékenységnek, a mozgás, vagy SF esetében a megnyitott gépen belüli tevékenység nem, ezen finomítani kellene, pl. eventek miatt. Meg úgy általában is, ha előbb jönne egy figyelmeztetés, mondjuk 1 perccel előtte, akkor nem lenne ebből sem gond, nem lehetne rá panasz.
Az OldVillage-en volt megoldásra nem emlékszem, csak pár hetet játszottam ott, nekem nem jött be, egyéb okok miatt. De a Poma által leírtak alapján, megfelelően beállítva, hogy azért ne kelljen értelmetlen hülyeségeket csinálni, hogy ne érzékeljen AFK-t, ez is jó lehetne. 
Összegezve, a javaslatom: a jelenlegi AFK szabályok azonnali hatályon kívül helyezése, az AFK-t valójában és ténylegesen szükségessé tévő problémák megoldása, majd ezek után értelmes, és automatikusan, objektívan betartatott AFK szabályok alkalmazása, ahol nincs, nem lehet szerepe staff egyéni döntésnek, szubjektív hozzáállásnak, mert jelenleg nem csak a szabály önmagában rossz, hanem az is, hogy minden a staffok mérlegelésén múlik.

**Comment by andris155** [comment]
Chunk loader nincs a Slimefun-ban csak egy extra bővítményében. De az biztosan nem kerül be ahogy az electric spawners sem fog. Nem bír el egy halom spawner-t meg mindenki gyárát egyszerre a szerver, mivel szinte biztos vagyok, hogy az összes gyárnál lenne chunk loader. Az electric spawner-s pedig szintúgy folyamatosan menne mindenhol miközben a játékos éppen nem is farmol. Ennyi sok dolgot, amit elvársz nem bír el egy magon egy processzor sem, és mindig egy egy magon futó játék a Minecraft.

**Comment by Komjatius** [comment]
> Chunk loader nincs a Slimefun-ban csak egy extra bővítményében. De az biztosan nem kerül be ahogy az electric spawners sem fog. Nem bír el egy halom spawner-t meg mindenki gyárát egyszerre a szerver, mivel szinte biztos vagyok, hogy az összes gyárnál lenne chunk loader. Az electric spawner-s pedig szintúgy folyamatosan menne mindenhol miközben a játékos éppen nem is farmol. Ennyi sok dolgot, amit elvársz nem bír el egy magon egy processzor sem, és mindig egy egy magon futó játék a Minecraft.

OK, akkor ezek ne kerüljenek be, az AFK szabály kerüljön ki. Mert a kettő együtt nyilván nem értelmezhető.

**Comment by skrisz0101** [comment]
Slimefun dc-re lehet ötleteket írni.
Pl az uránium meghajtású androidot. 
Asszem van már egy olyan elfogadott ötlet hogy az androidoknak lenne árammal működő verziója, nemtom mennyire kezdhették el. @poma123 

Afk-olni egyáltalán nem kötelező, mindig van valami tennivaló. Mondjuk azt nem tudom mennyire tölti be a chunokat melletted, de nem hinném hogy ugyanabban a chunkbam kell lenned ahhoz, hogy termeljen a gyár @Komjatius

**Comment by Komjatius** [comment]
> Slimefun dc-re lehet ötleteket írni.
> Pl az uránium meghajtású androidot.
> Asszem van már egy olyan elfogadott ötlet hogy az androidoknak lenne árammal működő verziója, nemtom mennyire kezdhették el. @poma123
> 
> Afk-olni egyáltalán nem kötelező, mindig van valami tennivaló. Mondjuk azt nem tudom mennyire tölti be a chunokat melletted, de nem hinném hogy ugyanabban a chunkbam kell lenned ahhoz, hogy termeljen a gyár @Komjatius

A blaze farm a fő probléma, ami miatt muszáj. A sima gyár miatt nem lenne vészes, elvben körbe 4 chunkot tölt be, ha jól számoltam, de már minden be van építve nekem ezen a területen.

**Comment by Ziredus** [comment]
Amúgy valamilyen szinten az AFK az a játék része, és sajátossága, pláne ha slime-fun plugint vesszük bele. Sajnos ez van. Nekem is kvázi ott kellene ücsörögnöm az istentudja hány kemencém elött, hogy legyen pár stack nether téglám, meg kiégetett kövem, mert jelenleg nem tudok haladni a ploton az építkezésekkel, amikkel igazából haladnék szívesen ahelyett, hogy szugerálom a kemencéimet, de ha nincs anyag... Én nem mondom, hogy legyen engedélyezve az afkzás, mert nem megoldás az se, Zerinek igaza van, játszani jövünk fel. Viszont tegyük hozzá azt is, hogy a játékmechanika néha nem ad más lehetőséget, ezt bele kellene venni a megítélésbe. Elvégre a saját korlátainkon belül kell, hogy megoldjuk a problémákat (pl amiket Komja felsorolt). Amit viszont komolyan büntetnék (továbbra is) Az az AFK Machineok telepítése/használata. De ezeket a "szükség afk"-kat nemhiszem, hogy büntetni kéne.

**Comment by poma123** [comment]
> sk: Asszem van már egy olyan elfogadott ötlet hogy az androidoknak lenne árammal működő verziója, nemtom mennyire kezdhették el. 

Semennyire, de főleg azért, mert nincs róla írva semmi részlet.
- Mennyit fogyasszon?
- Mi legyen a receptje? 

Egyébként lehet, hogy realitássá válhat egy saját Slimefun addon a szerverre, és akkor abba tényleg azt rakok bele amit akarok.


Szerintem, ha a staffok szemszögéből nézem, akkor nekem csak azzal lenne problémám, hogy az az eszméletlen sok cargo már nagyon laggoltat. Sajnos ez van. Bekerülésekor még nem épültek ekkora gyárak, így nem is derült ki pontosan, hogy mennyire laggoltat. Abba a jelentésbe bele is írtam, hogy egy tesztidőszakra bekerül a cargo, és ha nem laggoltat akkor bent marad. Ez most odáig fajult, hogy már laggoltatnak a hatalmas cargo-rendszerek. Ennyire van optimalizálva. A fejlesztő nem nagyon csinál vele semmit, többnyire ez a maximuma a cargo optimalizálásának. Szerintem ha csak azok a cargo részek lennének meghagyva, ami tényleg szükséges, kevesebb cargo filterrel (mert az laggoltat a legtöbbet, minden egyes itemet lecsekkol ugye...) akkor talán bent marad a cargo. De sajnos tényleg már játszhatatlan így a szerver, 15-ös tps alatt már kegyetlen.

Szóval, ha a cargo problémája megoldódik, akkor már nem kéne ennyire szigorúan venni az AFK-ot. Nem tudom, hogy kell-e plugin rá vagy sem, de a plugint amit emlegettem tényleg speciálisabb mint a mostani EssentialsX afk feature.

**Comment by SurvivorTheReal** [comment]
Két dolgot fűznék hozzá:
1:Én az életem végéig (valószínű) átkozni fogom a minecraft fejlesztőit hogy nem birják megcsinálni, hogy több magon is futhasson a szerver
2:Poma előző kommentjéhez: azt mondod hogy, az advanced output cargokba tett itemekre külön-külön csekkol minden egyes szállításnál? Ha jól gondolom, akkor, célszerű több cargo rendszert (külön cargo managerek) csinálni? Nálam 3-4 cargo manager és egy darab advanced output se kéne.
Ha így megoldható lenne, akkor úgy ahogy van kivenném az advanced outputot, és olcsóbbá tenném a cargo manager receptjét.

**Comment by poma123** [comment]
> Poma előző kommentjéhez: azt mondod hogy, az advanced output cargokba tett itemekre külön-külön csekkol minden egyes szállításnál? Ha jól gondolom, akkor, célszerű több cargo rendszert (külön cargo managerek) csinálni? Nálam 3-4 cargo manager és egy darab advanced output se kéne.
Ha így megoldható lenne, akkor úgy ahogy van kivenném az advanced outputot, és olcsóbbá tenném a cargo manager receptjét.

Lehetséges, hogy mégis jobban viselkedne külön rendszerekben, de a legjobb lenne ha tényleg csak azok a node-ok lennének használva amik tényleg kellenek, és a felesleges buffer ládákat mellőzni kéne.

**Comment by poma123** [comment]
@Komjatius @skrisz0101 @Ziredus 
Készítettem végül egy saját Slimefun addont, [PomaExpansion](https://github.com/TheOld-Crafters/PomaExpansion) néven. Ebbe bekerültek az alábbi androidok:
- Advanced Programmable Android (Miner)
- Advanced Programmable Android (Woodcutter)
- Empowered Programmable Android (Miner)
- Empowered Programmable Android (Woodcutter)
- Empowered Programmable Android (Farmer)

**Comment by Komjatius** [comment]
> > sk: Asszem van már egy olyan elfogadott ötlet hogy az androidoknak lenne árammal működő verziója, nemtom mennyire kezdhették el.
> 
> Semennyire, de főleg azért, mert nincs róla írva semmi részlet.
> 
> * Mennyit fogyasszon?
> * Mi legyen a receptje?
> 
Javaslat. A programmable androidok ugyanazokkal az üzemanyagokkal mennek, mint a coal generatorok. Tehát gyakorlatilag olyan, mintha az androidban egy coal generator lenne elrejtve. 
Ergo, a kérdésedre a javaslataim:
- a fogyasztása egyezzen meg egy coal generator II termelésével
- a receptje legyen 1 programmable android + 1 coal generator II + 1 big energy capacitor (ezek középső oszlopban egymás alatt) + 4 block of coal (a 4 sarokban) + 2 steel ingot (a coal generator 2 oldalán)

**Comment by poma123** [comment]
Köszi Komjatius, már meg lett csinálva, sk segített. Bekerült a szerverre.

**Comment by Komjatius** [comment]
> @Komjatius @skrisz0101 @Ziredus
> Készítettem végül egy saját Slimefun addont, [PomaExpansion](https://github.com/TheOld-Crafters/PomaExpansion) néven. Ebbe bekerültek az alábbi androidok:
> 
> * Advanced Programmable Android (Miner)
> * Advanced Programmable Android (Woodcutter)
> * Empowered Programmable Android (Miner)
> * Empowered Programmable Android (Woodcutter)
> * Empowered Programmable Android (Farmer)

Hálás köszönet! Mindig nagyszerű, ha valaki rászán időt, energiát, és tényleg tesz valamit, alkot valamit!

**Comment by PinkWizard** [comment]
Nem felesleges az afk szabályzat... 
Ha valaki megépít egy emberfeletti gyárat (egyébként minek akkora?) akkor ott van az a következmény, hogy ott nem lehet afkolni. Múltkor is tesztelve lett, hogy mi történik, ha az összes gyárbánál ott vannak... 
Az meg megint nem normális dolog, hogy ott a gyárad, és azért jössz fel, hogy afkolj mellette. Erre is van példa. 
Amit nekünk staffoknak figyelnünk kell az az utóbbi eset, hogy ha azért jön fel, hogy afkoljon a gyár mellett... ha pl. egyszer kidobja az embert afk miatt, majd feljön, és folytatja az afkot, utánna már nem lehet beleszólása, hogy miért történt ez. 
Szóval NEM, nem kell kivenni ezt a szabályzatot, mert mindenkinek jobb az, ha lagg nélkül, simán fut a szerver... 
Amin változtatni kell az a szabály szigorúsága, amin csökkenteni kell.

**Comment by Komjatius** [comment]
> Nem felesleges az afk szabályzat...
> Ha valaki megépít egy emberfeletti gyárat (egyébként minek akkora?) akkor ott van az a következmény, hogy ott nem lehet afkolni. Múltkor is tesztelve lett, hogy mi történik, ha az összes gyárbánál ott vannak...
> Az meg megint nem normális dolog, hogy ott a gyárad, és azért jössz fel, hogy afkolj mellette. Erre is van példa.
Azért jó látni, hogy a laposföld- és AFK-szabály hívők, illetve a potenciális megoldásokra azonnal, csípőből nemet mondók mellett, legalább egy ember (Poma) van a szerver vezetésében, aki tett is valamit azért, hogy jobb legyen, miközben mások egymással versengve kommentálják, hogy jó ez így, ahogy van. :D

**Comment by MrZero1** [comment]
Erre inkább nem mondok semmit, Komjatius.
