### ISSUE TITLE
Ötlet#2: Bolt - messze van, rosszak az árak, ilyesmi.

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#3862]
**Szerver**: Survival
Szóval, igen, a bolt. Régen jobb volt, oké. A piac nem volt jó, oké. Az új bolt nem jó, oké. 
Legyen GUI, legyen /sell. Legyen. Ki állítja be? 
Megláttam valaki (tudomanevét) Discordos üzenetét, hogy lustaságból nincs GUI, meg nincs időnk rá, bezzeg(!) az AFK-olókat figyelni van. 
Igen, arra van ideje a sok staffnak, Pomának meg Andrisnak meg nincs mindenre végtelen ideje, türelme. 
A bolti árakon meg egy csodatévő kismacska se tudna segíteni, maximum egy teljes restart, normális árakkal. De resit nem akarunk. Én legalábbis nem. A pénzrendszer meg előbb-utóbb tönkremegy. Survival szerver, nem egy városalapítós, ahol tényleg a pénz lenne a lényeg. 
Szubjektív véleményeket, segítséget mindig elfogadunk a bolti árakhoz, de mi sem vagyunk mindenhatóak. 
Ez az az eset, amikor mindenkinek nem tudunk eleget tenni.

Továbbá, ha lenne egy GUI alapú bolt, akkor fix, hogy ennyi eladható-vásárolható dolog nem lenne benne, mint ami most van a boltban. Mert tök felesleges. 
(Meg amúgy is, ha valaminek épp változtatni kell az áron, mert van egy árrés, akkor valakinek elérhetőnek kell lenni, hogy a konfigba átírja.) (szerveren belül módosítható lenne a legjobb...)

🟥 összegzés: sz*rok a bolti árak, tudjuk. Segítsetek.

**Comment by andris155** [comment]
A /sell módosítható a szerveren már elvileg.

**Comment by MrZero1** [comment]
És honnan tudják, mit tudnak eladni vele?

**Comment by Sanszi** [comment]
Szerintem a bolton a nerfek rontottak sokat árazás szempontjából. Pl. a blaze rod ára, brewing stand ára, ghast tear ára.
Másrészről ez a GUI dolog szerintem felesleges. egy /back paranccsal oda vissza tudsz járni az otthon meg a bolt között. Adtam már el 15-20 ládányi itemet anno együltőre, nem zavaró használni a boltot legalábbis szerintem.

**Comment by MrZero1** [comment]
Főleg azok lettek nerfelve, aminél 0 munka árán több ládányi cucc bejön. Ezek a farmok, ahogy te is írtad. 3-5 spawner már igen szép termést hozott. Ezért is írtam, hogy úgysem lesz senkinek jó. 
Lehet drágítani, de azzal nem a kezdőket segítjük, hanem azokat, akik brutális farmokat csinálnak, mert megtehetik.

**Comment by KingDeadZ** [comment]
Ha azért vannak az árak nerfelve, mert valaki időt/pénzt költött a dolgokra, amiből van a farm, az nem jó :D Minimális nerf elfogadható szerintem még így is, hogy valaki pl 50órát beleáldoz egy farmba,és ha ilyen szintű nerfet kap nem jön fel egy hétig, mert elvesztegetett 50óra játékidőt. A mobfarmokhoz nem birok hozzáfűzni semmit, amíg kézileg volt farmolva szerintem balanced volt (oldcuccért no nerf pls) de amióta csak afkolsz, és az androidok rohadt sok mobot megölnek helyetted értéktelen lett konkrétan, mert rohadt nagy mértékben lehet így automatán gyártani, csak afkolni kell hozzá. 

Javasolnám, hogyha minden csak manuálisan farmolható dolog kapna egy buffot pl. ércek (vas,arany és szén kivételével, mivel azt SFel lehet automatizálni) 
Ha valamikor lesz kedvem, felnézek és leírom ide azokat a dolgokat, hogy miket lehet csak manuálisan farmolni. (A növényeket lehetne pl. répa,krumpli,cékla stb, mert az androidnak van egy max kód nagysága ha jól tudom, ami limitálja a hatékonyságát) Ha valaki jelzi felém, hogy lenne igény arra, hogy átnézzem a boltban található dolgokat, hogy mi manuálisan farmolható akkor megcsinálom szivesen.

**Comment by MrZero1** [comment]
> Ha azért vannak az árak nerfelve, mert valaki időt/pénzt költött a dolgokra, amiből van a farm, az nem jó :D Minimális nerf elfogadható szerintem még így is, hogy valaki pl 50órát beleáldoz egy farmba,és ha ilyen szintű nerfet kap nem jön fel egy hétig, mert elvesztegetett 50óra játékidőt. A mobfarmokhoz nem birok hozzáfűzni semmit, amíg kézileg volt farmolva szerintem balanced volt (oldcuccért no nerf pls) de amióta csak afkolsz, és az androidok rohadt sok mobot megölnek helyetted értéktelen lett konkrétan, mert rohadt nagy mértékben lehet így automatán gyártani, csak afkolni kell hozzá. 
> 
> 
> 
> Javasolnám, hogyha minden csak manuálisan farmolható dolog kapna egy buffot pl. ércek (vas,arany és szén kivételével, mivel azt SFel lehet automatizálni) 
> 
> Ha valamikor lesz kedvem, felnézek és leírom ide azokat a dolgokat, hogy miket lehet csak manuálisan farmolni. (A növényeket lehetne pl. répa,krumpli,cékla stb, mert az androidnak van egy max kód nagysága ha jól tudom, ami limitálja a hatékonyságát) Ha valaki jelzi felém, hogy lenne igény arra, hogy átnézzem a boltban található dolgokat, hogy mi manuálisan farmolható akkor megcsinálom szivesen.

Akkor most jelzem, szeretném ha leírnád.

**Comment by KingDeadZ** [comment]
Estefelé felmegyek majd, és átnézem őket

**Comment by andris155** [comment]
Ez a plugin teljesen módosítható a játékon belül. 0 konfig tudás kell hozzá. Ezt sem lenne kedved beállítani inkább a mostani bolt helyett?
https://www.spigotmc.org/resources/ss-dynamic-shop-1-13-1-16.65603/

**Comment by MrZero1** [comment]
Nem rossz, de az elkövetkezendő időkben nem lesz rá időm.

**Comment by SurvivorTheReal** [comment]
KingDead-el értek egyet teljes mértékben, ami manuálisan farmolható (hatékonyan) mint pl az említett növények, azok kapjanak egy kis buffot és az olyan dolgok amikhez a farm építése nagyon sok időt vesz igénybe (a blaze farmok nem ide tartoznak véleményem szerint, igazából csak barangolni kell a netherbe és már talál az ember 4-5 spawnert, mivel a nether nagy része még le sincs generálva, ezért van még bőven spawner)
A növények amúgy tökéletes ötlet mert a farmer androidok elég hasznavehetetlenek. Nem is ad annyit, és csak kis területen lehet automatává tenni.

**Comment by KingDeadZ** [comment]
Lemez buff
Seagrass (ezt lehetne venni is, ha jól tudom nem lehet farmolni automatán, és limitált mennyiségű van egy világban)
Gunpowder (Ezt lehet automatán farmolni, ha valaki android mellett afkol, de mivel nincs spawner, ezért jó lenne egy normálisabb ár)
Tojás nerf
Toll buff
Leather buff
Minimális prizmarin shard és crystal buff
Anvil buff
piston nerf
Gravel nerf
Bookshelf buff
Íj nerf
Arrow nerf
Shield nerf
Az összes fa kaphatna egy kissebb nerfet
Minimális kő nerf
Gombaleves nerf 
Alma buff
Wheat buff
Dinnye nerf
Nyúlláb buff
Arany répa buff
Fermented spider eye buff
Sima spider eye minimális nerf
Ghast tear buff
glistering melon slice buff
magmakrém buff
Az összes sfes dustra nerf és a flask of xpre is nerf (kevésbé érné meg az automata mobfarm, automata sf gyár)
Az összes hús fajtára ráférne a buff
Sima tök eladási lehetőség, és kaphatna buffot is (a carved pumpkin árából ítélve)
Mushroom buff

Ezeket bírtam kiírni, hogy jók lehetnének.

**Comment by skrisz0101** [comment]
Kövek árat hova akarod csökkenteni? Xd
A kezdőket látom eladni a követ leginkább, az ne csökkenjen

**Comment by KingDeadZ** [comment]
A dinnye sokkal többet ad, mint a tök. Ha pl kiütsz 2stacknyi tököt, majd aztán 2stacknyi dinnyét, akkor párszor annyiért birod eladni a dinnyét, mint a tököt.
Ha a spawner ládában vannak passzív állat spawnerek, akkor az bónuszpont szerintem annak, aki vásárol kulcsot hozzá. Magmacube is egy ilyen spawner, ha jól tudom.
Gombaleves op, csak tálakat kell craftolnod, és 1bocit lefejni 900000x, ez is eléggé jó pénzforrás, csak túl aktív, ami nem jó a normieknak h farmolják.
Rohadt sok fát bírnak szedni az androidok + kézzel is sokat lehet szedni nagyon, tekintve hogy létezik a haste poti,haste beacon,mcmmo fadöntés.
Követ szedni is egyszerű, de egyébként főleg az SF miatt nerfeltetném le, mert ténylegesen borzasztó mennyiségben lehet sfel termelni, és így ha nincs feldolgozva,akkor ne is érjen annyit. (Meg ne szedjék annyira szét az egész világot csak azért, hogy pénzt szerezzenek a kőből, tehát nem akarom azt látni hogy egy hegyből csak a követ lebontják azt jóvanazúgy,de ez az egyetlen dolog amire erősebb indokot nem birok mondani)

**Comment by skrisz0101** [comment]
Köveket akkor is csak a kezdők adják el, akik nem old Csákival bányásznak
Akiknek megvan old csákányuk,nnem követ fognak eladni

**Comment by KingDeadZ** [comment]
Eff5 pickaxeval és haste2vel oneshotolod a követ még diapickel is.
Minimálist írtam, ami szerintem rá is férne azért.

**Comment by Komjatius** [comment]
Ki ad még el követ a warp boltban, amikor játékosok is veszik, szerintem jobb áron?

**Comment by Komjatius** [comment]
Amikor a nagy dust gyárak a fő ellenség a szerveren, akkor talán helyénvaló lenne a dust árak nerfelése, de nem egy hirtelen lefelezés formájában, mert az nem lenne korrekt azokkal, akik most kezdtek vagy kezdenének bele, hanem mondjuk első körben levinni mindent a gold dust árára, aztán az iron dust árára, és onnan havonta kb. 10 százalékkal, mondjuk 640 / 64 db árra.

**Comment by lovi-dev** [comment]
az összes mobdropp és SF dust eladását kivenném.    
@"Gunpowder (Ezt lehet automatán farmolni, ": creeper farmból és witchből is jön. Utóbbira  spawner is van
@"farm építése nagyon sok időt vesz igénybe": akinek van annak viszont egyre több lesz és még és még és még...

**Comment by KingDeadZ** [comment]
Az, hogy kiveszed a mobdropokat az nem megoldás, egyébként így is keveset adnak, főleg a gunpowder, pedig az a legmacerásabb. Aki witch spawnert kap, annak lehet hogy jó az a kis plusz pénz, ha már támogatta a szervert (feltételezem hogy nem lehet spawner kulcsot nyitni sehonnan) 

Az sf dust eladása sem annyira megoldás, mert egy idő után nem bírsz vele mit csinálni, főleg azokkal nem, amik csak jönnek jönnek és jönnek, de alig lehet őket felhasználni valamire. Egy nerf jót tenne neki nagyon,mert nagyon sokat lehet abból keresni, az igaz.

Btw, a farm építése csak akkor vesz sok időt igénybe, ha nem spawneres farmot csinálsz, és nincs oldod. Pl. egy guardian farm megépítése azért sok időbe telik, ha nincs old rangod, de szerintem ilyenek miatt nem szabadna az árakat nerfelni, hogy van Old rangod, és könnyebben bírsz farmokat építeni, vagy vannak old eszközeid, amikkel rohadt sok anyagot bírsz szerezni, mert akkor a pvpn kívül szerintem értelmetlen lenne az oldcucc.

**Comment by MrZero1** [comment]
Azért örülök, hogy írnak hozzá az emberek, és látom, hogy nekik sem könnyű téma ez, pedig csak ötletelnek. 😃
Mellesleg Witch spawnert a Slimefunos láda adhat.

**Comment by Ziredus** [comment]
Én az SF árak nerfelése ellen voksolok. Piszok sok grindeléssel, vagy épp relativ nagy költségekkel jár 1-1 komolyabb gyár összerakása, legyen szó Dust gyárról, széngyárról, vagy épp a homok feldolgozókról, melyek ugyebár nem is termelnek akkor ha az ember nincs ott. Továbbá hozzátenném, hogy nem fogja pl a dustok árának csökkenése a Dustgyárakat tömegesen bezárni. Az Advanced Cargo kivételével együtt annyit eredményezne csak, hogy kevesebb új dustgyár készülne, azonban a már meglévö nagy gyárak mérete simán megduplázódna, hogy a hozam szinten maradjon (pl egy 50% os nerf esetén). A dustokra inkább más korlátozást vezetnék be, a gyárak méretét korlátoznám, de ez már átlóg kicsit az Advanced cargo outputokra is. Sajnos volt szerencsém látni olyan gyárakat ahol csak E-grinderből 2 stack volt bekötve... a kérdés, hogy MINEK? Ezt a fajta megalomániát kéne inkább kezelni szerintem, mintsem az SF árakat nerfelni, és ez szerver laggra is pozitív hatással lenne.

**Comment by Zsombec** [comment]
Esetleg,a Dark prizmarin árát csökkenteni kellene,mivel az eladási ára egy 0, viszont nagyon drágán lehet venni a boltban,és ha valaki azzal a alapanyaggal szeretne dolgozni,rendesen belekell nyúlnia a pénztárcájába,mivel hihetetlenül piszkosdrága már csak 1darab stack is.

**Comment by KingDeadZ** [comment]
Támogatom azt, hogy a prizmarin vásárlási árat nerfeljétek.
A gyárak korlátozása nem hülyeség, viszont ahhoz új thread kéne, ha más is így véli.
Mondjuk van az a pár ember, aki rohadt sok géppel dolgozik, hogy FPS nincs ott, azoknak fájhatna.
