### ISSUE TITLE
Ötlet#3: Survival staffok meg a játékoséletmód

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#3863]
**Szerver**: Survi
Ez kicsit inkább a Staffok irányába szólna, de ha már belejöttem...
Szóval, nem kereskedhettek, barátokkal közösen nem építgethettek, ellenben van kreatív jogotok, mindenhol. 
Megoldás: Segítőnek nem lesz kreatívja a vadonokban, telken, csak a flat-en, ha építeni akarna eventet, arénát.

Előnye: Az a “húdenagy” ‘szigor’, hogy ne kereskedhess, meg hogy ne építkezz a haveroddal közösen, nem lenne. A chat figyelése és a további Staffos “munka” elvégzése kötelező lenne.

Hátránya: Nincs kreatív jog, csak flat világban, illetve a Staffos munka lenne a másodlagos, de remélem nem.

Moderátorra nem lenne érvényes ez.

🟥 Nincs összegzés, csak egy gondolat: az utóbbi időben sokkal lazábban kezeltünk mindenféle ezzel kapcsolatos dolgot, sőt, van akitől meg is kérdeztem, hogy szerinte mennyire szigorú ez a rendszer, amire azt válaszolta, hogy egyáltalán nem, neki jó ahogy van. De ha nem, itt a lehetőség leírni.

🟥  mégiscsak van összegzés: semmisejósohasem

**Comment by poma123** [comment]
Pro:
* Anno amikor én voltam segítő (igaz savszigeten) ott csak moderátortól volt és van kreatív jog, nem volt annyira rossz. Egy ideig szokatlan és idegesítő lenne, de szerintem megszokható.

Kontra:
* Bár mondjuk nincs olyan Survival-on lévő kihasználható dolog, amivel a jelenlegi segítők több pénzhez jutnának a kreatív joggal.
* Nem kéne elvenni a kreatív jogot szerintem, maradjon, de tudjanak kereskedni ők is.
* Plusz ugye már nem pénzzel jutalmaznak a staffok eventen, szóval nincs bevételük olyan forrásból, ahonnan a játékosoknak nincs.

Szóval így az én pro/kontrám szerint (vagyis szerintem) nem kellene elvenni a kreatív jogot, maradjon, viszont tudjanak kereskedni is, és ne szoruljon a háttérbe a Staffos munka.

**Comment by poma123** [comment]
Mégjobb ötlet: Egy két féle módváltás a Staffoknak, ahol tudják maguknak logolni, hogy éppen "mit csinálnak".

- Játék-mód
- Staff-mód

Erre két parancs, a Játék-módban csak "játszani" lenne jog, kreatív mód nélkül, büntetni még tudnának. Staff-módban pedig minden máshoz jogot kapnának, amihez alapból van staffként. A módváltási parancshoz egy indokot is kell írni, pl. "Játék", "Eventtartás" "Ellenőrzés" stb.)

Amikor egy staff Játék-módban van, tabon ferdével lenne a neve, amikor pedig Staff-módban, akkor simán a megszokott módon.

Ezen amúgy már OldVillage óta gondolkodom, ott volt nagy probléma, hogy azon izéltek sokan, hogy a staffok is biztos azt nézik hogy xy bázisa hol van. Picit továbbgondoltam azóta. Majd ha lehet írni, véleménykifejtés alattam jöhet!

**Comment by Shryxx** [comment]
Nem azért jelentkezik valaki staffnak, hogy sk féle nub boltokat építgessen. Nem kötelező jelentkezni, de ha valaki megteszi, akkor fogadja el azt a pár EGYÁLTALÁN NEM SZIGORÚ szabályt. Ha pedig valaki kereskedni akar, az ne jelentkezzen staffnak. Nem kötelező :)

**Comment by skrisz0101** [comment]
,, barátokkal közösen nem építgethettek" szabály eddig is volt? Mert ha igen, abban 100% biztos vagyok, h senki se tartott la be. 

sztem nincs szükség ilyen szabályra, ha van ideje, úgyis épít, bányászik, amihez kedve van.
Savon meg csak moditol van krea, modik csak nem élnek vissza a szigetszint érdekében

**Comment by Sanszi** [comment]
Szerintem a Segítők is része lehetnének a gazdaságnak. 
Kereskedés szempontjából nincs más helyzetben egy Segítő egy Oldtól. Mindkettőnek van gm 1 joga, a kreatív korlátozás mindkettőre érvényes, 10 percenként ugyanazt az összeget kapja egy Old rangú mint egy Segítő. Egy random playernek megadjuk ezt a lehetőséget, de egy Staffnak nem, aki valószínűbb, hogy megbízható?
Ezáltal szerintem, amíg a Segítő elvégzi a feladatát és nem a játékra koncentrál nincs vele baj, ha játszik (akár egyedül, akár barátokkal)
Nekem nem nehéz megállni, hogy kereskedjek, vagy másokkal játsszak, de szerintem logikusabb, ha a staffok is kereskedhetnek (ha már egy player rang ugyanannyi benefittel rendelkezik mint a Segítő rang kereskedés, építés szempontjából)

**Comment by MrZero1** [comment]
Igen, volt ilyen, még talán a Don-korszakból, épp ezért is mondtam/írtam, hogy sok mindenen változtatni kell.

**Comment by MrZero1** [comment]
Légyszi ne hasonlítsuk össze a Staffokat az Old játékosokkal.

**Comment by andris155** [comment]
> Mégjobb ötlet: Egy kétféle módváltás a Staffoknak, ahol tudják logolni, hogy éppen "mit csinálnak".
> 
> * Játék-mód
> * Staff-mód
> 
> Erre két parancs, a Játék-módban csak "játszani" lenne jog, kreatív mód nélkül, büntetni még tudnának. Staff-módban pedig minden máshoz jogot kapnának, amihez alapból van staffként. A módváltási parancshoz egy indokot is kell írni, pl. "Játék", "Eventtartás" "Ellenőrzés" stb.)
> 
> Amikor egy staff Játék-módban van, tabon ferdével lenne a neve, amikor pedig Staff-módban, akkor simán a megszokott módon.
> 
> Ezen amúgy már OldVillage óta gondolkodom, ott volt nagy probléma, hogy azon izéltek sokan, hogy a staffok is biztos azt nézik hogy xy bázisa hol van. Picit továbbgondoltam azóta. Majd ha lehet írni, véleménykifejtés alattam jöhet!

Szerintem ez már nagyon túl lenne így bonyolítva. Mindenkinek utána elmondani, hogy az a staff most nem segít, mert éppen játék módban van. Érdekes lenne. :D

**Comment by andris155** [comment]
> Nem azért jelentkezik valaki staffnak, hogy hatalmas boltokat építgessen. Nem kötelező jelentkezni, de ha valaki megteszi, akkor fogadja el azt a pár EGYÁLTALÁN NEM SZIGORÚ szabályt. Ha pedig valaki kereskedni akar, az ne jelentkezzen staffnak. Nem kötelező :)

Ezzel 100%-ban egyetértek.

**Comment by MrZero1** [comment]
Úgy látom, pont az nem írt ide, aki miatt (főleg miatta) lett megírva ez. Lezárom.
A kézikönyvben átírásra fog kerülni 1-2 dolog, de nem nagyon lesz változtatva semmin.

**Comment by bimerboi** [comment]
Zero már lezárta ezt a témát, viszont én azért még hozzászólnék ha lehet...


> 
> 
> Nem azért jelentkezik valaki staffnak, hogy hatalmas boltokat építgessen. Nem kötelező jelentkezni, de ha valaki megteszi, akkor fogadja el azt a pár EGYÁLTALÁN NEM SZIGORÚ szabályt. Ha pedig valaki kereskedni akar, az ne jelentkezzen staffnak. Nem kötelező :)

Nincs sok szabályzat a Staff tagoknak előírva, viszont nem az a probléma hogy nem lehet kereskedni, engem személy szerint az zavart a legjobban, hogy nem játszhatok az ismerősömmel, mindig beszéltem erről Zerinek hogy lehetne-e ezt megoldani, de nem nagyon találtunk ki erre semmit sajna...


> 
> 
> ,, barátokkal közösen nem építgethettek" szabály eddig is volt? Mert ha igen, abban 100% biztos vagyok, h senki se tartott la be.
> 
> sztem nincs szükség ilyen szabályra, ha van ideje, úgyis épít, bányászik, amihez kedve van.
> Savon meg csak moditol van krea, modik csak nem élnek vissza a szigetszint érdekében

Én nem tudok róla hogy ki szegte meg ezt a szabályt, és ki nem, de én annó úgy lettem értesítve hogy tilos mással játszanom együtt, mivel a rangom által "előnyt szerezhetek" és ugyebár az nem nagyon szabad.



> 
> 
> Szerintem, amíg a Segítő elvégzi a feladatát és nem csak a játékra koncentrál nincs vele baj, ha játszik (akár egyedül, akár barátokkal)
> A kreatív mód szerintem maradjon meg, én szeretem használni, ha playerhez megyek oda segíteni, de nem akarok itemet felvenni véletlenül.

Hogyha csak ennyiért maradjon meg a kreatív, az szerintem felesleges... Poma nagyon egyszerűen tudna csinálni egy pl.: "/nopickup" vagy hasonló parancsot a Staff tagoknak, amivel ez elkerülhető lenne. A barátos részre meg kitértem fentebb.
Röviden: Én szeretném ha valahogy ezt megtudnánk valósítani, lehet a többségnek "szüksége van a kreatív jogra" mint Staff tag, "ez kijár, hogyha már Staff tag vagyok", és társai végett, de ez szerintem akkor sem egy eget verő, nagyon fontos dolog hogy ne tudnék nélküle élni Survin... Persze örülnék ha olyan köztes megoldást találnánk, ami mindenkinek tökéletes de mindig valami bökkenő lesz, ami sajnos meggátolja ezt a folyamatot...

**Comment by PinkWizard** [comment]
Lehessen a staffoknak, egy multiacc, csak meg kell indokolni, h minek van, ill. nem lehet itemet átvinni stb... nem szerezhet előnyt abból, h van multiaccountja. Ha valaki túl jutott a próbaidőn, annyi becsülete csak van, hogy nem használja ki ezt.

**Comment by bimerboi** [comment]
@MrZero1 Akkor ez ügyben nem lesz sok változás, vagy bármi ilyesmi?
