### ISSUE TITLE
Lock tábla 

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#3866]
**Szerver**: Survival

Ma már többen jelezték Nekem is, illetve más staffnak is, hogy a [lock] tábla alatt, a név előtt megjelent egy ~ jel, ezáltal nem férnek hozzá a saját tárolóikhoz.

![kép](https://user-images.githubusercontent.com/29709854/90283097-d38a1700-de6f-11ea-9288-e3c2b0316349.png)

Ahogy leütöttem, ezt írta: You have just bypassed a protection of ~hipomix

A játékosnak, ahogy próbált bármit kezdeni vele: 
![kép](https://user-images.githubusercontent.com/29709854/90283159-f0bee580-de6f-11ea-8b84-9078d4e44766.png)

**Comment by andris155** [comment]
Ami már ilyen lett azt csak leütni lehet. De ha újra levédik nem szabadna ilyennek lennie. Ha mégis ilyen lenne az is, amit újra levédtek, akkor mindenképpen nyiss egy új hibajalentést.
