### ISSUE TITLE
Új, érdekes plugin.

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#3867]
**Szerver**: Survival

Eyo, Jaffis vagyok, ex segítő, és arra gondoltam, hogy bekerülhetne, a Brewery nevű plugin, amelyben alkoholos italokat, kávét, és juiceokat lehet főzni, érlelni, desztilállni. Lehetne egy kocsmáros, akitől aprópénzért (Én itt 1000-2000$-ra gondolok, hogy azért mégse ingyen legyen.) meglehet vásárolni az italok receptjeit. Szerintem mégjobban feldobná a szervert, és örülnének neki a játékosok. Amennyire ismerem magunkat, Pomáé lenne a legnagyobb szeszfőzde. ;P 
Köszönöm, ha elolvastad, és, ha bekerül, örök hála. Ha nem, akkor is :P

Üdv: Jaffis

**Comment by skrisz0101** [comment]
és effektet ad egy alkoholos ital, vagy ,,csak dísz"?

**Comment by Jaffis** [comment]
Igen, sk, ad effektet, szédülést, egyes alkoholok mérget, egy kis időre (meghalni nem lehet tőle!). Van benne pl. kávé is, ami regenerációt, és gyorsaságot ad.

**Comment by ketezerhat** [comment]
SZÉTADOM!!!

**Comment by andris155** [comment]
Volt róla már szó régebben, de akkor sem került be. Ennek a lényege, hogy utána részegen járkálsz (effektekkel megoldva). Illetve a chatre hülyeségeket írsz. A chat része biztosan tiltva lenne. Szerintem semmi értelme. Párszor vicces aztán meg is unná mindenki.
