### ISSUE TITLE
A lucky blockos tnt.

### ISSUE THREAD

**Issue by sajtospitypang** [TheOld-Crafters/Minecraft-servers#3868]
<Survival szerver.
<A lucky blockból jövő tnt-k rombolnak nem úgy mint amit simán lerakunk.
![tnt robbantás](https://user-images.githubusercontent.com/69716168/90310744-d0853a00-def4-11ea-860f-b6c83cdd2ef1.png)

**Comment by andris155** [comment]
Letiltottam benne ezt. Holnap betölt a változtatás.
