### ISSUE TITLE
Újraéledés-kapocs

### ISSUE THREAD

**Issue by Shryxx** [TheOld-Crafters/Minecraft-servers#3870]
**Szerver**: Survival

Nem megy. Be van aktiválva, vagy mi, és ha meghalunk spawnra rak.

**Comment by andris155** [comment]
Mi az az újraéledés kapocs?

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/90320216-5b8b2200-df3f-11ea-9423-12791734d048.png)

https://minecraft.gamepedia.com/Respawn_Anchor

**Comment by andris155** [comment]
Látszik, hogy nem magyarul játszom a játékot. Egyébként a spawn prioritásban magasabb szerintem ennél és azért rak oda.

**Comment by poma123** [comment]
Igen, valszeg az EssentialsX a ludas.

**Comment by andris155** [comment]
Egész összetett volt összességében ez a hiba. Holnap betölt a javítás.

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
Nincs Shryxx név a minemarketen.

**Comment by poma123** [comment]
DrBlade
