### ISSUE TITLE
PlotSquared talán kill-road-items beállítással kapcsolatos hiba

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#3872]
**Szerver**: Survival

A telkek közötti úton eltűnnek a dolgok, ha kidobják. 

Teszteltem, nálam is.

Itt a telken dobálom az üveget, a földre érkezik, ahogy kell:
![kép](https://user-images.githubusercontent.com/29709854/90321820-af9d0300-df4d-11ea-9f9e-7566e41dcea3.png)

Itt már a telek közötti úton állok, dobom az üveget, de el is tűnik:
![kép](https://user-images.githubusercontent.com/29709854/90321807-8e3c1700-df4d-11ea-8fc7-2a3e5f173407.png)

**Comment by UDPSendToFailed** [comment]
#3818 (?)

**Comment by andris155** [comment]
Nincs köze hozzá. Más miatt lesz a hiba. Majd tesztelnem kell.

**Comment by andris155** [comment]
javítva
