### ISSUE TITLE
Koordináták kiírása halálkor

### ISSUE THREAD

**Issue by andris155** [TheOld-Crafters/Minecraft-servers#3873]
**Szerver**: Survival, Savsziget

Halálkor a játékosnak küldjön egy üzenetet, hogy milyen koordinátákon halt meg.

**Comment by poma123** [comment]
https://www.spigotmc.org/resources/deathbroadcaster-1-13-x-1-16-x.65752/

Nem éppen arra való ez, hogy csak az adott játékosnak írja ki, de megoldható az is.

**Comment by PinkWizard** [comment]
A /Back parancsal úgy is vissza tud menni, nem?

**Comment by KingDeadZ** [comment]
Vissza, de ha pl. kicrashel v kidobja bármiért, akkor nem bír oda visszamenni, és a koordinátáit sem fogja megjegyezni eléggé nagy valószínűséggel.e

Jó ötletnek tartom, remélem nem lesz vele sok dolga pomának.

**Comment by poma123** [comment]
Bekerült. Ha valamelyik nem tetszik, átírhatod -> plugins/DeathBroadcaster/config.yml

Survival (világok: world2, world114, plotworld, world2_nether, world2_the_end)
példa:
![image](https://user-images.githubusercontent.com/25465545/90332685-36d68f00-dfbf-11ea-87e4-70e5d47c13f6.png)
![image](https://user-images.githubusercontent.com/25465545/90332722-ab113280-dfbf-11ea-8910-02b4ae13e9dc.png)


Savsziget (világok: acidisland_world, acidisland_world_nether, acidisland_world_the_end)
példa:
![image](https://user-images.githubusercontent.com/25465545/90332631-d1829e00-dfbe-11ea-9e52-02ab19fafb85.png)
![image](https://user-images.githubusercontent.com/25465545/90332634-d6475200-dfbe-11ea-8f7b-a15243865257.png)

**Comment by andris155** [comment]
Majd szed ki kérlek. Ez az EssentialsX-ben benne van.

**Comment by poma123** [comment]
Akkor hajrá :)

**Comment by andris155** [comment]
kész
