### ISSUE TITLE
A túl hamar lejárt rang

### ISSUE THREAD

**Issue by sajtospitypang** [TheOld-Crafters/Minecraft-servers#3875]
<Survival szerver
< 07.27-én vettem egy  vip rangot és máris lejért és ez az én véleményem szerint még nem volt egy hónap.

**Comment by andris155** [comment]
sajtospitypang névre nem találtam V.I.P. rang rendelést.

**Comment by poma123** [comment]
cevelien a játékosneve.

**Comment by andris155** [comment]
Hol vetted ezt a V.I.P. rangot?

**Comment by skrisz0101** [comment]
Szavazásból vette, mivel írta hogy 1 hónap

**Comment by sajtospitypang** [comment]
Igen igen szavazasbol vettem.

**Comment by andris155** [comment]
A log alapján 1 hónapja és 15 órája vetted. Tehát az lehetetlen, hogy 07.27.-én vetted volna. Inkább olyan 07.16. körül. 30 napja adja meg egyébként a rangot. Nem 31 napra.
