### ISSUE TITLE
Lock hibák

### ISSUE THREAD

**Issue by Shryxx** [TheOld-Crafters/Minecraft-servers#3876]
**Szerver**: Survival

**Hiba1**: Hozzá vagyok adva a lock táblához, de nem tudom kinyitni.

**Hiba2**: Nincs lefordítva a plugin :(
![2020-08-16_13 07 02](https://user-images.githubusercontent.com/69635280/90332956-9fbf0680-dfc1-11ea-88aa-3e653b15b0e9.png)

**Comment by poma123** [comment]
A fordítást feltettem ide GitHubra, ha valakinek van kedve, küldhet Pull requestet.

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a hibát. Próbáljátok meg újra levédeni.
