### ISSUE TITLE
Griefprevention levédés blokk küldés

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3878]
**Szerver**: Szurvi ~~(OldSpace?)~~

Jó lenne ha át lehetne adni a levédésblokkokat, vettem már vagy 40 milláért levédésblokkot, de nem szeretném minden pénzem erre költeni :D 
Akinek meg nem kell, oda tudja adni akinek kell.

Pomát elkapta egy riporterünk és elmondása szerint 10 perc alatt meg lenne egy olyan parancs. alt2☻

**Comment by poma123** [comment]
OldSpace-re nem kell, mivel ott annyi levédésblokkjuk van mint csillagon az ég. Bolygónként +200 illetve a party bónusz.

**Comment by andris155** [comment]
@MrZero1 neked mi erről a véleményed?

**Comment by MrZero1** [comment]
Multiaccozás miatt nem szeretnék, régebben is volt már erről szó.

**Comment by andris155** [comment]
Régebben is arra a döntésre jutottunk, hogy nem lesz ilyen, és én továbbra is maradnék ez mellett a döntés mellett.

**Comment by UDPSendToFailed** [comment]
/sellclaim azért lehetne :( 

Vagy esetleg egy olyan opció, hogy ha pénzért levédek másoknak, át tudjam adni az owner jogot.

**Comment by skrisz0101** [comment]
Multiacc?
Annyit úgyse tölt egy játékos a multiaccos karakterével, hogy több1000 levédést szerezzen.
10percenkénti pénzt is el tudja utalni a multiaccos karakterének

**Comment by mnb124** [comment]
szerintem legyen.. régi accomonrol áthozást NAGYON megkönyitette volna

**Comment by skrisz0101** [comment]
Mizu?

**Comment by andris155** [comment]
Szerintem bekerülhet ha ennyien akarják.

**Comment by poma123** [comment]
Elkészültem vele, várom a végső megerősítést, hogy bekerüljön-e.
- Parancs: /transferclaimblocks <játékos> <mennyiség>
- Minimum limit: 150 blokk, tehát ennél kevesebbet nem lehet küldeni
- Maximum limit: nincs
- Küldéskor először a bónusz levédésblokkokból vonja le amennyit tud, utána pedig az accrued/játékidős levédésblokkból. Átvitelkor a cél játékosnak a bónusz levédésblokkjai közé kerülnek az átvitt levédésblokok.
- Lines of code: ~130

**Comment by MrZero1** [comment]
Én továbbra sem szeretném, de nekem ilyenekbe nincs beleszólásom.

**Comment by poma123** [comment]
Miért ne lenne beleszólásod? Dehogynincs. Ezért írtam a legutóbbi komment elején, amit írtam.
Milyen feltételekkel lenne szerinted jó? Ha a multiaccot akarjuk kiküszöbölni, lehet több a minimális limit, esetleg egy játékidős feltétel, hogy csak 1 óra játékidő után lehessen küldeni. Ilyennel se lenne elfogadható?

**Comment by MrZero1** [comment]
Tök mindegy, Én mit javaslok, vagy mondok, az úgysem jó. 
Legyen amit írtak fentebb

**Comment by poma123** [comment]
Akkor rakok rá egy játékidő limitet is.

**Comment by poma123** [comment]
Bekerült.

Parancs: /transferclaimblocks <játékos> <mennyiség>
Minimum játékidő: 1 óra játékidő szükséges a parancs használatához.
Minimum limit: 150 blokk, tehát ennél kevesebbet nem lehet küldeni
Maximum limit: nincs
Küldéskor először a bónusz levédésblokkokból vonja le amennyit tud, utána pedig az accrued/játékidős levédésblokkból. Átvitelkor a cél játékosnak a bónusz levédésblokkjai közé kerülnek az átvitt levédésblokok.
Lines of code: ~130
