### ISSUE TITLE
Slime-fun Egyedi gép javaslat

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#3879]
Survival szerver
Slime-fun Plugin bövités

Kellene egy olyan gép a Slime-funba mely képes a sima Terrakotta blockokat betörni, homokká, avagy vörös homokká. a Müködési elve ugyanaz lenne mint az electric ore grinder-nek.
Haszna: Jelenleg a dust gyártás során az egyetlen olyan anyag amely hulladékként végzi az az agyag. Ezzel a géppel azonban a hasznosítása megoldhatóvá válna.

**Comment by skrisz0101** [comment]
Szerintem egy receptként lehetne egy rakni e-ore grinderbe

**Comment by Ziredus** [comment]
Az is egy teljesen jó megoldás persze, csak nemtudom melyiket egyszerübb kivitelezni. Berakni oda, vagy berakni egy "butított grinder" ezzel a recepttel.

**Comment by andris155** [comment]
A Slimefun-hoz ötleteket a Slimefun Discord szerverén lehet írni angolul: https://discord.gg/fsD4Bkh
