### ISSUE TITLE
Csalásvédelem - Paci, hajó

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3880]
**Szerver**: Szurvi

Ha lovon lovagolok, random ledob és bebuggolok. 

Csónakba ha beülök, néhaú gy érzékeli hogy bent se vagyok. random kicsúszik a csónakból és szintúgy bebuggolok.

**Comment by VdszHun** [comment]
Volt már egy hasonló hiba az Álomfutóval (Strider) nem?

**Comment by andris155** [comment]
Szerintem ez a cargo miatta folyamatos szerver lagra vezethető vissza. Erre nincs így megoldás szerintem.

**Comment by andris155** [comment]
A tesztek is igazolták. A cargo-val meg nem tudok mit kezdeni.
