### ISSUE TITLE
Cargo "optimalizáció"

### ISSUE THREAD

**Issue by poma123** [TheOld-Crafters/Minecraft-servers#3881]
**Szerver**: Survival, Savsziget

~~Ki lesz véve a whitelist/blacklist mód, nem lehet majd itemeket beletenni oda középre.~~
Ki lesz véve az Advanced Cargo Node (Output), csökkentve a lagot. Az esetek 80%-ban abban van a legtöbb filter használva. A Cargo Node (Input) pedig marad, a filterrel együtt.

A régi Advanced node pedig bekerül a beváltóhoz, 2 sima Outputra lehet majd cserélni.

**[Klikk ide az összefoglalóért](https://github.com/TheOld-Crafters/Minecraft-servers/issues/3881#issuecomment-675396935)**

**Comment by andris155** [comment]
Egyébként, ha nyitsz optimalizációs javítás pull-t a cargo-hoz, ami nem változtat a működésén szerintem biztosan elfogadnák.
Ezt amit pedig írtál, ha megoldanád, hogy konfig beállítással lehessen kapcsolni szerintem akár ezt is elfogadnák.

**Comment by poma123** [comment]
Nem fogadnának el semmi ilyet.

**Comment by Komjatius** [comment]
> ~Ki lesz véve a whitelist/blacklist mód, nem lehet majd itemeket beletenni oda középre.~

--> ez teljesen használhatatlanná tette volna a cargot


> Ki lesz véve az Advanced Cargo Node (Output), csökkentve a lagot. Az esetek 80%-ban abban van a legtöbb filter használva. A Cargo Node (Input) pedig marad, a filterrel együtt.

--> ez csak megbonyolítja a cargot, jó alaposan, rengeteg plusz buffer és cargo node kell majd, és teljesen újjá kell építeni mindent a nulláról, de aki szereti a kihívásokat... viszont 16 channel így nagyon karcsú lesz... nem lehet azt feltornászni? OK, nincs végtelen színű gyapjú, de valahogy. Ha nincs advanced output, egy adott gyáron belül minden itemnek külön csatorna kell majd, és a szétválasztásoknak pluszba külön csatorna kell... Egy jól összerakott dustgyárban van cobblestone, gravel, sifted ore, flint, clay ball, iron nugget, 9x dust, clay, terracotta, iron ingot. Ez alapból 18 item, 18 csatorna. A szétválogatás a több kimenetes gépek miatt, mivel egy ládára nem lehet végtelen mennyiségű cargot rakni, még hozzáad pár csatornát. Kb. így:

channel 01 - felvásárló láda -- (cobblestone) -> buffer01
channel 01 - cobblestone gen -- (cobblestone) -> buffer01
channel 01 - press -- (cobblestone) -> buffer01
channel 02 - buffer01 -- (cobblestone) -> ore grinder
channel 03 - ore grinder -- (gravel) -> buffer02
channel 04 - buffer02 -- (gravel) -> gold pan
channel 05 - gold pan -- (sifted ore, flint, clay ball, iron nugget) -> buffer03
channel 06 - buffer03 -- (sifted ore) -> buffer04
channel 07 - buffer03 -- (flint) -> buffer05
channel 08 - buffer03 -- (clay ball) -> buffer06
channel 09 - buffer03 -- (iron nugget) -> buffer07
channel 10 - buffer04 -- (sifted ore) -> dust washer
channel 11 - dust washer -- (9x dust) -> buffer08
channel 12 - buffer08 -- (iron dust, lead dust, copper dust) -> buffer09
channel 13 - buffer08 -- (gold dust, silver dust, aluminum dust) -> buffer10
channel 14 - buffer08 -- (tin dust, zinc dust, magnesium) -> buffer 11
channel 15 - buffer09 -- (iron dust) -> buffer12
channel 15 - ore grinder (iron dust)-> buffer12
channel 16 - buffer09 -- (lead dust) -> buffer13
channel 17 - buffer09 -- (copper dust) -> buffer14
channel 18 - buffer10 -- (gold dust) -> buffer15
channel 19 - buffer10 -- (silver dust) -> buffer16
channel 20 - buffer10 -- (aluminum dust) -> buffer17
channel 21 - buffer11 -- (tin dust) -> buffer18
channel 22 - buffer11 -- (zinc dust) -> buffer19
channel 23 - buffer11 -- (magnesium) -> buffer20
channel 24 - buffer05 -- (flint) -> press
channel 25 - buffer06 -- (clay ball) -> press
channel 25 - buffer06 -- (clay ball) -> furnace
channel 26 - press -- (clay) -> furnace
channel 27 - furnace -- (terracotta) -> buffer21
channel 28 - furnace -- (brick) -> buffer22
channel 29 - buffer07 -- (iron nugget) -> press
channel 30 - press -- (iron ingot) -> ore grinder

És akkor még nem vettünk ki a rendszerből sifted ore-t, hogy átmenjen az uranium gyártásba... 

Lehet, hogy fejlesztői oldalról ez jó ötletnek tűnik, de mielőtt fejlesztői oldalról alapvető változtatásokat eszközöltök, előtte építsetek tesztgyárakat, ahol ki lehet próbálni, hogy ezek a változtatások mivel fognak járni, szóval értsétek meg felhasználói oldalról is.

**Comment by poma123** [comment]
Ahogy mondtam, holnap lejátszátok sk-val.

**Comment by lovi-dev** [comment]
Automatad crafting chamber és az electric smeltery ezek után 3nál több komponnesel automatán nem lesz használható.
Tárgyak szétosztására sokkal több filterres inputnode fog kelleni, smit eddig megoldott a adv. output azt most kvázi rendezési algoritmusokkl kell megoldani. pl. 9 itemenként egy fa.
Sokkal nagyobb, több és bonyolultabb cargo rendszereket fog eredményezni rengeted (2-4 cargo redenszer közti) item átadó ládákkal. 
Ugyan az az alapanyag sokkal többet fog mozogni.

**Comment by skrisz0101** [comment]
Vagy így, vagy sehogy. Régebben kaziki egy reinforced gyárat hozott össze sima cargokból, menni fog az :D. Jobb megoldás mint a cargo kikerülése, nem?

**Comment by SurvivorTheReal** [comment]
Vhogy éreztem, hogy ez sok embernek nem fog tetszeni. Már többet kell gondolkodni a cargon...
Oszt mivan abba?
Bent marad! *kitörő taps és extázis

**Comment by Komjatius** [comment]
> Vagy így, vagy sehogy. Régebben kaziki egy reinforced gyárat hozott össze sima cargokból, menni fog az :D. Jobb megoldás mint a cargo kikerülése, nem?

Nem, nem jobb, mert nem megoldás.

**Comment by Komjatius** [comment]
Két legyet egy csapásra... Úgyis sokak szemét szúrtam a szerveren... Hát így majd nem fogom. :D

**Comment by poma123** [comment]
Akkor mit ajánlasz? Csak mert más lehetőség nincs.

**Comment by skrisz0101** [comment]
@Komjatius így is lehet gyárakat csinálni, csak lagg nélkül. ennyi az egész. +jobban át kell gondolni hogy mit merre, azt hittem szeretsz gondolkodtató feladatokat megoldani :(

**Comment by Komjatius** [comment]
> @Komjatius így is lehet gyárakat csinálni, csak lagg nélkül. ennyi az egész. +jobban át kell gondolni hogy mit merre, azt hittem szeretsz gondolkodtató feladatokat megoldani :(

Szeretek, fent le is írtam... Mellőzhető az advanced output, csak akkor dupla channel kellene. Tudom, erre azt mondjátok, legyen két cargo manager, két rendszer, egyikből átdobva mindet a másikba, nekem így jönnek át a dustok pl. Angi gyárából, szóval tudom, hogy működik... Ha akarod, ahogy fent, azt is levezetem neked, megoldom a gondolkodtató feladatot, itt fejben rögtön. Csak ez nem azt jelenti, hogy a valóságban is akarok ezzel rollerezni azon a bizonyos rolleren.

**Comment by skrisz0101** [comment]
ha lehetne több csatornát állítani, lenne több állítva, de nem lehet

**Comment by poma123** [comment]
- Több csatornát nem lehet állítani. 
- Sajnos ez az egyetlen módja részemről, hogy megoldjuk a cargo lagot.
- Még mindig jobb, mintha ki lenne véve az egész cargo...
- Le lett tesztelve, letiltás után még működik minden, manuálisan kell kiütögetni az Advanced output node-kat, amire majd megkérek mindenkit, hogy tegye meg.
- Az előző pontnak köszönhetően a reaktorok se fognak felrobbanni.
- Biztosan több lesz a sima output node (narancssárga), de mivel nincs benne filter, nem fog laggoltatni. Az input node-ból (kék) pedig lehet több, ha nem lesz annyi mint az Advanced output nodeból.

**Comment by andris155** [comment]
Tehát gyakorlatilag semmi se fog változni mert úgy se üti ki senki. Max az a pár ember akiről tudjuk, hogy van cargo rendszere. :D

**Comment by lovi-dev** [comment]
>  úgy se üti ki senki.

kb 40-et már kiütöttem, ugyanannyi filteres input lett helyette.
Item rendezőnél rosszabb lesz ez az arány... (vagy redstone, ha az járható út?!)

**Comment by skrisz0101** [comment]
@andris155 akkor majd leüti egy admin, ha rosszalkodik és nem üti le :D

**Comment by poma123** [comment]
Kedves @andris155, ha nem ütik le mondjuk 1 hét múlváig, akkor végigmegyek az összesen és kiütöm... Miért kell izélni?

**Comment by Conaniwnl** [comment]
Nem tudom, ez érinti-e a savszigetet (az elején meg van jelölve). Szerintem savszigeten nem kellene még kiszedni azért mert survivalon lag van. Savszigeten egyáltalán nem tapasztalható lag, ebből kifolyólag annak a pár embernek - nagy részben régi játékosok - akik használják szerintem meg maradhatna.  Új járékosok nem igazán használják a SF-et bármilyen formában, így nem fenyeget a veszély, hogy bárki AOutput-al szeretné kipakolni a szigetét (ha ez bekövetkezne elég lenne akkor cselekedni szerintem).

**Comment by Komjatius** [comment]
> > úgy se üti ki senki.
> 
> kb 40-et már kiütöttem, ugyanannyi filteres input lett helyette.
> Item rendezőnél rosszabb lesz ez az arány... (vagy redstone, ha az járható út?!)

Ezt mondtam elejétől kezdve. Az advanced output lényege, hogy borzasztóan leegyszerűsíti a cargot. Ez nem csak azért jó, mert egyszerűbb megépíteni a rendszert, hanem azért is, mert egy nagyságrenddel kevesebb cargo node kell. Ahogy nagyjából lejátszottam fejben, hogyan építeném meg a rendszert (nem fogom megépíteni, befejeztem a TOC-en), 3 cargo manager kellene csak a dust gyárhoz, és legalább 3x annyi filterezős cargo node, mint most, annyival több input kellene.

**Comment by poma123** [comment]
Igen, annyi kell amennyi kell, de legalább nem lagol ez a szerencsétlen szerver...

**Comment by lovi-dev** [comment]
dust rendező ( gyár=>szétválogtva ládába ) esetén, 9 adv. output-ot 10 input és 11 output valamint +10 csatornával sikerült kiváltani
9 entitásra van rövidebb rendezési megoldás?

**Comment by skrisz0101** [comment]
A dust szortírozásra sajna nincs jobb ötletem.

**Comment by SurvivorTheReal** [comment]
Ma vagy holnap felmegyek és kiütöm amit ki kell, mert a gyáram fut ha valaki sk boltjába megy. Újraépíteni majd, max szeptemberben.

**Comment by andris155** [comment]
Kitörlöd majd az adatbázisból aztán kész. Nem kell végig menni.

**Comment by poma123** [comment]
Jövőhéten hétfőn délután ki lesz törölve az adatbázisból az összes Advanced Cargo Output. Addig van időtök kiütni őket, és beváltani a /warp beváltó-n sima ouput-ra.

**Comment by schmekkels** [comment]
az mnb hibája az egész
