### ISSUE TITLE
Spawner dropp elektromos gép vagymi

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3882]
**Szerver**:szurvi(sav) 

MNB ötlete, nekem nagyon megtetszett
Egy elektromos gép, amibe spawnert kell rakni, és akkor a spawner mobjának a droppjait termeli természetesen áramból

Nagy előnye, hogy így nem kell Megidézni a mobot, hogy majd utána megöld (vagy megölesd 100 féle módon),  gondolom nem tesz jót a szerónak a sok mob, ezzel talán kicsit segíteni is lehet ezen.

Saját ötlettel kiegészítve: bele lehetne rakni egy EXP collectort (azt csinálja, hogy a lebegő XP-t XP palacká alakítja át) ebbe a gépbe, és akkor XP potit is gyárt 
Akár a receptbe, vagy a gépen bellül egy részre 

Ezt az egészet meg lehet oldani a szokványos módon, de így szerintem laggmentesebb lenne az egész. (spawner mobfarm, android, stb) 

És ez ugye nem csak 16blokkig ér el, ezáltal nem kell mellette Afk-olni *kacsint*

Azért nem sf githubra írtam, mert mire azt megszavazzák (ha megszavazzák), el fogadják, és esetleg meg is valósítják, az sok idő (szerintem)
PomaExpansionba gondoltam,és ha az sf fejlesztőnek tetszik,akkor sima sf-be

@poma123 remélem tetszik az ötlet :D.    
Ja és szeretünk ❤️

**Comment by mnb124** [comment]
Imádlak sk.

**Comment by Komjatius** [comment]
Támogatom, egy próbát mindenképp megér, hogy berakjátok ezt, kiszedünk minden spawnert (bár én már éppen ott tartottam, hogy majdnem minden androidot lecseréltem már, szóval az egész spawneresdi fölöslegessé vált), és akkor megnézni, javul-e a helyzet és mennyit, kell-e a cargot és mennyiben butítani.

**Comment by poma123** [comment]
Sajnos a cargo laggját ez nem oldja meg.
