### ISSUE TITLE
Nem működnek a szavazási linkek

### ISSUE THREAD

**Issue by sajtospitypang** [TheOld-Crafters/Minecraft-servers#3883]
<Survival szerver
<A szavazáshoz kapott linkek nem működnek legalábbis nem lehet őket megnyitni.
Mert nincs előttük a https://
![image](https://user-images.githubusercontent.com/69716168/90365703-7f955300-e066-11ea-9002-918c3be72369.png)

**Comment by skrisz0101** [comment]
Hogy lehet ilyen undorító chattel játszani? Xd

**Comment by sajtospitypang** [comment]
Undorító vagy te sk 🥰

**Comment by andris155** [comment]
javítva
