### ISSUE TITLE
Savsziget: Slimefun-os küldetések

### ISSUE THREAD

**Issue by szofogado** [TheOld-Crafters/Minecraft-servers#3884]
Savszigeten bekerülhetnének slimefun-os küldetéseket, amivel az új játékosok is megérthetik, hogy mivel kezdjenek, mit csináljanak elsőre. Úgyanúgy lehetne olyan küldetés ami azt kéri, hogy legyen meg egy tárgy, Meg lehetne olyan is ami azt érzékeli, hogy van e körülötted olyan block amit kért a küldetés. Szerintem nem kell értékes jutalmat adniuk. már az is elég, hogy tudni fogják mit mi útán kell csinálni.

**Comment by andris155** [comment]
A Slimefun egy extra dolog, és nem a savsziget játékmód része. Nem mindenki használja. Inkább nem szeretnék ehhez küldetést.
