### ISSUE TITLE
Slimefun - RestrictedCreative GUI hiba

### ISSUE THREAD

**Issue by Shryxx** [TheOld-Crafters/Minecraft-servers#3885]
**Szerver**: Survival

Edit by poma:
Amikor kreatívban rámegy egy játékos a GPS Activation Device-re, akkor megnyitna egy GUI-t, de ugye kreatívban letiltja. Viszont a Slimefun úgy érzékeli, hogy megnyitották a GUI-t, így ilyenkor minden klikkelést letilt az invben. Ezt egy másik gui megnyitásával (pl /rangok) túléló módban lehet fixelni, de jó lenne, ha a RestrictedCreative be is zárná a GUI-t letiltáskor, nem csak megszakítaná az InventoryOpenEventet.

![image](https://user-images.githubusercontent.com/69635280/90399714-b174dc80-e09b-11ea-8d5c-4ea73f21edca.png)

**Comment by poma123** [comment]
Valamelyik gui cucc bugolt be valszeg, azt hitte guiba klikkel. Megnyitotta a /rangok-at és utána jó lett. Ha valakinek újból előjön nyisson új jelentést.

**Comment by andris155** [comment]
Ne menjen rá a játékos kreatívban. Ez a megoldás rá.
