### ISSUE TITLE
Slimefun GPS teleportálás

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3888]
**Szerver**: Szurvi, (sav)

Ha a gps rendszerrel teleportálunk egy gps pontra, akkor mindig south fele nézünk, nem számít merre fele néztünk mikor letettük a gps pontot. 

/Pwarp, home, stb mind nézi hogy merre fele néztünk mikor letettük a homet, pwarpot.
Ilyennek kéne lennie a gps rendszernek is

**Comment by poma123** [comment]
Akkor csak a koordinátát menti le, nem tudom direkt-e.

**Comment by poma123** [comment]
Sajnos nem lehet ezzel mit kezdeni, mivel a lerakott Market Tool helyét menti le, ami nem tartalmaz elforgást és dőlésszöget.

**Comment by andris155** [comment]
De ez most hiba, vagy direkt ilyen vajon?

**Comment by poma123** [comment]
Direkt ilyen.

**Comment by poma123** [comment]
Most mivan? Egy blokk location objectjének honnan a rákból legyen elfordulása és dőlésszöge? A Marker Tool egy blokk, az kerül lerakásra, és annak a helye kerül lekérésre... Most mit magyarázzak még ezen, @andris155?

**Comment by andris155** [comment]
Az van, hogy eléggé utálom ahogy a Slimefun fejelsztője kezel mindent ami szerinte nem hiba. Most ennél persze írhatnék Discord-ra ahol ha jól emlékszem még meg is kell szavazniuk a tagoknak, hogy egyáltalán foglalkozzon vele a fejlesztő. Gyakorlatilag ha nincs valami eszméletlen jó ötleted hozzá meg se nagyon érdemes írni.

**Comment by poma123** [comment]
DE ez nem hiba........ így működik a Minecraft, a Spigot API, stb, soroljam még? Akkor leírom megint, remélem érthetőbben...

Redstone Torch item -> Lerakás -> Event megszakítása -> Lerakás helyének lekérése (Location.class) -> Location lementése a GPS-ek közé.

Mivel a Block.class -nak kértük le a Location.class-át, ezért észak felé fog nézni, ha valakit odateleportálunk, mivel a blokk nem játékos... yaw = 0.0 és pitch = 0.0. Miért? Azért, mert Blockról beszélünk, nem állatról, nem játékosról, nem repülőgépről, stb...
