### ISSUE TITLE
Pénz küldés letiltás cucc

### ISSUE THREAD

**Issue by Shryxx** [TheOld-Crafters/Minecraft-servers#3889]
**Szerver**: Survival

A /payon és /payoff üzenetie felcserélődtek, ugyan azt csinálja a két paranc, csak nem jól küldik az üzenetet.
![image](https://user-images.githubusercontent.com/69635280/90500109-bb094d80-e14a-11ea-91ed-94d563fbcf51.png)
Az elsőt a /payonra írta
A másodikat a /payoffra

**Comment by andris155** [comment]
Maga a fordítás helyes. Valahol az EssentialsX-ben van a hiba. Használd a /paytoggle parancsot inkább.
