### ISSUE TITLE
Csalásvédelem - visszadobálás

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3893]
**Szerver**: szurvi biztos, többi nemtom

Hiba: Visszadobál
Mikor? Random, teljesen random
Az előbb pl ferdeház eventen több játékost is random visszadobott 10 blokkal, 5 blokkal, vagy csak épp egy pár mp megállás, ami csak kell egy eventre. 

Eléggé irritáló, sokszor előfordul

**Comment by andris155** [comment]
Hétfőn, amikor poma kitörli az összes Advanced Cargo Output-ot az adatbázisból, akkor meg fog oldódni szerintem.

**Comment by poma123** [comment]
Nem lagol már a szerver, nem amiatt rossz.

**Comment by andris155** [comment]
Akkor se tudok ezzel mit kezdeni sajnos. A lightengine miatt vannak esetleg megakadások. De arra nincs megoldás egyelőre. Talán az új verzióban jobb lesz, csak az meg még nem stabil.

**Comment by Shryxx** [comment]
Prémium pluginugye

**Comment by andris155** [comment]
Attól, hogy valami prémium nem lesz tökéletes sőt még talán több is benne a hiba, mert sokkal kevesebben használják.

**Comment by Shryxx** [comment]
Hát akk addig nem futunk vagy nemtudom
