### ISSUE TITLE
Jármű plugin

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3894]
**Szerver**: Szurvi, (sav)

Már egy ideje fejlesztették 1.16-ra, szóval szerintem simán bekerülhetne.
Minemarketet tuti sokan vennék xd -> több mani
De akár lehetne beváltóban alapabb jármű + A drágább ládákban közepesen jó 
Vagy akár voteshop-ban is 1db
ahogy áttam, bővítették a  járműveket pár darabbal, tuti bírnák a játékosok :D

https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/

**Comment by andris155** [comment]
Nem fog továbbra sem bekerülni. Így is túl sok plugin van már.

**Comment by skrisz0101** [comment]
:(

**Comment by Shryxx** [comment]
haha

**Comment by skrisz0101** [comment]
Hirdetés plugint feláldozhatjuk érte
