### ISSUE TITLE
Slimefun - kikerült slimefun cuccok

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3896]
**Szerver**: Szurvi, sav

Sorban írom a cuccokat, amik visszakerülhetnének, vagy hogy mik a hibák. a hibákat lehetne jelenteni, ha nem volt.

Weapons: 
Blade of Vampires: Úgy emlékszem azért került ki, mert más levédésén is tudtak vele  állatokat ütni (szólj ha nem emiatt).  Na, ezt javították, teszteltük a teszt szerón 
Telken nem tudom hogy előjött-e ez a hiba, de teszt szerón nincs telek:(

Seismic Axe: Úgy emlékszem ez is emiatt került ki, ezzel se tudtam állatokat sebezni más levédésén

Basic machines:
Table saw (Krea hiba): Ha kreában fával jobb kattolunk rá, megadja a fát

Automated panning machine (Krea hiba) Ha sóderrel jobb kattolunk rá, megadja a shifted oret, stb-t

Industrial miner és advanced insdustrial miner: (Krea hiba): Kiszedi a kreás érceket is.

Cruciblet egyszerűen nem tudtam hogy működik, de szerintem ennek is megvan a krea hibája

Block placer: Nem emlékszem miért került ki ':D

Tools:
Lumber axe: erre se emlékszem, hogy mi miatt került ki ':D

Expo csáki: a csákány maga és a Robbanás kiüti a kreás érceket, köveket is
Expo ásó: Az ásó maga és a  robbanás kiüti a kreás földeket, sódereket (ami nem nagy probléme szerintem)

Pickaexe of the seeker: Kiüti a kreás érceket
Pickaxe of vein mining: Kiüti a kreás érceket

Addonok:
Mobcapturer: Levédésen (és telken) be lehet velük fogni az állatok
(nem rémlik hogy jelentve lett-e volna)

**Comment by andris155** [comment]
Mindegyikről tudok mindent. Ezen én nem értem mi a hiba.

**Comment by andris155** [comment]
Amivel kapcsolatban nincs hiba vagy javításra kerül az értelemszerűen visszakerül. De ezek nem hibák, hanem szándékosan lettek kivéve/letiltva a dolgok.

**Comment by andris155** [comment]
A Blade of Vampires egyébként nincs is tiltva. Szóval azt nem is értem miért írtad bele.

**Comment by andris155** [comment]
Korábban már amúgy foglalkoztam ezekkel és minden hiba lett jelentve. A Block Placer került javításra legutóbb, azt reggel már engedélyeztem majd holnap lesz elérhető. A savszigeten ez viszont továbbra sem lesz elérhető, mert a szigeten kívülre is lehet vele blokkokat rakni.

**Comment by andris155** [comment]
Szintúgy nem lesz elérhető az Android sem a savszigeten, mert a szigeten kívülre is kitud menni.

**Comment by andris155** [comment]
A telkeken majd lesz Android, ha megjelenik az új CS-Corelib verzió, amiben van javítás elvileg. De majd tesztelni kell.
