### ISSUE TITLE
Tab - RGB prefixek

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3909]
**Szerver**: Mindenhol

Nem tudom hogy ez direkt, vagy sem, de tabon nem RGB-sek a rangok

**Comment by andris155** [comment]
Van rá sokkal jobb plugin egyébként, amit már régebben is néztem. Sőt igazából 2 plugint is helyettesít egyben. Csak időm nem volt rá egyelőre, hogy ezzel foglalkozzak.

**Comment by andris155** [comment]
Beraktam az új plugint, ami egyben a Titlemanager-t és Nametagedit-et is helyettesíti. A hex színkódokat teljesen támogatja.
