### ISSUE TITLE
Slimefun Tárgy eltörlő androdidok

### ISSUE THREAD

**Issue by szofogado** [TheOld-Crafters/Minecraft-servers#3912]
Savszigeten miközben írtam az androidnak a szkriptjét aközben az 1-es számmal véletlenül be tettem a kardomat az üres mezőre. (ahol még nem volt neki feledat) Majd aztán bezártam és eltünt a kardom. Bármilyen itemet be lehet oda tenni a számok használatával. Bármelyik androdidal működik. 
Savszigeten teszteltem le és savszigeten vettem észre. (nem tudom, hogy survalon is működik-e)

Link a videóhoz: https://www.youtube.com/watch?v=ScuFkrZqqRg

**Comment by andris155** [comment]
poma javította a hibát, pár napon belül bekerül a szerverre is a javítás.
