### ISSUE TITLE
Piston addolás

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3916]
**Szerver**: Survival

Ha egy levédés szélénél aktiválok egy kreás piston-t, felrobban és kidobódik itemként.
Nyomólapot rakva a piston újtába elég gyorsan farmolható:

https://youtu.be/xGFKJ9q95HE

Edit: Fáklyákkal, karral, gombokkal, és egyéb krea plugin által védett blokkokkal is működik.

**Comment by andris155** [comment]
Már jelentett hiba, csak a megoldás a piston check letiltása volt régen. Viszont az előző jelentés alapján ugye ez nem egy jó megoldás. Így most a kreatív plugin fejlesztőhöz fordultam ezzel. Ha lesz javítás akkor 30-60 nap. De szerintem sajnos erre nem várható javítás.

**Comment by andris155** [comment]
508 OCD
