### ISSUE TITLE
Luckyblock - Telek

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#3918]
Survival
A kép megmagyarázza a problémát
![2020-08-23_15 34 51](https://user-images.githubusercontent.com/38157910/90979588-5ab54a00-e556-11ea-93fa-495ce58c331c.png)

**Comment by andris155** [comment]
Most mondanám, hogy letiltom a telkeken, de gondolom a levédésbe is ugyanígy belerakja ezt.

**Comment by andris155** [comment]
Nem tudok erre megoldást. Aki szándékosan csinál ilyet szabálysértésnek számít a szerveren. Talán lesz rá javítás majd.
