### ISSUE TITLE
Falakon átbugolás pettel

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3919]
1 blokkos falakon, ajtókon át lehet bugolni, ha peten ülve nekimegyek, nyomom a W-t folyamatosan, és mikor félig a falban vagyok, leszállok róla.

**Comment by andris155** [comment]
Jelenleg ez egy nem támogatott plugin. A fejlesztő megírja, hogy működjön az új verziókon, de ennyi. Nincs fejlesztés, nincs hibajavítás.

**Comment by andris155** [comment]
Nem tartom ezt én olyan nagy gondnak. A levédésen ha bejutsz más házába nyilván az is védett. De egyébként nekem csak a falba sikerült beragadni, szóval megvalósítani sem annyira egyszerű. Meg tagként könnyen bele is halnak ha beleragadnak a falba.
Az eventeken meg úgy sincs pet, tehát a flat világba nem lehet ezzel kijutni.
