### ISSUE TITLE
Slimefun elbugolás

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#3920]
**Szerver**:Szurvi

Hali, nos, az történt, hogy én a slimefunban feloldottam egy csomó dolgot, meg is voltak egy ideig, de ma felmentem, és hopp, semmi nincs feloldva... Érdekes...

**Comment by andris155** [comment]
A játékos fájlodban pedig sok research fel van oldva. Nem tudok sajnos ezen javítani ha ez tényleg így történt ahogy írtad. Más nem számolt be ilyenről.
