### ISSUE TITLE
Mézes event

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#3922]
Survival/Savsziget--->

Egy olyan event, ahol egy hatalmas kaptárból kéne kiszabadulni. Egy afajta parkour event, keverve a Honey block mechanikájaval. A felépítése a CandyUp és IceUp Napi eventeihez hasonló lenne. A pályán CandyUp-hoz hasonló tudak lennének, annyi külömbséggel, hogy nem akárhol a rudon lehet átugorni a másikra, hanem csak pár blockrol (A rúd nagy része méz lenne, amin nem lehet ugrani) A nyertes 2 ládát kapna.

**Comment by KingDeadZ** [comment]
Ebbe bele lehetne vinni slimeblockokat is, hogy érdekesebb legyen, jó ötlet :D

**Comment by MrZero1** [comment]
Jó az ötlet, nekem is van a fejemben ilyen, majd meg is valósítom, addig ameddig meg tudom, de ezt inkább a warpos ötletládába, vagy az eventek warpon lévő ötletládába kéne megírni. Ezt lezárom, ne legyen addig megnyitva, míg el nem készül egyszer az event.
