### ISSUE TITLE
Megérős szavazói láda.

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#3923]
Survival->

A szerveren a  Szavazói láda sokkal jobb volt, mivel nagy mennyiségü nyereményt lehetett szerezni. Jelenleg, hogy a  szavazói láda bővült 3 sor spawn egg-el, így ritka az, hogy valami jót nyitunk. Egy Szavazói kulcsért 4 napon át kell szavazni a szerverre, és hatalmasabb csalódás az, amikor egy spawn egg-et nyitunk, és egy napi fortuna ládából hasznosabb dolgot nyitunk.
Ugyan ez a helyzet a Titkos ládával. Abba is sok a spawn egg, ami szintén nagy csalódás a játékosnak. (Ma történt velem: Volt 2 titkos kulcsom, és mind a kettőböl Ghast Spawn Egg-et nyitottam).

Ajánlani tudnám a Szavazói ládánál: Az utolsó 3 sor loot eltávolítása, és nerfelni a felső 3 lootok számát.

Ajánlani tudnám a Titkos ládánál. A spawn egg-ek eltávolítása.

**Comment by andris155** [comment]
@MrZero1 ezek is szerintem jó ötletek. Megvalósulhatnak?

**Comment by MrZero1** [comment]
Kiveszem a tojásokat a ládákból, majd a spawneresbe rakok új spawnereket pluszba.

**Comment by andris155** [comment]
De 2x gondold át miket raksz bele. Ezekkel könnyen tönkre lehet tenni az egész játékmenetet, hiszen végtelen mob jön belőle.

**Comment by andris155** [comment]
Meg úgyis csinálnak pwarp-ot szóval mindenki eléri ezeket.

**Comment by MrZero1** [comment]
Kész.
