### ISSUE TITLE
Megérős Spawner láda. 

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#3924]
Survival -->

A spawner láda az a láda, amihez kulcsot venni lehet igazi pénzből, és elég ritka az amikor máshogy tudsz szerezni eggyet. És elég szomorú az, hogy  nevével ellentétbe nehéz spawnert nyitni. A spawn egg-ek alalból haszontalanok, és szerintem senki se fizetne igazi pénzt érte.

Ajánlanj tudnám, hogy a láda első 3 sora eltünjön, így nagyobb esély lenne a lényeg megkaparintására.

**Comment by andris155** [comment]
@MrZero1 ez szerintem egy jó ötlet. Hiszen ez spawner-ek láda nem pedig spawn egg-ek láda. Megvalósulhat?

**Comment by MrZero1** [comment]
Szívesen kiveszem, de akkor alig marad benne spawner :D

**Comment by MrZero1** [comment]
Kész.
