### ISSUE TITLE
Több tokenből vehető jog.

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#3925]
Survival -->

Ahogy láttam manapság a csapat arra törekszik, hogy a free játékosoknak is jusson a fizetős dolgokból (Hírdetés jog és Tag+ rang). Ezért ajánlani tudnák pár jogot, mint pl:

-Heal/Feed: 400 Token az ára, 1 hónalig tartana.
-Skin jog: 600 Token az ára, 1 hónapig tartana, (1x használható)
-Craft/EC: 400 Token az ára 1 hónapig tartana.

**Comment by KingDeadZ** [comment]
A skin jogon kívül a másik 2 jó ötlet szerintem.

Egyébként a voteshopban van VIP rang is, és azért csak szavazni kell, még eventezni sem.

**Comment by andris155** [comment]
Valamennyire vezettünk be ilyeneket, de a szerver nem ingyen fut, szóval én több ilyet nem szeretnék. Így is rengeteg jog még tag ranggal is.
A skin amúgy teljesen ingyenes és bármire lehet cserélgetni. Csak persze ami fizetős, hogy meg kell venni az eredetit hozzá.
