### ISSUE TITLE
Kreában kiütve elbugol a spawner típusa

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3926]
![kép](https://user-images.githubusercontent.com/16057404/91059551-2a3ee000-e62a-11ea-9424-047ef9010610.png)

Survivalban is ilyen lesz, ha nem a SF spawner kiszedő csákányát használom.

**Comment by lovi-dev** [comment]
és tényleg 👍

**Comment by mnb124** [comment]
Le ne rakd mert utána hiába ütöd ki soawner felszedő csákival akkor se kapod meg a spawnert. (Drágán tanultam meg)

**Comment by lovi-dev** [comment]
normál helyzetben egy üres spawnerbe tojással bele lehetne "rakni", hogy mit spawnoljon...

**Comment by andris155** [comment]
Normál helyzetben tojást sem tudnál szerezni tólelőben...

**Comment by andris155** [comment]
Most már nem fog dobni semmit ha nem a megfelelő eszközzel ütöd ki. Holnap kerül be a javítás.

**Comment by andris155** [comment]
1016 OCD
