### ISSUE TITLE
Menci rgb-s nick jog staffoknak

### ISSUE THREAD

**Issue by Shryxx** [TheOld-Crafters/Minecraft-servers#3928]
**Szerver**: Survi 

Rgb nick jog staffoknak pls :(

**Comment by UDPSendToFailed** [comment]
Rangosoknak is lehetne, ha valaki pirosat vagy feketét rak bele, ugyanúgy szabálytalan, mint régen.

**Comment by MrZero1** [comment]
Igazából már jelentősége sincs annak, hogy valaki pirosat vagy feketét használ

**Comment by skrisz0101** [comment]
a feketének azért van, mert ocsmány xd

**Comment by andris155** [comment]
Igazából alig látszik sok esetben a fekete. Engem mondjuk nem zavar max elolvasni nem tudjuk. :D

**Comment by Shryxx** [comment]
Akkor lehet rá jog? :3

**Comment by KingDeadZ** [comment]
Zero, akkor lehetne legalább az oldnak engedélyezni a piros és vörös színt nickbe? :D 

Kernel ötletét támogatom, lehetne pl Prémitől.

**Comment by MrZero1** [comment]
Részemről lehet

**Comment by KingDeadZ** [comment]
Csak hogy  tisztázzam, ezennel engedélyezve van a /nick jogosoknak a piros és a vörös, vagy majd csak az RGB? :D

**Comment by KingDeadZ** [comment]
Egyébként majd ezzel együtt lehetne majd egy /einfo RGB is, vagy valami hasonló néven. De minimum a prémi szerintem az RGBhez

**Comment by MrZero1** [comment]
Igazából lehetne a játékosoknak is RGB, de én az előző kommentben a Staffokra gondoltam, játékosoknak a jelenleg 3 tiltott színre mondtam, hogy lehetne engedni 😃 
Nem tudom, hogy a játékosok közül ki mennyire értené meg, hogyan kell ilyet megadni/csinálni.

**Comment by KingDeadZ** [comment]
Remélem akkor hogy majd frissítve lesz a szabályzat, és engedélyezve lesznek a tiltott szinek a feketén kívül, mert az olvashatatlan. (azt pls ne xd)

Az RGBt kevesen értenék meg valószínűleg, amivel lehetnek bajok xd

**Comment by skrisz0101** [comment]
sokan a sima színkódokat se értik, azért van a /einfo színek xd
amúgy sztem is jó ötlet a vörös/piros (+RGB :p)

**Comment by Shryxx** [comment]
Igen.

**Comment by andris155** [comment]
Aki egy minimális szinten is ért a weboldal fejlesztéshez elég könnyen megérti a színezést. Másik fogalmam sincs mennyire értik meg. Alapvetően van rá weboldal ahol lehet hozzá kódot csinálni és látja a színét is. Szerintem nem egy bonyolult dolog. :D

**Comment by andris155** [comment]
https://www.w3schools.com/colors/colors_picker.asp

**Comment by Shryxx** [comment]
Ééés akkor lesz rá jog?

**Comment by skrisz0101** [comment]
@andris155 ha bekerül, akkor szerintem lehetne rá egy /einfo ami ekvisz a weboldalra, amit linkeltél

**Comment by KingDeadZ** [comment]
Szerintem bekerülhetne minél hamarabb, mert jelenleg szerintem ez még pár napot csak úgy állna magában előrehaladás nélkül.

**Comment by MrZero1** [comment]
Legyen akkor Prémiumtól jog az RGB-s nickekre, ezáltal a fekete piros vörös színnek a változatait is tudnák használni, de maradna a 3 tiltott szín az Elitnek.

**Comment by skrisz0101** [comment]
szal fekete nick a préminek szabad, az elitnek nem? ':D vagymi

**Comment by andris155** [comment]
A 3 tiltott színt a színkóddal engedélyezzem szintúgy a prémiumtól?
Illetve RGB-s írást is tudjanak?

**Comment by MrZero1** [comment]
Szerintem maradhat tiltva a 3 szín, ha az RGB-hez nem kell külön engedélyezni

**Comment by andris155** [comment]
Nem kell de az RGB-vel tudnak ugyanolyan színt is.

**Comment by skrisz0101** [comment]
Akkor nem vágom miért marad a sima piros, vörös, fekete tiltása

**Comment by Shryxx** [comment]
Jó csak legyen rá jog pls xd

**Comment by andris155** [comment]
Ezért kérdezem, mert én se értem. :D

**Comment by KingDeadZ** [comment]
Azt írta zero, hogy az elitnek tiltva marad, de RGBt sem kapnak. Prémitől már lesz RGB és a 3tiltott szín,

**Comment by MrZero1** [comment]
> Azt írta zero, hogy az elitnek tiltva marad, de RGBt sem kapnak. Prémitől már lesz RGB és a 3tiltott szín,

Köszi, ezekszerint legalább egy ember értette.. 😃😊

**Comment by KingDeadZ** [comment]
Így, hogy levan tisztázva mikorra kerülnek be a jogok? :D

**Comment by Shryxx** [comment]
NA akkor most hogy minden oké lehetne jog!

**Comment by skrisz0101** [comment]
@Shryxx csak ezért kérte vissza a segítőt én úgy hallottam

**Comment by andris155** [comment]
Csak a nick névvel kapcsolatban legyen ez a változtatás, vagy a a chatre írással kapcsolatban is?

**Comment by MrZero1** [comment]
Szerintem csak nick

**Comment by andris155** [comment]
A savszigeten csak old rangtól legyen ez a jog?

**Comment by Shryxx** [comment]
Ezaz! Egyre közelebb vagyunk már

**Comment by andris155** [comment]
bekerült

**Comment by KingDeadZ** [comment]
@andris155 Ez holnapra tölt be, vagy egy kis hiba csúszott be? Nem birok piros-vörös nicket állítani. Survival, Old rangom van.

**Comment by andris155** [comment]
Most jó?

**Comment by KingDeadZ** [comment]
Most sem jó, bocsi a késői válaszért.

**Comment by andris155** [comment]
De mit ír ki?

**Comment by KingDeadZ** [comment]
![image](https://user-images.githubusercontent.com/38157910/91637596-e83ae300-ea09-11ea-829e-10b647bfabb2.png)

**Comment by andris155** [comment]
Mos próbáld meg.

**Comment by KingDeadZ** [comment]
Megy az rgb is, és a 3tiltott szín is mostmár. köszi!

**Comment by vace-ai** [comment]
Lehetne Savszigeten is rgb staffoknak :C

**Comment by vace-ai** [comment]
Segítőkre és Modikra gondolok, mert mondjuk Olinak sem ment a chaten, pedig ő Moderátor

**Comment by andris155** [comment]
Legyen?
