### ISSUE TITLE
Freezer, túltermelés

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3929]
**Szerver**: szurvi ?sav?

Ha egy freezerben túltermelődik a hűtőcella, egyszerűen kidobja maga elé.

**Comment by poma123** [comment]
Ha megcsinálták, hogy kidobja, akkor szerintem direkt ilyen.

**Comment by mnb124** [comment]
Sk.. ritka mikor dibobja. Szeintem nem fogsz hisztizni heti 3-4 stsck hütőcellán. Nekem a reinforcedet köpte ki a gyár néha 😂

**Comment by KingDeadZ** [comment]
Nekem ploton ezt az ore grindernél csinálta amivel cobblet grindoltam le gravelnek. 
Gondolom más gépeknél is előfordul ez.

**Comment by skrisz0101** [comment]
mnb 5 percenként dobálja

**Comment by mnb124** [comment]
> mnb 5 percenként dobálja

Ha nincs sf nincs bug 🤷‍♂️

**Comment by andris155** [comment]
Ha megírjátok az összes hibát, akkor úgy sem lesz hiba, hogy van sf.

**Comment by andris155** [comment]
Nekem ezt nem sikerült reprodukálni. Ha túltermel amit csak szándékosan lehet elérni akkor nem dob ki semmilyen blokkot.

**Comment by skrisz0101** [comment]
@andris155 akkor majd ha fent leszel te is és én is, megmutatom. eddig nekem se volt ilyen, csak most köültözés után

**Comment by andris155** [comment]
Nekem az kellene, hogy hogyan tudom pontosan reprodukálni a hibát.
