### ISSUE TITLE
zúzottkő addolás

### ISSUE THREAD

**Issue by lovi-dev** [TheOld-Crafters/Minecraft-servers#3930]
**Szerver**: Survi
gm1-ben lerakott stone block-ot  gm0 -ban kiütve dobja a cobblestone -t.

**Comment by mnb124** [comment]
Elvielg dirrkt nincs tiltva. Nem egy értékes dolog a cibblestone..

**Comment by andris155** [comment]
Nem csak elvileg, hanem direkt van tiltva. Nem sokat ér ahogy írták. Nincs értelme ezt is tárolgatni.

**Comment by andris155** [comment]
Nem csak elvileg, hanem direkt nincs tiltva. Nem sokat ér ahogy írták. Nincs értelme ezt is tárolgatni.
