### ISSUE TITLE
Survival - HG és HNS jutalom

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#3931]
Lehetne a HGnak és a HNSnek (has) token jutalma, ugyan úgy mint az automata eventeknek.

A HG alapból ad pénz jutalmat, viszont a HNS az asszem nem ad semmit sem, csak a saját plugin currencyjét, az érmét adja, amit a pluginon belül bírsz elkölteni.

Szerintem így rá lehetne venni az embereket könnyebben arra, hogy többet játszanak HNSen és HGn 

u.i: Poma szerint megoldható.

**Comment by skrisz0101** [comment]
Paintballon is lehetne akkor már :c

**Comment by MrZero1** [comment]
Hát, a HG valóban keveset ad (500$).

**Comment by andris155** [comment]
Írjátok le melyik mit, és mennyit adjon, és akkor beállítom.

**Comment by KingDeadZ** [comment]
Ha lehet változtatni azon, hogy melyik csapatnak adja a hnsben akkor szerintem így kéne: Bújók: 6 token, 5000$ Seekerek: 4token, szintén 5000$

HGban csak 1 nyertes van, ott lehetne 15 token, és 7500$

Paintballon nyertes csapatok vannak, de mivel 2en is lehet tolni ezért 2token a nyerteseknek, és 1000$

**Comment by MrZero1** [comment]
10 tokentől többet nem igen adnék HG-n, ott is max 5k$

**Comment by skrisz0101** [comment]
Bújócskát is lehet tolni 2en,van mini aréna
ott is lehet 2token, 1000$

**Comment by skrisz0101** [comment]
amúgy a fortuna kulcs nyeremény  már túlzás lenne?

**Comment by MrZero1** [comment]
Az. Szavazással meg a naponta kivehető ládából épp eleget tudnak szerezni. 
Token lehet esetleg másik ládakulcs még lehetne, esetleg egy új minigames napiládát csinálni

**Comment by andris155** [comment]
A HideAndSeek-ben parancsot lehet megadni ha nyer valaki.
Mi legyen akkor a parancs, vagy ne adjon továbbra se mást?

A HungerGames-ben szintúgy paranccsal lehet megadni az extra jutalmakat. A pénz jutalom pedig jelenleg 500.
Mennyi legyen a pénz jutalom és mi legyen akkor az extra parancs oda?

**Comment by KingDeadZ** [comment]
Hnsben lehetne akkor 3token (gondolom kissebb arénára nem lehet megszabályozni h az mennyit adhat) és 1750$

Hgban pedig akkor lehetne 8token, és 5000$

Amit zero felvetett minigames láda az jó ötlet, csak akkor azt is meg kell csinálnia valakinek :V 

Amit írtam most összegeket kicsikét balancedebbek, remélem jó mindenkinek.

**Comment by skrisz0101** [comment]
@andris155  és paintballban?

**Comment by andris155** [comment]
Ott csak pénzt lehet esetleg beállítani.

**Comment by MrZero1** [comment]
Bújócska: 3 token, 1500$
Éhezők viadala: 8 token, 3500$
Paintball: minden nyertesnek 1500$

**Comment by andris155** [comment]
kész
