### ISSUE TITLE
Világ generálás újragondolva

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#3933]
Survival--->

Minden új frissítésnél megtörténik az, hogy az új dolgok miatt egy világot törölnek, és helyébe raknak egy új világot. Ez ameddig a staffoknak 1 nap, a játékosoknak több hét átköltözni. És ez egy afajta undort ad a játékosnak az új frissítéstöl. Íme az ötletem: 

Vadon1/Vadon2 név törlése. Helyükbe jöhetne a Letelepedés világ, és a Vándor világ. Ez annyit takar, hogy a Letelepedés világba költözne mindenki, és onnan nem kéne soha elköltöznie. Oda építhet halamas építményeket, farmokat, Falukat. Ezt a világot csakis a letelepedés céljából lenne. És a Vándor világ, az a világ ami minden frissítésbe törlődne és újra generálódna. Ezt a világot csak az új dolgok felfedezése érdekébe lenne.

**Comment by lovi-dev** [comment]
A letelepedés világ röviden plot.

**Comment by Shryxx** [comment]
Szerintem jó az ha néha újra kell építeni a dolgokat. Uncsi mindig egy helyen lenni. Ha valaki mégis egy helyen akar lenni annak ott a plot.

**Comment by skrisz0101** [comment]
ha mindig lenne egy állandó világ, az előbb-utóbb teljesen szét lenne rombolva, mint az atom.

**Comment by DiaGamer321** [comment]
Nem mondtam semmit.
