### ISSUE TITLE
Nem működnek az mcmmo képességek (savsziget)

### ISSUE THREAD

**Issue by diepitepie** [TheOld-Crafters/Minecraft-servers#3934]
**Szerver**: savsziget

 Az mcmmo képességeket shift+jobb clickkel lehet előhívni, de most nem csinál semmit.

**Comment by skrisz0101** [comment]
milyen képesség van shift+jobb klikkel? mondj párat

**Comment by KingDeadZ** [comment]
Survin sima jobbkattal lehet aktiválni, majd utána ütsz 1et. Amikor annó savoztunk skékkal akkor ugyan úgy működött.

De kíváncsi vagyok mit válaszolsz sk kérdésére, letesztelem survin ha van válasz

**Comment by diepitepie** [comment]
Savszigeten én mindig shift+jobb clickkel használtam (és persze utána ütöttem és akkor aktiválódott..), de most kipróbáltam és sima jobb click se jó.
(ezeket próbáltam használni:
balta: fadöntés
csákány: szuper törés
ásó: giga fúró-törő)

**Comment by KingDeadZ** [comment]
sima jobbkattal "előkészíti" és utána ha ütsz a blockra, amit ugymond "támogat" a képesség akk aktiválódik

**Comment by diepitepie** [comment]
Oh, mikor lefeküdtem az ágyba, az 'öklöm' most működött (vagyis felhozta a kis üzenetet). Kipróbáltam most eszközzel és ha nézek egy blockra (amit elérek) és úgy próbálom aktiválni a képességet, akkor működik, de ha a levegőbe nézve próbálom, akkor nem jó csak. (Eddig pedig levegőbe nézve próbálkoztam csak (ami régebben működött is), mert nem akartam se leszedni a fa kérgét, se 'path'-ot csinálni a füves blockból..)
