### ISSUE TITLE
Savsziget hibák / fejlesztések

### ISSUE THREAD

**Issue by Conaniwnl** [TheOld-Crafters/Minecraft-servers#3936]
**Szerver**: Savsziget

- Savszigeten lucky blockból, lehet kapni még Kulcsmester kulcsot, ami ugye savon nincs. Nem tudom a configba még milyen kulcs van amit savon nem lehet felhasználni, azokat kilehetne szedni? Vagy esetleg átírni hogy savos kulcsokat dobjon.
- Spawnon nem lehet használni a /ec parancsot. Ez a event világos /ec letiltás óta nem jó, lehetne engedélyezni spawnon? (Ha valaki pl cserélni akar vip szigeten jól jöhet ha hozzáfér a cuccokhoz és nem kell tpzgetni. Meg egyébként sincs értelme ott letiltani.)

- Ez inkább fejlesztés, de ide írom: Lehetne-e változtatni mennyi játékos kell az este kihagyásához, mert jelenleg szerintem indokolatlanúl sok. Survin elég pár játékos, savon kb a játékosok felének aludni kellene. Lehetne ezt kb a játékosok 30-25%-ára csökkenteni?

**Comment by andris155** [comment]
1. Kivettem a konfigból a Kulcsmester kulcsot. A fortuna van benne még, de az elvileg ott is van. Holnap tölt be a változtatás.

2. Nem lehet megoldani. Van egy újabb spawn egy másik világban nem tudom az végül miért nem került be.

3. Beállítottam ugyanarra mint a túlélőn van.
