### ISSUE TITLE
LiteXpansion kérdés

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#3938]
Andris, meg lehetne tudni, hogy a LiteXpansiont miért nem szeretnéd, hogy bekerüljön? :D Ha lehet, részletesen.
Elméletileg nagyon személyre szabható addon az sfhez, és én nem látom hogy miért ne kerülhetne be. (Solarpanelek nélkül)

**Comment by skrisz0101** [comment]
+1 skrisz részéről: Slimy TreeTaps

**Comment by andris155** [comment]
A Slimy TreeTaps-et MrZeri nem szeretné, hogy bekerüljön. Mert már túlságosan automatizált lenne szerinte minden úgy.

**Comment by skrisz0101** [comment]
de menő a kapás cucc, amivel le lehet szedni a cuccot a fáról xd

**Comment by andris155** [comment]
Szerintem ilyen szempontból elcseszi a játékot tényleg. Annak pont az a lényege, hogy nehezen lehet szerezni.

**Comment by andris155** [comment]
A Slimy TreeTaps tőlem bekerülhetne. De a szervert csapat vezeti. Szóval erről a csapat dönt nem csak én.
A LiteXpansion-t megfogom nézni. Meg mielőtt bekerülne esetleg majd alaposan letesztelni.

**Comment by MrZero1** [comment]
Én továbbra sem szeretném, de ahogy már oly sok minden, most sem számít amit mondok. Úgyis ti döntitek el. 🤷🏼‍♂️

**Comment by skrisz0101** [comment]
Nekem az a bajom a LiteXpansionnal, hogy túl op solar generátor van benne. Rohadt sokat termel rohadt kevés alapanyagból

**Comment by KingDeadZ** [comment]
Solarpanelek nélkül szerintem élhető az addon, egy kis "viszonzás"ként is fel lehet fogni az adv outputok miatt.

**Comment by poma123** [comment]
- :x: A SlimyTreeTaps szerintem annyira nem lényeges, ha jól tudom Plastic szerzésre jó, de azt bőven lehet szerezni most is.
- :+1: Az LX pedig jöhetne, miután  át lettek nézve az UU Matter craftjai. (Egyébként direkt nagyon nehézre és drágára lett az egész addon tervezve.)

**Comment by skrisz0101** [comment]
Kivéve a solar panelek rész :/

**Comment by andris155** [comment]
Tőlem bekerülhet a LiteXpansion. Aztán majd megírjátok a hibákat, amik biztosan vannak benne.

**Comment by andris155** [comment]
Akkor kerüljön be a Solar panelek nélkül?

**Comment by KingDeadZ** [comment]
Szerintem bekerülhetne, nem látom hogy miért ne kerüljön be.

**Comment by andris155** [comment]
mind a 3 napelem legyen tiltva?

**Comment by skrisz0101** [comment]
Asszem Mind3 túl olcsó, megnézem holnap

**Comment by andris155** [comment]
Nem tudod ma megnézni?

**Comment by poma123** [comment]
Mind a 3 legyen tiltva igen

**Comment by andris155** [comment]
Bekerült
