### ISSUE TITLE
Mute és jail

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3939]
**Szerver**: szurvi, sav

Az örök némítás és örök jailnál úgy írja a /seen-nél hogy,,igaz"
Nem lehetne átírni örökre vagy valami? 
Egyrészt a kezdők nem érthetik
Másrészt igénytelen (sztem) 

Tudom, mindig is így volt, de attól még szar :v

**Comment by andris155** [comment]
Nem lehet.

**Comment by MrZero1** [comment]
Mi ebben az igénytelen? 😀

**Comment by skrisz0101** [comment]
Az,,igaz", mikor örök 🤷‍♂️

**Comment by MrZero1** [comment]
😂😅

**Comment by Shryxx** [comment]
Nem kell elérni hogy örök némítást vagy jailt kapj és nem lesz probléma
