### ISSUE TITLE
Addolás esélyes hiba mobarénában

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3941]
Mobarénában le lehet pakolni a cuccokat ládákba, halál után pedig survivalban visszakerülünk az aréna tetejére, ahol lehet elytrát, Slimefun-os peteket, stb használni. Ha sikerül átbugolni a barrieren, ki lehet venni a ládákból az előzőleg belerakott mobarénás tárgyakat, páncélokat.

**Comment by KingDeadZ** [comment]
Ha mobarénában játszol, akkor le birod egyből dobni a cuccaidat, amit fel lehet venni.

**Comment by UDPSendToFailed** [comment]
Nem pont a barrieren keresztül, de be lehet jutni, és elvinni a cuccokat: https://youtu.be/2vCvslQQIt8

Még eventvilágba is ki lehet menni:

![kép](https://user-images.githubusercontent.com/16057404/91645325-7cc23700-ea44-11ea-96ec-8ae490d2da98.png)

**Comment by andris155** [comment]
A tárgyak kidobását letiltottam az arénában.

**Comment by KingDeadZ** [comment]
Még mindíg be lehet menni. A ládanyitást is le lehetne tiltani. Minden blockon át lehet esni, szóval ajánlanék egy barrier réteget is az arénában.

**Comment by andris155** [comment]
Jól van remélem a staffok figyelik. Amint hazaérek majd nézek megoldást.

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
508 OCD
