### ISSUE TITLE
Slimefun Smeltery Savsziget

### ISSUE THREAD

**Issue by vace-ai** [TheOld-Crafters/Minecraft-servers#3942]
**Szerver**:Savsziget

Használtam a smeltery-t, és random azt veszem észre, hogy nem alszik ki a **Láng** amivel működik a Smeltery. Szóval mivel eddig kiégett, elég gyakran, ezért gondoltam írok. 

-vace

**Comment by Conaniwnl** [comment]
Nincs ilyen hiba, ugyan úgy kialszik, csak vace tudta nélkül volt mögötte egy Automatic Ignition Chamber.

**Comment by andris155** [comment]
Köszi az infót @Conaniwnl
