### ISSUE TITLE
Savsziget egyedi receptes plugin

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#3944]
**Szerver**: Savsziget

Úgy kinézete van a receptes könyvnek.
![kép](https://user-images.githubusercontent.com/29709854/91657258-ef242d00-eabf-11ea-90f9-b566ee5cc28e.png)

Ebben vannak angol szövegek, azokat lelehet fordítani?

**Comment by MrZero1** [comment]
A mellette lévő zöld a régi könyv ugye.

**Comment by MrZero1** [comment]
Illetve nem tudom, lehet e változtatni rajta, de a kategorizálás eltűnt, minden recept egy helyen van. Eddig a kemencés, üst, tábortűz stb. külön volt.

**Comment by andris155** [comment]
A régi nem fog működni ez egyértelmű.

**Comment by andris155** [comment]
A fenti iránytűre kell jobb klikkelni a kategória váltáshoz.

**Comment by andris155** [comment]
<img width="455" alt="Capture" src="https://user-images.githubusercontent.com/8324198/91665136-c584f900-eaf3-11ea-8bf3-3b88d3b8e334.PNG">

**Comment by andris155** [comment]
<img width="350" alt="Capture" src="https://user-images.githubusercontent.com/8324198/91665149-d7ff3280-eaf3-11ea-9e7c-0fb1cff5dbd9.PNG">

**Comment by andris155** [comment]
Le lehet fordítani, de mivel sokszor frissül nem nagyon érdemes. Nincsen nagyon ember aki folyamatosan frissítené ennek is fordítását.

**Comment by MrZero1** [comment]
Jogos. Amúgy meglepő, de a zöld is működik 😃

**Comment by andris155** [comment]
Az fura. xD
