### ISSUE TITLE
RGB savszigetre

### ISSUE THREAD

**Issue by Conaniwnl** [TheOld-Crafters/Minecraft-servers#3945]
**Szerver**: Savsziget

Esetleg megoldható lenne, hogy úgy mint survin, savszigeten Old rangtól megkapjuk az RGB név állítást, és RGB írást? Savszigeten még a segítők se tudják egyiket se, survin viszont már rangos játékosok is képesek rá. Valahogy az ilyen fejlesztések a savszigetet elkerülik.

**Comment by andris155** [comment]
már meglett oldva.

**Comment by Conaniwnl** [comment]
Holnaptól?
