### ISSUE TITLE
SlimeFun - Gold Pan nem működik csak telken

### ISSUE THREAD

**Issue by valtinator** [TheOld-Crafters/Minecraft-servers#3946]
*Survival*

Ahogyan a címből is látható, a Gold Pan nem működik moderátor is próbálta neki sem ment, csak a telken működik valamiért, pedig egy órája még  jó volt.

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a hibát. Kreatív blokkal nem működik, lehet azzal próbáltad?
