### ISSUE TITLE
OldSpace és Építész+, játékosszám

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3947]
**Szerver**: Mindenhol

Mindig azt írja, h 0 ember van fent, mikor nem is. most is fent vannak 5en kb, de 0-t ír mindegyik szerón. OldSpacen jól mutatja

Most látom, Építészen is szarul számolja. most pl 19et ír, mikor 0 ember van fent.
(Építészen jól mutatja)

**Comment by andris155** [comment]
Most jó?

**Comment by skrisz0101** [comment]
most jó, igen
