### ISSUE TITLE
Tab - Tabtető

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3948]
**Szerver**: gondolom mindenhol kivéve OldSpace vagy nemtom

Csak vadon1 és vadon2ben ilyen:
Kép elmond mindent: 
(Tab tetejét kell nézni)
![2020-08-31_12 54 52](https://user-images.githubusercontent.com/29951969/91713181-8e612700-eb89-11ea-8191-ee64cd466870.png)

**Comment by andris155** [comment]
Gondoltam, hogy problémás lesz az example konfig benne. xd

**Comment by andris155** [comment]
Most jó?

**Comment by andris155** [comment]
Teszteltem, és jó.
