### ISSUE TITLE
LiteXpansion Mass Fabricator túl sok energiát fogyaszt

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3949]
100db Scrap kell egy UU-Matter-hez, és egy Scrap átalakítása 16.666 J energiát használ, amit kb lehetetlen szinten tartani, 16db Radiant Solar Generator kéne hozzá poma pluginjából, vagy 34db Nuclear Reactor, ezeket átlag játékos számára hónapokig tartana megszerezni. UU-Matter-ből pedig 9db kell egyetlen gyémánthoz, tehát ~15 millió J energiába kerül.

Javaslatok a probléma megoldására:

- Scrap átalakítás energiaszükségletének csökkentése 1024 / 2048 / 4096 J-re, még ez is durván sok az eddig elérhető gépekhez képest, egy komplett dustgyár elvan 1000 J alatt.
- Kevesebb Scrap kelljen egy UU-Matter-hez, 100 helyett 10-20

**Comment by andris155** [comment]
Ötleteket elvileg a Slimefun Discord szerveren lehet írni hozzá angol nyelven.
https://slimefun.dev/discord
Bocsi, de annyira nem bírom az ottani fejlesztők stílusát. Szóval ezt neked kell megírnod nekik, ha szeretnél ilyen fejlesztés.

**Comment by UDPSendToFailed** [comment]
Ez a gép nem a Slimefun-ban van, hanem a tegnap bekerült LiteXpansion addonban, egy szám átírásával megoldható a dolog. A LiteXpansion fejlesztője nem hiszem, hogy megcsinálja, mivel abban voltak direkt ehhez a géphez Solar Generator-ok, de azok tiltva lettek a szerveren, mert túl OP-k lennének az árukhoz képest.

https://github.com/J3fftw1/LiteXpansion/blob/master/src/main/java/dev/j3fftw/litexpansion/machine/MassFabricator.java

![kép](https://user-images.githubusercontent.com/16057404/91715063-47753080-eb8d-11ea-898d-82da25bb7e2a.png)

**Comment by poma123** [comment]
Sajnos ezen nem fognak változtatni. Vagy vissza kell kerülnie az egyik solar generátornak, vagy repül akkor az addon.

**Comment by skrisz0101** [comment]
lehet állítani azon, hogy mennyi trashbe kerüljön egy UU matter, nem?

**Comment by poma123** [comment]
Nem, az UU matter craftokat lehet csak állítani. (értsd: azokat a craftokat, amiben UU matterből lehet valamit készíteni.)

**Comment by skrisz0101** [comment]
jaa, rosszul emlékeztem

**Comment by poma123** [comment]
Vagy még lehet az is, hogy a PomaExpansionba kerül be egy új generátor ami kifejezetten ehhez lenne. Jöhetnek ötletek, hogy mennyit termeljen.

**Comment by skrisz0101** [comment]
azaz egy rohadt drága áramtermelő? :D

**Comment by UDPSendToFailed** [comment]
![kép](https://user-images.githubusercontent.com/16057404/91725829-8e6c2180-eb9f-11ea-83a4-a8a17ddce8e9.png)

TL;DR: LiteXpansion fejlesztő nem fog opciót berakni, hogy lehessen változtatni a gép fogyasztását.

**Comment by andris155** [comment]
Akkor legyenek engedélyezve a napelemek, vagy mi legyen?

**Comment by poma123** [comment]
Ne legyenek, mert túl sokat generálnak túl olcsón -> ergó a többi generátornak semmi értelme nem lesz.

**Comment by andris155** [comment]
Akkor mi legyen?

**Comment by skrisz0101** [comment]
slimefun dc-re ment az ,,ügy" :D

**Comment by poma123** [comment]
Most elég kevés üzenet jön róla, kiderül mi lesz. (Szerintem semmi)

**Comment by UDPSendToFailed** [comment]
Indoklást is kaptunk, hogy miért nem lesz rá konfig opció. =D

![kép](https://user-images.githubusercontent.com/16057404/91749616-077c7080-ebc2-11ea-8443-2f64afdab2ec.png)

További lehetőségek:

- Értékesebb UU-Matter craftok, amik megérnek ~1.6 millió J energiát
- Marad a LiteXpansion, de ilyen áron kb senki se fogja használni
- Repül a LiteXpansion

**Comment by poma123** [comment]
Vagy csinálok egy saját Advanced Mass Fabricatort ami nem fogyaszt annyit.

**Comment by poma123** [comment]
Kész, holnap betölt az Advanced Mass Fabricator
