### ISSUE TITLE
Lávalerakás

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3953]
**Szerver**: Szurvi, sav

Oldtól lehetne jog lávalerakáshoz. 
Egy 5milla$/5k ocd/2,5k Ft értékű rangot szerintem senki se használna trollkodásra 
+láva lerakás  nélkül is lehet trollkodni. (halálos csapdák, tpkill, witherrózsa, falösszecsukódás, minden rák)

**Comment by andris155** [comment]
@MrZero1 neked mi erről a véleményed?

**Comment by MrZero1** [comment]
Az, hogy bármelyik admin és moderátor rak le lávát, bárkinek. 🙂

**Comment by UDPSendToFailed** [comment]
Mi van, ha éppen nincs fent moderátor / admin, és építgetés közben eltűnik a láva, mert valahonnan ráfolyik a víz? Vagy esetleg ha valaki több féle elrendezést is ki szeretne próbálni egy farmnál, kőgenerátornál, hívja oda 10 percenként a staffokat? Ahogy sk is írja, hülye lenne ezzel bárki is kockáztatni az 5080 OCD-s rangot, ha pedig trollkodni akar, van rá millió másik lehetőség a láván kívül.

**Comment by MrZero1** [comment]
Eddig sem volt rá jog játékosoknak, szerintem jogosan. Részemről nem, ne is legyen jog rá,de majd a illetékesek eldöntik.

**Comment by schmekkels** [comment]
Én például dekorációként szívesen használnám, **a saját levédésemen belül.**

**Comment by andris155** [comment]
Az a baj, hogy attól, hogy támogatja valaki a szervert még ugyanúgy trollkodhat. Szerintem erre rengeteg példa is volt már sajnos. Ez így nem fog bekerülni.

**Comment by UDPSendToFailed** [comment]
Ennyi erővel az Uranium-ot, Plutonium-ot, és a többi radioaktív Slimefun itemet is lehetne tiltani, azokkal még a saját levédésén belül is meg lehet ölni valakit.

**Comment by andris155** [comment]
A lávával a világot is eléggé tönkre lehet tenni, ha mindent tele öntögetnek vele. Ez vele a probléma.

**Comment by UDPSendToFailed** [comment]
Vízzel is meg lehet tenni ugyanezt, azzal a különbséggel, hogy az nem sebez, még gyorsabban is folyik a lávánál. De igazából nekem mindegy, megvagyok nélküle.
