### ISSUE TITLE
XP szint átváltása nem működik

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3954]
Hiába jobbklikkelek spawnerre üres kézzel vagy üvegpalackkal, semmi sem történik.

**Comment by MrZero1** [comment]
A craftbook-os xp kinyerés kikerült már egy ideje, elvileg van a slimefun-ban valami alternativa

**Comment by andris155** [comment]
Pontosan úgy van ahogy @MrZero1 írja.

**Comment by UDPSendToFailed** [comment]
Van EXP Collector, de azzal a játékos nem tudja kivenni a saját XP szintjét palackba, az csak a megölt moboktól gyűjti.

**Comment by kBalix** [comment]
flask of knowledge-be lehet XP-t tölteni.

**Comment by UDPSendToFailed** [comment]
Csak azt lehet, amit az EXP Collector közelében megölt mobok dobnak, a játékos XP szintjét nem.

**Comment by andris155** [comment]
Flask of knowledge-be lehet XP-t tölteni ahogy írták.

**Comment by andris155** [comment]
Jobb klikkelni kell vele.

**Comment by UDPSendToFailed** [comment]
Így már jó, köszi.
