### ISSUE TITLE
Lucky Block állatok

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3956]
![kép](https://user-images.githubusercontent.com/16057404/91969335-37d52380-ed16-11ea-8d43-8b7f411ade42.png)

Egy picit túl sok spawnol, telkeken átmennek a szomszédokhoz is, ahol már nem lehet őket megölni. Szerintem feleslegesen laggoltat ennyi mob.

Chaten is spamel szépen.

![kép](https://user-images.githubusercontent.com/16057404/91971226-26d9e180-ed19-11ea-95fa-6f14e0f9ed83.png)

**Comment by DiaGamer321** [comment]
Jej rajta vagyok a képen.😌

**Comment by DiaGamer321** [comment]
Am tényleg zavaró a sok mob. Meg felesleges. Max 1 lucky Blockbol 1-3 farkas/macska jönne. Az jobb lenne. Meg van a pandás/rókás/méhes loot. Abbol is lehetne az, hogy csak 1-2 db állatot ad ezek közül random.

**Comment by andris155** [comment]
@poma123 csökkenthetem a mobok számát a konfigban?

**Comment by poma123** [comment]
Persze.

**Comment by andris155** [comment]
Csökkentettem a mobok számát. Holnap betölt a változtatás.
