### ISSUE TITLE
Slimefun textúra engedélyezése

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3958]
Van egy SF textúra, amit elég gyakran frissítenek, minden item benne van, de szerveroldalon is engedélyezni kell. Szerintem sok játékosnak jól jönne.

https://www.planetminecraft.com/texture-pack/slimefun-texture-by-raulh22/

**Comment by andris155** [comment]
A régi tárgyak nem fognak vele változni így semmi értelmét nem látom már ennek.

**Comment by skrisz0101** [comment]
De az újak igen :(
Úgyis csak az tenné be aki akarná

**Comment by andris155** [comment]
Nem szeretném így. Vagy mindegyikre működjön vagy egyikre sem. Most az, hogy félig működik félig nem annak nem sok értelme van.

**Comment by poma123** [comment]
Én sem támogatom ezt. Kész sincs normálisan ez a rendszer, és minden itemet "elcsesz".
