### ISSUE TITLE
15p afk helyett crash

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3960]
**Szerver**: OldSpace

Csikbaro-val történik ez.
állítása szerint 15p játék után kicrashel neki a játék, de csak a tocon (perpill nézi szurvin, de ott már szóltak volna gondolom ha ilyen lenne) 1-es hibakóddal
azt mondta más szerón és egyjátékosban nincs ilyen neki

**Comment by andris155** [comment]
Hánykor dobta ki pontosan a játék?

**Comment by skrisz0101** [comment]
Mondtam neki h írja fel legközelebb. (Ma is kidobta 2x, szóval biztos lesz még ilyen)

**Comment by skrisz0101** [comment]
Tegnap: 21:06:40, 21:31:29, 21:47:41
ma: 9:47:36
@andris155

**Comment by andris155** [comment]
A log-ban csak annyi van, hogy megszakadt a kapcsolat a játékos és a szerver között. Nála lesz a hiba. Kellene a kliens log a \.minecraft mappából, amiben van ilyen kidobás.
+ a crash report.
Akár privátban is elküldheted ha vannak benne titkos információk.
