### ISSUE TITLE
Tab

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#3961]
**Szerver**: Mindenhol

![kép](https://user-images.githubusercontent.com/29709854/92303075-efb23d00-ef71-11ea-9ca1-73a6cc3a4c99.png)

A csillag helyett lehetne ×.

A táblán az első sor a csillag, a második az × jel.

![kép](https://user-images.githubusercontent.com/29709854/92303244-42402900-ef73-11ea-9122-ccc97c378417.png)

**Comment by andris155** [comment]
Azzal a béna áthúzott vonallal is akkor kezdeni kellene valamit.

**Comment by poma123** [comment]
> Azzal a béna áthúzott kötőjelekkel is akkor kezdeni kellene valamit.

Így egy sima vonal lesz
`&7&m &7&m &7&m &7&m `

**Comment by andris155** [comment]
&7&m &7&m &7&m &7&m
Most ez mi?
Ezek space-ek csak.

**Comment by andris155** [comment]
kész

**Comment by poma123** [comment]
Szuper lett
![image](https://user-images.githubusercontent.com/25465545/92309983-2e63e980-efaa-11ea-8150-ad2c468ef341.png)
