### ISSUE TITLE
Tab - RGB

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#3962]
A nickeknél az RGB-s szineket szerintem lehetne offolni, mert elcsúnyítják a tabot nagyon, de ha megoldható egy olyan opció is lehetne, hogy beírsz egy parancsot, és a régi tabot fogod látni,rgb nélkül. Félreértések elkerülése végett még1x leírom, hogy nekem a nickekkel van csak a bajom, mert elcsúnyítják a tabot. Az, hogy a rangok rgbsek, meg még nem tudom mi az teljesen belefér.

**Comment by andris155** [comment]
Szerintem meg így szebb és jobb, hogy látni rajta a színes nick neveket is.
