### ISSUE TITLE
Survival - Kreatív védelem

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#3963]
Ha leraksz egy bármilyen kerítést, majd rá egy blackstone pressure platet kreatívban, majd kiütöd a kerítést, a pressure platet kidobja. szerintem csak ezzel működik, warped fással próbáltam még, meg arannyal azok nem működtek

**Comment by andris155** [comment]
Jelentettem a fejlesztőnek kb. 30-60 nap a javítási idő.

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
javítva
