### ISSUE TITLE
Lift táblák

### ISSUE THREAD

**Issue by Conaniwnl** [TheOld-Crafters/Minecraft-servers#3964]
**Szerver**: Savsziget, Survival

Ha használjuk a lift táblákat, egy kellemetlen felszólítást kapunk, de ettől függetlenül végrehatja a feladatát.

https://www.youtube.com/watch?v=UMpeC59j9Lw&ab_channel=Conan-iwnl-

**Comment by kBalix** [comment]
Survivalon is.

**Comment by poma123** [comment]
My bad, holnap jó lesz

**Comment by andris155** [comment]
De milyen fejlesztőnek kellett jelenteni, ha az te vagy?

**Comment by poma123** [comment]
Saját magamnak jeleztem xdxd
