### ISSUE TITLE
/játékidő, első belépés

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3965]
**Szerver**: Mindenhol

A /játékidő-nél  az első belépést hibásan írja ki. nekem pl 2020.09.05-t ír.

**Comment by KingDeadZ** [comment]
gondolom a plugin berakása óta mér időt csak

**Comment by MrZero1** [comment]
Nemhiszem, hogy tegnap került volna be a plugin 😃

**Comment by poma123** [comment]
A fő világ "első belépés" nevű vanilla statisztikáját nézi a plugin, teljesen mindegy, hogy mikor került be.

**Comment by andris155** [comment]
Elvileg ugyanazt kell írnia mint ami a statisztikák játék menüben van.

**Comment by andris155** [comment]
Nem sikerült reprodukálni a hibát. Nekem hibátlanul írja.
