### ISSUE TITLE
Cenzúra igazságtalanság

### ISSUE THREAD

**Issue by Shryxx** [TheOld-Crafters/Minecraft-servers#3967]
**Szerver**: MIndegyik!

Ha a barom, basszus, ÉS MÉG a buzi is csúnya szó, akkor már a cigány is legyen az! Igazságtalan, hogy az egyiket szabadon lehet írkálni másik meg cenzúrázva van! Vagy mind a kettő legyen, vagy egyik sem. Csalódtam benned, Andris!

**Comment by mnb124** [comment]
Chh.. mert a cigány annyira rasszista..
Most nem irhatom le hogy mekkora egy cigány vagyok?
Akkor cékla,cintányér,cibbony, c tipusu stb is tiltva lehetne.. ugyanugy a ciganyra utal..

**Comment by Shryxx** [comment]
Oké, írjad ha cigány vagy, de akkor a buzi se legyen cenzúrázva, vagy legyen mind a kettő

**Comment by UDPSendToFailed** [comment]
A retardáltat sem kéne cenzúrázni, teljesen normális szó a mentálisan sérült személyekre.

![kép](https://user-images.githubusercontent.com/16057404/92324651-117bf480-f044-11ea-87e5-a3dfb58601d9.png)

**Comment by MrZero1** [comment]
Igazából ha senki nem írná ki a chatre nem illő szavakat, cenzúrázni sem kéne őket :D:D 
Kicsit normálisabb hozzáállás és felfogás kérdése

**Comment by andris155** [comment]
Letiltottam a cigányt is.
Nyilván nem teljes a lista. Rengeteg olyan dolgot is tiltana, amit nem kellene, ha megcsinálnánk teljesre. Azt próbáltuk tiltani, amit a legtöbbször használnak helytelenül.
Ha lenne esetleg ,,cigány" játékos bár szerintem a mai világban nincs értelme ilyen különbségeket tenni, akkor lehet használni a roma szót rá.
A ,,buzi" szó helyett pedig lehet használni a meleg szót. Ajánlom, hogy a valóságban is inkább meleget mondjatok a melegekre, mert ők sem szeretik ha a ,,buzi" szót használjátok rájuk.

**Comment by Shryxx** [comment]
Tapasztaltam az utolsó mondatot, tényleg ne buzizzatok

**Comment by UDPSendToFailed** [comment]
Na és a retardált? 😢

**Comment by andris155** [comment]
@UDPSendToFailed az a baj, hogy ezt is helytelenül használják szerintem 90%-ban.

**Comment by Shryxx** [comment]
Nem kerek ocdt csak segitetem!
