### ISSUE TITLE
report rendszer

### ISSUE THREAD

**Issue by derpyke** [TheOld-Crafters/Minecraft-servers#3968]
**Szerver**:
Savsziget/Survival

**Lehetne egy report rendszer ahova játékosok tudnak jelenteni mindenféle szabály ellenes dolgot. És a staffok meg tudják nézni a reportokat.**

**Comment by Shryxx** [comment]
Erre van a segítségkéres szoba dcn nem?

**Comment by MrZero1** [comment]
Nem lenne rossz, de talán a Discord a leggyorsabb útja a csalók, rosszalkodó játékosok jelentésére.
