### ISSUE TITLE
Login - elcsesződött rangok

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3969]
**Szerver**: Login

![2020-09-07_19 14 08](https://user-images.githubusercontent.com/29951969/92408636-69972180-f13e-11ea-80e3-4efcd2fc70e6.png)

**Comment by andris155** [comment]
Majd néznem kell valami modernebb chat kezelő plugint oda.

**Comment by andris155** [comment]
Javítva.
