### ISSUE TITLE
Vas ajtó LOCK hiba

### ISSUE THREAD

**Issue by maryhonaly** [TheOld-Crafters/Minecraft-servers#3971]
1.16.2, Survi, Sav. (Oldspace-n jó.)

https://youtu.be/S_MuJuVHN1Q

Sima fa ajtónál minden működik ahogy azt illik. 
Amennyiben vas ajtót [lock]-olok le (mindegy, shit-el teszem rá vagy csak jobb klikk és automata teszi a táblát), a vas ajtó lezárása megtörténik, és nem nyitható jobb klikkel. Amennyiben a vas ajtóra sima jobbklikkel teszem rá a táblát, kinyílik és úgy marad.

Puszta kézzel nem nyitható-zárható. Amennyiben valamilyen itemmel a kezemben klikkelek, azt alapesetben leteszi, viszont ha nincs hely vagy nem lehetséges letenni, akkor nyitható az ajtó.

hibát jelentette: janos_vagyok9185

**Comment by andris155** [comment]
Valamikor talán érkezik rá. Addig redstone segítségével szerintem nyithatóak a védett vasajtók is.
