### ISSUE TITLE
Spam védelem - aukció

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3972]
Elég zavaró, hogy pont a 9. stacknél kell 10 másodpercet várni, mielőtt fel tudnám rakni aukcióra. Lehetne még +1 "spam" megengedve a playereknek, így amíg belepakoljuk a hotbar-ba az eladandó cuccokat, le is járna a 10 másodperces késleltetés.

![kép](https://user-images.githubusercontent.com/16057404/92640215-3fc83100-f2dd-11ea-8d33-de2e3781c224.png)

**Comment by andris155** [comment]
Ezen nem szeretnék módosítani inkább. Másban nem okoz problémát és ez a limit így is elég magas azért.
