### ISSUE TITLE
/csn history

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3975]
**Szerver**: szurvi, talán sav is

/csn history-ra ismeretlen parancsot ír (hasznos, remélem nem csak kikerült :( )

**Comment by poma123** [comment]
Ki lett véve @andris155 által, mert több giga adatot tárolt.

**Comment by skrisz0101** [comment]
nem lehetne valami automata history törlőt rakni? :(

**Comment by andris155** [comment]
Nem.

**Comment by Shryxx** [comment]
@andris155 mennyi pénzért csinálnál megoldást rá? Korrekt összeget mondj
