### ISSUE TITLE
Mypet 1.16.3 támogatás

### ISSUE THREAD

**Issue by poma123** [TheOld-Crafters/Minecraft-servers#3976]
**Szerver**: Survival

Jelenleg nem támogatja az 1.16.3-at, nincsenek benne az 1.16.3-as NMS classok. Emiatt kivettem a plugint, mert a szerver kicrashelt.

https://pastebin.com/0cqRcKqt

**Comment by andris155** [comment]
Nincs is olyan nms. Gyakorlatilag minimálisan változtattak a jelenlegin csak ahogy láttam. A MyPet-et nem nagyon fejlesztik, szóval türelmesen ki kell várni még frissítik.

**Comment by poma123** [comment]
Hülyén van megcsinálva, minden verzióra külön van nekik egy de.Keyle.MyPet.compat.VERZIÓ.entity.ai.movement.Control class, viszont az 1.16.3-ra még nem csináltak. Gondolom NMS miatt van rá szükség. (net.minecraft.server)

**Comment by andris155** [comment]
Visszakerült és frissült.
