### ISSUE TITLE
Hülye szabály

### ISSUE THREAD

**Issue by Shryxx** [TheOld-Crafters/Minecraft-servers#3977]
**Szerver**:mindegyik

5.8, Amennyiben új karaktert szeretnél használni, jelezd azt egy Adminnak! A karakterváltásról Neked kell gondoskodni. Rangot és különböző, már elért tulajdonságokat (mcMMO, Slimefun, szavazói pont, levédés, levédésblokk) átadni nem áll módunkban. A régi, már nem használt neved pedig tiltásra kerül, az 5.7 pont miatt.

Ha kifizeti valaki a rangot miért nem lehet átadni neki?

**Comment by skrisz0101** [comment]
zárd a rákba, csináltam mencibb jelentést

**Comment by Shryxx** [comment]
#3978

**Comment by poma123** [comment]
Ez volt előbb megnyitva, nem az amit sk írt. Ha véleménye van, akkor azt szépen leírja ide.

**Comment by skrisz0101** [comment]
tovább írtam....

**Comment by skrisz0101** [comment]
**Szerver**: Mindenholis


5.8, Amennyiben új karaktert szeretnél használni, jelezd azt egy Adminnak! A karakterváltásról Neked kell gondoskodni. Rangot és különböző, már elért tulajdonságokat (mcMMO, Slimefun, szavazói pont, levédés, levédésblokk) átadni nem áll módunkban. A régi, már nem használt neved pedig tiltásra kerül, az 5.7 pont miatt.

Most jött az ékezetes nevű emberek törlése, és hopp, egy ,,Déé" nevű ember Oldot vett, de most közelető neki karaktert váltania. Mi legyen? :)

Alapból is kaki ez a szabály, mert ha valaki októberben vesz rangot, majd vált nevet a hó végén, akkor kuka az Ft, amit a szeróra költött? :/
Ugyanez a levédésnél. valakinek van 100k levédése, de ha nevet vált, eltűnik? tudtommal csak 1 parancsba fáj. :/
Ugyanez az mcmmonál meg mittomén még minél

&lNevet akarnak váltani, nem resetelni magukat

**Comment by poma123** [comment]
Akkor hajrá, írhatod ide.

**Comment by andris155** [comment]
Nem tudom miért kell ennyiszer váltogatni a neveket. kb. pár évente egyszer ha vált valaki. Általában szoktunk segíteni szinte mindig. Szerintem felesleges ezen ennyit problémázni.

**Comment by skrisz0101** [comment]
Hát
ok
Akk nem értem minek a szabály rá

**Comment by MrZero1** [comment]
Érdekes módon, amíg ott volt a csoportba a poszt az új szabályokkal kapcsolatban, addig nem tetted szóvá Blade. 🤷🏼‍♂️😅
