### ISSUE TITLE
Szabály, ami kaki :(

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3978]
**Szerver**: Mindenholis

5.8, Amennyiben új karaktert szeretnél használni, jelezd azt egy Adminnak! A karakterváltásról Neked kell gondoskodni. Rangot és különböző, már elért tulajdonságokat (mcMMO, Slimefun, szavazói pont, levédés, levédésblokk) átadni nem áll módunkban. A régi, már nem használt neved pedig tiltásra kerül, az 5.7 pont miatt.

Most jött az ékezetes nevű emberek törlése, és hopp, egy ,,Déé" nevű ember Oldot vett, de most közelető neki karaktert váltania. Mi legyen? :)

Alapból is kaki ez a szabály, mert ha valaki októberben vesz rangot, majd vált nevet a hó végén, akkor kuka az Ft, amit a szeróra költött? :/
Ugyanez a levédésnél. valakinek van 100k levédése, de ha nevet vált, eltűnik? tudtommal csak 1 parancsba fáj. :/
Ugyanez az mcmmonál meg mittomén még minél

&lNevet akarnak váltani, nem resetelni magukat

**Comment by poma123** [comment]
#3978

**Comment by skrisz0101** [comment]
de tovább írtam csak, annyi .-.
