### ISSUE TITLE
2 havi szavazás pontot vesztett el állítása szerint.

### ISSUE THREAD

**Issue by vace-ai** [TheOld-Crafters/Minecraft-servers#3979]
**Szerver**:Savsziget

Almacsutka játékos állítása szerint, kéthavi szavazat pontja törlődött ismeretlen módon és vissza szeretné ezt kapni. Plusz állítsa szerint, amiről én semmit nem tudok, mindkét tulaj megalázta, (nem tudom, ezért nem ír, elhatároztam hát, hogy írok én helyette.

**Comment by andris155** [comment]
Ahogy a tárgyakért ezért sem tudunk felelősséget vállalni. Bár egyébként lehetetlennek tartom, hogy pont csak az ő pontjai vesztek volna ez. Mindenkinek egy sql fájlban vannak tárolva a pontja és a fájl nem veszett el.
