### ISSUE TITLE
Plugin ötlet

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3980]
Jól jönne, ha lehetne valahogyan szűrni, mit szeretne felvenni a játékos, és mit nem, főleg az old eszközök miatt, amik sokkal gyorsabban teleszemetelik az inventory-t.

https://www.spigotmc.org/resources/itemfilter-1-14-filter-pickup.70334/

**Comment by andris155** [comment]
Több mint 1 éves ez a plugin és szerintem nem sok szerver használja. Nem tartom ezt jó ötletnek berakni így a szerverre.

**Comment by UDPSendToFailed** [comment]
Esetleg másik hasonló plugin?

**Comment by andris155** [comment]
Van?

**Comment by UDPSendToFailed** [comment]
https://www.spigotmc.org/resources/auto-trasher-keep-your-inventory-clean-1-8-1-16.46037/

**Comment by andris155** [comment]
Inkább nem nagyon szeretnék belenyúlni a pickup event-be, szerintem ez is elég sokat van használva. Nem lenne túl jó hatással a teljesítményre, ha minden felvett tárgyat át kellene néznie a szervernek.
