### ISSUE TITLE
Slimefun - hibaüzenet spam limit

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3981]
**Szerver**: Szurvi, sav

Ha üresen vagy hibás recepttel kattintasz a slimefunos gépekre, kiír egy 3 soros hibaüzenetet.
Ha valaki kicsit elbambul, kattint 10et, egyből elpörög a chat. nem lehetne erre valami spam limitet állítani? pl 10mp-ként csak 1x írja ki vagy valami

**Comment by poma123** [comment]
Nem lehet.

**Comment by andris155** [comment]
Az oké, hogy nem lehet, de ez a Slimefun hibája ha egy interakciónál többször írja nem?

**Comment by poma123** [comment]
Nem, egy interakciónál egyszer írja. Az a játékos hibája, hogy spammeli az interakciót.

**Comment by andris155** [comment]
Akkor nem értem ezt az egészet. Ha spam-eli a klikkelést persze, hogy sokszor írja. XD

**Comment by poma123** [comment]
Épp ezért zártam le a jelentést.

**Comment by skrisz0101** [comment]
craftolok 46ot, nem számolom egyesével a klikkek számát, ezért a végén spamelődik, csak azért írtam.

**Comment by poma123** [comment]
Akkor is, ennek így kell működnie.

**Comment by skrisz0101** [comment]
l
