### ISSUE TITLE
mondatvégi pont

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3982]
**Szerver**: Mindenhol asszem

Chaten ugye a mondatok végén automatán rak pontot
Ha a mondat vége ékezetes, nem rak

**Comment by UDPSendToFailed** [comment]
Ugyanitt ha van unicode karakter a mondatban, elveszik a színkód és a formázás.

![kép](https://user-images.githubusercontent.com/16057404/92995839-3c17f280-f507-11ea-8076-0104b3ba1f40.png)

**Comment by andris155** [comment]
A pontot sajnos nem lehet megoldani magyar betűknél.
A színezést megoldottam, hogy működjön a chat jeleknél is.
