### ISSUE TITLE
Rossz leírni, de Slimefun warp :(

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3983]
**Szerver**: Szurvi, sav

Fejleszteni kéne a slimefun warpot. eléggé rég lett felujítva
sok sf cucc nincs felírva

**Comment by andris155** [comment]
Valaki amúgy tényleg onnan tanulja meg a dolgokat? Én játékosként biztos, hogy wiki oldalt használnám inkább meg a YouTube-t.

**Comment by poma123** [comment]
A Wiki már egész jól meg van csinálva egyébként, csak ugye angol.

**Comment by skrisz0101** [comment]
andris igen, van.

**Comment by andris155** [comment]
Valami jobb Slimefun-osnak kellene frissítenie.

**Comment by MrZero1** [comment]
1-2 profi Slimefunos emberke kellene majd, akik segítenek (OCD-ért) frissíteni és kibővíteni a warpot. Akár rendszeresen, aktualizálva ha valami frissül a slimefunban.

**Comment by skrisz0101** [comment]
Mary már írt nekem

**Comment by andris155** [comment]
Hogy áll a warp fejlesztése @skrisz0101 ?

**Comment by skrisz0101** [comment]
hát egyedül nem tudom xd
kell oda egy admin, mert se addolni se építeni nem tudok ott :D
mary írt 1-2 hete, azóta semmi :(

**Comment by MrZero1** [comment]
Ezzel lesz valami?

Talán érdemesebb lenne egy almenüt csinálni a weboldalra, ott lehetnének kategóriák, a fontosabb, lényegesebb dolgokat meg ott leírni.

**Comment by andris155** [comment]
Ott van hozzá a wiki oldal. Ha valaki Slimefun-ozni akar szerintem nem árt egy kis minimális angol tudás hozzá. Mivel folyamatosan változik nem sok értelmét látom ezt lefordítani, mert utána folyamatosan frissítgetni is kellene.
