### ISSUE TITLE
Rubber synthetizer - Slimefun LiteXpansion

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3984]
**Szerver**: Szurvi, sav

A rubber synthetizer nem rég került be és 1200j/s-t fogyaszt (2,5 nukleár reaktornyit)
nem lehetne erre is egy advanced változat? 
@poma123

**Comment by poma123** [comment]
Mire jó, mennyit fogyasszon, stb.

**Comment by skrisz0101** [comment]
majd ha fent leszek, mert recept is kell gondolom :c

**Comment by andris155** [comment]
Azóta sem voltál fent?

**Comment by skrisz0101** [comment]
de, csak mással foglalkoztunk xd

**Comment by poma123** [comment]
Majd visszatérünk rá, ha lesz normális értelme a Rubbernek.
