### ISSUE TITLE
Jail / mute ideje offline is telik

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3985]
Így kb feleslegesen kap bárki is pár órás jail-t / mute-ot, lemegy, aztán mikor később visszajön, már le is járt a büntetése.

**Comment by andris155** [comment]
A megoldás, hogy hetekre vagy napokra kell adni.

**Comment by skrisz0101** [comment]
xddd

**Comment by MrZero1** [comment]
Nem, az nem megoldás :D A tényleges megoldás az lenne, hogy offline nem telik, de ez már régóta így van amúgy.

**Comment by andris155** [comment]
Ezt sajnos nem lehet megoldani.
