### ISSUE TITLE
Slimefun - LiteXpansion miatt elcseszett kinézet

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3986]
**Szerver**: Szurvi, sav ha ott is van
1 recepthez kiírja 9x ugyanazt pl ott, hogy mixed metal ingotból advanved alloyt csinál
+a receptek végén még csak úgy random is odateszi újra
Igénytelen, csúnya, zavaros
![image](https://user-images.githubusercontent.com/25465545/93014237-bbf99780-f5af-11ea-8de2-cef8e363d479.png)
![image](https://user-images.githubusercontent.com/25465545/93014241-c1ef7880-f5af-11ea-81f1-3a9a2b9196c0.png)

**Comment by andris155** [comment]
Már jelentett hiba. Lehet akár javítani is, ha valaki tud programozni.
https://github.com/J3fftw1/LiteXpansion/issues/16
