### ISSUE TITLE
Elemental staff-storm

### ISSUE THREAD

**Issue by Bazsaaaa** [TheOld-Crafters/Minecraft-servers#3987]
**Szerver: Survival**:

Ha akármennyi elemental staff-storm van stackelődve és úgy idézel vele villámot akkor nem csak egy botról vonja le a 'lövést' hanem az összesről ami a kezedben van egy sloton

**Comment by KingDeadZ** [comment]
ebben inkább az a hiba, hogy stackelődik az item

**Comment by andris155** [comment]
Valamikor talán lesz rá megoldás, addig annyi a megoldás, hogy ha használjátok ne stack-elve használjátok.
