### ISSUE TITLE
Elytra bug

### ISSUE THREAD

**Issue by BlackSuit25** [TheOld-Crafters/Minecraft-servers#3989]
**Szerver**:

Sziasztok, Survivalon találtam ezt a hibát, ami a következő : Ha egy elytrával és slime bootsal, vagy szigonnyal közlekedsz akkor ugye elytrával amikor le érkezel akkor a földbe bebugolsz és emiatt nem tudsz gyorsan , leérkezés után röktön tovább ugrani. Ez nagyon idegesítő tud lenni, illetve ha szigonnyal magasan repülsz nagy sebességgel akkor néha beleütközöl a semmibe és zuhanni kezdesz úgy hogy az elytrád  nem kopott, ugyan ez észlelhető tüzijátékkal is

**Comment by andris155** [comment]
Nekem ezeket a hibákat nem sikerült reprodukálni.

**Comment by andris155** [comment]
Sajnos egy másik hibát találtam ezzel kapcsolatban. Ideiglenesen állítottam be rá megoldást, de jelentettem a fejlesztőnek a végleges megoldáshoz. Ha az OldSpace szerveren van ez akkor ott valószínűleg nem lesz erre megoldás.
