### ISSUE TITLE
Plugin Ötlet

### ISSUE THREAD

**Issue by BlackSuit25** [TheOld-Crafters/Minecraft-servers#3990]
Sziasztok, egy plugin ötletem lenne, mégpedig a golden lasso, ami arra hasznos, hogy a barátságos mobokat pl:npc, birka lehessen nagyobb távolságon átvinni, pl:Egy a bázisodtól több tízezer blockra lévő falusikat lehessen hazavinni, ugyan ez működni egy coursed lassoval is csak ez az ellenséges mobokat mozgatná (pl:piglin) . Ez természetesen a Survival szerveren lenne hasznos.

Linkelném is a Plugint hogy ne kelljen keresgélni : https://www.spigotmc.org/resources/golden-lasso.13276/

**Comment by poma123** [comment]
Amint lesz újra MyPet, azzal megoldható a mobok szállítása

**Comment by andris155** [comment]
Ha nem lesz akkor majd kitalálunk valamit.
