### ISSUE TITLE
Savsziget pwarp bug

### ISSUE THREAD

**Issue by szofogado** [TheOld-Crafters/Minecraft-servers#3991]
Savszigeten idönként tönkre megy a pwarpom. Ezt úgy kell érteni, hogy 1. A /is pwarp parancsban nem lehet tab-al beíratni a nevemet. 2. ha manuálisan írom be a nevemet akkor azt írja ki, hogy: Ajjaj!
A táblánlévő szöveg ugyanúgy megmarad. Nem változik rajta semmi.

**Comment by andris155** [comment]
Ezzel így nem igazán tudok mit kezdeni. Kellene pontosan, hogy mikor tűnik el, vagy mit csinálsz amitől eltűnik. Illetve mástól ilyen problémát még nem hallottam.

**Comment by szofogado** [comment]
Megint megtörtént. Nem tudom mi okozza ezt. Most reggel felmentem a szerverre és ez történt: 
![2020-09-14_07 11 13](https://user-images.githubusercontent.com/52892955/93046324-cec8a680-f659-11ea-9fdd-c0525bb6013e.png)
![2020-09-14_07 11 11](https://user-images.githubusercontent.com/52892955/93046326-cff9d380-f659-11ea-9148-d739065dc62e.png) Az első képen azt mutatom, hogy a játék nem jelzi a nevemet. hogy beírhatom a tab-al. A második képen meg azt mutatom, hogy nem működik a pwarp.

**Comment by andris155** [comment]
Ha sima nem nether-ben található fából rakod le a táblát, akkor is eltűnik?

**Comment by szofogado** [comment]
Ma reggel is megtörtént. Kicseréltem nyírfatáblára, de most újra megtörtént. Ha kell küldök róla képet. Nem csináltam vele semmit.

**Comment by andris155** [comment]
Az adatbázis egy óriás káosz volt így inkább reseteltem. Próbáld meg most újra lerakni majd. Ha most is eltűnik lehet a táblás szöveggel van baja. Esetleg próbáld meg rövidebbel vagy nem tudom.

**Comment by andris155** [comment]
A parancs átírtam warpra. Teljesen felesleges oda a p szerintem úgy, hogy úgyis kell elé a savsziget parancs.
