### ISSUE TITLE
OldSpace frissítése 1.16.3-ra

### ISSUE THREAD

**Issue by poma123** [TheOld-Crafters/Minecraft-servers#3992]
**Szerver**: OldSpace

A "terv" elkészítése a frissítéshez. Egyelőre annyit mondanék, hogy az őszi szünetben sort szeretnék rá keríteni, ha normálisan lesz megoldva a CustomCrafting.

- [x] LibsDisguises
- [x] MythicMobs
- [x] WorldEdit
- [x] A receptkönyv frissítése a CustomCraftinghoz
- [x] CustomCrafting (amíg ez nem frissül normálisan, addig szó se lehet az 1.16ról)
- [x] Fő plugin (+ rakétás) frissítése
- [ ] Az NpcCmds parancsok átírása a Citizens fájljaiba
- [ ] Titlemanager + Nametagedit lecserélése a TAB plugin-ra.

**Comment by andris155** [comment]
Frissítened kell majd a worldedit-et is amit akár már most is megtehetsz, mert még támogatja az 1.15.2 verziót.

**Comment by poma123** [comment]
A TitleManager kell a scoreboard miatt. Szóval egyelőre marad a NameTagEdit is. Még lehet, hogy jövő héten megcsinálom NTE nélkül a sima TAB pluginnal, de ez majd kiderül.

**Comment by andris155** [comment]
A frissítés folyamatban van, ahogy láttam.

**Comment by poma123** [comment]
Kész
