### ISSUE TITLE
ghelpop és a némítás egyesülése

### ISSUE THREAD

**Issue by Shryxx** [TheOld-Crafters/Minecraft-servers#3993]
**Szerver**: Gondolom mindegyik

Némítva is lehet ghelpopot használni.
![image](https://user-images.githubusercontent.com/69635280/93068600-009f3480-f67d-11ea-8993-983126785bc6.png)
BTW azért lettem némítva mert azt írtam hogy ne kúrj ki :(

**Comment by poma123** [comment]
Szerintem jó, ha lehet használni a /ghelpop-ot. Ha meg valaki spammeli, akkor ki lesz tiltva tempbannal.

**Comment by Shryxx** [comment]
én adom
