### ISSUE TITLE
Slimefun - fordítás hiba

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3994]
**Szerver**: Szurvi, sav

![2020-09-14_18 28 46](https://user-images.githubusercontent.com/29951969/93112601-7e346600-f6b8-11ea-87c4-7e82c80b6a3f.png)
20 egységek helyett egység
+valahol chunkot is ír

**Comment by poma123** [comment]
Én már rég kijavítottam az összes hibáját a fordításnak, nem lett vele semmi.

**Comment by andris155** [comment]
Mióta poma nyitott egy kérdéses kérést azóta nem lehet ezen javítani. A fejlesztő nem tudja szerintem eldönteni, hogy elfogadja vagy sem. Majd szerintem vissza kell rakni angolra, mert ha jönnek be új tárgyak azok hibát fognak írni a hiányzó fordítások miatt.

**Comment by skrisz0101** [comment]
folyamat jönnek be új tárgyak xd

**Comment by poma123** [comment]
Egyelőre nem is működik a gitlocalize, majd ha meg lesz csinálva kérek moderátort.

**Comment by andris155** [comment]
Hibátlanul működik, de oké. xd

**Comment by poma123** [comment]
Nem működik hibátlanul... Át lett téve a Slimefun4 repo a Slimeun organization-ba, és a gitlocalize ezt nem oldotta meg, így most áll az egész fordításmizéria.

**Comment by andris155** [comment]
Az igen. Elég gagyi amúgy a gitlocalize. Pedig sokkal jobbat is kihozhattak volna belőle a fejlesztők.

**Comment by andris155** [comment]
Mondjuk ott a crowdin aki jobbat akar. Nem is értem, a Slimefun miért nem azt használja inkább.

**Comment by poma123** [comment]
Fizetős.
