### ISSUE TITLE
Ládanyitás - spam

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3995]
**Szerver**: Szurvi, sav

Azt, hogy valaki ládát nyit, sztem felesleges kiírni chatre. 
Max az oldot meg a spawnereset, ha valahogy valaki addolna vagy valami
![2020-09-15_18 53 07](https://user-images.githubusercontent.com/29951969/93240692-be611a80-f784-11ea-9d48-dc28cf224b59.png)

**Comment by andris155** [comment]
Szerintem hasznos, de nem minden ládára kellene. Inkább csak az értékes ritka meg OCD-ért vehetőre.

**Comment by MrZero1** [comment]
Pont azokon van.

**Comment by andris155** [comment]
Szerintem akkor jó ez így.

**Comment by MrZero1** [comment]
Talán a Titkos ládáról lelehetne venni ezt.

**Comment by andris155** [comment]
Levegyem?

**Comment by MrZero1** [comment]
Igen

**Comment by andris155** [comment]
levettem.
