### ISSUE TITLE
Chat jail ötlet

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#3996]
**Szerver**: Survival

Van néhány ember egy bizonyos értelmi szint alatt, aki ugyan nem sértett szabályt, ezért némítást nem kaphat, mégis mindenkit zavar a folyamatos, órákig tartó vergődésével. Az ignorálás nem opció, mindig lesz egy másik hülye, aki válaszol neki, és emiatt ugyanúgy megy tovább a dolog.

Erre lenne megoldás a chat jail, némítást nem kapna a játékos, írhatna chatre, így fel se tűnne neki, de senki más nem látná szövegeit, csak ő maga. 

Amennyiben ez nem megvalósítható, lehetne egy szabály, miszerint: "Aki a globális chat, és ezzel a többi játékos nyugalmát akár szándékosan, akár önhibáján kívül (pl.: mentális visszamaradottságából adódóan) zavarja, az némításban részesül."

**Comment by schmekkels** [comment]
Sajnos a "mentális visszamaradottságából adódóan" rész kicsit meredek, de ha azt befoltoznánk egy "a szerver szellemiségével nem egyenrangú megnyilvánulások miatt"-tal talán PC-bbek lehetnénk. 

Amúgy teljes lendülettel támogatom, mivel időnként mélyen szántó a random zavaró tényezők jelenléte a chaten, és magát a chatet több okból nem áll módomban kikapcsolni..

Ha valamely módon lehetne rendszabályozni az ilyen eseteket az nagyban emelné a színvonalat.

**Comment by andris155** [comment]
Szerintem ennek sok értelme nincs. Azt fogja hinni, hogy nem is kapott semmit és miután lejár a ,,chat jail" ugyanúgy megfogja szedni a chat szabályokat.

**Comment by andris155** [comment]
Nem írunk bele ilyeneket a szabályokba. A mentálisan visszamaradottak is ugyanolyan emberek mint mindenki más és szerintem 90%-ban nem is ez miatt használják helytelenül a chat-et.
