### ISSUE TITLE
Játékidő - köszönet a kockáknak

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#3998]
**Szerver**: Mindenhol

Lehetne valami jutalom x játékidő után. akár valami egyedi tárgy, vagy valami emléktrágy vagy mittomén. akár 10 naponként vagy mittomén. 

Így 99nap 22óra játékidővel rájöttem mekkora kocka vagyok.

**Comment by ketezerhat** [comment]
NUB VAGY SK

**Comment by Kittyoo** [comment]
Afkrisz <3

**Comment by MrZero1** [comment]
Ne legyen már ilyenért is. Sokféle jutalom van ígyis

**Comment by UDPSendToFailed** [comment]
Azért aki 50-100+ napot játszik a szerveren, szerintem valami egyedi, nem feltétlenül értékes itemet megérdemel, ettől nem fog tönkremenni a gazdaság.

**Comment by skrisz0101** [comment]
Nem napi vagy éppen heti,, Jutalom" lett volna, na mindegy :(
Nem is gondoltam feltétlen 20k ocdre
