### ISSUE TITLE
Minemarket pénzvásárlás

### ISSUE THREAD

**Issue by Shryxx** [TheOld-Crafters/Minecraft-servers#3999]
![image](https://user-images.githubusercontent.com/69635280/93392613-66541200-f871-11ea-95b3-a4718dda5de1.png)
![image](https://user-images.githubusercontent.com/69635280/93392635-6f44e380-f871-11ea-8397-93b8f5f6a0cb.png)

Ez a pénzes rész szerintem tök felesleges, mert ha valakinek pénz kell, akkor jobban megéri eladni egy játékosnak az ocd-t. mint a minemarketen venni. Szerveren 1000$ 1 OCD. Vagy lehetne minemarketen is emelni akár. ha nem is 1k/ocd, de legalább ha nem sikerül eladni és csak pénz kell, akkor megérje ocd-ért pénzt venni a minemarketen.

**Comment by andris155** [comment]
Van aki szokott ezt is venni. Attól, hogy neked nem éri meg úgy tűnik másnak viszont igen.

**Comment by Shryxx** [comment]
Akkor most kés és egy lágy mozdulattal véget vetek a szenvedésemnek
