### ISSUE TITLE
Hiba 

### ISSUE THREAD

**Issue by BlackSuit25** [TheOld-Crafters/Minecraft-servers#4000]
**Szerver**: Survival

 A hiba az lenne , hogy a Crop Growht Accelerator nem növeszti meg a terményeket, de nem is használ fertelizert, viszont megkapja az áramellátást , van a környékén növény is, nem tudom mi lehet vele a probléma

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a hibát.
