### ISSUE TITLE
Némítás közben a parancsokat nem lehet használni

### ISSUE THREAD

**Issue by BlackSuit25** [TheOld-Crafters/Minecraft-servers#4001]
Minden szerveren valószínűleg
**Szerver**:

 Ha lemute-olnak akkor nem tudsz semmilyen parancsot használni, még a /home és a /pwarp parancsokat sem

**Comment by Shryxx** [comment]
@andris155 mennyit fizessek hogy ezt megcsináld geci zavaró

**Comment by andris155** [comment]
Ne viselkedj úgy le kelljen némítani és akkor nincs ilyen probléma.

**Comment by Shryxx** [comment]
Ez eddig akkor sem így volt. Ez valami új kínzásos módszer?

**Comment by poma123** [comment]
Akárhogy viselkedik akárki, azért ahhoz csak legyen már joga egy játékosnak, hogy haza tudjon menni.

**Comment by andris155** [comment]
Most elvileg jónak kell lennie. Majd teszteljétek le.

**Comment by skrisz0101** [comment]
Látod @Shryxx, muteoltasd magad és teszteld xd

**Comment by Shryxx** [comment]
Félig megbízható forrásból (én) tudom, hogy még mindig nem mennek a parancsok. A /home /pwarp ilyenek nem működnek still. @andris155

**Comment by andris155** [comment]
Teszteltem és jó. A forrásod félig sem megbízhetó.
