### ISSUE TITLE
Elveszett cuccok

### ISSUE THREAD

**Issue by ketezerhat** [TheOld-Crafters/Minecraft-servers#4002]
**Szerver**: Survival

 Na az a helyzet, hogy haverom aludni kezdett és alvás közben kidobta a szeró és amikor vissza lépett akkor meghalt és a cuccainak se híre se hanva... ÉS ez így nagyon rossz... Nem tudom mi lett de elég érdekes

**Comment by andris155** [comment]
Ezzel így nem tudok mit kezdeni. Még nevét se írtad le. Se egy pontos dátumot és órát, hogy mikor történt ez.
