### ISSUE TITLE
Login bábuk számai

### ISSUE THREAD

**Issue by Shryxx** [TheOld-Crafters/Minecraft-servers#4003]
**Szerver**: Login

![image](https://user-images.githubusercontent.com/69635280/93653077-ac4ada80-fa17-11ea-9281-5a3910afefdc.png)
![image](https://user-images.githubusercontent.com/69635280/93653106-c5ec2200-fa17-11ea-82b9-b905687e09bb.png)
A két kép ugyanakkor készült, ez a két emberke nem jó számot ír maguk felett.

**Comment by poma123** [comment]
Gondolom csak akkor frissül, ha a chunkok be vannak töltve. (ha van ott játékos)
A config szerint 3 mp-enként frissülnie kéne. @andris155 szerinted az megoldja ha betöltve hagyjuk a chunkokat?
Vagy szerinted mi a baja?

**Comment by andris155** [comment]
Nem fog valós időben frissülni nyilván. A belépésnél jól írja utána úgyis mindenki szervert választ. Szerintem nem annyira lényeges. A spawn chunkok minden szerver folyamatosan be vannak töltve.

**Comment by poma123** [comment]
Elvileg van rajta egy 800 (másodperces?) timeout, akár az az is lehet, hogyha addig nem frissül (=nincs fent játékos loginon) akkor utána már nem érdekli egyáltalán.

**Comment by andris155** [comment]
Mint írtam a belépésnél jól írja. Lehet utána ritkábban frissül, de nem is baj. Ahogy szintén írtam úgy se töltenek sokat a belépés szerveren a játékosok.

**Comment by Shryxx** [comment]
Én szeretek nézelődni ott
