### ISSUE TITLE
Old Cipő upgrade

### ISSUE THREAD

**Issue by BlackSuit25** [TheOld-Crafters/Minecraft-servers#4004]
**Szerver**: Survival

 Az old cipőre rá lehetne rakni a lélekjárást, mivel azon kívül minden pozitív enchant rajta van

**Comment by KingDeadZ** [comment]
Soul speed 3 mehetne rá, de afelett az ac nem bírná kezelni, már most sem mindíg birja normálisan kezelni a speed 3 oldcipő kombót.

**Comment by andris155** [comment]
Ma akartam megcsinálni, de a MineMarket nem működik sajnos. Amint jó lesz vagy lesz más, akkor befog kerülni.

**Comment by andris155** [comment]
Mivel így god módban is kopik inkább nem raknám rá. Korábban már került is le enchant róla ez miatt. Több probléma is volt belőle, hogy nem figyeltek oda többen és eltört nekik így.
