### ISSUE TITLE
DustShop

### ISSUE THREAD

**Issue by derpyke** [TheOld-Crafters/Minecraft-servers#4005]
**Szerver**: Savsziget

A boltban az sf részlegnél folyamat buggol a dust eladás, ezáltal elég idegesítő eladni a dolgokat, van mikor pár 64 dustot nem érzékel eladásnál.

**Comment by andris155** [comment]
Letudod rakni egy ládába a szigetedre amit nem tudsz eladni és mellé írni, hogy andris155?

**Comment by andris155** [comment]
Illetve kellene majd a játékosneved.

**Comment by derpyke** [comment]
El tudom adni, csak sokszor van az hogy mondjuk van nálam 10x64 copper dust, el szeretném adni az összeset /shopban és nem érzékel mondjuk 4x64-et. Próbálgatom át tenni az inventorymba vagy pedig kidobni és felvenni van mikor utána érzékeli van mikor pedig utána sem. Játékos nevem derpy.

**Comment by andris155** [comment]
Olyan dust-tal amit adoltam magamnak nem sikerült ezt reprodukálni. Tényleg látnom kellene azt a dust-ot amit nem enged eladni. Bár sokat nem tudok vele tenni, ha mondjuk más az NBT rajta. Egy tárgyhoz csak egyfajtát lehet eladni a shopgui-ban.

**Comment by andris155** [comment]
Lehet ha átmegy egy pár cargo rendszeren más lesz az NBT. De az viszont akkor Slimefun bug lesz.

**Comment by andris155** [comment]
Elvileg az a baja, hogy más sorrendben vannak rajta talán az NBT tag-ek. Sajnos ezen nem tudok javítani.
