### ISSUE TITLE
Discordot érintő, játékosoknak kedvező fejlesztési ötletek

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4007]
**Szerver**: Discord🥰

Discordon lehetne egy szoba, ahol ha hirdetnek pl egy eventet akkor a Poma Bot kiírja oda, és akár egy reakcióval lehetne jelezni, hogy valaki jönne. Mert lehet, hogy valaki fel jönne eventezni egy jót attól, hogy épp nincs fent.

Ötlet2: Egy hirdetés szoba ahol **normális** hirdetéseket lehetne tolni pl boltokról. Így egy picit nagyobb élet lenne discordon is, meg tök hasznos lehet.

**Comment by andris155** [comment]
A pomabot-ot poma fejleszti értelemszerűen erről ő dönt, hogy mit valósít meg benne vagy mit nem. @poma123

**Comment by poma123** [comment]
Nekem jelenleg se időm, se kedvem foglalkozni ezzel és időt belefektetni.

**Comment by MrZero1** [comment]
Az eventeshez annyit, hogy mire valaki megnézi, addigra szerintem elkezdődik az event. 
A másikat átgondolom, de sok szobát sem szeretnék. 
(Egy ötletelős szobán gondolkozom, nem tudom melyik lenne a fontosabb és a kihasználtabb.)

**Comment by andris155** [comment]
Ide GitHub-ra írhat bárki ötleteket és mindegyik el van döntve, hogy jó ötlet bekerül-e vagy sem stb... Discord-on esetleg olyan lehetne, hogy beírják oda. De az a megszavazásos hülyeség amit azt hiszem a Slimefun-nál láttam szerintem borzalmas megoldás. Mert akinek lenne ötlete meg se írja inkább úgy se szavaznak rá elegen hacsak nem a legeslegjobb ötletről van szó.

**Comment by KingDeadZ** [comment]
Az eventeshez annyit raknék hozzá, hogy lehetne hozzá role, amit fel bir venni valaki, és azt lehetne pingelni.
Esetleg lehetne egy külön role, akinek engedélyezve van az, hogy pingelje az eventekhez való roleot, és ezt admintól lehetne kérni.

Egy ötletelős szoba jó ötlet, nem sokan használnak githubot (sadly) pedig egy jó dolog. Discordon a legegyszerűbb megírni a casual embereknek az ötleteket szerintem.

**Comment by andris155** [comment]
Egyelőre ez így nem valósult meg sajnos, de köszönjük az ötletet.
