### ISSUE TITLE
Survival - Fortuna kulcs beváltó

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4010]
Lehetne olyan beváltó falusi a Fortuna kulcsra, mint Savszigeten, mivel stack számra össze tud gyűlni, de a ládája kb értéktelen, felesleges időpazarlás nyitogatni.

**Comment by MrZero1** [comment]
Egyelőre 3 kulcsot raktam be, de majd bővítem más dolgokkal is.
