### ISSUE TITLE
Zúzottkő addolás kreatív móddal

### ISSUE THREAD

**Issue by CubeBarack** [TheOld-Crafters/Minecraft-servers#4012]
**Szerver**: Survival

A kreatívban lerakott követ, túlélő játékmódban való kiütés során megkapjuk zúzottkőként. Több blokkal is teszteltem, azoknál nem működött.

**Comment by kBalix** [comment]
Direkt nincs tiltva #3930

**Comment by MrZero1** [comment]
Pedig lehetne tiltani. 
@andris155

**Comment by andris155** [comment]
Mi értelme?

**Comment by MrZero1** [comment]
Mi az, hogy mi értelme? Az az értelme, amiért a többi blokk is le van tiltva.. 😃

**Comment by andris155** [comment]
De semmi értelme olyan blokkokat tiltani, amiből van egy csomó mindenhol a világban.

**Comment by MrZero1** [comment]
Ilyen alapon akkor az érceket meg a fákat se tiltsuk le.

**Comment by KingDeadZ** [comment]
Aki így addol követ magának, az megérdemelne egy Retardált rangot a szerveren... xd végtelen mennyiségű cobble van.

**Comment by MrZero1** [comment]
Akkor kiveszem az eladást a zúzottkőnél, nekem mindegy

**Comment by skrisz0101** [comment]
Előbb lehet szedni gm0-s zúzottkövet mint
lepakolni egyesével majd kiütni
Legyen öröme annak aki addolja

**Comment by MrZero1** [comment]
Jólvan sk, tudjuk.

**Comment by KingDeadZ** [comment]
Ezzel fölösleges foglalkozni szerintem, nem ér annyit idő ügyileg :p egyszerűbb rtpzni valamelyik vadonba, és pár percig haladni egysíkban előre vagy valami. A legtöbb oldos amúgy sem foglalkozik egyébként ilyenekkel szerintem

**Comment by CubeBarack** [comment]
Zero megelőzött, de szénércből is tele van a világ, mégis tiltva van.

**Comment by andris155** [comment]
A szénércet azért keresni kell valamennyire azért tiltott.

**Comment by MrZero1** [comment]
Engedjük el Icecroft, úgyis Andrisé az utolsó szó.

**Comment by MrZero1** [comment]
Engedjük el Cube, úgyis Andrisé az utolsó szó.

**Comment by andris155** [comment]
A telkeken a telek törléssel sokkal egyszerűbben van végtelen kő, ha valakinek az annyira kell. Mi értelme lenne kreatívban lerakni a követ és azt kiütni? Vagy ha van értelme az egy lassabb megoldás ráadásul. Ezeknek a blokkoknak a kivétele optimalizáció miatt valósult meg, próbálom kímélni az NVMe SSD-t a szervergépben, mert az SSD-kre nem lehet végtelen adatot írni.
