### ISSUE TITLE
SF Metal Forge

### ISSUE THREAD

**Issue by lovi-dev** [TheOld-Crafters/Minecraft-servers#4013]
Surivi serv.

(SF) Metal Forge alá gyémánt blokkot kell rakni mint üzemanyag. Ha kreában teszek alá gyémánt blokkot, azt is megeszi.

**Comment by andris155** [comment]
Meg is fogja. Erre nincs megoldás. Max ha letiltanám ezt az SF gépet.

**Comment by poma123** [comment]
Ez multiblock?

**Comment by lovi-dev** [comment]
Igen, multiblock.

**Comment by poma123** [comment]
Szerintem megoldható. Majd ha lesz időm ránézek.

**Comment by andris155** [comment]
Akkor megtudod oldani?

**Comment by poma123** [comment]
Hétvége.

**Comment by poma123** [comment]
Elvileg javítottam. Tudná valaki tesztelni?

**Comment by poma123** [comment]
Nem lehet megoldani mégsem, javíthatatlan.

**Comment by andris155** [comment]
:(
