### ISSUE TITLE
A MineMarket nem működik

### ISSUE THREAD

**Issue by andris155** [TheOld-Crafters/Minecraft-servers#4014]
**Szerver**: túlélő, savsziget, oldspace, építész

Az az oldal rész, amit a plugin használ nem működik. Tehát gondolom meglehet venni a dolgokat, de egyelőre nem fogja ezeket megadni a szerveren a rendszer.

**Comment by lovi-dev** [comment]
Mmirror beszívta. Kulcsokat vett, de nem kapta meg.

**Comment by andris155** [comment]
Az admin oldal se megy szóval letiltani se tudom.

**Comment by andris155** [comment]
Elvileg most már jó.
