### ISSUE TITLE
2 extra küldetés

### ISSUE THREAD

**Issue by Albinocska** [TheOld-Crafters/Minecraft-servers#4016]
**Szerver**:Oldspace

Az oldspace-n küldetés legyen az enderchest és shulkerbox megcsinálása

**Comment by andris155** [comment]
@poma123

**Comment by skrisz0101** [comment]
tőlem lehet, bár nincs különösebb lényege

**Comment by poma123** [comment]
Szerintem elég annyi előrelépés amennyi jelenleg van. Mivel nincs különösebb lényege, vagy indoka, nem vezet semmi másmilyen itemhez nem látom értelmét.
