### ISSUE TITLE
üllő bugok fixálása

### ISSUE THREAD

**Issue by Albinocska** [TheOld-Crafters/Minecraft-servers#4017]
**Szerver**:oldspace

Sok ilyen van. Egy-két példát írok csak. pl az itekemeket nem lehet átnevezni(pl egy nametag-et jószinak, hogy elnevezhesd a kutyádat jószinak), vagy ha sikerült valahogy egy eszközöd átnevezned, akkor már nem tudod tovább enchantolni

**Comment by poma123** [comment]
Jelenleg direkt van letiltva.

**Comment by Albinocska** [comment]
ooh... nem tudtam
