### ISSUE TITLE
Ládabolt értesítő

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4018]
**Szerver**: Szurvi, sav

Eddig kiírta ki akar vásárolni nálam, ha egy láda kifogyott. egy ideje már nem.  
Annyit ír hogy xy kifogyott, de nem írja ki aakrt venni. én hasznosnak tartottam
Elég lenne a végére bökni pl hogy (skrisz01)

**Comment by andris155** [comment]
Ha ráviszed az egeret a szövegre, akkor kiírja azokat az infókat amit írtál.

**Comment by andris155** [comment]
<img width="309" alt="Capture" src="https://user-images.githubusercontent.com/8324198/94363034-ac09a980-00bf-11eb-93ca-e64710ab5c18.PNG">

**Comment by skrisz0101** [comment]
Köszi, nem tudtam 😅
