### ISSUE TITLE
Advanced Woodcutter Android nem működik Bucket of Oil-ról

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4020]
**Szerver**: Survival

Csak a favágót tudtam tesztelni, de szerintem a többi sem jó, Bucket of Fuel is kérdéses.

**Comment by poma123** [comment]
Holnap lehet jó lesz

**Comment by poma123** [comment]
Most jó?

**Comment by UDPSendToFailed** [comment]
Nem megy egyikkel sem, csak lávásvödörrel. Lehet, hogy az ID változott, pár napja írta valaki chatre.

**Comment by poma123** [comment]
De, működik már.
