### ISSUE TITLE
Advanced Woodcutter Android, Advanced Mass Fabricator elbugol restartkor telkeken

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4022]
**Szerver**: Survival

Ugyanaz történt a favágó androidommal, mint az advanced fabricatorral, újraindítás után megáll, nem lehet jobbklikkel megnyitni, de kiütésre megadja rendesen. A fabricatornál még elment, hogy napi egyszer reggelente kiütöm, és visszarakom, de 16 androidot minden nap beállítani már egy picit szopás.

**Comment by poma123** [comment]
De csak survivalon van ez? Savszigeten nincs?

**Comment by UDPSendToFailed** [comment]
Savszigeten nem tudom tesztelni, nincs hozzá cuccom. :/  Szerintem a PlotSquared pluginhoz van köze, mivel teszten se sikerült reprodukálni.

**Comment by poma123** [comment]
Csak telken bugol el?

**Comment by andris155** [comment]
Nem értem a telek miben más világ ilyen szempontból a többihez képest.

**Comment by UDPSendToFailed** [comment]
Igen, csak telken. Ha próbálom megnyitni úgy, hogy folyamatosan nyomom a jobbklikket, rak bele valamennyi késleltetést, de ez lehet, hogy Slimefun feature, és semmi köze hozzá. 

https://youtu.be/SYug0vha064

**Comment by andris155** [comment]
Szerintem erre nincs megoldás. Nagyon rég jelentették már, hogy elbugolnak az Android-ok. Senki se oldotta meg azóta sem.
https://github.com/Slimefun/Slimefun4/issues/2111
A teszt szerveren amúgy valami custom Slimefun build fut, amit poma rakott össze. Így az ottani tesztelésnek sok értelme nincs.

**Comment by UDPSendToFailed** [comment]
Az már kiderült, hogy az alap Multiverse világon kívül mindenhol elbugolnak, egy /mv unload, /mv load után működnek tovább hibátlanul.

**Comment by andris155** [comment]
Addig oké ameddig nincs rá javítás. De meg kell írni a hibát a fejlesztőnek, mert végleges megoldásnak ez így nem túl jó.

**Comment by poma123** [comment]
Nyugalom, már megvan a hiba oka. Ne írj még sehova semmit.

**Comment by poma123** [comment]
Megoldottam, most már a "PlotSquared előtt" tölt be az addonom, mivel ha nem így lenne (eddig nem így volt), akkor azután tölt be, miután a Slimefun betölti világokból az itemeket és elindítja a tickereket, ilyenkor nem találta meg az androidot, tehát skippelte.
