### ISSUE TITLE
Pénz farm gyorsabbá tétele. 

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4023]
**Szerver**:

Üdv, lehetne lehetőség a /warp bolt-ban a dustok nagyobb mennyiségben (pl. egy inventory) való eladására. Kicsit fáraszó tud lenni a sok katt. 
Köszönettel, és üdvözlettel: Jaffis.

**Comment by UDPSendToFailed** [comment]
Mással is lehet pénzt farmolni, nem muszáj dustokat eladni, ha ennyire fárasztó. :)

**Comment by poma123** [comment]
Jelenleg nincs erre mód a pluginban. Vagyis van, de akkor a vásárlással is véletlenül teljes invet lehetne venni, ami pedig nem jó.

**Comment by KingDeadZ** [comment]
Át lehet írni nagyobb mennyiségre, de szerintem így is eléggé erős pénzfarm a dust, szóval fölösleges, aki azzal akar pénzt szerezni akkor öljön bele időt, és ne adjon el 1nagyládányi dustot 2másodperc alatt
