### ISSUE TITLE
Hónapstaffja szavazás

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4024]
**Szerver**: Survi

Nem tudom, valahogy jobbnak érezném, ha a szavazás részleteit (%, kire mennyi szavazat ment addig) csak adminok látnák. Így most az van, hogy látják, hogy XY staffja érkezett eddig ennyi %, elkezdenek miatta és érte szavazatokat gyűjteni.

Nem tudom, ki hogy látja ezt, a nyílt vagy a titkos szavazás lenne a jobb.

**Comment by mangoshell** [comment]
Teljesen jó ötlet. Chaten is látni, hogy sokakat az "motivál,", hogy xy staffra sokan szavaznak. Részemről lenne egy olyan kérés, hogy a lefizetéses, meg hirdetéses szavazások (szavazz erre meg arra, és kapsz ennyi pénzt) legyenek tiltva. Akár szabályzatban, akár staffok szólnának érte chaten (amit szoktak, de senkit sem érdekel) mert ez így elég igazságtalan. Sok új játékos nem is ismeri a staffokat, csak szavaz, mert írják neki.

**Comment by andris155** [comment]
Szerintem jobb lenne ha nem látnák a végeredmény előtt mennyien szavaztak valakire. Erősen befolyásolja ez, hogy kire szavaznak szerintem.

**Comment by poma123** [comment]
Mostantól csak teljes jogú segítőtől lehet látni /hónapstaffjában a statisztikákat.
