### ISSUE TITLE
Pwarp jog

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4025]
**Szerver**: Survival

Ha már savszigeten mindenkinek lehet pwarpja, survin is lehetne rá valami megoldás. Hiába épít valaki egy tök jó boltot rang nélkül, nem tud vele mit kezdeni, mert pwarpot alig ad el rangos játékos. Nem olyan nagy dolog ez, hogy rangtól lehessen csak jog rá, simán lehetne rá joga tagnak, vagy lehetne játékidőhöz is kötni akár. Ha ebből egyik sem tetszik, akkor lehetne a jól bevált tokenes megoldás, amivel egyszer beírhatnád a parancsot, és törölhetnéd amikor akarod.

**Comment by snowman142** [comment]
abszolút egyet értek

**Comment by andris155** [comment]
Nem lesz mindenkinek a túlélőn. A savsziget egy teljesen más játékosmód.

**Comment by MrZero1** [comment]
Ebből még talán a tokenes lenne a legjobb, de ott is úgy, hogy X napig lenne rá joguk.

**Comment by snowman142** [comment]
> Nem lesz mindenkinek a túlélőn. A savsziget egy teljesen más játékosmód.

és mi lenne ha viptől lehetne pwarp? azt szavazásból ki lehet szedni,havi szinten fent kéne tartani a vipet hozzá ami arra ösztönözne mindeki h napi szinten szavazzon vagy különben nem lesz vipje

**Comment by MrZero1** [comment]
Én a rangok jogain nem változtatnék.
