### ISSUE TITLE
Survival: Iron gólemek a telken nem spawnolnak

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4026]
A telkemen az iron gólemek kb 1.16.3 bevezetése óta nem spawnolnak, a falu rendben van, új falusi is született, de a gólemek sehol.

**Comment by andris155** [comment]
Az 1.16.2 verzió óta kevesebbet rak le a játék a falusiakhoz. A telkeken jelenleg semmi sem tiltja az idézését. Szerintem ez nem a szerver hibája lesz.
