### ISSUE TITLE
Auto Disenchanter és az X melletti egyéb enchant

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4027]
**Szerver**: Szurvi, sav

Ugye Auto Disenchanterben tiltva lett az, hogy  X-es enchantot leszedjen.
Na, van egy olyan csákány hogy Cobalt Pickaxe, amin van tör X és hatékonyság VI.
Hiába rakom be a csákit az Auto Disenchanterbe, nem szedi le a hatékonyságot mert rajta van a tör X. 
Hasznos lenne ha lehetne :(

**Comment by poma123** [comment]
Vagy nem lesz. Akkor lesz, ha valaki belekezd. Én nem fogok ezzel foglalkozni.
