### ISSUE TITLE
Survival - Levédés sethome

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4029]
A /sethome tiltva van más levédésén, de a /esethome, /createhome, /ecreatehome nincs. Slimefunnal is lehet GPS waypoint-ot rakni más védésére.

**Comment by andris155** [comment]
Nem tudom, hogy ez alapból van-e beállítva. De ha valaki beállította gondolhatott volna alias-okra is. Minden parancshoz még van essentials: alias is.

**Comment by mangoshell** [comment]
Egyébként Sf-es Gps cuccot lerakhatod bárhova. Azzal is tudsz "homeot" rakni bárki levédésére

**Comment by poma123** [comment]
Alapból be van ez a configban beállítva, senki se nyúlt hozzá.

**Comment by andris155** [comment]
Javítva.

**Comment by andris155** [comment]
508 OCD
