### ISSUE TITLE
Slimefun - Hunter Talisman engedélyezése

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4030]
Javították már :(

**Comment by andris155** [comment]
Teszteltem és ugyanúgy megduplázza a tárgyakat. Bár felvenni nekem továbbra se vette egy zombi se csontváz alapból a dolgokat. Tehát nem teljesen értem ezt a hibát se azt, hogy most akkor a javítás mit is javított.
