### ISSUE TITLE
1.16-os tárgy emojik

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4031]
Ha már ennyi szimbólumra van kód, lehetne ezekre is.

🪓⛏🎣🗡🔱🏹🧪⚗ 

![kép](https://user-images.githubusercontent.com/16057404/94703757-7a9f1100-033f-11eb-9d45-0e1c3fa2adc8.png)

**Comment by andris155** [comment]
Milyen kódokkal lehessen ilyeneket írni?

**Comment by poma123** [comment]
> Milyen kódokkal lehessen ilyeneket írni?

`:axe:` 🪓
`:pickaxe:` ⛏
`:fishingrod:` 🎣
`:sword:` 🗡
`:trident:` 🔱
`:bow:` 🏹
`:potion:` 🧪
`:splashpotion:` ⚗

**Comment by andris155** [comment]
Beállítva.
