### ISSUE TITLE
Survival - Dustok

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4032]
Szerintem mostmár ténylegesen ideje van, hogy csökkentve legyen az ára az sfes dustoknak, mivel mindenki ezt farmolja... nem éri meg más pénzfarmot építeni, csak az sfes dustgyárat, mert ezt lehet a legkönnyebben csinálni, és 1stack dust 1024$

Mostmár minden 2. ember arra épít, hogy lesz egy nagy dustgyára, aztán rak pwarpot, és mehet a profitshop, és nagyon sokan ki is használják, és ezzel szereznek milliókat 0 energiabefektetéssel.

A dustok árát legalább felezni kéne.

**Comment by UDPSendToFailed** [comment]
Ezzel együtt a normális, nem olyan egyszerűen farmolható tárgyak eladási árát növelni kéne. #3862

**Comment by MrZero1** [comment]
Könnyű leírni, de az árakat megszabni már kevésbé. 
Szokás szerint hiszti lesz a vége.

**Comment by MrZero1** [comment]
Egyelőre a Sulfate-on kívül mindet 256 (4x64) darabot lehet eladni, a sulfate esetében 128 db.
Beszéljünk már privátba srácok, segítsetek nekem ebben. Köszi.

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/94719189-21d97380-0353-11eb-95e5-03688879c05c.png)
valaki kukkol :(

**Comment by lovi-dev** [comment]
Én egy az egybe kivenném a dust eladást és az összes automatán gyártható SF-es cucc eladását.
A kettő együtt ér csak valamit, Amíg lehet automatán gyártható dolgokat eladni, addig végtelen méretekbe nőnek a gyárak.
Egyszerűen ha nem tudja eladni, nem fog rá akkora gyárat építeni...

**Comment by MrZero1** [comment]
Valószínűleg az lesz a megoldás, talán a hétvégéig marad a dust eladás. Addig a jelentés is nyitva marad, így szabadon lehet hozzászólni.

**Comment by skrisz0101** [comment]
Én hagynám a dust eladást nevetségesen olcsón, hogy azért el lehessen adni ha tényleg nem kell valakinek
Pl 128dust 100$ vagy valami

**Comment by KingDeadZ** [comment]
Jó lesz az a mostani ár, ha mást nem legalább a profitshopokat megöli. Ha teljesen ki lesz véve, akkor majd át kell nézni az sfes cuccokat h mit lehetne gyártani nehezen sfben, amit el lehetne adni a boltban.

**Comment by andris155** [comment]
Ahogy láttam már csökkentve lettek az áraik. A savszigeten ha még nem lett csökkentve és szeretnéd akkor szívesen átírom az árakat majd @MrZero1

**Comment by MrZero1** [comment]
> Ahogy láttam már csökkentve lettek az áraik. A savszigeten ha még nem lett csökkentve és szeretnéd akkor szívesen átírom az árakat majd @MrZero1 

Köszi!
