### ISSUE TITLE
Survival - Kreatívos plugin bug

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4033]
Ha bármire raksz egy itemframet kreatívban, majd rá egy itemet surviban, amikor az itemframe kiütődik a survivalos item nem esik ki, hanem törlődik.

**Comment by andris155** [comment]
Jelentettem a fejlesztőnek. Nagyjából 30-60 nap a javítás.

**Comment by MrZero1** [comment]
Addig esetleg a képkeretet lelehetne tiltani kreatívba, amíg nem javítják.(?)

**Comment by andris155** [comment]
Szerintem felesleges. Ha nem a mögötte lévő blokkot ütik ki, hanem a tárgy keretet akkor nem veszik el a tárgy.

**Comment by KingDeadZ** [comment]
Ha eléraksz egy blockot, és az üti ki a képkeretet akkor is elveszik.

**Comment by MrZero1** [comment]
Ezért lenne jó addig tiltani a képkeret lerakását..

**Comment by poma123** [comment]
Letiltottam. @andris155 ne izéljünk már ilyenekkel... belerakhatja akárki az old cuccát aztán kéregethet vissza akármit. Illetve miért van lezárva a jelentés, habár még nincs megoldva a probléma?

**Comment by andris155** [comment]
60 napig felesleges nyitva hagyni, de lehet lesz az 100 is. Itt a megoldás részünkről csak annyi, hogy megírtuk a fejlesztőnek.

**Comment by andris155** [comment]
Old tárgyakat biztosan nem tárgy keretben tárolnék mások helyében. :D

**Comment by andris155** [comment]
+ az is megoldás most már, hogy egyelőre letiltottad. Majd próbálom nem elfelejteni engedélyezni, ha javítja a fejlesztő.

**Comment by MrZero1** [comment]
Sok ember tárolja a dolgait képkeretben, van akik Old cuccokat és más színesnevű szetteket is

**Comment by KingDeadZ** [comment]
Sknak van egy kiállítása, ahol képkeretben vannak a ritka szettek pl :D én is úgy tudtam meg h kernelnél egy carbon press 3at vhogy töröltem ezzel, aztán kifizettem neki :v
