### ISSUE TITLE
Lasszó-buggoltatás

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4035]
**Szerver**: survi, meg ahol Multi Tool van (sf) 

Nos, a buggoltatás folyamata:
-Töltsd fel a MultiToolt
-Válts GraplingHook módba
-Állj szilárd blockon, majd egy előtted lévő blockra katt, hogy kilője a hookot
-Húzd vissza, és ekkor kidob egy lasszót, ami szabadon használható, nem tűnik el. 

Üdv, Jaffis. 

(Jelentettem a weboldalon, kapcsolat résznél, de eddig nem kaptam rá választ.)

**Comment by andris155** [comment]
Mivel fel kell tölteni annyira nem tartom ezt nagy hibának. De egyébként jelentették már és elvileg lesz rá majd javítás is.
