### ISSUE TITLE
Mobcapturer jelentés

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4036]
**Szerver**: Teszt(?)

Levédésen és ploton ugye be lehet fogni az állatokat/mobokat más területén vele.
Nincs megírva sf githubjára, gondoltam érdemes lenne (videó is kéne, de teszt szerón nincs plot)

**Comment by andris155** [comment]
Mi értelme foglalkozni egy olyan pluginnal ami nincs bent a többi szerveren és valószínűleg nem is lesz?

**Comment by skrisz0101** [comment]
azért nincs bent, mert van ez a hiba xd

**Comment by skrisz0101** [comment]
emlékszel?

**Comment by andris155** [comment]
MrZeri azt írta nem kerül vissza így engem nem érdekel ebben milyen hibák vannak.
