### ISSUE TITLE
Ismételten egy fura dolog

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4038]
**Szerver**:Szurvi

Nos, nemtudom, hibának nevezzem-e, de eddig a /warp bolt-ban lehetett backpacket használni, most a szokásos SlimeFunos hibaüzenet, tiltott tárgy. 
Üdv, Jaffis.

**Comment by andris155** [comment]
A színezett hátizsákok valóban nem voltak engedélyezve. Holnap betölt a változtatás és akkor már elvileg tudod majd használni.

**Comment by Jaffis** [comment]
Köszönöm. 
És nemtudom hogy működik, meg mivan, de valami OCD-t említettek. 
Vagy ilyenért nem jár?

**Comment by andris155** [comment]
Nem jár mindenért.
