### ISSUE TITLE
Dust eladás megszüntetése

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4040]
**Szerver**: Survival

Az ár levétel óta teljesen értéktelenek lettek a dustok. Nem is lehet eladni őket normális áron. Ha a boltból kiszednétek, a fontosabb dustokat el lehetne adni, és végre lehetne normális áruk.

**Comment by mnb124** [comment]
Igazából úgy kelett volna megoldani hogy az értékesebb dustok nem esnek ennyit.. az értéktelen pl lead meg mehet olcsóra..

**Comment by MrZero1** [comment]
Ez a végeláthatatlan harc a bolttal kezd igencsak unalmas lenni. 
Akármit tesz az ember, a hiszti lesz a vége, persze az Én irányomba. 
Egyik jelentés alá sem írt senki konkrét árakat, amiket megadtam, meg nyilván nem jó soha senkinek. Nem lesz kivéve semmi.

**Comment by andris155** [comment]
@MrZero1 lehetetlen megfelelni mindenkinek a szerveren. Mindig lesz olyan, akinek valami nem tetszik.

**Comment by andris155** [comment]
Egyébként nem olyan rossz dolog lenne tényleg megszüntetni. Biztosan nem lenne ennyi gyár utána és sokkal stabilabb lenne a TPS is. Nem esne be sokszor 15 körüli értékre mint jelenleg, ami 100%-ban a cargo rendszerek okoznak.
Szóval szerintem is jó ötlet a kivétel, de ez a döntés nem csak rajtam múlik, szóval valószínűleg nem lesz kivéve. :D

**Comment by MrZero1** [comment]
Jólvan, akkor ki lesz véve az összes dust eladása...

**Comment by UDPSendToFailed** [comment]
Mindig is a bolti árak változtatása ellen voltam, de ebben még én is egyetértek, hogy ki kell venni. Ha maradna így, biztosan lenne pár játékos, akik a lecsökkentett árakat a jelenlegihez képest 2-3x akkora gyárakkal kompenzálnák, szóval rosszabb lenne a helyzet, mint volt. Ha ki van véve, feleslegessé válik ennyi dustot legyártani, és normális ára is lehetne, mivel nem a bolti eladás miatt vennék.

**Comment by UDPSendToFailed** [comment]
Esetleg lehetne a helyükön dust vétel, hogy ne maradjon üresen a hely. Átlag dustok 512$/16db, copper 1.5x ennyi (768), iron és gold pedig a duplája, mivel azokból lehet vasat / aranyat, és Lucky Block-ot gyártani. Ha már vas és arany, azoknak az eladási árát is kb felezni kéne, mert ugyanúgy gyárthatók végtelen mennyiségben pár géppel, mint a dustok.

**Comment by lovi-dev** [comment]
> Esetleg lehetne a helyükön dust vétel, hogy ne maradjon üresen a hely. Átlag dustok 512$/16db, copper 1.5x ennyi (768), iron és gold pedig a duplája, mivel azokból lehet vasat / aranyat, és Lucky Block-ot gyártani. Ha már vas és arany, azoknak az eladási árát is kb felezni kéne, mert ugyanúgy gyárthatók végtelen mennyiségben pár géppel, mint a dustok.

Dust eladást megszüntetni.
Glowstone dust/block, nether wart, ghast trear, magma cream/block, quartz /block, flint árát átgondolni.
Illetve csökkentetni minden olyan dologot, aminek az alapanyaga gold vagy iron.

pl. 1 stack hopper-t 5.600-ért lehet eladni a boltba. (201.600 egy inv-vel)
Mi kell hozzá? Vas meg fa. Vasat ontja a dust gyár, fát pedig vágják a droidok. Kvázi nincs alapanyagköltség, csak idő kérdése...

**Comment by MrZero1** [comment]
Az 'átgondolni az árat' nekem nem segít.

**Comment by valtinator** [comment]
> Jólvan, akkor ki lesz véve az összes dust eladása...

Alapból egyetértenék vele, de picit azért gondoljuk ezt át szerver economy szempontjából:

Jelenleg vannak bizonyos játékosok a szerveren akik a jó áron eladható dust korszakában megszedték magukat "mágnásokká" váltak, ha kivesszük a dustok eladását nekik a monopol helyzetük csak erősödni fog, egy unfair előnyük lesz mindenki mással szemben, mert már nem lehet utánuk csinálni így azt, amit ők megtettek. A dolgok nerfelésével mindig az a baj, hogy hatalmas előnyökhöz juttatja azokat akik előtte kihasználták az adott rendszert, így lesz egy szerver pár milliomos játékossal, és pár emberrel akiknek vannak százezreik ami gyorsan elfogy, és utána az árak le fognak esni, vagy ha nem senki sem fog tudni megengedni magának semmit ah-n vagy player boltokban csak az a pár ember akik jelenleg sok millió tartalékot halmoztak fel. Ez egy szerver megfelelője a real life pár gazdag sok szegény esetének.

**Comment by valtinator** [comment]
> Egyébként nem olyan rossz dolog lenne tényleg megszüntetni. Biztosan nem lenne ennyi gyár utána és sokkal stabilabb lenne a TPS is. Nem esne be sokszor 15 körüli értékre mint jelenleg, amit 100%-ban a cargo rendszerek okoznak.
> Szóval szerintem is jó ötlet a kivétel, de ez a döntés nem csak rajtam múlik, szóval valószínűleg nem lesz kivéve. :D

Szerintem a dust eladás kivétele egy okból nem fogja megszüntetni a hatalmas gyárakat:
Lucky gyártás, amihez ugye hatalmas mennyiségben kell gold dust, olyan mennyiségben hogy a gyárak mérete nem változna nagy mértékben, csak a goldon kívül az összes többi dust kukába menne, de az infrastrukrúra megmaradna csak a gold dust miatt.

Persze ha piacon lehetne venni gold dustot az ezt is megoldaná, de ha nem lehet dustokat eladni miből lenne pénze a játékosoknak a nagy mennyiségű gold dust megvételére? (mert sajnos a luckyhoz nagy mennyiségben kell) Persze tudom, kifarmolható az a pénz más módon is de az ember a legkönnyebb utat fogja választani, és a pénz kifarmolásánál (dust eladás nélkül) egyszerűbb inkább a dustot legyártani.

**Comment by UDPSendToFailed** [comment]
> Azóta eszembe jutott, hogy talán lehetne minden kézzel learatott teljesen megnőtt répa után adni 50-100$-t a játékosnak amint kiüti a répát (nem az eladásért hanem az aratásért ahogy az mcmmo is érzékeli mikor növényt ütök ki), így nagy ipari méretű gépesített farmok helyett a kézi nem automatizált picit kisebb és cargo mentes farmok lennének előnyben részesítve/jutalmazva/ösztönözve.

Ez akár a Jobs pluginnal is megoldható lenne, de normális beállításokkal, limitált maximum szinttel, nem úgy, mint régen, mikor egy mob megölése adott több 10000 $-t. Így nem tenné tönkre a jelenlegi pénzrendszert, és lenne valamilyen farmolási lehetőség, amit használhatnak a játékosok a Slimefun gyárak építése helyett, a bolti eladást sem lehetne kijátszani automata farmokkal. Mindig azt fogják csinálni az emberek, ami megéri, régen épültek a kaktuszfarmok, aztán a ghast tear,  most a dust. Sajnos ez a gond, hogy minden más lehetőség meg lett szüntetve, így a megmaradt opciókat használják ki a játékosok.

A Jobs beállításában szerintem sokan segítenének, nem látok rá okot, hogy miért ne kerülhetne be. 

TL;DR részemről: Dust eladás megszüntetése, vétel tábla a helyére, Jobs plugin berakása **normális** fizetésekkel, és limitált maximális szinttel (esetleg ranggal nagyobb max szint).

**Comment by andris155** [comment]
Jobs, mcMMO. ennyi sok event-et már nem bírna el a blockbreakevent és akkor már azt sem igazán bírná egy magon a CPU.

**Comment by andris155** [comment]
Vagy Jobs vagy mcMMO. A 2 együtt már túl sok.

**Comment by UDPSendToFailed** [comment]
Sok szervert tudok, ahol hibátlanul működik a kettő együtt, még config opció is van direkt erre, amivel össze lehet kapcsolni a képességeket. Esetleg egy teszt időszakra bekerülhetne, aztán ha nem laggoltat, marad.

![kép](https://user-images.githubusercontent.com/16057404/95066190-560db500-0702-11eb-80ca-549c06aabfb3.png)

**Comment by andris155** [comment]
Én nem fogok már semmi újat berakni az biztos. Így is borzalmas a szerver teljesítménye több játékossal.

**Comment by UDPSendToFailed** [comment]
Szerintem hosszabb távon segítene rajta, mivel nem lenne annyi cargo betöltve. Most a legtöbben úgy farmolnak, hogy állnak a gyár mellett órákig, de igazából nekem mindegy, csak írtam egy lehetséges megoldást.

**Comment by mangoshell** [comment]
> Én nem fogok már semmi újat berakni az biztos. Így is borzalmas a szerver teljesítménye több játékossal.

Nem kell nagyon félni a több játékostól

**Comment by skrisz0101** [comment]
pedig valamivel meg kéne fogni a játékosokat, azért a napi 10 játékos szurvin nem a legjobb 👍

**Comment by KingDeadZ** [comment]
jobs>mcmmo

**Comment by skrisz0101** [comment]
@MrZero1 te mit gondolsz?

**Comment by MrZero1** [comment]
Azt, hogy valamit gyorsan, de hatékonyan kell kezdeni a pénzrendszerrel, mert előbb-utóbb élvezhetetlen lesz ilyen szempontból a játék. Kezdve a gyárak mellett afkolással meg a társaival.

**Comment by MrZero1** [comment]
A játékosszám meg csupán azt tükrözi, hogy suli van. Hétvégén is voltak azért, ez mindig ilyen holtpont.

**Comment by andris155** [comment]
Ennyi játékos mellett mondjuk legalább játszható a szerver és nincsenek laggok. Ha komolyabban akarunk fejlesztgetni a jelenlegi Slimefun-os rendszerrel teljesen 0 értelme van, mert 40+ játékosnál laggolni fog az egész úgyis.

**Comment by UDPSendToFailed** [comment]
Ezért kell a Slimefun mellé valamilyen más pénzszerzési opció is, ha nem éri meg gyárakat építeni, mert nem jól fizet, értelemszerűen nem fognak annyian belekezdeni. Jelenleg a legjobb pénzszerzési módszer az, hogy állunk a gyárak mellett, és várunk. Ha lenne helyette más, amit érdemesebb csinálni, kevesebb lenne a betöltött cargo, ezzel együtt a lag is.

**Comment by Sanszi** [comment]
Egyetértek, hogy gyors és hatékony változtatás kell. Szerintem a jobs nem lenne rossz ötlet. Olvastam, hogy Andris szerint túl sok energiaforrást használna, az MCMMO mellett, viszont látok más szervereket ahol fut a kettő együtt. Több szempontból is jó volna szerintem:
-Nem a slimefun lenne az elsődleges pénzszerzési módszer.
-Mindenki számára elérhető.
-Játékra ösztönözné a játékosokat, a gyárak melletti afkolás helyett.
Ha csak megpróbálni is, de úgy gondolom megérné.

**Comment by KingDeadZ** [comment]
mcmmo sztem simán mehetne akkor is, és jöhetne a helyére jobs, ha egyáltalán nem fér meg a 2 egymás mellett mert elm. sok erőforrást használna

de ha nem érzékeli a cobble és a basalt kiütést, akkor én azokat kapásból tiltanám belőle mondjuk mert azokra léteznek generátorok p.p

**Comment by andris155** [comment]
A dust eladás akkor így szerintem nem kerül megszűntetésre hiszen semmit se változtatna valószínűleg. A Jobs szintúgy nem fog bekerülni.
Más változások a jövőben lehet lesznek, de az már a Dust-tal kapcsolatos így ezt lezárom.

**Comment by andris155** [comment]
A dust eladás akkor így szerintem nem kerül megszűntetésre hiszen semmit se változtatna valószínűleg. A Jobs szintúgy nem fog bekerülni.
Más változások a jövőben lehet lesznek, de az már nem a Dust-tal kapcsolatos így ezt lezárom.

**Comment by mangoshell** [comment]
Az szép

**Comment by skrisz0101** [comment]
miért ne változtatna semmin? nem értem xd

**Comment by MrZero1** [comment]
Kikerült a dust eladás. Egyelőre legalábbis biztos.
