### ISSUE TITLE
Spawnerek behozatala savszigetre

### ISSUE THREAD

**Issue by Magicaly1** [TheOld-Crafters/Minecraft-servers#4041]
**Szerver**:Savsziget

Úgy gondolom,hogy savszigetre bekerülhetnének a spawnerek (valamilyen közepes áron)

**Comment by MrZero1** [comment]
Szia. Nem kerülnek vissza. Kiütni nem lehet őket, a meglévőket is kérésre mozgatja Admin, de nem minden esetben.
