### ISSUE TITLE
Cheat védelem lassú esés effekt hiba

### ISSUE THREAD

**Issue by valtinator** [TheOld-Crafters/Minecraft-servers#4042]
**Szerver**: Survival

Legendás csizmával eddig lehetett futni és futásból ugrani is minden gond nélkül, de 2-3 napja ha sprintelve ugranék, nem engedi, azonnal visszadob, konkrétan az ugrás első pillanatában megakaszt (vélhetően anti-cheat hiba), speed 2 beacon hatása mellett még futni sem enged, amint sprintelni kezdenék azonnal megakaszt, pedig a csizma speed 1 effektje nem is stackelődik a beacon speed 2 effektjével.

**Comment by andris155** [comment]
Azt írta a fejlesztő, hogy ha lesz ideje javítani fogja. Ha van még ilyesmi hiba mindenképpen várjuk a jelentésed azzal kapcsolatban is.

**Comment by andris155** [comment]
Elvileg javította a fejlesztő.
