### ISSUE TITLE
Építész+ - Építész

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4043]
**Szerver**: Ép+

Elvileg az Építészek is tudnak némítani. Ne tudjanak, azért van ott a Staff rang.
Esetleg a jailt/bant is meglehetne nézni, ha arra is lenne joga a sima Építész rangnak, akkor azokat is tiltani

**Comment by poma123** [comment]
Kész

**Comment by MrZero1** [comment]
Köszönöm ☺
