### ISSUE TITLE
Hiba?

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4044]
**Szerver**: Survival

![kép](https://user-images.githubusercontent.com/29709854/95013764-aae9f680-0642-11eb-9a48-ebebe0224911.png)

A játékos kergeti a rókát, be akarja fogni petnek, azonkívül semmit nem csinál :D Nem tudom, ezt kell e jelezni?

**Comment by andris155** [comment]
Talán igen. Legközelebb kellene egy videó a játékosról, hogy mit csinál pontosan és egy TPS adat is hozzá.
Videó nélkül ezzel így nem igazán tudok mit kezdeni. Kergethetek rókákat, de nem hiszem hogy nekem ezt fogja írni.
