### ISSUE TITLE
Survival - Nem lehet törölni a netherstar nevét

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4045]
Találtam pár elnevezett netherstar-t, nem lehet őket simára visszaalakítani. Ha elnevezek egy újat, azzal is ugyanez történik, használhatatlanná válik.

![kép](https://user-images.githubusercontent.com/16057404/95016717-0e7d1f80-0655-11eb-8481-ab28153edc8a.png)
![kép](https://user-images.githubusercontent.com/16057404/95016722-150b9700-0655-11eb-9974-083960692855.png)

**Comment by andris155** [comment]
Ez a vanilla játék hibája. Már jelentették a Mojang-nak.
Ha egy space-t adsz meg üllőben a nether star nevének, akkor törli az egyedi nevet egyébként. Addig ez a megoldás erre.
https://bugs.mojang.com/browse/MC-124327
