### ISSUE TITLE
MineMarket elírások, frissítések

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4046]
**Survival:**

- Prémium rang

Ha tele a szerver, akkor is _be tudsz_ lépni.
![kép](https://user-images.githubusercontent.com/16057404/95016978-cced7400-0656-11eb-9a50-e9d9d6e233fd.png)

- Tárgyak

Nem lehet ékezetes névvel felmenni.
![kép](https://user-images.githubusercontent.com/16057404/95017036-235ab280-0657-11eb-8057-2a5a4cb5e285.png)

- Spawnerek

Nem lehet ékezetes névvel felmenni.
![kép](https://user-images.githubusercontent.com/16057404/95017165-f78bfc80-0657-11eb-92a1-df63597a29cf.png)

**Savsziget:**

- Elit rang

Ha tele a szerver, akkor is _be tudsz_ lépni.
![kép](https://user-images.githubusercontent.com/16057404/95017292-c95aec80-0658-11eb-921b-de2f81332207.png)

- Tárgyak

Nem lehet ékezetes névvel felmenni.
![kép](https://user-images.githubusercontent.com/16057404/95017323-fd361200-0658-11eb-8d9e-06ad71f8f02e.png)

Survival tárgyak részlegen "Old", itt "OLD".
![kép](https://user-images.githubusercontent.com/16057404/95017350-20f95800-0659-11eb-9834-cd3e64b2791f.png)

l -> é
![kép](https://user-images.githubusercontent.com/16057404/95017367-38384580-0659-11eb-9c91-33d3f2081c92.png)

**OldSpace:**

Space+ rang

&&72név -> &2név
![kép](https://user-images.githubusercontent.com/16057404/95017528-19867e80-065a-11eb-98b0-432b12fb7431.png)

&2' -> &2
![kép](https://user-images.githubusercontent.com/16057404/95017554-3e7af180-065a-11eb-95b0-bb23cac98c7b.png)

**Comment by andris155** [comment]
A betudsz egyben van helyesen. Ezt nem fogom átírni.

**Comment by poma123** [comment]
Nincs egyben a be tudsz. Itt az ige és az igekötő közé beékelődik egy szó, így külön kell írni mind a hármat. Be tudsz menni. Meg tudod csinálni. Meg lehetne csinálni. stb.

**Comment by andris155** [comment]
Én inkább az oldalnak hiszek.
<img width="542" alt="Capture" src="https://user-images.githubusercontent.com/8324198/95235566-0fa17e80-0806-11eb-90b4-569058635f65.PNG">

**Comment by poma123** [comment]
írd be, hogy "betudsz menni"... másodikos tananyag.

**Comment by poma123** [comment]
Miért törölted ki amit írtam? :D

**Comment by andris155** [comment]
Javítottam a leírt hibákat. 508 OCD.
