### ISSUE TITLE
Slimefun - új addon (luffyvalami)

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4047]
**Szerver**: Szurvira, savra

Sorolom sorba mi jönne be vele, mert sok dolog (és menő)
Watering can:  10használatos üvegpalack kb, jobb katt a vízre és tele lesz 2 dologra jó:
   1.: kattintgatni kell vele a növényre, hogy minimálisan felgyorsítsa a növekedését. (1katt = 1 nagyon minimális növekedés)
   2.: kb 2mp-s lassúságot okoz egy játékosra, ha jobb kattolsz vele (ez 10-et levesz alapból)

Scythe: kapa, amivel egyszerre 5 növényt lehet learatni.

Upgraded lumber axe: mivel tiltva a sima, gondolom ez nem kerül be (nem emlékszem a sima miért van tiltva xd)

Water spinkler: Ha van alatta víz, és van áram, megnöveszti a növényeket (menő effektet is ad)

Auto Crafting Table: Auto vanilla craftoló, rohadt sok áramba fáj sajna :(

Auto Ancient Altar: 1700J/s, csoda ha valaki tudja használni, de azért menő lenne (3+ reaktor kell, hogy csak ezt elbírja)

Ender Chest Insertion/Extraction Node: leraksz egy ec-t, mögé egy extract vagy insert nyilat, mögé egy ládát, akkor ki-be pakolgatja a ládából az ec-be a cuccokat, vagy fordítva.
nem tudom mennyire ütközne az ec pluginnal, az nincs teszten, nem tudtuk meglesni.

Helicopter hat: Ugyanaz mint a jetpack, csak nagyon olcsó, túl olcsó is, ez ne kerüljön be.

BackPack loader/Unloader: A táskából ki,- és beteszi a cuccokat. elég menő, gyorsítja a raktárköltöztetést (itt megjegyezném, hogy agyonteszteltük és buggmentes, kernel és én)

Upgraded  Explosive csáki és ásó: tiltva a sima is, szóval ez se kerülne be

Ancient Rune [Fireproof]: amelyik itemre rádobjuk ezt, FireProofot kap. (mint a soulbound rúnánál)

Dolly: ha jobb kattolunk vele egy ládára, akkor azt belerakja (nagyon menő xd)

Auto Magic Workbenc: ez  is 1700/s J, csoda ha valaki használni fogja, de menő
Auto Armor forge: ez is 1700/s J, csoda ha valaki használni fogja, de menő

Crank generátor:  multiblock gép, huzogatni kell egy kart hogy legyen áram xdd
(Sztem tökély lenne a kezdőknek, mert nem is drága és nem is termel sokat)

Foundry: Ez is multiblock gép, bele kell rakni egy lávásvödröt hogy működjön
pakolhatsz bele dustokat (max 40 duplaládányit), és kiveheted belőle sztekkesével dustként vagy ingotként! nagyon hasznos lenne, cargo lagg kisebb lenne a dust raktárak miatt, mivel csak egy ,,láda" kéne. 

Még ne kerüljön be, jelentenénk kernellel a hibáit, de ha nem kerül(ne) be, akkor felesleges jelentenünk (nincsenek nagy hibák, de azért van 1-2 apróbb)

**Comment by KingDeadZ** [comment]
Folyamatosan fissül amúgy, szóval nagyon jó cucc. am asszem azért lett tiltva a lumberaxe mert levédéseken is kivágta a fát maybe, de ha a kreás fát kiütötte (ami fix h megtörtént) akkor nem látom annak az értelmét h miért ne kerüljön be xd

**Comment by Sanszi** [comment]
Eléggé úgy hangzik, mint ami energiaigényes (szervergép szempontjából).

**Comment by IcyAlex** [comment]
Az Auto Crafting Tablet és a Foundryt nagyon adnám. :P

**Comment by andris155** [comment]
Nyilván az extra enderchesteket nem támogatja, csak az alap vanilla enderchestet.

**Comment by MrZero1** [comment]
Fireproof rúna gondolom tűzállóvá teszi azt, amire rárakják. Ha igen, akkor ne kerüljön be. 

Helicopter hat se.

Cracked generator esetén mennyire jó, ha gyorsan húzogatják a kart? Illetve egy sima órajellel (vagy olyannal, amire nem jelez a rendszer) is megy? Amennyiben igen, akkor ez is kilőve.

Az 5 növényes aratós is túl egyszerű, az se.

**Comment by skrisz0101** [comment]
cracked generátor karja igazából meg se mozdul, csak jobb klikkelni kell rá. Kernel tesztelte, órajellel nem megy.

**Comment by skrisz0101** [comment]
> Az extra enderchesteket nem támogatja, csak az alap vanilla enderchestet.

és nem ütközne szerinted? vagy nem lenne valami hiba? végülis ki lehet próbálni, max ki lesz véve

**Comment by poma123** [comment]
Az ilyen táskába tevős és kivevős illetve az ec-be tevős részeket én letiltanám. Nagyon új az addon, biztos hogy ezekkel még előfordulhat hiba. Jobb félni, mint megijedni.

**Comment by andris155** [comment]
Nem ütközne semmi az ec-s résszel.

**Comment by andris155** [comment]
Ha lesz időm átnézem alapszinten és bekerül. Az ec-vel továbbra is 100%-ig kompatibilis. De nyilván a plusz enderchest-eket nem látja hiszen az egy külön plugin-ban tárolva amit ez nem támogat. Csak az alap vanilla enderchest-et látja és kezeli. Én nem szeretném tiltani a táskás dolgot és ec-st sem. Biztosan inkább más jellegű hibák vannak benne már ha vannak. Talán még nem olyan nagy ez a bővítmény így majd tudom tesztelni is a dolgokat benne.

**Comment by poma123** [comment]
"Biztosan inkább más jellegű hibák vannak benne már ha vannak." Honnan tudod hogy jól teszi bele a két inv között a cuccot? Honnan tudod hogy nem duplikálhatja valamikor? Új a fejlesztő, kezdő, új az addon is. Nem hiába írom le amit leírok... De oké, akkor én itt most leírom és nem vállalok felelősséget, hogyha mégis lesz benne hiba! :D

**Comment by andris155** [comment]
Szerintem ennél bonyolultabb lenne benne így is duplikálni. Meg ahogy olvastam már elég jól tesztelték akik írták ezt az ötletet ide.

**Comment by MrZero1** [comment]
Ha a gyanú is felmerül, hogy lehet duplikálni valamivel, mert olyan, akkor ne kerüljön be. Ki akarna emiatt egy teljes szerver resetet?

**Comment by andris155** [comment]
A Slimefun-ban is biztosan van duplikációs hiba. Ha így állunk hozzá akkor semmi se fog bekerülni ami nagyobb dolog.

**Comment by andris155** [comment]
Le fogom tesztelni amennyire lehet. 100%-ig sajnos nem tudom azért.

**Comment by andris155** [comment]
Az extra dolgok jórésze ahogy írtátok meg sem éri. Illetve tényleg elég kezdő a fejlesztő és nem nagyon teszteli a javításait sem. Találtam még több dolgot is amiket szintén tiltani kellene, mert lehet vele kreatívból adolni, X-s enchantot leszedni meg stb... Egyelőre ezt így inkább nem raknám be. Majd ha később már kiforrottabb lesz akkor talán.

**Comment by skrisz0101** [comment]
okés, amúgy melyikkel lehetett addolni?
