### ISSUE TITLE
Egyből +1000 játékos a szervereken ötlet!

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4050]
**Szerver**: Nemtom hova, megy a login szeróra

Among us minigame
http://phoenixsc.me/download-links/among-us-1-16-3/
Videó:
https://www.youtube.com/watch?v=me9Tt6rK6nk

**Comment by poma123** [comment]
Disagree, és tök felesleges. Jó a játék, de megint ki szívna vele, hogy ez bekerüljön? :D
