### ISSUE TITLE
Hazug lottó

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4051]
**Szerver**: Survi
 

![image](https://user-images.githubusercontent.com/69635280/95195189-7eff7a00-07d6-11eb-9791-870954e95bc5.png)

**Comment by poma123** [comment]
Ezt olyankor írja ki, amikor történik a sorsolás, és senki se vett lottót. A fordítás rossz, jobb lenne: "Nincs eladott szelvény." vagy valami hasonló.

**Comment by andris155** [comment]
Javítva.

**Comment by mangoshell** [comment]
5000 ocd!

**Comment by andris155** [comment]
Mindenért nem jár. De szerintem, ha valaki OCD-t akar hibajelentéssel szerezni, akkor a Slimefun-ban még mindig van bőven hiba, amik egy része olyan szintű, hogy simán jár érte.

**Comment by andris155** [comment]
Ettől függetlenül persze köszönjük az észrevételt.
