### ISSUE TITLE
Bújócska bug

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4052]
Szerver: Survival

Hiba:  Láthatatlanok a shulker box kinézetű bújók.

**Comment by MrZero1** [comment]
Melyik arénában van shulker? Mindenhonnan ki lett szedve, emlékeim szerint.

**Comment by Sanszi** [comment]
Aréna3. Álcaválasztóban is benne van, de van esély hogy sulkerként spawnoljon a játékos egyből.

**Comment by andris155** [comment]
Kivettem a blokkok közül a shulker boxot.
