### ISSUE TITLE
Hg ötlet

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4053]
**Szerver**: Szurvi

Lehetne minden mapon 1-1 falusi cserekereskedő aki a smaragdokért adna limitált tárgyakat, amiket nem lehet szerezni ládából, ha már szerezhető smaragd

+1: a mérgezés nyíl  túl op, 1lövés levisz fél életre

**Comment by KingDeadZ** [comment]
az ötlet jó, poison nyíl maradhat, de ha kikerül akk mehet vele a pajzs is és a tridentxd

**Comment by MrZero1** [comment]
A mérgező nyílvesszőt lehetne cserélni pl. teknősmesteres nyílra(?)

**Comment by skrisz0101** [comment]
az ilyen kétes nyíl, egyszerre rossz és jó is
