### ISSUE TITLE
Stone generátor bug

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4054]
Szerver: Savsziget

Van egy stone generátorom savon ami működött korábban, de már nem. A lávát a víz fölé helyezem és annyi történik, hogy álló víz lesz a folyóvízből és lebeg a láva a víz felett. Reprodukáltam singleplayerben a generátort és ott működik ahogy kellene (1.16.3 singleplayer). 
Csatolok képeket is alább:

![2020-10-06_20 17 40](https://user-images.githubusercontent.com/37781201/95243764-63fe2b80-0811-11eb-8f28-eb6618faaee1.png)
![2020-10-06_20 17 57](https://user-images.githubusercontent.com/37781201/95243775-66f91c00-0811-11eb-892d-9e750da4f83f.png)
![2020-10-06_20 17 58](https://user-images.githubusercontent.com/37781201/95243777-66f91c00-0811-11eb-8e02-56b791d10160.png)

**Comment by andris155** [comment]
Megírtan a fejlesztőnek, de nem tudom eldönteni, hogy direkt tiltották-e, mert ezzel a megoldással mondjuk elég gyorsan lehet szigetet készíteni ha ráfolyatod a vízre a lávát.

**Comment by Sanszi** [comment]
nem tudom, de a kő csak 1 pontot ér, amivel nem sokat tesz hozzá a szigetszinthez.

**Comment by andris155** [comment]
Azt írják nem hiba.
https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/issues/75

**Comment by andris155** [comment]
Lehet később bizonyos egy koordinátán felül működni fog. Majd kiderül.
