### ISSUE TITLE
15:15, random kidobott 9 embert a 12ből

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4055]
**Szerver**: Szurvi

Fagyás, majd 9 embert kidobott, maradt 3

**Comment by andris155** [comment]
A cargo okozta fagyás miatt.
![121044321_2838178976415654_3717174499772206304_n](https://user-images.githubusercontent.com/8324198/95336795-5b5d3200-08b1-11eb-8ca4-61b25f769d07.png)

**Comment by andris155** [comment]
A fejlesztő egyből lezárja az ilyen jelentéseket. Nincs megoldás rá. Az hogy nevetséges minőségben van optimalizálva az nekik nem számít hibának.
