### ISSUE TITLE
Mc szerverek oldal

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4056]
Googleba beírtam: Magyar minecraft szerverek ->első link
Nincs ott a toc, hh?
https://hu.minecraft-multiplayer-servers-list.com/

**Comment by andris155** [comment]
Mert ezt az oldalt én személy szerint utálom. Gagyi szerintem. Egy időben bányász script-et is futtatott a látogatókkal ez az oldal.

**Comment by skrisz0101** [comment]
hááát, oké.
bár szerintem számítana xd

**Comment by MrZero1** [comment]
Érdemes lenne ide is kirakni magunkat.

**Comment by andris155** [comment]
Akkor rakd ki. Én ezzel az oldallal nem fogok foglalkozni.

**Comment by MrZero1** [comment]
https://hu.minecraft-multiplayer-servers-list.com/server.php?id=10817

Itt van. Esetleg bekerülhetne a linkek közé. :)

**Comment by andris155** [comment]
Nem rakom be a linkek közé. Ezt az oldalt én nem fogom hirdetni.

**Comment by MrZero1** [comment]
Pedig be lehetne rakni, neked semmibe nem telik, ellenben a szervernek jó reklám, a játékosoknak meg mégegy szavazós oldal.

**Comment by andris155** [comment]
Sajnálom, de ez egy számomra nem megbízható oldal és senkinek se fogom ajánlani így, hogy még kössék össze a Facebook-al is. Aki szavaz saját felelősségre teszi, de mi nem fogunk erre senkit sem bíztatni.

**Comment by MrZero1** [comment]
Egy lépést előre, kettőt hátra.

**Comment by UDPSendToFailed** [comment]
Nálam nem is működik, még úgy sem, hogy kikapcsoltam az AdBlock-ot, és a követő cookie-k tiltását, be se hozza a Facebook-os bejelentkező oldalt.
