### ISSUE TITLE
GlobalWarming tesztelés

### ISSUE THREAD

**Issue by poma123** [TheOld-Crafters/Minecraft-servers#4057]
Egy új, saját Slimefun addont szeretnék csak **TESZTELNI** élesben a Survival szerveren a hétvégén (mondjuk szombaton).

Röviden annyit tud az addon, hogy előre beállított SF gépek és item receptek, illetve az állatok párosodása kibocsájt egy adott mennyiségű légszennyezettséget. A faültetés és az Air Compressor gép pedig csökkenti a légszennyezettséget. Van egy hőmérő és egy másik mérő eszköz, ami a jelenlegi hőmérséklet emelkedést mutatja. Ha nő a szennyezettség, akkor nő a hőmérséklet is. Vannak következmények, pl. erdőtüzek, jég olvadás, lelassulás, égés stb.

**A TESZTELÉS CÉLJA:** A tesztelés célja az arányok ellenőrzése lenne, hogy megfelelő mennyiségű szennyezettség kerüljön kibocsájtásra olyan szerveren, ahol sokan használnak SF gyárakat és gépeket.

Minden beállítható és **kikapcsolható**, az erdőtűz értelemszerűen csak akkor tud terjedni, ha a tűz terjedés be van kapcsolva az adott szerveren.

**AZ ERDŐTŰZ NEM IS TUD TERJEDNI MIVEL KI VAN KAPCSOLVA A TŰZ TERJEDÉS A SZERVEREN! A JÉGOLVADÁS ÉS AZ ERDŐTŰZ KI LESZ KAPCSOLVA A CONFIGBAN. REMÉLEM ÍGY MÁR VILÁGOS MI A CÉLJA A TESZTELÉSNEK!**

Link az addonhoz: https://github.com/poma123/GlobalWarming

**Comment by andris155** [comment]
Biztosan jóötlet elégetni az erdőket a túlélő szerveren meg elolvasztani a jeges biome-okon a dolgokat? Illetve gondolom elolvadnak a játékosok által levédett jegek, illetve a saját erdőik is elégnek. Szerintem ezzel tönkre teszed a világot így és a játékosok is kiakadnak majd.

**Comment by poma123** [comment]
MONDOM KI LEHET KAPCSOLNI EZÉRT BE SE LESZ KAPCSOLVA XD ott van a tesztelés célja is... most komolyan 5x el kell magyaráznom amit leírok?

**Comment by andris155** [comment]
Az egy dolog, hogy ki lehet. De azt nem írtad oda, hogy ki is lesz. :D

**Comment by poma123** [comment]
A tesztelés célja nem az volt, hogy szétb***m a világokat :D Szerintem értelmesen le van írva mi a célja a tesztelésnek.

**Comment by poma123** [comment]
Vége a tesztelésnek, köszi a türelmet.

**Comment by andris155** [comment]
és mi lett az eredménye?

**Comment by poma123** [comment]
A TOC szempontjából irreleváns, de sikeres volt.
