### ISSUE TITLE
Nincs jog? 

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4058]
**Szerver**: Szurvi

Hali, Elitnek elvileg 10 telekhez van joga, nekem 8 van, és nem enged többet elfoglalni. Ez miért lehet? Tudtok kezdeni vele valamit? 
Üdv, Jaffis.

**Comment by andris155** [comment]
Van egy telked ami egybe van kötve, az több teleknek számít. Az adatbázis alapján így 23 telked van jelenleg. Ez azért jóval több 10-nél.
