### ISSUE TITLE
Slimefun - Üres slotok a Coal Generator-nál

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4059]
Random slotok kimaradnak azon a részen, ahol a Coal Generator-ban elégethető tárgyakat listázza a SF guide, ráadásul nem is sorban vannak a cuccok.

![kép](https://user-images.githubusercontent.com/16057404/95460557-64afd280-0975-11eb-8afd-a0ad53c56b0f.png)
![kép](https://user-images.githubusercontent.com/16057404/95460568-69748680-0975-11eb-9238-9aae0cb95281.png)
![kép](https://user-images.githubusercontent.com/16057404/95460576-6ed1d100-0975-11eb-8e99-a4240a38bf22.png)
![kép](https://user-images.githubusercontent.com/16057404/95460593-73968500-0975-11eb-9a9e-a005a3ae3813.png)
![kép](https://user-images.githubusercontent.com/16057404/95460606-772a0c00-0975-11eb-8cab-198af25ffb94.png)

**Comment by andris155** [comment]
Tudsz írni nekem egy listát, hogy mik vannak benne pontosan?
A Spigot material nevekkel lenne a legjobb.
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

**Comment by UDPSendToFailed** [comment]
Írhatok, de restart után megint felcserélődött az egész, nem úgy vannak sorban, ahogy tegnap.

![kép](https://user-images.githubusercontent.com/16057404/95570462-3db1d900-0a27-11eb-8f1e-c737cd80fcb1.png)

**Comment by UDPSendToFailed** [comment]
Coal Generator (II) ugyanez.

![kép](https://user-images.githubusercontent.com/16057404/95570814-be70d500-0a27-11eb-99ca-7384d2e627fe.png)

**Comment by UDPSendToFailed** [comment]
Coal Generator mai listája

**Page 1**

- JUNGLE_BOAT
- ?
- ACACIA_WOOD
- STRIPPED_SPRUCE_WOOD
- ACACIA_DOOR
- ?
- ACACIA_BUTTON
- WARPED_BUTTON
- OAK_LOG
- ?
- SPRUCE_BOAT
- BIRCH_FENCE
- ACACIA_SLAB
- JUNGLE_WOOD
- CRIMSON_HYPHAE
- JUNGLE_FENCE
- ?
- SPRUCE_BUTTON

**Page 2**

- DARK_OAK_BUTTON
- WARPED_SIGN
- WARPED_STEM
- DARK_OAK_LOG
- WARPED_SLAB
- STRIPPED_JUNGLE_LOG
- STRIPPED_SPRUCE_LOG
- DARK_OAK_BOAT
- CRIMSON_SLAB
- DARK_OAK_DOOR
- OAK_BUTTON
- STRIPPED_DARK_OAK_WOOD
- JUNGLE_BUTTON
- ACACIA_BOAT
- OAK_SIGN
- STRIPPED_WARPED_STEM
- BIRCH_PRESSURE_PLATE
- WARPED_HYPHAE

**Page 3**

- BIRCH_TRAPDOOR
- BIRCH_WOOD
- ACACIA_FENCE
- STRIPPED_CRIMSON_STEM
- ACACIA_SIGN
- STRIPPED_JUNGLE_WOOD
- STRIPPED_OAK_LOG
- BIRCH_SLAB
- OAK_PLANKS
- ACACIA_PRESSURE_PLATE
- SPRUCE_SIGN
- BIRCH_LOG
- STRIPPED_WARPED_HYPHAE
- BIRCH_PLANKS
- OAK_SLAB
- BIRCH_BOAT
- SPRUCE_WOOD
- CRIMSON_FENCE

**Page 4**

- WARPED_DOOR
- JUNGLE_SLAB
- SPRUCE_DOOR
- JUNGLE_TRAPDOOR
- ?
- BLAZE_ROD
- JUNGLE_PRESSURE_PLATE
- WARPED_FENCE
- STRIPPED_ACACIA_WOOD
- JUNGLE_LOG
- STRIPPED_ACACIA_LOG
- SPRUCE_SLAB
- STRIPPED_CRIMSON_HYPHAE
- WARPED_PLANKS
- JUNGLE_DOOR
- DRIED_KELP_BLOCK
- CRIMSON_PLANKS
- BIRCH_DOOR

**Page 5**

- STRIPPED_BIRCH_LOG
- OAK_FENCE
- OAK_TRAPDOOR
- STRIPPED_BIRCH_WOOD
- STRIPPED_OAK_WOOD
- ?
- DARK_OAK_PRESSURE_PLATE
- SPRUCE_LOG
- BIRCH_SIGN
- COAL
- CRIMSON_BUTTON
- CRIMSON_PRESSURE_PLATE
- DARK_OAK_PLANKS
- CRIMSON_DOOR
- STRIPPED_DARK_OAK_LOG
- JUNGLE_PLANKS
- DARK_OAK_WOOD
- WARPED_PRESSURE_PLATE

**Page 6**

- CHARCOAL
- DARK_OAK_TRAPDOOR
- CRIMSON_SIGN
- ACACIA_TRAPDOOR
- CRIMSON_TRAPDOOR
- COAL_BLOCK
- ?
- ACACIA_LOG
- DARK_OAK_SLAB
- DARK_OAK_FENCE
- JUNGLE_SIGN
- OAK_BOAT
- CRIMSON_STEM
- OAK_DOOR
- WARPED_TRAPDOOR
- SPRUCE_PLANKS
- OAK_PRESSURE_PLATE
- OAK_WOOD

**Page 7**

- SPRUCE_TRAPDOOR
- SPRUCE_FENCE
- ACACIA_PLANKS
- DARK_OAK_SIGN
- ?
- SPRUCE_PRESSURE_PLATE
- BIRCH_BUTTON


![kép](https://user-images.githubusercontent.com/16057404/95573074-312f7f80-0a2b-11eb-9777-19a697272da2.png)
![kép](https://user-images.githubusercontent.com/16057404/95573088-35f43380-0a2b-11eb-91de-c41cef206da1.png)
![kép](https://user-images.githubusercontent.com/16057404/95573105-3a205100-0a2b-11eb-969f-0d2199189a9f.png)
![kép](https://user-images.githubusercontent.com/16057404/95573118-3f7d9b80-0a2b-11eb-93de-b4d6099cb791.png)
![kép](https://user-images.githubusercontent.com/16057404/95573127-43112280-0a2b-11eb-8756-d2f3134e5179.png)
![kép](https://user-images.githubusercontent.com/16057404/95573139-47d5d680-0a2b-11eb-8c73-8c7a22c51c1b.png)
![kép](https://user-images.githubusercontent.com/16057404/95573151-4d332100-0a2b-11eb-88e5-6defc0d158be.png)

**Comment by andris155** [comment]
köszi

**Comment by andris155** [comment]
Elvileg javították a hibát, vagy holnap vagy holnapután bekerül a frissítés a javítással.
