### ISSUE TITLE
Slimefun - Villager reset rune működik más telkén / levédésén

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4061]
![kép](https://user-images.githubusercontent.com/16057404/95474546-831dca00-0985-11eb-9b13-416129400e81.png)

**Comment by KingDeadZ** [comment]
asszem amikor bejött és teszteltük lépnem kellett, megkérdeztem vkit aki ottvolt h mükszik-e más levédésén (asszem skt) aztmondta h igen, és bentmaradt xd gondolom direkt, ha meg nem akkor rip

**Comment by poma123** [comment]
> és bentmaradt xd gondolom direkt

... ha senki se jelenti, honnan kéne tudnunk róla?

**Comment by skrisz0101** [comment]
én már nem emlékszem mi volt mikor bekerült

**Comment by andris155** [comment]
Ez biztosan nem rég került be. De amúgy naponta elég sokat változtatnak a Slimefun-on. Nem tudjuk sajnos minden nap letesztelni benne az új dolgokat.

**Comment by MrZero1** [comment]
Akkor hatékonyan teszteltek addonokat..😃

**Comment by andris155** [comment]
Ez nem add-on. Ez elvileg már rég bent van, csak át lett nevezve.

**Comment by MrZero1** [comment]
Addon, nem addon, akkor is. Rég meg biztos nincs bent

**Comment by poma123** [comment]
A Slimefunba került be, nem addonba. Teljesen mindegy lett-e tesztelve, az itt lévők egyike sem tehet róla, hogy el lett cseszve. Jelenteni kell az Sf felé, és majd javítják (vagy javítom)

**Comment by andris155** [comment]
Valamikor lesz rá valószínűleg javítás. Addig a falusiakat próbáljátok meg olyan helyen tárolni, ahol nem fér hozzá senki.
