### ISSUE TITLE
Hibát találtunk az ércgenerátorban

### ISSUE THREAD

**Issue by szucs76** [TheOld-Crafters/Minecraft-servers#4062]
**Szerver**:Savsziget

a sziget ércgenerátoránál nem tudjuk az ércek  activálni/deactivalni illetve a bekapcsolva maradt ércek szintjeinél block listában lévö ércek nem generálodnak a vas és a szén kivételével!
sziget tulajdonos: Tulaj Dondani2  altulaj: szucs76

**Comment by andris155** [comment]
Javítva.
