### ISSUE TITLE
Old rang invsee jog

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4063]
Régen volt, miért lett kivéve? Kereskedésnél hasznos lenne, nem egyszer próbáltak átverni.

**Comment by andris155** [comment]
Mert a játékosoknak a privát adata, hogy éppen pontosan mi van nála. A staffok férnek ehhez csak hozzá és ezen én nem is szeretnék változtatni.

**Comment by skrisz0101** [comment]
Azért került ki mert flyman mindig zaklatta kittit és nézte mit csinál (invsee-vel) xd
@UDPSendToFailed
