### ISSUE TITLE
Survival - 10 percenkénti pénz

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4064]
Old ranggal elvileg naponta 150.000$-t lehet szerezni az online időért, 10 percenként 1500$. Ehhez 16.7 órát kéne fent lenni, de 10-12 óra után már írja, hogy elértem a fizetési limitet, így valami nem jó, szerintem nincs meg a 150.000$ naponta.

**Comment by andris155** [comment]
Minden jó, csak valahogy el lett felejtve a limitek frissítése a minemarket-en. Javítottam.

**Comment by andris155** [comment]
1016 OCD
