### ISSUE TITLE
Slimefun - Gold panok és az eszközkeret

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4065]
**Szerver**: Szurvi, sav nem tudom

Nem lehet eszközkeretbe rakni a gold paneket, a simát és a nether gold pant se.

**Comment by poma123** [comment]
Direkt ilyen szerintem, az entitásokkal való interakciójuk le van tiltva.

**Comment by skrisz0101** [comment]
:(

**Comment by andris155** [comment]
Általában amit poma ír a Slimefun-nal kapcsolatban az úgy is van. Ránézek majd azért, de szerintem akkor úgy van ahogy poma írta.

**Comment by andris155** [comment]
Elvileg már bele lehet tenni.
