### ISSUE TITLE
Chaten nem írja a szavazást

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4066]
Ha tiltva lett, szerintem jobb volt a régi megoldás, legalább emlékeztette rá a playereket, hogy kéne szavazni.

![kép](https://user-images.githubusercontent.com/16057404/95653121-6228b680-0af6-11eb-962e-14374e4b9cc0.png)

**Comment by skrisz0101** [comment]
esetleg az is lehetne hogy percenként max 1x írja ki

**Comment by andris155** [comment]
Döntsétek már el mit akartok... Nem lehet továbbra sem, hogy hányszor írja x időn belül. Egyszer azt írjátok, hogy legyen egyszer meg azt, hogy nem.

**Comment by andris155** [comment]
Szerintem nem kell ennyiszer spam-elni ezt. Belépésnél is írja, hogy ne felejts el szavazni.

**Comment by Ziredus** [comment]
Andris oldalán állok. Piszok bosszantó volt az ha valaki feljött mondjuk 1 hét után. és 200 csillió sorban kiírta h köszönjük, hogy szavaztál. A szerver emlékeztet rá, hogy szavazz, nem kell ez a flood.
