### ISSUE TITLE
Slimefun - Multi Tool hibák

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4067]
A Multi Tool-ra lehet enchantokat rakni Auto Enchanter-rel, és azokban a világokban, ahol tiltva van, lehet sima ollóként használni.

![kép](https://user-images.githubusercontent.com/16057404/95662486-a38d8600-0b37-11eb-96ad-e4c076257a9f.png)
![kép](https://user-images.githubusercontent.com/16057404/95662521-dc2d5f80-0b37-11eb-92b8-585aa6ea07f6.png)

**Comment by skrisz0101** [comment]
xd

**Comment by andris155** [comment]
Az hogy a fejlesztést lehet rárakni szerintem nem befolyásol semmit. Lehetne tiltani, de az is plusz ellenőrzés lenne szóval inkább nem módosítok ezen.

**Comment by andris155** [comment]
Egyszer talán lesz rá megoldás. De addig sajnos a farmon végtelen ollóként használható. De annyira azért ez nem nagy probléma szerintem. Egy olló csak pár vasba kerül.
