### ISSUE TITLE
Slimefun - Minden fegyvert, eszközt, és páncélt szét lehet szedni McMMO aranyblokkon

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4068]
![kép](https://user-images.githubusercontent.com/16057404/95663063-43e5a980-0b3c-11eb-8930-4dd2339345e0.png)
![kép](https://user-images.githubusercontent.com/16057404/95663069-4ba54e00-0b3c-11eb-9250-91e74803dd7a.png)

+1 McMMO-val kapcsolatos hiba, ennek már nem akartam külön jelentést nyitni. A SF Ingotokat lehet alap MC és SF tárgyak javítására is használni McMMO-s vasblokkon.

![kép](https://user-images.githubusercontent.com/16057404/95663527-2adef780-0b40-11eb-9504-e11fef5b3235.png)

![kép](https://user-images.githubusercontent.com/16057404/95663538-4518d580-0b40-11eb-9af8-82907d80440b.png)

**Comment by Ziredus** [comment]
és Reinforced alloyt kaptál vissza? vagy sima vasrudat?

**Comment by UDPSendToFailed** [comment]
@Ziredus sima vasrudat, de másféle páncélnál ez kihasználható lehet.

**Comment by lovi-dev** [comment]
@Ziredus SF-es itemet nem ad.

**Comment by andris155** [comment]
Erre sajnos nincs megoldás. Az mcMMO-nak kellene megoldania, de ők nem nagyon foglalkoznak a jelentéseimmel. De azért persze megírtam nekik.
