### ISSUE TITLE
Slimefun - Adagoló alapú blokkok hibái

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4069]
Ancient Pedestal: Lerakok egy tárolót, arra tölcsér / cargo, kiütöm a tárolót, lerakom a helyére az Ancient Pedestal-t, a saját funkciója mellett sima adagolóként is működik, redstone jelre kidobja a tárgyakat.

Android Fuel / Item Interface: Redstone jelre kidobja a tárgyakat.

**Comment by andris155** [comment]
Valószínűleg ennél a hibánál sem lesz javítás a szerveren, mert szerintem ehhez is a hopper event-et kell majd ellenőrizni a plugin-nak, ami optimalizáció miatt le van tiltva a szerveren. A hibát megírtam azért a Slimefun-nak. Illetve persze OCD-t is adok ezért is csak majd egyben.
