### ISSUE TITLE
Slimefun - Kemence alapú gépek használhatók sima kemenceként

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4070]
![kép](https://user-images.githubusercontent.com/16057404/95663588-c83a2b80-0b40-11eb-83a7-0287b4c4f581.png)
![kép](https://user-images.githubusercontent.com/16057404/95663596-d38d5700-0b40-11eb-9428-df187878ada2.png)
![kép](https://user-images.githubusercontent.com/16057404/95663600-dee08280-0b40-11eb-94cf-1d611910df1d.png)

**Comment by andris155** [comment]
Valószínűleg ennél a hibánál sem javítás a szerveren, mert szerintem ehhez is a hopper event-et kell majd ellenőrizni a plugin-nak. A hibát megírtam azért a Slimefun-nak. Illetve persze OCD-t is adok ezért is csak majd egyben.
