### ISSUE TITLE
Slimefun - Necrotic Skull-ból lehet Wither-t idézni

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4071]
![kép](https://user-images.githubusercontent.com/16057404/95663715-ba38da80-0b41-11eb-9cf1-96fa562ada1d.png)
![kép](https://user-images.githubusercontent.com/16057404/95663717-bf962500-0b41-11eb-85c7-ab56f071788b.png)
![kép](https://user-images.githubusercontent.com/16057404/95663721-ca50ba00-0b41-11eb-9935-ec2158b91154.png)

**Comment by andris155** [comment]
Majd egy staffal szedesd ki onnan a ghost blokkokat ahol megidézted.

**Comment by andris155** [comment]
A javítást megcsinálták rá, majd valamikor jövőhét elején kerül be a szerverre.
