### ISSUE TITLE
Slimefun - Dustok használhatók potion főzéshez

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4072]
Dustokon kívül még ezek is mennek a tölcséres módszerrel: Essence of Afterlife, Vitamins (Level III), Magnesium Salt, Salt, Magic Sugar, Wheat Flour, Sifted Ore, Crushed Ore, Pulverized Ore, Pure Ore Cluster, Magical Zombie Pills.

![kép](https://user-images.githubusercontent.com/16057404/95663844-c96c5800-0b42-11eb-9d01-1ceacc84e8fe.png)
![kép](https://user-images.githubusercontent.com/16057404/95663852-db4dfb00-0b42-11eb-9222-b7b74efbd840.png)
![kép](https://user-images.githubusercontent.com/16057404/95663848-d12bfc80-0b42-11eb-8496-8097e91ea8cf.png)

**Comment by skrisz0101** [comment]
Ezt már egyszer javította poma, nem?

**Comment by UDPSendToFailed** [comment]
@skrisz0101 simán invből nem lehet belerakni, de tölcsérrel igen.

**Comment by andris155** [comment]
A fejlesztőnek megírtam a hibát, de nálunk erre szerintem nem lesz megoldás, mivel a hopper event-tel tudják nézni, hogy mi megy át rajta. Ez az event optimalizáció miatt nálunk le van tiltva a pluginok számára.
