### ISSUE TITLE
Kapocs

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4073]
**Szerver**: Survival

![kép](https://user-images.githubusercontent.com/29709854/95666361-0ba09400-0b59-11eb-84a2-3bfcfef37598.png)

Tudom, hogy játékosnak le van tiltva (csak a pokolban tudják lerakni), de most nézegettem, a spawn világban, vadonban ha lerakom, rakok bele izzókövet, akkor felrobban.
Esetleg ezt le lehet e tiltani? Mármint hogy ne robbanjon fel. Dekorációs célra akartam volna használni a spawn-on (halloween miatt), jól mutat, ahogy van benne izzókő és "dolgozik"a kapocs. :D

**Comment by andris155** [comment]
Nem lehet tiltani. WorldGaurd régión ha le van védve és nem férnek hozzá, akkor lehet nem robban. Teszteld le.

**Comment by MrZero1** [comment]
Milyen flag-gel nézzem? Use, interact nem ért semmit, csak ezt:
![kép](https://user-images.githubusercontent.com/29709854/95678010-dd0ed180-0bc9-11eb-9d57-b4f69e083f6d.png)

**Comment by MrZero1** [comment]
Oké, sikerült. Van rá flag. Köszi!
