### ISSUE TITLE
Survival - Pénzrendszer/bolt

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4074]
**Szerver**: Survival

Jó lenne közösen ötletelni, majd eldönteni, hogy hogyan kellene javítani/orvosolni/megújítani a jelenlegi Survival-os pénzrendszert.

E hibajegy alá lehet írni ötleteket, bármiféle hozzászólást szívesen veszek.

**Comment by MrZero1** [comment]
Ötletként jött: Azoknak az eladási árát növelni (tehát több pénzért lehetne eladni), amiket nehezebben, kevésbé automatikus - farmos megoldással lehet szerezni. Lehet ez akár SF-es cucc (de mik az ilyen dolgok?), lehet sima minecraft-os.

**Comment by Ziredus** [comment]
Az a baj Zero, hogy mi az ami nem farmolható automatikusan? Vannak androidjaink, miner, farmer, fisher, butcher. Ezálltal farmolható a Fa (és alma bot meg csemete) ha teszünk hozzá observereket, adagolókat akkor farmolhatő a lombkorona is! Kövek és ércek szintúgy, csak elegendő miner androidot kell elengedni, halak egyértelmü, butcher pedig mivel a mindenre is van szinte spawner, vagy valamilyen farm megoldás, így az is automatizálható. Egész egyszerűen nemigazán tudok olyat mondani amit ne lehetne automatizáltan nyomatni. Talán az alap craftos cuccok azok amik egyelőre nem automatizáltak, de hogy abból mit érné meg és mit nem átárazni... arról lövésem sincs.

**Comment by skrisz0101** [comment]
butcher android nélkül is van 1000+1 automata mód mobölésre.

**Comment by MrZero1** [comment]
> butcher android nélkül is van 1000+1 automata mód mobölésre.
> 
> Amúgy erre a problémára a jobs lenne a legjobb megoldás, csak nem olyan mértékben mint régen
> 
> (Amiket mesélt kernel, nem volt jól beállítva :v)

Szívesen várom a független érveket, ellenérveket. A "jobs kell" nem éppen segítség.

**Comment by KingDeadZ** [comment]
a jobs az azért lenne jó, mert az nem afkért ad pénzt hanem azért ha valamit tevékenykedsz pl bányászol v növényt farmolsz

**Comment by Bazsaaaa** [comment]
és ha jobs helyett az mcmmo ad pénzt? :)

**Comment by KingDeadZ** [comment]
Szerintem erre nincs lehetőség, amúgy asszem valaki megszólta, hogy akkor 2x kapsz pénzt ugyan azért az itemért. Szerintem ettől függetlenül mondjuk jó lenne, mert attól függetlenül hogy 2x kapnál pénzt itemért (amire asszem van kb 1-2sec kihagyás a jobsban) nem fognak manuálisan farmolni, mert az automata menő. Ma tudtam meg, hogy 60db dust fabricatorral tolja valaki, hogy bírjon vasat eladni mert az az egyetlen item kb, amit megéri eladni jelenleg a boltban xd

**Comment by Bazsaaaa** [comment]
lehetne olyan dolgoknak felvinni az árát amiből lehet farmot építeni de nem auto-t pl az édes bogyó. Azt csak kézzel lehet leszedni ha jól tudom

**Comment by MrZero1** [comment]
A ma este a srácok (skrisz, multi, kingdead) segítségével egy helyre rendeztük a farmolható dolgokat (növények + mobdrop) jó nagy részét, talán kicsit jobb árazással. Nyilván ez nem fogja megoldani a gondot, de hátha kedved kapnak a farmoláshoz.
A staffok ezentúl gyakrabban fognak körbemenni, ha a rendszeres afkolókat pedig büntetik.

Holnap folytatjuk a bolt átnézését.

**Comment by MrZero1** [comment]
Ha jobs lenne, hogyan lenne? Hogy lenne értelme? Hogy gondoltátok?

Boltba is el lehetne adni azt, amit kitermel pénzért?

Sok bennem a kérdőjel.

**Comment by skrisz0101** [comment]
nemtom. sztem ja

**Comment by KingDeadZ** [comment]
El lehetne, szimplán annyi változna, hogy többet kapna azért, amit manuálisan farmolna ki. 
pl: Kiütök manuálisan 768 (12stack) tököt, azért kaphatnék egy jó 500-600$t kb mivel régen volt cooldown a pénzadások között, most nemtudom hogy van-e.
A jobsal egyébként olyan helyeken is lehetne kompenzálni, amit annyira nem éri meg manuálisan farmolni, mivel kicsi az ára (mert természetesen egy rakatnyit szerzel belőle pár perc alatt) erre egy jó példa a blazerod.

**Comment by MrZero1** [comment]
Egyedül kevés vagyok ezt eldönteni, miért mennyit, milyen munkák legyenek. 

Lehet jobs, de ahhoz jó lenne ha független (tehát nem saját érdekeit nézi) emberek segítenének ebben.

**Comment by KingDeadZ** [comment]
Ha megbírnánk valahol nézni az alap árakat, hogy milyen munkák vannak, hogy alapból mikért kapunk pénzt az sokat segítene szerintem, ha lesz rá lehetőség egy páran biztos hogy segítenénk benne.

**Comment by MrZero1** [comment]
Tesztre be lehetne rakni. (?) @andris155

**Comment by andris155** [comment]
Teszt szerver?

**Comment by snowman142** [comment]
> Szerintem erre nincs lehetőség, amúgy asszem valaki megszólta, hogy akkor 2x kapsz pénzt ugyan azért az itemért. Szerintem ettől függetlenül mondjuk jó lenne, mert attól függetlenül hogy 2x kapnál pénzt itemért (amire asszem van kb 1-2sec kihagyás a jobsban) nem fognak manuálisan farmolni, mert az automata menő. Ma tudtam meg, hogy 60db dust fabricatorral tolja valaki, hogy bírjon vasat eladni mert az az egyetlen item kb, amit megéri eladni jelenleg a boltban xd

jelen,remélem lassan az is ki lesz szedve h semmiféle képpen ne lehessen pénzhez jutni

**Comment by KingDeadZ** [comment]
Nem az a lényege a játéknak szerintem, hogy csak az afkfarmokra építs, és ne csinálj semmit, csak craftolgass tovább, hogy még nagyobb afkfarmod legyen, míg el nem jutunk arra a szintre, hogy nonstop bírsz afkfarmból eladni, v másoknak profitshopot csinálni (amit szerintem be kéne tiltani mondjuk) de emellett a szerver tpse csak a fellépéskor csökkenjen 5el.

**Comment by MrZero1** [comment]
Szerintem most a farmolható dolgokkal is lehet pénzt keresni, mióta egy helyre kerültek. 
Nyilván ez is valamilyen szinten át fog menni afkolásba, de legalább dolgoznak vele valamennyit. 

Ha a jobs bekerülne, akkor kapna azért pénzt mert kitermeli amit kell, meg kapna azért mert eladja.

**Comment by KingDeadZ** [comment]
hmm például pénzért venni küldiket? nem rossz ötlet amúgy

**Comment by skrisz0101** [comment]
Kajak nem rossz ötlet a pénzért küldi
