### ISSUE TITLE
Eltünt android

### ISSUE THREAD

**Issue by szucs76** [TheOld-Crafters/Minecraft-servers#4075]
**Szerver**:Sav sziget

a mai nap egy androidom el tunt es a nem az androidot kaptam meg hanem egy fejet
![Base Profile Screenshot 2020 10 11 - 12 52 05 93](https://user-images.githubusercontent.com/72626519/95676769-fc553100-0bc0-11eb-9dcf-36f788200bf0.png)

**Comment by andris155** [comment]
Kérj meg egy admint, hogy adja vissza neked.
