### ISSUE TITLE
Slimefun - Auto Anvil (I, II)-ből lehet vasgólemet idézni

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4076]
(Ghost blokk ki lett szedve)

**Comment by andris155** [comment]
Sok dologból lehet összességében így már. Egy ideje megírtam nekik. Szerintem aki normálisan játszik nem fog belőle semmit idézni. Egyszer lehet lesz rá javítás, de szerintem a Slimefun-nak nem ez az elsődleges, hogy ezt megoldja.
