### ISSUE TITLE
Slimefun - Miner Android kiszedi a levédett ládákat, és a ChestShop ládáit is

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4077]
![kép](https://user-images.githubusercontent.com/16057404/95680965-8d3a0580-0bdd-11eb-873d-0c7fdc3be5c3.png)
![kép](https://user-images.githubusercontent.com/16057404/95680978-9f1ba880-0bdd-11eb-92fa-c40cf1c6b027.png)
![kép](https://user-images.githubusercontent.com/16057404/95680981-a5118980-0bdd-11eb-88f6-3f994c54da98.png)
![kép](https://user-images.githubusercontent.com/16057404/95681001-ca9e9300-0bdd-11eb-9b72-020fc7256163.png)
![kép](https://user-images.githubusercontent.com/16057404/95681011-d8ecaf00-0bdd-11eb-9aeb-9f06fa1f45ff.png)

**Comment by andris155** [comment]
Erre sajnos nincs megoldás egyelőre. De szerintem a jövőben sem lesz. A LockettePro, és ChestShop fejlesztője se nagyon akar ezzel foglalkozni és ezt nekik kellene megoldaniuk. Nem a Slimefun-nak.
