### ISSUE TITLE
Kick

### ISSUE THREAD

**Issue by snowman142** [TheOld-Crafters/Minecraft-servers#4078]
Survival szerver.
A telek rendszeren vannak olyan playerek akiket nem lehet kickelni (/P kick <név>) nem működik.

**Comment by mangoshell** [comment]
Ezért nem lehet kitiltani: #3617

**Comment by poma123** [comment]
A plot kick és a plot deny nem ugyanaz.

**Comment by mangoshell** [comment]
Azt hittem ez a tiltásos jelentés, bocsi

**Comment by snowman142** [comment]
esetleg valami visszajelzés h mikor lesz javítva?

**Comment by poma123** [comment]
türelem...

**Comment by andris155** [comment]
Akkor lehet valakit kick-elni amikor a telkeden van. Ha nincs a telkeden, akkor nem fog működni. Nekem ezt a hibát nem sikerült reprodukálni. Esetleg ha leírnád mit ír ki, meg hogy egyáltalán a telkeden volt-e, akit kick-elni akartál az nagy segítség lenne.

**Comment by snowman142** [comment]
A telkemenm volt,Kittii is próbálta kickelni a személyt miközben előtte volt,neki is ugyan azt írta mint nekem.Valami olyasmi volt h a player nem található,ha jól emlékszem.Ott voltunk mind a ketten a telkemen,a parancsot is jól írtam be.Hozzá teszem h csak egyetlen egy játékosnál nem működött eddig.

**Comment by andris155** [comment]
Sajnos nem tudom, hogy ez hogyan történhetett. Nem találtam ezzel kapcsolatban error üzenetet sem. Mivel nem tudtam reprodukálni a hibát nem tudok így ezzel mit kezdeni. Ha megint lenne ilyen, akkor mindenképpen nyiss egy új jelentést.
