### ISSUE TITLE
Telek világ/Tiltás

### ISSUE THREAD

**Issue by snowman142** [TheOld-Crafters/Minecraft-servers#4079]
Survival szerver.
Jó lenne visszahozni a tiltás a telek világban is.Ha már a vadonban továbbra is lehet tiltani,semmi értelme nincs hogy a telken meg nemlehet.

**Comment by mangoshell** [comment]
Azért lett tiltva a plotos deny, mert ha valaki ki volt tiltva a telekről, és pwarpolt, akkor borderen kívülre dobta és R,I.P minden cucc

**Comment by poma123** [comment]
Amikor belépett valaki a letiltott telekre, akkor dobta el a világvégére.
