### ISSUE TITLE
Lantern és Soul Lantern nocheat hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4080]
https://youtu.be/K5GqoansHd8

**Comment by andris155** [comment]
A fejlesztő azt írta, hogy ezt nem lehet javítani.

**Comment by andris155** [comment]
Elvileg mégis javította aztán.

**Comment by andris155** [comment]
Szerintem a felejtsd el, hogy lehet javítani helyett azt akarta írni, hogy elfelejtette javítani. :D
