### ISSUE TITLE
Beváltó warp - androidok

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4082]
**Szerver**: Szurvi, sav

Egy ideje már bekerült a PomaExpansion, ezért lehet fejlettebb miner, woodcutter, stb androidokat is csinálni, de a sima alap miner, woodcutter androidokkal nem lehet mit csinálni (nem az kell craftba)
Jó lenne ha be lehetne cserélni ezeket a sima Programmable androidokat (miner, woodcutter, stb)
sima programmable androidokká, amit tovább lehet craftolni

**Comment by Ziredus** [comment]
Támogatom. A korábban szükségből készült androidoknak abszolut nem vesszük hasznát, csak porosodnak egy ideje.

**Comment by skrisz0101** [comment]
mizu?

**Comment by MrZero1** [comment]
Semmi, veled?

**Comment by skrisz0101** [comment]
Megvagyok, bár üldöz a korona

**Comment by MrZero1** [comment]
Amit be lehetne váltani és amire, azt tudnál adni?

**Comment by skrisz0101** [comment]
Rakok majd ec-be holnap

**Comment by MrZero1** [comment]
hát, akkor ez csak szombat este lesz meg, akkor leszek, de oksi. köszi

**Comment by MrZero1** [comment]
Hol találom majd?

**Comment by MrZero1** [comment]
Csak sikerült. :D Köszi sk.

**Comment by skrisz0101** [comment]
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4110
