### ISSUE TITLE
Használhatatlan solar helmet

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4083]
**Szerver**: Szurvi, gondolom sav is
Nem tölti fel sem a jetpackemet, sem a multi toolomat. nem tudom akkor mire lenne használható
![2020-10-14_16 13 40](https://user-images.githubusercontent.com/29951969/96001538-6cb9b780-0e38-11eb-864c-ed80ca294a70.png)

**Comment by poma123** [comment]
Nappal próbáltad? Megpróbálod szabad ég alatt is?

**Comment by andris155** [comment]
A ptime-t, telek időt, és terület időt sem támogatja. Az adott világban kell nappalnak lennie hozzá.

**Comment by skrisz0101** [comment]
Lehet az volt a baj, majd meglesem holnap újra

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a hibát.
