### ISSUE TITLE
Plot claim sikertelenség

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4084]
**Szerver**: Survival

Nem lefoglalt telken állva a /p claim parancsra ezt a szöveget írja ki, viszont a telket nem foglalja le.
![image](https://user-images.githubusercontent.com/69635280/96026459-ccbf5680-0e56-11eb-9a74-d6100f514f65.png)

**Comment by andris155** [comment]
Milyen néven játszol a szerveren?

**Comment by skrisz0101** [comment]
DrBlade

**Comment by mangoshell** [comment]
DrBlade, de más játékosnak is ezt írta ki.

**Comment by andris155** [comment]
Megtudod adni a plot id-t?

**Comment by mangoshell** [comment]
mindegyik ploton ezt írja

**Comment by mangoshell** [comment]
Úgy néz  ki már megjavult. Mostmár rendesen lefoglalja.

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a hibát. Nekem hibátlanul működik a claim.
