### ISSUE TITLE
Slimefun - Lucky Block név bug

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4085]
Nyitottam egy Shopkeeper falusit, minden szerver restart után újra be kell állítani a Lucky Block csere opciót, mert dőlt betűssé válik a neve. 

Falusi:
![kép](https://user-images.githubusercontent.com/16057404/96097883-c8844f00-0ed1-11eb-8053-b96f27dbe603.png)

Ládában lévő Lucky:
![kép](https://user-images.githubusercontent.com/16057404/96097983-e651b400-0ed1-11eb-8310-64ec84fa09c2.png)

Az aukcióra felrakott Lucky Blockokkal is ez történik.

**Comment by andris155** [comment]
Szerintem erre nem nagyon lesz mostanában megoldás. Nem igazán foglalkoznak a Lucky Block bővítménnyel mostanában. Ez sajnos ilyen.

**Comment by andris155** [comment]
Az újonnan létrehozott Lucky Block-oknál már nem szabadna ilyen hibának lennie. Próbáld meg azt használni a kereskedőhöz.
