### ISSUE TITLE
Survival - Hide and seek 2

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4088]
Amikor szilárd block vagy, akkor ha a seeker meglő íjjal, akkor nem ugraszt ki az álcádból, és így csak kardal bir kiugrasztani, amikor az íjjal is kéne szerintem ennek működnie.

**Comment by MrZero1** [comment]
Tudomásom szerint az íj szilárd blokkot nem sebez, ez eddig is így volt. A bájitalokkal és a karddal lehet a szilárd blokkot "elmozdítani".
