### ISSUE TITLE
Farm

### ISSUE THREAD

**Issue by IcyAlex** [TheOld-Crafters/Minecraft-servers#4090]
Szerver: Survi

A warp farmon nem működik a fly, god, feed, heal, ec, és még biztos van egy pár apróság.

**Comment by kBalix** [comment]
a slimefunos fegyvereket se lehet használni

**Comment by MrZero1** [comment]
Mivel az a farm az eventvilágban van.

**Comment by andris155** [comment]
Maximum akkor működne minden, ha át lenne helyezve a sima világba.

**Comment by MrZero1** [comment]
Viszont azért lett az eventvilágban a farm, mert a spawnon lévő nem volt jó. Én nem helyezgetem sehova, jó ahogy van.

**Comment by andris155** [comment]
A spawn világban meg azért nem volt jó, mert le van tiltva a világban a mobspawn. :D
