### ISSUE TITLE
Survival - Hide and Seek levédés

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4091]
Pár mapon nincs jogunk potival sebezni másokat seekerként, majd át kéne nézni és engedélyezni.

**Comment by andris155** [comment]
Letudod írni pontosan melyiken nem lehet?

**Comment by KingDeadZ** [comment]
Talán teveváros a neve az egyik olyan mapnak a neve, ahol nem lehet, de máshol is észre vettem már, de sajnos azoknak/annak a nevére nem emlékszem. A hétvégén megpróbálom majd rávenni az embereket arra h menjünk hide and seekezni, és így kiderüljön hogy melyik mapokon nem használ a poti, de lehet hogy majd egy admin segítségét kérem, hogy könnyebben megtudjuk.

**Comment by MrZero1** [comment]
Jó lenne tudni, melyik arénákban nincsen jog rá. Köszi előre is, ha megírod majd. 😄

**Comment by andris155** [comment]
Engedélyezzem minden Hide And Seek aréna védésén az eldobható italokat?

**Comment by andris155** [comment]
Levettem a potion-spalsh tiltást a global régióról mivel nincsenek levédve az arénák ahogy néztem külön. Viszont a potion-spash ha tiltott máshol és lehet valahogy oda vinni eldobható italokat ott most így külön kell tiltani a survivalgames világban. Vagy vissza kell rakni a __global__ régióra a potion-splash tiltást és levédeni az összes hide and seek arénát majd engedélyezni rajta a potion-splash flag-et ha ez így nem jó.

**Comment by poma123** [comment]
Az összes eventen letiltva kellene lennie, ezért lett a globál levédésen tiltva.

**Comment by MrZero1** [comment]
Le vannak védve az arénák amúgy.
