### ISSUE TITLE
Sikertelen telek lefoglalás. (Survival)

### ISSUE THREAD

**Issue by ToncsiChannel** [TheOld-Crafters/Minecraft-servers#4093]
PinkWizard-nak egy problémája akadt amit én jelentek be mivel neki nincs githubja. Annyi az egész story, hogy ő törölte a telkét majd újra leakarta foglalni és azt írta ki neki (Meg utánna amikor én probálkoztam nekem is), hogy "a telek nincs lefoglalva". Csatolok egy képet mellé. Telek adata: 42;36
![Teleknincslefoglalva](https://user-images.githubusercontent.com/69111516/96332975-63626200-1067-11eb-8432-c3e5f399954e.PNG)

**Comment by andris155** [comment]
Nekem ezt a hibát nem sikerült pedig reprodukálni a szerveren.

**Comment by andris155** [comment]
A megadott telek az adatbázis alapján egyébként jelenleg PinkWizard telke.
