### ISSUE TITLE
Survival - Hirdetés spam

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4094]
Elég zavaró, hogy órákon át ez megy, szerintem a hirdetések közötti 3 perc szünetet lehetne növelni 8-10-re legalább, esetleg egy új szabályt hozni rá, hogy tilos egymás után spamelni.

![kép](https://user-images.githubusercontent.com/16057404/96338567-66714880-108f-11eb-882b-fe571e147f61.png)

**Comment by UDPSendToFailed** [comment]
Ha van rá opció, a szín / formázási kódok használatát is lehetne limitálni.

![kép](https://user-images.githubusercontent.com/16057404/96338765-8ce3b380-1090-11eb-9b2e-cd413d49423b.png)

**Comment by andris155** [comment]
Az időt lehet növelni az oké. Viszont nincs ilyen, hogy limitálni a színkódot meg formázást. Esetleg le lehet tiltani a formázási lehetőségeket.

**Comment by MrZero1** [comment]
A színeken kívül én minden mást letiltanék, az időt  lehetne növelni akkor.

**Comment by poma123** [comment]
> Az időt lehet növelni az oké. Viszont nincs ilyen, hogy limitálni a színkódot meg a formázást. Esetleg le lehet tiltani a formázási lehetőségeket.

Dehogynem, lehet limitálni a színkódot és a formázást, nézz bele a configba, le van tiltva a &c &4 &0 és a &k.
Egymás hirdetései közötti időt nem lehet megadni, csak saját hirdetések utáni cooldown van.

**Comment by andris155** [comment]
A letiltás nem limitálás szerintem.

**Comment by poma123** [comment]
szó szerint limitálni nem... de párat ami ronda le lehet tiltani.

**Comment by andris155** [comment]
kész
