### ISSUE TITLE
Spleefevent

### ISSUE THREAD

**Issue by derpyAK** [TheOld-Crafters/Minecraft-servers#4095]
**Szerver**:Savsziget

 Spleef eventen nem működik a fill-es commandblock ami a havat teszi újra, gondolom 1.16.3ra váltás miatt. Kellene egy kis frissítés.

**Comment by andris155** [comment]
Mi változott a parancsban?

**Comment by MrZero1** [comment]
A parancsban semmi, a koordináták voltak rosszak. Javítottam, most már szépen feltölti a 2 sor hóréteget, lehet tartani.
