### ISSUE TITLE
Ignore - Staff

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4096]
Kérdés, kérésre: Meg lehetne-e oldani azt, hogy játékosnak ne legyen joga Staffot ignorálni?

**Comment by andris155** [comment]
Sajnos az EssentialsX-ben nincs ilyen funkció.

**Comment by poma123** [comment]
Őszi szünetben ha lesz rá lehetőség megcsinálom.

**Comment by KingDeadZ** [comment]
https://www.minecraft.net/en-us/article/minecraft-1-16-4-pre-release-1
ha valaki ezt fogja használni, akkor nem lényegtelen ez?

**Comment by poma123** [comment]
Ahh tényleg. 1.16.4-től ugyebár kliensoldalról lehet majd akárkit ignorálni. Innentől kezdve nem szeretnék feleslegesen foglalkozni ezzel.

**Comment by andris155** [comment]
Teljesen igazad van és a kliens nem fogja tudni, hogy ki staff vagy ki nem.
