### ISSUE TITLE
Spawn - Nubbiztosság

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4098]
**Szerver**: Szurvi

Spawnon a négy kapu fele lehetne vadon2 nyomólap vagy valami, amivel el tudnak menni a vadonba (esetleg randomTP-vel)

**Comment by MrZero1** [comment]
A spawnon vannak a leírások, warpok. Inkább járják körbe a várost, mintsem egyből elteleportálja őket a vadonba. De majd rakok teleportálós cuccot a kapuk köré
