### ISSUE TITLE
Cargo optimalizáció - Remény

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4099]
**Szerver**: Szurvi, sav

bekerült pár új cucc a Fluffy addonba (egy rohadthasznos is cargo lagg ellen), szóval gondoltam újra lehetne gondolni mi legyen. - Végére hagyom a lényeget, de a többi is számít

Warp pad és pad configurator: Tök menő kis szerkezet. Le kell rakni két warp padot, az egyikből tudsz tpzni a másikba. 

Electric dust recycler: 8 dustból csinál 1 shifted oret. Haszontalan dustokat a szemét helyett lehetne ide is rakni, hasznos is lehet.

 --------------LÉNYEG--------------
        Electric dust fabricator
Zúzottkőből csinál dustot. Alapból a dust gyárhoz kellő gépek kellenek a craftjához (E-gold pan, E-ore grinder, E-Dust washer,) de ez mind csak 1 blokkban! +nem gyárt szemetet.  6 maxos gép kell a craftjához + pár egyéb 

Miért lenne jó:
1.:  kb hatodolódna (minimum) a dust gyárból származó cargo. Amíg egy dust gyár jobb esetben 6 gépből áll, most 1ből áll(na)
2.: Nem kell cargo a szemételvezetésre (Agyag, kovakő, vasrög) Ez is sok cargot fel le, ez se lenne
3.: Kicsit gyorsabb is mint a 6 gép egyben (mondjuk ez nem gyárt szemetet)
4.:  SOKKAL KEVESEBB CARGOOOOOOOOOOOOO 
5.: Idő spórolás gyárépítés,- és leépítéskor

Egyetlen hátránya: Kicsit több áramba kerül, de nem vészes egyáltalán. 
 --------------LÉNYEG--------------      

A mostani buggokat lehetne jelenteni a fejlesztőnek, mert akkor ki is lenne javítva :/ 
Ezelőtti jelentés:
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4047

**Comment by IcyAlex** [comment]
Én pl örülök a vasrögnek. :(

**Comment by skrisz0101** [comment]
Ezzel jön annyi +iron dust hogy ne kelljen a vasrög :D

**Comment by andris155** [comment]
Majd ismét tesztelgetem, de most más nagyobb projektet akarok előbb megvalósítani.

**Comment by UDPSendToFailed** [comment]
Már az is sokat segítene, ha úgy kerülne be az addon, hogy a Dust Fabricator-on kívül minden más tiltva van benne. Így nem lenne mit bugoltatni, abban az egy gépben nincs hiba.

**Comment by skrisz0101** [comment]
a többiben sincs feltétlen, csak ebben tuti nincs xd

**Comment by KingDeadZ** [comment]
jobs incoming?

**Comment by andris155** [comment]
Nem fog úgy bekerülni. Csak az lesz tiltva, amiben tényleg találok hibát és úgy fog.

**Comment by andris155** [comment]
Jobs nem lesz. Értelmetlen szerintem. Ugyanaz mint a bolt, csak nem kell eladnod, hanem egyből fizet x, y dologért. De az adott tárgyat még el is tudod adni... Gyakorlatilag duplán kapsz így pénzt mindenért.

**Comment by skrisz0101** [comment]
azt nem lehet automatán farmolni.

**Comment by andris155** [comment]
Miért ne lehetne?

**Comment by andris155** [comment]
Lehet írni mindenféle automatikus script-et ehhez is szerintem. Aki automatán akar farmolni nem hiszem, hogy egy Jobs fogna ki rajta. :D

**Comment by skrisz0101** [comment]
akk szedjük ki az érceket a világból, mert létezik xray és ki tudják bányászni. ugyanaz

**Comment by andris155** [comment]
Nem Jobs kellene igazából, hanem az, hogy async-ben fusson a cargo, de ezt még egy fejlesztő sem oldotta meg sajnos. Egyszer talán megoldják. Addig is minimálisan tudunk fejleszteni a szervergépen mondjuk erősebb processzorral kicsit (az egy magos teljesítmény számít csak sajnos). Ez utóbbi, ha minden jól megy hamarosan megvalósulhat.

**Comment by skrisz0101** [comment]
cargotol függetlenül is jó a jobs

**Comment by andris155** [comment]
De nem oldunk meg vele semmit. Az sf gyárak mennek ugyanúgy tovább attól, hogy van Jobs. Csak még több pénzt kapnak mindenért.

**Comment by KingDeadZ** [comment]
Egyébként titok, hogy miről volt szó nagyobb projektek alatt? :D Szerintem mostmár több embernek is felkeltette az érdeklődését.

**Comment by skrisz0101** [comment]
amúgy amiben van hiba és tiltva lesz, azokat majd jelented @andris155 ?

**Comment by andris155** [comment]
Ha olyan hiba, ami nem az miatt van, hogy egy másik plugin nem támogatja azokat mindenképpen.

**Comment by andris155** [comment]
Konkrétan le lett írva. Ha minden jól megy lesz egy kicsivel erősebb szervergép a cargo-ra. Bár ha a RAM gyorsaságot jól kitudja használni akkor egy jóval erősebb szervergép. De egyelőre fogalmam sincs, hogy a gyorsabb RAM miben előnyösebb a Minecraft szervereknél.

**Comment by andris155** [comment]
Tényleg jó ez a bővítmény. Szóval hamarosan bekerül persze tiltva lesznek a problémás dolgok.

**Comment by KingDeadZ** [comment]
A fluffy barrelst majd tiltani kéne, mert masszív laggot lehet vele okozni. Teszten talán 2napja néztük pomával kernellel és skval. @andris155 @poma123

**Comment by andris155** [comment]
Miért lehet vele laggot? Egyszerűen elmenti egy fájlba milyen tárgy és utána csak a számot írja át. Nem 64-sével tárolja.

**Comment by andris155** [comment]
Szeretnék látni egy timings reportot arról a lagról.

**Comment by andris155** [comment]
A bővítmény bekerült. Az ezzel kapcsolatos hibákkal nyissatok új jelentést. Ha a teszten lagot okoz valami azt timings report-al együtt tudom elemezni és javítani illetve jelenteni a fejlesztőnek. Anélkül nem fogjuk tudni pontosan mi okozza a laggot.
Egyéb változtatások bővítmény miatt:
A respawn anchor már nem robban és lerakható. Találtam megoldást az ágy robbanás tiltására is így már az is lerakható mindenhol. Az ender kristály pedig már nem robban így nem is rombol.

**Comment by UDPSendToFailed** [comment]
> 
> 
> Miért lehet vele laggot? Egyszerűen elmenti egy fájlba milyen tárgy és utána csak a számot írja át. Nem 64-sével tárolja.

Ha kiütjük a Barrel-t, az összes tárgyat kidobja a földre, ami benne van. Ez több 10000 itemnél eléggé laggoltat.

**Comment by poma123** [comment]
> Miért lehet vele laggot? Egyszerűen elmenti egy fájlba milyen tárgy és utána csak a számot írja át. Nem 64-sével tárolja.

Belerakni 393847482847 itemet majd kiütni, kidobja az összes itemet. Kene ra lennie egy checknek hogy csak akkor engedje kiutni ha 64nel kevesebb van benne

**Comment by UDPSendToFailed** [comment]
241 gép helyett 30, picit jobb

![kép](https://user-images.githubusercontent.com/16057404/96704891-db48c900-1394-11eb-88a8-114887b6aa30.png)
