### ISSUE TITLE
Fluffy barrels

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4100]
**Szerver**: Szurv, sav

Jó lenne ha nem lehetne ezeket kiütni, ha pl 64 itemnél több van benne.

**Comment by andris155** [comment]
Valahol talán Discord-on talán a Slimefun szerverén meglehet írni az ötleteket a fejlesztőnek. A GitHub-on sajnos csak hibajelentéseket fogad el. Az, hogy FPS lag lesz tőle az pedig nem igazán hibajelentés a Slimefun logikája alapján.

**Comment by poma123** [comment]
Nem csak FPS lag lesz tőle...

**Comment by andris155** [comment]
Majd rakok limitet a tárgyakra, hogy törölje ha túl sok.

**Comment by andris155** [comment]
Meg írok a fejlesztőnek ezzel kapcsolatban. Mert ez nem lag. Konkrétan megöli a klienset meg a szervert is. XD

**Comment by andris155** [comment]
Letiltottam végül. A limit semmit sem ér. 1M tárgynál instant fagy minden. A kliens és szerver is. Pedig ennél még több blokk is férne a legnagyobba.
A fejlesztőnek írtam.

**Comment by KingDeadZ** [comment]
Elméletileg javítva lett.

**Comment by poma123** [comment]
Nem lett javítva xdd vagyis szarul lett javítva, most ha kiütöd, kitörli azokat az itemeket ami x stack felett dobódott ki. nem tudom miért nem fogta fel amit leírtam neki

**Comment by poma123** [comment]
+ elméletileg valami dupe bug is van benne

**Comment by KingDeadZ** [comment]
láttam sf dcn, azt írta a fluffy hogy valszeg másik plugin az okozója, majd kiderül ha megtalálják a bugot

**Comment by andris155** [comment]
Nem értem miért baj ha kitörli a tárgyakat. Így legalább fagyást már nem okoz. Tehát simán lehet engedélyezni. Én duplikációs hibáról nem tudok benne. Ami volt azt javították.

**Comment by poma123** [comment]
xd azért, mert valaki megszerez magának cuccokat, azt eltárolja, aztán ha kiüti a barrelt törlődik? xdd logikátlan és nem megérős

**Comment by andris155** [comment]
Nem értem miért üti ki aki sok tárgyat tárol benne. Szerintem tök logikus, hogy lefagy tőle a játék ezért nem ütik ki így amúgy sem.

**Comment by andris155** [comment]
Duplikáció mindig van és lesz is. Ez a Minecraft. Lehet a barrel-el még akkor duplikált, amikor nem volt még javítva a tényleg létező duplikációs hiba benne. Bár Discord-on én ezt nem követem ha ott volt. Nincs időm még azt is követni sajnos. :(

**Comment by andris155** [comment]
Hülyén oldotta meg a fejlesztő, de szerintem már nem fog ezzel foglalkozni. Ha megoldja akkor persze majd lesz engedélyezve.
