### ISSUE TITLE
Eventes Ládát Savszigetre!

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4101]
**Szerver**:Savsziget

Szerintem az emberek sokkal szívesebben játszanák az eventeket amiket staffok tartanak ha esetleg nyereményként nem 10 token lenne, hanem mondjuk egy Eventes kulcs a Survi szerverről. Így is sokszor nem indítanak eventet a segítők, mert tudják hogy nem jönnének elegen.

**Comment by MrZero1** [comment]
Savszigeten nem lesz ilyen fajta láda.
