### ISSUE TITLE
Helicopter hat - Fluffy

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4102]
**Szerver**: Szurvi, sav

Sokkal olcsóbb mint a jetpack, pedig ugyanazt tudja. szerintem ez legyen kivéve, mert így nincs értelme a jetpacknak

**Comment by andris155** [comment]
Esetleg valahol valamerre talán a Slimefun Discord szerverén meglehetne írni ötletként a fejlesztőnek, hogy változtasson rajta. Majd letiltom persze így jelenleg.

**Comment by andris155** [comment]
Az pedig nem hiba, hogy olcsóbb... Kérlek megfelelő kategóriát válassz legközelebb, ha GitHub-ra írsz.

**Comment by skrisz0101** [comment]
nem tudtam mit adjak neki, ötlet? xd

**Comment by andris155** [comment]
letiltottam.
