### ISSUE TITLE
FluffyMachines - Csak tölgyfából lehet botot, ládát, eszközöket craftolni az Auto Crafting Table-ben

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4103]
Szerver: Savsziget, Túlélő

![kép](https://user-images.githubusercontent.com/16057404/96754440-97c08000-13d1-11eb-8691-ea103aae54df.png)
![kép](https://user-images.githubusercontent.com/16057404/96754606-d1918680-13d1-11eb-8d4f-f49d746d574f.png)
![kép](https://user-images.githubusercontent.com/16057404/96754668-e3732980-13d1-11eb-8986-e6236d46c535.png)

**Comment by andris155** [comment]
Ennél is megírod azokat is amiket lehet vanilla tárgyként használni? :D

**Comment by andris155** [comment]
Holnap már elvileg működnie kell nem tölgyfából is.

**Comment by andris155** [comment]
508 OCD
