### ISSUE TITLE
Slimefun - LiteXpansion

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4104]
Mivel tiltva vannak a solar panelek (mivel túl opk) így nem lehet a solar sisakokat sem craftolni. 
![image](https://user-images.githubusercontent.com/38157910/96767653-1a9b0800-13dd-11eb-89a3-90c08d5e9916.png)

**Comment by andris155** [comment]
Akkor ezt is tiltsam le?

**Comment by poma123** [comment]
Engedélyezve nem lesznek, szal sztem igen

**Comment by UDPSendToFailed** [comment]
Ezek szerintem maradhatnak, alap Slimefun-os solar kell hozzájuk.

![kép](https://user-images.githubusercontent.com/16057404/96864648-0ac90580-1469-11eb-9be0-6bcdaa610baa.png)
![kép](https://user-images.githubusercontent.com/16057404/96864660-11577d00-1469-11eb-953f-99e491dc432c.png)
![kép](https://user-images.githubusercontent.com/16057404/96864687-1a484e80-1469-11eb-8c36-72c25b4f1f54.png)
![kép](https://user-images.githubusercontent.com/16057404/96864709-22a08980-1469-11eb-956f-eed30eed1ec5.png)

**Comment by andris155** [comment]
Akkor csak az Ultimate Solar Helmet legyen tiltva?

**Comment by andris155** [comment]
Az Ultimate Solar Helmet-et akkor letiltottam. Majd holnap betölt.
