### ISSUE TITLE
LiteXpansion - Hibás craft

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4105]
Az Uninsulated Copper Cable craftja hibás, Copper Ingot van benne a Copper Item Casing helyett.

![kép](https://user-images.githubusercontent.com/16057404/96893257-cf3f3300-148a-11eb-90fd-bebddff980da.png)

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a hibát.
