### ISSUE TITLE
Survival - Kreatívban lerakott csillét ki lehet ütni más telkén

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4107]

**Comment by KingDeadZ** [comment]
A simát nem lehet.

**Comment by andris155** [comment]
Nagyjából 60-90 nap a javítás szerintem mire lesz. Addig kreatívban szerintem nem érdemes csillét lerakni olyan helyre, ahol kitudja más is ütni.
