### ISSUE TITLE
Javításra szorul (addolás) 

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4108]
**Szerver**:Szurvi, sav

Nos, a kreatívban, egy fáklyára zuhanó üllőt (ugye a fáklya szédszedi azt) survivalban fel felet szedni, így pl. boltokban árusításkor ez nagy vas-spórolás tud lenni.

**Comment by MrZero1** [comment]
A boltból addig kikerült, míg nem lesz javítva.

**Comment by Jaffis** [comment]
Király. 😃

**Comment by Jaffis** [comment]
Gondolom ez sem nagy hiba, vagy valami OCD-s... xd

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a hibát.
