### ISSUE TITLE
Slimefun - Jet Boots és Jetpack nocheat hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4109]
A kettő együtt alig használható, szinte folyamatosan visszadobál, néha a 2-4 chunkkal korábbi helyemre is.

Jetpack magában is eléggé bugos, felrepülök 50-60 blokkot, és visszarak a földre.

**Comment by andris155** [comment]
Nekem hibátlanul működnek ezek. Lehetséges, hogy ha nem 20 a TPS akkor nem működik megfelelően. De azzal nem tudok mit kezdeni. Talán az új gépen jobbak a TPS értékekek valamivel.
