### ISSUE TITLE
Shoopkreepers - slimefunos csere

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4110]
**Szerver**: Szurvi, sav

Nem lehet slimefunos itemekkel (ami nem fej) kereskedni. 
Carbonadoval sikeresen kereskedtek a cserekereskedőmnél, de basic circuit board-al (sínnel) nem sikerült, azt írta nem lehet kereskedni slimefun itemmel

**Comment by poma123** [comment]
#3817 vezetett idáig.

**Comment by andris155** [comment]
Ez direkt ilyen.

**Comment by andris155** [comment]
Azt nem tudja a Slimefun, hogy az most Shopkeeper-e.
