### ISSUE TITLE
ploton kickelés

### ISSUE THREAD

**Issue by snowman142** [TheOld-Crafters/Minecraft-servers#4111]
Survival szerveren található a probléma a /p kick (játékosnév) parancs továbbra sem működik...Azt írja hogy "Játékos nem található",a problémát mutattam poma-nak is,legutóbb nem lett foglalkozva a problémával mert hogy "nem sikerült reprodujálni a hibát" mostmár nem lenne rossz ha lenne vele foglalkozva,ha kell akkor játékon belül tpz-en rám valamelyik admin vagy akárki aztán megmutatom...nem mindenkinél de van jópár játékos akti nem lehet valamiért kickelni..

**Comment by poma123** [comment]
Tanúsítom, hogy nem működött.

**Comment by KingDeadZ** [comment]
Van benne valami, én pár hete Bladeot nem birtam hozzáadni a telkemhez (in fact hozzá lett adva csak nem birt csinálni semmit sem) amúgy a /p kick * kidobja?

**Comment by andris155** [comment]
Rajta állt a játékos a telkeden, amikor ki akartad dobni a telekről?

**Comment by poma123** [comment]
Rajta

**Comment by andris155** [comment]
Megtudod adni a telek ID-ját?

**Comment by poma123** [comment]
Snowman játékos egyik telke volt, már nem tudom melyik.

**Comment by snowman142** [comment]
> Megtudod adni a telek ID-ját?

-18--36

**Comment by andris155** [comment]
Ez egy olyan dolog, ami szerintem nem nagyon javítható. Optimalizáltam az adatbázison, hátha megoldja a problémát.
