### ISSUE TITLE
Discord widget weboldalra

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4112]
**Szerver**: Toc

![image](https://user-images.githubusercontent.com/69635280/97113776-d1a0c780-16ec-11eb-93a1-929bc48dfb46.png)
Kikerülhetne weboldalra ez a widget cucc. Menőbb mint az a kis kocka 👍

**Comment by poma123** [comment]
Viszont látszik hogy ki van fent és hol, nem biztos hogy mindenki szeretné tudatni azzal aki nincs bent a szerveren.

**Comment by KingDeadZ** [comment]
Bárki beléphet a szerverre igazából, szóval szerintem nem számít. Annyi biztos, hogy menőbben nézne ki

**Comment by andris155** [comment]
Egy ideig volt, de eléggé lelassította a weboldal betöltését így inkább kivettem. Továbbra se szeretném így inkább ezt használni az oldalon.
