### ISSUE TITLE
savszíget  nether generator hiba

### ISSUE THREAD

**Issue by Aquir-0** [TheOld-Crafters/Minecraft-servers#4114]
szerver: savsziget
A nether generator nem működik , netherbe próbáltam mert azt írja hogy ott kell.

**Comment by andris155** [comment]
Vizet se lehet a nether-ben lerakni. :D

**Comment by Tomi321** [comment]
Tudtommal nem vízzel, hanem valamelyik jég típussal lehet a generátort csinálni. Mmirror megépítette, és nála tökéletesen működik. Vagy kék jég, vagy tömör jég kell a víz helyére.

**Comment by andris155** [comment]
Így működik:
Bal oldalt láva, a közepén ahol létrejön a blokk oda soul soil kell alá, bal oldalra pedig kék jég.
![2020-10-26_23 08 37](https://user-images.githubusercontent.com/8324198/97234051-5b7d8d00-17e0-11eb-85c1-75cae7883d9c.png)
