### ISSUE TITLE
FluffyMachines Sf addon bug

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4116]
Ez a frissen hozzá adott addon hozott egy Foundry nevü gépet. Ez a Tinker Construct ihlette gép egy Multiblock structure gép ami azt teszi lehetővé, hogy Dustokat lehessen benne raktározni (Több 10 ezer db-t). Ha a gépbe lávát rakunk, akk a dustok olvaszthatóak. Ezt visszafele is lehetséges.  

A hiba: Tegyük fel, hogy raktározok 64 db dustot a gépbe. De ki szeretném szedni. Van opció, hogy eggyesséve szedjük ki ball klikkel, és hogy 64-et jobb klikkel.  Ha a második funkciót használom, akk a gép csak 1 dustot ad vissza, a többi eltünik.

**Comment by KingDeadZ** [comment]
Nincs sok köze a tinkers constructhoz szerintem azon kívül h 1szerkezetbe raksz sok ércet, de a foundryba csak 1fajtát lehet mondjuk p.p

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a hibát. Nekem 64-et ad jobb klikkel.

**Comment by KingDeadZ** [comment]
Elméletileg már javította a fejlesztő
