### ISSUE TITLE
OldCup esemény ötlet.

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4117]
Survival -->

A szerveren sok külömböző esemény van megtarva az év mindegyik szakaszába. (Pl karácsony, halloween, szülinap, stb). De vanna olyan évszakok, ahol több hónapon át nincs semmi esemény. (Pl: tavasz közepe-Nyár végéig).
Itt az ötletem. Ez a szerver saját ünnepe lenne, az "OldCup" esemény.  Ez egy 1 hétig tartó verseny, amibe az győz aki legjobban ismeri a szerver mindegyik oldalát. Külömböző küldetéseket kellene végrehajtani, amiből pontokat kapnánk. 
Példa kükdetésre: "Szerezz 10 tokent" "100 eventpontot", Szerezz valami SlimeFun tárgyat" (A tárgy meghatározott lenne, olyan amit nem lehetne automatán farmolni) "bányássz 50 vasat", "szerezz 30 tököt", "szavazz 3× a szerverre".  A küldetések több külömböző águak, ami körbe ölelik a szerver sajátosságait (Eventek, Slimefun, alap minecraft)
A pontok az esemény végéig gyűjtődnének, majd az esemény végén a Top 10 jutalomba részesül.
Top 1:5000 OCD
Top 2:2000 OCD
Top 3:1000 OCD
Top 1-5: OldKulcsok,
Top 1-8 Exluzív modellezett fejfedő (Pl egy korona) (Mint a Szülinapi kalap)
Top 1-10 1M játékpénz.

A küldetések után kapnánk tárgy fizetőeszközt, amit beváltanánk a beváltóba exkluzív szettre, eszközre.

**Comment by derpyAK** [comment]
Savsziget?

**Comment by skrisz0101** [comment]
szerintem nem kell ekkorában megvalósítani. lehetne ilyen akár minden héten (úgy értve hogy hetente változna a küldetés, de mégis hasonló), de persze sokkal kisebb jutalmakkal. pl old kulcs, pár száz ocd, a beválthatós cucc se lenne rossz.

**Comment by KingDeadZ** [comment]
Ilyen megvalósításban egy külön eventként simán lehetne tartani, természetesen külön világban. Az biztos, hogy a nyeremények túlságosan is nagyok, simán rálehetne mondani, hogy vicces

**Comment by DiaGamer321** [comment]
Én azért írtam ekkora jutalmakat, hisz ez egy verseny lenne, aminek emlékezetes nyereményei kell legyen. És ez csak évente 1× lenne nyár eleje-közepe közt. Ennyi belefér szerintem.

**Comment by skrisz0101** [comment]
a hetente változó küldetések itöbbet tennének sztem  a szerverhez, mint egy esemény ami csak évente 1x van. persze a kettő nem zárhatja ki egymást, lehetne akár egy havonta változó küldetéssorozat, aminek nagyobb a nyereménye (és persze nehezebb a küldetése)

**Comment by Tomi321** [comment]
Én ezt az egészet nagyon jó ötletnek tartom, de én inkább a heti küldetéseket preferálnám, mint az évi 1 eventet. Persze akkor már nem csak survira, hanem savszigetre is jöhetne egy ilyen

**Comment by KingDeadZ** [comment]
Adom. Lehetne majd egy github ötletes megathread ehhez, hogy minél több legyen.

**Comment by skrisz0101** [comment]
@MrZero1 vélemény?

**Comment by MrZero1** [comment]
Most akkor ez egy esemény lenne vagy egy küldetéses rendszer? :D

**Comment by KingDeadZ** [comment]
A 2. lenne a legjobb, mert egyébként szerintem nincs értelme az eseménnyé tételének.

**Comment by skrisz0101** [comment]
Sk verzióban küldetésrendszer
Akár hetente változó
akár honaponta
vagy tudomisén

**Comment by skrisz0101** [comment]
Amúgy nemtom. Ez a jelentés meg kell? Xd
Nem hinném hogy megvalósításra kerül

**Comment by andris155** [comment]
A túlélő szerveren jelenleg nem a küldetéses rendszer a fő fejlesztési irány. Viszont az eventrendszer folyamatosan van fejlesztve.
