### ISSUE TITLE
Enderláda event végén

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4118]
**Szerver**: Szurvi

Nem minden event végén van enderláda, pedih jó lenne, hogy bele lehessen rakni a nyereményeket
pl.: Lavarun. ha találok még olyat, akkor ideírom, de nem tudom mindegyiket kivinni xd

**Comment by MrZero1** [comment]
Pedig kivihetnéd, egyik sem nehéz 😌

**Comment by KingDeadZ** [comment]
Ha nem is nehéz, de csomó hosszú, és 1ugrást elrontasz és kezdheted elölről, ez egy olyan dolog ami nagyok sok embernek a k edvét elveszi az eventektől.

**Comment by MrZero1** [comment]
Akkor nem eventezik. 
Sk,majd írd meg Discordon, hogy melyik eventen nincs még
