### ISSUE TITLE
Szerverek közti /m

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4120]
**Szerver**: Mindenhol

Jó lenne, ennyi.

**Comment by skrisz0101** [comment]
ma vagy 40x beírtam h /oldspace, hogy segítsek. a /m azért gyorsabb

**Comment by andris155** [comment]
Az EssentialsX nem támogatja. Nem akarok inkább más privát üzenet kezelőt csak ezért.

**Comment by poma123** [comment]
Nem kell más üzenetkezelő, a mostanit lecserélni nem kell. Egy kiegészítés kellene csak, ami csak globális üzenetküldésre képes.

**Comment by MrZero1** [comment]
Tényleg jó volt, amíg volt, és jó lenne most is.

**Comment by skrisz0101** [comment]
hm

**Comment by andris155** [comment]
Találtam már rá megoldásokat. Majd ha lesz időm meglesz valósítva szerintem.

**Comment by andris155** [comment]
Visszakerült a régebben is használt megoldás. Elvileg így már lehet a szerverek között is privát üzeneteket írni a szokásos privát üzenetes paranccsal. A formázást inkább úgy csináltam meg ahogy az Essentials-ban van. Extraként az üzenetre kattintással lehet válaszolni vagy új üzenetet írni, ami szerintem sokszor hasznos tud lenni.
