### ISSUE TITLE
Oldspace - mennyi üzemanyag kell?

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4121]
**Szerver**: Oldspace

Sztem sehonnan se tudják meg (ha nem kérdezik), hogy mennyi üzemanyag kell bolygónként a rakétába. ezt valahol le lehetne írni, akár leírásokban @poma123

**Comment by poma123** [comment]
Kiírja amikor felépítik a rakétát :)
