### ISSUE TITLE
Nincs elég áram

### ISSUE THREAD

**Issue by snowman142** [TheOld-Crafters/Minecraft-servers#4122]
Survival szerver
Amióta megtörtént a szerver gép váltás azóta nem termel elég áramot a reaktor/energized solar kombó,nem raktam le semmilyen gépet,semmi nem változott,és még sincs elég áram,leraktam még legalább 3 másik energized panelt,továbbra is minusz J-ba vagyok,ha kiütök 1 capacitort v valamit változtatok a rendszeren akkor ideiglenes jó,felmegy az áram 200k J-ra aztán amint eléri lecsökken megint -50k-ra....elég idegesítő h így gyakorlatilag nem megy semmilyen gépem...

Remélem ezt a problémát hamarabb sikerül orvosolni mint amiket eddig leírtam,nem lenne rossz valami visszajelzés a ploton való kickelés bugról sem,köszönöm

**Comment by mangoshell** [comment]
Elvileg a reaktorokkal van valami. ha kiütöd és visszarakod működnie kell.

**Comment by andris155** [comment]
Elvileg voltak olyan eszközök, amik nem használták áramot. Most ezt javították.
Ezzel a jelentéssel így semmit se tudok kezdeni. Pontos gép nevek kellenének, amik túl sok áramot használnak esetleg.
