### ISSUE TITLE
NINCS ELÉG ÁRAM

### ISSUE THREAD

**Issue by snowman142** [TheOld-Crafters/Minecraft-servers#4123]
SURVIVAL SZERVER

66 Electric Dust fabricator//92 Cobblestone generator//39 electric ingot factory//28 Electric smeltery//16  Electric ore grinder//
5 Electric dust washer//22 Carbon press//14 Carbonado edged furnace//3 Automated crafting chamber//8 Electric dust recycler

Ezeket a gépet látom el 15 Nuclear reaktorral és 15 Energized solar generatorral (csak a jelenlegi helyzet miatt raktam le ennyit,és így sem működik)
Ha kiütök 1 capacitort,vagy lerakok újra 1 nuclear reactort akkor működik,amint eléri 1 bizonyos J szintet,leaáll,és lecsökken minuszba.Játékon belül Snowman a nicknév ha esetleg további információkra lenne szükséged.Remélem ennnyi infóval már tudtok valamit kezdeni.
Ez a telek megtalálható a -18;-36 koordinátánál.

**Comment by snowman142** [comment]
Yah és hozzá tenném h egészen tegnap előttig (tegnap ugye egész nap nem volt szerver) működött,sokkal kevesebb Energized solar generatorral,azóta nem változtattam semmit a rendszeren,hozzá sem nyúltam,fel logoltam és már nem jó.

**Comment by andris155** [comment]
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4122

**Comment by andris155** [comment]
Le kellene tesztelni egy gépet ezekből a típusokból, hogy melyik használ túl sok áramot.

**Comment by KingDeadZ** [comment]
66 dustfab áramfogyasztás: 28116 Snowman leírt áramtermelése: 11340 a többi gépet bele se számolom, elég egyértelmű

**Comment by lovi-dev** [comment]
> 66 dustfab áramfogyasztás: 28116 Snowman leírt áramtermelése: 11340 a többi gépet bele se számolom, elég egyértelmű

Szerintem is, az a 11k áram az nagyon kevés. 
Nekem is néha egy-egy aksi pirosan villog,  de minden megy. Mindez 41k áramtermeléssel és 40 dust fab.-al.
Egyszerűen az a 66 dust fab. elkezdett fogyasztani, ennyi. 
Ha kiütök egy energiatárolót (reaktor is az) akkor nálam is lemegy nullára, kvázi "kisül" és nulláról újratöltődik. Onnantól pedig már csak fogyasztás kérdése...
