### ISSUE TITLE
Fű block addolási lehetőség

### ISSUE THREAD

**Issue by Bedrich102** [TheOld-Crafters/Minecraft-servers#4124]
**Szerver**:Survival

Kreatívban raktam le pár fű blockot ami végül nem kellet, gondoltam gyorsabb lesz survivalban ásóval kiszedni. Na hát a kreatívban lerakott füvet fel tudtam venni survivalban az inventoryba. Próbáltam több olyan blockot is ami ásóval üthető ki, és az összes közül még a sima alap casual föld block viselkedett így, ki bírtam szedni. Az ásó egy silk touchos ásó volt, így jött ki a fű, ha simán kézül ütöm ki akkor ugye föld jön ki. 
Ez 18ezer milliárd ocd lesz, köszi hali.

**Comment by andris155** [comment]
A teljesen értéktelen blokkok nincsenek lementve, hogy kreatívban rakták-e le. Felesleges lenne.

**Comment by poma123** [comment]
#4012
