### ISSUE TITLE
Sziget hiba

### ISSUE THREAD

**Issue by szofogado** [TheOld-Crafters/Minecraft-servers#4125]
Szerver: savsziget

Ma felmentem savszigetre és észrevettem, hogy valami nem jó a szigetemmel. Megnéztem a csapattagokat és nincs benne Aquir. Azt írja, hogy én vagyok a tulaj, de nincs semmi olyanhoz jogom, amihez a tulajnak van.
 Megnéztem a sziget szintet is és a 72k-ról le esett 86-ra. Ugyanúgy van jogom mindenhez, mint eddig is.
 /is top-ban ott van Aquir szigete amiben én is benne vagyok és írja is, hogy 72265 a sziget szint. 
![2020-10-31_08 13 14](https://user-images.githubusercontent.com/52892955/97774819-72fba380-1b5b-11eb-9d38-218fd2816f52.png)
![2020-10-31_08 45 49](https://user-images.githubusercontent.com/52892955/97774823-78f18480-1b5b-11eb-83c0-a19346d91f67.png)

**Comment by Tomi321** [comment]
Nekem az is topon sem vagytok fent, ha gépközelbe kerülök majd küldök egy képet is róla.

**Comment by andris155** [comment]
Elvileg van rá valami javítás, hogy javítani lehessen az adatbázist. Majd kipróbálom. Sajnos az adatvesztések miatt köszönhetően annak, hogy elég gagyi módon tárolja a szigeteket a plugin többször volt már visszaállítva és így keletkezett benne jópár hiba.

**Comment by andris155** [comment]
Egyelőre a javítás nem működik. A fejlesztőnek megírtam, de az se fog mindent megoldani sajnos. Ezek megoldásában az adminokat kell keresni.

**Comment by MrZero1** [comment]
Az adminok mit tudnak csinálni?

**Comment by andris155** [comment]
Én megpróbálnám beállítani újra tulajnak.

**Comment by andris155** [comment]
Csapattagnak meg újra hozzáadni akit írt.

**Comment by szofogado** [comment]
Ma felmentem a szerverre és semmihez sincsen jogom a szigeten.

**Comment by andris155** [comment]
Mert már gondolom több szigeted van vagy hozzá vagy adva többhöz, amit nem lehetne. Elsősorban meg kell keresni azokat a szigeteket amikhez hozzá vagy adva, és azokról törölni. Majd úgy lehet hozzáadni az eredeti szigethez téged. Ha megadod a koordinátát arról a szigetről, ami a tiéd (tulajdonosként) akkor valamikor 23 körül megpróbálom ezt megoldani.

**Comment by szofogado** [comment]
Már megoldódott a probléma
