### ISSUE TITLE
OldSpace hibák megathread

### ISSUE THREAD

**Issue by poma123** [TheOld-Crafters/Minecraft-servers#4126]
**Szerver**: OldSpace

_Hibák az OldSpace szerveren gondosan összegyűjtve Csikbaro krónikái alapján_

#### Mars
1. :x: Mars homokot nem lehet letenni.
**A vörös homok addolás kiküszöbölése miatt.**
#### Organic
0. ✔️ Organic 1. előrelépését csak a tölgy fára oldja fel. szerkeszteni kéne h legalább mindenféle fára oldja fel
**Javítva**
1. Mushroom tehén esetén nem veszi le a 13 szintet DNS mintakor
2. ✔️ Zafír kard használatkor nem használodik
**Direkt ilyen, örüljetek hogy nem használódik C:**
3. :x: Szelet instant megadja a jura-kori őslovon való lovagláskor, leírás szerint 500 blockot kell vele megtenni
**Sajnos direkt ilyen, a távolságmérés miatt eszméletlenül laggolt a szerver.**
4. :x: Jura kori fa kivágásakor nem csak ősi gyűmölcsöt ad hanem az alap mc-s sweet berry-t is ami el lehet ülteni
**Sajnos ez javíthatatlan.**
5. ✔️ Hókuszpókusz boss bebugoltatható (láma nem érzékeli hogy rajta ül ezért betud vele menni a lépcső alá a dungeonban), valamint meg lehet nyitni a trade ablakát ami igen furcsa
**Javítva, a láma kapott lassúságot, és már nincs trade ablak.**

#### Enceladus
1. itt is a Mushroom tehén esetén nem veszi le a 13 szintet DNS mintakor
2. ✔️ Lávás vödröt meglehet kapni a vastartalmú kőzetmag sima kemencében való kiégetével is nem kell az üstbe beledobálni
**Javítva, az üstös recept véletlenül került be, kemencében kell kisütni.**
3. Sima gyémánt sisakot nem lehet craftolni, de a dia szett többi darabját viszont igen
4. ✔️ Kastélyban a vizizombik nem támadnak csak állnak bambán
**Valamiért egyáltalán nem támadnak ott a drownedek, sztem a biome miatt. Zombik spawnolnak mostantól.**

#### Föld
1. ✔️ Amikor normális gravitációban használják a jetpacket és lezuhannak, nagyon nagy sebzést kapnak.
(Suggestion: Amikor abbahagyják a használatát, kapjanak egy nagyon rövid lassú esés effektet, ha nincs rajtuk. Ennek meg kell oldania a problémát.)
**Javítva a fenti módon**
2. ✔️ Zafír kard használat során nem használódik
**Direkt ilyen, örüljetek hogy nem használódik C:**
3. DNS átalakítónál a gombabocinál nem veszi le a 13 szintet
4. :x: Jura-kori ősló rögtön megadja a Megszelídített szelet, nem kell 500 blockot megtenni vele
**Sajnos direkt ilyen, a távolságmérés miatt eszméletlenül laggolt a szerver.**
5. ✔️ Flint-tel behozható a páncélállvány plugin kezelő felülete, és használható is
**Javítva**
6. :x: Tudás könyvében a "Speciális Blokkok" kategóriában van a Kincses láda, inkább az egyében lenne a helye
**Direkt van ott, mivel egy speciális blokk, ami nem úgy viselkedik letételkor, mint egy sima láda.**

7. ✔️ Fekete toll itemnek nincs benne a könyvben a receptje (Oké nem durva recept de a többi benne van akkor ez is leférne slight_smile )
**Bekerült az erőforrások közé, mivel az egyéb kategóriában nincs több hely.**
8. ✔️ End rod készíthető zombiaggyal is (NBT tag-et nem veszi figyelembe, zombi agyat is az alap popped chorus fruit-nak veszi)
**Javítva**
9. :x: "Szív" használható poti főzéskor fermentált pókszemként (NBT tag-et itt sem veszi figyelemben)
**Direkt ilyen :C**
10. ✔️ 4 "Varázspor"-ból készíthető glowstone (NBT tag-et itt sem veszi figyelemben)
**Javítva**
11. :x: "könnyű fém" és az "elektum" használható sima alap vasként (NBT tag-et itt sem veszi figyelemben)
**Szerintem ez nem probléma, a sima vas sokkal kevesebbet ér, mint a fenti kettő item. Ha valaki erre akarja pazarolni, akkor hadd csinálja.**
12. :x: Küldetéseknél a "Régészet mestere VI." küldetésnél rögtön megadja az utána következő "Reinkarnáció"-t az NBT tag miatt
**Sajnos ez javíthatatlan, mivel az előző előrelépés iteme (a csiga fosszília) is nautiluszhéjból van.**
13. ✔️ Tudás könyvében a "Mágnes" leírása szerint vasblockból alakítható át, közben Titánium egységből lehet, küldetéseknél is a Titánium egység szerepel
**Javítva**
14. Eye of Ender nem az End portálhoz vezet, többször próbáltuk, mindenkinél máshova vezet ahol nincs End portál
15. ✔️  Slenderman támadás esetén passzív nem támad vissza, Enceladus-on vissza támadott
**Javítva**
16. :x: Másik, nagyon kíváncsi lennék hogy hogyan tesztétek a Föld-i idézhető mobok. Aki egyedül játszik teljesen esélytelennek látom hogy végig tudja játszani, már a Phantom is simán megöl, nem a sebzése hanem a mérgezés, hiába iszik valaki tejet semmi sem segít, mérgezés ellen nincs tudtommal tartós ellenszer. Phantomot még ki lehet trükközni, de a Bukott angyalt már nem hiszem, többször próbáltam már (Organicon is iszonyat szenvedés volt) jeges ij semmit sem segít, Thor kalapácsával se lehet megölni, a vex-ek hamarabb megölnek mielött a Bukott angyal meghalna, hiába az aranyalma, varázspálca regenerációja. Csak úgy sikerült megölni hogy 2 voltunk de akkor is 2x meghaltunk. Teljesen inkorektül vannak beállítva legalább 3-4 ember kellene hozzá hogy meg lehessen őket ölni.
**Skrisz01 úrfi tesztelte, pár halál belefér, ő egyébként dia szettben tesztelte és meg tudta ölni. Ajánlott az aranyalma, regeneráció poti esetleg az életmentés totem használata. Ez már tényleg a végjáték.**

#### Egyéb
1. ✔️ Nem működik a kapszula letétel 1.16.3-on
**Javítva**
2. ✔️ A rakéta kilövés GUI hibát ír kattintáskor
**Javítva**
3. ✔️ Az előrelépések nem oldódnak fel... pl Hold homoknál
**Javítva 3 és fél óra kínkeserves munka árán**
#### Organic

1. ✔️ Map tetején a barrier fölé is tudnak mobok spawnolni
**Javítva, 255 fölötti koordinátára nem tudnak többé spawnolni.**

2. :x: Obszidián gömböket nem csak a felszínre hanem a bedrock szintre is generál időnként
**Nem lehet vele mit kezdeni, mondhatnám azt, hogy direkt ilyen. A világ előre le van generálva.**
3. ✔️ : Redstone-t nem csak ősi gyümölcsből lehet készíteni, hanem az obszidián gömbökben is lehet találni.
**~~Alapból le van generálva a világ, így onnan is lehet szerezni.~~ Javítva, most ugyanúgy dobnak redstonet, de egy elnevezett fajtát, amit nem lehet használni a craftban amihez kell.**
4. ✔️ Dimenzós sötét kardhoz több időbe telik összefarmolni hozzá az alapanyagot mint az összes többi küldetéset megcsinálni az Organicon, valahogy nem jön ki a ballansz 
**Olcsóbb lett a craftja.**
5. Gázmaszk elhasználodik akkori is müködik, csak kiírja hogy craftolj újjat

## Tapasztalatok

1. ✔️ Tudás könyvében hiába van alul egyes itemeknél részletesebb tájékoztató teljesen kivül esik a fószutól ami miatt szinte senkisem találja meg (Jetpack repülést szinte mindenki megkérdezi még az is aki csendben játszik mert tud tájékozodni a játékban).
**Javítva, kiegészítettem a /teendő parancsot.**
![image](https://user-images.githubusercontent.com/25465545/97778670-00012580-1b79-11eb-8364-0d4101b1ef11.png)

2. :heavy_check_mark: Üst problémát olvastam Discordon, de mivel nincs feltünteve a játékon belül ezért aki nem tud róla az nem tudja használni ha nem üti föl, új játékosoknál rendszeresen előfordul hogy mindent megpróbálnak, és nem éritik miért nem müködik ha a könyv szerint csinálják.
**Elvileg sikerült javítani, ha nem lesz lag, akkor marad is kikapcsolva az üst lista időszakos törlése.**
3. :x: Holdon és a Marson a Boss-okat nagy könnyü legyőzni, túl könnyü is, nem tudnak kijönni elég csak az ajtóban állni és ütni öket, valamint a ládák megtalálása/kifosztása is túl könnyü, ha valaki Jetpack-el megy oda, abban semmi kihivás sincs.
**Holdon és marsok még direkt könnyűek a mobok, a dungeonok kifosztásán pedig nem lehet sajnos nehezíteni, csak alulra spawnolnak mobok.**
4. ✔️ Dungeon területére sokan bemennek loval nem tudják hogy bebugol, ennek következtében vagy cirkuszulnak a cseten hogy szar a játék lagol/bugol, vagy egy nemtetszés nyilvánítás után lelépnek a szerverről és többet nem nagyon jönnek vissza(több példást láttam rá).
**Ki lett véve az elteleportálás, ami miatt bebuggolt.**
5. ✔️ Marson a rakéta üzemanyagnál nem tudom, hogy elíráse vagy szándékos, de nagyon kellemetlen hogy az állati maradványokból csak 8 üzemanyag jöni ki miközben a rakéta elindításához 10-re van szüksége. Mivel a dungeon több ezer blockra van mindenkitöl ami 20-30 perc utazást is jelenthez ez így nettó szivatásnak tünik mivel, amíg nem teszik le a rakétát ehez az információhoz nem is tudnak hozzájutni.
**Javítva, most már 10-et ad az állati maradványok craft.**
6. :x: Küldetéseknél összevissza vannak a füldek fönt nincs sorrend, mars van mindig elöl és utánna nem is az Organic jön, teljesen rendezetlen.
**Ez sajnos javíthatatlan, nem lehet sorrendbe tenni. Viszont az pozitívum lehet, hogy amikor fellép/világot vált valaki, mindig a megfelelő lapfül kerül kiválasztásra.**
7. ✔️ Eszközöknél/páncélzatoknál a leírásban van hogy feljavítható xyz itemmel, miközben a /fix parancsal csak simán 5 szintért megcsinálható ugyan ez, kettő kicsit üti egymást.
**Javítva, most már a /fix parancsot írja.**

## Javaslatok

1. ✔️ Leírások közé vagy valamelyik infós részre bele kellene tenni külön, hogy a tudás könyvében az egyes itemekhez kiegészítő informácót hol lehet megtalálni
**Javítva, kiegészítettem a /teendő parancsot.**

2. ✔️ Üsttel kapcsolat infót szintén valhol fel lehetne tüntetni.
**Mivel már nincs üst törlés, nincs rá szükség.**

3. ✔️ Mars-on a rakéta üzemanyag vagy legyen 8 vagy a boss által dobott item adjon 10 állati maradványt a craftolás után.
**Javítva, most már 10-et ad az állati maradványok craft.**

**Comment by skrisz0101** [comment]
Vöröskő érc dobhatna valami full más dolgot, ezzel ki lehetne javítani

**Comment by poma123** [comment]
Az mekkora baromság már xd

**Comment by skrisz0101** [comment]
+1 észrevétel: MINDEN SZAR

**Comment by skrisz0101** [comment]
Organic 1. előrelépését csak a tölgy fára oldja fel. szerkeszteni kéne h legalább mindenféle fára oldja fel

**Comment by skrisz0101** [comment]
Ha az érc keresőt aktiválják, kilépnek majd vissza, akkor ismét tudják használni
Nem lesz cooldown
kaszpi jelentette
