### ISSUE TITLE
Tripla HG szöveg

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4127]
**Szerver**: Survival

Mindent háromszor (jobbesetben) ír ki a HG.

Képek:
![kép](https://user-images.githubusercontent.com/29709854/97781816-22ea0480-1b8e-11eb-8198-9c47a6035859.png)
![kép](https://user-images.githubusercontent.com/29709854/97781819-28474f00-1b8e-11eb-8bd7-45ce842ba8a7.png)
![kép](https://user-images.githubusercontent.com/29709854/97781822-2c736c80-1b8e-11eb-91fd-0accce78d2b7.png)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/97784797-54200000-1ba1-11eb-9e36-af8a4fd2dc3c.png)
Ilyen is van még pluszba

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/97784838-91848d80-1ba1-11eb-993d-e7116f5d4790.png)
Ez meg semmiség, de ha tele van az aréna, kiírja angolul is

**Comment by MrZero1** [comment]
Nem tudom, lett e javítva, de most (új arénát állítottam be, azt teszteltük) normálisan viselkedett a HG, nem írta ki többször a dolgokat.

**Comment by andris155** [comment]
Nem módosítottam rajta pedig.

**Comment by MrZero1** [comment]
Holnap akkor majd teszteljük még

**Comment by andris155** [comment]
Sikerült tesztelni?

**Comment by MrZero1** [comment]
Persze, munkából telefonról mentem két kört.
Nem, nem sikerült, 6 után vagyok otthon minden nap.

**Comment by MrZero1** [comment]
Lezárom, most is simán írja ki.

**Comment by andris155** [comment]
Oké. Köszi, hogy tesztelted.

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/98404922-ba0dfb00-206b-11eb-8700-4bcfee400d7c.png)

![kép](https://user-images.githubusercontent.com/29709854/98404937-bf6b4580-206b-11eb-97c9-730a324bb67e.png)


Visszatért, megint bugos.

**Comment by andris155** [comment]
Holnap jónak kell lennie. Majd teszteljétek újra.
