### ISSUE TITLE
Béna redstone clock detector

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4128]
**Szerver**: Survi

Ha valaki épít egy órajelet és kiüti a plugin a redstoneokat, akkor a plugin szét spameli a staffok chat**jét**. Ami rosszabb hogy néha elég lassú órajelekre is bejelez, ami szerintem egyáltalán nem árt a szervernek. Jó lenne tudni, hogy mire jelez be és miért, mert szerintem ez a jelenlegi beállÍtás elég béna. Semmivel nem lehet órajelet csinálni, csak ha egy telken megy körbe a jel...

**Comment by mangoshell** [comment]
Legyen így

**Comment by andris155** [comment]
Növeltem a limiten.

**Comment by mangoshell** [comment]
Az most azt jeletni, hogy lehet gyorsabb órajel, vagy hogy lassabbat kell?
