### ISSUE TITLE
Event ládakulcs rework

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4129]
**Szerver**:

Az eventkulcs mára eléggé vesztett az értékéből, mivel már kulcsmester ládából is kaphatók, így sokkal többen így jutnak hozzá, mint hogy eventen nyerjenek.
 
Az ötletem:
Az eventkulcsok összes alternatív beszerzését eltüntetni a szerverről (Csak eventen szerezhető legyen ismét.)
Az eventláda értékét buffolni (eltüntetni pár kacat tárgyat, crossbow, totem, blockok. Maradna a szett, kulcsok, lehetne benne pár érc, sf tárgyak, lucky block, eventes eszközök, több kulcs)

Napi event fejlesztés ötletem: A napieventek nehézségétől függően kapnánk pár "eventpont" tárgyat, ami egy valutaként használható. Ezt a kulcsbeváltó npc-nél beváltható lenne Eventkulcsra. (64 eventpont -> 1 event kulcs)

**Comment by MrZero1** [comment]
Majd akkor ránézek az Eventes ládára.
Eventpont item biztos nem lesz.

**Comment by skrisz0101** [comment]
Arra van kB a token, dia
