### ISSUE TITLE
Fortuna kulcs

### ISSUE THREAD

**Issue by donthurtme123** [TheOld-Crafters/Minecraft-servers#4130]
**Szerver**:Savsziget

Felléptem a szerverre és pár perc múlva egy Player azt mondta, hogy nem működik a Fortuna láda, megnéztem, és tényleg nem. Kinyitottam a kulccsal és semmi sem történt, mintha kinyitottam volna egy üres ládát ami elvan nevezve Fortuna ládává. Mind ez savszigeten. -vace_senpai
![2020-11-02_07 55 08](https://user-images.githubusercontent.com/58477814/97839519-a0bf2480-1ce2-11eb-819d-729a0e26f350.png)

**Comment by andris155** [comment]
Javítva
