### ISSUE TITLE
mcmmo party

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4131]
Nem lehetne valahogy visszarakni a régi mcmmo party kinézetet? a mostani elég csúnya.
A chatet a /p-re rakja, szóval a /p h és társai nem működnek, mert a chatre ír inkább. a /plot home működik.

![](https://cdn.discordapp.com/attachments/485769626513571882/772837447456653342/unknown.png)

![image](https://user-images.githubusercontent.com/38157910/97883921-bf92da80-1d25-11eb-85df-a734c81ae2f7.png)

**Comment by mangoshell** [comment]
Ott vagyok!

**Comment by poma123** [comment]
A /p parancs most már a plotsquaredhez kell hogy tartozzon. A partychat kinézetét pedig a langfájlban lehet módosítani, bár sajnos a régi megszokott kinézet nem fog visszatérni, mivel a party nevet nem lehet sehogy se oda beilleszteni.

**Comment by andris155** [comment]
Nem fogom visszarakni a régit. Ha az mcMMO ezt így gondolta jónak, akkor ilyen lesz mostmár. Viszont az hex színkód támogatással vannak problémák. Szóval majd írok nekik ha lesz időm.

**Comment by poma123** [comment]
Ez a nyilas kinézet tényleg ronda, legalább egy kettőspont és zöld írás legyen megcsinálva. Megpróbálom megcsinálni a langfájlt frissítve az mcMMO/locales/ mappába téve

**Comment by andris155** [comment]
Szerintem így jobban néz ki. Szóval ez ember függő, hogy kinek mi tetszik.

**Comment by poma123** [comment]
Mindenesetre megcsináltam a kettőspontot és a zöld írást ahogy régen volt, a hex színkód támogatásra pedig akkor továbbra is várunk. Addig legalább mindenki élvezheti a majdnem konzol élményt, bár a konzolban lévő hex színekhez képest ez még jól néz ki.
![image](https://user-images.githubusercontent.com/25465545/97898236-e1955880-1d37-11eb-927b-bc5a45aa0959.png)

btw ha már konzol, a Pterodacyl nem tervezi támogatni a hex színeket?

**Comment by andris155** [comment]
Nem tud mit támogatni. :D
A konzolban mindenhol úgy jelenik. Ezt vanilla-nak, spigot-nak, vagy paper-nek kellene valahogy megoldania.

**Comment by andris155** [comment]
Windows 10-en is olyan, ha indítasz egy szervert konzolban.

**Comment by andris155** [comment]
Elég béna amúgy kettősponttal. skrisznek így tetszett jobban?

**Comment by poma123** [comment]
Mi béna rajta? Ha ennyire tetszik a nyilacska, akkor miért nincs a sima chaten is nyilacska? Szerintem eszméletlen igénytelen :D

**Comment by andris155** [comment]
Nem mindenki van party-ban. Pár olyan embert kellene megkérdezni, aki party tag.

**Comment by poma123** [comment]
Go for it.

**Comment by poma123** [comment]
Régen nem is kettőspont volt, bocsmár, rosszul emlékeztem, elmegyek akkor a búsba. Ilyen volt régen:
`&a(név) &aSzöveg`
Szerintem maradjon is ilyen.

**Comment by KingDeadZ** [comment]
Szerintem a régi jobb volt mint a nyilas.

**Comment by MrZero1** [comment]
Szerintem ez a nyilas ronda.

**Comment by andris155** [comment]
Akkor marad a kettőspont.

**Comment by poma123** [comment]
???

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/97903391-3d171480-1d3f-11eb-94c7-1a557cbc2cc0.png)

**Comment by andris155** [comment]
Beraktad a fullos a fordítást 4 sorért. Azt módosítottam, de látom már te bírod eldönteni milyen legyen. A 4 sor ott a fájlban írd át tőlem, de már külön lettek véve a party tagok és party vezetők. Akármilyen is volt valamennyire jó lenne követni a változást is és nekik maradhatna valamivel másabb, vagy a kettőspont megoldás.

**Comment by poma123** [comment]
Abba a mappába felülíráshoz lehet betenni fordítást. Ha csak azt a 4 sort hagyom benne, a többi fordítás ami nincs a fájlban angol lesz... Nem jó követni az igénytelen újítást, szerintem (és többek szerint is) sokkal igényesebb volt régen. A party vezetőknek is simán lehet ugyanaz ahogy írnak, max egy koronát tenni a nevük elé (bár mostanság senki se akar a koronához kötődni)
Egy picit örülnék ha tudnánk normális diskurzust folytatni, nem jó hogy mindig mindent meg kell magyaráznom, amit tök egyszerűen meg lehetne érteni abból amit leírok.

**Comment by andris155** [comment]
Nem lesz angol a többi. Marad magyar. Direkt leteszteltem.

**Comment by andris155** [comment]
Akkor írd át a 4 sort ahogy szeretnéd reload-old a fordítást és kész. :D

**Comment by poma123** [comment]
Akkor örülj neki, hogy tudtál róla, és annak is, hogy én nem tudtam, de azért oda tudtál szúrni nekem egyszer, hogy miért tettem be az egész fordítást. :D

**Comment by poma123** [comment]
Megcsináltam olyanra, mint régen volt, lezárom a jelentést, az mcmmo githubján már van jelentés a HEX színkódok támogatásáról.
