### ISSUE TITLE
Ládabolt - valami hiányzó valami

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4134]
**Szerver**: Szurvi, gondolom sav is

Ha eladó táblát csinálok, ezt írja ki: (a tábla attól még működik)
![2020-11-03_19 23 02](https://user-images.githubusercontent.com/29951969/98025554-2689bf80-1e0a-11eb-8913-cf37547f72c3.png)

**Comment by andris155** [comment]
Frissítettem, de lehet csak holnap tölt be.
