### ISSUE TITLE
Küldetések 

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4137]
**Szerver**: Szurvi, sav(???)

#4117 -ben fogalmazódott meg, de szerintem megérne ez egy külön jelentést, mivel telejsen más mint dia ötlete.

Hetente vagy havonta lennének változtatva ezek a küldetések, esetleg mindig ugyanaz, csak resetelődne vagy éppen a jutalom változna meg.

Lehetne akár kategóriákra bontott küldetések is. pl.: Növénytan, kalandozás, bányászat, stb
nem csak az alap kategóriák, lehetnének ötletesebbek is. pl nem tudom xd Állatgyűjtő(tojás)

ezekért a küldetésekért több fajta jutalmat/nyereményt gondoltam, nehézségtől függően
1.:  némi xp, mert miért ne
2.: némi pénz, mert miért ne.
3.: Küldetés pont, amit a hetente/havonta resiznek, és a top1/top3/topmittomén különleges nyereményben részesül. Lehetne valami csak erre a célra kialakított valami op-bb szett/eszközök, esetleg a ládák warpon egy láda, amiben csak jó/új cuccok vannak. pl 8-as enchantos soulbound szettdarab, vagy valami spawner, esetleg old cuccok, ocd, vagy mittomén.

Küldetés pont top10-et meg lehetne nézni ugyanúgy mint az eventpontot, hogy látni lehessen ki hogy áll.

lehetne erre egy warp, amiben ott egy falusi a küldetésekkel + leírással, a nyereményekkel, stb.
Esetleg minden küldetés fajtára egy falusi (nether falusi, bánya falusi, mittomén)

**Comment by KingDeadZ** [comment]
Szerintem lehetne napi, amiket random ad be egy fix táblázatból hogy mik lehetnek, heti, aminél szintén ez van meg talán max 3-4 hónaponta változó küldi, amik mindíg valamilyen szinten egyedibbek

**Comment by MrZero1** [comment]
Én azt nem tudom, hogy van e erre egyáltalán kapacitás, plugin? 
Kivitelezhető e?
Meg mennyire illik bele a szerver arculatába ez a küldetéses vonal? Egy teljesen új szervernél persze, oké, de így, behozni valamit, nem tudom.

**Comment by andris155** [comment]
Biztos meglehetne oldani, de szerintem ez nem egy Slimefun szerverre való dolog, vagy már én se tudom milyen szerver mert már annyi dolgot raktunk be. Szerintem lehetne olyan fejlesztést is nyitni, hogy mi kerüljön ki, és majd utána esetleg valami más irányba elmenni a fejlesztésekkel. De a küldetésrendszer az pedig inkább RPG irány. RPG szerver irányba nem igazán szeretnék elmenni. Van már Magyarországon egy elég jó RPG szerver amit nagyon nehéz lenne felülmúlni.

**Comment by skrisz0101** [comment]
nem kell túlgondolni. Nem RPG lenne. 
Gyűjtögetős küldik, amikért cserébe kapunk ezt-azt, valami beváltható itemet +a hét/hó végén a legjobb ember/emberek kapnak valami extra jutalmat. Talán így kicsit jobban fel lehet pörgetni a szerót. 
Amúgy meg szerintem a szeró arculata a ,,minden is"

történet se lenne, se semmi. nincs köze az RPG-hez.

**Comment by andris155** [comment]
A minden isből szelektálni kell és lesz is mert így tényleg nincs már a világon se olyan CPU ami elég lenne hozzá. Így egyelőre nem adnám hozzá még a küldetés rendszert is.
