### ISSUE TITLE
MineMarket hiba (?)

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4138]
Elvileg 3 napja le kellett volna járnia a rangomnak, de nem vette el. Nem azért, maradhat, csak gondoltam jelentem.

![kép](https://user-images.githubusercontent.com/16057404/98362573-c4a99f80-202d-11eb-8f97-4200705bbf70.png)

**Comment by mangoshell** [comment]
Rajta vagyok a képen!

**Comment by andris155** [comment]
Én biztosan nem 60 FPS-re raknám a limitet a helyedben a játékban. A képen is be is van esve 60 alá és akkor laggol a játék. Szerintem a monitor Hz*2-re érdemes rakni az FPS limitet.

**Comment by andris155** [comment]
4 nap múlva jár le a rangod. Mivel volt egy nap is kb. ameddig nem ment a szerver szerintem még korrekt is, hogy legalább cserébe tovább tart rangod.
