### ISSUE TITLE
szerverválasztó - hiányzó ráksetudjamilyen szöveg

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4139]
**Szerver**: Mielőtt belépünk a loginba

Ha rávisszük az egeret a tocra, ahol mutatja a játékosszámot, nem ír ki semilyen szöveget se.
Eddig volt.

**Comment by poma123** [comment]
Andris szerint az 1.16 nem támogatja, ezért került ki. Én láttam más szervereket hogy használják, szóval nem értem, hogy akkor most mi van.

**Comment by andris155** [comment]
Szerintem felesleges. Aki már belép a szerver listába úgyis fel fog menni a szerverre. Nem pedig azt nézegeti csak.

**Comment by skrisz0101** [comment]
Jobb mint a semmi, szerintem.
