### ISSUE TITLE
PvE minigame javaslat

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4140]
**Szerver**: Survival

Valamelyik Minigame (vagy akár plusz egy, mindegy) bekerülhetne a RabbitsVSPenguins minigame. Tök jó kis csapatjáték, menő fegyverekkel. :D 

https://www.spigotmc.org/resources/rabbitsvspenguins-pve-team-minigame-1-8-1-16.65277/

**Comment by andris155** [comment]
Egy halom minigame van, nem értem miért pont erre esett a választás?

**Comment by MrZero1** [comment]
Nézegettem és megtetszett. Ennyi 😅🥲

**Comment by KingDeadZ** [comment]
Megnéztem a trailerjét, a mostani mobaréna helyére mehetne szerintem, ezerszer jobb

**Comment by andris155** [comment]
Rakjam be a szerverre aztán majd beállítjátok?

**Comment by KingDeadZ** [comment]
szivesen segítek a beállításában ha van rá lehetőség

**Comment by andris155** [comment]
De most a lájk erre a kérdésre milyen választ takar? xd

**Comment by KingDeadZ** [comment]
Szerintem azt, hogy igen xD

**Comment by MrZero1** [comment]
Igen

**Comment by andris155** [comment]
Beraktam a szerverre.

**Comment by MrZero1** [comment]
Majd munka után megnézem akkor.

**Comment by andris155** [comment]
Működik? Vagy mi a helyzet? A konfigot szívesen elküldöm ha kell.

**Comment by MrZero1** [comment]
Azt megköszönöm ha elküldöd 😄

**Comment by andris155** [comment]
Elküldtem.

**Comment by MrZero1** [comment]
Fordítást valaki bevállalja?

**Comment by andris155** [comment]
Mivel bekerült ezt lezárom. A konfigot még biztosan módosítjuk meg lehet le is lesz fordítva.
