### ISSUE TITLE
Ancient altar bug

### ISSUE THREAD

**Issue by Gabello14** [TheOld-Crafters/Minecraft-servers#4141]
Nem lehet Essence Of Afterlifeot craftolni

Survival

**Comment by KingDeadZ** [comment]
Én egy jó 4-5órája bírtam craftolni, kb 20at craftoltam belőle. Helyes sorrendbe raktad be az itemeket?

**Comment by KingDeadZ** [comment]
Találtam az egyik ládámban "régi" necrotic skullt, ami még wither skeleton fej, 2nbtvel amit elfogad a recept, és amit birsz mostmár craftolni az player head 4 nbtvel

Kéne rá egy beváltó szerintem, a 7. ec slotomba raktam be mind a kettőből, a baloldali a régi, a jobboldali az új.

**Comment by Gabello14** [comment]
igen helyes sorrendbe raktam

lehet az a baj majd kipróbálom

**Comment by andris155** [comment]
Nem sikerült reprodukálnom a hibát. Nekem működik a craftolása.

**Comment by KingDeadZ** [comment]
> Nem sikerült reprodukálnom a hibát. Nekem működik a craftolása.

Gondolom régiből akarta craftolni, ugye lehetett idézni pl withert a necrotic skullból, szóval a fix átváltotta player headra a base itemet, az ecm 7es slotjában mind a kettőből van. (KingDead) A régiből nem lehet craftolni, próbáltam. Az újból pedig sikerült, tekintve hogy aznap a necrotic skullt is craftoltam, nem tudtam hogy volt a telkemen 40+ a régiből

**Comment by andris155** [comment]
A régi értelemszerűen nem fog működni, de ez nem hiba. Esetleg lehet csinálni rá beváltót.

**Comment by KingDeadZ** [comment]
Ezt írtam én is először :D

**Comment by poma123** [comment]
Kész, csináltam beváltót... köszi a jelentést
