### ISSUE TITLE
Savsziget hirdetés

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4142]
**Szerver**: Sav

Itt is lehetne a vastagítást meg a többi formázást letiltani, ami survivalon is van.

**Comment by andris155** [comment]
Ugyanaz a konfig a 2 szerveren hozzá.

**Comment by MrZero1** [comment]
A vastagítás Survin tiltva van? Hirdetésbe.

**Comment by andris155** [comment]
A konfigban le van tiltva. Az, hogy működik-e a tiltás azt nem tudom. :D

**Comment by MrZero1** [comment]
Savon nem működik a tiltás, azért nyitottam ezt a jelentést.

**Comment by andris155** [comment]
A túlélőn működik?

**Comment by MrZero1** [comment]
Ott igen, eddig legalábbis. Én nem szoktam látni azóta vastagított, aláhúzott hirdetéseket

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a hibát.
