### ISSUE TITLE
Fluffy barrels - javítva

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4143]
**Szerver**:  Teszt

Teszt szerón meglestük. tettünk 500k itemet a barrelbe, majd kiütöttük. azt írta h
,,There are more than 5000 items in this barrel! Dropping 5000 items instead!" -az kb 1,5 nagyládányi cucc, szóval nem laggoltat se játékost, se szervert.
dugattyú se üti ki

**Comment by KingDeadZ** [comment]
![image](https://user-images.githubusercontent.com/38157910/98448207-b55c4c00-212a-11eb-8fde-21c41e1e9f5b.png)

**Comment by andris155** [comment]
Nekem így is sikerült kinyírni a szervert és a klienst is. Ráadásul ezt csak a chunk fájl törlése oldja meg. Addig folyamatosan lefagy a szerver, amikor betölti a chunk-ot meg persze a kliens is.
https://www.youtube.com/watch?v=4pja5VIiPak

**Comment by poma123** [comment]
De ez már változott, ha nem látnád a képen. Csak akkor engedi újból kiütni, ha nincs a közelben kidobott item.

**Comment by andris155** [comment]
De akkor minek ez az egész, ha te is tudsz róla? Engedélyezed a savon és túlélőn majd megírod privátban nekem, és kész.

**Comment by skrisz0101** [comment]
mert a te szavad is számít

**Comment by poma123** [comment]
Te döntesz, hogy mi legyen

**Comment by poma123** [comment]
Engedélyeztem az első négy barrelt (small, medium, big, large), az utolsó kettőt hagytam letiltva.
