### ISSUE TITLE
Paintball - 3 és 4 csapatos mapok

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4144]
**Szerver**: Szurvi
 

Lehetne 3 és 4 csapatos mapokat is építeni, mert a pb-ben van olyan lehetőség is, hogy 3 vagy épp 4 csapat küzdjön egymás ellen. Szerintem még élvezhetőbb lenne :D

**Comment by poma123** [comment]
Sajnos nem lehet ezt a jelenlegi jól bevált pluginnal megvalósítani, mivel a négy színből kettő (piros és kék) a két csapatot jelenti, a zöld szín a véletlenszerű csapatot, a sárga pedig a megfigyelő (spectator) "csapatot".
