### ISSUE TITLE
Shopkeepers

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4145]
**Szerver**: Survival

A lerakott adminos shopkeepers csak south irányba néz. Akartam volna lerakni, illetve áthelyezni, de így, hogy a falat bámulják, nem tudom. 
![kép](https://user-images.githubusercontent.com/29709854/98468057-0d518c00-21d9-11eb-9486-0e6dfba6b26c.png)

**Comment by andris155** [comment]
Elvileg most működnie kell.

**Comment by MrZero1** [comment]
Kösziiii!
