### ISSUE TITLE
Sziget szint lekérési hiba

### ISSUE THREAD

**Issue by szofogado** [TheOld-Crafters/Minecraft-servers#4147]
Savsziget

Amikor megpróbálod lekérni a saját szigeted szintjét, akkor csak azt írja le, hogy mennyi idő mire leírja és egy hibaüzenetet.
![image](https://user-images.githubusercontent.com/52892955/98557498-9386d480-22a4-11eb-97d8-11e656401eca.png)

Más szigetének a szintjét le lehet kérni.

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a hibát.
