### ISSUE TITLE
mobaréna - nem nő az élet

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4148]
**Szerver**: szurvi, mobaréna

Hiába van maxon a kajacsíkunk, nem nő az életünk.

**Comment by Sanszi** [comment]
Mindig is így volt, nem tudom hiba-e. 😄

**Comment by skrisz0101** [comment]
nem volt mindig így sztem

**Comment by andris155** [comment]
Ez direkt ilyen.
