### ISSUE TITLE
Survival-ra Nagyon fontos lenne!

### ISSUE THREAD

**Issue by Goldie2000** [TheOld-Crafters/Minecraft-servers#4149]
**Survival**:

- Az a kérésem lenne, hogy a Survival szerveren a [V.I.P]-Joggal lehetne a táblára a vastag írás (&l)-el.

- Meg az a kérésem lenne, hogy a /me-ben is lehessen színessel írni mert így nem nagyon lehet elolvasni amit írnak.

**Comment by KingDeadZ** [comment]
Azt nem mondanám azért hogy fontos :D Az első részével egyetértek, a másodikkal nem, igazából azt se tudom hogy miért van /me

A 2. pontnál mások írását mondod, egyébként ez teljesen személyre szabott hogy ki szinezi, ki nem amikor rangom volt én szineztem ha /me-ztem, attól függetlenül hogy lusta voltam toggleolni a partychatot 2x

**Comment by skrisz0101** [comment]
színes írás elittől van.

**Comment by mangoshell** [comment]
King neked annyi eszed van mint egy hintalónak. A 2. ötlet nekem sem tetszik, inkább legyen megváltoztatva az alap /me színe valami jobban láthatóbbra.

**Comment by Goldie2000** [comment]
Valahogy ezzel, én is egyet értek!

mangoshell <notifications@github.com> ezt írta (időpont: 2020. nov. 10., K
15:53):

**Comment by andris155** [comment]
Ezeket nem valósítjuk meg sajnos.

**Comment by andris155** [comment]
Hozzáadtam a formázási jogot jogot + hex színezési táblán jogot a túlélőn a V.I.P. ranghoz a savon pedig az elit ranghoz.
A /me-n nem tudok módosítani.

**Comment by andris155** [comment]
Hozzáadtam a formázási jogot + a hex színezési jogot táblán a túlélőn a V.I.P. ranghoz a savon pedig az elit ranghoz.
A /me-n nem tudok módosítani.
