### ISSUE TITLE
Party - rossz rgb és skrisz, a kiválasztott

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4150]
**Szerver**: Túlélő, savsziget, OldSpace

Mindenkinek rossz mint a rangja, mit a nicke partyn bellül, de nekem valahogy kiírja rendesen. 
Úgy, mint sima chaten. tipp?

**Comment by andris155** [comment]
Kérlek küldj egy képet, hogy mi rossz.

**Comment by skrisz0101** [comment]
ok ha felmentem

**Comment by andris155** [comment]
Továbbra is várom a képet és a pontos leírást, hogy mit takar az a rossz RGB. Legközelebb alapból normálisan megadhatnád mi a probléma...

**Comment by skrisz0101** [comment]
eh, elfelejtettem a képet

**Comment by skrisz0101** [comment]
![Inked2020-11-10_16 03 26_cenzúra](https://user-images.githubusercontent.com/29951969/99056980-67689d80-259b-11eb-86f7-cf268ffb721c.jpg)

**Comment by andris155** [comment]
Nekem ezt sehogy sem sikerült reprodukálni. Mindenhogy működött a hex színezés.

**Comment by andris155** [comment]
Esetleg leírhatnád mit csináltak és hol éppen. Bár fogalmam sincs miért nem lehet jó, ha tényleg nem jó.

**Comment by skrisz0101** [comment]
amióta bejött, mindenkinek ilyen. nekem is ilyen volt, de egyszer csak megjavult xd

**Comment by andris155** [comment]
Úgy teszteltem, hogy átírtam a nevemre a party-dat a teszt szerveremen és beléptem egy teszt névvel. Nekem is és a teszt névvel is működött a színezés. Lehet kell hozzá a ki és belépés a party-ba. A tört játékban én nem bízok így azokkal a nevekkel nem tudom tesztelni, amikkel a képeken rossz.
