### ISSUE TITLE
Reaktor működési probléma

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4153]
**Szerver**: Survival

Az elmúlt órában történt az eset, mikoris feltöltöttem kb 64 _coolant cell_-el a reaktorom, majd hozzávetőleg 10 perccel később felfedezem az _energy regulator_-om felett, hogy nincs áram. Ránéztem a reaktorra és obszidiánná változott. Körül volt véve **vízzel** és **elegendő** _coolant cell_ volt benne, úgyhogy elvileg nem kellett volna így történnie. Ezt követően (mivel szerencsére volt elég nyersanyagom és pénzem) készítettem egy másikat, gondolván csak én ronthattam el valamit. Miután elkészültem vele, leraktam (ugyanúgy vízbe) és mielőtt még megnyithattam volna, hogy beüzemeljem meglepettem konstatáltam, hogy kb fél másodperc alatt (hozzáteszem hogy semmi sem volt benne) **szintén obszidiánná változott**. Sajnos videót és/vagy képet nem tudok mellékelni, mivel teljesen váratlanul ért.

Ha tényleg egy hibáról van szó, akkor - ha lehetséges - örülnék ha visszakaphatnám a nehezen megszerzett reaktorjaimat. Előre is köszi. :)

**Comment by andris155** [comment]
Szerintem ezt a hibát nem fogom tudni reprodukálni. Sajnos a Slimefun ilyen. Kellene mögé egy rendes csapat aki fejleszti és lehetne fizetős is akár. De így, hogy pár ember fejleszti, ha éppen van kedvük hozzá nem a legjobb.

**Comment by poma123** [comment]
Biztos hogy mindenhol volt körülötte víz? Mellette, alatta, fölötte?

**Comment by andris155** [comment]
Nem tudom sajnos ez a hiba mitől lehetett. Másoknak nincs probléma a reaktorral. Próbáld meg esetleg teljesen máshova megépíteni az egészet.

**Comment by Ziredus** [comment]
Igazából nekem is volt probléma a reaktoraimmal és az öket kiszolgáló egységekkel miután szervergépet cseréltetek pár nappal késöbb felmentem, 8 reaktorból 4 le volt égve. a hozzá tartozó coolant cell gyárban egy darab coolant cell se volt, holott böven +os gyártásra volt kalibrálva, tehát esélytelen h többet egyenek a reaktorok mint ami termelődik. Áram probléma se lehetett, ugyanis teljes kapacitáson müködve is 1M+ energiám van állandóra. Az se lehetett, hogy nem volt betöltve a coolant cell gyár chunkja, ugyanis a másik 4 reaktort kiszolgáló coolant cell gyáregység ugyanazon a chunkon van és tele volt a rendszer coolanttal, valamint el se volt tömödve a cargo. Egy rejtély h mi okozhatta, némi csendes mérgelődés után inkább pihentettem a játékot vagy másfél hétig, s csak utánna hoztam rendbe. :)
