### ISSUE TITLE
Javításra szorul: Adminchat

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4154]
**Szerver**: Survival

:)
![image](https://user-images.githubusercontent.com/69635280/98962053-85d08980-2506-11eb-9757-10cfd7c912cb.png)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/99101805-69ebe700-25dd-11eb-861a-8f476c4f7767.png)
:(

**Comment by MrZero1** [comment]
Köszi!

**Comment by mangoshell** [comment]
Látod!!!!! Javításra szoeult, mondtam!
