### ISSUE TITLE
Portable charger hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4155]
Fluffy Machines Portable Charger-t be lehet rakni a saját megnyitott invjébe.

![kép](https://user-images.githubusercontent.com/16057404/98966018-0b563880-250b-11eb-8da5-1419b1b317ad.png)

**Comment by skrisz0101** [comment]
200IQ örök áram

**Comment by andris155** [comment]
A jelentésnek legközelebb normális címet adjatok ami összefoglalja a hibát.

**Comment by mangoshell** [comment]
A Javításra szorul tökéletesen összefoglalja a dolgokat

**Comment by poma123** [comment]
https://github.com/TheOld-Crafters/Minecraft-servers/issues?q=is%3Aissue+Jav%C3%ADt%C3%A1sra+szorul+is%3Aclosed

**Comment by andris155** [comment]
Mivel nem tölti én ezt nem tartom nagy hibának. A fejlesztőnek megírtam remélhetőleg majd lesz rá javítás.
