### ISSUE TITLE
Savsziget cserekereskedő bug

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4156]
**Szerver**:Savsziget

Savszigeten a cserekereskedők (adminok által lerakottak és játékosok által lerakottak) nem működnek. Végignéztem mindenhol, se a vip, cserekereskedők, beváltó warpokon nem működnek. Valamint a boltomban lehelyezettek sem működnek.

**Comment by UDPSendToFailed** [comment]
Survivalon se.

**Comment by skrisz0101** [comment]
szerkeszteni lehet, csak belenézni nem :%

**Comment by andris155** [comment]
Holnap elvileg jónak kell lennie ennek.
