### ISSUE TITLE
mcmmo parancs problémák

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4157]
**Szerver**:Savsziget

 Savszigeten, ha beírom a /mctop és /mcrank parancsot akkor csak ennyit ír: AZ előző parancs még feldolgozás alatt áll. Kérlek várj. Újraindítottam a játékot is, hogy nem-e nálam van a gond, de ugyan az történt a játék újraindítása után is. Megkérdeztem más játékosokat is, nekik se megy.

**Comment by andris155** [comment]
Elvileg holnap ennek már jónak kell lennie.
