### ISSUE TITLE
[Info] tábla - twitter

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4158]
**Szerver**: Survi, Sav, Ép+

Lehetne a Twitter linkjéhez is egy [Info] tábla.

(Mint ez.)
![kép](https://user-images.githubusercontent.com/29709854/99103211-89840f00-25df-11eb-8903-7a07af09e2c8.png)

**Comment by andris155** [comment]
Kész.
