### ISSUE TITLE
Pet  parti

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4159]
**Szerver**: Survi, Sav

Nem tudom, direkt van e, meg hogy volt e jelentve, de a /pc a partit akarja előhozni, eddig meg a petet hívta elő. /petc a petet előhozza, nincs baj, csak a pc jobb volt.

**Comment by andris155** [comment]
Javítva.

**Comment by UDPSendToFailed** [comment]
Nemá, sokkal jobb volt a /pc, mint végigírni a /partychat-et 😥

**Comment by MrZero1** [comment]
> Nemá, sokkal jobb volt a /pc, mint végigírni a /partychat-et 😥

Nem lehetne egy aliast rakni a partychat-re? pl. /pchat vagy /partyc p

**Comment by andris155** [comment]
Nem akarok több alias-t. A tab gombbal nem nehéz beírni a partychat-et sem.
