### ISSUE TITLE
ChatControl tiltott szó lista hiányosság

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4160]
**Szerver**: MIndenhol

![image](https://user-images.githubusercontent.com/69635280/99143406-57b18d80-265d-11eb-9ff8-8b7a4c0ebbbf.png)

**Comment by UDPSendToFailed** [comment]
Javításra szorul.

_Mentálisan retardáltak a hagyományos gyógypedagógiai tipológia hazai értelmezése szerint azok a gyermekek, akiknél nem számottevő, sokszor inkább a kedvezőtlen szociokulturális hatásokra létrejövő, többnyire csak átmeneti és helyrehozható elmaradás állapítható meg az értelmi fejlődésben._

**Comment by andris155** [comment]
Kérlek ne ilyen címet adj legközelebb a jelentésnek.

**Comment by andris155** [comment]
Elvileg már nem tiltja le.

**Comment by mangoshell** [comment]
Mindig elrontod a játékom....
