### ISSUE TITLE
A túl ritka ghastok

### ISSUE THREAD

**Issue by Albinocska** [TheOld-Crafters/Minecraft-servers#4161]
**Szerver**:Survival

A probléma egyszerű. Túl ritkán spawnolnak a ghastok a netherben. Kb 3 napja este elindultam nyersanyagot szedni a netherben. Minimum 1,5 óráig csináltam-de valószínűleg több volt- és csak 1 ghasttal találkoztam.

**Comment by Albinocska** [comment]
Megértem azt, hogy nem szabad azt engedni, hogy az emberek a ghastokat-és egyéb mobokat- farmolják. De ez azért már tény
leg túl ritka

**Comment by Albinocska** [comment]
Arról nem is beszélve, hogy 1 ghast tear ára a redstone alloy ingot-éval vetekszik

**Comment by MrZero1** [comment]
Konkrét biomokban spawnol, nem?

**Comment by KingDeadZ** [comment]
soulsand valleyben elm nagyon gyakorinak kéne lennie, de itt amúgy sem olyan jó a spawnrate kb semmire, szóval am ink ajánlom h nether goldpanozz soulsandet

**Comment by andris155** [comment]
Módosítottam a spawn limit beállításokon. Remélhetőleg már több spawn-ol majd holnaptól.
