### ISSUE TITLE
Telekvilágban nem jók a petek

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4162]
**Szerver**:szurvi

A telekvilágban nem engedi előhívni a petemet, nem működik semmilyen pet parancs. 
Szándékos, vagy hiba, azt nem tudom, de fenn áll ez a helyzet.

**Comment by andris155** [comment]
Direkt került letiltásra, mivel a PlotSquared támogatás elavult benne.
