### ISSUE TITLE
Páncél hiba!

### ISSUE THREAD

**Issue by Goldie2000** [TheOld-Crafters/Minecraft-servers#4164]
**Survival**:

**Lenne Egy kis hiba a páncéllal!**

A Legendás Páncélt szerettem volna össze craftolni egy másikkal (Önjavításossal hogy legyen rajta az is)
És mikor össze szerettem volna craftolni egy hiba üzenetett kűldött:
_**,,Az unicode nem támogatott"**_
És vissza vettem és eltűnt az xp szintem is!
Pedig azt írta 37 xp szint! (Én 38-as voltam)

**Köszönöm a Segítséget!
By: Goldie2000**

**Comment by andris155** [comment]
Az üllőben való tiltást nem lehet máshogy megoldani. Gondolom van valami olyan karakter a nevében ami nem támogatott. Majd engedélyezem.

**Comment by andris155** [comment]
Engedélyeztem. Most próbáld meg.

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
Goldie2000 nevet nem találtam a MineMarket-en.

**Comment by skrisz0101** [comment]
skrisz01-et megtalálod.

**Comment by poma123** [comment]
skrisz01 nevet nem találtam MineMarketen.

**Comment by MrZero1** [comment]
> Goldie2000 nevet nem találtam a MineMarket-en.

Pedig van neki.
![image](https://user-images.githubusercontent.com/29709854/99514835-79c44c00-298c-11eb-8d85-662133766407.jpeg)

**Comment by andris155** [comment]
Megadtam neki.

**Comment by Goldie2000** [comment]
Köszönöm!

András Marczinkó <notifications@github.com> ezt írta (időpont: 2020. nov.
18., Sze, 14:53):
