### ISSUE TITLE
OldSpace - hibás Dimenziós Barkácsasztal

### ISSUE THREAD

**Issue by nival0926** [TheOld-Crafters/Minecraft-servers#4165]
**OldSpace**:

Elakadtam az előrelépések közt, ugyanis nem tudom használni a Dimenziós Barkácsasztalt. Minden összetevő megvan az Idézőasztalhoz, be is tudom pakolni (tehát vannak ott slotok), de hiába pakolom be őket megfelelően, semmi nem történik.
Elég furán néz ki maga a gui, csatoltam képen, szerintem ennek nem így kéne kinéznie.

![unknown](https://user-images.githubusercontent.com/74589323/99361075-d272e680-28b1-11eb-98bf-d50f9717af69.png)

**Comment by nival0926** [comment]
Szóval ha megpróbálom kirakni sem történik semmi, akárhová kattintok is.
A bal oldali zöld könyvre kattintva:
[CC] You don't have the permission.
customcrafting.inv.crafting.recipe_book

![letöltés](https://user-images.githubusercontent.com/74589323/99361544-85434480-28b2-11eb-9f85-7eedeb9fe49f.jpg)

**Comment by poma123** [comment]
Nem is mondtad hogy itt is jelentetted... rég javítva lett, a recept közepén valamiért Idézőasztal volt beállítva a sima enchant asztal helyett.
