### ISSUE TITLE
Javításra szorul!

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4166]
**Szerver**: Survival

Ez ideje rendszertelenül despawnolnak a falusijaim. Elvileg van egy plugin ami kordában tartja az egy chunkon lévő mobok számát, de ebben az esetben nincs arról szó, hogy olyan sok falusi lenne azokon a chunkokon.

Többen írták a játékon belül, hogy ugyan ezt tapasztalják. Ha látjátok ezt az issue-t kommenteljetek kérlek.

Több falusi tojást buktam már a bugnak köszönhetően, úgyhogy a többiek nevében is, kérjük hogy minnél hamarabb javítsátok. Előre is köszi c:

**Comment by andris155** [comment]
Növeltem a limiten.

**Comment by MrZero1** [comment]
Mennyi tojást veszítettél el?

**Comment by Laci444** [comment]
5-öt. Azt leírod legyszi, hogy mennyire növelted a limitet? A jövőben úgy tevezem majd a farmomat, hogy az alatt maradjon. Köszi

**Comment by andris155** [comment]
15
