### ISSUE TITLE
Spam védelem

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4167]
Kellene valami spam védelem az ilyen szellemileg visszamaradottak ellen, hogy ne tudják ugyanazt az üzenetet többször elküldeni egymás után.

![image](https://user-images.githubusercontent.com/16057404/99416843-8fd4fc80-28f9-11eb-9262-9146fe5f46f9.png)

**Comment by Ziredus** [comment]
Támogatom, ha nem fogyaszt az amugyis véges erőforrásokból.

**Comment by andris155** [comment]
Nem fogyaszt mert teljesen külön folyamat elvileg a chat. Még akkor is működik ha kifagy az egész szerver.

**Comment by andris155** [comment]
Majd kitalálok valami jó megoldást.

**Comment by andris155** [comment]
Fejlesztettem rajta. A képhez hasonló flood-ot így már tiltja a plugin.
