### ISSUE TITLE
Javításra szoruló android hiba

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4168]
**Szerver**: Survival, Sav
 

Az összes android el tud bugolni, de csak egy speciális esetben. Hogyha épp az android mozgása közben (vagyis akkor, amikor a következő blokkra kerül letételre az android blokkja) folyik víz arra a következő blokkra ahova az android megy (kerül lerakásra), elbugol. Mindenfajta android elbugol így, poma tudta reprodukálni, viszont videóra nem sikerült venni.

**Comment by poma123** [comment]
Légyszi olvasd el az issue template-ben lévő komment szöveget, ami úgy szól, hogy "Ez alá a sor alá írd le részletesen a hibát. Térj ki arra is, hogyan tudjuk azt reprodukálni. Ha készítettél róla videót vagy képet, csatold bátran."

Ezekre szükség lenne a reprodukáláshoz:
- Melyik android fajta bugol el?
- Kép kellene arról milyen körülmények között történik ez meg.

**Comment by mangoshell** [comment]
Milyen körülmények között vajon. Ha víz megy rá bármilyen irányból kiütődik és CS-CoreLib feje lesz belőle.

**Comment by poma123** [comment]
Köszi a releváns választ, erre lettem volna kíváncsi, hogy a víz milyen módon folyik rá.

**Comment by andris155** [comment]
Ezt a hibát már jelentették a Slimefun-nak, és egyelőre nincs rá javítás.

**Comment by andris155** [comment]
https://github.com/Slimefun/Slimefun4/issues/2496
