### ISSUE TITLE
Javításra szorul - Ingame MineMarket GUI

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4169]
/bolt parancsnál 20 Shopkeeper tojás van, de a leírásban és a MineMarket-en is csak 10.

![image](https://user-images.githubusercontent.com/16057404/99548428-efdea800-29b8-11eb-994e-1758b4bd8663.png)
![image](https://user-images.githubusercontent.com/16057404/99548453-f40ac580-29b8-11eb-8031-d7bf0b0207aa.png)
![image](https://user-images.githubusercontent.com/16057404/99548505-0258e180-29b9-11eb-990b-af359ef8b921.png)

**Comment by poma123** [comment]
Javításra szorult, és javítottam!
