### ISSUE TITLE
Egyszerű /back bug.

### ISSUE THREAD

**Issue by Albinocska** [TheOld-Crafters/Minecraft-servers#4170]
**Szerver**:Szurvival

Egy konkrét példát mondok. Elteleprtáltam bazsaaa pwarpjába, /back-eltem és a bányámba dobot vissza, ahonnan  kb már 10 perce feljöttem. Innen fel home-oltam a házam elé, vissza bazsaaa pwarp-jára, de még mindig a bányámba dobott(ahova menesleg semmi külön home-m nincs).

**Comment by KingDeadZ** [comment]
Én úgy tudom, hogy csak essentialsos tp parancsokkal kompatibilis a back pl: back,warp,home,tpa,tp ha más pluginból használsz valamilyen teleportot arra értelemszerűen nem fog hatással lenni a back

**Comment by Albinocska** [comment]
igen, de haza home-oltam utána a házam elé, szóval oda kellett volna raknia

**Comment by andris155** [comment]
Csak az EssentialsX teleport parancsokat támogatja a /back parancs.
https://essinfo.xeya.me/commands.html
