### ISSUE TITLE
Barrel

### ISSUE THREAD

**Issue by IcyAlex** [TheOld-Crafters/Minecraft-servers#4171]
Surv-(sav?)

Fluffy Barrels nincs lefordítva.

![Barrels](https://user-images.githubusercontent.com/32267424/99575880-8ae77a00-29d9-11eb-8de8-d73fe03effa3.png)

**Comment by andris155** [comment]
Ez a forráskódba van beleírva. Sajnos ezt nem tudjuk lefordítani.
