### ISSUE TITLE
Javításra szorul - Ezt nem rakhatod le

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4172]
![image](https://user-images.githubusercontent.com/16057404/99666901-e4988480-2a6b-11eb-94f4-be7e36d50eb0.png)

**Comment by andris155** [comment]
A tiltás része ugyanúgy működik. Az üzenet érdekes az biztos. Az FAWE miatt lett ilyen. Megírtam a fejlesztőknek ezt, ha hiba akkor majd biztosan javítják.
