### ISSUE TITLE
ChestShop - összes item eladása

### ISSUE THREAD

**Issue by Albinocska** [TheOld-Crafters/Minecraft-servers#4173]
**Szerver**:Szurvival

Ennek egy értelme van: időspórolás. Arról van szó, hogy az eladó táblára shift+bal klikkelve eladja az összes olyan itemet az inventorydból.

**Comment by KingDeadZ** [comment]
Van rá funkció, csak az azzal jár, hogyha vásárolni akarsz bármit shift jobbkattal akkor annyit vesz, amennyi hely van nálad, így nem került be.

**Comment by MrZero1** [comment]
Ami engem nem zavarna. :D Ki lenne írva, aztán aki kicsit is olyan, elolvassa.

**Comment by andris155** [comment]
<img width="453" alt="Capture" src="https://user-images.githubusercontent.com/8324198/99709470-84bbd100-2a9f-11eb-8e14-a09ddf1a28cd.PNG">
Ez az egy beállítási lehetőség van ezzel kapcsolatban ,,extra funkcióként". Engedélyezzem?

**Comment by Albinocska** [comment]
Igen.

**Comment by KingDeadZ** [comment]
Facebook vagy discordon lévő szavazásként meglehetne tartani, mert azért szerintem számít

**Comment by andris155** [comment]
Nincs értelme ezeknek a szavazásoknak. A Facebook-on régi tagok vannak. Discord-on meg sokan vannak de nem sokan nézik folyamatosan.

**Comment by skrisz0101** [comment]
100% hogy a vételnél is vesz mindent ami az invbe fér vagy csak feltételezés

**Comment by poma123** [comment]
> 100% hogy a vételnél is vesz mindent ami az invbe fér vagy csak feltételezés
Sk kérlek... "If true, people will be able to sell/buy everything available of the same type."
Röviden: igen

**Comment by UDPSendToFailed** [comment]
+1 arra, hogy legyen engedélyezve

**Comment by TryHardDo** [comment]
+1 innen is! (tf2levi)

**Comment by Albinocska** [comment]
> ```yaml
> # If true, people will be able to sell/buy everything available of the same type.
> SHIFT_SELLS_EVERYTHING: false
> ```
> 
> Ez az egy beállítási lehetőség van ezzel kapcsolatban ,,extra funkcióként". Engedélyezzem?

Engedélyezd. Nem ártana semmit, és csak felgyorsítaná a nagy tömegben történő eladást

**Comment by poma123** [comment]
Ezzel át lehet állítani, hogy csak eladásnál lehessen shifttel többet, vételnél nem.
```yaml
# What can you do by clicking shift with SHIFT_SELLS_IN_STACKS turned on? (ALL/BUY/SELL)
SHIFT_ALLOWS: SELL
```

Habár a komment csak a SHIFT_SELLS_IN_STACKS-t említi, a SHIFT_SELLS_EVERYTHING-re is érvényes.

**Comment by KingDeadZ** [comment]
Akkor bekerül?

**Comment by andris155** [comment]
Az eladáshoz engedélyezésre került.

**Comment by KingDeadZ** [comment]
Nem birok sneakelve vásárolni 1stacket, és nem ad el mindent egyszerre sneakelve.

**Comment by poma123** [comment]
Nem fogsz tudni már stackelve vásárolni, csak eladni mindent, és szerintem csak ma töltött be a változtatás.

**Comment by andris155** [comment]
Nem ma töltött be. Már tegnap is jó volt. A vásárlásra nem merem engedélyezni, hogy annyit vegyen amennyit az inv-be fér. De szerintem írok a fejlesztőnek, hogy lehessen variálni, hogy a vásárlásnál 64-et vegyen csak.
