### ISSUE TITLE
Javításra szorul: partychat és a sorszámok

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4174]
**Szerver**: Survival

Ha bármilyen betű/szám után space nélkül írunk valamit az ilyen lesz:
![image](https://user-images.githubusercontent.com/69635280/99694088-5254a880-2a8c-11eb-9fb9-9db1afa8b587.png)
![image](https://user-images.githubusercontent.com/69635280/99694322-96e04400-2a8c-11eb-8a1d-abf67e494b1f.png)
![image](https://user-images.githubusercontent.com/69635280/99694366-a2cc0600-2a8c-11eb-9885-504524e90c86.png)

**Comment by andris155** [comment]
Mivel linknek veszi. Ne írd space nélkül az a megoldás.
