### ISSUE TITLE
Nyulak vs Pingvinek

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4175]
**Szerver**: Survival

Van valami furcsaság a játékkal. 2 aréna van beállítva, ha mindkettőben játszanak, és elindulnak az arénák, akkor egy idő után despawnolnak a zombik, mind2 arénában. Az idő csak megy, de a zombik nem jönnek.
Ha csak egy aréna van és ott játszanak akkor nincs baj

**Comment by andris155** [comment]
Ezt fogalmam sincs hogy lehetne reprodukálni 2 teszt névvel. Több névre nincs eredetim sajnos.

**Comment by MrZero1** [comment]
Játékosokat hozok én.

**Comment by andris155** [comment]
Egy videó erről nagyon jó lenne.

**Comment by andris155** [comment]
Nem írt rá semmit a fejlesztő, pedig látta az üzenetet. Nem tudok ezzel mit kezdeni sajnos. Lehet javítja, de azt majd úgyis megírom neked Facebook-on. Persze csak ha visszakerül a plugin egyáltalán.
