### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Albinocska** [TheOld-Crafters/Minecraft-servers#4176]
**Szerver**:Survival

Ezt adta ki, amikor leraktam a lávát(valahogy, mert elvileg lerakni sem lehet)
![Képernyőkép – 2020-11-19 21-03-48](https://user-images.githubusercontent.com/67507919/99718533-4d532180-2aab-11eb-8663-429705beaa33.png)

**Comment by andris155** [comment]
Jelentették már a hibát, szerintem majd más fogja ezt akkor kezelni.

**Comment by andris155** [comment]
Komoly op. rendszer. Nem sokan értenek manapság ennyire a gépekhez.
