### ISSUE TITLE
Savsziget Könnyebb Érc Eladás

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4177]
**Szerver**:Savsziget

Savszigeten a /shop parancsnál az érceket sajnos nem lehet blokkokként eladni. Ez lazuritnál és redstonenál kifejezetten zavaró, mivel az androidok kb. Óránként megtelítenek egy inventoryt lazurit és redstone blokkokkal, (automatikusan blokkokká craftolja őket az autocrafter) és hát lebontogatni őket eladáshoz elég unalmas. Sokat segítene, ha ez bekerülne.

**Comment by szofogado** [comment]
Támogatom az ötletet.
(bár én annak is örülnék, ha kvarcot is el lehetne adni a shopban)

**Comment by andris155** [comment]
Beraktam az érc blokkok kategóriát a boltba.
