### ISSUE TITLE
Surviva levédésblokk küldése

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4179]
**Szerver**: Survival

/transferclaimblock parancs nem működik. Ezzel lehet blokkot küldeni másiknak (pl. most új névre váltott valaki, átakarta küldeni magának)

**Comment by poma123** [comment]
Ezt én fejlesztettem egy külön pluginként, ami végül/egyelőre kikerült, mivel elvileg volt valami hiba vele, amibe nem volt időm (őszintén kedvem sem) beleásni magam, mivel órákat kellene a logot nézni kb.

**Comment by MrZero1** [comment]
Akkor a táblát érdemes lett volna leütni a warpról.

**Comment by poma123** [comment]
Na ezt elfelejtettem, sajnálom. Én is emberből vagyok, hibázhatok és sajnos hibázok is
