### ISSUE TITLE
Javításra szorul - Slimefun Flask of Knowledge

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4180]
Egy egész szintet levesz jobbklikkre, de alig ad vissza pár XP-t. 
400-as XP szintről indultam, ha az összeset kivenném Flask of Knowledge-be, majd eldobálnám, lenne max 10-20-as szintem belőle.

Itt konkrétan elvett majdnem 3400 XP-t, és eldobás után visszaadott 8-at.

![image](https://user-images.githubusercontent.com/16057404/99876669-8816a000-2bf8-11eb-8d68-5de9c5d63f4b.png)
![image](https://user-images.githubusercontent.com/16057404/99876677-8fd64480-2bf8-11eb-8e76-da99fffbe967.png)

**Comment by KingDeadZ** [comment]
elég erősen abuseolható lenne, ha egy egész szintet adna vissza, főleg úgy hogy az xpcollector is flask of knowledgeot ad vissza

**Comment by UDPSendToFailed** [comment]
Annyit adjon vissza, amennyit elvesz, ez lenne a normális.

**Comment by andris155** [comment]
Ez nem hiba, mivel működik és így van megírva a forráskódban. Egy szintet vesz le. Visszaadni pedig annyit ad amennyit vanilla tapasztalat tároló üveg ad.
Fejlesztési ötleteket a Slimefun-hoz a Discord szerverén tudtok írni: https://discord.com/invite/slimefun
