### ISSUE TITLE
Nyulak VS Pingvinek - végtelen élet

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4181]
Elküldtem andrisnak privátban discordon, és pomának mutattam.

**Comment by andris155** [comment]
Kikerült a plugin egyelőre. Az max életeket visszaállítottam...

**Comment by andris155** [comment]
5080 OCD

**Comment by KingDeadZ** [comment]
Van a pluginról bármi hír?

**Comment by andris155** [comment]
Egyelőre nincs. Nem igazán tudtuk megoldani saját megoldással úgy, hogy 100%-san ne tudjon senki se valahogy Old tárgyakkal belépni és mivel ezzel olyan hiba keletkezik amit nem igazán lehet észre venni így nem kockáztattunk. De egyébként ha ennyire sem képes a fejlesztő, hogy javítsa ezt akkor amúgy sem hiszem, hogy hosszú ideig bent lett volna. Rengeteg hiba van még benne szerintem, mivel max 3 szerver használhatja talán. A jövőben én nem fogok többet ilyen kevés szerver által pluginokat berakni, mert csak a gond van belőle utána.
Ha lesz rá javítás visszakerül persze, de nem hiszem hogy sokáig bent lesz, ha nem frissíti a fejlesztő meg nem javítja benne a többi hibát.

**Comment by andris155** [comment]
Visszakerült a plugin.
