### ISSUE TITLE
Nyulak VS Pingvinek ötlet

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4182]
Lehetne drágítani, vagy esetleg kivenni azt a szuper boostos dolgot, mivel csak 1k érmébe kerül, és minden egyes zombira ami az ellenségnél van ad erő2t, speed2t, így ha megveszed, akkor instant megnyered a játékot.

**Comment by skrisz0101** [comment]
lehetne az is h lássák egymást a csapatok. pl a mostani kőfal helyére üvegfal.

**Comment by IcyAlex** [comment]
Én egy olyat adnék hogy mondjuk 10k-ért visszavásárolni az egyik csapattársadat.

**Comment by KingDeadZ** [comment]
addig nem megy a játék, hogy meglegyen 10kd, max ha a játékidőt növelve lenne

**Comment by andris155** [comment]
Egyelőre használhatatlan állapotban van. Majd ha még egyáltalán visszakerül, akkor lehet majd gondolkodni az újításokon.

**Comment by skrisz0101** [comment]
amúgy nem lenne jó ha lenne egy feltétel h üres invvel lehet csatlakozni?

**Comment by andris155** [comment]
Zárt forráskódú plugin, amit a fejlesztője nem nagyon fejleszt. De egyébként az effektes plusz életet is a max élethez írja szerintem. Szóval nem lenne jó.

**Comment by skrisz0101** [comment]
Szerintem nem
Old szett nélkül nem kaptunk +életet

**Comment by poma123** [comment]
Nem kell a pluginon változtatni, hogyha nincsen semmilyen külön belépési parancsa, akkor mivel csak az eventguiból lehet odajutni, abban kell beállítani az üres invet, és az enderládákat kiütni a teleport helyen.

Ezzel megoldódna a gond, feltéve ha a játék után nem marad ott a játék közben beállított max health érték.

**Comment by andris155** [comment]
Kicsit várok a megoldásra. Aztán ha nem lesz akkor majd írok @poma123 .

**Comment by Sanszi** [comment]
Én üres inventoryval mentem oda mindig, és sose maradt meg a játékban vásárolt + maximális élet. szerintem műküdne.
