### ISSUE TITLE
Javításra szoruló rohadékok

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4184]
**Szerver**: Survival

Survivalon az ún. rohadékok (mobok) nagyon gyakran spawnolnak. Pls legyen kisebb a spawnrate.

**Comment by KingDeadZ** [comment]
specifikus mob pls??? én ma 20as tpsnél enderman farmoltam kb 5percet, de alig-alig estek

**Comment by mangoshell** [comment]
Trollkodd szét megint a jelentésem. Zombi, pók, csonti, kb ezek

**Comment by KingDeadZ** [comment]
spawnerből?

**Comment by skrisz0101** [comment]
eddig mindig rohadtkevés volt, nem tudom elképzelni hogy túl sok xd

**Comment by MrZero1** [comment]
Lett valami állítva a szellemek miatt, azóta elvileg mindenből sok spawnol.

**Comment by andris155** [comment]
Eddig szinte nem is volt. Akkor az volt a baj. Most meg az a baj, hogy van.
A vanilla-hoz képest a mostani beállítás közelebb áll, de még így kevesebb jóval. Szerintem ez így rendben kell, hogy legyen.

**Comment by mangoshell** [comment]
Ez jo flegma volt
