### ISSUE TITLE
A tábla addolós bug

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4185]
**Szerver**:Szurvival, de úgy gondolom savsziget is (ott nem próbáltam) 

Nos, ha kreatívban egy cenzúrázott szót írsz táblára, akkor a tábla úgymond ledobja a blockról magát, azaz kidroppolja item formájában, melyet survivalban fel lehet venni.

**Comment by KingDeadZ** [comment]
ez már régóta így van, kb 2 éve

**Comment by andris155** [comment]
Már sokszor lett jelentve. Mivel a tábla nem túl értékes nem probléma szerintem. Az se lenne jobb, ha a tábla utána elvesznek szerintem.

**Comment by andris155** [comment]
Megcsináltam, hogy ne dobja ki a táblát.
