### ISSUE TITLE
Spam védelem ötlet

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4188]
**Szerver**: Szurvi, sav

Partychat nem élvezhetne ezalól kivételt?
Pl ha véletlen partyban köszönök majd újra kiírnám globálba, nem engedi.

**Comment by andris155** [comment]
Hogy szoktál pontosan köszönni?

**Comment by mangoshell** [comment]
„Helosztok” „Helo”

**Comment by skrisz0101** [comment]
de nem csak a köszönés miatt kéne

**Comment by mangoshell** [comment]
Ha véletlen valamit partyba írok és chatre szeretném, akkor át kell fogalmazni hogy engedje :( meg az xd lehetne kivétel a spam cucc alól, mert azt sokszor írjuk, és van olyan is hogy sokáig nem engedi újra kiírni

**Comment by andris155** [comment]
Ezzel nem tudok mit kezdeni. Neked kell figyelni, hogy ne rossz helyre írd.

**Comment by skrisz0101** [comment]
pedig nagyon irritáló. Segítenék valakinek, írok 2 sort véletlen partyba és akkor már eltelik 1 perc mire újraírom (átfogalmazva)

**Comment by skrisz0101** [comment]
esetleg lehetne olyan is hogy 2x le lehetne írni ugyanazt, ha nincs más megoldás

**Comment by andris155** [comment]
Mint írtam. Neked kell figyelni arra, hogy hova írsz. Ez még mindig nem hiba így.

**Comment by skrisz0101** [comment]
nem hibaként van megnyitva a jelentés

**Comment by andris155** [comment]
Kikapcsoltam inkább ezt a megoldást. Sajnos automatikus megoldás egyelőre akkor nincs flood-ra.

**Comment by skrisz0101** [comment]
De az nem lenne elég ha engedné 2x ugyanazt leírni, de 3x már nem?

**Comment by andris155** [comment]
Nincs ilyen lehetőség benne. Talán majd az új Red verzióban lesz.
