### ISSUE TITLE
EventRendszer fejlesztés

### ISSUE THREAD

**Issue by poma123** [TheOld-Crafters/Minecraft-servers#4189]
**Szerver**: Survival, Savsziget

2019 februárban került be, jó sok hibajavítást kapott, de még mindig nem tökéletes.
A kód olvashatósága a lehetetlennek mondható, és nagyon sok logikai bukfenc is van benne.
Illetve ugyebár a gyakran említett teljesítménybeli problémák, itt is vannak bőven.

Tervek, célok?

Szeretném normálisan megcsinálni, kisepregetni belőle a koszos részeket, tisztává varázsolni.
Emellett létrehozni egy jobb testreszabhatóságot, amivel "addon" plugint lennénk képesek hozzá írni, ahelyett, hogy a fő plugint változtatom hacky módokon.
Ezzel a módszerrel nagyon sok egyedi minigame/event születhetne, akár PVP, akár parkour vagy valami egészen más.

Illetve még lenne mód a staffoknak rgb-s nyerteshirdetés szöveget beállítani, amire jelenleg nincs mód.

- [x] HEX színek támogatása az eventnyertes üzenetekben
- [x] Külső pluginnal egyedi event létrehozás
- [x] Egyedi eventek regisztrálása (egyedi WinnerType, illetve scoreboard az esetleges pontok jelöléséhez)
- [x] Eventenként induláskor és leállításkor lefutó egyedi dolgok
- [x] Eventbeállítás GUI teljes átdolgozása
- [x] Szortírozás, blokk letétel, belső visszaszámláló és leírás betétele az ingame beállítóba

**Comment by MrZero1** [comment]
Nem tudom, ez mennyire oldható meg, de többen is mondták, hogy a hosszabb eventeknél lehetne checkpoint.

**Comment by poma123** [comment]
Igen, én is gondoltam pár parkour eventhez checkpointot, nagyon jó lenne.

**Comment by MrZero1** [comment]
#4200 jelentés idekapcsolható. Ha lesz frissített/új eventrendszer, majd savra is bekerül több új event.

**Comment by poma123** [comment]
Kétféle új auto event fajta kerülhet be ezzel a frissítéssel, egyik a bridge a másik pedig a checkpointos parkour féleség. A bridge-re már map is van, a parkour cuccot pedig pár eventet kimásolva raktam össze survin, majd megmutatom.

Auto eventből van savon bőven, a napi és a manuális eventeket pedig csak ugyanúgy kell beállítani mint eddig. Ha van rá igény, tarthatok valamikor egy gyorstalpalót, hogy minden admin be tudjon állítani eventeket, akár auto eventeket is az új rendszerrel.

**Comment by MrZero1** [comment]
Savszigeten inkább majd az auto eventek lennének, a meglévő eventeket majd megnézem, mit lehetne átrakni checkpointos auto eventre.
A bridge az event vagy minigame lett? 😃 Mutatták Hypixelen, jó kis cucc.

**Comment by poma123** [comment]
Auto event, bár minigame közé sorolható. Még nem került ki táblaként
