### ISSUE TITLE
mcMMO - Fadöntő képesség hiba

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4190]
Survival, valószínűleg savon is

Ha az mcmmoban a fadöntő képességet használod a fákon, akkor a fa lombjainak nagyjából 90-95%a eltűnik úgy, hogy nem droppol semmit.

Ha a fadöntés nélkül vágok ki egy fenyőfát, akkor dob ilyen 14-15 levelet, viszont ha a fadöntéssel akkor a kevés lomb miatt 1-2t dob maximum.

**Comment by KingDeadZ** [comment]
Kivágtam vele egy csomó dark oak fát is, konkrétan az összes levelet megsemmisítette, és nem adott 1db saplinget sem.

**Comment by andris155** [comment]
Nekem egy csomó dolgot ad, szóval az nem hiba. Inkább az hiba, hogy silk touch baltát nem támogat ez.

**Comment by andris155** [comment]
Megírtam az mcMMO-nak. Volt már hasonló jelentés a magas gombákkal kapcsolatban. Valamikor lehet megvalósítják, de több mint 200+ probléma vár még megoldásra. Szóval nem hiszem, hogy ennek a megoldása nekik most a legfontosabb sajnos.

**Comment by andris155** [comment]
https://github.com/mcMMO-Dev/mcMMO/issues/4303
https://github.com/mcMMO-Dev/mcMMO/issues/4344

**Comment by KingDeadZ** [comment]
Fortune Xes baltával is próbáltam, de azzal is ugyanúgy szimplán eltüntette a leveleket

**Comment by andris155** [comment]
Fortune X-es baltával is dob nekem extra dolgokat. De azt nem tudom, hogy többet dob-e mintha simával ütném ki.
