### ISSUE TITLE
Slimefun engedélyezése eventvilágban

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4191]
**Szerver**: Szurvi, (sav)

Nem lehet flat világba kb sehova se menni cuccal, javítsatok ha tévedek.
Van egy csomó cucc amivel tök jó eventeket lehetne csinálni. ilyen a warp pad (portál), multi tool, storm staff, stb.
Lehetne a hunger games arénákban is sf cucc, mint a storm staff, 1v1 arénákban, meg még mittomén hol

**Comment by poma123** [comment]
Amiatt lett letiltva, hogy ne lehessen az eventeken használni ezeket a tárgyakat. Bár hogyha nem tudnak odamenni, csak üres invvel, akkor ebből sincs probléma.

**Comment by MrZero1** [comment]
Eventekre nem, de minigame-ekre igen (azt hiszem)

**Comment by poma123** [comment]
Az eventeken az inventory lementésre kerül mindenhol nem? Kivéve paintballon, ahova csak üres invvel lehet menni

**Comment by MrZero1** [comment]
Aha. Ha nincs kitanulva a játékosnak, akkor nem is tudná használni eventen/minigame közben, nem?

**Comment by KingDeadZ** [comment]
szerintem a páncélok kivételével egyiket se lehetne használni, ha nincs kitanulva

**Comment by poma123** [comment]
Igen, ha nincs kitanulva nem megy alapból

**Comment by skrisz0101** [comment]
Alapértelmezetten fel lehet oldani cuccot mindenki számára?

**Comment by andris155** [comment]
Szerintem ezeket oldja fel mindenki magának és tanulja meg, hogy kell ezeket használni és elkészíteni. Én ezt nagyon nem tartom jó ötletnek, hogy ezeket alapból feloldjuk. Illetve egy csomóan nem akarnak Slimefun-t használni, hanem csak rendesen játszani a játékkal. Nekik ezekről fogalmuk sem lesz, hogy micsodák vagy mire jók.

**Comment by skrisz0101** [comment]
nem nagy ördöngösség jobb kattolni pl egy bottal ami villámot csap, vagy jobb kattolni egy lasszóval ami elrepít a retekbe.
Nem gyárépítő ,,event"-ekre gondoltam
