### ISSUE TITLE
Sf táska rúna bug

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4193]
**Szerver**:Savsziget, Survival

 Ha bármilyen hátizsákra teszünk rúnákat (nem soulbound bakcpackre gondolok) pl. soulbound, fireproof majd utána befestjük, akkor a táskáról lekerülnek az eddig rátett rúnák.

**Comment by andris155** [comment]
Gyakorlatilag ha sima táskát fejlessz tovább akkor is elveszik róla. Megírtam a fejlesztőnek, de addig még nincs rá megoldás figyelni kell arra, hogy csak akkor rakd rá a fireproof és soulbound-ot, ha már kimaxoltad, vagy nem akarod tovább fejleszteni.

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
Nem találtam Tomi321 nevet a MineMarket-en.

**Comment by Tomi321** [comment]
Tomi_YT a nevem. Csak ez a név foglalt volt már.

**Comment by andris155** [comment]
Megadtam

**Comment by andris155** [comment]
A soulbound-ot elvileg már nem törli róla. A fireproof-ot nem lehet megoldani, hogy ne törölje le róla ilyenkor.
