### ISSUE TITLE
Spawnereket Savszigetre!

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4194]
**Szerver**:Savsziget

Tudom, hogy régen sokféle spawnert lehetett szerezni amiket az inventorynkba is lehetett tenni. Viszont mára szerencsésnek érezheti magát az ember, ha egyáltalán talál olyan játékost, aki hajlandó sokmillió dollárért eladni egy spawnerét. Esetleg bekerülhetnének a spawnerek minemarketbe Savszigeten is. Abban biztos vagyok, hogy sokan vennék meg, köztük én is. :)

**Comment by andris155** [comment]
Régebben volt de aztán kérésre ki lett szedve. Gondolom nem véletlen, de már a pontos indokra nem emlékszem. Erről sweetant kérdezd majd meg.

**Comment by andris155** [comment]
Ha sweetan azt mondja, hogy legyen ilyen akkor írjon majd rám mik legyenek és mennyi OCD-ért.

**Comment by MrZero1** [comment]
Minemarket-re visszakerülhetnek, de kiütni továbbra sem lehet őket.
A multiaccosok miatt került ki ámblokk. (Feljöttek kiskarakterekkel, kiütötték a szigeten, újrakezdték majd megint kiütötték a spawnereket, és így tovább. Lényegében farmolták a spawnereket. Ezért volt jobb a limitált kiütési számos megoldás.)

Ha így is legyen a Minemarkatben akkor jó, összeírom milyenek kerüljenek be.

**Comment by poma123** [comment]
> Ezért volt jobb a limitált kiütési számos megoldás
Multiaccosok ellen nem védett volna az sem, játékosonként volt limit a kiütésre

**Comment by MrZero1** [comment]
Igen, de ott legalább meg volt egy napi limit, amit a multiaccosok sem tudtak átlépni, hiába kezdték újra többször a szigeteket.
