### ISSUE TITLE
Rejtélyes cargo elállítódás

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4195]
A tegnap este lerakott cargo out-ok egy része, amik 9-es channelen voltak, visszaálltak channel 1-re, és nem kapcsolódnak a cargo connectorhoz, nem is viszik át a cuccokat, ha újra beállítom őket. 
Plusz poén, hogy véletlenszerű tárgyak jelentek meg ezekhez a cargokhoz kapcsolódó smelterykben, például egy vizesvödör, amit sehol se használok az egész telken.

![image](https://user-images.githubusercontent.com/16057404/100219623-86a9e800-2f16-11eb-9b61-d231832703a1.png)

**Comment by poma123** [comment]
Nem állítódnak el maguktól :D 
Inkább itt a probléma az, hogy a LiteXpansion-os Cargo Configuratort nem érdekli ha levédésen van a cargo, azt is át lehet vele állítani. Valaki jót érzett és szétcseszte a cargo-dat.

**Comment by skrisz0101** [comment]
ezt jó tudni

**Comment by Ziredus** [comment]
Minden cargot be kell erődíteni...

**Comment by andris155** [comment]
Erről nekem eddig senki se szólt. Lefogom majd tesztelni és megírom a fejlesztőnek. De ha tudtatok róla nem értem, hogy eddig miért nem szólt erről senki.

**Comment by skrisz0101** [comment]
én nem tudtam xd

**Comment by poma123** [comment]
> Erről nekem eddig senki se szólt. Lefogom majd tesztelni és megírom a fejlesztőnek. De ha tudtatok róla nem értem, hogy eddig miért nem szólt erről senki.

Nem tudott róla senki, tegnap lett letesztelve, hogy működik-e, és működik, ezért írtam amit írtam.

**Comment by andris155** [comment]
Le lett tiltva addig a configurator még nincs megoldás rá.

**Comment by KingDeadZ** [comment]
Tegnap a copper dust raktáram felénél az outputos cargok nem működtek. Megbírtam nyitni a guit, 1es channelen volt az összes, nem szállított onnan semmit (pedig birna) és átállítani se bírtam más channelre. Replace megoldotta

**Comment by andris155** [comment]
Megírtam a fejlesztőnek a hibát. Ha javításra kerül újra engedélyezésre kerül majd a configurator.

**Comment by TryHardDo** [comment]
Annyit hozzáfűznék hogy a cargo configuratort nem zavarja hogy le van tiltva. Ad egy üzenetet hogy tiltva van de a metódus lefut ami a cargot állítja. Annyi hogy amikor copyzol vele megyitja a cargo interface-t és a tiltó üzenet után kiírja sikeresen belőve a channel és kajakra meg is csinálja.

**Comment by andris155** [comment]
@TryHardDo Ha jól tudom te valami nagy programozó vagy. Ha esetleg értesz hozzá és tudnád javítani az nagy segítség lenne.

**Comment by andris155** [comment]
https://github.com/J3fftw1/LiteXpansion/issues/117

**Comment by KingDeadZ** [comment]
azóta már bekerült a fix ahogy néztem, de még nincs engedélyezve a cargo configurator 
esetleg lehetne engedélyezni?

**Comment by andris155** [comment]
Engedélyezve kellene lennie pedig. Biztosan nincs?

**Comment by KingDeadZ** [comment]
Megnézem újra, tegnap próbáltam asszem, akkor le volt tiltva még

**Comment by KingDeadZ** [comment]
Mostmár engedélyezve van, m1 akkor köszi xd tegnap még nem ment v tegnapelőtt

**Comment by TryHardDo** [comment]
> Mostmár engedélyezve van, m1 akkor köszi xd tegnap még nem ment v tegnapelőtt

Ezek szerint a disable is jó lett :D
