### ISSUE TITLE
Beváltó

### ISSUE THREAD

**Issue by IcyAlex** [TheOld-Crafters/Minecraft-servers#4197]
Survi

Beváltónál az SF falusival nem tudsz kereskedni.

![kép](https://user-images.githubusercontent.com/32267424/100371481-1bd8d980-3008-11eb-812c-4812a2158b88.png)

**Comment by KingDeadZ** [comment]
Ki lehet játszani azzal, hogy a menüjéből rákattolsz a tradera, és berakja.

**Comment by andris155** [comment]
A Slimefun tárgyakkal való kereskedés le lett tiltva a falusiaknál egy másik probléma miatt. Ez direkt működik így sajnos.

**Comment by IcyAlex** [comment]
De akkor feleslegesen van a Beváltónál ott a falusi

**Comment by andris155** [comment]
@MrZero1 Szerintem így kilehetne venni ezt a beváltót. Nem sok értelme van így.

**Comment by MrZero1** [comment]
Akkor kikerül, de az ottani dolgokat máshogy nem fogják tudni elcserélni.

**Comment by andris155** [comment]
Majd írok nekik hátha kezdenek vele valamit.

**Comment by andris155** [comment]
@MrZero1 Amit írtak megoldást, hogy a trade-re kell kattintani az működik. Ha nem Slimefun-os tárgyat vár a falusi akkor pedig nem. Tehát nem lehet vele kijátszani a védelmet, de ha Slimefun-os tárgyat vár el a falusi, akkor erre ez jó megoldás.

**Comment by andris155** [comment]
<img width="418" alt="Capture" src="https://user-images.githubusercontent.com/8324198/100520774-ebc43e80-319f-11eb-97f4-9729752b0c81.PNG">

**Comment by andris155** [comment]
<img width="642" alt="Capture" src="https://user-images.githubusercontent.com/8324198/100634511-afbfe380-332f-11eb-9178-b0389d0645c3.PNG">
