### ISSUE TITLE
Hónapstaffja szavazás

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4198]
**Szerver**: Savsziget

Savra is bekerülhetne ugyanaz a szavazás, csak annyi különbséggel, hogy abban csak a savszigetes staffok lesznek benne.

**Comment by andris155** [comment]
Ezt a plugint poma írta. Nem lett volna egyszerűbb inkább vele beszélni, hogy csinálja meg oda is?

**Comment by MrZero1** [comment]
Nem. Szerintem azért néha ránéz a Githubra, meglátja, ha ideje van megcsinálja és lezárja a jelentést.

**Comment by andris155** [comment]
Beraktam a savszigetre a plugint. A staff listát elvileg így betudod állítani külön ott is.

**Comment by MrZero1** [comment]
Igen. Köszi!
