### ISSUE TITLE
Káromkodáscsillagozó hiba.

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4199]
**Szerver**: Gondolom mindegyik

Ha színkódot írunk egy káromkodásba, akkor a chatcucc nem cenzúrázza. Példa: Retar&fdált
![image](https://user-images.githubusercontent.com/69635280/100391553-1c876500-3034-11eb-809e-f2a5b17ffbbf.png)

**Comment by andris155** [comment]
Ez szó nincs tiltva jelenleg.

**Comment by skrisz0101** [comment]
Tele káromkodta a party minden szóval, szóval ez hiba 🗡️
próbáld ki

**Comment by mangoshell** [comment]
![image](https://user-images.githubusercontent.com/69635280/100391756-c1a23d80-3034-11eb-95ee-d8bc7ded8a8a.png)
@andris155 ez sem?

**Comment by andris155** [comment]
Nem tudok rá megoldást, ha hiba ha nem.
