### ISSUE TITLE
Savsziget eventfejlesztés

### ISSUE THREAD

**Issue by derpyAK** [TheOld-Crafters/Minecraft-servers#4200]
**Szerver**: **Savsziget**

Elég kevés event és minigame található a savsziget szerveren. Survivalon sokkal több található, bővíteni lehetne akár a survivalos eventekkel és minigamekkel a savsziget szervert is. **Ui:** _Szerintem sokkal több játékost vonzana._

**Comment by Tomi321** [comment]
Ezt az ötletet csak támogatni tudom, szerintem simán bekerülhetne pár survivalos event savszigetre

**Comment by MrZero1** [comment]
Minigame közül melyik lenne jó savszigetre? Vagy milyen?

**Comment by skrisz0101** [comment]
Összes(?)

**Comment by Tomi321** [comment]
Felmentem survira válogatni egy párat, szóval itt van a listám az eventekről, amit szerintem bekerülhetnének savra:

Napi Eventek:
DeathRun
Lavarun
Osonás
Wildrun2

Manuális Eventek:
Ultra Spleef
Fallout
BuildUp
Spirál

Automata eventeket sajnos nem volt lehetőségem kipróbálni, de szerintem ezek az eventek is bőven feldobnák a savszigetet
Ui: Szerintem a Spirál event napi eventnek is bekerülhetne

**Comment by skrisz0101** [comment]
nemtom mér ne mehetne mind xd
