### ISSUE TITLE
Essence Of Afterlife Crafting Hiba

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4201]
**Szerver**:Savsziget (Survival?)

Savszigeten ma próbáltam craftolni egy pár essence of afterlifeot megrendelésre, de sajnos találkoztam egy elég zavaró hibával. Az ancient altar nem ismerte fel a craftingot. Mivel féltem, hogy csak én vagyok hülye, kétszer megpróbáltam a craftingot minden irányból, és újra is tettem az ancient altart, és ancient pedestalokat is körülötte, Sajnos semmi nem oldotta meg a problémát, emiatt azt gondolom, hogy a pluginnal van valami gond.

**Comment by UDPSendToFailed** [comment]
A régi, wither_skeleton_skull alapú Necrotic Skull már nem jó, player_head alapú kell hozzá.

**Comment by Tomi321** [comment]
Óhh értem. Akkor valami beváltó kéne hozzá, mert nekem van majdnem 1 stack régi necrotic skullom

**Comment by andris155** [comment]
Nem tudunk beváltót csinálni, mert le vannak tiltva a falusiaknál a Slimefun tárgy cserék.

**Comment by Tomi321** [comment]
Ejj akkor valahogy ki tudná nekem cserélni egy admin a régi necrotic skulljaimat?

**Comment by andris155** [comment]
Szerintem kitudják.
