### ISSUE TITLE
/1v1 hiba

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4202]
**Szerver**:Savsziget

Savszigeten nem működik a /1v1 parancs. Folyamatosan azt érzékeli, mintha foglalt lenne, vagy nem lenne egy aréna sem.
![PicsArt_11-27-05 37 50](https://user-images.githubusercontent.com/73227678/100470281-3bd7ce00-30d8-11eb-8357-b2485e8f99a7.png)

**Comment by MrZero1** [comment]
Nem tudom mi történt, de a 3 arénának nem volt beállítva az 1-1 kezdőpont, illetve a lobby sem. Javítottam, már jó minden.

**Comment by andris155** [comment]
köszönjük a javítást.

**Comment by szofogado** [comment]
Most már elindul az 1v1 és meg is kapod a kitet, csak nem teleportál el az arénába. 
Utánna, ha véget ér az 1v1 elteleportálódsz a tengerbe.
![image](https://user-images.githubusercontent.com/52892955/100514984-40a08e80-3179-11eb-98eb-8a2183e2760f.png)

**Comment by andris155** [comment]
Gratulálok a lottó nyereményhez.

**Comment by MrZero1** [comment]
Jó lenne ránézni, mi az isten baja van savon az 1v1-nek, survivalon jól működik.

**Comment by MrZero1** [comment]
Megint javítottam, beállítottam ismét az arénákat, de ez nem normális.

**Comment by szofogado** [comment]
Újra rossz :( Viszont mostmár az inventory-mat is törölte

**Comment by Tomi321** [comment]
A helyzet az, hogy megint elromlott, de most az egész inventorymat törölte. (Szofogadoval 1v1-eztünk)

**Comment by andris155** [comment]
javítva

**Comment by szofogado** [comment]
A cuccainkat azért vissza kapjuk?

**Comment by Tomi321** [comment]
A törlődött inventorymból az itemeket vissza kaphatnám majd esetleg? teljes old felszerelés volt nálam, valamint egy gyárat is terveztem építeni, emiatt az alapanyagok hozzá nálam voltak, és emellett még három hátizsák is volt nálam, elég sok értékkel

**Comment by andris155** [comment]
Ez már nem a jelentés része. Erről a staff tagokat kérdezzétek.

**Comment by MrZero1** [comment]
Mit kérdezzenek? Rámondással nem adunk vissza semmit..
