### ISSUE TITLE
Cheat akármi

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4203]
**Szerver**:Survival

Lovi_ karddal öli a boszorkányokat, közben ezt spameli nekem.
![kép](https://user-images.githubusercontent.com/29709854/100480309-2de27700-30f1-11eb-867a-af1debfc1871.png)
![kép](https://user-images.githubusercontent.com/29709854/100480354-45b9fb00-30f1-11eb-8825-6973df308de2.png)

**Comment by andris155** [comment]
Van már szerintem rá javítás. De továbbra se működik az mc-marketen a letöltés és addig nem tudja felrakni a plugin fejlesztő a frissítést hozzá sajnos. Amin elérhető lesz bekerül a frissítés.
