### ISSUE TITLE
Spleef  Event Pearl Hiba

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4204]
**Szerver**:Savsziget

Vace spleef eventet tartott, én meg 3.-ként kiestem. Mivel a nézőtérről semmit nem látni gondoltam letesztelem, hogy be tudok-e alulról ender pearlezni. És az eredmény az lett, hogy vége volt az eventnek, a map resetelődött, én meg ott álltam a pályán (persze nem én nyertem). Szóval igen, lehet ender pearlt használni a spleef eventen savon, és ez eléggé nagy gondot is okozhat, ha más is rájön, nem csak én.

**Comment by andris155** [comment]
Most már mindenki rájött, hogy ide publikusan megírtad.

**Comment by MrZero1** [comment]
Ezeket célszerűbb lenne nekem privátban (Discordon vagy Facebook oldalunkon) megírni, hamarabb is veszem észre.

**Comment by MrZero1** [comment]
Javítva.
