### ISSUE TITLE
Multi tool grappling hook 

### ISSUE THREAD

**Issue by Cartman777** [TheOld-Crafters/Minecraft-servers#4205]
**Szerver**: Survival

 Ha a multi tool grappling hookot jól lövöd és földetérés előtt itemet váltasz akkor megkapod a nyilat és a lasszót is.

**Comment by Tomi321** [comment]
Ez már asszem volt jelentve

**Comment by Tomi321** [comment]
#4113

**Comment by andris155** [comment]
Ez valamivel másabb, majd tesztelem ezt is.

**Comment by andris155** [comment]
Ez gyakorlatilag ugyanaz a hiba, csak már nem beragad az egész a földbe, hanem fel lehet szedni. Szerintem annyira nem probléma. Nem olyan értékes a nyíl meg a lasszó. Főleg, hogy ezt tölteni is kell.
