### ISSUE TITLE
/shop hiba

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4206]
**Szerver**:Savsziget

/shop-ban 9 stack lávát próbáltam venni, a több vásárlása opcióval. 9 stacket vettem, de a 9 stack helyett 9db-ot kaptam. A pénzt szerencsére nem buggosan vonta le, de az androidok miatt fontos lenne, ha stackelve bírnám a lávát venni.

**Comment by Tomi321** [comment]
Update: Minden item több vásárlása buggos. Az eddig 9 stack vásárlás az átállítódott 9db vásárlására. Szóval nem is kicsi baj van, az egész shop buggos

**Comment by andris155** [comment]
Lávából nem is lehet 9 stack-et, mivel nem lehet stack-elni...

**Comment by andris155** [comment]
A lávás vödörből 1 stack az 1 db. lávás vödör. Ez nem hiba.

**Comment by andris155** [comment]
Amit nem stack-elni azoknál ugyanez érvényes. Vagy 16 1 stack pár tárgynál.

**Comment by andris155** [comment]
Az árat helyesen számolja így is.

**Comment by KingDeadZ** [comment]
Régen lehetett stackelve venni a lávát :D

**Comment by andris155** [comment]
Már nem lehet.
