### ISSUE TITLE
Item megduplázás

### ISSUE THREAD

**Issue by LebkuchenXD** [TheOld-Crafters/Minecraft-servers#4207]
A slimefunos charging benchbe találtam mégegy pontosan ugyanolyan nano blade-et mint amilyen az enyém fireproof és soulbound rúnákkal és ugyanolyan enchantokkal!

**Szerver**:s1.oldcrafters.net

**Comment by MrZero1** [comment]
Survival szerver, az egyiket elvettem tőle.

**Comment by andris155** [comment]
Nekem nem lesz belőle még egy, ha berakok tölteni egyet. Kellene az, hogy pontosan hogyan duplázod meg. Így, hogy valamiért véletlenszerűen 2 lett belőle ezzel nem tudok mit kezdeni sajnos.
