### ISSUE TITLE
Sav SF hiba

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4208]
**Szerver**: Sav

Privátba elküldtem Pomának, Andrisnak. 
Forgacsm jelentette. OCD-t kér érte, ha jár neki. :v

**Comment by andris155** [comment]
Javítva. De ez a túlélőn is szerintem probléma. Majd teszteljétek le.

**Comment by andris155** [comment]
1016 OCD
