### ISSUE TITLE
Savsziget páncélállvány szerkesztő

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4209]
**Szerver**: Sav

![kép](https://user-images.githubusercontent.com/29709854/100775593-c8013280-3403-11eb-8a07-0a7682acb41e.png)

Ha valaki elkezdi használni a szerkesztőt, kiírja a chatre (gondolom op-tól), kicsit zavaró

**Comment by andris155** [comment]
Javítva.
