### ISSUE TITLE
Slimefun Anti afk megoldás

### ISSUE THREAD

**Issue by HighmanHuge** [TheOld-Crafters/Minecraft-servers#4211]
Survival szerver

Üdv, mivel folyamatosan probléma hogy pár játékosnak csak a balltop 10 a cél a szerveren, így amióta játszok megy a küzdelmetek az óriás sf farmok ellen. Most a vas és az arany kivétele az eladható holmik közül szemmel láthatóan létszámcsökkenést eredményezett.
Szerintem jó megoldás lenne ha limitálnátok az egy chunkra lehejezhető sf gépek számát (cobble gen grinder egyebek), már ha kivitelezhető
Így visszakerülhetne minden a boltba, magát az sf kiegészítőt sem kellene csonkítani, és ösztönözné a játékosokat hogy építsenek olyan pwarpot amin szívesen tartózkodnak mások is, mert higgyétek el nem fognak fel alá rohangálni hogy termeljen a holmi.

**Comment by andris155** [comment]
Nem szeretnék ilyen limitet és egyébként nem is igazán megoldható jelenleg.
