### ISSUE TITLE
Kreatív védelem hiba csapóajtóknál

### ISSUE THREAD

**Issue by justvidmanfan** [TheOld-Crafters/Minecraft-servers#4212]
a hiba a survival szerveren van de elhiszem hogy a savszigeten is müködik nos ami történik **ha** felépitünk 3 block magasra és lerakunk egy trapdoor-t majd rá egy ajtót kreatívban és kinyitod a csapóajtót/trapdoort akkor a kreatívban lehelyezett ajtó itemként megkapható
![image](https://user-images.githubusercontent.com/75452269/101089202-2588b100-35b5-11eb-9145-e3356eac57a3.png)
![image](https://user-images.githubusercontent.com/75452269/101089326-4d781480-35b5-11eb-82e1-75aff7495802.png)
elnézést ha nem lehet látni a képeket mert ha nem a játékbeli nevem justvidmanfan szóljanak rám ott majd demonstrálom

**Comment by andris155** [comment]
Jelentettem a fejlesztőnek. Talán valamikor az 1.17-re lesz javítás rá.

**Comment by andris155** [comment]
508 OCD
