### ISSUE TITLE
Cheat védelem hiba

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4213]
**Szerver**: Survi

Ha jégen csónakázunk és gyorsan megyünk akkor kidob a csónakból.

**Comment by TryHardDo** [comment]
Szintén ha minecartba kicsit gyorsabban mész kidob.

**Comment by andris155** [comment]
Egy ellenőrzés van a járművekre. A fejlesztő szerint megpróbálhatom letiltani, de azt nem szeretném, mert úgy a csónakkal lehet repkedni csalással. Talán lesz rá javítás később, de az is lehet, hogy sajnos nem.

**Comment by mangoshell** [comment]
Denemááár. Kinek jutna eszébe csónakkal repülni csalással? xd Ezért ne legyenek már elcseszve ilyen alap dolgok.

**Comment by andris155** [comment]
A Minecraft hivatalos Facebook oldalán is osztottak meg olyan videót, amiben ezt a csalást használják. Szóval sok embernek jutna eszébe.

**Comment by mangoshell** [comment]
Csalódtam a szerverben
