### ISSUE TITLE
Cheat védelem?

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4214]
**Szerver**: Survival

Csak öli a vadonban a mobokat.

![kép](https://user-images.githubusercontent.com/29709854/101227049-d5821b00-3696-11eb-9690-4eda9e0691a6.png)
![kép](https://user-images.githubusercontent.com/29709854/101227058-df0b8300-3696-11eb-8ec4-24dbec397c72.png)
![kép](https://user-images.githubusercontent.com/29709854/101227071-ec287200-3696-11eb-850f-d0dd481179ce.png)

**Comment by andris155** [comment]
Szerintem az mcMMO miatt amit nem támogat. Vagy valóban csal.
