### ISSUE TITLE
Nyulak VS Pingvinek - tesztelések

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4215]
**Szerver**: Survival

Ha van valami hiba, észrevétel a játékkal, itt lehet jelezni.
Most teszteltük 4-en (King, Oli, Viki), jó volt minden.

**Comment by KingDeadZ** [comment]
Szövetséges szuperboostot ki lehetne majd kapcsolni, túl op

**Comment by MrZero1** [comment]
> Szövetséges szuperboostot ki lehetne majd kapcsolni, túl op

Mi lenne, ha drágábban lehetne megvenni? És mondjuk a mostani effektek helyett kaphatna erő 1 meg valami más effektet.

**Comment by KingDeadZ** [comment]
Úgy talán jó lehetne, erő 1 gyorsaság 1 5secre, és 2,5kért talán

**Comment by andris155** [comment]
Szerintem egyelőre rendben van most ez a plugin. Nem ír ki hibákat sem. Ha valami beállítás legyen változtatva azt meg majd írd meg @MrZero1 ha a játékból nem lehet.
