### ISSUE TITLE
Bal top parancs.

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4216]
Szerver: Survival

Olvastam egy jelentést githubon amelyben az alábbi állt:
"Üdv, mivel folyamatosan probléma hogy pár játékosnak csak a balltop 10 a cél a szerveren, így amióta játszok megy a küzdelmetek az óriás sf farmok ellen."
Valóban tény, hogy a mértéktelen pénzhalmozás az ami miatt egyesek slimefun gyárakat hoznak létre, és mivel különösebben nincs céljuk a pénzzel egyéb ötletem nekem sincs, hogy mi másért kellene nekik, mint a baltop első oldaláért. Így hát egyszerű javaslattal élnék. a /baltop parancs legyen kivéve. Player ne láthassa, hogy a szerveren kinek mennyi pénze van. Az indoklás egyszerű. Ha nem tudják összeméregetni hogy kinek mekkora a ... akkor kevésbé fogják érezni a motivációt arra, hogy a sajátjukat növeljék tovább és tovább.

**Comment by andris155** [comment]
Ezzel nem oldunk meg semmit. Sokan el is mennének, mert nincs többé semmilyen cél amiért érdemes lenne játszaniuk a szerveren.

**Comment by MrZero1** [comment]
Mondjuk én/mi is gondoltunk rá, hogy ha nincs baltop parancs, akkor talán kevésbé érdekli az embereket a pénz.
