### ISSUE TITLE
Fordítás hiány

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4218]
**Szerver**: Savsziget
![2020-12-08_13 19 42](https://user-images.githubusercontent.com/29951969/101483299-42780800-3958-11eb-91cb-0fbfe8fe63cc.png)

**Comment by andris155** [comment]
Nincs lefordítva. Ez nem hiba.

**Comment by skrisz0101** [comment]
hát, de. mér nincs lefordítva?

**Comment by andris155** [comment]
Mert erősen fejlesztés alatt áll az addon és napi szinten változik az angol fordítás is jelenleg. Majd ha már valamennyire kész állapotban lesz akkor érdemes lefordítani. De akár most is nyithatsz pull-t az addon-hoz a fordítással és akkor hozzánk a szerverre is bekerül.

**Comment by skrisz0101** [comment]
Ja, jó
nem tudtam h még ennyire fejlesztik
