### ISSUE TITLE
survi spawner

### ISSUE THREAD

**Issue by lovi-dev** [TheOld-Crafters/Minecraft-servers#4219]
Surv. szerveren spawnerek simán és kreában is szétüthetőek. Kiüti és megsemmisül, eltűnik. Jó ez így?

**Comment by andris155** [comment]
Mi ezzel a probléma?

**Comment by lovi-dev** [comment]
> Mi ezzel a probléma?
Ez eddig nem így volt, nem lehetett spawnert véletlenül kiütni.

**Comment by andris155** [comment]
Szerintem ez mindig így volt. De túlélőben is lehet véletlen spawner-t kiütni a nem megfelelő eszközzel.
