### ISSUE TITLE
SF lebegő felirat

### ISSUE THREAD

**Issue by maryhonaly** [TheOld-Crafters/Minecraft-servers#4221]
Survival, SF eszközöknél tegnap láttam először, hogy a felettük lebegő felirat valamiért duplikálódik-triplikálódik, így olvashatatlan lesz.

Képet mellékelem, próbáltam rákérdezni, hogy mikor miért miről lesz ilyen, állításuk szerint random, és utána így is marad, de funkcionál tovább. 

Említették nekem, hogy ha teljesen kipakolják (nem tudom ezeknél mit jelent ez) majd leállítják, és újraindítják, ismét jó lesz. 

<img width="1792" alt="Képernyőfotó 2020-12-10 - 0 42 18" src="https://user-images.githubusercontent.com/53797506/101772524-c1517a00-3aeb-11eb-848b-1e4109b81100.png">
<img width="1792" alt="Képernyőfotó 2020-12-10 - 12 08 37" src="https://user-images.githubusercontent.com/53797506/101772529-c31b3d80-3aeb-11eb-8771-2d2e559be445.png">

**Comment by IcyAlex** [comment]
Elég idegesítő

**Comment by KingDeadZ** [comment]
gondolom a barrelekre értette, amúgy főleg a barreleknél észrevehető ez, ott sokszor van ilyen, meg néha a regulatorok halnak be
nálam a cargo managerek annyira nem szeretnek bugolósat játszani

**Comment by Tomi321** [comment]
Nálam a Cargo Managerektől az Energy Regualtorokig rengeteg minden buggol be elég gyakran

**Comment by skrisz0101** [comment]
nekem sose semmi se buggol be xd

**Comment by andris155** [comment]
Pontos reprodukciós lépések nélkül nem tudok ezzel mit kezdeni ahogy a Slimefun fejlesztő sem.
