### ISSUE TITLE
Pvp Telekvilágba

### ISSUE THREAD

**Issue by DiamondGamer321** [TheOld-Crafters/Minecraft-servers#4222]
Survival -->

Napokba szembesültem azzal a ténnyel, hogy a PVP a telek világba annak ellenére se megy, miután a telek plugin "engedélyezi", és kijelenti, hogy "A flag sikeresen hozzáadva!". Egy nagyobb szórakoztató arénát épitettem telkemre, aminek lényege, hogy tudjunk sebzést adni más játékosoknak. Miután elkészültem, egy tesztelést akartam végrehajtani, miután észrevettem, hogy nincs PVP.
Két opciót tudnák ajánlani.
1. A flag "használatának" engedélyének megvonása.
Amiért nem teszteltem a projekt elött, hogy tényleg van-e PVP, mivel a plot plugin kijelentette, hogy "Igen is, van PVP!", én meg nem számítottam rá, hogy az egész világ WorldGuard-al van védve a pvp ellen. 
2. A PVP engedélyezése.
Tisztába vagyok vele, hogy miért is döntöttek így a staffok, hogy megvonják az egész világot ettől az opciótól, gondolom a TpKill
megelőzése érdekébe. De ez nagyon logikátlan. Aki van olyan féreg, hogy ilyet tenne, az akk ha nem a telekvilágba, hanem a vadonba biztos megteszi. Szóval teljesen mindegy, Lehet egy másik oka is a megvonásnak mégpedig, hogy a telkeken a szomszédok/véletlenszerű vándorlók meg ne haljanak egyes rosszindulatú emberek által, mivel belépnek a telkükre. Szerintem az ilyenre, apró az esély, hisz naponta egyszerre csak 20-40 játékos van fent, kevés az esély, hogy az eggyik közel legyen a másikhoz.

A második opcióra megoldás szerintem:A PVP flag beállítása ranghoz lenne kötve (Mint a biom, zene beállítása telken), például az Elit ranghoz (Nem azért, mert az van nekem jelenleg. :,D), hiszen ha valaki költ a szerverre nagyobb esetbe nem akar magának rosszat, nem használja ki "előnyeit".

UI: Ez az amit építettem, egy saját "eventem", amit játékosok közt tartok nagyobb nyereményekért. Ehez az eventemhez kellet volna a pvp flag. (Nem vérharc az event lényege, egy eléggé vicces, mókás event, ráadásul nagyon egyedi amit nagy nyereményért tartottam volna. A flag azért kell, mert a playerek sebzést kell okozzanak a többi játékosnak.) 

-DiamondGamer321

**Comment by andris155** [comment]
Elég lett volna egy 2 soros szöveg, hogy szerinted hasznos lenne ha engedélyezném. Ezt még valamikor 6 évvel ezelőtt állíthattam be én így. Azóta ez mindenkinek jó volt így. Megnézem majd ezt a flag dolgot, és ha tényleg jó akkor átállítom.

**Comment by MrZero1** [comment]
Elit rangtól lenne a legjobb.

**Comment by andris155** [comment]
Engedélyeztem a pvp-t a telek világban. Más telkén csak akkor működik a pvp, ha ahhoz külön hozzá lett adva a pvp flag true beállítással.
