### ISSUE TITLE
/ignore hiba

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4223]
Survival, Savsziget.

Ignorált player /me üzeneteit látja az is aki ignorálta őt.

**Comment by andris155** [comment]
Javítva.

**Comment by UDPSendToFailed** [comment]
P gombbal is lehet ám ignorálni, nem kéne ezért kivenni a /me jogot

**Comment by andris155** [comment]
Nem is lett kivéve. Máshogy lett megoldva. :D

**Comment by andris155** [comment]
508 OCD

**Comment by UDPSendToFailed** [comment]
Oh, ez esetben nem szóltam, csak a partychat miatt hasznos dolog, és pár perce még nem volt jog xd
