### ISSUE TITLE
Nether generátor probléma

### ISSUE THREAD

**Issue by balazzz53** [TheOld-Crafters/Minecraft-servers#4224]
**Szerver**:

szerver:savsziget egyszerüen nem müködik a nether generátor egy segítő is megnézte nem tudott rá semmit mondani.csak egy sima generátor de nem működik.

**Comment by balazzz53** [comment]
test

**Comment by andris155** [comment]
Így működik nekem:
Bal oldalt láva, a közepén ahol létrejön a blokk oda soul soil kell alá, bal oldalra pedig kék jég.
![2020-10-26_23 08 37](https://user-images.githubusercontent.com/8324198/97234051-5b7d8d00-17e0-11eb-85c1-75cae7883d9c.png)

**Comment by andris155** [comment]
Amelyik generátornak kifejezetten nether generator a neve az csak a nether-ben működik. A bazalt generátor mindenhol működik.

**Comment by andris155** [comment]
A sima nether generátor csak a nether-ben működik. A starting nether generátor pedig mindenhol.
