### ISSUE TITLE
mcmmo /inspect

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4225]
**Szerver**: Survi

Amikor szeretném használni a /inspect parancsot valami ratyi fawe üzenet jön be. 
![image](https://user-images.githubusercontent.com/69635280/102012675-14296c80-3d4c-11eb-8144-c3025c55e125.png)

**Comment by poma123** [comment]
Nem hiba, a fawe parancsa felülírja az mcmmo parancsát. Ha használni szeretnéd, /mcmmo:inspect

**Comment by mangoshell** [comment]
Nem lehet kitabolni :(
