### ISSUE TITLE
Cucc elvesztős bridge, hg  kaland

### ISSUE THREAD

**Issue by Bazsaaaa** [TheOld-Crafters/Minecraft-servers#4226]
**Szerver**: survival

 Nagyban éveztem a bridge eventet amikor egy csúnya fiú lelökött és ahelyett hogy játchattam volna tovább, a telkemre teleportálodtam a cuccaim nélkül (ami nálam volt mielőtt beléptem az eventre). 
A hungergamesnál meg az volt hogy rátpztem diára, beléptem hg-ra, dia elfogadta a tp-t és hg közben ott futkároztam dia pwarpján

**Comment by andris155** [comment]
A Bridge eventre akkor gondolom be lehet lépni tárgyakkal (?). Ha jól tudom ezt poma fejlesztette, szóval szerintem max javítani is ő tudja.
A Hungergames-nél meg akkor ha függőben van a teleport kérés akkor ha elfogadják gondolom el tp-z. Erre majd megpróbálok megoldást találni.

**Comment by poma123** [comment]
Az automata eventekre lehet belépni, és olyankor lementi az inventoryt. Nem nagyon tudom elhinni, hogy ez így megtörtént, de meg fogom nézni a logokat. Jobb lenne ha külön issue-t nyitnál két külön hibára, és nem egyet.

**Comment by Sanszi** [comment]
> A Bridge eventre akkor gondolom be lehet lépni tárgyakkal (?). Ha jól tudom ezt poma fejlesztette, szóval szerintem javítani is csak ő tudja.
> A Hungergames-nél meg akkor ha függőben van a teleport kérés akkor ha elfogadják gondolom el tp-z. Erre majd megpróbálok megoldást találni.

Teszteltük, működik, HG-s itemeket is lehet így kihozni.

**Comment by poma123** [comment]
Nem tudtam reprodukálni a cucc elvesztést, a logban konkrétan semmi nincs erről.

**Comment by andris155** [comment]
Megcsináltam a teleportálást, már nem működik, amit írtál.

**Comment by andris155** [comment]
1016 OCD

**Comment by andris155** [comment]
Kinek adjam az OCD-t?

**Comment by Bazsaaaa** [comment]
Halii! Bazsaaa a nevem a szerón

András Marczinkó <notifications@github.com> ezt írta (időpont: 2020. dec.
18., P 17:08):

**Comment by andris155** [comment]
Megadtam.

**Comment by Bazsaaaa** [comment]
Köszönöm szépen 😙

András Marczinkó <notifications@github.com> ezt írta (időpont: 2020. dec.
18., P 17:15):
