### ISSUE TITLE
Slimefun láda újratöltés

### ISSUE THREAD

**Issue by DiamondGamer321** [TheOld-Crafters/Minecraft-servers#4227]
Survival -->

Új loot a Slimefun ládához. Új ércet bele, új eszközt, új inventory pet, új gép alkatrész, új gépek, új alapanyag. Már nem izgalmas a láda, mint amilyen volt az elején.

**Comment by MrZero1** [comment]
Lassan jelentéktelenek lesznek (vagy már azok) a napiládák, amennyi kulcsot lehet farmolni belőlük.

**Comment by skrisz0101** [comment]
lucky blockot nem akartátok újrakonfigolni?  asszem volt jelentés is hozzá

**Comment by MrZero1** [comment]
#4229
