### ISSUE TITLE
Alap színes írás 

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4228]
**Szerver**: mindenhol
Egy időben volt colortoggle vagy milyen parancs amivel az írásod alapértelmezetten átállítjattad, csak asszem rang után nem veszett el
Ez már jó? Sztem bekerülhetne
(adnám ha party chaten is színesen írna)

**Comment by andris155** [comment]
A MineMarket megbízhatatlansága miatt nem igazán akarok ilyet. Sokszor nem törölné a színes írást.

**Comment by andris155** [comment]
Talán jogokkal is megoldható. Majd tesztelem ezt még.

**Comment by andris155** [comment]
Így van. Működik jogokkal.

**Comment by andris155** [comment]
Bekerült /chc color a parancs.

**Comment by andris155** [comment]
A party chat nem volt tesztelve. Azt majd nektek kell. :D

**Comment by KingDeadZ** [comment]
partyban is működik

**Comment by skrisz0101** [comment]
kösziiiiii

**Comment by skrisz0101** [comment]
am lesz majd hozzá fordítás? van kisebb infos rész is

**Comment by MrZero1** [comment]
Szerintem borzalmas. Zavaró nagyon, több staff nevében is írhatom ezt. 
Legalább a Staffchaten ne legyen egyéni szín, jó volt ahogy volt az.

**Comment by KingDeadZ** [comment]
Esetleg admintól lehetne, kicsit tul sok a szín, nagyon ocsmány a chat xD 
![image](https://user-images.githubusercontent.com/38157910/102260519-da559300-3f10-11eb-8a9d-f7646a52dd26.png) itt egy aláírás
 
másik jó dolog lenne a formázás kikapcsolása ha bentmaradna játékosoknak meg a sötétebb szinek kikapcsolása + pink kikapcsolása

**Comment by andris155** [comment]
De ha akarnának tudnának így írni alapból is. Akkor inkább a színes írás és formázás a probléma nem?

**Comment by MrZero1** [comment]
Folytonosan nem tudnának így írni.

**Comment by andris155** [comment]
Visszavontam a változtatást akkor így.
