### ISSUE TITLE
Bolt - Lock kapcsolata

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4230]
**Szerver**: Survival

![kép](https://user-images.githubusercontent.com/29709854/102253537-bb063800-3f07-11eb-9809-6bd53df8c9cb.png)

Mikulásnál akartam még lerakni tölcsért, ládát, mert sok a könyv, erre ezt írja ki.

**Comment by MrZero1** [comment]
Áh, ha leütöm a [lock] táblát, akkor jó, de amúgy amiatt nem engedi lerakni a láda alá (hozzákötni) a tölcsért.

**Comment by andris155** [comment]
A levédés hibátlanul működik ha megfelelően van használva. Azért nem működik ez esetben megfelelően mert a [lock] sor alatt nem adtál meg semmilyen nevet.

**Comment by andris155** [comment]
Mondjuk ha megadod a saját neved akkor működik a tölcsér lehelyezés, de azt nem értem én sem, hogy ha bolt nincs létrehozva, akkor miért a bolt tiltja le a tölcsér lehelyezést a ládához.
