### ISSUE TITLE
Szezonális szöveg / szerverek kiírása

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4231]
**Szerver**: Szerverválasztó (nem a szerveren)

TheOld - Crafters felirat alá lehetne rakni, hogy milyen szerverek elérhetőek <Survival  Savsziget  OldSpace  Építész>

Ha esetleg különleges időszak van, akkor:
TheOld - Crafters felirat alá lehetne rakni szezonális szöveget, mint pl téli eventek, téli login, mikulás, vagy mittomén mi

Kicsit uncsi a sima TheOld - Crafters felirat

**Comment by andris155** [comment]
A szerver típusokat teljesen felesleges kiírni. Aki hozzáadja a listához általában fel is megy a szerverre ott pedig úgyis látja milyen szerverek vannak.
Szezonális dolgokat lehetne kiírni, ha elküldi nekem az adminok közül valaki, hogy mettől meddig legyen valami, és milyen színezéssel illetve hogy mi, akkor azt nagyon nagyon szívesen kiírom oda.
@MrZero1

**Comment by andris155** [comment]
A színezések a motd-hoz: https://docs.adventure.kyori.net/minimessage.html#format
