### ISSUE TITLE
Javításra szorul a káromkodásszűrő

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4232]
![image](https://user-images.githubusercontent.com/16057404/102348107-ad04f580-3fa1-11eb-8905-562f09fec8be.png)

**Comment by andris155** [comment]
Megcsináltam ékezetek nélkül is a tiltásokat, bár ha már magyarul írunk szerintem sokkal szebb ékezetekkel írni.

**Comment by andris155** [comment]
508 OCD
