### ISSUE TITLE
Admin ignor

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4233]
**Szerver**: E

Hiába ignoreolok egy admint, akkor is látom mit ír :( 

Edit: Megoldottam, de a /ignore akkor is béna így

**Comment by poma123** [comment]
Az ignore paranccsal nem fog menni. Az 1.16.4 óta van a social beállítás, amit a P betűvel lehet előhozni.

**Comment by andris155** [comment]
Szerintem volt is ilyen kérés, hogy admint ne lehessen. Legalább most megvalósult ez is. A P betűs megoldást én mondjuk egyáltalán nem teszteltem. Egyáltalán támogatja a custom chat format-et? /me üzeneteket? Privát üzeneteket? Nem lepne meg ha nem támogatná.

**Comment by mangoshell** [comment]
Még a partychatet is lehet vele ignoreolni, amit a simával nem lehet.
