### ISSUE TITLE
Fluffybarrels hiba

### ISSUE THREAD

**Issue by szofogado** [TheOld-Crafters/Minecraft-servers#4234]
Savsziget, survival

Savszigeten nekem van egy Miner android tornyom, amivel érceket bányászok. Ma ki akartam üríteni ezeket a hordókat, mert metgteltek., Mikor oda érem egyszer csak eltünt néhány darab. A szöveg ott maradt fölöttük. Nem tudom, hogy mi okozta, még meg nyitni se volt időm.

![2020-12-17_08 31 49](https://user-images.githubusercontent.com/52892955/102457377-f35e6100-4042-11eb-8400-883e050a1b80.png)

**Comment by szofogado** [comment]
![2020-12-17_08 47 04](https://user-images.githubusercontent.com/52892955/102458389-7502be80-4044-11eb-9ff7-813b31740c09.png)
A dust gyáramnál is eltüntek.

**Comment by UDPSendToFailed** [comment]
Nekem is eltűnt minden dustból jó 1 millió, és ~1.8-2 millió aranyrúd.

![image](https://user-images.githubusercontent.com/16057404/102501684-fe82b280-407d-11eb-9047-914f3433c6ed.png)

**Comment by andris155** [comment]
A hibát a fejlesztő a ,,hologram toggle button" hozzáadásával okozta. A hiba már javításra került. A blokkot a hiba miatt tudtommal a Slimefun törli ilyenkor. Az inventory-ban tárolt dolgokat nem biztos. Ha újra leraktok egy ugyanolyan barrel-t lehet benne lesz, ami előtte volt.

**Comment by UDPSendToFailed** [comment]
Leraktam egy ugyanolyat a Coal-os helyére, így már a bizonyítékul szolgáló hologram is eltűnt. :/ 

![image](https://user-images.githubusercontent.com/16057404/102641326-319b7380-415c-11eb-923f-a4f862f606c4.png)
![image](https://user-images.githubusercontent.com/16057404/102641334-37915480-415c-11eb-9318-acabaeaf7a74.png)
