### ISSUE TITLE
Mypet pet eltünése

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4235]
**Szerver**: survival

Vadonba befogok egy petet, majd ha elmegyek a telkemre, utána újra le akarom hívni, eltűnik, akkor is ha a petstorage-ba rakom.

**Comment by andris155** [comment]
A telkeken le van tiltva a MyPet, mivel sajnos nem frissítették az új PlotSquared-hez.

**Comment by Sizarra** [comment]
Igen azt tudom, de ha újra elmegyek a vadonba, akkor azt írja, hogy: "You don't have a pet!"

**Comment by Jaffis** [comment]
Siza, relog ilyenkor asszem segít.

**Comment by andris155** [comment]
Nem támogatott plugin a MyPet. Sajnos erre így nincs jelenleg javítás. Az adatbázis hibáról tudunk és már a MyPet GitHub oldalán is elég régen megírtam nekik.

**Comment by andris155** [comment]
Valószínűleg ennek is köze lehet az adatbázisos hibának, vagy valamelyik másik plugin támogatása is már elavult benne.
