### ISSUE TITLE
Slimefun bővítmény és a hozzátartozó kiegészítők

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4236]
**Szerver**: Túlélő, Savsziget

Nem tudom, hogy hibajelentés vagy fejlesztési ötlet, de valamit kellene kezdeni a Slimefun-nal. 
Napi szinten írják, hogy élvezhetetlen a szerver a laggok miatt.

**Comment by MrZero1** [comment]
Ha van bárkinek bármi ötlete, hogyan lehetne ésszerűen korlátozni a gyárakat, akkor nyugodtan írja ide.

**Comment by UDPSendToFailed** [comment]
Cargo Input-ból ki kell venni a filter lehetőséget, lesz helyette redstone-os szelektáló xdddd

**Comment by lovi-dev** [comment]
Első ötlet: pwarp-on és tőle 16 chunkon belül ne lehessen cargo-t használni, így a boltok nem fognak plusz cargo laggot generálni. Kemény szabály, de nem kell hozzá fejlesztés, a ráérő segítők tudják ellenőrizni...

Második ötlet: ez sajnos fejlesztést igényel.
Van valami plugin Pistonra, ami számolja és max 100-at enged lerakni. Ha ezt át lehetne írni cargo input/output node-okra, akkor lehetne vele mérsékelni a cargo laggot.

**Comment by andris155** [comment]
Nem tudjuk kivenni a filter-t. A cargo letiltása lenne az egyetlen tényleg jó megoldás, de akkor meg már a Slimefun-nak sincs értelme.
Tesztelgettem én is tag ranggal a szervert. Számomra is elér borzalmas a játék élmény. Egy gagyibb gépen amin alapból is akad játék ott mondjuk gondolom nem igazán észrevehető. De egy jó gépen nagyon észrevehető és ha én lennék a játékos inkább egy olyan szerverre mennék ahol nincsenek ilyen laggok. Számomra a Slimefun annyit nem ad hozzá a játékélményhez hogy elviseljem a laggokat.

**Comment by MrZero1** [comment]
> Nem tudjuk kivenni a filter-t. A cargo letiltása lenne az egyetlen tényleg jó megoldás, de akkor meg már a Slimefun-nak sincs értelme.
> 
> Tesztelgettem én is tag ranggal a szervert. Számomra is elér borzalmas a játékélmény. Egy gyengébb gépen amin alapból is akad játék ott mondjuk gondolom nem igazán észrevehető. De egy jó gépen nagyon észrevehető és ha én lennék a játékos inkább egy olyan szerverre mennék ahol nincsenek ilyen laggok. Számomra a Slimefun annyit nem ad hozzá a játékélményhez hogy elviseljem a laggokat.

Sajnos ezzel egyetértek. A legszomorúbb, hogy az amúgy is extrákkal teli szervert (sok event, minigame, mcmmo, napiládák meg a többi) is elrontja. 
Nem kötelező slimefunozni, ezt már többször hallottam a szerveren, de a játékélményre kihat a lagg is, hiába nem akar a játékos slimefunozni.

**Comment by KingDeadZ** [comment]
Pár ember túlhasználja a cargot, szerintem csak annyi a baj szerintem... Ha valaki odamegy tf2levitelkére, a tps nagyon leesik a fölöslegesen sok gép miatt és a cargok miatt. Limitálni kell valahogy, akár staffal akár valahogy pluginnal ha megoldható, mert hiába vannak fent a "nagyobb sf"esek közül páran, nincs akkora lag 40 ember mellett, mintha valaki 10 embernél odamenne tf2levi telkére

**Comment by andris155** [comment]
Nem megoldható a cargo limitálása és mivel nem hiba a Slimefun nem is foglalkozik ezzel. Mindig lesznek olyanok akik túlhasználják.

**Comment by UDPSendToFailed** [comment]
Ezért kell szabály, mielőtt lemegy a player, szépen kiüti a mangereit, hogy offline ne működjön a gyár.

**Comment by andris155** [comment]
Ennek a szabálynak semmi értelme nem lenne. Most is csak akkor gond értelemszerűen, ha a játékosok ott vannak a farmnál és megy. Ha nincs ott a játékos és offline a farm nem megy.

**Comment by UDPSendToFailed** [comment]
Ha valaki odamegy a gyár közelébe a pwarp-ra, már el is indul, és ahogy lovi is írta, 14-16 chunk távolságról betölt a cargo.

**Comment by lovi-dev** [comment]
[Slimefun4/src/main/resources/config.ym](https://github.com/Slimefun/Slimefun4/blob/3a9f9f0416ef23e8fe38e82a8d732d02d3fb4a16/src/main/resources/config.yml#L37)l -ba  van egy network config rész, ezzel nem lehet limitálni a cargo nodeok számát?
Mármint bevezetni egy szabályt, hogy max X darab nodemannagered lehet és a max-size -t levenni 200-ról jóval kevesebbre.

**Comment by andris155** [comment]
és mennyire levenni?

**Comment by skrisz0101** [comment]
Az a config beállítás elvileg nem működik

**Comment by andris155** [comment]
Nekem ez a szám sokat nem mond. Az érték kellene ami még nem is túl kicsi meg nem is túl nagy.

**Comment by andris155** [comment]
Ha jól emlékszem de működik. Úgy emlékszem ilyenkor dobja ki a földre a tárgyakat ha ezen limiten túl megy valaki.

**Comment by skrisz0101** [comment]
Nem számít, mert ha 1 rendszeren csak 50 lehet, akkor 4x annyi rendszer lesz.
Nem kell túlbonyolítani ezt az egészet 
Akkor van lagg, ha 2-3 ember ott van a farmján.
Nem kell világmegváltó ötleteket írni, elég lenne csak őket meggyőzni
(nem, tőlem még csak 0.1 Tps se megy le, teszteltük többször is)

**Comment by lovi-dev** [comment]
> Nem megoldható a cargo limitálása és mivel nem hiba a Slimefun nem is foglalkozik ezzel. Mindig lesznek olyanok akik túlhasználják.

elméleti jelleggel a
[CargoInputNode.java](https://github.com/Slimefun/Slimefun4/blob/e4ddc7c452436061f690f8faeee79d3515eb6075/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/cargo/CargoInputNode.java#L43) 
BlockStorage.addBlockInfo(b, ROUND_ROBIN_MODE, String.valueOf(true));
helyett
BlockStorage.addBlockInfo(b, ROUND_ROBIN_MODE, String.valueOf(false));
és tiltva van a round robin. 
Csak innentől kézi buildelés és firssítés :(

**Comment by skrisz0101** [comment]
És elég könnyen lehet számolni hogy melyik gyár mennyit,,fogyaszt" egyszerűen úgy nézve hogy odatpzik majd spawnra pl

**Comment by lovi-dev** [comment]
> 4x annyi rendszer lesz
de ha nem lehet lehet, mert tilos? Perszer sokan megpróbálják majd kijátszani...

**Comment by UDPSendToFailed** [comment]
Advanced out nélkül így is sok manager kell a különböző itemek gyártásához, ki fogja azt eldönteni, hogy melyik hová tartozik, és belefér-e a limitbe?

**Comment by skrisz0101** [comment]
> Nem számít, mert ha 1 rendszeren csak 50 lehet, akkor 4x annyi rendszer lesz.
> Nem kell túlbonyolítani ezt az egészet
> Akkor van lagg, ha 2-3 ember ott van a farmján.
> Nem kell világmegváltó ötleteket írni, elég lenne csak őket meggyőzni
> (nem, tőlem még csak 0.1 Tps se megy le, teszteltük többször is)

Tartom magam ehhez a véleményhez :D

**Comment by Squidmanus** [comment]
Én úgy gondolom, hogy területkorlátozás kéne a cargozásra. Ez a mostani pandémia helyzet miatt jutott eszembe. Dióhéjban: 
Tarstuk be a másfél méter távolságot. Cargo esetében azt a távolságot, ahol már nem tölt be. Ötletem: csak telken lehetne cargozni(összevont telkere nem lehetne), minden játékosnak csak egy telkén lehetne cargozás(elféren,mivel ki lehet ásni,256 blokkig
megy), csak adott mennyiségű cargo lehet egy telken. És egy cargozott terület addott körzetében nem lehet másik cargo rendszer. Nehéz megoldani, de tökéletes megoldás lenne.

**Comment by KingDeadZ** [comment]
![image](https://user-images.githubusercontent.com/38157910/102695864-5e1dc100-422a-11eb-9b5a-d1e6a0801a38.png)
![image](https://user-images.githubusercontent.com/38157910/102695888-873e5180-422a-11eb-9831-ed586d2536e9.png)

**Comment by KingDeadZ** [comment]
![image](https://user-images.githubusercontent.com/38157910/102695892-945b4080-422a-11eb-88ba-1f5b9d0acdec.png)
![image](https://user-images.githubusercontent.com/38157910/102695896-9cb37b80-422a-11eb-9238-253b5bba0e3f.png)

**Comment by UDPSendToFailed** [comment]
Első kép úgy, hogy be van kötve a szelektáló (2db duplaláda, 10db input whitelisttel, 2db output), második úgy, hogy nincs. Alig van pár gép a telkemen, és ekkora laggot okoz, szerintem valami nem jó a cargonál.

**Comment by maryhonaly** [comment]
Mi is gondolkoztunk ezeknek a limitálásán, de valahogy nehezen kivitelezhetőnek tűnik. Másból se állna a napunk, csak a cargo meg a mindenféle humbuk eszközöket keresnénk, és ha igaz az iménti komment, akkor 10-15 is már soknak számít. 
Nem kell ezeknek olyan sok hely, egy telek is bőven elég egy lagg gyár építéséhez. 
Kíváncsi vagyok, hogy van-e esetleg még valakinek valami ötlete, én személy szerint a letiltásra vagy a kivételre szavaznék. Sokaknak nem tetszene, sokaknak viszont javulna a játékélmény.

**Comment by andris155** [comment]
@maryhonaly és ki fog arról dönteni végül, hogy mi lesz?

**Comment by KingDeadZ** [comment]
a whitelist okozta kernel telkén a laggot, többször is néztük, hogy leütötte a dust szortírozók alól a connectort, normálisabb volt az sf timings, aztán visszarakta és instant tps drop + sf timings is eléggé megugrott

**Comment by Ziredus** [comment]
Öszintén még mindig az van, hogy pár megalomániás miatt szív az összes player, szív az összes normális SF-es. Hányszor megmondtam, hogy felesleges kivenni az Advanced Outputokat is, mert a lagg megmarad, csak átalakul és nem megoldás! Tessék igazam lett. Most megint agyaltok valami kivételén, ami ugyancsak nem lesz megoldás, csupán mással lesz generálva a lagg. Cargo nélkül meg az SF 75% kukázva lenne gyakorlatilag. Azt kéne belátni, hogy a tiltások, meg itemkivételek helyett azt a pár playert kéne megfogni akik nem képesek ésszerü méretekben késziteni gyárakat.
A cargo manager kiütése nettó hülyeség. Nekem 8 reaktorom sülne be ha kiütném a managereket. Ráadásul mire kiütném az összeset addigra lazán elmenne egy fél napom (Innen is köszönöm, hogy nincs advanced output).
Irtózatosan egyszerű a megoldás még mindig a témára. Fogjátok meg azokat akik miatt leesik a TPS + Bolt közelébe ne lehessen gyár és pont.

**Comment by andris155** [comment]
Pár dolgot állítottam a cargo-n így talán nem okoz akkora gondot.
A hálózat nagyságát 200-ról 150-re állítottam. Ez még szerintem minden általános dologra elég. Aki ennél nagyobb hálózatot akarna inkább ne építse meg gondolva a többi játékosra.
A cargo-ticker-delay-t pedig 0-ról 1-re állítottam. Ezt a Slimefun hivatalos optimalizálásos oldalán ajánlották. Azt írták, hogy az 1 az ajánlott beállítás hozzá, de ennél nagyobbra nem érdemes növelni csak ha tényleg muszáj.
Ez utóbbi lehet megtörhet dolgokat, amikhez kisebb átalakítások kellenek, de viszont ha ez megoldja a szerver laggot szerintem ennyit megér mindenképpen.

**Comment by andris155** [comment]
Növeltem még eggyel cargo-ticker-delay-t. Meg visszaengedélyeztem az advanced output-ot, mivel 0 értelme van tiltani. Filter-t akkor is használ mindenki ha tiltva van, csak még nehezebben lehet megoldani a dolgokat és még talán több filter-t is használtak így...
A lagnak így meg kell szűnnie.
