### ISSUE TITLE
Átváltozó androidok

### ISSUE THREAD

**Issue by ketezerhat** [TheOld-Crafters/Minecraft-servers#4251]
**Szerver**: sav, lehet, hogy survivalon is jelen van a hiba de ezt nem tudom biztosra

 Az androidjaim (minerek) elkezdtek vissza változni sima fejjé, most a 3. változott át és nem tudom mi tévő legyek, nem tudom őket megnyitni se semmi egyet meg ki is szedtem de az meg sima fej lett... nem tudom, hogy mi lehet a probléma mert üzemanyag volt, interfacek is ötletem sincsen. Ez egy elég irritáló probléma, ha megáll egy android több hibát is okoz. Kérlek javítsátok a hibát, ha lehet :D (az androidjaimat meg majd szeretném vissza kérni, 2 empowered miner, 1 sima miner) Előre is köszi!

**Comment by maryhonaly** [comment]
Régi hiba, az okát én személy szerint nem tudom, viszont napközben nyugodtan noszogass, hogy cseréljem ki neked őket.

**Comment by andris155** [comment]
Erre sajnos nincs megoldás továbbra sem.
