### ISSUE TITLE
Hibás HG!

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4252]
**Szerver**:Szurvi

ma eddig 3hg volt egymás után, de egyiknél se írt nyertest, ki se dobta őket az aréna. ha egy ember maradt, kilépett és kész.
a /hg listgames is mind a 3 arénát úgy jelzi, hogy még megy, csatlakozni se lehet rá

+1: a felderítőbot se működik

**Comment by MrZero1** [comment]
Nem jó, tanúja voltam. Lemegy a meccs, a 2 ember bent marad, a cuccaik eltűnnek. Tegnap este jó volt, több HG event volt.

**Comment by MrZero1** [comment]
Reload-oltam, semmi. A nyertes bent marad, az egyik játékosnak eltűnt a cucca mikor meghalt és kirakta a játék.

**Comment by MrZero1** [comment]
Most volt 2 tesztkör, úgy érzékeli, hogy 1-1 ember bent van még az arénában, de nincs. 
![kép](https://user-images.githubusercontent.com/29709854/102716380-da241180-42db-11eb-940f-13629352d87c.png)

**Comment by andris155** [comment]
Holnap jónak kellene lennie. Sajnos újraindítás kell hozzá úgyhogy addig nem elérhető.
