### ISSUE TITLE
Spam védelem

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4253]
**Szerver**: Mindenhol

Annyi spamert látni, lehet mégis jobb lenne az a spam védelem ami volt, mert szerintem a sok spamer rosszabb

**Comment by KingDeadZ** [comment]
Ha beállítható, akkor szerintem a 2. ugyan olyan szöveget még engedje kiírni, de a 3.at már ne.

**Comment by Tomi321** [comment]
Amit KingDead írt az szerintem jó lenne, csak nem több óráig nem engedné kiírni, hanem mondjuk 15 percig

**Comment by andris155** [comment]
Nincs benne ilyen opció. Talán az új ChatControl Red-ben majd. Addig én ezt a megoldást túl szigorúnak tartom így. Az összes köszönés is egy óriási lista és biztosan vannak még olyan dolgok amiket többször írnak egymás utána az emberek és nem azért mert spam-elni akarnak vele.
