### ISSUE TITLE
Profitshopok Savszigeten

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4254]
**Szerver**:Savsziget

Savszigeten is kezdenek szépen lassan gyűlni a profitshopok, főleg ércekkel és dustokkal. Szerintem még most be kéne tiltani őket, hogy ne legyen hamarosan olyan a helyzet mint survivalon volt a tiltás előtt. Ha kell, akkor szívesen írok példákat is.

**Comment by andris155** [comment]
@MrZero1 ott se lehessen eladni ezeket?

**Comment by Tomi321** [comment]
Szerintem az nem lenne jó megoldás, inkább csak simán ellenőriztetni kéne a segítőkkel a hírdetett boltokat, és rászólni az adott játékosokra, hogy nem kéne ilyet csinálni, és ha nem törlik ki a profitshopjukat akkor staff törli, és büntetést kap a játékos

**Comment by Tomi321** [comment]
Az, hogy az érceket kivenni a boltból, amikből a szerver 80%-a tisztességesen androidokkal gazdagodik meg szerintem nem a legjobb megoldás

**Comment by andris155** [comment]
A staffoknak így is van rengeteg dolguk a szerveren. Nem fogják még azt is nézni, hogy kinek milyen farmja van...

**Comment by Tomi321** [comment]
Az, hogy kivenni a shopból, vagy csökkenteni az árukat szerintem semmiképpen nem lenne jó, mivel nagyon sok játékos kárára menne a dolog. Ha kell én szívesen megnézem a boltokat amikor meghírdetik őket, és írok derpynek esetleg, hogy ha feljön szóljon az illetőnek. Nem lenne nagy feladat, naponta max 4-5  külömböző boltot hírdetnek savon.

**Comment by MrZero1** [comment]
Csökkenteni vagy a mennyiséget növelni kellene szerintem.

**Comment by andris155** [comment]
Ha megírod pontosan mit változtassak rajta, akkor szívesen beállítom.
