### ISSUE TITLE
Automata fly kikapcsolás levédéseken

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4255]
**Szerver**: Túlélő

Repülés közben ha egy levédésre érsz, akkor egyből kikapcsolja a fly-t
A legjobb, hogy a saját levédésem parcellái közt is kikapcsolja :)

**Comment by andris155** [comment]
Nem sikerült ezt a hibát reprodukálnom. Nem kapcsolja ki a levédésen a fly-t nekem.

**Comment by skrisz0101** [comment]
Ja, elfelejtettem írni hogy azóta már megjavult
