### ISSUE TITLE
Survival telek aukciók

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4256]
Szerver: Túlélő

Az olyan playerek telkeit, akik már 1-1.5 éve nem voltak fent, ki lehetne rakni aukcióra pár 100k-ért attól függően, hogy mi van rajtuk. Csak egy price flag-et kell rátenni, és bekerül a telek a /p list forsale listába.

**Comment by MrZero1** [comment]
Ha van rá mód, hogy ne keljen repkedni meg megnézni, a tulaj mikor volt fent, nekem jó.

**Comment by andris155** [comment]
Létezik rá fizetős plugin, de kb. 1 vagy 2 szerveren fut. Lehetnek benne hibák és nem tudni a fejlesztő meddig fejleszti. Sajnos ezt így nem tudjuk megoldani, hogy automatikus legyen.
