### ISSUE TITLE
Csónak

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4257]
**Szerver**: Valószínűleg az összes, de lehet a Slimefun okozta lag miatt ilyen.

![kép](https://user-images.githubusercontent.com/29709854/102789002-c93ed300-43a3-11eb-8098-b45fc9d412bf.png)

Ha valaki csónakot akar használni, akkor kidobja belőle. Kívülről úgy néz ki, hogy egy helyben evez. Biztos volt jelentve.

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a hibát. Lehet, hogy ha kevés a TPS a Slimefun miatt akkor van ez a hiba.

**Comment by skrisz0101** [comment]
Nem Tps miatt.
sose jó a csónak

**Comment by andris155** [comment]
Érdekes módon nekem hibátlanul működött. 15 ms ping-gel és 20 TPS-sel teszteltem.

**Comment by MrZero1** [comment]
Nekem is jó volt, de a játékosoknak nem.

**Comment by andris155** [comment]
Old ranggal teszteltem túlélő módban.

**Comment by andris155** [comment]
Megtaláltam mi okozta a hibát és javítottam.
