### ISSUE TITLE
PvP védelem után megkapjuk az összesített fall damaget

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4258]
**Szerver**: Túlélő

Amíg egy HG meccs közben PvP védelem alatt állunk, és Fall Damaget szerzünk azt a PvP védelem után összesítve megkapjuk.

**Comment by Jaffis** [comment]
Lehetséges a javítása, vagy mindenképpen a plugin tulajdonosával kell felvenni a kapcsolatot?

**Comment by andris155** [comment]
Nekem ezt a hibát nem sikerült reprodukálnom.

**Comment by andris155** [comment]
Sikerült mégis rájönni mi okozza. Egy másik plugin. Ideiglenesen állítottam be rá megoldást.

**Comment by andris155** [comment]
508 OCD
