### ISSUE TITLE
Ha a soulbound le van tiltva a világban, akkor is működik.

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4259]
Szerver: Túlélő (Tesztelve), Savsziget

Olyan helyen, ahol van soulbound rúna, rádobod például a mellesedre. Elmész olyan világba, ahol le van tiltva a soulbound rúna, meghalsz és újraspawnolsz a soulbound melleseddel.

A slimefun verziók nem tudása miatt írtam ide.

Hogy a jelentés gyorsabban menjen:

Steps to reproduce:
1. Get a soulbound item, like a chestplate and equip it.
2. Die in a world, that has soulbound rune disabled.
3. You will respawn with the soulbound item, despite the fact that it is disabled.

Excepted behavior: Soulbound items should drop on death, if it's disabled in the world.

**Comment by andris155** [comment]
Megírtam a fejlesztőnek. Annyira nem nagy hiba szerintem ez. Majd lehet lesz rá javítás egyszer.
Köszönjük a jelentést.
