### ISSUE TITLE
Pomabot a szerverre

### ISSUE THREAD

**Issue by DiamondGamer321** [TheOld-Crafters/Minecraft-servers#4260]
Szerver: Túlélő

Pomabot a szerverre is! Fun! Jej!

**Comment by KingDeadZ** [comment]
Ennek mi értelme lenne?

**Comment by DiamondGamer321** [comment]
Poma a túlélés fő eleme! :)

**Comment by MrZero1** [comment]
Szerintem ígyis elég sok minden van már bent. (100+ plugin.)

**Comment by poma123** [comment]
Definitely not.
