### ISSUE TITLE
Vanish jog Old rangosoknak

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4261]
Elég irritáló, mikor felmegy az ember, és 5-en írnak 10 féle problémával, ilyenkor jól jönne a vanish. Staffok ugyanúgy látnák, ha fent van egy Old, de a playerek elől el lehetne tűnni tabról.

**Comment by MrZero1** [comment]
Nem gondolom, hogy ilyen jog kellene a játékosoknak.

**Comment by andris155** [comment]
> Nem gondolom, hogy ilyen jog kellene a játékosoknak.

Ahogy én sem.
