### ISSUE TITLE
/bolt

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4262]
**Szerver**: Szurvi, sav, (építész?)

Eléggé össze-vissza vannak a /bolt-nál a kategóriák, nem lehetne esetleg úgy hogy a gui-ban 4 lehetőség (szurvi, sav, építész, oldspace) és  azon bellül felsorolni a cuccokat?

mondjuk lehet ez inkább fejlesztési ötletnek ment volna, na mindegy

**Comment by andris155** [comment]
Nincs benne ilyen beállítási lehetőség.
