### ISSUE TITLE
Slimefun - LiteXpansion

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4263]
**Szerver**: szurvi, sav

![2020-12-23_12 55 01](https://user-images.githubusercontent.com/29951969/102993829-2ced0b80-451e-11eb-8047-755bb94bd873.png)
![2020-12-23_12 55 02](https://user-images.githubusercontent.com/29951969/102993837-30809280-451e-11eb-9745-7a26e4de7edf.png)
![2020-12-23_12 55 06](https://user-images.githubusercontent.com/29951969/102993842-324a5600-451e-11eb-88f1-d103eadaf294.png)

hibás a recept. nem copper ingotból lehet craftolni, hanem copper item casingból (vagyis abból kéne, de perpill sehogy se lehet craftolni) 
Többi hasonló receptnél is mind a ,,casing"-ból kell ilyet craftolni, ennél hibás csak

**Comment by UDPSendToFailed** [comment]
#4105

**Comment by skrisz0101** [comment]
leírás több infót ad, de ha nem megy, megmutatom a szerón (andris)

**Comment by andris155** [comment]
Nekem még mindig jól írja.
<img width="331" alt="Capture5" src="https://user-images.githubusercontent.com/8324198/103095731-f8528000-4601-11eb-9c06-5deb209a51ae.PNG">
<img width="437" alt="Capture" src="https://user-images.githubusercontent.com/8324198/103095735-fab4da00-4601-11eb-82e2-49547ffc1a67.PNG">

**Comment by andris155** [comment]
Nekem sikerült craft-olni is a szerveren.

**Comment by skrisz0101** [comment]
Akkor ezt is javították azóta xd
