### ISSUE TITLE
pénzért we, mert miért ne

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4264]
**Szerver**: Szurvi
 

Régen is volt ilyen, de kikerült egy ideje a szar we miatt, de most van újra :C
Szerintem lehetne ilyen fix árakkal blokk számra, ha nem farmot akar az illető csinálni

Pl én is hasznát venném házak csinálásához a városba <3 (semmi önző cél, csak egy kicsit)

**Comment by MrZero1** [comment]
Hát, végülis lehet, mint régen. De erről az adminokkal kell egyeztetni, hogy ők mit szólnak. Ha lesz is, nem lesz olcsó mulatság. 🎅

**Comment by Kelvin172** [comment]
Akik nagy mennyiségben keresnek pénzt azoknak nem lesz nehéz :V

**Comment by skrisz0101** [comment]
de azért ne rám legyen szabva xd

**Comment by MrZero1** [comment]
Egyelőre nem lesz, ez megint csak annak könnyebbség, akinek sok pénze van.

**Comment by skrisz0101** [comment]
szerintem nem 2 embernek van minimum 1 milliója, kezdő meg úgyse we-ztetne

**Comment by andris155** [comment]
Szerintem olvasd el jobban, amit MrZero írt. :D

**Comment by skrisz0101** [comment]
elolvastam, nem változott a vélemény :v
