### ISSUE TITLE
Hibás szöveg némításnál

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4269]
**Szerver**:Összes

![unknown-13.png](https://user-images.githubusercontent.com/69621187/103178822-ba19c280-4886-11eb-8630-c291e671671d.png)

Hibás a muteolásnál a szöveg. 
Legalábbis nem helyes. 

[DrBlade/Tetrix/Shryx_ fedezte fel]

**Comment by mangoshell** [comment]
Egy t a Tetrix, de amúgy hibátlan

**Comment by Jaffis** [comment]
Sorry, átírtam.

**Comment by andris155** [comment]
Holnap már jól kellene majd írnia.
