### ISSUE TITLE
McMMO növénytan hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4270]
![image](https://user-images.githubusercontent.com/16057404/103208944-1c63d900-4902-11eb-91b3-25299b66b10e.png)

Elvileg 100% esély lenne rá, hogy visszaültesse a kiütött növényeket a szerencse perk miatt, de ez valamiért nem működik, csak ~80%-ban, mintha nem lenne jog a perk-re.

**Comment by lovi-dev** [comment]
1000+ szintnél répa/búza esetén tudom mondani:  csak akkor ültei vissza, ha van az invedben "vetőmag" hozzá. Akkor viszont 100%ba visszaülteti.

**Comment by UDPSendToFailed** [comment]
Tele volt az invem répával, de a szerencse perk hatása nem érvényesül, hiába lenne azzal 100%, nem ültet vissza mindent.

**Comment by andris155** [comment]
1000+ szinttel valóban működik. A perk-re megvan adva a jog. Jog nélkül nem írná sárgán ott zárójelben, hogy mennyi lucky perk-kel az esély. Ez úgy tűnik az mcMMO plugin hibája.

**Comment by andris155** [comment]
Az mcMMO talán majd javítja. Sajnos eléggé elvannak maradva a javításokkal és fejlesztésekkel.
