### ISSUE TITLE
Sf - Jerky húsok

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4271]
**Szerver**: Szurvi, sav

A ,,jerky" húsok nem adnak több kajacsíkot mint a simák, pedig kéne elvileg.

**Comment by andris155** [comment]
https://github.com/Slimefun/Slimefun4/issues/2668
Nem nagyon értem hogy kellene működnie, de elvileg akkor több food level-t nem regenerál.

**Comment by andris155** [comment]
A saturation mint effekt pedig food level-t regenerál. Tehát nem értem. Írhatsz issue-hez, ha gondolod de én így erre nem tudok mit mondani.

**Comment by andris155** [comment]
,,foodSaturationLevel: The player's current saturation level, which determines how fast the hunger level depletes and is controlled by the kinds of food the player has eaten. Its maximum value always equals foodLevel's value and decreases with the hunger level. Its initial value on world creation is 5."
Elvileg ezt módosítja.

**Comment by skrisz0101** [comment]
Hát, okosabb nem lettem,, de akkor ez nem hiba xd

**Comment by KingDeadZ** [comment]
Saturation: Az a kajacsík, amit nem látsz, de jelen van. Mindennek van egy saturation értéke. 
Ez mire jó? 10kajacsíkod van, 1 életed. Nem fogsz gyorsan regenerálódni, de ha van saturationod, akkor igen. Úgy lehetne rá gondolni, mint egy 2. kajacsík, amit nem látsz.
