### ISSUE TITLE
Survival - Jobs

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4272]
Leírom ide is, újra, érthetően. 

-----------------------------------------------

Nagy SF gyárak -> lag
Nincs semmi értelmes pénzszerzési lehetőség -> épülnek a SF gyárak, hogy egy itemet lehessen millió számra gyártani, és legyen belőle pénz -> lag
Nincs semmi értelmes pénzszerzési lehetőség -> az új játékosok is SF gyárakat fognak építeni -> lag
Lag -> hiszti -> egyszerűen gyártható tárgyak bolti tábláinak leütése -> még több gép a nehezebb craftokhoz -> még nagyobb lag
Lag -> még több hiszti -> #3881-hez és #4236-hoz hasonló jelentések -> SF gyárasok megunják -> támogatók és játékosok számának csökkenése

-----------------------------------------------

Jobs normális fizetésekkel + csökkentett eladási árak boltban -> kevesebb AFK player -> kevesebb SF gyár -> kevesebb lag -> kevesebb hiszti -> több támogató és játékos

-----------------------------------------------

TL;DR: 

Nem a farmolási lehetőséget kell megszüntetni, a játékok 99%-ának az a célja, hogy jobb legyél a többieknél, vagy baltopon, vagy killekben, vagy nagyobb és szebb házakkal, etc etc.
Elég lenne átalakítani a farmolási opciókat egy lag mentes megoldásra, és nem lenne semmi probléma. SF gyárak ugyanúgy működnének tovább, de mivel nem sok pénzt adna, közel sem lennének ekkorák, esetleg egy kis kiegészítésnek maradnának meg a Jobs mellé.
Jelenleg ha feljön random Pistike, azt látja, hogy a profitbolt és a SF éri meg, tehát ő is ezt fogja csinálni. Viszont ha Pistike azt látja, hogy bányászni vagy fát vágni érdemes, mert sokkal többet fizet, mint az SF gyár, abba fog belekezdeni.

**Comment by andris155** [comment]
Továbbra is nem. Most már ki kell majd szedni dolgokat nem pedig berakni ha majd változtatni akarunk.

**Comment by skrisz0101** [comment]
kettő együtt nem lehetne? elég észszerű amit kernel írt

**Comment by UDPSendToFailed** [comment]
A staffoknak admintól felfelé kéne pár napot játszani a szerveren új playerként, tagként, egyből mindenki értené a problémát.

**Comment by Sanszi** [comment]
Így, hogy állítva lett az sf-en is nagyon ugrál a tps, kevesebb plugin kell. Az sf is sok sebből vérzik, nem csak a cargo inputok számától függ a lagg nagysága, hanem a round robin üresen futása is nagyon húzza le a tps-t pl. Lehet nem így van, de szerintem azért 25-30 playernél nem kellene 12-18 közt ugrálnia a tpsnek (néhány másodpercenként változik kb.). Átnézni a pluginokat, ami felesleges kirostálni, az sf-et talán meg lehetne menteni a kivételtől erős korlátozásokkal (pl mint a hoppernél, csak szerintem fejenként kellene megadni mennyi cargo managert, input nodeot használhat valaki, nem pedig chunkonként)
Miután kevesebb plugin van, a jobs reborn azért lehetne jó, mert nem afkolva keresnének az emberek pénzt, lehet konfigolni minden pénzbevételt, pénznövekedést, xp szerzés sebességét. Nem lenne olyan imba. mint amilyen az sf most.

**Comment by lovi-dev** [comment]
" andris155 closed this 5 hours ago"
 van még így értelme ide írni?

**Comment by skrisz0101** [comment]
igen, mert van olyan hogy újranyitás

**Comment by MrZero1** [comment]
> A staffoknak admintól felfelé kéne pár napot játszani a szerveren új playerként, tagként, egyből mindenki értené a problémát.

Admintól felfelé is tudjuk, hogy szar a helyzet, anélkül, hogy játszanánk. Nem kell hülyének nézni.

**Comment by skrisz0101** [comment]
@lovi-dev

**Comment by UDPSendToFailed** [comment]
> Admintól felfelé is tudjuk, hogy szar a helyzet, anélkül, hogy játszanánk. Nem kell hülyének nézni.

Ezt inkább a tábla leütögetésre írtam, mert abból csak az lesz, hogy még nagyobbak lesznek a gyárak. Ha lenne például zúzottkő eladás jó áron, az megoldható lenne 1x50 géppel, az üsthöz pedig kellett legalább 4-5 lépés, tehát 4-5x50 gép.

**Comment by skrisz0101** [comment]
ha meg egy az lenne, akkor az 1x50 gép lenne sokszor :D

**Comment by MrZero1** [comment]
Milyen bugok, hibák vannak jelenleg? @Sanszi

**Comment by Sanszi** [comment]
> Milyen bugok, hibák vannak jelenleg? @Sanszi

https://github.com/Zrips/Jobs/issues/1012 ez a végtelen pénz bug, ez a legkritikusabb.
https://github.com/Zrips/Jobs/issues/518  ha kiírja az mcmmo antiafkhalászata, hogy túlhalászott a terület akkor is ad a jobs pénzt és xpt. Ez is kritikus. (Mégsem javították)
Ezeket elég könnyen lehet letiltással orvosolni.
A többi elég jelentéktelennek tűnik. (Ettől függetlenül át kéne szerintem nézni pomának és Andrisnak, vagy mintkettőjüknek)

**Comment by UDPSendToFailed** [comment]
Inkább írom ide is, bányászat munka tiltása nem lenne valami jó, szerintem az érc lerakást kéne offolni, amíg nem javítják. Kemencében továbbra is ki lehet égetni, amit gyengéd érintéssel ütnek ki.
AFK halászat pedig alapból is tilos, és ban jár érte, mert segédprogram, mint az xray.

**Comment by Sanszi** [comment]
Nem látom rá a módot, hogy ezt javítani lehetne. xd November 30-óta semmit nem csináltak ezzel.

**Comment by montlikadani** [comment]
> [Zrips/Jobs#1012](https://github.com/Zrips/Jobs/issues/1012) ez a végtelen pénz bug, kritikus hiba.

Ezt valószínűleg nem is fogjuk, mivel a megoldás már meg van válaszolva, de sok mindenki ignorálja a választ, nem érdekli és csak a javításra vágyik. A megoldás ennyi: https://github.com/Zrips/Jobs/issues/1012#issuecomment-747409864

Egyszerűen csak hozzá kell adni azokat a blokkokat a restrictedblocks.yml fájlhoz, amelyekkel a játékosok tudnak "végtelen" féle pénz szerzést alkalmazni. Például vegyük azt, hogy van egy vas érc egy játékosnál és azzal tud pénzt szerezni folyamatosan, most hozzáadjuk az `IRON_ORE` a fájlhoz és egy meghatározott időt, például, 60, tehát 1 percre.

Egyébként is, ha ezt csak javítással kellene megoldani, nos memória problémák adódhatnak és valószínűleg TPS csökkenéssel jár.

**Comment by UDPSendToFailed** [comment]
Nekem amúgy saját szerveren reprodukálni sem sikerült teljesen alap beállításokon, más játékos által lerakott ércekért nem adott pénzt.

**Comment by Sanszi** [comment]
Ahogy Zrips írta "enyhíteni" lehet a problémát, megoldás nincs rá, szóval nem ignorálva lett a válasz, csupán nem vettem megoldásnak. Mindenesetre köszönöm, hogy írtál ide, az amit UDPSendToFailed írt fix, együtt teszteltük és nem tudtuk reprodukálni a bugot, az egymásnak lerakott ércekért nem kaptunk se pénzt sem pedig xpt.

**Comment by andris155** [comment]
Szerintem belehet rakni a Jobs-ot. De be kellene állítani valakinek/valakiknek megfelelően a szerverhez. Ha esetleg laggot okozna akkor maximum kikerül vagy optimalizál rajta a fejlesztő.

**Comment by andris155** [comment]
De egyébként a lag probléma már megoldásra került azóta.

**Comment by Sanszi** [comment]
> Szerintem belehet rakni a Jobs-ot. De be kellene állítani valakinek/valakiknek megfelelően a szerverhez. Ha esetleg laggot okozna akkor maximum kikerül vagy optimalizál rajta a fejlesztő.

Ha rámondja az igent az a réteg, akinek ebbe van beleszólása, bekerülhetne a teszt szerverre. Utána csak meg kellene bízni egy csapatot aki beállítja, meg teszteli.

**Comment by andris155** [comment]
Már bent van a teszt szerveren. :D

**Comment by Sanszi** [comment]
> Már bent van a teszt szerveren. :D

Dejó! :) Akkor már csak a 2. mondatom érvényes.

**Comment by lovi-dev** [comment]
...és lassan vége a februárnak is...

**Comment by UDPSendToFailed** [comment]
Egy hónapja elkészült a beállítása, a küldetések is 2 hete, már csak az adminokra vár.

**Comment by andris155** [comment]
Bekerült.

**Comment by andris155** [comment]
Az eddigi tesztjeim alapján elég durván eszi a memóriát a Jobs, gondolom mivel a RAM-ban tárolja a lerakott blokkok védelmét. Szerintem ha átírnám a memóriát 100 GB-ra, akkor sem lenne elég a Jobs-hoz így. Nem tudom mi legyen. Jobs nélkül most a plusz hozzáadott RAM-mal úgy tűnik rendben van a szerver. Mindenképpen kell még hozzá majd a RAM bővítés hogy 100%-ban tökéletesen legyen, de így a Jobs-al nem tudom mi legyen.
