### ISSUE TITLE
Tiltott játékos levédésen

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4273]
**Szerver**:Szurvi

Ha valakit kitiltanak a levédésről, be tud menni a levédésre.
Módszer: Határon állsz és futsz ugrasz egyszerre

**Comment by mangoshell** [comment]
Szerintem véletlen történt, mert nekem nem sikerült

**Comment by skrisz0101** [comment]
próbáld újra :D

**Comment by andris155** [comment]
A fejlesztő szerintem nem igazán tud ezzel mit kezdeni. Remélhetőleg a jövőben javításra kerül majd.

**Comment by andris155** [comment]
508 OCD
