### ISSUE TITLE
Survival - Ender Dragon drop

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4274]
Az Ender Dragon nem dob semmit halálkor, se fejet, se tojást, se XP szintet.

**Comment by skrisz0101** [comment]
esetleg lehetne tiltani a godot, flyt a sima endben a sárkánynál és akk dobhatna valami értékesebb droppot is

**Comment by andris155** [comment]
Mivel másoknak nem tetszik a fly tiltás megoldás én sem akarom ezt erőltetni.

**Comment by andris155** [comment]
Tojást csak egyszer ad, amikor az első sárkányt megölik. XP-t szerintem kell adnia de csak egy gömböt mivel egyesíti a Spigot ezeket. De szintben ugyanannyinak kell lennie mintha többet adna.

**Comment by UDPSendToFailed** [comment]
Régebben a crystal-ból spawnoltak is dobtak tojást vagy fejet, ez már nem megoldható? :/ Így kb értelmetlen megölni, semmi jót nem ad.

**Comment by skrisz0101** [comment]
mintha olyan sok ember flyolgatna a sárkánynál.. :v

**Comment by andris155** [comment]
Megcsináltam, hogy minden sárkány megölésekor rakjon le tojást.
