### ISSUE TITLE
HG

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4275]
**Szerver**: Survival

Meglehet-e oldani, hogy HG-ra üres invvel lehessen csak csatlakozni?
Folyton eltűnnek a cuccai embereknek, főleg az Old eszközök. :)

**Comment by skrisz0101** [comment]
:(

**Comment by KingDeadZ** [comment]
Ha vége a hg meccsnek, akkor a tps is ledroppol azért eléggé, meg általában ha megölnek valakit hg közben akkor is érződik egy kissebb lag.

**Comment by MrZero1** [comment]
Illetve azt is hallottam, hogy több embernél megmaradnak a HG-s cuccok ha vége van.

**Comment by andris155** [comment]
Megírtam a fejlesztőnek mindkét dolgot. Ha megvalósítja, akkor beállítom. Addig ezen sajnos nem tudok változtatni.

**Comment by andris155** [comment]
Sajnos optimalizálni nem lehet rajta. Ha véget ér egy HungerGames játék, akkor viszonylag sok dolog történik. Ez a sok dolog mivel rengeteg plugin-t használunk kicsit lassabban is fut le alapból mint kellene.
Kevesebb plugin-nal talán kicsit jobban működne, de optimalizálni a HungerGames részén nem lehet. Esetleg, ha bekerül, hogy csak üres inventory-val lehessen belépni, akkor annyival kevesebb lesz, hogy nem kell az inventory-ban található tárgyakat visszaállítani, amikor véget ér a játék.
