### ISSUE TITLE
Cenzúra

### ISSUE THREAD

**Issue by marcika1290** [TheOld-Crafters/Minecraft-servers#4277]
**Szerver**: Survival

Kellene egy olyan parancs a szerverre amivel ki/be lehetne kapcsolni a cenzúrát saját magadnak

**Comment by MrZero1** [comment]
Persze, aztán mindenki kikapcsolja magának.. 😃

**Comment by andris155** [comment]
Ilyen lehetőség nem lesz.

**Comment by UDPSendToFailed** [comment]
Erre jó a partychat, ott nem szólhatnak érte.
