### ISSUE TITLE
Survival - Plot alias teleport hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4279]
Telkeknél a /p sethome paranccsal be lehet állítani, hová rakjon teleportáláskor. Ez a /p h-nál működik is, de ha adok a teleknek egy nevet a /p alias-sal, és arra teleportálok, például /p h asd, nem a beállított sethome-ra rak, hanem az alap helyre a telek elé. 

Ez nagyobb telkeknél elég zavaró, vagy be kell írnom, hogy /p h 12, vagy ha a rövidebb parancsot választom alias-sal, át kell repülnöm 4 teleknyi távolságból a másik végébe, ahová a home-nak raknia kéne.

**Comment by andris155** [comment]
Nincs benne elvileg ilyen lehetőség. Csak azt tudod beállítani, hogy hova teleportáljon. Home név megadásról sehol sem írnak.

**Comment by UDPSendToFailed** [comment]
Nem home név, teleknév. Be lehet állítani a szám mellé nevet is, például /p alias asd, aztán /p h asd. A számos megoldásnál (/p h 12) a home-ra rak, a névnél (/p h asd) a telek mellé az alap helyre.

**Comment by andris155** [comment]
Nekem hibátlanul működik. Oda rak akkor is ahova beállítottam a home-ot ha alias-t használok hozzá.

**Comment by UDPSendToFailed** [comment]
https://youtu.be/lDve1D_Z7YY

Valami az összekapcsolt telkeknél bugol szerintem xd
