### ISSUE TITLE
Adolás,Bug

### ISSUE THREAD

**Issue by Goldie2000** [TheOld-Crafters/Minecraft-servers#4282]
**

**Azt szeretném mondani hogy, találtam egy bugot/addolást!**

**Lényeg:** _Ha Creativban Csinálok Egy Boltot ládára és ha elírok valamit, akkor kidobja a táblát és azt végtelenségig lehet csinálni. És ha átlépek Survivalba akkor meg kapom!_

**Köszönettel:** **_Goldie2000_**

**Comment by Sizarra** [comment]
Ezt már jelentették párszor.

**Comment by UDPSendToFailed** [comment]
#3540 
#3489 
#1861 
#4185
#3311 
#2945 
#2874
#2649
#2364
#2316
#1418
#747

**Comment by andris155** [comment]
Ezt sajnos nem tudom javítani. Nem akarom tiltani a táblát is kreatívban.
