### ISSUE TITLE
mobspawn flag / biome flag bug?

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4283]
**Szerver**: Szurvi

Levédésen bellül csináltam egy parcellát, beállítottam neki a meleg tenger biomet és engedélyeztem a mobspawnt. Minden spawnol bele, csak hal nem. (tintahal, delfin, fulladt zombi, zombifalusi, csontváz)

**Comment by andris155** [comment]
Növelve lett a halak spawn limitjén. Olvasd el majd hozzá a wiki-n, hogy hol spawn-olnak pontosan. Elvileg kellene működnie.
