### ISSUE TITLE
multi tool 

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4284]
**Szerver**: Szurvi, sav?

ha sokat nyomom a wind staff módot multi toolban, akkor akár 1 perc után is visszarak a kezdéshelyre

**Comment by andris155** [comment]
Erre a megoldás, hogy ne nyomkodd sokat. Ha belerepülsz egy nem betöltött chunk-ba akkor visszadob, meg szerintem ha már kicsit nagyobb a pinged vagy nem stabil 20 a TPS akkor a cheat védelem plugin is gondolom visszadob.

**Comment by skrisz0101** [comment]
elrepülök, lerakok egy blokkot, visszarak. a blokk megmarad, szóval be van töltve
