### ISSUE TITLE
levédés - accestrust 

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4285]
**Szerver**: Szurvi

Accestrust paranccsal hozzá lehet adni az embereket kar, gomb, stb hozzáféréshez. Az olvasóállványban is tudnak könyveket olvasni. Jó lenne ha nem tudnák kivenni a könyvet, csak olvasni

**Comment by andris155** [comment]
Elvileg ha accestrust-al van hozzáadva akkor nem tudják kivenni.

**Comment by andris155** [comment]
accesstrust - tudják olvasni.
containertrust - tudják módosítani.

**Comment by andris155** [comment]
Teszteltem és accesstrust-al valóban nem lehet elvinni a könyvet.
