### ISSUE TITLE
Slimefun - Faragott tök tiltása Auto Enchanterben

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4286]
Faragott tökre lehet rakni bilincselés átka enchantot, és soulbound-ot, így aki felveszi, az kb nem tud tőle staff segítsége nélkül megszabadulni, mivel elkoptatni sem lehet. Egyedül a /ci ** paranccsal törölhető, de ezt szerintem nem sokan ismerik.

**Comment by andris155** [comment]
Sajnos nincs ilyen lehetőség a Slimefun-ban.
