### ISSUE TITLE
SlimeFun/Diet Cookie

### ISSUE THREAD

**Issue by Viking998** [TheOld-Crafters/Minecraft-servers#4287]
**Szerver**:Survival

SlimeFun dolgok között elkészíthető egy úgynevezett Diet Cookie nevű étel, ami minimálisan tölt vissza éhséget és kb 3 másodpercre elemel a talajtól. (Véleményem szerint teljesen értelmetlen/Nem éri meg az Elytra Scale pazarlását) Esetlegesen érdemes lenne teljesen kivenni a SlimeFun-ból, ha megoldható

**Comment by skrisz0101** [comment]
Ha te nem akarod használni, ne használd.
Kivenni felesleges

**Comment by MrZero1** [comment]
Szerintem is. Aki akarja használja, aki akarja nem. 
Lezárom ezt a jelentést.
