### ISSUE TITLE
Szabályváltoztatás javaslat 

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4288]
**Szerver**: Mindenhol

ha valaki Xrayezik, vagy valami kisebb ,,hack"-et használ, nem feltétlen kéne sztem örökre bannolni
Lehetne adni neki pár nap bant + és ha mégegyszer ilyet csinál, akkor örök. 
Nem rosszabb az, aki szerez 10 gyémántot Xray-el mint aki kirabol 2 házat és szerez kétszer annyit (ugye ő csak jailt kap, 
jogosan)

**Comment by maryhonaly** [comment]
Ebből következően, aki csak egy kis fly hacket használ se legyen gond, hiszen az oldok is tudnak repülni. 
Aki valami auto-clicker-aim dolgot használ se legyen gond, hisz Multons közel olyan jól céloz szabad kézzel, mert ügyes. 

Én teljes mértékben elutasítom. Aki bármi féle segédprogramot használ, az vállalja a felelősséget érte. Ha egyszer használta, következőre is fogja, csak jobban megválasztja majd az időpontot. 
Aki kirabol másokat, igaz, hogy csúnya tett, viszont jelentősen kisebb az értéke, mint annak, aki bármi külső alkalmazást telepít, és használja azt. Nem a 10 db meg a 3 stack dia érdekel minket, hanem a szándék.

**Comment by skrisz0101** [comment]
xray szándék: cuccokat szerezzen bányából
lopás szándék: cuccokat szerezzen másoktól
Fly hacket meg nem gondoltam idesorolni xd
Leginkább az Xray, auto clicker/afk farm dolgokra gondoltam

**Comment by UDPSendToFailed** [comment]
https://www.spigotmc.org/resources/orebfuscator.82710/

**Comment by KingDeadZ** [comment]
Autoclickerért max 3-4napot adnék, xrayért max 1hét, ha harmadjára kapnánk rajta ugyan azt az illetőt, akkor meg örök... A hackerek meg ugyan úgy örökbant kapnak

**Comment by andris155** [comment]
Van egy alapszintű x-ray védelem. Igen van komolyabb is, semmiképpen sem plugin formájában hanem a Paper fork részeként. De a komolyabbat teszteltük pár hónapig és nem igazán bírja sajnos el a szerver. Hihetetlenül sok erőforrást használ. Így az alapszintűt használjuk. Az alapszintűnél annyi a hátrány, hogy látni a barlangokat.

**Comment by andris155** [comment]
Az, hogy mivel büntetik azt a staffok döntik el. Mondjuk szerintem olyan óriási csalás ha látják a barlangokat. Az érceket amik nem barlangokban vannak azokat nem látják az x-rayel.

**Comment by andris155** [comment]
Az, hogy mivel büntetik azt a staffok döntik el. Mondjuk szerintem nem olyan óriási csalás ha látják a barlangokat. Az érceket amik nem barlangokban vannak azokat nem látják az x-rayel.

**Comment by andris155** [comment]
Az auto clickernek szerintem sok értelme nincs mióta az újabb PVP rendszer van.

**Comment by andris155** [comment]
A fly hack nem működik a szervereken.

**Comment by Jaffis** [comment]
> Az auto clickernek szerintem sok értelme nincs mióta az újabb PVP rendszer van.

(AFK farmolási lehetőség)

**Comment by MrZero1** [comment]
Az érceket csak látják, hisz nem egy embert kaptak el a staffok, úgy, hogy "bányásztak" az emberek.

**Comment by UDPSendToFailed** [comment]
Ha nem kapok érte bant, szívesen tesztelem az xray védelmet xdd

**Comment by andris155** [comment]
De hiába teszteled nem tudok rajta változtatni.

**Comment by KingDeadZ** [comment]
ha xrayezel, ugyan úgy látod a nem bányákban lévő érceket is, nem számít konkrétan semmit xd az autoclickerrel meg beülsz a mobfarmhoz, beállítod hogy üssön mondjuk 800msenként, és good to go
