### ISSUE TITLE
Mcmmo elért szint szöveg

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4289]
**Szerver**: Survival, gondolom sav is.

![kép](https://user-images.githubusercontent.com/29709854/104090437-0b5a8680-5277-11eb-9291-8fc3edf1c21b.png)

Mióta fent vagyok, azóta 2 embernél láttunk ilyet. Nagyon jó kis dolog, de az RGB-t nem kezeli(?)

**Comment by andris155** [comment]
Inkább letiltottam egyelőre ezt a funkciót. Holnaptól nem fogja írni.

**Comment by MrZero1** [comment]
Kár.

**Comment by MrZero1** [comment]
Igazából maradhatna, nem zavaró, hogy ilyen színesen írja ki a neveket.

**Comment by Sanszi** [comment]
Nem zavaró a nevek színe így sem.
