### ISSUE TITLE
Enderdragon tojás szerzés

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4291]
**Szerver**: Survival

Az Enderdragon halálakor ad tojást, viszont nem lehet megszerezni, mivel nem lehet rombolni.

**Comment by andris155** [comment]
@MrZero1 Legyen rombolható a sziget? Vagy mi legyen erre a megoldás?

**Comment by poma123** [comment]
Kell egy allow-block-break DRAGON_EGG flag a levédésre

**Comment by andris155** [comment]
De az semmit se ér. Az ender dragon tojást nem úgy kell kiszedni.

**Comment by andris155** [comment]
Majd szerintem beállítom, hogy dobja ki a tojást mint tárgy. Ne lerakja.

**Comment by poma123** [comment]
Hát jó

**Comment by MrZero1** [comment]
A sziget ne legyen rombolható semmiképpen.

**Comment by andris155** [comment]
![2021-01-12_16 20 28](https://user-images.githubusercontent.com/8324198/104334146-4e745e00-54f2-11eb-9d8b-efd1795415ec.png)
Beállítottam, hogy a halálkor dobjon tojást a sárlány.

**Comment by andris155** [comment]
Köszönjük a hibajelentést.

**Comment by maryhonaly** [comment]
Viszont a kis külön rg levédések, amik biztosították, hogy tojást lehessen letenni, mostmár nincsenek, nem engedi nekik letenni a kristályokat.
