### ISSUE TITLE
Karmazsin,torz fák fadöntés

### ISSUE THREAD

**Issue by Bazsaaaa** [TheOld-Crafters/Minecraft-servers#4292]
**Szerver**:Survival

 Favágásnál van a fadöntés skill (mcmmo) amit ha a netherben a torz és karmazsik fáknál használunk akkor szinte semmit nem ér mert túl közel spawnolnak a fák és mingíg azt írha hogy "ez a fa túl nagy". Nem tudom mit lehetne ezzel kezdeni de így használhatatlan ezeknél a fáknál

**Comment by andris155** [comment]
Szerver optimalizáció szempontból nem túl jó ha túl nagy részeket szed ez ki. Szerintem ez rendben van így, ahogy most van.

**Comment by andris155** [comment]
A fejlesztési javaslatot azért köszönjük.
