### ISSUE TITLE
Rg üzenetek

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4293]
**Szerver**: mindenhol

,,Sorry, but...." üzeneteket nem lehet helyettesíteni valamivel? nem minden nub érti 
pl:  itt nem üthetsz ki messzebb semmit, menj a retekbe innen

**Comment by mangoshell** [comment]
Szerintem csak te nem érted

**Comment by andris155** [comment]
A deny-message flag-gal tudnak beállítani adminok egyedi üzenetet, ha szeretnének valahova.
