### ISSUE TITLE
savsziget slimefun elevator plate hiba

### ISSUE THREAD

**Issue by ksricsi** [TheOld-Crafters/Minecraft-servers#4295]
**Szerver**: Savsziget

Nem tudok sokat írni róla :D A slimefunos Elevator Plate nem működik. Nem ír ki semmit és nem is csinál semmit amikor ráállunk. Persze 2 van egymás feletti emeleteken, ha 1 van kiírja, hogy nincs úticél, de kettőnél már semmit sem csinál.

**Comment by andris155** [comment]
Maga a könyv menü nem működött, mivel megváltozott a szerverfájlban az api hozzá. Elvileg már javították. Kérlek teszteld majd le újra.
