### ISSUE TITLE
Offline playernél növekszik a mute ideje

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4297]
![image](https://user-images.githubusercontent.com/16057404/104243316-abbfcf00-5460-11eb-8f1f-d0bcb4e8dc23.png)

**Comment by maryhonaly** [comment]
Valóban szebivagy12 esetén folyamat nő, most magamon teszteltem, offline voltam, amikor magamnak adtam a némítást, és nálam csökken. Nem vettem le szebiről, hogy utána lehessen nézni, hogy mi történik a háttérben

**Comment by andris155** [comment]
Csak a jail idő nem telik offline. Ez nem hiba.

**Comment by KingDeadZ** [comment]
De Andris, a játékosnak akiről a kép szól, annak növekedett a mute ideje, és ez hiba. @andris155

**Comment by maryhonaly** [comment]
Jelen percben már 18 óránál tart szebivagyok12

**Comment by andris155** [comment]
Fogalmam sincs mi okozza ezt.

**Comment by andris155** [comment]
Reprodukálni nem sikerült sajnos.

**Comment by UDPSendToFailed** [comment]
![image](https://user-images.githubusercontent.com/16057404/104337943-48807c00-54f6-11eb-90e5-8f238f319479.png)

Nem baj, maradhat rajta, megérdemli

**Comment by andris155** [comment]
A növekedő mute jó nagy büntetés az biztos. :D

**Comment by mangoshell** [comment]
Szerintem ez egy isteni ajándék

**Comment by MrZero1** [comment]
De akkor miért van lezárva ez, ha még fennáll a hiba?

**Comment by andris155** [comment]
Mert ha nem tudom reprodukálni nem tudok vele mit kezdeni. A fejlesztőnek úgy tudom megírni, ha letudom neki írni pontosan, hogy lehet reprodukálni a hibát.

**Comment by MrZero1** [comment]
Oké, de a hiba még létezik. Vagy már nem növekszik? Másnál is van ilyen?
