### ISSUE TITLE
Szerverek közti chat kihasználása némított játékosként

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4298]
**Szerver**:szurvi, sav, építész

A hiba annyi, ha bármelyik szerveren muteot kapunk, másik szerverre átcsatlakozva, privát beszélgetést létesítve BÁRKIVEL (/m név -> egyértelműen csak online játékossal működik) tudunk beszélni.

**Comment by mangoshell** [comment]
Ez mindig így volt és sosem zavart senkit. Ha egy némított player másik szerverről spamelt staffoknak, vagy playernek, akkor ott is némítást kapott.

**Comment by andris155** [comment]
Jelenleg ezt sajnos nem lehet megoldani. Talán majd az új ChatControl verzióban.

**Comment by andris155** [comment]
A hibajelentést köszönjük.
