### ISSUE TITLE
Lassú cargo

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4299]
**Survival**:

Nincs semmi értelme a cargonak survivalon... Konrkétan 5s alatt megy át 1 darab dust a ládába. És megtelik az összegyűjtő. Annyira lassú, hogy ha kézzel pakolgatom, hamarabb megvagyok... Jó hogy nincs lagg meg minden, de ez is elég nagy gond.

**Comment by andris155** [comment]
Erre sajnos nincs megoldás.
