### ISSUE TITLE
Pénz!

### ISSUE THREAD

**Issue by Goldie2000** [TheOld-Crafters/Minecraft-servers#4300]
**Sziasztok!** Az miért van hogyha kűld valaki 100.000$-t és ki lépek a játékból és utánna vissza akkor eltűnik? (szerintem levagyok korlátozva valamiért 99.999$-ra!) És nem-e tudnátok ezt nekem megoldani? mert hogyha elvásárólnák azt ki írná a játék!

Megértéseteket köszönöm szépen!

**_Goldie2000_**

**Comment by Goldie2000** [comment]
Meg vagy 2.000.000 $-om is lenne!

**Comment by andris155** [comment]
Ilyen korlátozás tudtommal nincs.
Talán ha van ládaboltod van akkor oda adnak el dolgokat. Más szerintem nem igazán okozhatja.
