### ISSUE TITLE
Balance limit

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4301]
**Survival**:

Mindíg az az indok a pénzfarm ellen, hogy "az emberek 20 perc alatt kifarmolnak milliókat..."
A köztes megoldás lehetne a balance limit. Mondjuk 50 millió. És akkor a pénzfarmosok sem panaszkodnának, meg a pénzfarm ellenesek sem. Új adás-vétel táblarendszer is kellene hozzá. 

Én olyat láttam, hogy: a táblába kell beletenni az eladni kívánt dolgokat jobbklikkel, és ha valaki vesz a táblából, akkor nem egyből a játékosnak megy a pénz, hanem bele a táblába, és a pénz csak akkor kerül a játékoshoz, ha az kiüti a táblát, vagy jobbklikkel leveszi róla a pénzt.

**Comment by maryhonaly** [comment]
Régebb óta van egy ötletünk ennek megoldására, ma reggel Zeri talált is egy lehetséges utat (nem pont ezt). Megnézzük és meglátjuk

**Comment by UDPSendToFailed** [comment]
Szóval, még több limitálás ahelyett, hogy lenne a pénzszerzésre normális alternatíva? Kíváncsi leszek az eredményre.

**Comment by skrisz0101** [comment]
hát akkor én mit csináljak, a bolt pörög, nem tehetek róla :(

**Comment by lovi-dev** [comment]
A limit/fő vpn-eseknél sok multiacchoz vezetne, míg mások meg összeállnának X-en és több emberrel/bolttal azonnal X szerese a limit, nem megoldás.

@jobbklikkel leveszi róla a pénzt.  pl. SK meg majd minden nap végigclickelgeti a 700 táblát?

**Comment by skrisz0101** [comment]
erre még én se gondoltam bele, de amúgy ja xd
átnézni is kín xd

**Comment by Sizarra** [comment]
Szerintem se jó ez a táblás kiszedős módszer. Ezzel semmivel sem lenne jobb, csak a játékosok dolgát nehezítenétek meg.

**Comment by MrZero1** [comment]
Igazából az egész helyzetet 2 dolog oldhatná meg igazán:
1. a jelenlegi pénzeket resetelni, a boltot újragondolni, az árakat a Slimefunhoz igazítani. Akár lehetne GUI bolt is.
2. Kivenni a slimefunt, mert a szerver felépítése (pl bolt) nem a slimefunhoz igazítva készült, hanem a rendes játékmechanikához. A Slimefun csak jóval később került vissza, a gyárakkal gyakorlatilag tönkretéve azt a boltot, ami amúgy nem az SF adta lehetőségekhez készült. 

Nem azzal van a baj, hogy valaki afkol vagy pénzt termel magának, hanem hogy olyan hatalmas gyárak épülnek, ami nem a pénzrendszer teszi (tette) tönkre, hanem előbb-utóbb a szervert fogja megölni. 

(Mari említette, hogy találtunk egy olyan lehetőségek, hogy lehessen limitálni, hogy miből mennyit lehessen eladni/venni percenként/óránként/naponta/hetente stb., meg még sok hasznos dolog van benne. De ez még csak kósza ötlet.)


Szóval, bármilyen javaslatot, ötletet meghallgatunk, senkinek nem az a célja, hogy ellenesítse a pénzszerzést. Csak talán lehetne jobb célokat is kitűzni az emberek elé, mint a baltop1 hely.

**Comment by Sizarra** [comment]
Én szerintem inkább jobb lenne újragondolni a boltot, mint az SF-et kivenni. Szerintem sok ember az sf miatt van itt, mint pl én is.

**Comment by MrZero1** [comment]
> Én szerintem inkább jobb lenne újragondolni a boltot, mint az SF-et kivenni. Szerintem sok ember az sf miatt van itt, mint pl én is.
> 
> 

(Nincs is tervben a kivétele 😃)

**Comment by Sizarra** [comment]
"Kivenni a slimefunt, mert a szerver felépítése (pl bolt) nem a slimefunhoz igazítva készült, hanem a rendes játékmechanikához. A Slimefun csak jóval később került vissza, a gyárakkal gyakorlatilag tönkretéve azt a boltot, ami amúgy nem az SF adta lehetőségekhez készült."
Csak ezért írtam ezt le.

**Comment by UDPSendToFailed** [comment]
> Nem azzal van a baj, hogy valaki afkol vagy pénzt termel magának, hanem hogy olyan hatalmas gyárak épülnek, ami nem a pénzrendszer teszi (tette) tönkre, hanem előbb-utóbb a szervert fogja megölni.

Na és miért épülnek a gyárak? Mert szinte minden normális pénzszerzési lehetőség meg lett szüntetve, már jóval azelőtt, hogy bekerült volna a Slimefun. 
Ha valaki spawner nélküli ghast farmot épített, az volt a baj, ha ásta a homokot napi több órán át, akkor az lett ellehetetlenítve. Mindegy mi volt, meg lett szüntetve, törölve, nerfelve, leütve. 
Valamiért soha semmi nem volt jó a staffoknak, ami kicsit is megérte. Emiatt rákényszerültek a játékosok a SF gyárakra, most pedig lényegében azért lenne törölve a baltop, és ezzel hónapok-évek munkája, mert a SF gyárakon kívül nem maradt más értelmes opció. Picit azért ironikus, nem? 

> Csak talán lehetne jobb célokat is kitűzni az emberek elé, mint a baltop1 hely.

Egyáltalán miért ilyen fontos a baltop? Nem teljesen mindegy, hogy valakinek 20 milliója, vagy 5 milliárdja van? Majd átalakulnak a pwarp-ok árai, a bolt pedig még mindig durván túlárazott, a mostani egyenlegekhez képest is.

**Comment by Squidmanus** [comment]
> hát akkor én mit csináljak, a bolt pörög, nem tehetek róla :(
> amúgy nem vágom miért jobb az új táblás módszer mint a mostani, ugyanúgy megkapja a pénzt

Azért lenne jobb, mert ott a táblában benne van a pénz, ha vesznek tőled, nem egyből hozzád kerül, hanem a táblába. És akkor veszed le,amikor akarod, ha csak nincs max balanceod.

**Comment by maryhonaly** [comment]
Nagyjából egyszerre mind a kettő. Ha tudtam volna, hogy mennyi baj lesz az sf-el, minden erőmmel tiltakoztam volna, hogy bekerüljön. Biztos nagyon szórakoztató, csak már lövésem sincs hány tizede le van tiltva, mennyi duplikációs miegymás bugot szedtünk ki belőle, és vajon még mennyi van amiről nem tudunk, meg Andrisnak hány órája van abban, hogy ne laggoljuk szét magunkat miatta. De próbálom elhinni, hogy élvezetes a farm mellett állni, meg a boltba oda vissza teleportálgatva milliókat szerezni. SF előtt is sokan és ugyan ilyen jól elvoltunk.

Természetesen előbb a bolt lesz átalakítva, viszont kegyetlen nehéz bárminek is beállítani az árát úgy, hogy az egyik nap óránként 10.000 darabot állítotok elő, 2 nap múlva meg óránként 200.000 darabot. Nem tudom megérteni, mért kell minden esetben szürreális mértékűre növelni a termelést, a farm méretét, csak hogy üljetek a pénzen.

**Comment by Squidmanus** [comment]
> Nagyjából egyszerre mind a kettő. Ha tudtam volna, hogy mennyi baj lesz az sf-el, minden erőmmel tiltakoztam volna, hogy bekerüljön. Biztos nagyon szórakoztató, csak már lövésem sincs hány tizede le van tiltva, mennyi duplikációs miegymás bugot szedtünk ki belőle, és vajon még mennyi van amiről nem tudunk, meg Andrisnak hány órája van abban, hogy ne laggoljuk szét magunkat miatta. De próbálom elhinni, hogy élvezetes a farm mellett állni, meg a boltba oda vissza teleportálgatva milliókat szerezni. SF előtt is sokan és ugyan ilyen jól elvoltunk.
> 
> Természetesen előbb a bolt lesz átalakítva, viszont kegyetlen nehéz bárminek is beállítani az árát úgy, hogy az egyik nap óránként 10.000 darabot állítotok elő, 2 nap múlva meg óránként 200.000 darabot. Nem tudom megérteni, mért kell minden esetben szürreális mértékűre növelni a termelést, a farm méretét, csak hogy üljetek a pénzen.

Én személy szerint azért szeretek farmolni, mert gyors. Nincs időm fentlenni ásni a füvesföldet meg bányászgatni. Amikor fentvagyok, inkább élvezetesen töltöm ki az időt, építem a gyárat, csinálom, ami érdekel. Azért jó a pénzfarm, mert akinek nincs ideje fentlenni bányászgatni, annak sem kell 3 héten keresztül kraftolgatni meg gyűjteni a pénzt dolgokra. Elég unfair lenne velünk szemben.
Egyébként is... Ez a logika megőrjít. Ha a valóságban lennénk: te vagy a minisztérium, Nagy_Medve meg egy non-profit vállalat. Ha ő segíteni akar az embereknek, mire fel hiúsítja meg a minisztérium? Nem csettintésre lett ám ott 120 droid:D(megszámoltam). Ez is elég unfair, hogy valaki napokat, heteket, és rengeteg pénzt öl abba bele, hogy kedveskedjen a többi játékosnak, ti pedig egyszerűen kiveszitek a droidot. Akkor legalább kapna juttatást....

**Comment by Squidmanus** [comment]
> > Nagyjából egyszerre mind a kettő. Ha tudtam volna, hogy mennyi baj lesz az sf-el, minden erőmmel tiltakoztam volna, hogy bekerüljön. Biztos nagyon szórakoztató, csak már lövésem sincs hány tizede le van tiltva, mennyi duplikációs miegymás bugot szedtünk ki belőle, és vajon még mennyi van amiről nem tudunk, meg Andrisnak hány órája van abban, hogy ne laggoljuk szét magunkat miatta. De próbálom elhinni, hogy élvezetes a farm mellett állni, meg a boltba oda vissza teleportálgatva milliókat szerezni. SF előtt is sokan és ugyan ilyen jól elvoltunk.
> > Természetesen előbb a bolt lesz átalakítva, viszont kegyetlen nehéz bárminek is beállítani az árát úgy, hogy az egyik nap óránként 10.000 darabot állítotok elő, 2 nap múlva meg óránként 200.000 darabot. Nem tudom megérteni, mért kell minden esetben szürreális mértékűre növelni a termelést, a farm méretét, csak hogy üljetek a pénzen.
> 
> Én személy szerint azért szeretek farmolni, mert gyors. Nincs időm fentlenni ásni a füvesföldet meg bányászgatni. Amikor fentvagyok, inkább élvezetesen töltöm ki az időt, építem a gyárat, csinálom, ami érdekel. Azért jó a pénzfarm, mert akinek nincs ideje fentlenni bányászgatni, annak sem kell 3 héten keresztül kraftolgatni meg gyűjteni a pénzt dolgokra. Elég unfair lenne velünk szemben.
> Egyébként is... Ez a logika megőrjít. Ha a valóságban lennénk: te vagy a minisztérium, Nagy_Medve meg egy non-profit vállalat. Ha ő segíteni akar az embereknek, mire fel hiúsítja meg a minisztérium? Nem csettintésre lett ám ott 120 droid:D(megszámoltam). Ez is elég unfair, hogy valaki napokat, heteket, és rengeteg pénzt öl abba bele, hogy kedveskedjen a többi játékosnak, ti pedig egyszerűen kiveszitek a droidot. Akkor legalább kapna juttatást....

C

**Comment by maryhonaly** [comment]
Ha ilyen problémákba megyünk bele, akkor nagymedve és mindenki más is nyugodtan csinálhatna bármekkora farmot, és termelhetné a napi több százezer bogyót, mert nem lenne piac aki azt annyiért megvegye tőle. Illetve a piacnak is korlátolt vagyona van, lenne egy pont, amin túl ha akarna se lenne miből vásároljon. Az admin shopra eszek viszont nem igazak. Ebből adódóan a valóságban nagymedvének nem érné meg hosszútávon annyit (nem tudom mennyire nehéz egy olyan andoid előállítása) befektetnie a bogyófarmba. 

Amúgy megértelek, tudom, hogy sokan kikapcsolódni járnak fel. De a pénzfarmokat NEM csak az ilyen játékosok használták napi 20-30 percig. Nagyon sokan kihasználták. 
Minden játékosunk egyformán értékes és fontos nekünk, viszont egy kicsit se unfair. Aki nincs is itt és nem is tesz semmit a pénzért, annak miért kellene gazdagnak lennie, vagy fél óra alatt megszerezni azt, amivel más 2 napig szenved? Ki választaná a hosszabb nehezebb utat, ha ott a pénzfarm, minden kész van szinte azonnal, csak a boltba kell teleportálgatni?

**Comment by Squidmanus** [comment]
> Ha ilyen problémákba megyünk bele, akkor nagymedve és mindenki más is nyugodtan csinálhatna bármekkora farmot, és termelhetné a napi több százezer bogyót, mert nem lenne piac aki azt annyiért megvegye tőle. Illetve a piacnak is korlátolt vagyona van, lenne egy pont, amin túl ha akarna se lenne miből vásároljon. Az admin shopra eszek viszont nem igazak. Ebből adódóan a valóságban nagymedvének nem érné meg hosszútávon annyit (nem tudom mennyire nehéz egy olyan andoid előállítása) befektetnie a bogyófarmba.
> 
> Amúgy megértelek, tudom, hogy sokan kikapcsolódni járnak fel. De a pénzfarmokat NEM csak az ilyen játékosok használták napi 20-30 percig. Nagyon sokan kihasználták.
> Minden játékosunk egyformán értékes és fontos nekünk, viszont egy kicsit se unfair. Aki nincs is itt és nem is tesz semmit a pénzért, annak miért kellene gazdagnak lennie, vagy fél óra alatt megszerezni azt, amivel más 2 napig szenved? Ki választaná a hosszabb nehezebb utat, ha ott a pénzfarm, minden kész van szinte azonnal, csak a boltba kell teleportálgatni?

Hát akkor ütögessétek le továbbra is a táblákat, vegyétek ki továbbra is a dolgokat az sf-ből... A végére oda fog jutni a szerver, hogy a duplicate bugokat fogják keresni a playerek, mert nem lesz más... Aztán jön a resi, és csodálkoznak, hogy -30 player napi szinten. Ilyen szinten már annyira mindegy lesz....

**Comment by andris155** [comment]
A Slimefun-n tudtommal semmit se tiltottunk ez miatt. Amik tiltva vannak azok a legtöbb esetben azért lettek tiltva, hogy kreatívból ne lehessen tárgyakat és blokkokat átvinni túlélő módba.

**Comment by skrisz0101** [comment]
@Squidmanus - miért kéne kárpótlás, ha már degeszre kereste magát vele? feljön egy csávó, látja van pénzfarm, fent van két órát, szerez 200k-t és máris op eszközei vannak. Ha nem lenne pénz farm, talán egy vas szettre tellett volna neki :D 
(Ugye a bevételének a fele meg megy a pénzfarm tulajdonosának) új játékos megszerez minden szart amit alap szurviban szerezhet, sf nem érdekli és befejezte a szerót még aznap, mert ,,unalmas". Akkor most kinek lett segítve ezzel? :/
+táblából ha kiveszem a pénzt, ugyanúgy hozzám jön xd nem mindegy hogy egyből jön vagy egyet kattolnom kell érte?

andris: nincs is semmi létfontosságú cucc tiltva, nem is lehet érezni annyira hogy nincsenek bent azok a dolgok.

@maryhonaly - akkor még jó hogy nem tudtad, és végül bekerült. Kicsit unalmasabb lenne nélküle a szeró, rengeteg dolgot hozott be :D - majd megmutatom :p 

@MrZero1 3.: jobs - Pl: jancsika kap 200$-t a jobs miatt ha kiszed 64 követ, de warp bolt-ban el tudja adni még a 64 követ 50$-ért, így Jancsika 250$-t keres vele, aki meg sf-el csinálja és úgy akarja eladni, az 50$-t keres vele. Persze nem ilyen mértékekben, de remélem érthető volt. Persze itt is bele kell számolni az old eszközöket :C 
Azaz: warp boltban az eladási árakat csökkenteni, helyére jöhetne a jobs mint fő pénzfarm, de beleszámolva hogy el lehet adni warp boltban is az árakat. (Tudom, ehhez több ember kéne, de sztem kapásból jelentkezne 5 ember, ha el lett döntve)

**Comment by Sizarra** [comment]
> > hát akkor én mit csináljak, a bolt pörög, nem tehetek róla :(
> > amúgy nem vágom miért jobb az új táblás módszer mint a mostani, ugyanúgy megkapja a pénzt
> 
> Azért lenne jobb, mert ott a táblában benne van a pénz, ha vesznek tőled, nem egyből hozzád kerül, hanem a táblába. És akkor veszed le,amikor akarod, ha csak nincs max balanceod.

Így is, úgy is hozzá megy a pénz, ezzel csak a játékos dolga lenne megint csak megnehezítve, vegyük példának megint sk-t. Neked lenne kedved naponta akár többször is végigszaladgálni a bolton, csak, hogy megnézd van-e bennük pénz, vagy épp cucc? Nekem se lenne hozzá akaraterőm a 20 táblához, nemhogy 700 táblához.

**Comment by lovi-dev** [comment]
> Ha ilyen problémákba megyünk bele, akkor nagymedve és mindenki más is nyugodtan csinálhatna bármekkora farmot, és termelhetné a napi több százezer bogyót, mert nem lenne piac aki azt annyiért megvegye tőle. Illetve a piacnak is korlátolt vagyona van, lenne egy pont, amin túl ha akarna se lenne miből vásároljon. Az admin shopra eszek viszont nem igazak. Ebből adódóan a valóságban nagymedvének nem érné meg hosszútávon annyit (nem tudom mennyire nehéz egy olyan andoid előállítása) befektetnie a bogyófarmba.

Már kész az elmebeteg méretű obszidian farmja. Teljesen mindegy "mennyire nehéz egy olyan andoid előállítása" vagy épp mit vesztek ki, vagy milyen bolt táblát cserlétek le,  Ő megy a következő itemre. Nem érdekli a szerver és nincs ami határt szabna neki, akkor miért ne tenné?

**Comment by lovi-dev** [comment]
> 1. jelenlegi pénzeket resetelni, a boltot újragondolni, az árakat a Slimefunhoz igazítani.

Pénz reset szerintem pont ellenkezőleg hatna, épp versenyt indítana.  Mindenki azt látná hogy itt a lehetőség és most kell nagy farmokat/gyárakat építeni...  Nyilván páran azonnal elhúznának az a többségtől és kis idő múlva ott járnánk mint most.

Amíg a boltba bármit is el lehet adni, addig arra farmok/gépsorok fognak épülni, ha nincsenek korlátok akkor sokan nem tudnak megállni.
Amint a boltba nem lehet eladni, nem lesz pénzforrás. Olyan is szóba jött már, hogy boltba csak venni lehessen eladni nem, pénzforrásnak legyen a jobs.  DE jobsból is azonnal ki kellene venni egy csomó növényt/fát, az összes olyat aminek a növekedését  SF-el vagy csontporral lehet gyorsítani, hisz arra azonnal farmok épülnének. Akkor viszont mi marad bányászat/ásás? Mindenki mobfarmokat fog építeni és abból lesz lagg... az sem jó.

**Comment by lovi-dev** [comment]
Már írtam többször, hát ide is írom. Pwarpok és ládaboltok közelében kellene szabállyal tiltani az SF-et és a tölcséreket (hopper)

Bővebben: Az automatikus pénzfarmok attól működnek, hogy 
1) a gyár ott van közel a bolthoz így szinte kifogyhatatlan a készlet
2) a cargo folyamatosan tölti a ládaboltot

Azaz 2 egyszerűnek tűnő szabállyal jelentősen lehetne csökkenteni a mint a pénzfarm mint a lag problémát:
- ládaboltot és pwarp közelébe,  X chunkon belül ne lehessen SF gép/cargo  
(X-et meg kell nézni, hány chunk távolságból aktiválódnak az sf gépek, nem tudom fejből)
- ládaboltot csak a ládabolt tulajdonosa és csak kézzel tölthessen

Nyilván nem egyik napról a másik, türelmi idővel.

**Comment by skrisz0101** [comment]
X chunk ötlet szerintem nem megoldás, pl Jancsika csinál egy telket, ott a bolt és rajta a pwarp, de 3 telekkel odébb egy másik telken meg ott a gyár, ami pl a haverjáé. Minden pwarpnál körbe lenne nézve (asszem 15) chunkig? (úgy, hogy a másik telek nem feltétlen az övé)

Ládabolt kézzel töltés szerintem tök jó ötlet, ha megvalósítható.

**Comment by lovi-dev** [comment]
> X chunk ötlet szerintem nem megoldás, pl Jancsika csinál egy telket, ott a bolt és rajta a pwarp, de 3 telekkel odébb egy másik telken meg ott a gyár, ami pl a haverjáé. Minden pwarpnál körbe lenne nézve (asszem 15) chunkig? (úgy, hogy a másik telek nem feltétlen az övé)
> 
> Ládabolt kézzel töltés szerintem tök jó ötlet, ha megvalósítható.

15 az nagyon sok, szerintem gép chunkja mellé 4-5 gépmentes chunk elég

**Comment by Sanszi** [comment]
> > Nagyjából egyszerre mind a kettő. Ha tudtam volna, hogy mennyi baj lesz az sf-el, minden erőmmel tiltakoztam volna, hogy bekerüljön. Biztos nagyon szórakoztató, csak már lövésem sincs hány tizede le van tiltva, mennyi duplikációs miegymás bugot szedtünk ki belőle, és vajon még mennyi van amiről nem tudunk, meg Andrisnak hány órája van abban, hogy ne laggoljuk szét magunkat miatta. De próbálom elhinni, hogy élvezetes a farm mellett állni, meg a boltba oda vissza teleportálgatva milliókat szerezni. SF előtt is sokan és ugyan ilyen jól elvoltunk.
> > Természetesen előbb a bolt lesz átalakítva, viszont kegyetlen nehéz bárminek is beállítani az árát úgy, hogy az egyik nap óránként 10.000 darabot állítotok elő, 2 nap múlva meg óránként 200.000 darabot. Nem tudom megérteni, mért kell minden esetben szürreális mértékűre növelni a termelést, a farm méretét, csak hogy üljetek a pénzen.
> 
> Én személy szerint azért szeretek farmolni, mert gyors. Nincs időm fentlenni ásni a füvesföldet meg bányászgatni. Amikor fentvagyok, inkább élvezetesen töltöm ki az időt, építem a gyárat, csinálom, ami érdekel. Azért jó a pénzfarm, mert akinek nincs ideje fentlenni bányászgatni, annak sem kell 3 héten keresztül kraftolgatni meg gyűjteni a pénzt dolgokra. Elég unfair lenne velünk szemben.
> Egyébként is... Ez a logika megőrjít. Ha a valóságban lennénk: te vagy a minisztérium, Nagy_Medve meg egy non-profit vállalat. Ha ő segíteni akar az embereknek, mire fel hiúsítja meg a minisztérium? Nem csettintésre lett ám ott 120 droid:D(megszámoltam). Ez is elég unfair, hogy valaki napokat, heteket, és rengeteg pénzt öl abba bele, hogy kedveskedjen a többi játékosnak, ti pedig egyszerűen kiveszitek a droidot. Akkor legalább kapna juttatást....

Ez nem kedveskedés egyébként, hanem hogy ne neki kelljen járni a boltba a bogyókkal... Helyette elviszik a playerek valamennyi profitért. xd

**Comment by Sanszi** [comment]
> @Squidmanus - miért kéne kárpótlás, ha már degeszre kereste magát vele? feljön egy csávó, látja van pénzfarm, fent van két órát, szerez 200k-t és máris op eszközei vannak. Ha nem lenne pénz farm, talán egy vas szettre tellett volna neki :D
> (Ugye a bevételének a fele meg megy a pénzfarm tulajdonosának) új játékos megszerez minden szart amit alap szurviban szerezhet, sf nem érdekli és befejezte a szerót még aznap, mert ,,unalmas". Akkor most kinek lett segítve ezzel? :/
> +táblából ha kiveszem a pénzt, ugyanúgy hozzám jön xd nem mindegy hogy egyből jön vagy egyet kattolnom kell érte?
> 
> andris: nincs is semmi létfontosságú cucc tiltva, nem is lehet érezni annyira hogy nincsenek bent azok a dolgok.
> 
> @maryhonaly - akkor még jó hogy nem tudtad, és végül bekerült. Kicsit unalmasabb lenne nélküle a szeró, rengeteg dolgot hozott be :D - majd megmutatom :p
> 
> @MrZero1 3.: jobs - Pl: jancsika kap 200$-t a jobs miatt ha kiszed 64 követ, de warp bolt-ban el tudja adni még a 64 követ 50$-ért, így Jancsika 250$-t keres vele, aki meg sf-el csinálja és úgy akarja eladni, az 50$-t keres vele. Persze nem ilyen mértékekben, de remélem érthető volt. Persze itt is bele kell számolni az old eszközöket :C
> Azaz: warp boltban az eladási árakat csökkenteni, helyére jöhetne a jobs mint fő pénzfarm, de beleszámolva hogy el lehet adni warp boltban is az árakat. (Tudom, ehhez több ember kéne, de sztem kapásból jelentkezne 5 ember, ha el lett döntve)

Nézd meg a jobs githubját, tele van hibával. Na annak tényleg jó részét tiltani kéne, hogy működőképes legyen.

**Comment by Sanszi** [comment]
@skrisz0101 nézd meg a jobs githubját, csomó bug van benne. Persze le lehet tiltani ott is sok mindent, csak rossz amikor nincs pl. bányász meg farmer munka, mert ki lehet használni végtelen pénzfarmhoz.

**Comment by skrisz0101** [comment]
meh, megleshetem de nem értek én ezekhez xd

**Comment by andris155** [comment]
Az eredeti jelentéshez hozzászólva. Nem lesz pénz limit. A valóságban is vannak nagyon gazdag emberek és nincs rá limit, hogy mennyi pénzük lehet. :D

**Comment by maryhonaly** [comment]
A szerver gazdasága nem fenntartható lábakon áll. Nem az a gond, hogy valaki gazdag, hanem a bolt által jelentett végtelen pénzforrás. Való életben sem nyomtathatnak az országok korlátlan mennyiségű pénzt. Mindenhogy kell rá valami szabályzás, ha nem is ez, de valami kell.

**Comment by andris155** [comment]
Azt értem, de nem a pénz limit erre a megoldás.

**Comment by UDPSendToFailed** [comment]
> Való életben sem nyomtathatnak az országok korlátlan mennyiségű pénzt. Mindenhogy kell rá valami szabályzás, ha nem is ez, de valami kell.

Ennyi erővel minden nagyobb játékban törölhetnék a szinteket és az összegyűjtött cuccokat, WoT, LoL, CS:GO, stb, hiszen azokban is lehet bármennyit farmolni. Ezért nevezzük őket játékoknak, mert az nem a valóság, a Minecraft is egy játék. A szerver pedig azért van, hogy az emberek számára játékélményt nyújtson, nem arra, hogy itt is korlátozva és ellehetetlenítve legyen minden.

**Comment by maryhonaly** [comment]
Lol-t vagy wot-ot szerintem nem lehet összevetni a minectafttal. Ezekben ténylegesen játszani kell, hogy megszerezd azt a pénzt vagy xp-t, majd elköltsd valamire. 
Nálunk egy két abnormális farm, és csak azon múlik a vagyonod mérete, hogy mikor unod meg a boltba járogatást. 
Egyik említett játék sem az elért javak számítanak, hanem a játékélmény. Nálunk csak a pénz van amivel versengeni akartok

**Comment by UDPSendToFailed** [comment]
> Lol-t vagy wot-ot szerintem nem lehet összevetni a minectafttal. Ezekben ténylegesen játszani kell, hogy megszerezd azt a pénzt vagy xp-t, majd elköltsd valamire.

Itt is játszani kell, a semmiből nem lesz SF gyár, ahogy pénz sem. 

> Nálunk egy két abnormális farm, és csak azon múlik a vagyonod mérete, hogy mikor unod meg a boltba járogatást.

Ez pedig a mesterséges korlátozások miatt jött létre, mivel nem maradt más használható opció.

> Egyik említett játék sem az elért javak számítanak, hanem a játékélmény. Nálunk csak a pénz van amivel versengeni akartok

Kinek mi. :D LoL-ban ott a KDA, WoT-ban a WN8, szerintem teljesen mindegy, hogy azokkal verseng valaki, vagy egy baltop-on lévő számmal, ha jól szórakozik közben.

**Comment by Sanszi** [comment]
Látszik, hogy unjátok, ha nem így lenne, akkor nem járnátok folyamat lopkodni a vadonba. Addig élvezetes ameddig összeáll a gyár, aztán állsz mellette és várod, hogy termeljen.

**Comment by MrZero1** [comment]
Én azt gondolom, hogy csak azért építeni hatalmas nagy (laggoltató) gyárakat, hogy mellette afkoljon az ember, felesleges.

**Comment by UDPSendToFailed** [comment]
> Látszik, hogy unjátok, ha nem így lenne, akkor nem járnátok folyamat lopkodni a vadonba. Addig élvezetes ameddig összeáll a gyár, aztán állsz mellette és várod, hogy termeljen.

Erre ugyanazt tudom mondani, amit az előző kommentben is, nem maradt más opció. Azok is le lettek korlátozva, amiknek semmi közük nem volt a gyárakhoz. 
Ha lenne Jobs, tudna mit csinálni az ember. Eventeken ugrálni egész nap nem mindenkinek van kedve.

**Comment by MrZero1** [comment]
Semmi akadálya nem lenne a Jobs-nak, azonkívül, hogy vannak benne olyan hibák, amik miatt nem kerül még be.

**Comment by UDPSendToFailed** [comment]
Minden hibára van megoldás, például az érc lerakás és a Block Placer tiltása, és már nincs is végtelen pénz a bányászatból.

**Comment by Sanszi** [comment]
Nem azért jársz lopkodni, mert szükséged van az itemekre, hanem mert unod az afkolást XD
Ha tiltva lenne a bányászat munka, akkor más kritikus bug nincs benne, ahogy láttam. Ami volt ezen kívül, azt már kijavították.

**Comment by Sanszi** [comment]
> Minden hibára van megoldás, például az érc lerakás és a Block Placer tiltása, és már nincs is végtelen pénz a bányászatból.

Inkább akkor ne legyen bányászat munka, minthogy ne lehessen letenni érceket. (Szerintem)

**Comment by UDPSendToFailed** [comment]
> Nem azért jársz lopkodni, mert szükséged van az itemekre, hanem mert unod az afkolást XD

Persze, mindenki unja, sehol sem állítottam, hogy ne lenne unalmas egész nap egy helyben állni. Marad a gyárak bővítése, vagy egyéb tevékenységek, amik elfoglalják az embert, például az említett lootolgatás is. 

> Inkább akkor ne legyen bányászat munka, minthogy ne lehessen letenni érceket. (Szerintem)

Aki érceket rak le, az nagy eséllyel valamit bugoltatni akar szerintem, senki se fog abból házat építeni, de ezt majd Andris eldönti.

**Comment by Sanszi** [comment]
Igen, akiknek ez a hatáskörébe tartozik, majd eldöntik. Mindenesetre megérheti kipróbálni a jobst. Bolti árakban szívesen segítek.

**Comment by skrisz0101** [comment]
am ez a ,,vita" mehet a jobs alá, van neki jelentés xd
