### ISSUE TITLE
LiteXpansion vissza gomb hiba a GUI-ban

### ISSUE THREAD

**Issue by derpyAK** [TheOld-Crafters/Minecraft-servers#4302]
**Szerver**: **Savsziget/Survival**

 A slimefun guide-ban ha az uu-matter recipes részre kattintasz, nincs vissza út. Ha rá kattintasz a vissza gombra csak kiszedi azt és kidobja eléd vagy az inventorydba és sehogy sem lehet visszamenni. Hiába kéred le újra a könyvet. 
![image](https://user-images.githubusercontent.com/54103601/104728721-9f28c880-5737-11eb-97e9-fcc4b82594d1.png)
![image](https://user-images.githubusercontent.com/54103601/104728796-bc5d9700-5737-11eb-8539-40d55a0ec301.png)

**Comment by andris155** [comment]
Elvileg ezt a hibát javították.
