### ISSUE TITLE
Miner androidok kivétele-Savsziget

### ISSUE THREAD

**Issue by Forgacsm** [TheOld-Crafters/Minecraft-servers#4304]
**Szerver**:Savsziget

bányász androidok korlátozása vagy kivétele.Laggoltat,élvezhetetlen tőle a játék.

**Comment by Tomi321** [comment]
Szerintem ez teljesen elvenné a magas szinten lévő játékosok kedvét a szervertől. Ha normális mennyiségben használod őket (kb. 20) akkor egyáltalán nincsenek kihatással a szerverre, és max a te fps-edet viszik le. 

Nem mellesleg megjegyezném hogy amikor még aktívan nyomtam a szervert te voltál az aki 50-60 androidot használt egyfolytában. 

Szerintem felesleges a korlátozás, a kivétel pedig konkrétan ellehetetlenítené az "egyszerű" pénzszerzést, emiatt csak még laggosabb gyárakat kéne építeni a pénzszerzéshez.

**Comment by derpyAK** [comment]
Szerintem a korlátozás nem rossz ötlet. :) Esetleg 20-25 android lenne a maximum teljesen korrekt lenne szerintem.

**Comment by andris155** [comment]
Én nem láttam semmiféle laggot a szerveren, amit ez okozott volna.

**Comment by derpyAK** [comment]
Laggot nem okoz, legalábbis eddig nem okozott

**Comment by MrZero1** [comment]
A probléma azzal van, hogy pár ember olyan mennyiségben használja, rákötve az ércgenerátorra, hogy másnak elmegy a kedve a szervertől.

**Comment by derpyAK** [comment]
Pontosan, jóbol is megárt a sok. ^^
