### ISSUE TITLE
/warp vadon

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4305]
**Szerver**:szurvi

a sima warp vadon neve lehetne régivadon, a vadon2 neve meg vadon. 
Így nem költöznének annyian a régi vadonba
Sokszor a ,,hol lehet survivalozni" kérdésre a /warp vadon-nal válaszolnak + ha kicsit tapasztaltabb, akkor tudja hogy a /warp vadon-ra kell menni kérdés nélkül

**Comment by MrZero1** [comment]
Kész.
