### ISSUE TITLE
/plot setbiome hatástalan

### ISSUE THREAD

**Issue by lovi-dev** [TheOld-Crafters/Minecraft-servers#4306]
Survival plot-on nem megy a biomváltás.
se /plot setbiome river 
se /plot set biome river nem viszi.

pl:  /plot set biome river és /p i 
![image](https://user-images.githubusercontent.com/61882792/104898202-97f0fd00-5979-11eb-8208-6a4630c8e0d6.png)

**Comment by andris155** [comment]
Már működik. Meg kellett várni hozzá, hogy normálisan frissüljön a WorldEdit 1.16.5-re.
