### ISSUE TITLE
Slimefun - Auto Crafting Table hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4307]
![image](https://user-images.githubusercontent.com/16057404/104907220-05565b00-5985-11eb-842d-f72ec26eb55e.png)

Nem craftol csontport, akárhogy rakom bele, végigpróbáltam minden slotot, fél stackkel is, stb.

**Comment by lovi-dev** [comment]
(electric ore grinderrel lehet)

**Comment by UDPSendToFailed** [comment]
Lehet, csak az több cargo, így egy gépből megvolt.

**Comment by andris155** [comment]
Elvileg holnap vagy holnapután már jónak kell lennie majd.
