### ISSUE TITLE
Survival - Régi vadon levédés

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4309]
A régi vadon warpjára ki van írva, hogy ne védjenek le, de szerintem ezt sokan nem fogják fel. Nem lenne egyszerűbb tiltani a levédést abban a világban?

**Comment by MrZero1** [comment]
Akár le is lehet tiltani.

**Comment by andris155** [comment]
Letiltottam.

**Comment by andris155** [comment]
508 OCD
