### ISSUE TITLE
Bolt tábla készítés hiba

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4310]
**Szerver**: Szurvi, gondolom savon is

Amit eddig kellett írni vs amit most kell:
1. sor:   semmi     -     skrisz01
2. sor:       1          -         1
3. sor:      100       -      B 100
4. sor:    oak log   -     oak log
Ez elég kellemetlen ha valaki épp boltozni szeretne
ui: automatikusan kiegészítette eddig azt amit bal oldalon írtam azzá, amit jobb oldalon írtam

**Comment by MrZero1** [comment]
Eddig nem kellett jelölni hogy eladni vagy venni kívánsz?

**Comment by skrisz0101** [comment]
ha nem írtad ki, atutomatán odaírta hogy B
ha vétel táblát akartál, akkor oda kellett írni hogy S

**Comment by MrZero1** [comment]
Értem. A warpon is így van kiírva, szóval szerintem ez nem nagy gond. 😃

**Comment by skrisz0101** [comment]
épp új boltot csinálnék, nekem elég gond ~700 tábla xd

**Comment by andris155** [comment]
Oda kell írni. Nem fogja tudni helyetted, hogy B vagy S.

**Comment by skrisz0101** [comment]
Andris, eddig automatán b-t írt
de az jobban zavar hogy már a nevemet is oda kell írni 1. Sorba xd
Naponta csinálok ilyet, észreveszem ha változik

**Comment by MrZero1** [comment]
Akkor egy kis plusz munkád lesz a táblázással 😄

**Comment by mangoshell** [comment]
haha szivas sk nem kell lustalkodni ird le szepen a b betut

**Comment by skrisz0101** [comment]
@andris155 :(

**Comment by andris155** [comment]
Én ezt nem tartom hibának. Ha szeretnél írhatsz a Chestshop fejlesztőnek. A legújabb dev. verzió fut a szerveren.

**Comment by skrisz0101** [comment]
meh

**Comment by skrisz0101** [comment]
de abban mi nem hiba hogy eddig nem kellett az első sorba írni, most meg igen? :C

**Comment by andris155** [comment]
Szándékosan lett megváltoztatva tudtommal.

**Comment by MrZero1** [comment]
Sk, dolgozd fel, ennyi. 😃

**Comment by mangoshell** [comment]
Haladni kellene a korral sk és felfogni hogy ez mostmár ilyen
