### ISSUE TITLE
Survival - Víz alatt lehet cukornádat ültetni

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4311]
![image](https://user-images.githubusercontent.com/16057404/104938502-7c084e00-59af-11eb-93d4-77d15e4b1075.png)

**Comment by IciAlex** [comment]
Alap minecraftos hülyeség.

**Comment by andris155** [comment]
Ez a vanilla játék hibája. A Mojang jira oldalán tudod jelenteni, ha még nem jelentették.
