### ISSUE TITLE
Fungun

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4313]
**Szerver**: Login lobby

Lehetne valami fungun a loginba, lobby-ba, csak úgy. :D 

https://www.spigotmc.org/resources/ultra-fungun-%E2%98%85-1-8-1-16.77295/

**Comment by andris155** [comment]
Sajnos ez a plugin nem működik 1.16.5-ön.

**Comment by MrZero1** [comment]
Biztos van olyan, ami működik. Azt csak példaként írtam.

**Comment by andris155** [comment]
Én nem találtam olyat sajnos.
