### ISSUE TITLE
Jail 

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4314]
1. Néha 51évre adja a jailt, hiába írsz mondjuk 1órát/1percet. (Elméletileg ilyenkor ez csak ilyen visual bug, flame szerint ha letelt volna az alap idő amit írnak akkor kienged)

2. Növekszik a jail időtartama. 

Így bírtam reprodukálni a 2est: jailoltam az altomat 1percre, majd utána kiléptem vele.
Adtam az offline altomnak még1x 1perc jailt. Ekkor elkezdett telni a jail időtartama offline. Amikor letelik, akkor elkezd visszaszámolni, igazából kb annyi ideig, ameddig az ember offline volt, aztán kienged.

A fentit újracsináltam. 1 percre jaileztem az altomat, leléptem vele jaileztem megint, just to be sure. Felléptem vele, leszámolt 0ig az idő, majd elkezdett emelkedni. Megint leléptem vele, 1-2percet vártam, majd felléptem. A jail időtartama 1p 30 volt kb, de 2-3sec után kiengedett.

3. Offline is telik az idő

Jaileltem az altomat 1percre. Leléptem vele, 1p 20sec múlva felléptem. (Elm 57secen kellett volna, hogy maradjon a jail) Fellépek vele, 36secet ír. 5-6secre rá unjailelődött a karakter.

4. Ha jailelt playert seenelnek, akkor nem írja a jail időtartamát.

TL:DR = Bugos az egész, inkább teljen offline az idő, csak működjön jól.

**Comment by andris155** [comment]
Legközelebb kérlek ne egy hibajelentésbe írj több hibát.

Az 51 éves dolog csak egy vizuális hiba. Tudnak róla és lesz hamarosan rá javítás.

**Comment by andris155** [comment]
A növekedő időre kellene egy név ahol letudom ezt videózni az EssentialsX-nek.

**Comment by andris155** [comment]
Offline nem telhet az idő szerintem. Csak normálisan megcsinálták. Jail-en kívül másnál telik offline az idő az igaz.

**Comment by andris155** [comment]
A 4. nem tudom hogy hiba vagy úgy kell lennie.

**Comment by andris155** [comment]
Szerintem valószínű az idő növekedés is lehet csak vizuális hiba egyébként.

**Comment by KingDeadZ** [comment]
Az offline időtelést igazából lehet hogy benéztem.

A jail időt régen írta /seen-nél amúgy akkor is, ha az illető offline volt.

Az időnövekedés lehet hogy vizuális hiba igazából, de elm tegnap egy játékosnál nőtt a mute ideje, és le lett róla véve. Ha reprodukálom azt, hogy nőljön a jail idő, akkor ha letelik az az 1perc akkor kiengedett, amikor teszteltem. Leszámol 0ig, utána meg felszámol egy ideig, majd megint le, majd kienged.

**Comment by KingDeadZ** [comment]
Mondjuk amikor mary tesztelte rajtam a 20seces jaillel, felment másfél percig is, és nem dobott ki szóval nem vagyok benne biztos, hogy hogy bírnám azt újraprodukálni megint.

**Comment by UDPSendToFailed** [comment]
:(

![image](https://user-images.githubusercontent.com/16057404/105485387-18cb3400-5cad-11eb-8767-02a25bc8794d.png)

**Comment by andris155** [comment]
A vizuális hibák javításra kerültek. Ha még mindig növekszik a börtön idő, vagy mégsem írná jól, akkor mindenképpen írjatok.
