### ISSUE TITLE
barrier - old rang

### ISSUE THREAD

**Issue by maryhonaly** [TheOld-Crafters/Minecraft-servers#4315]
survi:
Old ranggal görgő segítségével ki tudják másolni a barriert. Letenni nem, illetve semmit se, de ennek lehet nem kellene játékosok kezében - invjéven lennie:
<img width="1375" alt="Képernyőfotó 2021-01-19 - 18 06 32" src="https://user-images.githubusercontent.com/53797506/105068308-14223800-5a81-11eb-9e97-36f602e6a027.png">

**Comment by andris155** [comment]
Ha nem tudnak vele semmit sem csinálni szerintem nem probléma.

**Comment by KingDeadZ** [comment]
be lehet rakni itemframeba :V

**Comment by maryhonaly** [comment]
Illetve ha jól hallottam, valakinrk cmd blockja is van már?

**Comment by andris155** [comment]
Szerintem nem zavar senkit ha belerakják egy tárgykeretbe.
