### ISSUE TITLE
Slimefun + McMMO enchant addolás

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4317]
A már letiltott Paxel még mindig tud módot változtatni, csak blokkütésre nem jó. Ásó / csákány módban az McMMO skillek rárakják a hatékonyság V enchantot, ha ilyenkor átváltom balta módba, megmarad rajta, és le lehet szedni Auto Disenchanterrel.

**Comment by skrisz0101** [comment]
még jó hogy csak neked van ilyen kb xd

**Comment by UDPSendToFailed** [comment]
4 napja került be, ennyi idő alatt bárki lecraftolhatta.

**Comment by skrisz0101** [comment]
fél napig volt bent

**Comment by andris155** [comment]
Továbbra is tiltva marad így egyelőre.

**Comment by andris155** [comment]
Javították a hibát.
Köszi a jelentést.
2032 OCD
