### ISSUE TITLE
Mcmmo hiba

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4318]
**Szerver**: Survival

![image](https://user-images.githubusercontent.com/34820798/105173818-daedd480-5b21-11eb-9cce-9979d0baa5dc.png)
Ha túl hosszú hex kódot írsz be, a partychat helyett a global chatre írja ki.

**Comment by UDPSendToFailed** [comment]
Ha elírod a hex színkódot, akkor is globalra megy.

![image](https://user-images.githubusercontent.com/16057404/105174263-97e03100-5b22-11eb-87f3-1f67ea9571db.png)

**Comment by andris155** [comment]
Szerintem nem a túl hosszú hex színkód a baja, hanem ez hogy a szöveg végén el van írva a hex színkód.

**Comment by Sizarra** [comment]
> Szerintem nem a túl hosszú hex színkód a baja, hanem ez hogy a szöveg végén el van írva a hex színkód.

Mivel nem fért ki a globalchatre amit írni akartam, így az mc levágta.

**Comment by andris155** [comment]
Egyszer lehet lesz rá javítás. De addig ha figyeltek, hogy ne legyen elrontott hex színkód benne addig nincs ilyen hiba.
