### ISSUE TITLE
Mobaréna helyett Boss aréna/ Boss arénák

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4319]
**Szerver**: Szurvi, sav

Mostanában a mobarénát nem nagyon használja senki se + nem is lehet sztem annyira élvezni
Szal arra gondoltam, mobaréna helyett lehetne ez:
Boss aréna, lényege:
-Nem kitekkel, hanem saját cuccal lehet harcolni a mobokkal
-Több aréna is lehetne, nehézség-jutalom függően (pl 1-es szint, 2-es szint, stb, vagy kreatívabban)
-időlimit lenne hogy napi/heti hányszor lehet legyőzni a bosst
-Értékes nyereményeket adna, boss szintjétől függően
-Boss létrehozása: mythicmobs, ami oldspacen is volt (akár az ottani mobokat is fel lehetne használni)
-Bossok pár tulajdonsága lehet akár: Tűz lövés, villámcsapás, segédek idézése, effekt adás, szöveg miközben harcol, stb
-Lehetne akár olyan boss is ami full old szett + eszközökkel is ritka nehéz :)
-Lehetne egyjátékos és többjátékos lehetőség is (persze a jutalom ettől függően nő-csökken)
-Akár olyan aréna is lehetne ahol valami tárgyért/pénzért cserébe lehet belépni (Boss-kulcs, Boss-érme, mittomén)
-Így belegondolva lehet túl nagy előny lenne az old cucc, akár azt tiltani valahogy

Sztem sokkal jobban lehetne élvezni mint a mobarénát + többen is játszanák

A bossokban, jutalmakban szívesen segítek, oldspacen sok bosst kiötlöttem xd

**Comment by MrZero1** [comment]
Ez megint csak annak élvezetes, akinek OP cuccai vannak.

**Comment by skrisz0101** [comment]
-Több aréna is lehetne, nehézség-jutalom függően (pl 1-es szint, 2-es szint, stb, vagy kreatívabban)

**Comment by Sanszi** [comment]
Nekem tetszene, csak nem saját cuccokkal. Egyedi bossok is király lenne szerintem. A mostani mobaréna elég nehéz, uncsi és a loot se a legjobb. (az se le utolsó ötlet szerintem, ha a mobaréna loottable lenne átalakítva)

**Comment by skrisz0101** [comment]
akár saját cuccos, akár kites arénák (?)

**Comment by andris155** [comment]
Jelenleg nem ebbe az irányba szeretném fejleszteni a szervert. Van így is rengeteg minigame szerveren. Több is mint amennyinek egy túlélő szerveren lennie kellene.

**Comment by skrisz0101** [comment]
1 minigame ki, 1 minigame be, csak ezzel még játszanának is és még értelme is lenne, lenne célja is az op cucc szerzésnek, mert pvp-zni nagyon nem lehet :D
nem tudom mi ebben a probléma, meg mi nem jó ebben az irányban
@andris155

**Comment by skrisz0101** [comment]
@andris155 :(
