### ISSUE TITLE
Rabbits vs Penguins kreatívban

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4321]
/rvp join arena2 paranccsal be lehet lépni, kilépés után pedig kreatívban marad a player a játék lobbyjában. Survivalos invet törli, így egy Soulbound-os Old Csizmát és egy Slime Leggings-t szeretnék visszakérni. 

![image](https://user-images.githubusercontent.com/16057404/105358409-6c2e7b00-5bf6-11eb-9c46-947e1692a1b8.png)

**Comment by andris155** [comment]
Tárgyakat nem tudunk visszaadni sajnos. Mivel gyakorlatilag azt mondasz amit akarsz, hogy mi volt nálad. Nem fogjuk tudni visszanézni.

**Comment by andris155** [comment]
A hibáért járó OCD-ből tudsz venni majd új Old tárgyakat.

**Comment by andris155** [comment]
Letiltottam kreatívban a jogot hozzá.
Köszi a jelentést.

**Comment by andris155** [comment]
1016 OCD
