### ISSUE TITLE
Survival - Vanish bug

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4322]
Vanishben lévő staffnak lehet pénzt küldeni, petet felajánlani, és hozzá lehet adni levédésekhez, így látható, ha fent van.

**Comment by andris155** [comment]
A petet megírni sincs értelme a fejlesztőnek. Több mint egy éve inaktív már.

**Comment by andris155** [comment]
Nem hiszem, hogy lesz rá javítás.

**Comment by andris155** [comment]
Adtam jogot, hogy lehessen offline játékosnak is pénzt küldeni. Ennyit tudtam javítani ezen. Mindig is lesznek lehetőségek a vanish-ben lévő játékosok megnézésére. Nem támogatja az összes plugin ezt az Essentials-ben.

**Comment by andris155** [comment]
Köszi a jelentést.
