### ISSUE TITLE
/warp farmon nem megy a mypet

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4323]
**Szerver**: szurvi

csóró kezdők nem tudnak hozni innen állatokat :'(

**Comment by maryhonaly** [comment]
Ebben a világban van a bolt is, szándékosan van letiltva itt a mypet. Szerintem nem nagy veszteség, van a vadonban bőven az azokból az állatokból.

**Comment by UDPSendToFailed** [comment]
Boltban miért kéne tiltani a peteket?

**Comment by andris155** [comment]
Elvileg kitudtak vele jutni a boltból. Mondjuk sokra nem mennek vele.

**Comment by andris155** [comment]
Engedélyeztem újra.

**Comment by UDPSendToFailed** [comment]
Spawn-ról is el lehet repülni a boltig, elég csak megnézni a koordinátáit, mivel ugyanabban a világban vannak.
