### ISSUE TITLE
gyorsaság effekt + hátra menet

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4324]
**Szerver**: Szruvi, gondolom savon is

Többen írták (+én is észrevettem) hogy ha gyorsaság  (nálam gyorsaság 3) effekt van rajtad és hátra fele próbálsz menni, akkor visszadobál folyamatosan

**Comment by lovi-dev** [comment]
gyorsaság 2-vel is.

**Comment by andris155** [comment]
Javították a hibát.
Köszi a jelentést.
1016 OCD
