### ISSUE TITLE
Savsziget, end portál "üzenet"

### ISSUE THREAD

**Issue by maryhonaly** [TheOld-Crafters/Minecraft-servers#4326]
Savszigeten 2 játékos jelezte az imént nekem (az egyik BoticraftHUN), hogy amikor átmegy az endkapun, az alábbi üzenet / hibaüzenetet dobja ki neki. Ettől függetlenül átteszi az endbe.

<img width="756" alt="Képernyőfotó 2021-01-22 - 20 36 30" src="https://user-images.githubusercontent.com/53797506/105536994-84cf8b80-5cf1-11eb-8917-071c2c6a86e0.png">

**Comment by andris155** [comment]
Javítottam ezt a hibát.
Köszi, hogy írtál.
