### ISSUE TITLE
Levédésre teleportálás

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4327]
**Szerver**: Szurvi
 

Jó lenne ha valahogy meg lehetne oldani hogy a saját levédésünkre tudjunk teleportálni.
Ez leginkább a kezdőkkel fordulnak elő hogy nem tudnak/nem raknak homet, elteleportálnak és nem tudnak visszajutni. leginkább ő miattuk kéne ez.

**Comment by andris155** [comment]
Megoldottam.
Az új parancsok:

/gpteleportlist [oldal] – A lefoglalt területek listája.
/gpteleport id – Teleportálás egy lefoglalt területre.
/setclaimspawn – A lefoglalt terület kezdőhelyének beállítása.
/setclaimname név – A lefoglalt terület nevének beállítása.
