### ISSUE TITLE
event újra újra újra

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4328]
**Szerver**: Szurvi, savon nem tom

Szurvin jó lenne pár jump event is a manuálisakhoz. Értem hogy napiban ott van meg minden, de manuálisba is kéne :)
hiába van ott 20 event, nagy része alkalmi csak. 
van a spirál, a paradise, a parkour. mindegyik egy órás parkour, lehetne egy lazább is.
Több kis laza parkour egymás után, mint pl a spleef körök
Néhány példa: run, upevent, ferdeház1-2, runordie, fel, mario, tudomisén

Ui: nem átrakni kéne, csak simán lemásolni

**Comment by Sanszi** [comment]
Talán a run or die nem, mivel az nagyon kaotikus lenne sok playerrel a redstone meg láva miatt. De egyébként szerintem jó gondolat.

**Comment by skrisz0101** [comment]
ja az mondjuk lehet, szar példa volt xd

**Comment by skrisz0101** [comment]
Biztos lenne még, csak át kéne majd nézni
íjászat is menő lenne amúgy

**Comment by andris155** [comment]
@MrZero1

**Comment by MrZero1** [comment]
Ha lesz rá kapacitás, visszatérünk rá.
