### ISSUE TITLE
Rg ,,Hey! Sorry.." szövegek beállítása

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4329]
**Szerver**: szurvi, sav

Sztem kicsit jobb lenne ha a sorry szövegek helyett be lenne állítva egyedi ,,ehhez nincs jogod" szöveg  a flaggal amit andris írt

**Comment by MrZero1** [comment]
Majd ha lesz rá felesleges kapacitás, akkor meg lesz csinálva.
