### ISSUE TITLE
End

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4331]
Survival--->

5 hónapja emlegetett End reset. Ideje lenne már nem csak emlegetni. Már régóta tartogatom terveim, amiket endbe lehet csak  végrehajtani.

**Comment by lovi-dev** [comment]
subscribe

**Comment by MrZero1** [comment]
Az biztos, ha lesz end reset, a telerakjuk vízzel dolog nem lesz lehetséges. :D

**Comment by DiaGamer321** [comment]
Nekem mind1, csak  tudjam azt, hogy építményem megmarad 1-2 évig.

**Comment by andris155** [comment]
Az admin csapat ha ír nekem, akkor megcsinálom szívesen. De ezt majd nekik kell eldönteni, hogy mikor legyen.
