### ISSUE TITLE
mcmmo elért szint szöveg

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4332]
**Szerver**: szurvi, gondolom savon is

#4289

**Comment by KingDeadZ** [comment]
#4289 nubsk

**Comment by skrisz0101** [comment]
már írtam xd

**Comment by Sanszi** [comment]
A Power Levelt ettől függetlenül ugyanúgy kiírja még most is, és elég zavaró.

**Comment by andris155** [comment]
Most akkor ez a kiírás kell vagy nem? A hex színkódokra nincs megoldás.

**Comment by skrisz0101** [comment]
Szerintem ha lenne rá fordítás, maradhat

**Comment by andris155** [comment]
Ha elfogadja az Essentials a fordítási javaslatot, akkor le lesz fordítva.

**Comment by skrisz0101** [comment]
Kész
