### ISSUE TITLE
Börtön

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4333]
**Szerver**: Szurvi

Egy ideje már online telik csak a börtönidő, de valahogy a büntetések ugyanakkorák maradtak 🤒

**Comment by Sizarra** [comment]
Nagyon sok az a 4 óra, ha csak online telik. Valahogy ezt ki kéne balanceolni.

**Comment by Sanszi** [comment]
> Nagyon sok az a 4 óra, ha csak online telik. Valahogy ezt ki kéne balanceolni.

Nem olyan sok, ha azt vesszük, hogy valószínűleg a létező összes házból loptál. A rongálásról nem beszélve.

**Comment by maryhonaly** [comment]
Tisztában vagyunk azzal, hogy csak online telik, és ehhez mérten vissza is fogtuk a szankciók mértékét. Ettől függetlenül, ha valaki többet érdemel mint 15 perc, akkor többet is kap.

**Comment by Sizarra** [comment]
> > Nagyon sok az a 4 óra, ha csak online telik. Valahogy ezt ki kéne balanceolni.
> 
> Nem olyan sok, ha azt vesszük, hogy valószínűleg a létező összes házból loptál. A rongálásról nem beszélve.

Akkor is sok, ha azt nézed, hogy online kell lenni. Akkor teljen offline is.

**Comment by andris155** [comment]
A legegyszerűbb megoldás, hogy be sem kerülsz oda erre. Nem nehéz szerintem betartani a szerveren a szabályokat és normálisan viselkedni...
