### ISSUE TITLE
Börtön kiírás

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4334]
**Szerver**: Survival

Ha magam alatt kiütök 1 blockot ezt írja ki, és értelmetlen.
![image](https://user-images.githubusercontent.com/34820798/105742737-2cd89500-5f3c-11eb-895b-f7b1511012ae.png)

**Comment by Sanszi** [comment]
Lehetne inkább "Ez nem a Breaking Bad".

**Comment by andris155** [comment]
Ha erre tudsz jobb fordítást, akkor nagyon szívesen megváltoztatom.
,,You do the crime, you do the time."
Egyedi szöveget nem szeretnék. De jobb fordítás biztosan van.

**Comment by mangoshell** [comment]
Ha megteszed a bűncselekményt, akkor leülöd az időt?

**Comment by andris155** [comment]
Átírtam erre: Ha bűncselekményt követsz el, akkor leülöd az időt.
Majd holnap már ez lesz a szöveg.

**Comment by andris155** [comment]
Köszi a javaslatot.
