### ISSUE TITLE
Börtön

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4335]
**Szerver**: Survival

Szerintem lehetne engedélyezni a /pg-t a börtönben, mivel csak akkor telik, ha online vagyok, így lehessen mit csinálni.

**Comment by andris155** [comment]
Nem lesz engedélyezve. A börtön nem a minigame-ről szól. Viselkedjenek úgy a játékosok, hogy ne kerüljenek oda!
