### ISSUE TITLE
/bolt menü tárgyak, blokkok

### ISSUE THREAD

**Issue by andris155** [TheOld-Crafters/Minecraft-servers#4336]
**Szerver**: Túlélő, Savsziget, Építész+

A MineMarket-en valamiért az összes kategória átállításra került így a jelenlegi beállítás elveszett. Majd újra be kell állítani, de szeretnék kicsit fejleszteni majd ezen.

**Comment by andris155** [comment]
Megcsináltam normálisabbra a menüt.

**Comment by mangoshell** [comment]
Köszönjük!
