### ISSUE TITLE
Jobs fizetések beállítása

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4337]
Most, hogy bekerült tesztre, szerintem szívesen segítene pár játékos beállítani, akik értenek az árakhoz. Így az adminok is időt spórolnának, és talán sikerülne a mostani pénzrendszerhez igazítani. Van hozzá ingame szerkesztő, csak jog kellene, és a whitelist-hez hozzáadni, akik benne vannak.

**Comment by lovi-dev** [comment]
Az összes csontporral és/vagy water sprinkler -el gyorsítható növény/fa kiütéséért járó $-t azonnal szinte ki kell nullázni. 
Csontport UU-matterből automatán craftolható, így ellenkező esetben hatalmas gyár építésére ösztönöz.

Az olvasztás is elgondolkodtató, hisz UU-matterből lehet automatán craftolni iron és gold ore-t, ha fizet arra is afk farmok fognak épülni.

**Comment by UDPSendToFailed** [comment]
Egyetértek, ezért kéne olyanokra bízni a feladatot, akik többet játszanak survivalban.

**Comment by Sanszi** [comment]
Blockplacert letiltani, úgy se használja senki. Legalább egy veszélyforrás kilőve.

**Comment by UDPSendToFailed** [comment]
2 hete elkészült, már csak át kéne néznie a staffcsapatnak, és összeírni a dolgokat, amik változtatásra szorulnak.
