### ISSUE TITLE
Táblabolt közös tulaj vagy ilyesmi

### ISSUE THREAD

**Issue by HunGamerFake** [TheOld-Crafters/Minecraft-servers#4340]
**Szerver**:survival

Ha többen üzemeltetnek egy táblaboltot azzal az a gond hogy csak egy ember tudja tölteni, a többiek csak úgy hogy egy hopper van bele vezetve ami meg ronda. Az én ötletem hogy trustolni lehessen táblabolthoz valahogy vagy közös tulaja lehessen, közös pénzel meg ilyesmi

**Comment by andris155** [comment]
https://github.com/ChestShop-authors/ChestShop-3/issues/133
Már pár éve megírták ezt a Chestshop-nak. Elvileg az LWC-vel a ládás dolog megoldható lenne. De az LWC jóval több erőforrást használ és kell hozzá külön adatbázis is. Én ezt nem tartom jó megoldásnak. Lehetséges, hogy a jövőben a Chestshop megvalósítja majd. De egyelőre nem úgy tűnik, hogy az mostanában lesz.
