### ISSUE TITLE
/rangok parancs

### ISSUE THREAD

**Issue by derpyAK** [TheOld-Crafters/Minecraft-servers#4343]
**Szerver**: **Savsziget**

 A /rangok parancs nem hoz ki semmilyen ablakot. Nem működik.

**Comment by andris155** [comment]
Ha teljesen elkészül az új MineMarket menü, akkor majd megcsinálom, hogy nyissa meg azt az oldalt benne. Viszont a tárgy lore-ba nem lesznek már leírva a dolgok.

**Comment by andris155** [comment]
Megcsináltam, hogy nyissa meg a rangok kategóriát a bolt menüből.
