### ISSUE TITLE
Börtönidő

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4344]
**Szerver**: szurvi, sav

/seen-el a börtön ideje nem csökken. nem tudom csökken-e amúgy, de ott biztos nem

**Comment by Sanszi** [comment]
Nem csökken és sosem jár le. Ma diát pl. /unjail-olnom kellett, hogy kijusson.

**Comment by andris155** [comment]
Nekem hibátlanul működik. Ha offline a játékos, akkor nincs ott az idő. Ha online akkor ott az idő és telik is. A szerveren teszteltem. Esetleg ha tudtok egy játékost írni ahol mindig van ez a hiba az jó lenne vagy nem tudom miért lehet ilyen.
