### ISSUE TITLE
bedrock kiütése

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4345]
**Szerver**: szurvi

ha kiütök egy bedrockot, ezt írja:
![2021-01-30_14 35 20](https://user-images.githubusercontent.com/29951969/106357772-7e03d280-6308-11eb-8efe-26e555e59990.png)

**Comment by andris155** [comment]
Már jelentett hiba. Egyelőre nem oldotta meg az FAWE fejlesztője sajnos.
