### ISSUE TITLE
Favágó android és a nether gombák

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4346]
**Szerver**: Szurvi, sav

Ha a favágó android kivág egy nether gombát, ugyanúgy visszarakja a nether gombát mint a fánál a facsemetét, de a talaj alatta sima netherackká változik. a sima netherrackkon nem marad meg a nether gomba, ezért kidobja saját magát a gomba
 ergó: nem lehet favágó androiddal nether fát szedni rendesen

**Comment by Sanszi** [comment]
Ha ráállítasz egy bone meallel teli dispensert, a gomba alatti netherrackra, akkor újra nyliumossá fogja tenni. De csak akkor, ha van legalább egy nylium blokk a gombaás mellett. (így "terjeszti" a nyliumot)

**Comment by skrisz0101** [comment]
de a gombát nem rakja vissza, mert abban a pillanatban mikor kivágja, akkor sima netherrack

**Comment by andris155** [comment]
Mivel nem kap fényt a talaj hosszabb ideig ezért netherrack lesz belőle. Ez a vanilla játék része. Az viszont hiba, hogy a netherrack-re rakja le. Ezt megírom a Slimefun-nak.

**Comment by andris155** [comment]
Javította a Slimefun. Majd betölt holnap vagy holnapután a frissítés.

**Comment by skrisz0101** [comment]
szóval mostantól vissza se rakja a gombát vagymi? xd

**Comment by andris155** [comment]
Netherrack-re nem fogja.

**Comment by skrisz0101** [comment]
szóval akkor a valódi hiba nem is lesz megoldva? :C
