### ISSUE TITLE
levédés - random eltűnik, de mégse

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4347]
**Szerver**: Szurvi

Ma többször is előfordult több levédésemen is.
-Épp nézni akartam ki van hozzáadva a /trustlist paranccsal, de azt írta, hogy itt nincs levédés
-Ha újat akartam létrehozni a helyére, azt írta ott a levédés
-Ha trustolnia kartam valakit, azt írta nincs ott levédés
-Ha aranykarddal jobb klikkeltem, azt írta van ott levédés
-Ha /claimlist-et írok, mutatja hogy ott a levédés
-Ha bővíteni akarom paranccsal a levédést, azt írja nincs ott levédés
-Ha valaki építeni próbál, aki nincs hozzáadva, azt írja hogy van ott levédés
-Ha valaki építeni próbál, aki hozzá van adva, azt írja hogy nincs ott levédés

Azaz: Parancsok fele azt mutatja hogy ott a védés, a fele meg azt hogy nem :D
Magától megoldódik egy idő után

**Comment by andris155** [comment]
Ezzel sajnos nem tudok mit kezdeni így, hogy nincs meg az, hogy pontosan mitől lesz ilyen. Nem is sikerült reprodukálnom se a hibát. Kb. 80 plugin is van ami okozhatja ezt. De az is lehet, hogy a szerverfájl. Hibát nem láttam semmit ezzel kapcsolatban a logokban. Próbáld meg esetleg kitörölni az egész levédést és újra levédeni az egészet. Lehet ez megoldja.

**Comment by skrisz0101** [comment]
Több védésnél is előfordult, nem csak egynél
Ez a hiba akkor kezdődött, mikor megírtam, aznap
