### ISSUE TITLE
Coreprotect - kreatívos bug

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4348]
A kreatívban letett blockokat ha kiütik, nem írja hogy kiütötték volna, csak azt hogy le lett rakva.

A survivalban lerakott blockokat írja normálisan, hogy kiütöttem.
![image](https://user-images.githubusercontent.com/38157910/106388258-f9838380-63dd-11eb-8800-85ecb55b2890.png)

**Comment by andris155** [comment]
Sikerült reprodukálni a hibát. Megírtam a fejlesztőnek. Kb. fél év a javítási idő. Addig sajnos ezzel nem tudok mit kezdeni.

**Comment by andris155** [comment]
A jelentést köszönjük.

**Comment by andris155** [comment]
508 OCD
