### ISSUE TITLE
Nem megy a nomobspawn flag

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4349]
Survival---->

Már jelentettem, és bezárták... Nem megy a claimflag nomobspawn a netherbe. Bizonyítani tudom, kingdead szemtanu ráadásul. Egy admin ha feljön szoljon nekem, és én megmutatom neki.

**Comment by andris155** [comment]
Ismét teszteltem és ismét nem spawn-olt egy mob sem nekem. Megnézegetni nekem nincs mindig ezeket időm. Csak annyit írsz hogy nether. A nether-ben ha csinálok egy levédést és bekapcsolom a nomobspawns flag-et ott valóban nem tud semmi sem spawn-olni.
Vagy talán igen, de persze meg sem adtad mik spawn-olnak. De így hogy ezt nem írtad le nem tudom mivel kellene pontosan tesztelni. Esetleg ha megadsz egy koordinátát és mob típusokat akkor megnézem szívesen ott és azzal az élőlénnyel. De így, hogy nem adsz meg elég információt nem tudok ezzel mit kezdeni.

**Comment by lovi-dev** [comment]
Ilyenek eddig is  spawnoltak /setclaimflag nomobspawns -os területen:
![image](https://user-images.githubusercontent.com/61882792/106659368-ebc92c00-659e-11eb-8b76-fdb652730721.png)

**Comment by Sanszi** [comment]
Tesztelem más playerrel együtt és működik a flag.

**Comment by andris155** [comment]
Teszteltem és pedig ezek sem tudnak spawn-olni. Bemenni persze betudnak a területre.
