### ISSUE TITLE
Survival férőhely

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4350]
**Szerver**: Szurvi

51en vagyunk fent, 20as a tps
Szerintem fel lehetne tolni a limitet

**Comment by Sanszi** [comment]
Még mindig sűrűn ingadozik 45-50 playernél, 13-20 között a tps.

**Comment by andris155** [comment]
Növeltem rajta kicsit, de azért még majd lesz min optimalizálni, hogy tényleg jól 20 körüli TPS legyen akkor is.
