### ISSUE TITLE
Afk szabályzat újradolgozása

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4351]
----> Survival

Értelmetlen, no sense szabályok vannak. Ha valaki aktív, de csak 5 percre feláll, akk az minek számít büntetendő Afknak. Ha egy gyár mellet afkol a személy, akk nem ártana, ha meglesnék azt, hogy az a gyár termel-e valamit, és csak azután dönteni büntetéséről. És ha valaki gyár mellet van, akk tessék ne akkor büntessék, ha valaki 5 percre kimegy a konyhába, hanem ha szándékosan áll ott, vagy alacsony a TPS. Az elmúlt napokba nem egy esetet láttam, amikor  a staff az Afk warpra teleportálta a játékost, közben a játékos csak  elnézett a játéktól, hogy igyon, vagy csak simán nem figyelte a chatet. Nekem mind1, hogy mit mondanak a staffok, mert ők csak a szabályaik szerint viselkednek. De kiváncsi vagyok más játékos véleményére is, mert szerintem nem korrekt.

**Comment by skrisz0101** [comment]
afk = afk warp
sok afk = börtön warp
Nem csak azért tilos az afk gyár mert leesik a tps

**Comment by UDPSendToFailed** [comment]
Majd ha bekerül a Jobs, nem kell 0-24 a gyár mellett állni, hogy legyen pénz.

**Comment by MrZero1** [comment]
Egyetértek, kicsit erős az AFK szabályzat, több szabály fog változni, bővülni, majd ezt is újragondoljuk. De attól még továbbra sem kell afkolni feljárni. (most nem miattad irom Dia)

**Comment by skrisz0101** [comment]
így jobban belegondolva:
5p után ,,AFK" leszel, utána 10p és kidob az egész.
Szerintem ez miatt felesleges az egész afk warp. 10perc afk miatt vadászni az emberekre. több kárt okoz ez, mint jót.
Pistike elmegy kajáért, már áttette őt ,,AFK"-ba. azzal a 10p-vel nem váltja meg sem a világot, sem dönti romokba a szerót. 
+Csomó gyűlöletet szül -> már volt elég eset ebből szerintem.

Röviden: Afk warp felesleges, kidobálni se kell senkit, ha afkol. kidobja azt magától
(Autoklicker persze más, sima kick aztán hadd klikkeljen magában :D)

**Comment by skrisz0101** [comment]
@MrZero1

**Comment by maryhonaly** [comment]
Azért, mert valaki elment kajáért vagy váltani 3 szólt egy rokonnal, nem bántunk senkit se. MIndenkinek közbe jöhet bármi, de nem fél óránként kell rohanva ott hagyni a gépet.
Lehet annak tűnünk, de nem vagyunk teljesen hülyék. Amikor valaki egy nap alatt már nyolcadik alkalommal ugyan azon a területen áll, és mindig csak hoz egy hamburgert. Persze. És akkor mindenkit hagyjunk nyugodtan afkolni, amíg Sopronból felmegy a nyugatiba egy fagyira.

Valamelyik nap beszélgettünk erről, illetve a büntetésekről: 
Két - három alkalommal 3-5 perc eltérésekkel kérdezi a staff, hogy gépnél vagy-e. Amennyiben nem reagálsz, ergo éppen a szomszédban nézed a filmet, afk-nak titulálunk, és warp. 4-5 elwarpolás után kezdődnek a kickek, és 3-5 kick után börtön. Ez durván 10 alkalmat igényel, amikor azon kapjuk, hogy megint "véletlen" el kellett mennie. 

Lehet igazatok van, nekünk is toleránsabbaknak kell lennünk, de a játékosoknak nem szabad majd ezzel visszaélniük.
Igaz, hogy 5-10 perc "afk" nem világmegváltó, és ennyiért nem is fogunk szólni, de ha egy nap alatt csak hatszor dobja ki, az kapásból egy órányi termelés, ami egy közepes méretű gyárnál tetemes összeg már.

**Comment by KingDeadZ** [comment]
5perc után dobjon el automatikusan afkra és 15p után kick esetleg?

**Comment by skrisz0101** [comment]
Érvet értem, de még mindig afelé hajlok hogy ez több gondot okoz, mint. ,, megoldást"

**Comment by skrisz0101** [comment]
na akk mi lesz

**Comment by Komjatius** [comment]
_> Valamelyik nap beszélgettünk erről, illetve a büntetésekről:
> Két - három alkalommal 3-5 perc eltérésekkel kérdezi a staff, hogy gépnél vagy-e. Amennyiben nem reagálsz, ergo éppen a szomszédban nézed a filmet, afk-nak titulálunk, és warp. 4-5 elwarpolás után kezdődnek a kickek, és 3-5 kick után börtön. Ez durván 10 alkalmat igényel, amikor azon kapjuk, hogy megint "véletlen" el kellett mennie._

Engem speciel a visszatérésem után második, adott napon első elwarpolás után, kick nélkül, tett valamelyik rosszéletű 30 perc börtönbe... Ezzel ugye el is vetettem a visszatérés ötletét, hiába vettem rangot (rossz befektetés volt). Korábban is tudtam, hogy pár staff direkt pikkel rám, és úgy tűnik, hogy ez nem változott.


_> Lehet igazatok van, nekünk is toleránsabbaknak kell lennünk, de a játékosoknak nem szabad majd ezzel visszaélniük.
> Igaz, hogy 5-10 perc "afk" nem világmegváltó, és ennyiért nem is fogunk szólni, de ha egy nap alatt csak hatszor dobja ki, az kapásból egy órányi termelés, ami egy közepes méretű gyárnál tetemes összeg már._

Más szerverek teljesen jól elvannak a 15-30 perc utáni autokickkel. Fel se merül, hogy egy rakás staff legyen online, és körbe járjanak a játékosok után kémkedni. A staff dolga egyáltalán nem ez lenne.
Mióta pedig nincs dust eladás a boltban, lehet az a gyár akármekkora, egy óra alatt lepkef**g termelődik, nem tetemes összeg.

Nyilván, minden szerveren vannak szabályok. De van különbség, hogy a szabályok azért vannak, hogy mindenki jól érezze magát (pl. ne "niggerezzenek", ne k***a anyázzanak, ne káromkodjanak az emberek, ne legyenek lopások, rombolások stb.), szóval mindenki szabadsága addig tart, amíg másokét nem sérti (ez ugye egy normál civilizáció hozzáállása, egy normális szerver is ezeket képezi le), vagy a szabályok öncélúak, azért vannak, hogy igazolják önmagukat, a staff létjogosultságát, a hatalom érzetét. Sajnos, a TOC ezt a mentalitást képviseli, ami, tekintve, hogy egy magyar szerverről beszélünk, látva, hová tart Magyarország politikája, társadalma, nem meglepő. De nekem ez nem tetszett sosem, nem tetszik továbbra sem. 

A staffok dolga nem a játékosok zaklatása, a játékélmény tönkretétele lenne, hanem csak annak szavatolása, hogy ne legyenek konfliktusok, illetve az igazságos állapotok szavatolása, pl. rombolások, lopások visszaállítása stb.

Ha börtönbe tesz a staff anélkül, hogy bárkinek is ártottam volna, bárkinek is kárt okoztam volna, bárki szabadságát, pozitív játékélményét sértettem volna, akkor ott nem velem van a baj, hanem a rendszerrel. Nem véletlenül hagytam magam mögött Magyarországot sem. 

Amikor ez történt, magyar idő szerint késő este, volt fent 15 ember, ebből 6 staff. Vicc. Az egész koncepció velejéig romlott. A TOC úgy működik, mint ha Magyarországom - a fenti arányokat alapul véve - 3 millió rendőr volna, és a Nagy Testvér minden lépésedet figyelné, és mindenért börtönbe tenne.

Az meg, hogy a börtönidő nem telik, ha nem vagyok belépve, nem AFK-olok a börtönben, az már végképp az értelmetlen, szadisztikus, öncélú g***ség csúcsa. Ismét a hozzáállást tükrözi, azt, hogy az alapvető probléma a fejekben van. Nem a játékosokért vagytok, hanem a játékosok ellen.

Tehát a dolgok helyreigazítását is itt az alapoknál kezdeni, az illetékesek fejében kellene rendet tenni. Mert amíg egy teljesen torz szemüvegen keresztül nézitek a világot, addig a normális, építő javaslatokat sem tudjátok a helyén kezelni, csak teljesen beteg kifogásokat fogtok előszedni, hogy miért ne hozzátok helyre a nyilvánvaló hibákat.

**Comment by Sanszi** [comment]
@Komjatius 

Bizonyos szinten egyetértek azzal amit írsz, viszont senki sem pikkel rád, minden játékos ugyanúgy megkapja a börtönt nem csak te. Plusz egy ország politikai helyzetét nem is lehet hasonlítani egy minecraft szerverhez, mert ez buta dolog. Mindazonáltal a probléma adott, túl erős szankciók vannak kiszabva bizonyos esetekben és abban is valamennyire egyetértek veled, hogy olyan mintha nem a játékosok élménye lenne az első helyen a staffok számára. Nyilván ez nem azt jelenti, hogy mostantól mindenki szabadon agyba-főbe afk farmoljon, vagy anti-afkoljon, vagy bugokat használjon ki, hanem ésszerűen átgondolni, hogy valóban az 5-10 perc afkkal keresi valaki magát halálra. Azt is meg lehet oldani, hogy 5-10 perc tétlenség után dobja ki a szerver a játékosokat, vagy 5 perc után automatikusan warp afkra tegye őket. A leveled sokkal szebb volna, ha nem lenne benne káromkodás, viszont ettől függetlenül szerintem megfogtad a lényeget bizonyos dolgokban.

**Comment by Icecroft** [comment]
Komjatiusnak igaza van, legyen elég a 15 perces kick, mint régen. Egyébként a gyárak jelentőségüket vesztették, a legtöbb nem is működik, mivel a termékekre nincs kereslet, a piac telítődött illetve a warp boltból kikerültek azok, amikkel keresni lehetett. Tehát 15 perc afk alatt senki sem keresi magát halálra.
Így mindenkinek kellemesebb lenne, a staffoknak nem kellene folyamatosan ellenőrizni, a játékosoknak nem kellene folyamatosan futkorászni, hogy ne kerüljenek warp afk-ra.
Többször kerültem már úgy warp afk-ra, hogy a gép előtt ültem, nem voltam AFK státuszban és mégis repültem. Az indok az volt, hogy jött a hal, de mégsem fogtam ki vagy nem válaszoltam a chaten :)   A chatet rendszeresen nem figyelem, mivel a stílus/tartalom időnként kritikán aluli. Nos ez a másik: A chat egésznapos floodolása hülyeségekkel, rendszeres káromkodás stb. sokszor egy mute-ot sem ér, de az afk börtönnel és bannal való büntetése fontosabb. Valami félrement.

**Comment by MrZero1** [comment]
Eddig tartott az értelmes, obszcén szavaktól mentes hozzászólások. Lezárom a hozzászólást. 

(Igen, diktatúra van, stbstbstb)

**Comment by MrZero1** [comment]
Az alábbiak szerint módosult:

Többé már nem kickelünk vagy börtönzünk be farm/gyár mellett egy helyben álló embereket, a szerver 15 perc után magától kidobja őket. Emiatt a /warp afk megszűnik.

Továbbra **sem** toleráljuk az anti-afk szerkezetek építését, használatát. Tehát, ha valaki egy helyben üt egy farmban vagy más módon elkerüli, hogy a szerver kidobja afkért, akkor lehet büntetés.

Az online töltött időért 10 perc helyett óránként fog járni pénz.

_(Ez egy teszt jellegű módosítás, a későbbiekben módosulhat még, attól függően, hogyan alakul a szerveren lévő játékosok afk tevékenysége.)_

**Comment by MrZero1** [comment]
Edit: Az AFK warp nem szűnik meg, aki akar, itt (is!) afkolhat, bármiféle következmény nélkül. De csak ennyi. Minden más az előző kommentemben van.
