### ISSUE TITLE
Survival - Kérdés

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4352]
A telkeken a zombik nem ölik meg a villagereket, és a gólem sem sebez más mobokat/játékost. Ez direkt van így?

**Comment by andris155** [comment]
Ha engedélyezed a pve flag-et akkor megtudják ölni, viszont sajnos így az entitások nem lesznek védettek a telkeden. Sajnos ez ilyen.
