### ISSUE TITLE
Szabályzat és szerver kiírás paradox

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4353]
**Szerver**: Szurvi

Ugye a szabályzatban benne van (ki szerint jogosan, ki szerint nem), hogy levédetlen is tilos lopni
Az [Információ] mindig kiírja hogy ,,levédetlen területekért nem vállalunk felelősséget" vagy valami hasonló.

Ez kicsit paradox.
Pl ha jancsika nem védi le a házát, lopnak tőle, majd szól staffnak, aki lerendezi a megszokottak szerint, akkor felelőséget vállal, nem?

Most volt épp chaten hogy egy csávó egy levédetlen dia blokkot lopott és kapott érte 20p jailt
Információ írta h a levédetlen területekért nem vállalunk felelősséget, de szabályzatban meg ott a nem lopás (sehonnan) szabály
Szerintem kicsit jogosan is háborodott fel, mert kb be lett csapva xd

**Comment by maryhonaly** [comment]
Elsőre picit fura, de kifejtem hogy kezeljük ezeket: lopni mindenhogy bűn. 

Levédett területről lopás: bármilyen úton-módon történik, szankcionálni fogjuk, és mivel "felelősséget vállalunk" a levédett területek után, elkezdjük keresni az eltűnt itemeket, majd visszaadni azt. 

Le Nem védett terület esetén lopás után az illetőt büntetjük, főleg ha nem elsőre és nem kis mennyiséget visz el, viszont mivel "felelősséget nem vállalunk", így nem szolgáltatjuk vissza az elveszett itemeket.


Személy szerint marhára unom, hogy mindenki a vadonban akar "lootolgatni", szerintem büntetni kell.

**Comment by skrisz0101** [comment]
ja, így vágom. Akkor ok.

**Comment by andris155** [comment]
Ha már fél éve offline a játékos akkor a Griefprevention fokozatosan törli a lefoglalásait. Most ha innen visz el valaki valamit azért is büntetünk? Mivel a jövőben már több reset nem lesz az 1.17 után és a világ nagysága pedig véges szerintem ilyen esetben nem kellene büntetni. Abban az esetben ha egy aktív játékos nem tudta hogy le kell védeni vagy elfelejtette levédeni akkor tényleg jogos a büntetés.

**Comment by maryhonaly** [comment]
Ha jól emlékszek, vagy 1 hónappal ezelőtt beszéltük, hogy ezt az automata levédés törlést letiltjuk.
Ilyen esetben kézzel szoktuk feloldani a levédéseket, de előtte minden tárolót, néha az épületet is töröljük onnan, hogy csak a területet kapja meg. Néhány játékos esetén ha feloldódna a levédése és lootolhatóvá válna, eszméletlen mennyiségű és értékű itemhez juthatnának

**Comment by UDPSendToFailed** [comment]
Ezt a láda / ház törlést amúgy nem értem, ha már egyszer megdolgozott valaki azokért a cuccokért, de többet nem megy vissza a szerverre, miért ne kaphatná meg más, miért kell elvesznie a semmibe? Nem a baltop elsők területeire gondolok, teljesen átlag játékosokéra.

**Comment by andris155** [comment]
Ahogy írtam a világ nagysága véges és több resetet meg senki se akar. Nem biztos, hogy jó ötlet évekig vagy évtizedekig megtartani az inaktív játékosok dolgait benne.

**Comment by Sanszi** [comment]
Egyetértek azzal amit mary írt, hogy "lopni mindenhogy bűn". Viszont a régóta inaktív playerek itemeit az adminok betehetnék a raktárvadász eventbe, így nem vesznének kárba.

**Comment by skrisz0101** [comment]
de az a téma most hogy mi van ha nem az admin viszi el onnan :v

**Comment by Sanszi** [comment]
> de az a téma most hogy mi van ha nem az admin viszi el onnan :v

Hát ahogy leírtam, szerintem a lopás az lopás, minden esetben büntetni kell.
