### ISSUE TITLE
Hónapstaffja szavazás

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4354]
Ha meg lehet csinálni, akkor szavazatért adhatna egy kissebb összeget, pl 5000$ vagy 10000$ a játékosokat is ösztönözné hogy szavazzanak.

**Comment by andris155** [comment]
Egy szavazatért ez rengeteg pénz szerintem főleg, hogy csak egy kattintás. Ha @MrZero1 jó ötletnek tartja és mond egy árat, hogy mennyit adjon akkor megpróbálom megoldani.

**Comment by mangoshell** [comment]
Szerintem nem sok pénz havonta az az 5-10000$ a jelenlegi "árak" mellett

**Comment by MrZero1** [comment]
Kapjanak 5 ezret, nem vészes az.

**Comment by andris155** [comment]
A savon is ennyi legyen?

**Comment by KingDeadZ** [comment]
Ott nagyobb összegeket szednek gyorsan, esetleg 7500$

**Comment by andris155** [comment]
Megcsináltam. A savon $3000-t ad érte.
