### ISSUE TITLE
Slimefun alapanyagkalkulátor.

### ISSUE THREAD

**Issue by mnb124** [TheOld-Crafters/Minecraft-servers#4355]
Észrevettem hogy újra törődnek az SfCalc pluginnal és kérdezni szeretném higy be-e kerülhetne? 
/sfcalc a parancs, ott megynilik egy menű és kiválasztja az ember hogy milyen itemet szeretne kraftolni majd kiírja lebontva hogy mi kell hozzá (hány copper dust stb)

https://github.com/Seggan/SFCalc

**Comment by andris155** [comment]
Skriszt már rég kérdeztem erről. Nem mondott rá semmit, ezért nem került még be.

**Comment by skrisz0101** [comment]
nemtom mennyire lenne hasznos, de sok port nem kavarna

**Comment by andris155** [comment]
Beraktam. Majd holnap betölt.

**Comment by mnb124** [comment]
Köszi
