### ISSUE TITLE
/recipes bug

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4356]
**Szerver**:Savsziget

Savszigeten nem működik a /recipe parancs (ha rákeresek valamire aminek eleve volt receptje akkor nem ad rá ki semmit), a /recipes parancsra pedig azt írja ki, hogy: you lack the permission customcrafting.omd.recipes.

**Comment by andris155** [comment]
Frissült a plugin és teljesen megváltozott. Sajnos a ,,fust" és ,,szuli" eszközök és tárgyak nem működtek az új verzión. Ezeket majd újra be kell állítani.
A könyves megoldás nincs többé. A /recipes parancs van hozzá, meg majd frissül a /receptek parancs is.

**Comment by andris155** [comment]
Adtam jogot a parancshoz. Köszi a jelentést.
