### ISSUE TITLE
Levédett területek rongálása Slimefun Luckyblock "jutalmak" által.

### ISSUE THREAD

**Issue by TamasB14** [TheOld-Crafters/Minecraft-servers#4357]
Ez a Survival szerveren jelentkető hiba, amivel akár mások területét is képesek vagyunk pár szerencsétlen leidézett dolgokkal rongálni. Vannak szerencsétlen luckyblockok, melyek valami kis struktúrákat tudnak megidézni, akárcsak egy Obszidián fal benne vízzel. Ezekre egyáltalán nincs szabályozás, így ha valaki levédett területén kívülre teszek luckyblockot, majd besétálok a területre és az ő területén ütöm ki a kívül levő szerencsétlen lucky blockot, így nagy eséllyel tud idézni struktúrákat, amik átcserélik a blokkokat. Szóval ha valaki eléggé szélére épített valami drága farmot, és én a luckyblockot a terület nem levédett részére rakom, majd ráállok a farmjára és úgy állok be, hogy még pont kitudjam ütni a luckyblockot, akkor nagy eséllyel rám idéződhet valami "unlucky" struktúra, ami áthelyezi a blockokat. Próbáltam telkeken is, és működött. 

Ajánlott megoldás?
- Legalább 6 blokkra játékos által levédett helyre ne lehessen letenni luckyblockot

Példa:
![2021-02-04_17 44 53](https://user-images.githubusercontent.com/26002677/106927323-551d7c00-6712-11eb-87a9-fceca9aea6c4.png)

**Comment by andris155** [comment]
Már jelentett hiba. Sajnos nem tudom megoldani ezt.
