### ISSUE TITLE
Woodcutter android megakad

### ISSUE THREAD

**Issue by HunGamerFake** [TheOld-Crafters/Minecraft-servers#4358]
**Szerver**:survival

![2021-02-04_17 23 32](https://user-images.githubusercontent.com/34073812/106927085-18518500-6712-11eb-94ab-11603b7f8a23.png) ha folyamatosan megy a fákra bonemeal, olyan gyorsan megnőnek hogy az android mielőtt kivágná teljesen az egyik fát ami mellette van, már megnől a másik és nem áll meg lerakni a fát meg az üzemanyagot felvenni, így felhalmozódik és amikor megtelik akkor nem üti tovább a fát és ki kell üríteni, ha sokáig nem ürítjük akkor üzemanyaggal is meg kell tölteni.

**Comment by KingDeadZ** [comment]
Ez miért hiba? Beállítás kérdése az egész szerintem.

**Comment by Sizarra** [comment]
Nem, nekem is így csinálja. Egyszerűen túl gyors neki, és "elfelejt" lepakolni, mert ott a következő fa.

**Comment by HunGamerFake** [comment]
valami olyasmit kéne hogy ha tele van akkor forduljon az interface irányába, tegye le és menjen vissza

**Comment by skrisz0101** [comment]
Lassítsd a csontliszt adagolást
Nálam sose áll meg :D
