### ISSUE TITLE
sf - Fluffy wrench

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4359]
**Szerver**: Szurvi, gondolom sav is

Ezzel elvileg gyorsan lehetne kiütni a cargo nodeokat és elektromos cuccokat, de nem csinál semmit se

**Comment by szofogado** [comment]
Ezt én is tapasztaltam savon, viszont nekem 1x kiszedte az egyik cargot egy kattintásra. Sajnos nem jöttem rá, hogy akkor miért szedte ki

**Comment by andris155** [comment]
Készítettem egy saját javítást hozzá addig, ameddig a hivatalos nem jelenik meg. Elvileg már működnie kellene így.

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
Ha van még ilyen blokk mindenképpen írjatok. A javításhoz csak bele kell írnom a listába igazából így most már.

**Comment by andris155** [comment]
Ha van még ilyesmi Slimefun tárgy mindenképpen írjatok. A javításhoz csak bele kell írnom a listába, amit készítettem hozzá.
