### ISSUE TITLE
/buyclaimblocks 10 millió blokk hibás kiírás

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4360]
**Szerver**: szurvi

hülyén írja ki az egyenleget

**Comment by skrisz0101** [comment]
nekem pl: 5.3654654634534E8

**Comment by Sanszi** [comment]
A teljes levédhető blokkjainak száma több mint 1 millió és nem tudja kiírni.

**Comment by andris155** [comment]
De kitudja írni, csak a plugin ezt így tárolja. Majd javítania kell a fejlesztőnek.

**Comment by andris155** [comment]
A vault adja át így a plugin-nak. 5.3654654634534E8 az 5.3654654634534 * 10 ^ 8 tehát 536546546. Ezen sajnos nem tudok változtatni.

**Comment by skrisz0101** [comment]
A szám az random volt, csak lusta voltam bemasolni xd
