### ISSUE TITLE
/sfcalc hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4361]
**Szerver**: Survival

Néha megy, néha nem, de általában nem. Rákattintok egy kategóriára, és nem történik semmi, bezárja az invet.

**Comment by mnb124** [comment]
Szerintem az adonokat nem támogatja :/ de ha ugy irod hogy /sfcalc lava_generator akkor megy elvileg

**Comment by andris155** [comment]
Már jelentettek egy ilyesmi hibát, szerintem ilyesmi történhetett nálunk is.
https://github.com/Seggan/SFCalc/issues/15

**Comment by andris155** [comment]
Ameddig nincs javítás hozzá, addig használjátok hozzá a parancsot. Köszi a jelentést.
