### ISSUE TITLE
halak

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4362]
**Szerver**: Szurvi

Kicsit fel lehetne tolni a trópusi halak chunk/hal számát?
5 is elég lenne :C

**Comment by andris155** [comment]
Nem szeretnék ezen állítani. A legtöbbször a játékosokat nem is érdeklik a halak, csak éppen mondjuk a tenger mellé költözött és ilyenkor meg teljesen feleslegesen csak terhelik a szervert.
