### ISSUE TITLE
Moblimit

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4364]
Survival ->

Nem tudok semmit sem a moblimitről, mert buta vagyok.🤔
Nem ártana kírni valahova azt, hogy minden eggyes mobnak mennyi a limitje/chunkon. A weboldalra egy cikk,  warp, vagy egy könyv is elég lenne.

**Comment by andris155** [comment]
Folyamatosan változtatni szoktam. Ha valamelyik érdekel kérdezd meg tőlem pl.: Discordon és szívesen leírom az éppen aktuálisat.
