### ISSUE TITLE
börtön idő

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4365]
**Szerver**: szurvi

nem telik még mindig, senkinél sem.
pl: noobminecraftos

**Comment by Sanszi** [comment]
Most teszteltem piroscolorral és kiengedte az idő letelte után.

**Comment by skrisz0101** [comment]
akkor csak a /seen nem mutatja hogy csökken az idő?

**Comment by Sanszi** [comment]
> akkor csak a /seen nem mutatja hogy csökken az idő?

Igen, sajnos az nem számol vissza.

**Comment by andris155** [comment]
Már jelentették a fejlesztőnek és javítást is csináltak hozzá. Remélhetőleg hamarosan elfogadják a javítást hozzá.

**Comment by andris155** [comment]
https://github.com/EssentialsX/Essentials/issues/3940

**Comment by andris155** [comment]
A hibát javították.
