### ISSUE TITLE
Craftbook hiba

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4366]
**Szerver**: Survival

![kép](https://user-images.githubusercontent.com/29709854/107082163-1102a800-67f4-11eb-89a2-7d4f261d6888.png)

Nem mennek Survin a craftbookos dolgok. 

(elv. piroscolor vette észre elsőnek, aki jelezte staff felé)

**Comment by andris155** [comment]
Most jó?

**Comment by MrZero1** [comment]
Igen, köszi!
