### ISSUE TITLE
!!!!!!Blokk letétel!!!!!

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4367]
**Szerver**: szurvi

tps 20, ping alacsony, de lehetetlen blokkokat letenni.
minden 5. letétel után rakja le (gm1 és gm0ban is)
blokk kiütésnél semmi probléma, egyedül a letételnél
KingDead küld videót ha kell
(Délután ilyen még nem volt, a lift hibával egyetemben)

**Comment by andris155** [comment]
Nincs köze a laghoz. Véletlen én írtam el egy dolgot. Most jó?

**Comment by skrisz0101** [comment]
aha
