### ISSUE TITLE
Fly a lobbyban

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4369]
Egy ideje van fly mindenkinek loginban. Arra gondoltam, hogy lehetne a lobbyban is.

**Comment by MrZero1** [comment]
Szerintem semmi akadálya. Úgyis szép a lobby, egy barrier tető kellene és kész :D

**Comment by skrisz0101** [comment]
Easteregg található az izzókő nőfej közepén (levegőben jó fent, lobby spawnja felett) 
aki leüti, azt örök kárhozatra ítélem

**Comment by MrZero1** [comment]
A barrier része az kész, mary segített benne.

**Comment by andris155** [comment]
Engedélyeztem a fly-t a lobby-ban is.
