### ISSUE TITLE
Survival rangok NPC

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4370]
A GUI megnyitása mellé ír egy ilyen üzenetet is.

![image](https://user-images.githubusercontent.com/16057404/107130178-47f7bd00-68cb-11eb-8073-9c56fb35135b.png)

**Comment by andris155** [comment]
Elvileg kikapcsoltam ezt a funkciót annál az NPC-nél. Köszi, hogy írtál.

**Comment by UDPSendToFailed** [comment]
Most is írja, csak angolul xd

![image](https://user-images.githubusercontent.com/16057404/107151069-f7cb3a00-6960-11eb-9a04-ed0a85a11241.png)
