### ISSUE TITLE
Survival - Mob befogó plugin

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4371]
A MyPet tiltva lett telekvilágban, így azzal nem igazán lehet mobokat szállítani, bekerülhetne mellé vagy helyette egy plugin, amivel ez megoldható. 

https://www.spigotmc.org/resources/mobs-to-eggs.69425/
https://github.com/Slimefun-Addon-Community/MobCapturer
https://www.spigotmc.org/resources/safarinet-premium-mob-catcher-plugin.9732/

**Comment by IciAlex** [comment]
Mobs to eggs-t adom :)

**Comment by andris155** [comment]
Ha már Slimefun van szerintem a Slimefun-os addon kellene. De a MyPet-nek akkor végképp nem lesz értelme szóval kikerülhetne. Főleg, hogy random eltűnnek a MyPet-ek az adatbázis hibája miatt.

**Comment by skrisz0101** [comment]
még régebben mondtam hogy ha javítanák a mobcapturert, akkor bekerülhetne, csak senki se jelentette a hibáját xd
szóval ha valaki jelenti, tuti javítják

**Comment by IciAlex** [comment]
Én mindha szóltam volna hogy be lehet fogni levédésen is.

**Comment by andris155** [comment]
Mivel úgy volt, hogy nem kerül be, ezért nem írtam aztán meg nekik a hibát. De most megírtam akkor, mert most talán akkor be is kerül így.

**Comment by andris155** [comment]
Nem lesz ilyen. A mob befogóval túl egyszerű tojásokat szerezni.
