### ISSUE TITLE
MOB Farm!

### ISSUE THREAD

**Issue by Goldie2000** [TheOld-Crafters/Minecraft-servers#4372]
**Szerverek**:

Sziasztok!

_Arra gondoltam, hogy milenne akkor hogyha lenne **MOB Farm**? (Ha már van sima farm is ahol állatokat lehet ölni).
És ha mobokat is lehetne ugyan úgy ölni mint ahogy állatokat, szerintem jobb lenne a szerver!_

By: **### _Goldie2000_**

**Comment by Sanszi** [comment]
/pwarp diamondgamer321, /pwarp skrisz01, /pwarp Icecroft, /pwarp aron556, /pwarp plaster, /pwarp zsombix stb. Szerintem felesleges eleve megadni mobfarmokat. Ha playereknek kell megépíteni, legalább ad valami célt a játéknak.

**Comment by skrisz0101** [comment]
pwarp kingdead :(

**Comment by Tomi321** [comment]
Elég lenne elmenned diagamer pwarpjára, nem hiszem hogy akad ott olyan mob amit ne tudnál farmolni
