### ISSUE TITLE
Barrel

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4373]
Szerver: Survi, gondolom Sav.

Barrellek néha kidobnak 1 stack itemet.

**Comment by mangoshell** [comment]
Megoldás: Vedd fel

**Comment by KingDeadZ** [comment]
nekem hibátlanul működnek

**Comment by IciAlex** [comment]
Gyere akkor és nézd meg. Szerintem valami olyasmi miatt hogy a cargo 1 stacket akar áttenni a gépbe, pedig abba csak 1db kell(szerintem)

**Comment by andris155** [comment]
Kellene az, hogy ezt hibát hogy tudom pontosan reprodukálni.

**Comment by andris155** [comment]
Ezzel így nem tudok mit kezdeni. Kellene a pontos rendszer, amit ha megépítek ez a hiba meg is történik, vagy, hogy mit kell csinálni ahhoz, hogy ez történjen.
