### ISSUE TITLE
Agresziv mobok telken

### ISSUE THREAD

**Issue by KerekHosting** [TheOld-Crafters/Minecraft-servers#4374]
A telken ha le helyezek egy agresziv mobot akkor az egy idö után el tünik, és ez miat nem lehet vas farmot épiteni.

**Comment by KingDeadZ** [comment]
Nevezd el a mobot, ez alap mcben is így van.

**Comment by KerekHosting** [comment]
![image](https://user-images.githubusercontent.com/71597619/107383363-34c63680-6af1-11eb-8bd6-604d9b312d03.png)
el van de még igy is el tünik

**Comment by andris155** [comment]
Hány falusid van összesen ott egy helyen?

**Comment by KerekHosting** [comment]
5

**Comment by KerekHosting** [comment]
de ugy 5 hogy fent van 3 lent van 2 25-30 block távolság magaságban

**Comment by andris155** [comment]
Nem tudom sajnos, hogy mitől tűnhet el. Esetleg próbáld meg megépíteni ezt a farmot a sima világban.

**Comment by andris155** [comment]
Ahogy olvasgatom létező probléma ez, de megoldást nem találtam.
https://papermc.io/forums/t/named-hostile-mobs-despawning-version-135/4492

**Comment by TamasB14** [comment]
Én piglint neveztem el és a szemem előtt despawnolt.

**Comment by andris155** [comment]
Ha éppen átalakult akkor lehet azért.
