### ISSUE TITLE
Jó lenne ha..

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4375]
_Survi_

**Jó lenne ha lehetne egyszerre 64-et venni shop tábláról, mert idegesítő hogy tele spameli a chatet.
Tudom hogy a /cstoggle kikapcsolja a spamet, de én pl látni akarom hogy mit kell feltöltenem.**

**Comment by HunGamerFake** [comment]
plusz vásárlást is felgyorsítja

**Comment by IciAlex** [comment]
Ja :P

**Comment by andris155** [comment]
Csak úgy lenne ilyen lehetőség, ha kikapcsolásra kerülne az, hogy a shift-tel eladjon mindent az adott dologból.

**Comment by IciAlex** [comment]
Ez mekkora Nubság de komolyan...

**Comment by mangoshell** [comment]
Ezt tuti valami mérnök találta ki.

**Comment by IciAlex** [comment]
Miért ne lehetne egyszerre... melyik okos volt az aki így programozta le?

**Comment by andris155** [comment]
https://github.com/ChestShop-authors/ChestShop-3/issues/384
Nem lehet és már írtam is nekik régebben.
