### ISSUE TITLE
Lámpásba bele lehet buggolni

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4376]
**Szerver**:Survi fix, savot nemtudom

Ha egy blockra lámpás van elhelyezve admin által védett területre, survival módban elég érdekesen buggolunk, ha ráállunk.

**Comment by Sanszi** [comment]
Visszadobál, ha megpróbálsz sétálni rajta, igaz?

**Comment by Jaffis** [comment]
Így van, Sanszi. 
Illetve nálam jelentkezett olyasmi is, hogy fel-fel dobált 1-2-3 blockot.

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a hibát a túlélő szerveren.

**Comment by andris155** [comment]
Lehetséges, hogy a cheat védelem frissítésében javították már.
