### ISSUE TITLE
Víz melletti grass_path blokkon nem lehet ugrani magasugrás II beaconnal

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4377]
Visszadob a nocheat.

**Comment by Sanszi** [comment]
Az anticheat is jelez rá.

**Comment by andris155** [comment]
@Sanszi Remélem ha olyanra jelez, ami hülyeség akkor azt ti is megírjátok nem csak UDPSendToFailed.

**Comment by andris155** [comment]
A hibát javították. Köszi a jelentést.

**Comment by andris155** [comment]
508 OCD
