### ISSUE TITLE
Nincs jog /gm 1-re mert gm1ben vagyok, pedig nem

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4378]
**Szerver**: szurvi

![2021-02-12_16 16 17](https://user-images.githubusercontent.com/29951969/107786192-d8ac1e00-6d4d-11eb-9719-ca88ba3b29be.png)
Látszik rajta h gm0-ban vagyok, de nem enged gm1-be
Relog megoldja de na

**Comment by andris155** [comment]
Nem tudok vele mit kezdeni, ha nem írod le, hogy hogyan lehet reprodukálni a hibát.

**Comment by skrisz0101** [comment]
fogalmam sincs, tök random
