### ISSUE TITLE
A (Kulcsos) ládákból kapott Enchanted Golden Apple és a Lucky blockból kapott Enchanted Golden Apple nem stackelhető

### ISSUE THREAD

**Issue by TamasB14** [TheOld-Crafters/Minecraft-servers#4379]
Survival szerveren vettem eddig csak észre.
Valamiben a kettő különbözik, de mégis ugyanaz.

Ládás: Valami NBT: 1 tag(s)-ben különbözik
![2021-02-12_17 19 53](https://user-images.githubusercontent.com/26002677/107828084-6573cd80-6d88-11eb-9967-414dd5889f12.png)

Lucky Blockos:
![2021-02-12_17 19 56](https://user-images.githubusercontent.com/26002677/107828002-3198a800-6d88-11eb-9ee8-b9b398eb360c.png)

**Comment by IciAlex** [comment]
-.-

**Comment by MrZero1** [comment]
Kicserélhetem, de egy idő után úgyis ilyen lesz :D

**Comment by andris155** [comment]
Majd ezt a plugint le kell cserélni.

**Comment by MrZero1** [comment]
> Majd ezt a plugint le kell cserélni.

Miért?

**Comment by andris155** [comment]
Mert elavult az egész. Nem fejleszti már senki jó pár éve.

**Comment by andris155** [comment]
Ezek a béna tárgy tárolások még az 1.12-ből vannak benne. Most meg már lassan az 1.17-nél járunk.

**Comment by andris155** [comment]
De szerintem egyelőre gyorsabb megoldani, hogy kiveszem belőle teljesen az item data részt, amit már nem használ semmi.

**Comment by andris155** [comment]
Frissítettem a plugint. Az item data teljesen kikerült belőle. Így már nem rak felesleges nbt-ket a tárgyakra.
