### ISSUE TITLE
Telkeken a "snow_form" flag ellenére sem keletkezik hó, ha havazik.

### ISSUE THREAD

**Issue by TamasB14** [TheOld-Crafters/Minecraft-servers#4380]
Survival szerveren a telkeken jelentkezik a gond.
A hóesés a "flag weather rain"-nel lett bekapcsolva.

![2021-02-12_21 30 06](https://user-images.githubusercontent.com/26002677/107828246-be436600-6d88-11eb-9877-8e0e979a633c.png)

![2021-02-12_21 29 53](https://user-images.githubusercontent.com/26002677/107828333-f0ed5e80-6d88-11eb-8a4b-0cd3ea0cf211.png)

**Comment by Sanszi** [comment]
"Megoldás" (félig)
/plot setbiome snowy_tundra (Elittől elérhető)
/plot flag set weather rain (vagy "on", mindegy)
/plot flag set snow-form true

Ez lenne a megfelelő módszer, de mindezek ellenére sem formálódik hó.

**Comment by TamasB14** [comment]
snowy tundrára van állítva, weather rain ott van, snow form is ott van. Mégsem képződik

**Comment by andris155** [comment]
Engedélyeztem a snow-form flag-et alapból így nem kell állítani ezen semmit most már. 
Az itt szereplő ,,Snowy biomes" éghajlatokon fog csak hó esni a telekre: https://minecraft.gamepedia.com/Biome
A telek időjárás és játékos időjárás nem számít. A világban kell esnie hozzá az esőnek/hónak, hogy havas legyen.

**Comment by andris155** [comment]
A hóember nem hagy havat sehol sem, mert elég csúnya ha összejárkálja a világokat sajnos mindenfelé.
