### ISSUE TITLE
Unicode karakterek /plot chat-en

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4381]
Survival

Unicode karakterek kiírhatóak plot chaten.
![unicode](https://user-images.githubusercontent.com/37781201/107845642-481d1e80-6ddd-11eb-925c-7dcf8fbc798d.PNG)

**Comment by andris155** [comment]
Majd az új ChatControl-ban meg kell ezt nézni. A jelenlegi már nem igazán támogatott.

**Comment by andris155** [comment]
Most próbáljátok ki majd, hogy működik-e még.
