### ISSUE TITLE
Youtube rang

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4383]
Van még olyan? mert nincs se /warp youtube se /youtube

**Comment by andris155** [comment]
Létezik még, de plugin már nincs hozzá és valószínűleg nem is lesz.

**Comment by skrisz0101** [comment]
Akkor esetleg lehetne hozzá valami leírás, hogy lehet szerezni vagy valami

**Comment by MrZero1** [comment]
Bocsi, de a /warp youtube eddig is elérhető volt.
