### ISSUE TITLE
Rgb - link

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4385]
**Szerver**: Mind

https://www.w3schools.com/colors/colors_picker.asp

Ezen az oldalon lehet RGB színeket keverni, lehetne engedélyezni, hogy ha kérdezik hogyan lehet RGB nicket csinálni, akkor el tudjuk küldeni.
![image](https://user-images.githubusercontent.com/69635280/107877708-5e56d780-6ece-11eb-9bce-574bf1d5badb.png)

**Comment by Sanszi** [comment]
Vagy lehetne pl /einfo rgb.

**Comment by mangoshell** [comment]
Vagy lehetne einfo rgb és lehetne küldeni is

**Comment by andris155** [comment]
Mindkettő lesz és majd az információs menübe is belerakom.

**Comment by UDPSendToFailed** [comment]
Ezt is lehetne engedélyezni: https://patorjk.com/text-color-fader/

**Comment by andris155** [comment]
Engedélyeztem a linkeket, létrehoztam az infó parancsot hozzá és bekerült az információs menübe is.

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
mangoshell játékos nincs a MineMarket-en.

**Comment by mangoshell** [comment]
Shryx_ a nevem
