### ISSUE TITLE
/shop 

### ISSUE THREAD

**Issue by vacesenpai** [TheOld-Crafters/Minecraft-servers#4386]
Savsziget

Semmitsem lehet eladni /shop-ban.
![2021-02-15_09 02 57](https://user-images.githubusercontent.com/79079473/107921765-42574280-6f6f-11eb-8d05-ec28a93e2387.png)

**Comment by mangoshell** [comment]
Én ezért OCD-t adnék!

**Comment by andris155** [comment]
Javítottam. Köszi a jelentést.
