### ISSUE TITLE
Könyv

### ISSUE THREAD

**Issue by cserooos** [TheOld-Crafters/Minecraft-servers#4387]
**Szerver**: Survival 

szóval ha van egy könyved, írsz az első oldalon egy szót vagy mondatot a legelső sorba, aztán ellapozol a 100. Oldalra és írsz 1 betűt aztán "kész" megnyitod a könyvet újra és kitörlöd az első oldalon lévő szót vagy mondatot majd ztánna "kész" és voilá kidob az anticheat

**Comment by Sanszi** [comment]
Andris, küldöm privátban, hogy mit írt ki az anticheat.

**Comment by andris155** [comment]
Most már lehet 100 oldalas könyveket írni. Köszi a jelentést.

**Comment by andris155** [comment]
508 OCD
