### ISSUE TITLE
/shop packed ice / tömör jég

### ISSUE THREAD

**Issue by vacesenpai** [TheOld-Crafters/Minecraft-servers#4388]
Savsziget

Nem lehet /shopban eladni a Packed Ice / Tömör Jeget.
![2021-02-16_15 54 47](https://user-images.githubusercontent.com/79079473/108079693-61d59480-706f-11eb-9be1-48b84767319b.png)

**Comment by andris155** [comment]
Most működik?

**Comment by Sanszi** [comment]
> Most működik?

Működik, teszteltük

**Comment by andris155** [comment]
508 OCD
