### ISSUE TITLE
login szurvi NPC

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4389]
**Szerver**: login
![2021-02-16_17 06 20](https://user-images.githubusercontent.com/29951969/108089034-6f901780-7079-11eb-8a95-bb3a93a7a9b7.png)

**Comment by andris155** [comment]
Nekem most meg tegnap este is jó volt. Szerintem ez megoldódott azóta. Azért köszi a jelentést.
