### ISSUE TITLE
Helyesírási hiba /warp ládák

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4390]
Survival

Az ingyenes fortuna kulcsot adó láda újra kinyitásánál van egy apró helyesírási hiba.
![helyesírási hiba](https://user-images.githubusercontent.com/37781201/108089728-360bdc00-707a-11eb-8cc8-5d85e84711dc.PNG)

A hibát akos92 nevű játékos jelezte.

**Comment by andris155** [comment]
Javítottam. Köszi a hibajelentést.
