### ISSUE TITLE
/ignore és P hiba?

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4391]
**Szerver**: szurvi

ha /ignore-vel vagy p-vel ignorálsz valakit, akkor látja hogy te mit írsz, nem tudom ez mennyire hiba, de zavaró

**Comment by Sizarra** [comment]
Mindig is látta. Te nem látod az övét.

**Comment by andris155** [comment]
Ha ignore-olod nem látod, amit ő ír. De ettől függetlenül ő fogja látni, amit írsz. Ennek így kell működnie és így is működik.
