### ISSUE TITLE
MyPet - Eltűnt a Ride skilltree

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4392]
**Szerver**: Survival

**Comment by KingDeadZ** [comment]
Le lett tiltva.

**Comment by UDPSendToFailed** [comment]
![image](https://user-images.githubusercontent.com/16057404/108129781-ef84a480-70ae-11eb-9851-bdc494470417.png)

**Comment by andris155** [comment]
Hibásan van megírva a plugin-ban ez a funkció így ez letiltásra került.
