### ISSUE TITLE
Teleport

### ISSUE THREAD

**Issue by Goldie2000** [TheOld-Crafters/Minecraft-servers#4393]
**Szerver**:

A **Survival** szerveren találtam a hibát!

Ha be írom hogy /warp bolt és ha ott szeretném hogy rám tpzzenek, pl: /tpahere (név) vagy /tpa (név) akkor nem lehetséges ez! Meg azt tudom hogy a Spawn határólja be, De ezt nem-e lehetne orvosolni?

**_By: Goldie2000_**

**Comment by mangoshell** [comment]
Miért akar valaki boltba tpzni

**Comment by Goldie2000** [comment]
Talán azért mert hogy megmutassam valakinek hogyan lehet pénzt farmolni!

Shryx_ <notifications@github.com> ezt írta (időpont: 2021. febr. 17., Sze,
22:18):

**Comment by andris155** [comment]
Majd ha lesz időm átfogom rakni egy teljesen új üres világba, ami az FPS-nek és TPS-nek is jót fog tenni. A spawn2 világból pedig letörlésre kerül az a rész.

**Comment by andris155** [comment]
Áthelyeztem, most már működik minden a boltban is.
