### ISSUE TITLE
Levédett területen "Védd le a területed" üzenet.

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4396]
Survival

Levédett területen random kiírja a chatre a következőt:
![image](https://user-images.githubusercontent.com/37781201/108516072-1537c680-72c6-11eb-8b82-a955aefaf9f2.png)

Itt éppen a cargo output node lerakása után írta ki, de kiírja más blokkokra is. Én nem tudtam reprodukálni saját levédésen ezt, viszont megnéztem és az ő területe teljesen le van védve.

A hibát Schmekkels jelezte.

**Comment by skrisz0101** [comment]
ilyen volt egyik nap velem is, tök random adta be ezt az üzenetet
ilyenkor a védéses parancsok fel megy, a másik fele nem megy

**Comment by Sanszi** [comment]
> ilyen volt egyik nap velem is, tök random adta be ezt az üzenetet
> ilyenkor a védéses parancsok fel megy, a másik fele nem megy

Nem oldotta meg, hogy törölted és újravédted?

**Comment by skrisz0101** [comment]
Nem lehetett törölni, mert nem érzékelte h ott a levédés xd
+akkor törölt volna minden védést is (város pl)

**Comment by andris155** [comment]
Most sem működik jól?

**Comment by andris155** [comment]
Ami ezt okozhatta szerintem azon változtattam. Majd írjátok meg, hogy jó-e lett.

**Comment by Sanszi** [comment]
> Ami ezt okozhatta szerintem azon változtattam. Majd írjátok meg, hogy jó-e lett.

Még mindig írja :(
