### ISSUE TITLE
MyPet pvp skilltree képesség

### ISSUE THREAD

**Issue by primusantica** [TheOld-Crafters/Minecraft-servers#4397]
**Szerver**: túlélő

Az ígért PvP skilltree képességet a pet nem kapja meg. Az élet regenerációval van a gond, ami nem hozza az értéket.

**Comment by Sanszi** [comment]
Teszteltem, működik.
Helyes alkalmazás: /pcst - PvP -> /petbeacon -> GUI-n belül válaszd ki az effektet amit szeretnél. -> Katt a Redstone blokkra a legfelső sorban (Emerald blokk legyen belőle). -> Válaszd ki, hogy csak rád vagy mindenkire hasson a hatókörben. -> Katt a zöld üvegre és kapsz hatást. (Legyen a pet level min. 85 ahhoz, hogy ez működjön.)
![petbeacon](https://user-images.githubusercontent.com/37781201/108576190-fca6cb00-731c-11eb-98b5-5b785367487f.PNG)

**Comment by primusantica** [comment]
Üdv. Nem a beaconnel van a gond. Amikor ramesz a pvpv skilltreere irja h
85.szinten milyen kepessegeket fog tudni a pet. Az egyik hogy 6hp regeneral
1mp alatt(maganak). Ezert huztam ki mert az jo. De amikot kihuztam azt a
6hpt 180masodperc alatt regeneralja


Sanszi <notifications@github.com> ezt írta (időpont: 2021. febr. 20., Szo
1:44):

**Comment by andris155** [comment]
Tényleg elvolt írva a leírás is meg a beállítás is hozzá. De legalább 2-3 éve így volt már. Azóta nem tűnt fel ez senkinek, ami érdekes.

**Comment by andris155** [comment]
A pvp skill most már 1 percenként ad 6 életet.

**Comment by andris155** [comment]
2032 OCD

**Comment by andris155** [comment]
Sajnos nem találtam primusantica MineMarket fiókot. Kinek adjam az OCD-t?
