### ISSUE TITLE
EventGUI vissza gomb

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4399]
Survival

Az eventguiban a vissza gomb egy "alex" fej. Ha nem lehet a headsből megoldani, megfelelne egy barrier is oda.
![2021-02-19_21 47 05](https://user-images.githubusercontent.com/37781201/108559934-47641b00-72fc-11eb-937a-52db28c04e37.png)

**Comment by andris155** [comment]
Biztosan nem lesz barrier. Ennek nem így kellene működnie. Eddig nem értem miért nem tűnt fel senkinek. :/

**Comment by skrisz0101** [comment]
Eddig nek nyíl volt ott

**Comment by Sanszi** [comment]
Én is úgy emlékeztem, hogy nyíl volt ott. Bár sosem használom a vissza gombot, mindig Esc-et használok.

**Comment by MrZero1** [comment]
Nyíl volt, igen. Eddig.

**Comment by andris155** [comment]
A forráskódot, amit poma feltöltött abban ez volt pedig. Csak persze skinnel együtt kellene lennie.

**Comment by andris155** [comment]
<img width="260" alt="Screenshot 2021-02-20 140847" src="https://user-images.githubusercontent.com/8324198/108596422-30b5d680-7385-11eb-82b8-f67c3b89e725.png">
Nekem eredeti játékkal most van skine a fejnek.

**Comment by Sanszi** [comment]
Nálam is látszódik.
