### ISSUE TITLE
Eventvilágban külön inventory

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4400]
**Szerver**: Survival

Elég zavaró, hogy minden egyes event előtt le kell pakolni, sokan ezért nem mennek, lehetne ott a normál világoktól elkülönített inv.

**Comment by andris155** [comment]
Sajnos ezt nem tudom jobban megoldani. Ha mentegetjük az inventory-t, akkor az volt mindig a probléma hogy elvesztek a játékos tárgyai belőle. Így legalább ilyen probléma nincs.
