### ISSUE TITLE
ChestShop fordítás hiányosság

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4401]
**Szerver**: Survival

Ha jobbklikkelek egy ChestShop ládára, amit nincs jogom megnyitni, ezt írja. 

![image](https://user-images.githubusercontent.com/16057404/108607876-68437380-73c3-11eb-991b-60656cd3c5bf.png)

**Comment by andris155** [comment]
Beraktam az új fordítást. Köszi a jelentést.
