### ISSUE TITLE
Pwarp hiba

### ISSUE THREAD

**Issue by HunGamerFake** [TheOld-Crafters/Minecraft-servers#4402]
**Szerver**:Survival

 nem lehet eljutni a pwarpomra mert amikor beírod a parancsot, csak a neveket írja ki hogy kinek van pwarpja. /pwarp set se ment /setpwarp az viszont igen, de így sem megy a teleport

**Comment by andris155** [comment]
Mi a pwarp neve?

**Comment by HunGamerFake** [comment]
Bazsaaa

**Comment by andris155** [comment]
Most jó?

**Comment by HunGamerFake** [comment]
mostmár jó köszi szépen! :)
