### ISSUE TITLE
ChatControl hiba (?)

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4403]
Nem írtam előtte percekig semmit chatre, mégis figyelmeztet spamért. 

![image](https://user-images.githubusercontent.com/16057404/108624519-b436fc80-7445-11eb-8aa0-f98b46d9cf8d.png)

Update: Hosszabb üzenetekre jelez. 

![image](https://user-images.githubusercontent.com/16057404/108624596-1f80ce80-7446-11eb-90e3-0c6496435575.png)

**Comment by andris155** [comment]
Javítva
