### ISSUE TITLE
Efficiency 15-ös bug

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4404]
**Szerver**:Savsziget, gondolom Survi is

 
Sikerült találnom egy buggot, ami segítségével az Old Csákányokon fel lehet vinni az Efficieny enchantot 10-ről 15-re. A buggot szívesen bemutatom egy adminnak, vagy tulajnak, nem szeretném ide leírni, hogy hogy működik, mivel mit is mondjak elég op.

-Tomi_YT

**Comment by Tomi321** [comment]
További teszteket csináltam, mégse olyan op, mint aminek hittem. Mcmmo skill használata után azonnal eltűnik, nem egy hosszúéletű bug.

**Comment by KingDeadZ** [comment]
így működik az mcmmo btw

**Comment by Tomi321** [comment]
A lényeg az volt, hogy ha mcmmo skill használata közben felteszed ah-ra az itemet, majd a skill lejárta után leveszed rajta marad az enchant. Viszont ha újra használod a skillt akkor utána leveszi róla, szóval nem egy nagyon op bug sajnos.
