### ISSUE TITLE
Fordítások

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4409]
**Szerver**: gondolom mindenhol

ha 1mp-n bellül írok ki valamit, akkor kiírja h lassabban (angolul)
képet lusta voltam csatolni xd

**Comment by andris155** [comment]
Rengeteg fordítás hiány van a szerveren. Remélem nem írsz mindegyikről ide. Sajnos nem igazán van időm már ezekkel foglalkozni. De a Facebook csoportba majd fogok tenni egy linkeket, ahol ha valaki ráér és van kedve ezzel foglalkozni és segíteni akkor letudja fordítani a dolgokat.

**Comment by skrisz0101** [comment]
nem nagyon láttam még, azért írtam ezt külön xd

**Comment by andris155** [comment]
Feltöltöttem a ChatControlRed fordítását. Ha valaki szeretne vele foglalkozni, akkor bőven elég azt lefordítani, amit használunk a szerveren, vagy szerinte majd fogunk használni.
https://github.com/TheOld-Crafters/Minecraft-servers/blob/master/Ford%C3%ADt%C3%A1sok/ChatControlRed/messages_en.yml

**Comment by andris155** [comment]
Ezek a fordítások hiányzok még a szerverekről, ha esetleg valaki szeretne segíteni benne:
ArmorStandEditor: https://github.com/TheOld-Crafters/Minecraft-servers/blob/master/Ford%C3%ADt%C3%A1sok/ArmorStandEditor/hu_HU.yml

BentoBox: https://gitlocalize.com/repo/2855/hu/src/main/resources/locales/en-US.yml
BentoBox Biomes addon: https://gitlocalize.com/repo/2894/hu/src/main/resources/locales/en-US.yml
BentoBox Challanges addon: https://gitlocalize.com/repo/2896/hu/src/main/resources/locales/en-US.yml
BentoBox Greenhouses addon: https://gitlocalize.com/repo/2897/hu/src/main/resources/locales/en-US.yml
BentoBox Level addon: https://gitlocalize.com/repo/3013/hu/src/main/resources/locales/en-US.yml
BentoBox Warps addon: https://gitlocalize.com/repo/2973/hu/src/main/resources/locales/en-US.yml
BentoBox MagicCobblestoneGenerator addon: https://gitlocalize.com/repo/2972/id/src/main/resources/locales/en-US.yml

**Comment by andris155** [comment]
Itt lehet javasolni más fordításokat a Jobs-hoz, ha valamelyik nem jó: https://crowdin.com/translate/jobsreborn/90/en-hu

**Comment by andris155** [comment]
https://github.com/TheOld-Crafters/Minecraft-servers/blob/master/Ford%C3%ADt%C3%A1sok/PlayerWarps/lang.yml

**Comment by andris155** [comment]
PlotSquared fordítás: https://intellectualsites.crowdin.com/u

**Comment by andris155** [comment]
Slimefun fordítás: https://crowdin.com/project/slimefun/hu

**Comment by KingDeadZ** [comment]
ha lesz rá időm, és kedvem az sf fordítást folytatom

**Comment by andris155** [comment]
EssentialX fordítás: https://crowdin.com/translate/essentialsx-official/8/en-hu

**Comment by IciAlex** [comment]
Itt maradt még valami amit le kell fordítani?

**Comment by andris155** [comment]
Bőven. :D

**Comment by IciAlex** [comment]
És melyik? 😅

**Comment by andris155** [comment]
PlotSquared, EssentialsX, PlayerWarps. Ezek biztosan nincsenek még lefordítva teljesen.

**Comment by andris155** [comment]
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4727
