### ISSUE TITLE
Survival - Nincs ignore jog

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4410]
![image](https://user-images.githubusercontent.com/16057404/108755500-a10c5580-7547-11eb-864a-d23ef43ebf37.png)

**Comment by andris155** [comment]
Hát igazából van, csak a /eignore paranccsal megy. De majd megnézem mi a legjobb megoldás, hogy a sima ignore-al működjön.

**Comment by andris155** [comment]
Javítottam. Köszi a jelentést.
