### ISSUE TITLE
GriefProtection /trustlist bug

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4412]
**Szerver**: Survival

Schmekkels levédésén valamilyen bug van. Sem én, sem ő nem férünk hozzá a /trustlist-hez. (Nem ismeri fel a pozíción a levédést)
Képeket mellékelem:
![image](https://user-images.githubusercontent.com/29151964/108776726-0d488280-7563-11eb-84c5-2f9d2b8de5ce.png)
![image](https://user-images.githubusercontent.com/29151964/108776732-0faadc80-7563-11eb-9f6b-aa2b098fa6bd.png)

Esetleg ha kellenek a koordináták:
-6512 Y -4065

**Comment by skrisz0101** [comment]
Ez is ahhoz a bughoz köthető, ahol random kiírja hogy,,itt mások is építhetnek", miközben le van védve.
itt is leírom: ilyenkor a védésnélba parancsok feléhez van jogod, felismeri a védést, a feléhez pedig nincs, nem ismeri fel a levédést

**Comment by andris155** [comment]
Ez a hiba azóta van, mióta bekerült a gpteleport nem?

**Comment by andris155** [comment]
Kivettem a gpteleportot, talán az okozza. De amúgy ötletem sincs mitől ilyen sajnos ezenkívül. Majd írjatok, hogy jó-e lett.

**Comment by Laci444** [comment]
Mostmár jó :D
