### ISSUE TITLE
Hex színek Hiánya

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4413]
Szerver: Survival

Semmilyen essentialsos parancsnál nem mutatja az rgbt, hanem a képhez hasonlóan mutatja. mcmmonál szintén, tabon hibátlan
![image](https://user-images.githubusercontent.com/38157910/108843464-03fafc80-75db-11eb-8b4e-72c3e6345ee7.png)
Edit: Staffchaten is ilyen.

**Comment by andris155** [comment]
hmmm ez egy nagyon érdekes hiba.

**Comment by andris155** [comment]
Visszaraktam a régi verziót, amiben ez még jó, ameddig erre nincs megoldás.

**Comment by andris155** [comment]
Javították.
