### ISSUE TITLE
Chatcontrol fordítás hiányosság

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4415]
**Szerver**: Survival

Ha caps lockal írok, akkor ezt az üzenetet kapom.
![image](https://user-images.githubusercontent.com/34820798/108864943-f7829e00-75f2-11eb-8daf-e918fdb34603.png)

**Comment by andris155** [comment]
Bizonyos karakterszámig lehet csak nagybetűket írni, de amit írtál mint láthatod az is eléggé spam szerű. Ha lehet kerüld az ilyeneket.

**Comment by Sizarra** [comment]
Itt igazából a fordítás hiánya lett volna a lényeg.

**Comment by andris155** [comment]
Azt a hibát már jelentették.
