### ISSUE TITLE
spam védelem

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4416]
**Szerver**: mindenhol

sztem vagy az 1mp írás időt kéne levenni, vagy azt, hogy ne dobjon ki ha csak simán túl gyorsan írunk. Nem tehet róla sok ember, hogy tök gyorsan ír xd (több embert is kidobott már, ami nem spam volt)

+1: ha ugyanazt a szót/mondatod írod ki, lehetne 5mp a várakozási idő, a 10mp valódi várakozás sokkal több, mint csak így leírva

**Comment by andris155** [comment]
Módosítottam rajta.
