### ISSUE TITLE
Végtelen gyöngy "addolás" Multitool(+ energia) segítségével.

### ISSUE THREAD

**Issue by TamasB14** [TheOld-Crafters/Minecraft-servers#4418]
Ha levédett területen használom a multitool endergyöngy teleportálást, ahol az endergyöngyös teleportálás nem engedélyezett, akkor a kiadott gyöngyöt beleteszi az inventorymba, így ha van feltöltött multitool, akármennyi gyöngyöt tudok "adni" magamnak, szimpla energiából.

A képek előtt nem volt gyöngy az inventorymban.
![2021-02-24_10 15 37](https://user-images.githubusercontent.com/26002677/108978461-e46edd00-7689-11eb-87a1-20c666caf3cc.png)

![2021-02-24_10 15 31](https://user-images.githubusercontent.com/26002677/108978488-ec2e8180-7689-11eb-9e6d-1a478f058005.png)

**Comment by andris155** [comment]
Ezt egyszer már megírtam a Griefprevention-nak. A teleportálás blokkolást ki lehet kapcsolni, viszont akkor ender pearl-el betudsz menni mások védésére. Ha be van kapcsolva, akkor ha a plugin blokkolta és, ha a teleportálást ender pearl okozta, akkor hozzá adja az eszköztáradhoz az ender pearl-t. Ez nem egy kapcsolható funkció. Gondolom azért sem, mert a vanilla játéknél ezt valóban felesleges is lenne kapcsolgatni.

**Comment by andris155** [comment]
Megírom a Slimefun-nak is ezt, de ott szerintem csak annyit fognak írni, hogy ez nem a Slimefun hibája.

**Comment by skrisz0101** [comment]
Akkor se nagy probléma ha nem kerül javításra, egy Enderman farm 100x gyorsabb, van egy csomó

**Comment by andris155** [comment]
Készítettem egy saját javítást. Így ez a hiba javítva lett.

**Comment by andris155** [comment]
508 OCD
