### ISSUE TITLE
Több ,,különleges event"

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4419]
**Szerver**: szurvi, sav

Több lehetne ezekből az eventekből, nem évente 3x
Esetleg valami rendszerességgel. Pl Minden 2. szombaton lesz raktár, minden hónap végén drogon, mittomén
Eventek:
Raktárvadász
Kódkereső
Drogonkincse

**Comment by MrZero1** [comment]
Nyári szezonban lesz esedékes, megnézzük mennyire lesz rá 'kereslet', ha igen, utána is kialakítunk egy menetrendet rá.
