### ISSUE TITLE
/baltop színes egyenleg (?)

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4421]
**Szerver**: szurvi, gondolom sav is

![2021-02-25_11 01 37](https://user-images.githubusercontent.com/29951969/109137286-519d7380-7759-11eb-800f-a7438c87eabf.png)

Nem tudom hiba-e, de az egyenleget olyan színnel írja, mint a nick vége.
Nekem igazából tetszik, csak gondoltam jelentem, hátha hiba

**Comment by andris155** [comment]
Így jobban néz ki amúgy. xd
Miért kell annyi levelet tárolni amúgy? Nem lenne ezerszer egyszerűbb lementeni egy fájlba amiben utána tudsz keresni is?

**Comment by skrisz0101** [comment]
jó ez így, érzem a törődést xd
szerintem is szebb, szóval akkor le is zárom

**Comment by andris155** [comment]
Biztosan javítják már. Egyelőre még nem igazán működik jól a pluginokkal a Paper által felújított hex színkód támogatás.

**Comment by andris155** [comment]
Biztosan javítják majd. Egyelőre még nem igazán működik jól a pluginokkal a Paper által felújított hex színkód támogatás.
