### ISSUE TITLE
Item keresése a slimefun könyvben.

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4422]
Survival, savsziget.

A könyv jobb felső sarkában lévő keresés gombra kattintva a chatre kell beírni a keresett itemet, viszont nem lehet vele keresni, mert a chatcontrol tesz egy .-ot a szó végére. 
![2021-02-25_12 00 58](https://user-images.githubusercontent.com/37781201/109144510-8f05ff00-7761-11eb-8400-a6d06bf6f1ad.png)

**Comment by andris155** [comment]
Ha 5 karakternél kevesebb akkor lehet vele keresni. Ez viszont valóban problémás így.

**Comment by andris155** [comment]
Javítottam. Köszi a jelentést.
