### ISSUE TITLE
refréngyümi flag levédésre

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4424]
**Szerver**: szurvi

Néha elég kellemetlen lehet ha valaki refréngyümölcs segítségével kijut valahonnan, amit nem szeretnénk (mint warp bolt)
lehetne flag rá, hogy ez tiltott legyen a levédésen.
(van ilyen flag, ha jól emlékszem, csak engedélyezni kell)

**Comment by MrZero1** [comment]
Van ilyen flag, igen, javasoltam is tegnap az adminoknak. 

Működik a flag amúgy?

**Comment by Sanszi** [comment]
én nem találtam claimflagek között, de plotflagek között sem :/

**Comment by MrZero1** [comment]
RG flag van, többire nem hiszem, hogy van.

**Comment by andris155** [comment]
Az adminok szerintem ezt látták és tudják is. Ha valahova kell beállítják majd.

**Comment by skrisz0101** [comment]
Claimflag-ra gondoltam amúgy xd
Ami elérhető a játékosoknak

**Comment by andris155** [comment]
Alapból le van tiltva Griefprevention védésen, vagyis nem teleportál oda, ha éppen oda akarna.
