### ISSUE TITLE
Unicode karakterek

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4428]
**Szerver**: ???

 

Szerettem volna táblára írni egy × jelet (ezt szoktam elválasztóvonalként használni), de nem engedi. 
![kép](https://user-images.githubusercontent.com/29709854/109389758-11cbbd00-790e-11eb-8565-194f4dcc285e.png)

**Comment by andris155** [comment]
Engedélyeztem ezt a karaktert.
