### ISSUE TITLE
Mob spawn rate

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4429]
Több mint egy a hete a természetes spawnolású mobok spawnrate-je olyan alacsony lett survavilön, hogy gyakorlatilag kikerültek a játékből. Kb 5 percenként spawnol 1 db pillager. Így nemhogy lvl 5 átkot nem lehet összgyűjteni, de egy óra is kevés a lvl 1-hez is. Alig lehet egyéb mobbal is találkozni. Csak szaladgálok éjszaka és sehol egy mob :(

**Comment by andris155** [comment]
Módosítottam a változtatásokon. Holnap majd betölt.

**Comment by andris155** [comment]
Módosítottam a beállításokon. Holnap majd betölt.

**Comment by Icecroft** [comment]
Köszi, majd tesztelem!

**Comment by andris155** [comment]
Ha vannak még ilyen dolgok nyugodtan írj. Sajnos mindent nem tudunk teljesen tesztelni, ha valamit megváltoztatunk.

**Comment by andris155** [comment]
Már jónak kellene lennie.

**Comment by Icecroft** [comment]
Szia Andris, egész jól működik a változtatás, a pillagerek szépen spawnolnak, kb 15-20 perc volt egy lvl 5 átok összegyűjtése, majdnem mint régen. Köszi!
