### ISSUE TITLE
"Üres" telek és az SF

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4431]
Survi:
Vegita telkén leraksz blockot és ami ott volt előtte sf cucc, azt kidobja:
https://www.youtube.com/watch?v=txpHzTI9SrA&feature=youtu.be

**Comment by andris155** [comment]
A telek törlést nem támogatja a Slimefun.

**Comment by IciAlex** [comment]
:)

**Comment by MrZero1** [comment]
Tehát akkor ezzel bármennyiszer lehet "visszaszerezni" a ploton lerakott SF-es dolgokat?

**Comment by andris155** [comment]
Mint a videón is láthatod egyszer adja vissza, mivel hiába törli a clear vagy delete paranccsal attól még az adatbázisban ott marad és ha lerak valaki valamit oda, akkor megkapja azt az egy dolgot onnan.

**Comment by andris155** [comment]
Én javaslom is rakjatok le oda blokkokat, hogy ne maradjanak ott a Slimefun dolgok úgy, hogy igazából ott levegő van.

**Comment by andris155** [comment]
Aztán persze utána ki lehet ütni a blokkokat, ha már nincsenek ott a Slimefun dolgok.
