### ISSUE TITLE
Cargo

### ISSUE THREAD

**Issue by KerekHosting** [TheOld-Crafters/Minecraft-servers#4435]
Golden pan-re nem lehet rá tenni a cargos dolgokat.

**Comment by KerekHosting** [comment]
![image](https://user-images.githubusercontent.com/71597619/109677619-22806b00-7b7a-11eb-9228-1995c7319d55.png)
tetejére.

**Comment by UDPSendToFailed** [comment]
A gépek aljára és tetejére nem lehet cargo-t rakni, csak az oldalaikra.

**Comment by KerekHosting** [comment]
ohh oksa

**Comment by IciAlex** [comment]
úr isten...
