### ISSUE TITLE
Survival - Spawnerek engedélyezése telken

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4436]
Sokkal egyszerűbben, kevesebb cargo-val és tölcsérrel lehetne megoldani néhány dolgot, ha működnének a spawnerek telekvilágban.

**Comment by andris155** [comment]
@MrZero1 továbbra se engedélyezzük a telkeken a spawnereket?

**Comment by MrZero1** [comment]
Továbbra sem.

**Comment by UDPSendToFailed** [comment]
Hát, nekem az is jó, ha a fél telket be kell építenem cukornád farmnak, hogy legyen csontpor, ami kiváltható lenne max 4-6 skeleton spawnerrel.

**Comment by andris155** [comment]
Építkezz a vadonba.

**Comment by MrZero1** [comment]
Pontosan. A vadon tökéletes a spawneres mobfarmok létrehozására. A plot kényelmesebb lenne, tény, mert azt nem kell levédeni, csak összekapcsolni 2-4 telket, de szerintem így is sok a kényelmi funkció a szerveren, ami miatt nincs kihívás.

**Comment by UDPSendToFailed** [comment]
Sokan azért építenek telekre, mert az nem törlődik, vadonban évente lehetne átpakolni mindent új világba, nem mindenkinek van kedve az egész területét, gyárát, boltját, stb szétszedni és újra összerakni.

**Comment by andris155** [comment]
A vadont sem tervezzük már többször törölni. Lesz egy fix vadon, meg egy olyan ami mindig törlődik. Értelemszerűen ami mindig törlődik oda nem sok értelme lesz majd építkezni.

**Comment by skrisz0101** [comment]
@andris155 a mostani 2 vadont se?

**Comment by MrZero1** [comment]
Tervek szerint az új 1.17 világ lenne az, ami megmarad, mellette egy ami nem.

**Comment by andris155** [comment]
Végülis megmaradhatna a mostani is. Csak bányákat módosítotják nagyrészt arra meg tökéletes az ideiglenes világ is, hogy tudjanak bányászni az új bányákban. Nem tudom miért kellene megint egy reset a mostani world2-re is. Semmi értelme.

**Comment by MrZero1** [comment]
Nekem az is jó, ha a mostani 1.15 vadon marad, legalább nem kell mégegy költözéssel szenvedniük.
