### ISSUE TITLE
Slimefun - Backpack hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4439]
Normál esetben nem lehet backpackeket egymásba rakni, de ha megnyomom a jobbklikket, és utána azonnal kidobom a backpacket Q-val, nem tiltja le a mozgatását inven belül.

https://youtu.be/8bCxJrYdhxQ

**Comment by lovi-dev** [comment]
A chat-et legalább kapcsoltad volna ki :)

**Comment by andris155** [comment]
Hát nekem ezt sehogy sem sikerült reprodukálni. Szerintem nagyobb a pinged és azért ilyen.

**Comment by andris155** [comment]
Még most is működik ez a hiba?
Ha igen, akkor jó lenne egy videó ahol világosabb van.

**Comment by UDPSendToFailed** [comment]
Saját szerveren nekem sem sikerült, valószínűleg a pingnek is van köze hozzá, mindjárt csinálok új videót.

**Comment by UDPSendToFailed** [comment]
Most éppen sikerült úgy, hogy ki sem dobta az invből. Jobbklikkel meg kell nyitni, és utána azonnal Q-t nyomni, egyszerre a kettő nem jó. 

https://youtu.be/FIeuKp0CWj4

**Comment by andris155** [comment]
Valószínűleg valamelyik plugin vagy beállítás okozza.

**Comment by andris155** [comment]
Nem tudom sajnos mi okozza ezt. Az egyik nap nekem is működött. De most megint nem és így nem tudom megkeresni, hogy melyik beállítás vagy plugin lehet.

**Comment by andris155** [comment]
A jelentést azért köszönjük.
