### ISSUE TITLE
tab - egyenleg

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4443]
**Szerver**: mindenhol

Szerintem tök jól nézett ki hogy ott volt tabon az egyenleg, vissza lehetne rakni :c 
Többen hiányolják

**Comment by andris155** [comment]
Van egy hiba, amit lehet ez okoz. Így egyelőre kísérleti jelleggel kivettem ezt. Délutánra kiderül, hogy tényleg ez okozta-e a hibát.

**Comment by andris155** [comment]
Visszaraktam.
