### ISSUE TITLE
/warp jobs

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4444]
**Szerver**: szurvi

leírásokkal, stb

**Comment by MrZero1** [comment]
Nyilván tervben van, de tegnap este 11 előtt került be, és nem mindenkinek van otthoni suli 🙂

**Comment by skrisz0101** [comment]
ja k, csak gondoltam megírom mert miért ne :c

**Comment by Sanszi** [comment]
Igazából megírhat egy alapot bárki, te is sk

**Comment by skrisz0101** [comment]
nem értek hozzá nagyon

**Comment by MrZero1** [comment]
Kész. /warp munka
