### ISSUE TITLE
/küldetések és /küldetés, kuldetesek, kuldetes (jobs küldetések)

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4445]
**Szerver**: szurvi

lehetne alias parancsot beállítani a jobsos küldetésekre, ezzel jobban ki lehetne emelni azt, h vannak küldetések is. Sokan nem tudnak róla (jobsról se még, nem hogy a küldetésekről)

**Comment by andris155** [comment]
Nem kevernék össze inkább ezzel senkit. Jobb ha tudják, hogy ez a Jobs része.

**Comment by skrisz0101** [comment]
sztem felesleges tudniuk h honnan származik, inkább azt kéne tudniuk hogy van ilyen :/
