### ISSUE TITLE
Élvezetesebb lobby/login plugin

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4447]
**Szerver**: login/lobby

a régebbi plugin jobb volt, azzal lehetett funolni, mint pl a bárány vonat vagy trambulin. mostaniban nincs semmi hasonló :(
nincs valami jobb?

**Comment by andris155** [comment]
Csak annyit vagy fent ezeken a szervereken általában, hogy szervert válts. Nem tudom, hogy van-e értelme így ezek beállítására időt szánni.

**Comment by skrisz0101** [comment]
néha előforduló szerver resi, leállás, stb-knél több idő is eltelhet, de azt megértem hogy nem elsődleges dolog ez xd

**Comment by andris155** [comment]
Egyelőre ilyet nem szeretnék, mert ami van és elterjedt plugin erre abban rengeteg hiba van. Esetleg lehetne valami parkour majd a jövőben ahol lehetne ugrálni vagy valami ilyesmi. @MrZero1
Próbálunk azon is fejleszteni, hogy a lehető legkevesebb ilyen leállás legyen.

**Comment by andris155** [comment]
Az ötletet azért köszönjük.
