### ISSUE TITLE
sav - küldetés dizájn

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4449]
**Szerver**: savsziget

Sztem elég csúnyán néz ki + sokak nem is tudják elolvasni a lilát. nem lehetne átdizájnolni a színezést?
![2021-03-09_11 54 36](https://user-images.githubusercontent.com/29951969/110460375-628da380-80ce-11eb-98c6-f34be6c11541.png)

**Comment by andris155** [comment]
Így is megérti mindenki. Több 100 fájlban kellene átírni. Inkább fontosabb dolgokat fejlesztek a szabadidőmben.

**Comment by andris155** [comment]
De az ötletet köszi. Talán ha eljutunk egyszer oda, hogy csak ilyen apróságokon lehet már fejleszteni akkor megvalósul majd. Esetleg ha az adminok ráérnek van hozzá menü is a játékban. De szerintem ők sem igazán érnek rá erre.
