### ISSUE TITLE
Sav - letiltott slimefun tárgyak

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4450]
**Szerver**: Savsziget

Jópár slimefun eszköz (csákányok) le vannak tiltva, ami azért lett tiltva szurvin, mert kreából lehet vele addolni. Sztem ezeket simán lehetne engedélyezni savon (expo csáki, ásó, meg még nemtom mi van fejből)

**Comment by andris155** [comment]
A túlélőn ezekre már rég van megoldás, hogy ne lehessen velük adolni. MrZeri-t kérdeztem erről és ő mondta, hogy ezek így se legyenek inkább engedélyezve.

**Comment by skrisz0101** [comment]
Eh
