### ISSUE TITLE
Sav - /Beváltó

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4454]
**Szerver**: savsziget

Bent van még a hirdetés jog /beváltó-n
(+eléggé nagy, ahhoz képest h ilyen kevés cucc van benne)

**Comment by andris155** [comment]
Töröltem ezt a warpot. Ha lesz mit beváltani akkor majd visszakerül. 330 OCD

**Comment by andris155** [comment]
Módosítottam rajta. 508 OCD
