### ISSUE TITLE
Sav - receptek warp

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4455]
**Szerver**: Savsziget

Sehol sincs kint hogy hogyan kéne receptek könyvet csinálni és nem is tudja kb senki

**Comment by MrZero1** [comment]
Mert nincs is már könyv. /recipes a parancs, vagy /receptek

**Comment by andris155** [comment]
Már egy ideje nincs könyv.

**Comment by skrisz0101** [comment]
akkor a warpon át lehetne írni a táblákat sztem, bár sztem a warp is teljesen felesleges. Egy információ is bőven elég
Annyi van a warpon hogy létezik /receptek parancs

**Comment by andris155** [comment]
Felesleges a warp ahogy mondod így. Egy tábla miatt meg főleg. :D

**Comment by andris155** [comment]
köszi
