### ISSUE TITLE
Wither rombol telken

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4457]
**Szerver**: survival

A Wither rombol a telken, mikor megidézem wither assemblerrel, Kernelnél viszont nem jelentkezik ez a hiba.
![image](https://user-images.githubusercontent.com/34820798/110463440-33793100-80d2-11eb-9246-d41750d009bd.png)
A képen is látható, hogy egy 3*4 területen az obszidiánt kiszedte. (Tudtommal az obszidiánt nem is tudja kiszedni.)

**Comment by Sizarra** [comment]
> Megoldottam

Mégsem sikerült megoldani, ugyanúgy rombol. Csak szerintem azt már nem láttad Sanszi.

**Comment by Sanszi** [comment]
rg flagnél állítottam be, hogy ne tudjon rombolni, de ezek szerint nem segített

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt a telkeden.

**Comment by andris155** [comment]
![2021-03-12_18 58 13](https://user-images.githubusercontent.com/8324198/110979532-01cbc880-8365-11eb-88a9-9469c715bd23.png)

**Comment by Sizarra** [comment]
Én bent voltam a helyiségben, gm0ában és godban. A kilőtt kék wither fejek romboltak. Így, mivel nem érzékel entitárst nem is támad, ergo nem tud rombolni.

**Comment by andris155** [comment]
Folyamatosan lőtte a fejeket. De hiába robbantak nem rombolta le az építményt. :D

**Comment by Sizarra** [comment]
![image](https://user-images.githubusercontent.com/34820798/111024115-2794b400-83dd-11eb-9cf9-185ceee5532a.png)
Nekem még mindig rombol :S

**Comment by andris155** [comment]
Használd a Slimefun Wither poof blokkokat.
