### ISSUE TITLE
Survival Clear lag

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4459]
**Szerver**: survival

Mivel, bekerült a Jobs, lehetne mellette clearlag is, mert a jobs miatt elég sok droppolt item van most.

**Comment by andris155** [comment]
Abszolút értelmetlen. Gyakorlatilag a lebegő tárgyak törlése és keresése több erőforrást használ mintha nincsenek törölve. A játék  tárgyanként törli ezeket egy idő után. Annyit meglehet és meg is volt csinálva, hogy egy megadott tárgy/blokk típus hamarabb tűnjön el. Viszont ezzel az volt a probléma, hogy a Slimefun oltárról is eltűnt elég hamar. De volt aki arra is panaszkodott, hogy földről túl hamar tűnik el. Végül így inkább kikapcsoltam ezt és nem is szeretném továbbra sem ezt használni.
