### ISSUE TITLE
Jobs hibák

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4461]
- ~~Ércek kiégetéséért nem ad semmit~~  - Javítva
- McMMO növénytan képességgel automatán visszaültetett növényekre nem hat a restrictedBlocks.yml-ban megadott érték, csak a globális védelem, kézzel visszaültetett növényeknél hibátlan - Ma jó volt, 300 másodpercről számolja, talán a restart utáni második aratáskor áll be a védelem
- Eredeti fordításban vannak még hibák, #4409-hez be lehetne rakni

**Comment by Sanszi** [comment]
McMMO növénytan képességgel automatán visszaültetett növényekre nem hat a restrictedBlocks.yml-ban megadott érték, csak a globális védelem, kézzel visszaültetett növényeknél hibátlan

Nem tudom mennyire megoldható ez. Szerintem növényekről levenni a restrictiont és tiltani a water sprinklert.

**Comment by montlikadani** [comment]
> Az eredeti fordításhoz szerintem pull-t kellene nyitni a javításokkal. De amúgy a fejlesztő aki mostanában fejleszti magyar. Szóval érdekes, hogy a fordítást mégsem fejlesztette.

Ezért van a Crowdin, https://crowdin.com/project/jobsreborn

**Comment by andris155** [comment]
@montlikadani Nem néztem, hogy az is van. Köszi az infót. :)
