### ISSUE TITLE
kapocs - káromkodás jelző

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4462]
**Szerver**: mindenhol

a kapocs szóból a ,,pocs" részét kicsillagozza

**Comment by andris155** [comment]
Ha van kedved kereshetsz még ilyeneket, mert biztosan van. Ugye most már akkor is tiltja ezeket, ha elé írsz valamit (space nélkül) nem csak akkor ha utána.

**Comment by andris155** [comment]
Javítottam, köszi.
