### ISSUE TITLE
Jobs ötlet

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4464]
A rangosoknak lehetne valamilyen pénz boost, mert jelenleg, ha felvesz 5 munkát, sokkal kevesebbet kap, mint egy tag.

Tag: 97% $t kap egy blockból, 2munkával míg az Old csak 88%ot, 5el. 

Ha nem szeretne élni az 5 munkával emiatt az old, és 1-2van neki max és mást is szeretne húzni pénzért akkor ha a munkáját leadja, egy csomó szint elveszik, ami tökre unfair így szerintem

**Comment by Sanszi** [comment]
Cserébe van neki xp boost + lesz bolt, nem kell még több bónusz szerintem.

**Comment by UDPSendToFailed** [comment]
A pénz maradhat így, viszont xp-re elférne egy 30-50% a jelenlegi 16% helyett, napi 6-8 óra bányászással alig jutottam túl a negyedén, és folyamatosan lassul a szintlépés.

**Comment by KingDeadZ** [comment]
Hát az a 16% nem a legnagyobb dolog xd legalább 100%ra kijöhetne 5munkánál az old pénzszerzése, mert úgy ja...

**Comment by Sanszi** [comment]
> Hát az a 16% nem a legnagyobb dolog xd legalább 100%ra kijöhetne 5munkánál az old pénzszerzése, mert úgy ja...

Ha lesz bolt, az remélhetőleg megoldja az ebből adódó problémákat.

**Comment by skrisz0101** [comment]
bolttól függetlenül kap kevesebb manit az old mint a tag
Boltban is ugyanúgy el tudja adni a tag és az old is a cuccokat

**Comment by Sanszi** [comment]
> bolttól függetlenül kap kevesebb manit az old mint a tag
> Boltban is ugyanúgy el tudja adni a tag és az old is a cuccokat

Sokkal gyorsabban tud farmolni és gyorsabban lépi a szinteket egy old, mint egy tag.
