### ISSUE TITLE
Jobs hiba

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4465]
**Szerver**: Survival

Spleef eventen ad a jobs xpt, pénzt amikor ásom a havat.

**Comment by skrisz0101** [comment]
+motiváció xd

**Comment by UDPSendToFailed** [comment]
https://github.com/UDPSendToFailed/Jobs/commit/a8f5ac93d441a6d5255583e5d5624f5eec1c8f39

**Comment by andris155** [comment]
Javítottam.
Köszi.
