### ISSUE TITLE
jobs munkák újabb vadonban is

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4466]
**Szerver**: szurvi

jó lenne ha engedélyezve lenne vadon2ben is a bányász, favágó munka. Pl most épp kiástam egy fél tengert városépítés miatt, de nem jött semmi $, pedig ugyanúgy sokat ástam meg bányásztam :v

**Comment by MrZero1** [comment]
Direkt vannak letiltva, hogy ne azt a vadont fosszák ki, ami meg fog maradni. Ott a régivadon, ott jár pénz, illetve majd a jövőben abban a világban is fog járni, ami nem marad meg.

**Comment by skrisz0101** [comment]
akkor az 1.17es vadon lesz a kövi loot világ majd?

**Comment by MrZero1** [comment]
Igen, hogy ne keljen mégegyszer költözködni senkinek. Főleg annak akinek ekkora városa van 😬
