### ISSUE TITLE
Jobs Építész

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4467]
Survi:
Kreatívban letett blockokért is járhatna pénz meg XP

Például mapart építés közben akkor járna egy kis pénz.

**Comment by andris155** [comment]
Ilyen nem lesz.

**Comment by andris155** [comment]
Kreatívban csak globálisan lehet tiltani. Munkánkként nem. De amúgy se lenne értelme, mert amiket leraksz blokkokat, azokat nem te szerezted meg. A túlélőben azért, amiket leraksz blokkokat azokat meg is kell szerezni valahogy.
