### ISSUE TITLE
/pg - maradék játékok

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4468]
**Szerver**: mindenhol

régebben még ki lett véve pár minijáték a /pg-ből. az azóta se jó?

**Comment by andris155** [comment]
Én nem tudok ilyenről. Mi lett kivéve?

**Comment by skrisz0101** [comment]
az utolsó oldalon hiányos az oldal és tökre úgy rémlik. már nem emlékszem h mi

**Comment by andris155** [comment]
Nem tudom miért van letiltva pár. De nem lehet rajta állítani.
