### ISSUE TITLE
jobs - craftoló munka, shift

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4476]
**Szerver**: szurvi

nem ad a craftoló munka pénzt akkor, ha valamit shifttel craftolok
Elvileg csak Onra kell nyomni valami beállítást és jó lesz

**Comment by IciAlex** [comment]
pont most akartam volna írni :D

**Comment by UDPSendToFailed** [comment]
```
  Crafting:
    # With this true, player will get money for all crafted items instead of each crafting action (like with old payment mechanic)
    # By default its false, as you can make ALOT of money if prices kept from old payment mechanics
    PayForEachCraft: false
```

True-ra állítva fizet a shift + klikkes craftolásért.

**Comment by andris155** [comment]
Átírtam true-ra, de le kellene majd tesztelni, mert a komment azt írja, hogy ezzel rengeteg pénzt lehet szerezni.

**Comment by UDPSendToFailed** [comment]
Át lettek írva ennek is a fizetései az alap beállításról, olyan durván sokat így sem fog fizetni.
