### ISSUE TITLE
Fordítás hiba 

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4477]
**Szerver**: savsziget 

Ércgenerátornál:
![kép](https://user-images.githubusercontent.com/29709854/111040736-cac4e800-8434-11eb-90b8-b8cfb21aa4dc.png)

**Comment by driverdakid** [comment]
Ha a 250-as szintűre gondolsz, Azzal nem lehet mit kezdeni, egy fordítás van minden értékre.
