### ISSUE TITLE
Szabály

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4479]
Survi:

Szabály ami a Mapart építőket védi.
Ebben a szabályban annyi lenne hogy a Mapartokat készítő embertől kell engedélyt kérned, ha árusítani szeretnéd az alkotását.
Azért egy ilyen térképbe nem kevés órákat lehet beletenni, és valaki csak megveszi, lemásolja majd továbbértékesíti sok-sok haszonnal. Ha valaki megszegi akkor esetlek "lopás" (vagy valami hasonló) indokkal bünti.
Ha a készítőtől megkapta az engedélyt, akkor az általa megadott ár alatt nem lehet továbbadni.

**Comment by Sanszi** [comment]
Hogyan keresed vissza? Amúgy meg szerintem idő van benne, energia már nem igazán. Kreatívval odaállsz aztán csinálja a dolgát. :)

**Comment by IciAlex** [comment]
sanszi te tudod egyáltalán hogy működik?

**Comment by IciAlex** [comment]
Egyébként meg a legtöbbről tudjuk kicsinálta, de amiről meg nem tudnánk annak meg majd mondanak az adminok árat.

**Comment by Sanszi** [comment]
Igazából lehetne ilyen szabály, de tetten érni/nyomonkövetni nagyon nehéz lesz.

**Comment by IciAlex** [comment]
Hát úgy talán nyomon lehetne követni ha Discordon egy külön helyre beküldené a készítő a mapartokat, vagy egy /warp poszeterek és ott.
Nyomonkövetni meg hát... például a staffok se tudják 100%ra nyomonkövetni ha valaki lop, csak amíg észre nem veszik.
Na ennél is pont így lesz, hogy a staff és a készítő figyel, de nyilván ez se lesz 100%os.
Vagy nem tudom hogy lehet e egy olyan kis plugint csinálni hogy a már átnevezett térképet mégegyszer ne lehessen átnevezni, és akkor amint elkészül, a készítő csak átnevezni ahogy akarja, esetleg ír egy olyat is hogy "by xy".

**Comment by andris155** [comment]
,,4.8, Ne másold le a szerveren lévő pályákat és építményeket engedély nélkül, ha nem a Te saját területeden van!"
Van már egy ilyen szabály. Ha megvan a másolt térkép esetleg kitudom törölni, ha ez ilyen nagy probléma és akkor azokon a térképeken nem lesz semmi már. Csak az eredetin meg a többi másolaton ha van.

**Comment by IciAlex** [comment]
De nem az építményt másolja le, (mert én pl azt törlöm) hanem a térképet.
