### ISSUE TITLE
SlimeFun & Shopkeepers bug

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4480]
**Szerver**: Survival/Sav

A SlimeFun tiltja az SF-es itemek falusival történő cseréjét. Ez egy hibát generál a /warp beváltó-nál lévő Shopkeeperrel. Nem lehet cserélni semmilyen SF-es itemet, így teljesen értelmét veszti.

**Comment by UDPSendToFailed** [comment]
De, lehet cserélni, bal oldalon a listában kell a tárgyra kattintani, és berakja.

**Comment by IciAlex** [comment]
+ nem bug

**Comment by andris155** [comment]
https://github.com/Slimefun/Slimefun4/issues/2581
