### ISSUE TITLE
Jobssal kapcsolatos szövegek [Infó] üzenetekben

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4483]
Ha már van rá warp, az automata üzenetekbe is lehetne néhány sort írni például a küldetésekről, sokan azt sem tudják, hogy van ilyen.

**Comment by andris155** [comment]
Ha van kedved írhatsz hozzá üzeneteket. Esetleg adok érte OCD-t is. :D

**Comment by andris155** [comment]
<img width="370" alt="Screenshot 2021-03-20 144951" src="https://user-images.githubusercontent.com/8324198/111871645-8a60ef00-898b-11eb-978e-820227607360.png">
Remélem ez így megfelel. Köszi az ötletet.
