### ISSUE TITLE
[Sav sziget] SF/ Is generator hiba nem tudom igazából melyik okozza.

### ISSUE THREAD

**Issue by baawoof** [TheOld-Crafters/Minecraft-servers#4484]
Sav sziget

Pár napja kicsit hülyén viselkedett az android rendszerünk sav szigeten, csomószor cobblestone jött a generatorban mikor nem is jöhetne és amikor az androidok kiütötték akkor csak cobblestone spawnolt vissza amire eleve 0% esély van, mert stone spawnolhatna csak. Ha ezt a blockot kézzel kiütjük megjavul és újra adja a többi blockot viszont egy idő után az összes androidnál csak cobblestone spawnol ezért folyamatos figyelemre van szükség, hogy ne romoljon el a rendszer.

**Comment by andris155** [comment]
A Slimefun nem támogatja a kőgenerátort. Nem tudok mit kezdeni ezzel a hibával.

**Comment by andris155** [comment]
Megpróbálom majd megfejteni, hogy mitől lett ilyen aztán kitalálom, hogy utána majd mi legyen. Hátha van rá valami konfig vagy valami ilyesmi.

**Comment by andris155** [comment]
Javításra került ez a hiba.

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
Köszi a jelentést.
