### ISSUE TITLE
Rang lejárati idő /bolt menüben

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4485]
Ha megoldható, ki lehetne rakni a bolt menübe, vagy akár egy külön /rang parancshoz, hogy mikor jár le a rang. Tokenből és szavazatból vásárolt rangnál ezt sehol sem lehet megnézni.

**Comment by andris155** [comment]
Beleraktam a rangok menübe.

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
Beállítottam ismét. Kicsit másképpen. Most már jól írja elvileg az időket.
