### ISSUE TITLE
Az Ender Chest Extraction Node hibás

### ISSUE THREAD

**Issue by balazzrthd** [TheOld-Crafters/Minecraft-servers#4487]
**Szerver**:
Survival 

Ender Chest Extraction Node textúrája egy steve fej, mind kézben tartva, mind az sf könyvben.
![Névtelen](https://user-images.githubusercontent.com/30508343/111148298-be9f6e80-858b-11eb-820a-a0984c1cdecf.png)

**Comment by balazzrthd** [comment]
+ lerakva is ez a textúrája

**Comment by andris155** [comment]
Eredeti klienssel nekem nincs ilyen probléma. Ha Tlauncher-t használsz akkor ne a TL verziót használd.
