### ISSUE TITLE
Rangvásárlás

### ISSUE THREAD

**Issue by balazzrthd** [TheOld-Crafters/Minecraft-servers#4488]
**Szerver**: 
Mindegyik
<!-- Ez alá a sor alá írd le az ötletedet. --!>
A Tag+ és V.I.P rangokat meg lehetne venni játékpénzért 1 hónapra. A többi rangot pedig meg lehetne venni a 2 hónapnyi vételár 60%-ért 1 hónapra. Még mindig ösztönzően hatna a playerekre, hogy megvegyék 2 hónapra a rangot, de aki csak kevesebbet tud megvenni / összegyűjteni, annak is lenne lehetősége a rangjában "szintet lépni". Emellett a többi játékost is ösztönözheti ez a rang vásárlásra , mivel nem kell olyan hihetetlenül "sokat" összegyűjtenie, hogy például vegyen egy Elit rangot ( A /setpwarp miatt hozom ezt példának).

**Comment by andris155** [comment]
Nem szeretnék ilyet. De köszönjük az özletet.
