### ISSUE TITLE
Pwarp hibák

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4490]
**Szerver**: szurvi

-Pwarp névben nem lehet space, ez nem tom hiba-e vagy sem
-Pwarp leírásban minden szó után színkódot kell írni, különben nem jó
-Ki lehetne rakni a fordítását githubra

**Comment by andris155** [comment]
A parancs miatt direkt nem lehet space-t.

**Comment by andris155** [comment]
A fordítást már kiraktam.

**Comment by andris155** [comment]
Kérlek egy hibát jelents egy jelentésben legközelebb.

**Comment by skrisz0101** [comment]
gondoltam a pwarp hibák mehetnek egybe, de akkor ok

**Comment by andris155** [comment]
Ha új sorba kerül a leírásban valami akkor mindig kell újra színkód. Ez is direkt ilyen szerintem.

**Comment by andris155** [comment]
PlayerWarps fordítás: https://github.com/TheOld-Crafters/Minecraft-servers/blob/master/Ford%C3%ADt%C3%A1sok/PlayerWarps/lang.yml
