### ISSUE TITLE
Minigame menü itemek kibugoltatása pwarppal

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4492]
Ha előre kimásolok egy minigame belépési parancsot, majd az 1 másodperces pwarp teleport késleltetés közben beírom, a pwarp kivisz a minigame lobby-ból, innentől pedig le lehet rakni a menü itemeket például egy eszközkeretbe. 

![image](https://user-images.githubusercontent.com/16057404/111203936-e4e20000-85c5-11eb-8056-320e1a60b815.png)

**Comment by andris155** [comment]
Kivettem a késleltetést.

**Comment by andris155** [comment]
508 OCD
