### ISSUE TITLE
Hiányzó teleportálási idő.

### ISSUE THREAD

**Issue by baawoof** [TheOld-Crafters/Minecraft-servers#4494]
**Szerver**: Sav sziget

A /is parancsnál eltűnt az 1 másodperces várakozási idő.

**Comment by andris155** [comment]
Egy hiba miatt egyelőre kikerült ez.

**Comment by CeakSon-yes** [comment]
Hello @andris155! A savszigeten van az chat hiba ha azt írod: ,,hiába írom" <-- ezt káromkodásnak/csúnya beszédnek észleli.

**Comment by andris155** [comment]
Kérlek egy új jelentésben írd meg ezt.
