### ISSUE TITLE
jobs - hiányzó vöröskő cuccok

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4495]
**Szerver**: szurvi

vörösköves cuccok craftolásáért nem fizet a jobs, nincs benne.

**Comment by Sanszi** [comment]
Szerintem teljesen jó, hogy nem fizet pl. a redstone fáklyáért. A bolt sem így lett összeállítva.

**Comment by andris155** [comment]
Így is rengeteg dolog van benne. Minden nem kerül bele.

**Comment by andris155** [comment]
De az ötletet azért köszi.
