### ISSUE TITLE
Rangok menü hibásan írja a hátralévő időt

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4496]
Ma vettem oldot. 

![image](https://user-images.githubusercontent.com/16057404/111339419-08658300-8678-11eb-9970-b3c3a63ead5d.png)

**Comment by balazzrthd** [comment]
Nekem is ez van, de kb egy random számot ír ki. 1 napos elit rangnál írta, hogy 9 nap 26h

**Comment by andris155** [comment]
Érdekes.

**Comment by andris155** [comment]
Sajnos erre nincs megoldás már lassan 1 éve. Úgyhogy nem tudom megoldani ezt egyelőre.

**Comment by andris155** [comment]
A menüből ezt az infót kiszedtem.

**Comment by andris155** [comment]
Köszi a jelentést.
