### ISSUE TITLE
Jobs - Barkácsoló vs mcmmo újrahasznosítás

### ISSUE THREAD

**Issue by lovi-dev** [TheOld-Crafters/Minecraft-servers#4497]
**Szerver**: Survi

Magas szintű (1000+) mcmmo Újrahasznosítás képességgel csak ércből gyártható tárgyak (pl. gyémánt páncélok) 100% visszabointhatóak az adott nyersanyagra. Az összes felhasznált alapanyagot visszadja. Ezt kihasználva alapanyag fogyasztás nélkül végtelenszer legyártható tárgyak vannak, melyre a Barkácsoló job fizet, sőt a szintlépések maitt egyre jobban fizet...
Kvázi végtelen pénz.

lovi_

**Comment by balazzrthd** [comment]
De shhh

**Comment by Sanszi** [comment]
> De shhh

eco set 0

**Comment by Sanszi** [comment]
Rip újrahasznosítás skill.

**Comment by andris155** [comment]
Kikerültek ezek a tárgyak a barkácsolóból.

**Comment by andris155** [comment]
Köszi a jelentést. 2032 OCD.
