### ISSUE TITLE
Bugoló Ender Dragon

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4498]
Survival

Folyamatosan fent van az Ender Dragon bossbarja az endben, miközben a sárkány nem látszik sehol. Össze vissza bugolnak a sárkány lövedékei, aztán X időnyi repkedés után meg szokott jelenni a semmiből a fenevad is, viszont több player vesztett már emiatt end crystalokat.

**Comment by skrisz0101** [comment]
általában csak simán felrepül a retekbe ahol már senki se üldözi aztán másbál visszajön

**Comment by andris155** [comment]
Nem tudom sajnos miért ilyen és megoldást se tudok rá.
