### ISSUE TITLE
Chatcontrol

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4499]
Survival, Savsziget.

https://github.com/TheOld-Crafters/Minecraft-servers/issues/4481 <- Az itt említetthez hasonlóan több szót/szókombicániót is kicsillagoz a chatcontrol.
Pl. barom -> baromfi. 
Valamint a "szar" szót nem csillagozza ki, viszont a "shit" szót igen.

Ha kell kigyűjtjük a legtöbb ilyen szókombinációt.

**Comment by andris155** [comment]
Kellene az összes ilyen, igen.

**Comment by andris155** [comment]
A baromfi már rég javítva lett. Kérlek teszteld is le mielőtt megírod ezeket.

**Comment by balazzrthd** [comment]
A jaffaszelet is káromkodásnak számít.

**Comment by andris155** [comment]
Kérlek nyiss új hibajelentést erre. Ez esetben egy jelentésbe akár több szót is írhatsz.
