### ISSUE TITLE
Szabályzat ötlet

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4500]
Szerver: Survival, savon nem hiszem hogy meg lehet valósítani.

A slimefunos gyárak mellé való pwarp rakást be kéne tiltatni, nagyon zavaró hogy több olyan pwarp is van, hogy odatpzel és 10 nem igazán fog menni az fpsed, mert annyira nagy gyár van mellette.  Az senkit sem zavar, ha csak a sell ládákból kicargozza, v buyba becargozza a cuccokat szerintem, de persze, ha olyan távolságban van a gyár hogy már nem eszi meg az összes fpsedet az teljesen okés.

Miért írtam meg az ötletet? Jelenleg is van szponzorálva olyan pwarp, amin alig van fps, mert rohadtnagy gyár van építve felé.

**Comment by MrZero1** [comment]
Talán mégis jobb lenne, ha tiltva lenne az, hogy más területére is lehessen lerakni pwarpot. #4489

**Comment by KingDeadZ** [comment]
A  levédés tulajdonosának a pwarpja van a masszív gyár alatt.

**Comment by skrisz0101** [comment]
igazából ha mindenki agyonlaggolja magát ott, max nem megy oda senki. Aki nem laggol, meg használja :v

**Comment by KingDeadZ** [comment]
> igazából ha mindenki agyonlaggolja magát ott, max nem megy oda senki. Aki nem laggol, meg használja :v
legalább a szponzor helyeket ne venné akkor el olyan elől, akinek a pwarpjára mennek is

**Comment by andris155** [comment]
A szerver warpokon próbálunk figyelni, hogy ne legyen gond az FPS-sel. De a játékosok által létrehozott helyeken erre nekik kell figyelni. Ha nem figyelnek akkor kevés lesz az FPS ott, de ez nem a szerver problémája és nem is a staff tagoké. Semmi értelmét nem látom erre a szabálynak.
Erre a legegyszerűbb megoldás: Ha neked laggos az a warp, akkor többet nem mész oda és akkor nem lesz ilyen probléma.

**Comment by andris155** [comment]
Meg esetleg adhatsz negatív értékelést a warp-ra még, ha ennyire problémás. Most már ilyet is lehet.

**Comment by andris155** [comment]
A szponzor helyre pedig mindenki ugyanúgy költ. Ha neki laggos a warpja többet más se fog oda menni és le is lesz szavazva.
De egyébként ez is egy érdekes kérdés. Mert akinek egy magon erősnek számító processzora van és használ optifine-t valószínűleg egyik warp se lesz laggos és nem nagyon fogja érdekelni ha sok ott a cargo. :D

**Comment by KingDeadZ** [comment]
Hát például kernelnek volt ilyen 12 fpse, nagyon durva gyár van ott azért.
