### ISSUE TITLE
Survival - Disposal

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4501]
Ha a tábla legfelső sorába beírom, hogy [Disposal] már nem csinál olyan táblát, ami szemetesként funkcionál, szimplán átírja [disposal]ra, hogy rossz legyen.

**Comment by MrZero1** [comment]
Ami a spawnon van, az sem megy?

**Comment by andris155** [comment]
Nem lehet létrehozni ilyen táblát. Használjátok a Slimefun Trash can-t.

**Comment by andris155** [comment]
Értelemszerűen az admin tud létrehozni ilyet, de az admin mindent is tud. :D

**Comment by KingDeadZ** [comment]
Nemrég még lehetett tagoknak is.

**Comment by andris155** [comment]
A trash can sokkal szebb és jobb megoldás erre. Szóval már egy ideje nem lehet tagtól ilyet.
