### ISSUE TITLE
hosszabb pwarp név

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4502]
**Szerver**: szurvi

most max 10 karakter hosszú lehet egy pwarp neve, ezt fel lehetne esetleg tolni 15-20ra is. 
Pl én nem tudtam olyan pwarpot létrehozni h ,,Skrisz egyetlen és csodálatos plázája", ezért sima skrisz01 nevűt kellett létrehoznom :'(

**Comment by MrZero1** [comment]
Szerintem bőven elég a 10 karakter is. :D

**Comment by UDPSendToFailed** [comment]
Még a saját nickem se tudom megadni pwarp névnek, mert hosszabb 10-nél.

**Comment by andris155** [comment]
Átírtam 16-ra a limitet.
