### ISSUE TITLE
gm 3 farmland kiugrálás

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4503]
Survival, Savsziget.

Spectatorban ki lehet "ugrálni" a veteményesét más playereknek.

**Comment by andris155** [comment]
Nekem ezt reprodukálni nem sikerült. De az egyik segítő szerint csak akkor működik, ha van jogod a területhez és szerintem sincs ez a védelem kifejezetten a játékmódokhoz kötve. Tehát elvileg védettnek kell lennie ha nem férsz hozzá a területhez akkor is, ha spectator módban vagy.
