### ISSUE TITLE
Savsziget szerver hasznosabbá tétele.

### ISSUE THREAD

**Issue by baawoof** [TheOld-Crafters/Minecraft-servers#4504]
**Szerver**: Savsziget

Mivel nem működik az /is generator illetve a slimefun gépek, a boltban lejebb mehetnének az árak 90%-al.
Vagy régebbi verzióra rakni az sf-et mert a mostani úgy működik mintha a cd projeckt red készitette volna.
Ha esetleg még megoldható lenne, minden egyes ércre külön generátor illetve szerencse 40-50 csákányok, hogy kompenzálja az sf gépeket.

Edit: Illetve leheseen afkolni a generátoroknál

**Comment by andris155** [comment]
Egyik sem lesz. A Slimefun előtt is volt savsziget és úgy is volt értelme.

**Comment by baawoof** [comment]
Hát akkor marad a leszarom az egészet úgy látszik mert engem kurvára nem érdekel stílus. Véletlenűl se a legtöbb sziget az sf-ről szól, de persze aki nem is játszik rajta nem is tudja és látszik.
