### ISSUE TITLE
Ládaboltok 

### ISSUE THREAD

**Issue by BagdiSandor** [TheOld-Crafters/Minecraft-servers#4505]
**Survi, Sav**:

A ládaboltok egyáltalán nem működnek egyik szerveren sem! (KillerX)

**Comment by primusantica** [comment]
Érvénytelen Minecraft felhasználóra hivatkozik.

**Comment by Sanszi** [comment]
/warp boltban sem megy
![2021-03-18_09 38 25](https://user-images.githubusercontent.com/37781201/111596739-c8181900-87cd-11eb-9454-42c13852f865.png)

**Comment by andris155** [comment]
Javítottam.
