### ISSUE TITLE
/untrust all :)))))))))))

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4506]
**Szerver**: szurvi

be lehet állítani h a levédés parcellája ne örökölje a fő védés tulajdonságait. (pl ha vlakit hozzáadok a fő védéshez, ne tudjon blokkot ütni a parcellán a levédésen bellül)
/untrust all-al levettem mindenkit a fő védésről, mert valamit változtatni kellett, de így levett mindenkit az összes parcelláról is :))))))))))))))))))))
kb 100+ védésről :)))))))
lehet beállítanom újra 100+ védés /trust-jait egyesével
ezt jó lenne javítani, ha meg direkt, akkor a gyász egye meg

**Comment by andris155** [comment]
Szerintem ez így logikus, hogy az ,,all" tehát magyarul minden az mindenhonnan töröl mindenkit.

**Comment by KingDeadZ** [comment]
szerintem úgy /untrust all , hogy a mostani levédésről levesz mindenkit. ha levédésen kívül álsz, pedig mindenhonnan mindenkit, így mükszik elm

**Comment by andris155** [comment]
Esetleg itt megírhatják ezeket az ötleteket a plugin fejlesztőnek, ha még más nem írta: https://github.com/TechFortress/GriefPrevention/discussions/categories/ideas
