### ISSUE TITLE
teljes tulaj jog levédésekre (parancs)

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4507]
**Szerver**: szurvi

lehetne valami parancs amivel társtulaj jogot lehet osztogatni (/permissiontrust nem az)

**Comment by andris155** [comment]
Egy tulaj lehetséges jelenleg, mivel neki számítanak bele a blokkjai is a védésbe. Ha lehetne társtulaj akkor valahogy úgy lenne talán értelme, hogy összeadódnak a blokkok. Én szerintem ez jobb így, ahogy most van.
