### ISSUE TITLE
halász, bájitalfőző, bűvölő munkák +$

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4508]
**Szerver**: szurvi

ezeket a munkákat kb senki se használja, esetleg lehetne rá rakni egy kicsit több $-t

**Comment by lovi-dev** [comment]
halász: mcmmo miatt sokkal többféle tárgyat fogsz ki mint amire fizet/xp-t ad, így nincs értelme.

**Comment by IciAlex** [comment]
bájitalfőző: mcmmo potikért nem ad pénzt.

**Comment by Sanszi** [comment]
Bájitalfőzőre én úgy gondolom, +50% pénz mehetne. 
Halászatra +100% pénz.

**Comment by andris155** [comment]
Az enchanternél mennyi plusz legyen?

**Comment by Sanszi** [comment]
> Az enchanternél mennyi plusz legyen?

Szerintem az enchanternél nem kell emelni.

**Comment by andris155** [comment]
Növeltem a pénzt a halásznál és bájitalfőző munkáknál.
