### ISSUE TITLE
topg.org szavazásnál a szerverleírás ékezetek hiányossága

### ISSUE THREAD

**Issue by UnaRkWfoglaltvolt** [TheOld-Crafters/Minecraft-servers#4509]
![kép_2021-03-19_150612](https://user-images.githubusercontent.com/80747757/111792542-a5b4f700-88c4-11eb-9edb-c2cfc0ff1db9.png)
Az ékezetes betűk hiányoznak így elég furán és értelmetlenül néz ki.

**Comment by andris155** [comment]
Ha jól emlékszem jól lett megadva, de átírja ilyenre sajnos.

**Comment by andris155** [comment]
Ékezettel van megadva a leírás, de sajnos átírja ilyenre. Nem tudok ezzel mit kezdeni.

**Comment by andris155** [comment]
A jelentést azért köszi.
