### ISSUE TITLE
Árpi csapata szerint szénnel nem érdemes tüzelni, csak a fa szabályos

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4510]
![image](https://user-images.githubusercontent.com/16057404/111793961-0e50a380-88c6-11eb-86d9-cadcb939ce9a.png)

**Comment by Sanszi** [comment]
Egy word dokumentumba kellene megírni az összeset, aztán egyenként hozzáadni a kivételekhez.

**Comment by andris155** [comment]
Nem kell Word sem. Igazából ide is megírhatod vagy a txt is tökéletes.

**Comment by andris155** [comment]
Javítottam. Köszi.

**Comment by Sanszi** [comment]
basszus
basszuskulcs
basszusgitár

**Comment by andris155** [comment]
Kérlek nyiss új jelentést ezekre.
