### ISSUE TITLE
mcmmo szint lépés

### ISSUE THREAD

**Issue by Volga080** [TheOld-Crafters/Minecraft-servers#4511]
Szerver: sav, survival

Jelenleg kettő helyen jelzi a szint lépést, és egy helyen, hogy mennyi kell a következő szinthez + jelenlegi szintet is írja ott. 

Szerintem ez kicsit sok. Véleményem szerint legalább a chat-en ne írja ki szint lépést. A másik kettő bőven elég.

**Comment by UDPSendToFailed** [comment]
Chat üzenetek kikapcsolása: /mcnotify
Bossbar kikapcsolása: /mmoxpbar disable
