### ISSUE TITLE
6 órás promo pwarp hely

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4512]
**Szerver**: szurvi

25.000$-t kéne levonnia, de 100.000$-t von le
![2021-03-20_13 35 27](https://user-images.githubusercontent.com/29951969/111869811-5bde1680-8981-11eb-8702-ff51475fbf5f.png)
![2021-03-20_13 35 39](https://user-images.githubusercontent.com/29951969/111869814-5d0f4380-8981-11eb-945f-8de0df122428.png)

**Comment by andris155** [comment]
Köszi. Javítottam. 1016 OCD
