### ISSUE TITLE
ChatControl szavak/mondatok

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4513]
basszus
basszuskulcs
basszusgitár
pocsék
pocsékolás
pocsolya
csicsóka
Legalább uzi van a gta 5-ben.

**Comment by IciAlex** [comment]
Kidob a szerver

**Comment by andris155** [comment]
Javítottam. Köszi.

**Comment by andris155** [comment]
330 OCD
