### ISSUE TITLE
slimefun - infinity expansion

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4514]
**Szerver**: szurvi

Megnéztük KingDeaddal ezt az addont, és szerintünk bekerülhetne a szerókra is.
-Be lehet állítani a nehézségi szintét, ami alapértelmezetten 1. (a szerón max 2-re lenne állítva, mert kb játszhatatlan afelett)
-nehézségi szint a craft árakat befolyásolja leginkább, de több apróságot is (pl 1 crafthoz 200 netherit kell, vagy 1000 netherit)
-Rengeteg fajta gép/cuccli kerül be vele, kb mint az egész slimefun fele
-Van benne op cucc/eszköz is, azok nerfelve lennének (állítható konfigban)
-Slimefunnak nincs nagyon ,,célja", ez simán lehetne az, mert kb lehetetlen craftok vannak benne, ezzel az idők végezetéig el lehet szórakozni. 
-Infinity Matrix-al (igaz, végtelen nyersanyag árán), de fly-t lehet szerezni. Gondolom ezt tiltani kéne
-Basic és advanced cobblegeneratort tiltani kéne, a mostaninál sokkal olcsóbb

(folyamat frissül a bejegyzés :p)

**Comment by KingDeadZ** [comment]
Nehézségi szint növelésével a gépek tickspeedje is lassul, max 1perc alatt tele volt a void quarry difficulty 1en, 5n kb 20p xD

**Comment by skrisz0101** [comment]
kis példa: van olyan cucc amit ha pénzben kéne kifejezni tocon: 50milla $

**Comment by Sanszi** [comment]
Ez nem vezetne ahhoz, hogy csak még nagyobb gyárakat építenének?

**Comment by andris155** [comment]
Mivel ez egy Slimefun szerver akármit is csinálunk lesznek nagy gyárak. Ha ez probléma, akkor a Slimefun a probléma nem pedig az addon-ok hozzá.

**Comment by KingDeadZ** [comment]
Az addon ad be erősebb gépeket is, akár drágán akár olcsón. Néhány esetnél a gyárak kissebbek lennének.

**Comment by Sanszi** [comment]
> Az addon ad be erősebb gépeket is, akár drágán akár olcsón. Néhány esetnél a gyárak kissebbek lennének.

Nekem nincs vele problémám akkor.

**Comment by skrisz0101** [comment]
inkább drágán...xd

**Comment by andris155** [comment]
Ez egy nagyon nagy addon. Ha lesz időm majd tesztelem és ha megfelelt a teszteken majd akkor kerül be.

**Comment by skrisz0101** [comment]
Még majd nézegetjük mi is

**Comment by skrisz0101** [comment]
átírtam az enchantokat a maxos cuccoknál, elv bekerülhet

**Comment by andris155** [comment]
Bekerült. Köszi az ötletet.
