### ISSUE TITLE
Cobblestone és androidok

### ISSUE THREAD

**Issue by ketezerhat** [TheOld-Crafters/Minecraft-servers#4515]
**Szerver**: savsziget

 Savszigeten ha lemegyek a szerverről akkor a generátorok csak cobblestonet termelnek ami logikus, de amikor újra fellépek az androidok nem szedik ki azt és nem tudnak termelni csak ha én egyesével mindenhonnan kiszedem a zúzottköveket. Egyébként elsőre úgy tűnik mintha kiszedné de csak az effectje látszódik a block törésnek.

**Comment by andris155** [comment]
Most jó?

**Comment by ketezerhat** [comment]
Tökéletes, köszi :dagger:

**Comment by ketezerhat** [comment]
Tökéletes, köszi szépen :D

**Comment by andris155** [comment]
Köszi a jelentést. Szívesen.
