### ISSUE TITLE
Értelmetlen/félrevezető szabályok frissítése.

### ISSUE THREAD

**Issue by baawoof** [TheOld-Crafters/Minecraft-servers#4516]
**Szerver**:
Savsziget

1. Chat
**1.13, Ne hirdess!**
Sokan hirdetik a /is warp-jukat, vagy pl: KisJoska: 1 darab földet veszek! is hirdetés.
**Javitás: Ne hirdess más szervert!**

2. Játékmenet
**2.5, Ne állíts senki levédése köré otthont a tulajdonos engedélye nélkül!**
- Sav szigetek egymás mellett vannak, nincs rá lehetőség, hogy a szomszédot megkérdezzük, hogy szabad-e oda raknunk szigetet.
**Javítás: (Túlélő szerver) 2.5, Ne állíts senki levédése köré otthont a tulajdonos engedélye nélkül!**

**2.10, Lehetőség szerint ne AFK-olj a gyáradnál, farmodnál.**
- Tudtommal ez módositva lett, csak érc generátor bányászása közben nem szabad afkolni.
**Javítás: 2.10, (Túlélő szerver) Lehetőség szerint ne AFK-olj a gyáradnál, farmodnál. (Savsziget) Ne afkolj kőgenerátor bányászása közben.**

**2.12, A fákat mindig ültesd vissza! Ügyelj a szép környezetre.**
- Szerintem egyértelmű, hogy miért fölösleges savszigetre.
**Javítás: 2.12, (Túlélő szerver) A fákat mindig ültesd vissza! Ügyelj a szép környezetre.**

**2.16 Ne védd le a portálokat úgy, hogy ne tudja azt használni más játékos. Feleslegesen ne torlaszold el.**
- Teljesen értelmetlen szabály savszigetre, ha ez mindig belenne tartva mindenki megszegte aki valaha is játszott a szerveren. Legtöbb ember a /is warp-ot boltnak használja, ahol általában nincs nether portál, és a helyiséget sem lehet elhagyni.
**Javítás: (Túlélő szerver) 2.16 Ne védd le a portálokat úgy, hogy ne tudja azt használni más játékos. Feleslegesen ne torlaszold el.**

**_Forrás: https://www.oldcrafters.net/szabalyok/_**

**Comment by Sanszi** [comment]
Lesz módosítva a szabályzat. Viszont a legtöbbnél amiket felsoroltál elég egyértelműen látszik, hogy melyik szerverre vonatkozik a szabály. Pl a 2.5 is egyértelmű, hiszen nincs claim savszigeten. 
2.16-nál pedig a lényeg az, hogy ha bemész egy portálba és a túloldal el van torlaszolva, akkor beszorulsz és nem tudsz kijönni magadtól sehogy. Ezért fontos a szabály.

**Comment by baawoof** [comment]
> 2.16-nál pedig a lényeg az, hogy ha bemész egy portálba és a túloldal el van torlaszolva, akkor beszorulsz és nem tudsz kijönni magadtól sehogy. Ezért fontos a szabály.

Hát igazából én is meg te is tévedtünk, mert savon lehetetlen a nether portálos beragadást (2.16) létrehozni, mert ugye mikor átmész  a netherbe ott nincs portál szóval csak 1 portál létezik. 
Röviden, nincs elég portál, hogy be tudj ragadni.

**Comment by Sanszi** [comment]
Azért írtam a 2. mondatban, hogy egyértelműen látszik, hogy melyik szerverre vonatkozik.

**Comment by baawoof** [comment]
> Azért írtam a 2. mondatban, hogy egyértelműen látszik, hogy melyik szerverre vonatkozik.

Attól független 2 perc oda irni, melyik szerverre vonatkozik. Van olyan szabály amúgy ugyan úgy egyértelmű, még is ott van, hogy melyik szerver az, szóval vagy mindenhol legyen ott, vagy sehol (ezért irtam én is oda, hogy melyik szabály melyik szerver), ne hagyatkozzunk az egyértelműre. A szabályzat a kezdő játékosnak a legfontosabb aki nem tud semmit a szerverről neki nem lesz egyértelmű minden szabály. Legyen pontos és érthető mindenki számára

PL: 4.4, (Survival), A warp-ok közelébe ne építsetek! Az itt épített építmény bármikor törlésre kerülhet.
Savon esélytelen lenne a warpokhoz épiteni, még is ott van, hogy survival.
vagy
4.5, (Survival), Ne építs máshoz túl közel!
Ez is egyértelmű, mivel savon csak túl közel tudsz épiteni, még is ott van, hogy survival.

Ennek a postnak lényege az, hogy legyen egységes, és szeparált a szabályzat (legyen külön sav és túlélő szabályzat), mert nem feltétlen igaz az egyik a másikra.

**Comment by MrZero1** [comment]
Már módosult a szabályzat jópár napja. (mikor a poszt volt a csoportban..:D)
Én is jobban örülnék, ha külön lehetne a szerverekre vonatkozó szabályzat.

**Comment by MrZero1** [comment]
Esetleg, ha megoldható, külön alpontokban lehetnének a szerverekre vonatkozó szabályzat, úgy akár lehetne egyedileg formázni, megfogalmazni. Az ötleteket köszi, bekerülnek a szabályzatba.
