### ISSUE TITLE
Survival - Jobs - Földműves

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4517]
A cukornád lényegesen rosszabbul fizet, mint a többi növény, pedig semmi sem indokolja:
- Ha kiütünk 1 szál cukornádat azt a jobs egynek számítja az mcmmo-val ellentétben, azaz a cukornád aratásakor nem "duplázódik" a pénz.
- A cukornádat nem kell elültetni valóban, de a többi növény ültetéséért fizet a jobs, nem kerül senki hátrányba.

Javaslom, hogy a cukornád által fizetett pénz ugyanannyi legyen, mint a bambusz utáni pénz (vagy mint a többi növény).
Így nem lenne hátrányos a cukornád aratása a többihez képest.

**Comment by lovi-dev** [comment]
Cukornádból egyszerre többet is ki tudsz ütni. Én is egyszerre 3 sort "szedek" ...

**Comment by skrisz0101** [comment]
Válasz h miért:
Water sprinkler

**Comment by UDPSendToFailed** [comment]
Minden növényre van cooldown, így Jobs-ban nem sokat segít a water sprinkler. Szerintem mehet a bambusz szintjére, a végső döntés az adminoké.

**Comment by Sanszi** [comment]
Szerintem fizethetne annyit a jobs érte, mint a bambuszért.

**Comment by MrZero1** [comment]
Szerintem is lehet a bambuszéval egyenlő.

**Comment by UDPSendToFailed** [comment]
https://github.com/UDPSendToFailed/Jobs/commit/c252e399b79651ca0a37144b022a43e5e29b4631

**Comment by andris155** [comment]
Frissítettem. Köszi.
