### ISSUE TITLE
spawn - bérelhető házak

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4518]
**Szerver**: szurvi

lehetnének újra bérelhető házak a spawnon.
Asszem akkor került ki, mikor minden tábla eltűnt onnan (?)

**Comment by MrZero1** [comment]
Felesleges, 1-2 ember használta, akkor is csak tárolásra. Én nem szeretnék újra ilyet.

**Comment by MrZero1** [comment]
Pláza is volt, direkt arra a célra, inkább mindenki a saját telkén, pwarpján csinált boltot.
