### ISSUE TITLE
1v1 és a Hide and Seek

### ISSUE THREAD

**Issue by WolterFox** [TheOld-Crafters/Minecraft-servers#4522]
**Szerver**: Survival

Ha egy 1v1 meghívót küldesz valakinek, s majd belépsz Hide and Seekbe, akinek küldted a meghívót elfogadja kb... 10 másodpercen belül, majd lezajlik a meccs akkor aki a Hide and Seekben van be lesz dobva az 1v1 váróterembe, majd azokat a tárgyakat amiket szerzett le rakhatja az Enderchestbe.

**Comment by WolterFox** [comment]
Ha nem baj ezért a jelentésért elrakunk 1-1 itemet, hogy majd odaadhassuk a TOC múzeumnak netán :3

**Comment by MrZero1** [comment]
Nem kellene elrakni egyet sem.
