### ISSUE TITLE
1v1 és más minijátékok

### ISSUE THREAD

**Issue by andris155** [TheOld-Crafters/Minecraft-servers#4525]
**Szerver**: Túlélő, savsziget, ???

Gyakorlatilag bármilyen helyről kilehet vele lopni a tárgyakat a szerveren.
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4520
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4521
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4522
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4523
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4524

OCD-t a jelentő csak akkor kaphat ha visszaadja az összes kilopott tárgyat.
Ameddig nem találtam erre megoldást addig a Duels nem elérhető.

**Comment by WolterFox** [comment]
Ah rendben, Multonsal próbáltuk ki, majd szólok neki!

**Comment by WolterFox** [comment]
Ha jól tudom egyébként sk-nál vannak ezek a tárgyak...

**Comment by WolterFox** [comment]
Andris, semmilyen tárgy nincs egyikőnknél már!

**Comment by andris155** [comment]
Nincs rá megoldás. Sajnos így kikerült a Duels.

**Comment by andris155** [comment]
Az OCD-t megadtam érte.
