### ISSUE TITLE
Pocket Games

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4526]
**Szerver**: Survival

Beírod a /pg-t és egyből kattintasz a hg táblára. Hg-n azok a cuccok lesznek nálad, amivel becsatlakoztál. Hg leave után törlődnek a cuccaid és helyette a pg cuccok lesznek az invedben. (Szerintem az összes minigamenel működik)
![image](https://user-images.githubusercontent.com/34820798/112133978-8c65c080-8bcc-11eb-813b-d3c244e37079.png)
![image](https://user-images.githubusercontent.com/34820798/112134141-b28b6080-8bcc-11eb-9a3d-87e802160074.png)

**Comment by andris155** [comment]
Letiltottam abban a világban, ahol a tábla van. Így már nem lehet kilopni sehogy a tárgyakat a Pocket Games-ből?

**Comment by Sizarra** [comment]
Ha az összes minigame egy világban van, és ott le van tiltva, akkor szerintem már nem.

**Comment by andris155** [comment]
Akkor javítva. Köszi a jelentést.

**Comment by andris155** [comment]
1016 OCD
