### ISSUE TITLE
/pwarp látogató számláló

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4527]
**Szerver**: szurvi

minden embert egyszer számol csak. nem lehetne hogy ez naponta frissüljön? pl ha szerdán pistike elmegy 5x, csak 1x számolja, de kövi nap ugyanúgy számolja 1x
nemtom h hiba vagy direkt, de sztem így jobb lenne :C

**Comment by andris155** [comment]
Nincsen hozzá sajnos beállítás.
A fejlesztőnek tudsz írni a Spigot-on, ha szeretnéd, hogy legyenek hozzá olyan beállítások, amiket írtál: https://www.spigotmc.org/members/olzie-12.587363/
