### ISSUE TITLE
/gm 1 olvasóállvány után

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4528]
**Szerver**: szurvi

ha gm0-ban megnyitok egy olvasóállványt, majd kilépek és /gm 1-be akarok menni, ezt írja ki:
nem tudok gm1-be lépni, csak ha relogolok.
![2021-03-23_17 59 50](https://user-images.githubusercontent.com/29951969/112186780-c3a29480-8c01-11eb-9f0b-2e958a8def72.png)

**Comment by andris155** [comment]
A megoldást leírtad. A jelentést köszi. Kb. 2-3 hónap a javítás hozzá.

**Comment by andris155** [comment]
Ez a hiba megoldódott azóta.
