### ISSUE TITLE
Ne hírdess!!

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4529]
Táblára nem lehet dátumokat írni.

**Comment by balazzrthd** [comment]
Nekem ment a /pwarp balazzrt-nél.

**Comment by IciAlex** [comment]
Ezt írom be és nem engedi
![image](https://user-images.githubusercontent.com/74869381/112215343-931e2300-8c20-11eb-9928-9b2ef91b2223.png)

**Comment by andris155** [comment]
Kérj meg egy admint, hogy írja rá neked addig, ameddig ezt nem tudom javítani.

**Comment by andris155** [comment]
Javítottam. Köszi a jelentést.
