### ISSUE TITLE
Hunger Games és Paint Ball

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4530]
**Szerver**: Survival

A felállás ugyanaz, mint a /pg-nél. Hunger Games váróban a tábla elé állva, majd a chatre beírva a /pb join-t, majd az enterrel egyidőben le kell nyomni a jobb klikket, így egyszerre leszek HG-n és PB-n is. Ha kilépek, megkapom a PB váróban lévő mellvértet, de szerintem maga a Painball-os itemeket is ki lehet hozni onnan.
![image](https://user-images.githubusercontent.com/34820798/112296860-80920100-8c95-11eb-95f4-11abfdc3e423.png)
Ha /pb leavet írok, akkor nem engedi a hg miatt, ha /hg leavet, akkor pedig a pb miatt nem. Az egyetlen megoldás a relog.

**Comment by andris155** [comment]
Ahol vannak ilyen táblák ott letiltottam a más Minigame parancsok használatát. Remélem ezzel sikerült javítanom ezt is.

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
Köszi a jelentést.
