### ISSUE TITLE
szavak, amiket kicsillagoz #2

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4531]
**Szerver**: mindenhol

hanyadik
fa, szén

**Comment by Sanszi** [comment]
Én elkezdtem írni őket txt-be, hogy ne 2 szavanként legyen 1 issue rá. xd

**Comment by andris155** [comment]
hanyadik szó nincs, oké most ezt beleírom de nem szívesen készítek ékezet nélküli támogatást bele. Angol billentyűzettel is lehet ékezetet írni ugyanúgy + akinek ez probléma miért vesz angol billentyűzetet ha magyarul ír?

**Comment by andris155** [comment]
Javítottam. köszi.
