### ISSUE TITLE
Jobs shop beállítása

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4532]
Ládakulcsok, fél - 1 órás pénz / xp boost, esetleg más tárgyak, olcsóbbak 5-10k pont, drágábbak 30-50k körül lehetnének.

**Comment by andris155** [comment]
A beállítás oké, de fogalmam sincs mit kellene beállítani vagy mennyiért?

**Comment by UDPSendToFailed** [comment]
Erről már az adminok döntenek, én csak ajánlottam pár dolgot, ami lehetne talán.

**Comment by Sanszi** [comment]
Így nézne ki a jobs shop egyelőre. Később még lehetséges, hogy bekerülnek más dolgok is.

Fortuna kulcs: 3000 jobs pont
Fortuna 2 kulcs: 5000 jobs pont
Ultrakirály kulcs: 8000 jobs pont
Varázslatos kulcs: 10000 jobs pont
Hiperszuper kulcs: 15000 jobs pont
Legendás kulcs: 20000 jobs pont
Titkos kulcs: 30000 jobs pont

1 órás pénz boost: 50000 jobs pont
1 órás xp boost: 50000 jobs pont

Az xp, pénz boostok csak az aktiválóra vonatkoznak és nem globálisak, igaz?

**Comment by UDPSendToFailed** [comment]
Persze, csak annak lesz, aki megvette, a küldetéseknél is így van. XP, pénz boostnál kéne még az, hogy mennyi legyen %-ban, szerintem 75% belefér annyi pontért.

**Comment by skrisz0101** [comment]
összes jobs szintem: 60
jobs pontom: 4000
1 fortuna kulcs szerintem édes kevés annyiért xd

**Comment by UDPSendToFailed** [comment]
Talán a kulcsok lehetnének valamivel olcsóbbak, kezdőknek így tényleg nem éri meg, inkább nyitogatnak lucky-t.

**Comment by Sanszi** [comment]
> összes jobs szintem: 60
> jobs pontom: 4000
> 1 fortuna kulcs szerintem édes kevés annyiért xd

Nekem 476 az összes szintem.
54k pontom van összesen, és igazán nem volt nagy erőfeszítés összegyűjteni.

**Comment by skrisz0101** [comment]
szerintem (sokkal) kisebb erőfeszítés venni 10 luckyt max 15k-ért és abból nyitni 1 luckyblock kulcsot, abból meg nyitni pl 3 legendás kulcsot

**Comment by KingDeadZ** [comment]
azért te sem 10percet farmoltál a 476 szintért, hanem több órát xd

**Comment by andris155** [comment]
Beállítottuk.
