### ISSUE TITLE
Texture pack, sav

### ISSUE THREAD

**Issue by Volga080** [TheOld-Crafters/Minecraft-servers#4534]
Szerver: savsziget

Igazából, texture pack én nekem mindig betöltött, de utóbbi napokban már nem nagyon jelent meg, még a Mojang-os betöltö képernyő sem. Még úgy kezdődőtt, hogy megjelent a Mojang-os töltőképernyő, de nem töltőtte be a texture pack-et. De most már Mojang sem jelenik meg. 

Sav meg igazából röviden elromlott a sav. Nem öl meg, csak megfulladni lehet benne.

**Comment by andris155** [comment]
Itt leírtam, hogy miért került ki a forráscsomag. A sav hibátlanul sebez. Persze ha god módban játszol gondolom nem sebez.
https://github.com/TheOld-Crafters/Minecraft-servers/commit/4833985f78f51edd07e2f0fd2b6f86d080531574
