### ISSUE TITLE
slimefun - DynaTech addon

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4535]
**Szerver**: szurvi, sav

Elég sok dolgot hoz ez is, de van benne pár kikerülendő cucc. Valaki átnézheti ha gondolja, aki ért is hozzá.

amit 100% hogy tiltani kéne:
-wheather controller: változtatja az időjárást
-flight gem: krea repülést lehet vele szerezni
-Inventory Filter: Hibásan működik, kellemetlen hibával
-Dimensional home: létrehoz egy saját világot a játékosnak xd
(elvileg lehet tiltani h új világot hozzon létre, de nemtom akkor mit csinálna, ezt esetleg lehetne tesztelni)
-Hydro turbine és Hydro generator (csak azért, mert infinity expansionban is van)

amit nem tudok biztosra hogy bekerülhet-e:
-Van 1 cucc amivel 1000 J energiáért cserébe 1 követ át lehet alakítani 1 random ércre. Farmolni nem nagyon lehet, mert leteszi magát a tárgyat is (8 alkalmat bír egy ilyen tárgy, mire kifogy)
-Antigravity bubble: 45 blokkos körben fly-t ad a játékosnak. (árammal megy, le kell tenni a gépet)
-van 4 fajta növény termelő gép, pl ha beleraksz 1 magot, abból csinál pár búzát és néhány magot.
   >1. gép: alap növényeket termel
   >2. gép: nether növényeket termel
   >3. gép: refréngyümölcsöt és virágot termel
   >4. gép: tengeri növényeket termel
azt hozzá kell tenni, hogy eléggé drága gépek. (pl a most sf-ben bent lévő növénynövesztő gép is kell hozzá)

**Comment by andris155** [comment]
Nem értem mi a baj az inventory filter-rel. Amit beleraksz azt kitörli az inventory-ból ha felveszed. Mi nem működik ezen?

**Comment by skrisz0101** [comment]
az, hogy random törli a dolgokat ha felvennél valamit xd

**Comment by andris155** [comment]
Bekerült. Köszi az ötletet.
