### ISSUE TITLE
Bugos a Nano Blade

### ISSUE THREAD

**Issue by Albinocska** [TheOld-Crafters/Minecraft-servers#4536]
**Szerver**: Survival

Kezdjük az elején. Régebben csináltam egy Nano Blade-t. Akkor még normálisan működött, netherite-á átváltoztatva is, teljesen felfulloztam( az auto enchanterrel). Aztán tegnap felléptem, és észrevettem, hogy nincsen durability-je, le van merülve. Logikusan feltöltöttem és bekapcsoltam, a duráját felvittem fullra, és elkezdett lemerülni és evvel együtt törni, ráadásul nem is lassan. Van mégegy problematika. A statjaival sincs minden rendben, eltűnt az attack speed teljesen, az attack damage-ből -3 lett,  és még az ütéscooldown is eltűnt róla.

**Comment by KingDeadZ** [comment]
Így működik, rohadt sok energiát eszik ha be van kapcsolva, és a durabilityjét is viszi le ha eszi az áramot belőle. Nem éri meg használni, ha ki van kapcsolva az attack speedje broken a -3 attack damage miatt, sokkal gyorsabban ütsz vele.
