### ISSUE TITLE
Survival horgászat probléma

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4537]
Eddig a sima horgászat során 9 fogás után új helyen kellett halászni. Az utolsó hal kifogásánál jelezte a rendszer, hogy kevés hal maradt (szürke felírat). Ha tovább próbálkoztam semmit sem fogtam és jött a sárga felírat, hogy túlhalászott a terület.

Most ez elég idegesítő módon megváltozott: Csak 3 halat lehet ugyanazon a helyen kifogni, a 3. hal után nem jön a szürke figyelmeztetés, hanem a 4. próbálkozásnál nem fogok semmit és jön mind a két felírat.
Vissza lehetne esetleg állítani a régi működésre?

![2021-03-26_11 09 21](https://user-images.githubusercontent.com/19332825/112616930-98e45600-8e24-11eb-9e18-1e7f0ec14537.png)

**Comment by KingDeadZ** [comment]
Szerintem akár egy nagyobb limit is lehetne rajta, pl 20-30

Szimplán azért, mert a horgászat amúgy is chillesebb dolog és azért zavaró lehet jelenleg 3, de régen 9 kapás után helyet váltani.

**Comment by Sanszi** [comment]
Szerintem 9 lehetne újra, de 20-30 az sok. Az afk halászatra is figyelni kell.

**Comment by KingDeadZ** [comment]
> Szerintem 9 lehetne újra, de 20-30 az sok. Az afk halászatra is figyelni kell.

asszem 1.14 v 1.16ban változott az afk horgászat, nem elég egy 1x1es vízblockban horgásznod azért hogy kapj jó lootot, aztán mcmmot nemtudom érdekli-e.

**Comment by andris155** [comment]
Sajnos ezen nem lehet állítani benne. Csak true és false lehet, de ezt nem szeretném letiltani.
