### ISSUE TITLE
Slimefun - Foxy Machines addon

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4538]
**Szerver**: szurvi, sav

Kb ez az első olyan addon, ami ,,varázslatos" dolgokat ad hozzá
Pl vér, feláldizó oltár, ilyesmik. 
értelmet ad minden olyan dolognak, aminek nincs értelme a sima minecraftnak
Édesbogyó, tenger szíve, méz-méz blokk,  prizmarin kristály, ilyesmik.
Ad hozzá pár fun dolgot + 1-2 új kardot, íjat + egy új szettet új enchantokkal. Elég menő addon.
Küldetések is vannak hozzá

Amit tiltani kéne:
-Forcefield dome: egy körben barriert rak köréd
-remote controller: dome-hoz kiegészítő
-Forcefield engine: dome alapanyaga
-Forcefield stabilizer: dome alapanyaga
-chunk loader: chunkokat tölt be

aminél nem tudom hogy bekerülhet-e:
-boosted sínek. (2,5x gyorsítást kapott mindegyik sín)
-ghost block-ok. Lehet sima blokk (+más kiegészítő alapanyagokból) ghost blockokat csinálni. Sztem -nincs semmi különösebb hátránya, de gondoltam inkább ezt megkérdezem
(ui: ha ez kikerül, akkor a ghost-block remover se kell)

**Comment by KingDeadZ** [comment]
A ghostblocknál én félek hogy bebugol és ottmarad, és admin kell hogy eltűntesse valahogy :c

**Comment by skrisz0101** [comment]
van ghost block remover

**Comment by KingDeadZ** [comment]
> van ghost block remover

ok a regulatoroknak sem kéne dupeolni hologramokat még is dupeol szal ezt hagyjuk pls xd

**Comment by andris155** [comment]
Már elvileg nem duplázza a hologramokat. Vagy igen?

**Comment by skrisz0101** [comment]
dupláz elvileg

**Comment by andris155** [comment]
Bekerült. Köszi az ötletet.

**Comment by skrisz0101** [comment]
a rune hh nem került be?

**Comment by andris155** [comment]
Melyik?
