### ISSUE TITLE
Slimefun autocrafterek

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4539]
**Szerver**: survival, savsziget

Nemrég bekerült az új vanilla és enchanted autocrafter. Lehetne a beváltóba berakni, hogy a régieket, amik ki fognak kerülni, be lehessen váltani az újra.

**Comment by andris155** [comment]
Tudtommal a régi az egyik addon része, amiben továbbra is működik. Nem lesz így beváltó.

**Comment by Sizarra** [comment]
Igen, de az enchanted-nek kellene, mivel az ki lesz véve

**Comment by andris155** [comment]
Ha már ki lesz véve akkor lehetséges, hogy lesz beváltó. :)
