### ISSUE TITLE
Trollokkal kapcsolatos szabályok

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4540]
Egy kicsit változtatni kéne a visszaeső emberkéknél a büntetésen, mivel az utóbbi időben eléggé elszaporodtak az ilyen esetek. 
Ha valaki egyáltalán nem mutat semmi hajlandóságot a változásra, és szándékosan provokál mindenkit, trollkodik napokon - heteken át, akár több karakterrel is egymás után, annál ne húzzuk már az időt, ne kéregessék a staffok, hogy légyszike viselkedj, mivel úgysem fog. Szimplán rakják ki, ahányszor csak visszajön, sokkal elviselhetőbb lenne így a chat hosszú távon.

**Comment by MrZero1** [comment]
Ez igazából most is így van. Mindenki megkapja a második esélyt. Ha nem élnek vele, az a játékos baja.
