### ISSUE TITLE
Belehetne rakni a shiftel való (stack) vásárlást? Sokszor igencsak jólenne.

### ISSUE THREAD

**Issue by primusantica** [TheOld-Crafters/Minecraft-servers#4542]
Survi

**Comment by UDPSendToFailed** [comment]
#4173

**Comment by andris155** [comment]
Már régebben írtam, hogy nem lehet keverni a beállításokat. Shift-el jelenleg mindent elad, ami nálad van. Ha engedélyezném a vásárláshoz is így, akkor ha jól tudom úgy működne, hogy annyi tárgyat vesz, amennyit helyed van az eszköztáradban (vagy amennyi pénzed). A másik megoldás pedig az lenne, hogy shift-el 1 stack-et ad el és 1 stack-et vesz. A játékosok legutóbb inkább azt szerették volna, hogy shift-tel eltudjanak adni mindent így a vásárlási részét inkább kikapcsoltam, mert biztosan sokan vennének véletlen túl sokat valamiből.
