### ISSUE TITLE
telek Pénzért

### ISSUE THREAD

**Issue by SirIntegra** [TheOld-Crafters/Minecraft-servers#4543]
Survival/Savsziget

Az lenne az ötletem hogy legyenek fizetős plotok surivalba, savon pedig fizetős szigetek, pl a rangok szerint lehessen telkeket venni vagy pedig
0$ alap
1000$ kezdő 
10.000$ királyi
100.000$ Ultrakirály
1.000.000$ V.I.P
10.000.000$ Old 
és ezeken a telkeken/szigeteken különféle seedeken lenne eldugva a föld alá a láda amibe van a zsákmány, a legolcsóbb telken legyen a legegyszerűbb megtalálni, a legdrágábbon meg a legnehezebb, az old-ba lehetne pl: bot, olló, és annak a százaléka hogy drága dolgot találjon legyen nagyon kicsi, így nem kell attol félni hogy sok lesz az old a szerveren, vagy pedig ennek az ötletnek létrehozni egy külön "kit"et amibe egy eszközön 1db X-es enchant legyen, pl egy kardon élesség X és ennyi, a többit a játékos dönti el

u.i:
időközbe gondolkoztam ezen szóval már kb 20perce írom:D

**Comment by andris155** [comment]
Ezt elég bonyolult lenne megvalósítani. Egyelőre erre nekem most nincs időm a jelenlegi fejlesztések mellett. De az ötletet azért köszönjük.
