### ISSUE TITLE
vöröskő/redstone warp

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4544]
**Szerver**: szurvi, sav, ???

marynak van egy pwarpja ahol olyan szerkezetek (is) vannak, amiket nem biztos  hogy egy játékos ismer, de szívesen használná. Sztem igényesebben kialakítva simán lehenet egy warp ezekkel

**Comment by skrisz0101** [comment]
Én nem értek annyira hozzá xd

**Comment by MrZero1** [comment]
Oli készíti, elvileg hamarosan meg lesz.
