### ISSUE TITLE
Tábla "addolás"kreatívban

### ISSUE THREAD

**Issue by primusantica** [TheOld-Crafters/Minecraft-servers#4545]
Survival. 
Amikor létrehoznál egy bolt táblát kreatívban név, mennyiség, ár beírva de az id-t elrontod olyankor eldroppolja a táblát ami felvehető survivalban.
Antee

**Comment by Sanszi** [comment]
Többször lett már jelentve ez a hiba, nem lehet vele mit kezdeni sajnos.

**Comment by balazzrthd** [comment]
+1 ok Old rangot venni

**Comment by UDPSendToFailed** [comment]
#3540
#3489
#1861
#4185
#3311
#2945
#2874
#2649
#2364
#2316
#1418
#747
#4282

**Comment by Sanszi** [comment]
gg Kornél xD

**Comment by andris155** [comment]
Sajnos mindent nem tudunk javítani. De a tábla nem sokat ér így erre szerintem nem is igazán érdemes időt szánni.

**Comment by andris155** [comment]
A jelentést azért köszi.

**Comment by IciAlex** [comment]
miért kell miden 1es játékosnak ezt leírni?

**Comment by andris155** [comment]
Sajnos inkább az a probléma, hogy sok dolgot meg nem írnak le.

**Comment by primusantica** [comment]
> miért kell miden 1es játékosnak ezt leírni?

Azért, hogy a javithato hibák javításra kerüljenek. Tudom hogy te 20eve itt játszol es az összes bejelentett panaszt fejből tudod, de én sajnos ilyen tudatlan vagyok és nemtudtam, hogy ismert problémáról van szó. Annyi idom(kedvem se) viszont sajnos nincsen, hogy végigolvasgassam az összes eddigi bejelentést.
