### ISSUE TITLE
Infinity expansion - Advanced cobble generator

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4546]
Az inifinity expansion -> advanced machines -> Obsidian generator receptjéhez kell Advanced Cobble generator, amit sehol sem lehet jelenleg feloldani.
![2021-03-29_12 33 32](https://user-images.githubusercontent.com/19332825/112824925-6e480680-908b-11eb-870b-2dc8fa15cf39.png)

**Comment by andris155** [comment]
Majd engedélyezem.

**Comment by skrisz0101** [comment]
basic cobble generator is kéne.
Mikor tiltattam veled, nem láttam hogy receptekhez is kell :/

**Comment by andris155** [comment]
Engedélyeztem.
