### ISSUE TITLE
sf - új craftolók

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4549]
**Szerver**: szurvi, sav

az új craftasztalokkal ugye úgy kell craftolni, hogy kezedben a cucc amit craftolni akarsz, shift+jobb klikk a gépre, bead egy receptet hogy ,,biztos ezt akarod-e", majd ott el lehet fogadni. Na. UU-matterből nem lehet se szenet, lapist, stb-t gyártani velük.
Az enchanced azért, mert nem ismeri fel a receptet
A vanilla meg azért, mert nem vanilla craft

**Comment by Sanszi** [comment]
https://github.com/Slimefun/Slimefun4/issues

**Comment by andris155** [comment]
A Slimefun fejlesztő azt írta, hogy ez nem az ő hibájuk. A LiteXpansion-t nem igazán foglalkozik több issue-val sem. Sajnos lehet, hogy ezt nem fogják megoldani még egy jó ideig.

**Comment by andris155** [comment]
Nem hiszem, hogy erre lesz javítás.
