### ISSUE TITLE
Picnic Basket

### ISSUE THREAD

**Issue by Terrarix544** [TheOld-Crafters/Minecraft-servers#4550]
**Szerver**: Survival

 Hiába próbálunk rájönni, hogy velünk van a baj, vagy a picnic basket nem akar működni. Kövezzetek meg, ha csak mi nem jöttünk rá. Minden esetre, kézbevéve, éhezést produkálva, teljesen feltöltve vanilla élelemmel, nem hajlandó etetni úgy, mint eddig a cooler.

**Comment by andris155** [comment]
Nem tudok ezzel mit kezdeni. Teszt szerveren nagyon kevés pluginnal se működik, de a fejlesztő ezt írta:
,,I dont know how to help you in this situation. It works for me and for everyone I have asked about it"

**Comment by andris155** [comment]
https://github.com/ProfElements/DynaTech/issues/54

**Comment by andris155** [comment]
A jelentést köszönjük.

**Comment by andris155** [comment]
Elvileg ezt javította a fejlesztő.
