### ISSUE TITLE
Ugyanolyan Slimefun receptek

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4551]
Survi, savról semmit nem tudok :)
Advanced Virtual Farmnak és Advanced Tree Growernek ugyan az a receptje.

**Comment by andris155** [comment]
Az egyikhez Basic Virtual Farm kell a másikhoz meg Basic Tree Grower. Nem ugyanaz a receptje a kettőnek.

**Comment by IciAlex** [comment]
Mind2höz Basic Virtual Farm kell.

**Comment by andris155** [comment]
Talán újabb verzióval teszteltem. De nálam nem ugyanaz kellet pedig. Holnap majd nézd meg újra kérlek.

**Comment by IciAlex** [comment]
Már jó
