### ISSUE TITLE
Nocheat chat spam

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4552]
Ha meglövöm magam íjjal, nem sebződök, hanem telespameli a chatem ezzel a szöveggel. Foxy altar-hoz jól jönne, ha tudná magát sebezni a player. 

![image](https://user-images.githubusercontent.com/16057404/112978123-39a18100-9157-11eb-8f7a-d1f5795f0779.png)

**Comment by andris155** [comment]
Engedélyeztem.
