### ISSUE TITLE
Inventory Filter

### ISSUE THREAD

**Issue by Terrarix544** [TheOld-Crafters/Minecraft-servers#4554]
**Szerver**: survival

 Az inventory filter új szokása: ha beleteszel valamit, onnantól azt ha felveszed, törli ... eddig semmi új. Na de ha kiveszed belőle, hogy mostantól szükséged van arra az itemre... na akkor is törli továbbra is ugyanúgy.

**Comment by Terrarix544** [comment]
Kiegészíteném annyival, hogy egy nappal később már működik. Szóval lehet hogy csak pár órán át produkálja, vagy a szerver újraindításáig.

**Comment by Terrarix544** [comment]
Lehetséges, hogy megoldódott, nem tudom. Ma reggel belépve nekem sem
csinálta, de tegnap egész este miután kivettem belőle a cuccokat, továbbra
is törölte azokat. Remélhetőleg megoldódott.

András Marczinkó ***@***.***> ezt írta (időpont: 2021. márc.
31., Sze, 13:19):

**Comment by andris155** [comment]
Elvileg javított ezen a fejlesztő.
