### ISSUE TITLE
A levédésemen eltűntek az armorstandek. 

### ISSUE THREAD

**Issue by primusantica** [TheOld-Crafters/Minecraft-servers#4557]
Felszerelésekkel rajtuk(némelyik értékes)
Antee

**Comment by andris155** [comment]
A Slimefun armor stand duplikáció miatt egy blokk koordinátán egy armor stand engedélyezett. Nem értem miért raktál egy blokk koordinátára többet, amiket ráadásul akkor duplán is tároltál dolgokat ?!

**Comment by primusantica** [comment]
Én nemtudtam, hogy van ilyen. De egyebkent mind kulonbozo blockon volt.

**Comment by andris155** [comment]
Próbálunk javítást készíteni a dolgokra. De többször is teszteltem és nekem nem törölte pedig az egymás mellett lévőket.

**Comment by andris155** [comment]
Állítottam rajta. Az adminoktól próbáld meg majd visszakérni a tárgyakat.
