### ISSUE TITLE
Árammal kapcsolatos hibák

### ISSUE THREAD

**Issue by balazzrthd** [TheOld-Crafters/Minecraft-servers#4558]
**Szerver**:Survival (ezen fix)

Készítettem egy alloy gyárat. Volt készletben 8.98 millió J energiám. A gyár már 4-5 órája termelt, erre annyit látok, hogy el kezdett fogyni az energia. Ez nagyon meglepő, mert ahogy kiszámoltam, bőven a termelésem felett van az energia utánpótlásom, magyarul nem kéne csökkenni az energiának. Erre 3 percen belül felszívódott. Helyeztem le pluszban több solar panelt, celestial panelt, néha felment 800K J-ra az energiám, fél pillanatra rá -7,4K energiát mutatott. Nem értem mitől lehet ez, hiszen a termelés bővestelen bőven bírja ezt. Nem használok nagy fogyasztású gépeket sem. A hiba délután jelentkezett nálam.

**Comment by skrisz0101** [comment]
Celestial panel harmad annyit termel mint amennyit ír a könyvben(+csak nappal)

**Comment by balazzrthd** [comment]
> Celestial panel harmad annyit termel mint amennyit ír a könyvben(+csak nappal)

de épp ez az, hogy anélkül is kéne bírnia az energiámnak, mert amíg az sem volt meg is bőven fölötte termeltem

**Comment by andris155** [comment]
Ezzel így nem tudunk mit kezdeni. Ha valami több energiát fogyaszt mint kellene az persze hiba, de ebből a jelentésből nem derül ki, hogy mi fogyaszt több energiát.
