### ISSUE TITLE
Survival - Crates

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4559]
Survival

Valamiért most ilyen ocsmány a ládák kiírása. 
![image](https://user-images.githubusercontent.com/38157910/113325171-5802aa80-9318-11eb-9076-c31dc23811c3.png)

**Comment by KingDeadZ** [comment]
Tegnap szerintem még nem volt ilyen

**Comment by andris155** [comment]
Most jól írja?

**Comment by andris155** [comment]
Én úgy láttam, hogy most már jól írja.
