### ISSUE TITLE
InfinityExpansion ötlet

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4560]
Survival

A quarry hozhatna az overworldben is netheres cuccokat, úgy is eléggé lassú.

**Comment by skrisz0101** [comment]
(elv beállítható konfigban)

**Comment by andris155** [comment]
Szerintem jó ez így ahogy van. Ezen nem szeretnék állítani.

**Comment by KingDeadZ** [comment]
Hát, szerintem void quarryval kb 10percenként hozhatna 2db netherite ingotot, és több ezer kell, szal nem lenne hátrány

**Comment by skrisz0101** [comment]
@andris155 így eléggé elérhetetlen kb az infinity ingot :(

**Comment by andris155** [comment]
Engedélyezem majd ezt az opciót benne.

**Comment by andris155** [comment]
Engedélyeztem.
