### ISSUE TITLE
Growth Chamber

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4561]
Mindkét szeró-->

A farmer android kikerült, így Crop Growth Acceleratort nem lehet crafolni. Nem ezzel van a gond, mivel eut a gépet nemsokan használják (szinte senki). De a DynaTechbe bekerült alap, End, Nether, Ocean Growth Chambert nem lehet lecraftolni, mert kell hozzá Crop Growth Accelerator, amihez farmer android kell.

Javaslat: Visszarakni a sfbe a farmer androidot, de csak mint craft alapamyag, ne lehessen használni.

**Comment by skrisz0101** [comment]
Nem lehet úgy visszarakni, warp beváltóba lehet max beletenni

**Comment by Sanszi** [comment]
Szerintem egy nagyon bölcs döntés volt, hogy nem került be a szerverre. Én úgy gondolom jobb, ha nem mindent lehet sffel farmolni, így annak is van esélye pénzt szerezni aki nem szándékozik belekezdeni a slimefunba. (Mivel egyébként nyilván csökkentve lenne az értéke az ilyen itemeknek a /warp boltban, az ok is nyilvánvaló, hogy miért).

**Comment by andris155** [comment]
Mit lehessen beváltani Farmer Android-ra?

**Comment by skrisz0101** [comment]
android + e-motor esetleg. alapból is kb ez a craftja

**Comment by andris155** [comment]
Beraktam a beváltóba.

**Comment by Sanszi** [comment]
Miért nem lett akkor inkább feloldva a tiltás róla a slimefunban?

**Comment by MrZero1** [comment]
Ne legyen már berakva, nem hiába lett letiltva!

**Comment by andris155** [comment]
Beraktam az átváltóba és le van tiltva. Nem írtam egy szóval se, hogy engedélyeztem. :D
A recept úgy is működik, hogy le van tiltva. Direkt le is teszteltem.

**Comment by andris155** [comment]
Csak mint tárgy tudják barkácsolásra használni. Lerakni nem lehet, de ha le is raknák valahogy akkor se működik, mert le van tiltva.

**Comment by Sanszi** [comment]
A belőle craftolható tárgy mégerősebb. Így, hogy bekerült sok bolti áron csökkentenem kellett, ami azoknak a játékosoknak rossz akik nem szeretnének belekezdeni a slimefunba.

**Comment by andris155** [comment]
Eddig is találták már rég megoldást a farm automatizálására és kb. mindenki használja is. Nem változott semmi azzal, hogy le lett tiltva a farmer Android. Átalakították és megoldották más Slimefun blokkokkal.
Ez egy kifejezetten Slimefun szerver most már szerintem ennyi sok addon-al. Ha valaki economy survival-t akar játszani Slimefun nélkül azt hiszem ez a szerver nem neki való lesz.

**Comment by MrZero1** [comment]
Persze, tök jól hangzik ez, csakhogy nem mindenki a slimefun miatt jön fel. 
Elég rossz, ha így gondolkozunk.

**Comment by MrZero1** [comment]
Persze, tök jól hangzik ez, csakhogy nem mindenki a slimefun miatt jön fel.

**Comment by Sanszi** [comment]
A játékosok economy slimefun szervert akarnak, de ezt nagyon nehéz megvalósítani úgy, hogy annak a játékélménye is megmaradjon, aki nem akar belekezdeni a slimefunba. Én szeretem a slimefunt, viszont a játékosok legjava nem azért kezd bele, mert annyira élvezi, hanem azért, hogy pénzt tudjon keresni. Részemről nem muszáj a bolt se, amúgy is mindenki csak hurrog az árak miatt. A legtöbb sf szerveren nincs is bolt egyébként sem.

**Comment by UDPSendToFailed** [comment]
_viszont a játékosok legjava nem azért kezd bele, mert annyira élvezi, hanem azért, hogy pénzt tudjon keresni_

Ezért került be a Jobs

**Comment by andris155** [comment]
Ha nagyon problémás, akkor le lehet tiltani a Growth Chamber-t meg akár többi dolgot is amit farmolásra használnak. De nem biztos, hogy sok játékos örülne ennek. Illetve már így is viszonylag sok dolog került tiltásra az addon-okban.
