### ISSUE TITLE
Singularity Constructor gyorsasága 

### ISSUE THREAD

**Issue by ketezerhat** [TheOld-Crafters/Minecraft-servers#4563]
**Szerver**:Survival/Sav 

Slimefunban most bejöttek a szingularitások, és elég nehéz lecrafotlni 1-et is. Nem a nyersanyag miatt hanem az idő miatt ami alatt bemegy a gépe a 4000 item(vagy több). Szerintem tök jó lenne ha egyszerre 64 itemet is betudna fogadni a gép amibe kell a szingularitást csinálni mert így tényleg nagyon sok idő :D

**Comment by KingDeadZ** [comment]
Az ilyen ötleteket a slimefun discordra írd, egyébként meg köss rá cargot, és majd egyszer elkészül, nem kell siettetni mindent.

**Comment by andris155** [comment]
Talán van külön rész az InfinityExpansion-nak a Slimefun Discord szerverén. De ha nincs akkor is valahol ott lehet ötleteket írni hozzá. A GitHub-on sajnos csak hibákat fogadnak el.

**Comment by Sanszi** [comment]
Esetleg itt próbáld meg @ketezerhat 

https://github.com/Mooy1/InfinityExpansion/issues
