### ISSUE TITLE
/minigame menü 1v1

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4564]
Kikerült az 1v1, így feleslegesen van benne. 

![image](https://user-images.githubusercontent.com/16057404/113478258-15f87680-9488-11eb-9876-6797af6f21ea.png)

**Comment by andris155** [comment]
Meg a HideAndSeek is. Az admin kitudja venni. poma csinált hozzá egy csomó szerkesztési parancsot nekik.

**Comment by skrisz0101** [comment]
mióta nincs bújócska? xd

**Comment by andris155** [comment]
A statisztikák alapján alig használta valaki és mivel voltak hibák ezzel kapcsolatban ezért inkább kikerült.

**Comment by andris155** [comment]
Kivettem belőle.
