### ISSUE TITLE
/eastereggs jog

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4566]
Nem írja, mennyit találtam meg, semmit sem csinál.

**Comment by andris155** [comment]
Szerintem nincs benne ilyen. Az adminok állították be. Ha nem rakták bele a %eastereggs_eggsfound% és/vagy %eastereggs_totaleggs% placeholder-t az üzenetekbe akkor nem fogja írni.

**Comment by Sanszi** [comment]
Már használható a playerek által is.
