### ISSUE TITLE
Survival- LiteXpansion frissítés

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4567]
Ma jött rá frissítés, és egy config opciót szerintem jó lenne átírni.

 nerf-other-addons

Konkrétan az összes infinitys áramtermelő az eredeti termelés 1/3át termeli, ezért ezt jó lenne átírni falsera :D Az ára a radiantéhoz hasonló, szóval nem lesz ebből probléma.

**Comment by andris155** [comment]
skrisz01 véleménye érdekelne erről.

**Comment by skrisz0101** [comment]
Szerintem is falsera lehetne állítani, így senkinek se éri meg

**Comment by WolterFox** [comment]
Lényegében nem éri meg, a celestialhoz 3 energized solar panel kell és még annál kevesebb energiát is termel. Egy Celestial most 416.7 J/s-t termel, pedig 3 Energized kell hozzá ami 3 kb 750 J/s-t termelne.

**Comment by andris155** [comment]
false-ra állítottam.
