### ISSUE TITLE
Farmer android engedélyezése

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4569]
**Szerver**: mindenhol

Mivel tiltva lett a Water sprinkler, lehetne engedélyezni a farmer androidot. Már közel se lehet vele olyan jól termelni mint azelőtt

**Comment by Sanszi** [comment]
Tesztelni fogom és átgondoljuk.

**Comment by andris155** [comment]
Engedélyeztem.
