### ISSUE TITLE
Sky Block & Sky PvP

### ISSUE THREAD

**Issue by Goldie2000** [TheOld-Crafters/Minecraft-servers#4572]
**Szerver**: Új

Sziasztok!

Az az ötletem támadt, Hogy mi lenne ha, lenne **Sky Block** illetve **Sky PvP** szerver is?!

_**A Válaszokat előre is köszönöm!**_

**Comment by TothAlbi** [comment]
Egyébként mind a kettő volt már.

**Comment by MrZero1** [comment]
Skypvp talán négyszer is elindult..:D
