### ISSUE TITLE
Storage Unit

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4573]
Sok Storage Unit craftolásánál tele lesz spamelve a chat.

![kép](https://user-images.githubusercontent.com/74869381/113885831-748f5e80-97c0-11eb-9429-dae42e38a448.png)

**Comment by andris155** [comment]
Sajnos ez ilyen. Ötleteket nem fogadnak el a GitHub-on csak hibákat. Discord-on lehet esetleg megírni nekik gondolom.
