### ISSUE TITLE
Survival - GriefPrevention flag ötletek

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4574]
Bekerülhetnének a következő flagek:
EnterMessage <-- Ha jól vettem ki, ha belépnek a levédésbe lehetne vele megadni különleges szöveget
ExitMessage <-- Ha jól vettem ki, ha kilépnek a levédésből lehetne vele megadni különleges szöveget
NoElytra <-- Az elytrázást tiltaná
NoChorusFruit <-- Chorus Fruit használatot tiltana
NoEnderPearl <-- Enderpearl használatot tiltana
NoSnowForm <-- A hó formálódását tiltaná
NoOpenDoors <-- Az ajtó,csapóajtó és a kapukat védené a nyitástól
RaidMemberOnly <-- A pillager raideket csak a levédéshez hozzáadott emberek aktiválhatják
ProtectNamedMobs <-- Az elnevezett mobokat védené a plugin, szóval pl egy elnevezett zombit nem ölhetnek meg.
NoMobSpawnsType <-- Ezzel kilehet választani specifikusan, hogy milyen mobfajták ne spawnoljanak a levédésre
NoFlight <-- A repülést tiltaná a levédésen.
NoIceForm <-- Jég formálódását tiltja

Ezekből több olyan, amikkel lehetne a játékosoknak építeni eventet, amit nem csalnak szét mindenféle itemmel/repüléssel.

**Comment by Sanszi** [comment]
Amivel nekem kivetnivalóm van: 
EnterMessage
ExitMessage, mindkettő az trágár, obszcén jellegű szövegek miatt.
NoMobSpawnsType, helyett lehetne simán NoMobSpawn.

A többit hasznosnak tartom.

**Comment by KingDeadZ** [comment]
NoMobSpawnsType az specifikus mobfajtára használható, a nomobspawn az pedig mindenre, de arra van is jogunk

Also, esetleg az entermessage és exitmessage lehetne rangtól akkor

**Comment by Sanszi** [comment]
> NoMobSpawnsType az specifikus mobfajtára használható, a nomobspawn az pedig mindenre, de arra van is jogunk
> 
> Also, esetleg az entermessage és exitmessage lehetne rangtól akkor

Első: Éppen azért, hogy ne lehessen specifikus mobokat farmolni.
Második: Egy rangos ugyanúgy trollkodik, mint egy sima tag.

**Comment by KingDeadZ** [comment]
Érdekes, még nem láttam telken tpkillt

**Comment by andris155** [comment]
Ha vannak csúnya szavak, amiket kiszoktak írni és nem tiltja a rendszer illetve ezeket nem is írtátok meg az egy elég nagy probléma. Nem a flag-el van itt a probléma akkor.

**Comment by andris155** [comment]
Az elnevezett élőlények száma, ha túlmegy a limiten akkor nem fogja érdekelni a rendszert, hogy el van nevezve és úgy is törli. Viszont alapból ha nem megy túl a limiten ezeknek nem szabadna eltűnnie.

**Comment by andris155** [comment]
Ezeket engedélyeztem:
EnterMessage, ExitMessage, NoElytra, NoChorusFruit, NoOpenDoors, RaidMemberOnly, NoFlight
Köszi az ötletet.
A többit azért nem engedélyeztem mert vagy nem működik megfelelően, vagy megtöri a túlélő játékmódot.

**Comment by Sanszi** [comment]
> Érdekes, még nem láttam telken tpkillt

Es ez hogy jon ide? Xd

**Comment by andris155** [comment]
1016 OCD
