### ISSUE TITLE
ChatControl elírás

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4575]
![image](https://user-images.githubusercontent.com/38157910/113909613-28e8af00-97d8-11eb-9251-8ffb4ca0941b.png)

**Comment by andris155** [comment]
Ha találsz benne angol szövegeket nyugodtan írj GitHub-ra. Az egész fordítás nagyon nagy és nem igazán használjuk a ChatControl összes funkcióját így nem sok értelme lenne az egészet lefordítani.

**Comment by andris155** [comment]
Köszi a jelentést.
