### ISSUE TITLE
Telkes tojások

### ISSUE THREAD

**Issue by WolterFox** [TheOld-Crafters/Minecraft-servers#4576]
**Szerver**: Survival

Survivalon le lehet tenni a más telkére tojások. Ez gondolhatod: "Nem nagy baj az", de ha valaki... valahogyan szerez x millió spawnegget egy erős hostile mobból az már elég nagy baj. Érdekes dolog még, hogy csak azoknak a telkére tudsz letenni tojást ahova nem vagy hozzáadva!

**Comment by UDPSendToFailed** [comment]
Hiába lehet letenni, nem sebez, és despawnol idővel.

**Comment by WolterFox** [comment]
Igaz, de elnevezett mobok nem despawnolnak (asszem :C)
Sőt, őrláng tud tüzet rakni s az sebez!

**Comment by KingDeadZ** [comment]
Saját telekre is lehet lerakni, de ha ki lesz véve akkor majd szeretnék visszakérni egy jó 70 zombifalusi spawnegget, mert hogy telekről elviszem az összeset az is biztos, mert így sem éri meg már annyira telkezni

**Comment by andris155** [comment]
Ezek a tojások azért nem olyan könnyen megszerezhetőek. Szerintem ez nem probléma, hogy ilyen.
