### ISSUE TITLE
Mountain és Badlands biome /is biomesba

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4577]
**Szerver**:Savsziget

Az új sf addonnal érkezett egy új anyag, a Stardust, amit a Stardust Meteorokból lehet előállítani. A Stardust Meteorokat Badlands, vagy Mountain biomekból lehet Geominerrel bányászni, de jelenleg még üvegházakkal sem érhető el egyik biome se. Emiatt egyáltalán nem lehet megszerezni se a Stardust Meteort, se a Stardustot, amik energiatermelésre, valamint ha jól láttam néhány craftinghoz is szükségesek lennének. A lényeg az, hogy ha nem is a /is biomesból, de valahogyan elérhetővé kéne tenni a Mountain és a Badlands biomokat.

**Comment by andris155** [comment]
Hozzáadtam a biome-okhoz ezeket. Köszi az ötletet.
