### ISSUE TITLE
water sprinkler

### ISSUE THREAD

**Issue by lovi-dev** [TheOld-Crafters/Minecraft-servers#4578]
Surv. szerver.

Ha már a water water sprinkler-t pistékék miatt ki lett szedve, jó lenne ha beváltó warpnál be lehetne váltani valami alapanyagra.
Sajnos már nem emlékszem mi volt a craftja, de Reinforced Plate szinte biztosan kellett hozzá. 215 water sprinkler maradt nálam.

**Comment by KingDeadZ** [comment]
A craftja:
Iron Ingot | Electric Motor | Iron Ingot
Bucket      | Dispenser        | Bucket
Iron Ingot | Small energy capacitor | Iron Ingot

Trade így lenne jó akkor: sprinkler -> Emotor, Small energy cap  | mind2ből 1db

**Comment by andris155** [comment]
A falusi csak egy tárgyra tud váltani dolgokat.

**Comment by andris155** [comment]
A motort raktam be, amire lehet váltani. A motort raktam be, amire lehet váltani.

**Comment by andris155** [comment]
A motort raktam be, amire lehet váltani.
