### ISSUE TITLE
Griefprevention flagekre nincs jog

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4579]
Az újonnan bekerült flagekre nincs jog, és egy csomó régire sincs.

Flagek, amikre most nincs jog de volt: 
noenterplayer
nomobspawns
allowpvp
changebiome

**Comment by andris155** [comment]
Elvileg most már jónak kellene lennie.

**Comment by KingDeadZ** [comment]
A setclaimflag direkt került ki?
