### ISSUE TITLE
Újdonságok / változások szoba DC-n

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4581]
**Szerver**: DC

Lehetne egy újdonságok és változások szoba, ahol az ilyen kisebb,,híreket" lehetne kiírni 
Pl:
-új old cuccok old ládában
-új levédés flagek
-új sf cucc/addon

**Comment by andris155** [comment]
Ha lesz ilyen azt nem tudom megígérni, hogy minden apróságot megírok majd oda. Egyébként már gondolkoztam ilyenen csak GitHub-ra. Viszont a Discord tényleg jobb lenne, mivel oda az adminok egyszerűbben tudnak írni dolgokat.

**Comment by skrisz0101** [comment]
Esetleg lehetne minden staffnak joga írni oda, nem nagy dolog sztem.
esetleg moditól

**Comment by MrZero1** [comment]
Nem lenne rossz, de így is viszonylag sok szoba van. 
Majd nézek bot-ot Discordra, ötletem már van erre.

**Comment by MrZero1** [comment]
Igen, szóval annyi, hogy van olyan bot (több is), ami azt teszi lehetővé, hogy van egy 'rangot', amit lehet kérni discordon (reagál az ember az emojire dc-n), amit posztolunk akkor azt a rangot kell megjelölni, nem az everyone-t, így azok kapnak értesítést, akik kérték ezt a rangot. 😬

**Comment by KingDeadZ** [comment]
self-role, ja jó dolog egyébként xd discordon lehetne valami fun bot is, pl idleminer
also, mostanában én is kiirogatom hogyha van valami olyasmi amiről tudok discordra, hogy tudják azért az emberek

**Comment by skrisz0101** [comment]
Sztem az lenne pont a lényege h az is lássa a változásokat aki nem nagyon szokta követni. Aki mindig résen van, általában tudja. (bár ez se mindig igaz)

1 szoba nem oszt nem szoroz szerintem

**Comment by MrZero1** [comment]
Épp erre szolgálna a bot.

**Comment by MrZero1** [comment]
Elkészült igazából.

A #szerverinfó-hírek szobában lehet kérni automatikusan rangot. Aki nyom egy reakciót, az kap egy rangot. A #hírek szobába meg kiírjuk, ami épp változott, frissült, de nem olyan jelentős, hogy a @everyone-t használjuk. A posztban így csak a @értesítések rangot kell megjelölni, és kész. :D
