### ISSUE TITLE
Savsziget - rossz ómen effekt 

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4582]
**Szerver**: sav

Nem lehet szerezni nagyon pillager tojásokat. 
Sztem jó lenne ha az egyik küldi adna, esetleg lehetne erre építve egy küldetés valami magasabb szinten, ahol életmentés totemet kell szerezni

**Comment by andris155** [comment]
Pontosan hogy legyen a küldetés?

**Comment by skrisz0101** [comment]
Pl:
Küldetés neve: Rabló
craftolj 3 számszeríjat és szerezz 1 gyors töltés III (asszem ez a max)  enchant könyvet
jutalim: rossz ómen III effekt
Erre még lehet építeni küldiket, de azt majd máskor

**Comment by MrZero1** [comment]
Sweetan beállította ezt:

Totemet csak a legvégén kapnak ha teljesítették az összes küldit.
Pillager tojást meg a vasgólemes küldetés és a falusis küldetés ad. így jó?

**Comment by KingDeadZ** [comment]
Szerintem itt főleg az effekt a lényeg

**Comment by andris155** [comment]
A pillager spawn egg elég ritkán rak le pillager captain-t. Ha sima pillager-t ölik meg azzal pedig nem kapnak ilyen effektet.

**Comment by KingDeadZ** [comment]
Lehet a pluginban rakni olyat, hogy effektet adjon.

**Comment by andris155** [comment]
Hozzáadtam a parancsot.
