### ISSUE TITLE
Survival - Új Old szett nocheat hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4583]
Ha farmland blokkon járkálok gyorsaság és magasugrás V effekttel, random bebugol, és megmozdulni se enged, visszadob folyamatosan.

**Comment by balazzrthd** [comment]
Engem olyan esetekben nem enged mozdulni magasugrásos cipővel, ha belémnő pont egy fa, vagy egy fal mellett van a cargo node és azon ugrok egyet.

**Comment by MrZero1** [comment]
Lehet túl erős az effekt. Csökkenthetem a szetten, aztán belehet cserélni arra vagy valamelyik darabra.

**Comment by UDPSendToFailed** [comment]
Általában jól működik, random lesz ilyen, szóval nem biztos, hogy az effekt hibája.

**Comment by lovi-dev** [comment]
> aztán belehet cserélni arra vagy valamelyik darabra.

Tényleg olyat nem e lehetne e, hogy 2 régi "hagyományos" old  eszközt/páncélt becseréni 1 újra?

**Comment by MrZero1** [comment]
> > aztán belehet cserélni arra vagy valamelyik darabra.
> 
> 
> 
> Tényleg olyat nem e lehetne e, hogy 2 régi "hagyományos" old  eszközt/páncélt becseréni 1 újra?

Nem, nem ilyen céllal került be ez a szett 😄

**Comment by andris155** [comment]
Teszteltem és nekem max akkor ilyen, ha víz van a farmland mellett. Ha valamivel lefeded a vizet pl.: szőnyeggel, akkor nincs ilyen probléma.

**Comment by andris155** [comment]
A fejlesztőnek elküldtem amit kért. Talán később lesz hozzá javítás, de már egyszer megpróbálták ezt javítani és mégsem tökéletes még most sem. Az is lehet, hogy ezt nem lehet másképp megoldani, hogy a csalást is érzékelje meg ezeket az effekteket is teljesen támogassa.

**Comment by andris155** [comment]
A fejlesztő javította ezt a hibát.

**Comment by andris155** [comment]
1016 OCD
