### ISSUE TITLE
Netherite scrap UU matterért

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4585]
**Szerver**: Survival, Sav

Mivel az új Infinity addon miatt rengeteg mennyiségű netherite kell, gondoltam, hogy a receptbe be lehetne rakni.
8db UU matter >> 1 netherite scrap

**Comment by skrisz0101** [comment]
(1 gyémánt 9 UU matterbe kerül)
1 netherit így 24 UU matter lenne

**Comment by Sanszi** [comment]
Ha bekerülne, akkor a boltból kikerülne az eladása. Melyik legyen?

**Comment by Sizarra** [comment]
> Ha bekerülne, akkor a boltból kikerülne az eladása. Melyik legyen?

Szerintem inkább a gyártás. A legtöbb player nem a boltban adja el, hanem egy másik playernek, mert sokkal többet keresnek rajta.

**Comment by IciAlex** [comment]
Sanszi ennyi erővel az egész boltot kivehetnétek...

**Comment by Sanszi** [comment]
> Sanszi ennyi erővel az egész boltot kivehetnétek...

Ezen is elgondolkoztam már, végülis azért van bent a jobs, hogy pénzt keressenek vele a játékosok.
A slimefun meg a bolt együtt egyébként is nehéz megoldás.

**Comment by Icecroft** [comment]
Jó ötlet a netherit szerzés UU-matterből, de mivel kikerült az Advanced massfabricator, így már az egész LiteExpansionnek gyakorlatilag semmi értelme. Akár ki is vehetitek a plugint is, mert egy sima Massfabricator fogyasztása 27k felett van, a sebessége is gyenge, egyszerűen nem éri meg ezzel foglalkozni, az így kapott anyagok az idő és anyagi ráfordítás szempontjából nem érik meg.

**Comment by andris155** [comment]
A probléma ott volt, hogy az Advanced Mass Fabricator bekerült és erről sokan nem is tudtak. Az UU-Matter egy nagyon nehezen és drágán létrehozható tárgy modokban és az addon-ban is és ez így is van rendben. Idővel biztosan lesznek olyan játékosok akik eljutnak olyan szintre, ahol ezt érdemes már használni.

**Comment by andris155** [comment]
A Cargo Configurator miatt hasznos még az addon ja valaki később sem szeretne UU-Matter-t használni.

**Comment by skrisz0101** [comment]
mindenki tudott róla h van adv mass, mert csak az használható. Sima mass fabricator használhatatlan. Mától senki se fogja használni az UU mattert, szóval ezt le is lehet zárni, felesleges róla beszélni

**Comment by Sizarra** [comment]
Az adv mass kivétele helyett, szerintem inkább balanceolni kellett volna.

**Comment by skrisz0101** [comment]
> A probléma ott volt, hogy az Advanced Mass Fabricator bekerült és erről sokan nem is tudtak. Az UU-Matter egy nagyon nehezen és drágán létrehozható tárgy a modokban és az addon-ban is és ez így is van rendben. Idővel biztosan lesznek olyan játékosok akik eljutnak olyan szintre, ahol ezt érdemes már használni.

nem, nincs olyan szint ahol megéri
