### ISSUE TITLE
Rainbow blockok

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4586]
Survival, Savsziget->

Jó pár éve a sfbe levő rainbow dolgok kilettek véve laggoltatás miatt. Kérdésem: Most is másképp lenne?
Szerintem meglehetne  próbálni visszarakni, hogy playerek díszíteni tudják otthonukat. (Szemény szerint nekem a karácsonyi rainbow blockok tetszettek legjobban) Meg szerintem sokan szeretnék jelzőfényüket egy rainbow glassel díszíteni. Ha esetleg a staffok félnek e döntés mellet állni, akkor két megoldást látok rá. Első, hogy egy chunkba max 3-5 rainbow cucc lehet, vagy a második, hogy egy player maximum 5-10et rakhat le egy világba.

**Comment by andris155** [comment]
Sajnos a blokkok változtatásához a szerver CPU-t használja. Sok blokknál viszonylag jelentős szerver CPU-t használ. Mivel ez csak egy dísz és nem jó igazából semmi másra, inkább nem szeretném ezt engedélyezni.
