### ISSUE TITLE
Survival csapóajtó spawn

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4587]
**Szerver**: Survival

![kép](https://user-images.githubusercontent.com/29709854/114315930-8a26c000-9b01-11eb-8015-c89104226517.png)

Ezt írja ki a játékosnak, ha a spawnon egy csapóajtót próbál lenyitni, NojinElife jelezte.

**Comment by andris155** [comment]
Már jelentett hiba. Erre sajnos egyelőre nincs megoldás.
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/756
