### ISSUE TITLE
Webstore slimefun rész fejlesztése

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4588]
A Minemarketen lévő slimefunos itemekből a szerver már nem hiszem, hogy nagy forgalmat csinál, a legtöbb item a gyárak miatt már könnyen elérhető, a player warpokon aránylag olcsón megvásárolható. Gyakorlatilag a meglévő sf itemeket akár lehetne törölni is a boltból.
Amiket érdemes lenne viszont berakni:
- 1 db Radiant solar generátor:  508 OCD
- 2 db Bottomless fluffy barrel: 508 OCD
- 5 db Infinity ingot 508 OCD

**Comment by KingDeadZ** [comment]
az infinity ingot az nagyon p2w, a többit támogatom

**Comment by skrisz0101** [comment]
Egy kicsit olcsónak tűnnek nekem az árak
Főleg az infinity ingot

**Comment by Icecroft** [comment]
ha egy db ingot 5000 OCD, senki sem veszi meg. Jelenleg a craftolása kb a lehetetlent súrolja, nincs alternatíva. Egyébként 5 db infinity semmihez sem elég.

**Comment by skrisz0101** [comment]
akkor már inkább újra kéne írni az egész slimefun részt. Így elnézve most az árakat

**Comment by Sizarra** [comment]
Ha nem is 5db infinity, akkor lehetne kettő darab.

**Comment by andris155** [comment]
Egyelőre ezeket az addon-os dolgokat még nem merem beállítani OCD-ért, mert ezek még elég új addon-ok. Majd ha már hosszabb ideje fejlesztik ezeket folyamatosan, akkor lehet bekerülnek MineMarket-re.

**Comment by andris155** [comment]
Az ötlet azért köszi.

**Comment by andris155** [comment]
@skrisz0101 A régi Slimefun részt nem sok értelmét láttam így berakni az új market-re. Kellene egy lista, hogy mi és mennyiért legyen vehető, amire lenne igény is. Az OCD-s is ár is jó hozzá.

**Comment by MrZero1** [comment]
Ezeket lehessen most is venni, tőlem, hogy a meglévő OCD-ket ellehessen költeni?

**Comment by andris155** [comment]
@MrZero1 Az a te döntésed, hogy mit adsz el OCD-ért. A Slimefun tárgyaknál figyelmeztesd őket, hogy jóvan nagyobb eséllyel tűnnek el a plugin/addon hibák miatt. Utána pedig nem tudjuk visszaadni ezeket.

**Comment by MrZero1** [comment]
Persze, ez egyértelmű. :D

**Comment by andris155** [comment]
A régi Slimefun részből az is kellene, hogy mi maradjon és mennyiért? (akár OCD-s ár is jó.)

**Comment by Icecroft** [comment]
A véleményem továbbra is az, hogy a régi slimefunos dolgokat teljesen ki lehet venni.
Amiket most beraknék:
- Radiant solar generátor  500 OCD
- Void panel 1500 OCD
- 5 Infinity ingot 1000 OCD

**Comment by IciAlex** [comment]
Szerintem az Infinity Ingot 1000OCDért 5db nagyon olcsó...

**Comment by Icecroft** [comment]
Csak egyetlen Infinity panelhez 54 db kell belőle, egy infinity quarryhoz 62 db.
Ha túl magas az ár, senki sem veszi meg. A szerver támogatása a fontos,

**Comment by MrZero1** [comment]
3 db / 1000 OCD?

**Comment by IciAlex** [comment]
Ha 5 1000 OCD akkor pl kernel simán vesz belőle 5 stacket és örökre elvan vele

**Comment by IciAlex** [comment]
Infintiy ingotot minemarketbe nem tenném, akkor minek van bent az inf expansion, az inf ingot benne kb a kihívás.

**Comment by Icecroft** [comment]
Ha valaki vesz 5 stack Infinity ingotot 64000 OCD.ért, akkor pont elértük a célunk, alaposan megtámogatta a szervert.
Pont azért tennénk be Minemarketre, mert vannak, akik pénzért a könnyebb utat választják. Erről szól a Minemarket.
a 3-5 db infinity Ingot 1000 OCD-ért továbbra is reális árnak tűnik figyelembe véve, hogy milyen sok kell belőle az egyes Infinity tárgyak legyártásához.

**Comment by MrZero1** [comment]
Paypal esetén a fele ugye, azért azt érdemes figyelembe venni.

**Comment by andris155** [comment]
Mivel nincs már többé SMS támogatás az új market-ben nincs fele meg hasonló árak. Minden fixen egy árba kerül. Kivétel akkor amikor éppen valamikor leárazást tartunk majd.

**Comment by andris155** [comment]
1000 OCD az 500 Ft.

**Comment by IciAlex** [comment]
Kikéne venni így a slimefun részt
Senki nem veszi meg ennyiért.

**Comment by Squidmanus** [comment]
Egyetértek IceCroft-al, viszont az Inf ingotot tényleg nem tenném be. Ez a kihívás, a sok szimulátor már így is kivett egy csomó pénzszerzési módszert(gondolok itt a wither skullra, a farmot több hónapig építettük a régi csapattal, nether star, stb..)az inf ingot egy új dolog, még alig van valakinek gyára, ha egyáltalán van, tényleg ne tegyétek be. Viszont az sf vételre tényleg kéne vérfrissítés.
