### ISSUE TITLE
Levédés slimefun gép probléma.

### ISSUE THREAD

**Issue by MagyarDemon** [TheOld-Crafters/Minecraft-servers#4589]
**Szerver**:

A levédésem területén föld alatt 30 block magasan bele tudnak nyúlni a slimefunos gépekbe, akik nincsennek hozzáadva a területhez.
A felszínen viszont nem tudnak.
Blockot kiütni, letenni, ládát kinyitni viszont nem tudnak. Valamint a /trustlist parancs parancs is mást ír ki fent, mint lent.

**Comment by skrisz0101** [comment]
üss valami blokkot lent, vagy tegyél le valamit, akkor levédi addig a vonalig

**Comment by MagyarDemon** [comment]
Ott van lent a raktáram. Tehát építettem már ott lent.

**Comment by KingDeadZ** [comment]
Ez egy érdekes dolog egyébként, ice pwarpján van szabad szemmel látható cargo, én abba nem birtam belenyulni. 

Nála laci444 is jelezte, hogy tud meg kb 2-3ember, szóval ott lehet valami

**Comment by andris155** [comment]
Próbáld meg törölni a levédést és újra levédeni az egészet.
