### ISSUE TITLE
Survival - El kéne érni egy kompromisszumot az adv massfabbal kapcsolatban.

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4591]
Első dolog: Ahogy néztük, magából a pluginból lett kivéve a massfab, ezért ami le volt rakva az sima betonná változott.

Második dolog: Régen azért került be az "advanced" massfab a pomaexpansionba, mert a normális massfab baromira sok 
áramot fogyaszt, és abszolút nem érné meg használni a simát. Szimplán nem volt jobb ötlet, hogy mi lehetne a massfab előtt, azért lett advanced.

Kompromisszumként dolgok, amik jók lehetnek mindenkinek:

1. Kerüljön vissza az adv massfab, de ha lehet akkor az áram használatát kicsikét feljebb lehet venni, pl 200ról 600-800ra akár.

2. Visszakerül az adv massfab, de az UUmatterből való craftolások outputját le kell felezni pl, 24redstone dust -> 12

3. Ha abszolút nem kerül vissza az adv massfab, valamilyen kártérítést kéne osztani azoknak, akiknek most csomó értéke ment a kukába a pluginból való kiszedése miatt, ami nem mass fabricator, mert azt ezek után nem igazán fog használni senki, maximum pár ember bírna 1dbot üzemeltetni.

4. Ha nem kerül vissza az adv massfab, kárpótlás és az uumatter craftokból kaphatnának a játékosok több itemet.

**Comment by skrisz0101** [comment]
+2

**Comment by skrisz0101** [comment]
mondjuk a 800 azért már kicsit túlzás, de egy 400-500 még belefér sztem, max 600

**Comment by lovi-dev** [comment]
Semmi olyan lényeges nincs a uu_matterben amit máshogy nem tudnál előállítani.
Legtöbben vagy szén, csonpor vagy gyémánt/redstone/lapis előállítására használták, de infinity gépeknek köszönhetően  erre már nincs szükség. Az infinity gépek sokkal kevesebb géppel/cargoval adjá ezeket...

**Comment by andris155** [comment]
A lerakott blokkokat kiütve már a rendes tárgyat adja vissza. Aki pedig kiütötte az elvileg ha rak a helyére egy blokkot akkor megkapja. A beváltóba lehetne esetleg kitalálni mást hozzá. Mivel szerintetek az a beváltás nem éri meg.

**Comment by andris155** [comment]
Eladható lett mindkét szerveren a beváltó warpon.
A túlélőn: $150 000/db.
A savszigeten: $225 000/db.

**Comment by UDPSendToFailed** [comment]
A Recycler-re is kéne eladás, mivel így az is használhatatlanná vált.

**Comment by andris155** [comment]
Azt max akkor tenném azzá, hogy ha kikerül a LiteXpansion.

**Comment by UDPSendToFailed** [comment]
A Scrap, amit gyárt, semmi másra nem jó, csak Mass Fabricator-ban felhasználni.

**Comment by MrZero1** [comment]
> A Recycler-re is kéne eladás, mivel így az is használhatatlanná vált. 

milyen ár lenne neki reális?

**Comment by andris155** [comment]
A Discord-on 50k-t írtak.

**Comment by KingDeadZ** [comment]
Kb. 50-55kt érhet egy recycler
