### ISSUE TITLE
Sav Sziget Hiba!

### ISSUE THREAD

**Issue by Goldie2000** [TheOld-Crafters/Minecraft-servers#4592]
**Sav Sziget Szerver**:

**Találtam egy kis hibát!**

A Sav Szigeten nem lehet a [V.I.P]-nak /head illetve a /fix parancsot be írni!
(De Survivalban meg lehet)

Kérem ezt javítsák ki!

Köszönettel: _**Goldie2000**_

**Comment by IciAlex** [comment]
![image](https://user-images.githubusercontent.com/74869381/114594011-10234200-9c8d-11eb-99fd-8fbc04319d75.png)

**Comment by BagdiSandor** [comment]
A 2 szerveren eltérőek a jogok :)
~KillerX

**Comment by andris155** [comment]
A /head parancs egy megadott játékos fejének létrehozására van. Erre csak az adminnak van joga. Szerintem te a /heads parancsot akartad inkább használni.
A /fix parancs a savszigeten az elit rangtól elérhető.
