### ISSUE TITLE
Túl érzékeny az anti cheat

### ISSUE THREAD

**Issue by balazzrthd** [TheOld-Crafters/Minecraft-servers#4593]
**Szerver**: Survival

Eventeken, főképp spleefen sok embert dobál össze vissza az anticheat, mivel az alatta lévő block az ugrás pillanatában kiütődik, de közben fut tovább a player. Mikor ezt érzékeli, visszadobja a semmi fölé az embert, ezáltal kiesik. Valakit a vízből dobott vissza a pályára, valamikor meg futás közben is érzékelődik ez. A netemmel nem volt gond abszolút, tehát nem net hiba ez.

**Comment by andris155** [comment]
Ezzel nem tudok mit kezdeni. Kellene rendes hivatalos Spleef plugin, amit jobban támogat a cheat védelem is.

**Comment by skrisz0101** [comment]
mint az ultraspleef :o

**Comment by andris155** [comment]
Az ultraspleef már nagyon elavult plugin sajnos.

**Comment by andris155** [comment]
Később lesz rá majd publikus rendes plugin azzal talán jobb lesz. Addig erre nem tudok megoldást.
