### ISSUE TITLE
Recycler tábla

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4594]
**Szerver**: Survival

Az adv mass fab kivétele után nagyon sok játékosnak nem éri meg a simát használni, így azt tervezik, hogy váltanak a LiteX-ről az Infinity-s megoldásokra. Ezáltal nagyon sok Recycler maradt meg nekik, aminek a lecraftolása elég sok nyersanyagot igényel.
Mivel már nem használják a UU-mattert így feleslegessé vált a Recycler. Lehetne a beváltó warpon egy eladás tábla, vagy legalább egy csere lehetőség (ha ez nem is egyenértékű csere lenne).

**Comment by KingDeadZ** [comment]
#4591

**Comment by andris155** [comment]
Most ha Zeri rákérdezett az árra gondoltam ez nem kérdéses és ki is rakja a táblát.

**Comment by andris155** [comment]
Beállítottam hozzá a sell táblát a beváltó warpra.
