### ISSUE TITLE
Húsvéti tojás hiba

### ISSUE THREAD

**Issue by Krumplee25** [TheOld-Crafters/Minecraft-servers#4595]
**Szerver**: Savsziget

 Összegyűjtöttem mind a 75 húsvéti tojást a spawnon, de nem kaptam semmit.

**Comment by andris155** [comment]
Csak otthon tudom tesztelni, hogy valóban rossz-e. Tehát valamikor 23 óra körül.

**Comment by andris155** [comment]
Amit én beállítottam, az hibátlanul működik. A probléma ott van, hogy valójában 77 tojás van nem pedig 75.

**Comment by andris155** [comment]
Ha megtalálod mind a 77 tojást meg kell, hogy adja a jutalmat.
