### ISSUE TITLE
ChatControl kihagyott sértő szó

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4596]
![image](https://user-images.githubusercontent.com/38157910/114737312-30173c00-9d47-11eb-9d9f-f6f54cf36604.png)
Az anyátok szót hozzá lehetne adni a chatcontrolhoz :D

**Comment by andris155** [comment]
Tiltottam. Köszi a javaslatot. 508 OCD.
