### ISSUE TITLE
GriefPrevention érdekes bug

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4597]
A lefelé bővülő levédés eléggé bugosan viselkedik.

- A /trustlist nem megy, hiába volt építve arra a szintre, ahol néztük.
- Levédésként mutatta az aranykard
- A cargokat lehet nyitogatni, hiába nem vagyunk hozzáadva a levédéshez
Ma lett levédve a terület.

https://youtu.be/LKImiPAuQA8

**Comment by andris155** [comment]
Próbáljátok meg teljesen újra levédeni, ha akkor is rossz akkor nyiss egy új jelentést azzal, hogy az újra levédés után sem lett védett a cargo ott.

**Comment by andris155** [comment]
+ lehet valami flag bezavar, nézzétek meg flag-ek nélkül.
