### ISSUE TITLE
Fegyver enchantok chaten

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4601]
ChatControl frissítés előtt ha rávittem az egeret, írta a fegyverek enchantjait, és a nevük is színes volt, ez jó lenne most is.

![image](https://user-images.githubusercontent.com/16057404/114872613-c9ebf100-9dfa-11eb-8936-5c20519368b8.png)

**Comment by andris155** [comment]
Nincs köze ennek a Chatcontrol-hoz semmilyen formában sem.

**Comment by andris155** [comment]
Letudod tesztelni, hogy a vanilla játékban hogy írja ki?

**Comment by andris155** [comment]
1 óra tesztelés után sikerült rájönni mitől ilyen. Javítottam. Köszi a jelentést.

**Comment by andris155** [comment]
508 OCD
