### ISSUE TITLE
Jobs booster hátralévő idő

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4602]
A rangokhoz hasonlóan a Jobs boosterekre is lehetne valami parancs, ami mutatja, mennyi van még az egy órából. A /jobs bonus írja, hogy aktív-e, de a hátralévő időt nem.

**Comment by andris155** [comment]
Remélem akkor végül maradsz a szerveren.

**Comment by andris155** [comment]
Ezt jelenleg sajnos nem lehet megoldani, ha lesz rá javítás akkor tudom ezt csak megoldani.

**Comment by MrZero1** [comment]
Esetleg javítva lett ez?
