### ISSUE TITLE
Újra megváltozott a chat - mcmmo

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4604]
Jó lenne újra visszakapni a régi designt, az sokkal átláthatóbb és szebb 
![image](https://user-images.githubusercontent.com/38157910/115019249-37f6ed80-9eb9-11eb-8aae-36fce324350c.png)

**Comment by andris155** [comment]
Szerintem az újabb jobb, csak ti inkább a régebbit szoktátok már meg.

**Comment by KingDeadZ** [comment]
Esetleg akkor a partychatban lévő szövegeket át lehetne szinezni? Annyira nem átlátható, ha többen vagyunk fent

**Comment by andris155** [comment]
Azt nem írtam, hogy nem javítom. :D

**Comment by KingDeadZ** [comment]
Köszönjük :D

**Comment by skrisz0101** [comment]
sztem elég lenne átszínezni, nekem is jobban tetszik a mostani 🌵

**Comment by andris155** [comment]
Mik legyenek a színek?

**Comment by balazzrthd** [comment]
> Mik legyenek a színek?

Nekem mindegy, csak ne olyan legyen, mint Teddmelk-nek, hogy hunyorítva alig lehet látni. Valami élénk színt javasolok, ami nem tartalmazza az automatikus üzenetek színét. (Pl. Hírdetés, eventek színei)

**Comment by KingDeadZ** [comment]
![image](https://user-images.githubusercontent.com/38157910/115066085-524bbe00-9eef-11eb-9110-43889388a949.png)
Ez a két szöveg eléggé rossz, ebből a régi fixen jobb lenne. 
Ha a játékos ír ki valamit, akkor pedig szerintem maradhatna ugyan úgy a régi &aSzöveg
Talán ezen kívül a nyilat lehetne még átrakni &a-ról talán &b-re? Nem tudom, hogyan nézne ki hirtelen az úgy. A party tulaj szinét nem kell viszont változtatni, az jó.

**Comment by skrisz0101** [comment]
+1 kinghez

**Comment by KingDeadZ** [comment]
Ha kész lesz, majd megnézzük de szerintem azért talán a régi sokkal kivehetőbb lesz chaten

**Comment by andris155** [comment]
Visszakerült a régi. Arra nem volt panasz.
