### ISSUE TITLE
ChatControl finomítása

### ISSUE THREAD

**Issue by balazzrthd** [TheOld-Crafters/Minecraft-servers#4605]
**Szerver**:Gondolom mindegyik

Ezt a szót kicenzúrázza, pedig nem kéne:
Jaffaszelet
Ezt a szót nem cenzúrázza ki, pedig ki kéne:
basszameg

**Comment by andris155** [comment]
A Jaffaszelet nem létező szó. Nem létező szavakra nem akarok inkább javítást írni. Így is már elég káoszos az egész. :D

**Comment by balazzrthd** [comment]
> A Jaffaszelet nem létező szó. Nem létező szavakra nem akarok inkább javítást írni. Így is már elég káoszos az egész. :D

A jaffa szelet az más néven a fanta szelet. 
https://www.google.com/search?q=jaffa+szelet&sxsrf=ALeKk02oHMIv4TmdN0hSaBsjsZhcUbodbg:1618593511231&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjI5JbaooPwAhXM0aQKHV_-B48Q_AUoAXoECAEQAw&biw=1366&bih=657#imgrc=4WnCvgdXlYuwCM

**Comment by andris155** [comment]
De te space nélkül írtad először.

**Comment by andris155** [comment]
Javítottam mindkettőt. Köszi a jelentést. 508 OCD.
