### ISSUE TITLE
Fluffy

### ISSUE THREAD

**Issue by Csongor52** [TheOld-Crafters/Minecraft-servers#4608]
**Szerver**:Survival

Lehetne egy gomb a fluffy-kban, ami egy kattintással tölti az inventory-t és akár ez visszafelé.

**Comment by KingDeadZ** [comment]
Az ilyen ötleteket a slimefun discordra írd meg.

**Comment by andris155** [comment]
A Slimefun Discord szerverén az other-addons szobába fogadnak el talán fejlesztéseket ehhez az addon-hoz. A Discord szobában FluffyBear néven van bent az addon fejlesztő. Szóval ha oda megírod angol nyelven, akkor szerintem látni fogja.
https://discord.com/invite/slimefun
