### ISSUE TITLE
Singularity

### ISSUE THREAD

**Issue by Csongor52** [TheOld-Crafters/Minecraft-servers#4609]
**Szerver**:Survival

Nagyon tetszenek az új infinity kiegészítők, viszont amikor automatizáltam a singularity gyártást, felmerült bennem, hogy meg lehet-e oldani a singularity visszaalakítást, mert sokszor túlszaladt a rendszer a kívánt mennyiségen.

**Comment by KingDeadZ** [comment]
Az ilyen ötleteket a slimefun discordra írd meg.

**Comment by andris155** [comment]
A Slimefun Discord szerverén az other-addons szobába fogadnak el talán fejlesztéseket ehhez az addon-hoz. A Discord szobában Riley néven van bent az addon fejlesztő. Szóval ha oda megírod angol nyelven, akkor biztosan látni fogja.
https://discord.com/invite/slimefun
