### ISSUE TITLE
Vip warp, állatidomár bővítés

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4610]
**Szerver**:Savsziget

A vip warpon az állatidomár nevezetű npc kínálatát a következő spawner eggekkel lehetne bővíteni: silverfish, vex, drowned. 

Ebből a három mobból a vex az egyetlen, amit bárhogy is meg lehetne szerezni, azt is nehezebb módon. A silverfisht és a drownedet jelenleg CSAK is a spawnerek ládából lehet nyitni. Még lenne bőven mivel bővíteni az npc-t, viszont ezek azok a mobok, amiket eddig észrevettem, hogy sehogy máshogy nem lehetne megszerezni.

**Comment by MrZero1** [comment]
Kész. Köszi az ötletet!
