### ISSUE TITLE
Plot

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4611]
Survi

Ha a biomot crimson forest-re álítod akkor rengeteg Hoglin spawnol le, kb 5mpenként spawnol egy csoportnyit és dispawon egy másikat. A hoglin ellenséges, de szerencsére telken nem tud bántani.

![image](https://user-images.githubusercontent.com/74869381/115143855-f21d5f00-a049-11eb-887f-4e15788b2e9f.png)

**Comment by andris155** [comment]
Letiltottam a mob spawn-t hozzá.

**Comment by andris155** [comment]
508 OCD
