### ISSUE TITLE
Lucky blockok

### ISSUE THREAD

**Issue by SeagullPeti200** [TheOld-Crafters/Minecraft-servers#4612]
**Survival**:

A very lucky blockoknak lehetnének változatosabb dropjai, kb 10 féle dolgot dobálnak folyamatosan.

**Comment by andris155** [comment]
16 fajta dolgot dob ebből Lucky kulccsal pedig még több dolog szerezhető. Szerintem ez így azért nem kevés.

**Comment by andris155** [comment]
55 fajta dolgot dob ebből Lucky kulccsal pedig még több dolog szerezhető. Szerintem ez így azért nem kevés.
