### ISSUE TITLE
Slimefun - Feloldott cuccok

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4613]
Egy embernek eltűnt most pl. a carbon press feloldása, és újra fel kell hogy oldja úgy, hogy eddig megvolt. Másnál is volt már ilyen, fogalmam sincs hogy mi okozhatta. (Csak neki újra feloldani, másnál jó)

**Comment by andris155** [comment]
Sajnos ezen nem tudok javítani. Semmiféle ezzel kapcsolatos hibát nem láttam a log-ban. Meg ezt így reprodukálni se tudom. Eltűnt azt értem. De hogyan? Mit csinált, hogy eltűnt? Mi történt esetleg, amitől eltűnhetett? Ezek nélkül ezzel így nem tudok mit kezdeni.
