### ISSUE TITLE
kámfor stand

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4614]
**Szerver**: Survivall

Ziredus területén az armorstandes bugfix bevezetése óta eltűnt néhány dekorációs armorstand. Volt köztük olyan, amelyiknek a közelében sem volt másik.

**Comment by andris155** [comment]
Ha nincs mellette egy sem, de akár csak egyetlen armor stand is belelóg az armor stand-be akkor azt törölni fogja a szerver. Nem tudok ezen a bugfix-en változtatni. Ha nem lóg bele az egyik a másikba akkor nem törli a rendszer.
