### ISSUE TITLE
Synthesizer bug

### ISSUE THREAD

**Issue by Forgacsm** [TheOld-Crafters/Minecraft-servers#4615]
Savsziget
**Szerver**:

Ha a resource synthesizerrel akarok craftolni pl reinforced ingot akkor amint lerakom egyből -2milla áramom van

**Comment by balazzrthd** [comment]
Írja, hogy mennyi energiát von le 1 singularityért. 1 craft 1 Millió energia.  Ahány cucc van benne, annyiszor 1 Millió energiád megy le.

**Comment by Forgacsm** [comment]
de nem rakok bele semmit se amint lerakom minusz 2millio energia

**Comment by balazzrthd** [comment]
> de nem rakok bele semmit se amint lerakom minusz 2millio energia

Akkor meg azért, mert úgy működik, mint az infinity workbench. "Meghitelezed" az első használat energia használatát előre mindig. Nálam is le volt téve az infinity workbench, semmit nem craftoltam, de levonta az energiát. Viszont érdekes a 2 milliós levonás, mert a crafting receptnél csak 1M/use-t ír

**Comment by andris155** [comment]
Ezt írta rá a fejlesztő: „thats cuz it can hold 2 mil at a time but will only use 1 mil.”
