### ISSUE TITLE
Chatcontroll hiba

### ISSUE THREAD

**Issue by balazzrthd** [TheOld-Crafters/Minecraft-servers#4616]
**Szerver**: Gondolom mindenhol

Party chaten tesztelgettem.
A "kurvára" szókapcsolatot nem cenzúrázza ki, ameddig a kurva szót kicenzúrázza

**Comment by andris155** [comment]
Vannak még olyan szavak, amiket szoktak használni, de nem cenzúrázza?

**Comment by balazzrthd** [comment]
> Vannak még olyan csúnya szavak, amiket szoktak használni, de nem cenzúrázza?

Mindig saját tapasztalat alapján írom ezeket ide, amelyek felmerülnek. De ha van ilyen, azonnal írok ide gh-ra.

**Comment by andris155** [comment]
Hozzáadtam. Köszi az ötletet. 508 OCD.
