### ISSUE TITLE
Jobs bonus számítási hiba

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4618]
Ha a rangomnál fogva van +16% xp bonuszom és ahhoz veszek egy egy órás +75%-os bónuszt, akkor a +91% helyett csak +75% lesz az xp bónusz.

![2021-04-20_22 43 31](https://user-images.githubusercontent.com/19332825/115465129-657fc600-a22e-11eb-9353-647448037b4e.png)

**Comment by andris155** [comment]
Nincs ebben semmilyen hiba. Sajnos nem lehet megoldani azt, hogy a permission utáni számokat összeadja a plugin. Ki is írtam a MineMarket-re, hogy az Elit rangtól az extra megszerezhető munka boost jogok nem működnek.

**Comment by andris155** [comment]
508 OCD
