### ISSUE TITLE
Plot

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4619]
Survi

Lehetne egy olyan flag amivel belehet álítani hogy az Olvasó álványt tudják mások is használni, de a könyvet ne tudják kivenni belőle(mint levédésen).

greeting flaget is jó lenne ha lehetne használni.

**Comment by andris155** [comment]
Nincsen sajnos olyen flag oda.
A greeting engedélyezve lett.
