### ISSUE TITLE
Chat hiba

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4622]
**Szerver**: Survival, Savsziget

![image](https://user-images.githubusercontent.com/29151964/115711557-f44a2b00-a373-11eb-8198-9c0cfee238fb.png)
A chaten a kettőspont elé és után a képen látható karaktersort illeszti be.

**Comment by andris155** [comment]
Visszaraktam a régi verziót, amiben nincs ez a hiba. A fejlesztő azt írta, hogy készít majd javítást hozzá.

**Comment by andris155** [comment]
Köszi a jelentést.
