### ISSUE TITLE
Plot területekről való tiltás

### ISSUE THREAD

**Issue by balazzrthd** [TheOld-Crafters/Minecraft-servers#4623]
**Szerver**:Survival

Sok embert zavar, ha járkálnak a telkén, akár for fun, akár ötletlopás érdekében. A chorus fruit letiltása felesleges lenne, mert simán bemennek máshogy is olyan helyekre, ahova nem kéne. Másrészt meg ki lett véve a plotról való végleges kitiltás. Azt javasolnám, hogy legyen lehetőség playerek (akár a "csillag" megjelölésével név helyett mindenkit) kitiltására a telekről, viszont a [Segítő] rangtól ne legyen rájuk érvényes ez, akár a kitiltás ellenére is be tudjanak menni. Másik ötlet : ahogy a levédéseket fel tudod osztani több részre, a telkedet is amely mondjuk 9 teleknyi terület , fel lehessen osztani régiókra és az adott régióra vonatkozzon egy adott player kitiltása, így a telken a nem tiltott régiókat tudja használni, de a tiltott zónákat ne (Sok player boltja telken van, ha az egész telekre vonatkozna a kitiltás és nem azokra a helyekre, ahová nem kéne menniük, az nem lenne megfelelő). Ez lehetne coordináta alapú is, terület két sarka lehetne az alapja. Valamit a "csillag" kitiltás alól lehessen kivételt tenni, de megőrizve a többi ember kitiltását ( az  általad megadott embereken kívül SENKI se tudjon a területre belépni)

**Comment by andris155** [comment]
Engedélyeztem a plot deny parancsot. Elvileg már jól működik.
