### ISSUE TITLE
Chatcontroll - A "ribanc" szót nem tiltja

### ISSUE THREAD

**Issue by balazzrthd** [TheOld-Crafters/Minecraft-servers#4624]
**Szerver**: Gondolom mindenhol

A "ribanc" szót nem tiltja a chatcontroll.

**Comment by balazzrthd** [comment]
+ a baromira szót cenzúrázza, mikor nem kéne.

**Comment by andris155** [comment]
Javítottam. köszi.

**Comment by andris155** [comment]
508 OCD
