### ISSUE TITLE
A boltos shiftje

### ISSUE THREAD

**Issue by WolterFox** [TheOld-Crafters/Minecraft-servers#4625]
**Szerver**: Survival (gondolom)

Survivalon a costum boltos amit a TOC MineMarketről lehet vásárolni 508 OCD-ért tizesével ezt írja ki.
Nem oly nagy gond csak elírás xd
"Adj hozzá tárgyakat, amiket el akarsz adni a tárolóból majd kattints a **shitf** + jobb klikkel a boltra az árak módosításához"

**Comment by WolterFox** [comment]
Sőt, bónuszban.
A rókánál a "Bekapcsolja a Róka Guggolást" a második sorban lévő textnek a róka úgy van leírva, hogy "RÓka"
Tényleg nem nagy hiba de egy kicsit baj xd

**Comment by andris155** [comment]
Javítottuk, amiket írtál. Köszi.
