### ISSUE TITLE
Emojik nem jók

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4627]
**Szerver**:Survi, Sav(?), Építész(?) 

Helló! A hibát lent csatolom, szerintem nem kell hozzáfűzzek semmit. /minőségért sorry/ !/[Uploading IMG_20210423_205250.jpg …]()![IMG_20210423_205238.jpg](https://user-images.githubusercontent.com/69621187/115917165-1a57f400-a476-11eb-8c09-0437cf708fa8.jpg)

**Comment by balazzrthd** [comment]
Laci tegnap / tegnap előtt jelentette már ezt a hibát, ha jól emlékszem.
