### ISSUE TITLE
Strainer

### ISSUE THREAD

**Issue by HunGamerFake** [TheOld-Crafters/Minecraft-servers#4628]
**Szerver**:survival

Volt lerakva helyekre cargo input amit kiütöttem Wrench-el és a helyére raktam strainert. Most amikor kiütöm a strainert akkor inputot dob és a stainer input, output nevű üveglapjait. Ha cargo connectort rakok a strainerek mellé akkor megjelenik az a kék cargo effekt rajtuk

**Comment by andris155** [comment]
Nekem ezt nem sikerült reprodukálni.

**Comment by HunGamerFake** [comment]
Máskor is volt ilyen hogy leraktam egy gépet és az előzőt érzékelte vagy
nem tudom de haszálni sem tudtam és amikor kiütöttem akkor az előzőt adta ki

András Marczinkó ***@***.***> ezt írta (időpont: 2021. ápr.
24., Szo, 15:51):
