### ISSUE TITLE
Régi solar panel csere

### ISSUE THREAD

**Issue by Gabello124** [TheOld-Crafters/Minecraft-servers#4629]
Szerver: 
Survival

A régi solar panelt lehetne becserélni Photovoltaic cellre

**Comment by KingDeadZ** [comment]
tegnap voltam fent, akkor már volt rá beváltón csere, csak nem írta ki senki dcre

**Comment by andris155** [comment]
Annak kellett volna kiírnia, aki berakta.

**Comment by andris155** [comment]
Beraktam a savszigetre is.
