### ISSUE TITLE
Chatcontrol egyéb szavak

### ISSUE THREAD

**Issue by balazzrthd** [TheOld-Crafters/Minecraft-servers#4630]
**Szerver**:Mindenhol

Van jópár szó , aminek az angol jelentését IS kicenzúrázza ( pl. fuck, bitch...), viszont találtam párat, aminek a magyar jelentését kicenzúrázza, még az angolét nem.
Bastard - rohadék 
cum - geci
cunt - picsa
A fent szereplő magyar szavak cenzúrázottak, még az angol jelentésük nem.

**Comment by balazzrthd** [comment]
+ a "felkúrtam" szót sem cenzúrázza :)

**Comment by IciAlex** [comment]
Kéne egy hely ahova ezeket lelehet írni :)

Amúgy: "Ha kell arany, adok"

**Comment by KingDeadZ** [comment]
![image](https://user-images.githubusercontent.com/38157910/116567095-9b483d00-a907-11eb-9818-a1b467cf49cb.png)

**Comment by andris155** [comment]
Módosítottam rajta. Köszi az ötleteket. (Nem mind került megvalósításra.)
