### ISSUE TITLE
Legendás Cipő

### ISSUE THREAD

**Issue by balazzrthd** [TheOld-Crafters/Minecraft-servers#4634]
**Szerver**: Survival (itt fix)

A legendás cipőn található magasugrás 4, gyorsaság és lassú esés 4. A magasugrás és a gyorsaság miatt történik velem gyakran olyan, hogy sprint közben (amit boostol maga a cipő) ugrok és visszadob emiatt az anticheat. Másik ilyen, ha egy 2x1 blockos helyre leesek és ott van egy cargo, akkor "beragadok" a cargoba az ugrás miatt. Ez a cargos nem gyakran fordul elő (nem is igen estem le), de nagyon idegesítő ha megtörténik.

**Comment by andris155** [comment]
Szóval akkor akkor a fejeken ugrálva van gond vele. Az, hogy cargo az a fej az lényegtelen ebben az esetben. Más blokkon nincs gond?

**Comment by balazzrthd** [comment]
> Szóval akkor akkor a fejeken ugrálva van gond vele. Az, hogy cargo az a fej az lényegtelen ebben az esetben. Más blokkon nincs gond?

Még az ágynál van vele ilyen probléma, meg ha a shulker boxot kinyitod, majd bezárod (ugye van az animáció, ahogy csukódik) és akkor ugrasz, akkor bebuggolsz a shulker boxba.

**Comment by andris155** [comment]
Nekem ezt sajnos nem sikerült reprodukálni. Lehet, hogy internettel kapcsolatos probléma okozza. Esetleg ha még mindig van ez a szerveren készíthetnél egy videót, hogy tudjam pontosan reprodukálni.
