### ISSUE TITLE
Bedrock kiütése ploton/gondolom sima világban

### ISSUE THREAD

**Issue by ketezerhat** [TheOld-Crafters/Minecraft-servers#4635]
survival
**Szerver**:

**Comment by IciAlex** [comment]
Zeri megeditelte :C

**Comment by ketezerhat** [comment]
:c

**Comment by ketezerhat** [comment]
Zeri dc-ről is töröld ha nem akarod hogy lássák mások is

**Comment by MrZero1** [comment]
Amit írtál, azt töröltem innen, de elküldtem Andrisnak privát üzenetben.

**Comment by MrZero1** [comment]
Lehetőleg ne szórakozzatok ezzel, másokat se lökjetek bele vagy hasonló.

**Comment by ketezerhat** [comment]
Okés :D

**Comment by andris155** [comment]
Letiltottam, amiket írtál, főleg mivel valószínűleg a telek szélét is kiszedték ezek.
Köszi a jelentést. Majd vedd fel a kapcsolatot velem Discord-on és megbeszéljük mit kapsz cserébe.
