### ISSUE TITLE
Hg-ról való item bugoltatás

### ISSUE THREAD

**Issue by ketezerhat** [TheOld-Crafters/Minecraft-servers#4636]
Survival
**Szerver**:

 Hg-ról könnyen lehet cuccokat kihozni, csak annyit kell tenni hogy legyen tele az inventoryd (ez azért kell hogy ne tudj felszedni itemeket) és amikor meghalsz legyenek szétdobálva körülötted cuccok, ezeket az itemeket fogod megkapni halálodkor, mivel igaziból nem halsz meg és mielőtt elteleportálna a játék 1 másodperce még ott marad a karakter. (és ugye ami az inventorydba volt azt nem tudnád felszedni mert nincs rá idő viszont amik körülötted vannak azokat feltudod)

**Comment by andris155** [comment]
Megpróbálok majd erre megoldást keresni. De most egyelőre rengeteg dolgom van azzal, hogy munka mellett hétvégére legalább használható szintre megtudjam csinálni a támogatói weboldalt. De utána is még lesz vele bőven munka mire olyan állapotban lesz mint a MineMarket volt. Ezt valamikor utána tudom majd megcsinálni.

**Comment by andris155** [comment]
Elvileg készítettem erre javítást. Majd teszteld le kérlek. Köszi a jelentést.

**Comment by andris155** [comment]
Nem vált be a megoldás szóval majd próbálok mást találni...

**Comment by andris155** [comment]
Készítettem rá egy javítást, ami holnap tölt be. Holnap letudod tesztelni, hogy sikerült-e javítani a hibát?
