### ISSUE TITLE
Seismic axe 

### ISSUE THREAD

**Issue by ketezerhat** [TheOld-Crafters/Minecraft-servers#4637]
**Szerver**: Survival, valószínű Savon is 

 a Seismic axe miatt sokszor jelez az anti cheat. Nem tudom mi lehet az oka, a balta ugye annyit tud hogy amerre nézel a levegőbe röpíti a blockokat (ez persze csak vizuális)

**Comment by andris155** [comment]
Az az oka, hogy nem igazán úgy sebez entitásokat, ahogy egy játékos normális esetben sebezhetne. Egyelőre letiltottam, mert úgy se így semmire, mert blokkolja a cheat plugin. Megírtam a hibát a Slimefun-nak, talán készítenek rá javítást.
A jelentést köszi.
