### ISSUE TITLE
Új támogatói webhely

### ISSUE THREAD

**Issue by andris155** [TheOld-Crafters/Minecraft-servers#4638]
- [x] OCD már nem vásárolható a MineMarket-en. Akinek maradt OCD egy később meghatározott ideig majd feltudja használni.
- [x] Alapszintű dizájn.
- [x] Kategóriák beállítása.
- [x] Termékek beállítása.
- [x] Termékek és kategóriák rendezése.
- [x] OCD felhasználhatósági idő eldöntése.
- [x] Bővebb dizájn fejlesztés.
- [x] A magyar fordítás fejlesztése.
- [x] Publikálás.
- [x] Játékbeli menü beállítása úgy mint a MineMarket-hez.

**Comment by UDPSendToFailed** [comment]
Mi lesz azzal, akinek nagy mennyiségben, 10-20k felett van OCD-je, és nem akarja mindet előre elkölteni?

**Comment by andris155** [comment]
Lesz rá legalább 1 hónap vagy több is. De semmi új nem fog már bekerülni a MineMarket-be.

**Comment by UDPSendToFailed** [comment]
Átvinni nem lehetne a másikba? Így kb rá vagyunk kényszerítve, hogy elköltsük olyan dolgokra, amire jelenleg nincs szükségünk, amikor pedig kéne, akkor nem lesz OCD.

**Comment by andris155** [comment]
Nem lehet, de nem is érné meg, mert más árak lesznek valószínűleg.

**Comment by andris155** [comment]
Minden kész.

**Comment by andris155** [comment]
https://www.oldcrafters.net/2021/05/09/uj-webstore-a-minemarket-helyett/
https://www.oldcrafters.net/2021/05/09/meddig-lehet-elkolteni-az-ocd-egyenlegeket/
