### ISSUE TITLE
OCD elköltés

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4639]
Mindenhol

Jelenleg kivezetésre kerül az OCD ha jól értelmezem a minemarkettel együtt. Javaslat, hogy lehessen a megmaradt OCD-ből venni valamilyen currency-t a játékban (olyasmit mint pl az eventpont) melyeket a player később bármikor elköltheti olyan dolgokra amik számára szükségesek a jelenlegi árfolyam szerint. Tehát pl 5080 OCD-ért kapna a player 5080 OldPoint-ot, melyet el tudna költeni ingame bármikor amikor neki megfelel. Az Old rang ára pedig 5080 OldPoint lenne. Így nincs senki se rákényszerítve arra, hogy gyakorlatilag elverje az OCD-t feleslegesen.

**Comment by andris155** [comment]
Nem lesz ilyen. A meglévő dolgokra ellehet költeni és azoknak az ára sem változik.

**Comment by IciAlex** [comment]
Pedig jó ötlet :)

**Comment by MrZero1** [comment]
És valami szerveres token, mint most az eventes tokenek? 

@UDPSendToFailed
