### ISSUE TITLE
Chatcontroll

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4640]
**Szerver**: mindenhol

Kúra és minden ebből képzett szó csillagozásra kerül, viszont rövid u-val írva nem cenzúrázza.
Bár az obszcén szó helyesen hosszú u-val írandó szerintem lehetne cenzúrázni a rövid verziót is :D

**Comment by andris155** [comment]
Hozzáadtam. Köszi.
