### ISSUE TITLE
Witch Mob Simulator

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4641]
**Survival**:

Behozni a Witch Mob Simulatort, ami redstoneot is termelne, ezáltal a playereknek nem kéne Strainer Baseket meg laggoltató mega gyárakat építeni a redstoneért.

**Comment by TothAlbi** [comment]
Szerintem ez tényleg jó lenne. Olyan 500 J/s szerintem jó lenne fogyasztásnak.

**Comment by lovi-dev** [comment]
> mega gyárakat építeni a redstoneért.

A redstone mobdrop, farmold.  Illetve a quarry-k is termelnek redstone-t. 
Strainer Base mint áram nélkül működő -így végtelen számban használható-  gép csak fölös lagforrás...

**Comment by Squidmanus** [comment]
Na igen, de mennyivel egyszerűbb lenne egy simulator a strainer basek helyett, amihez csapni kéne egy fa-string-reinforced gyárat is, hogy működjön. A lagg is kevesebb lenne szerintem.

**Comment by IciAlex** [comment]
Támogatom az ötletet, kevesebb strainer lenne a szerveren.

**Comment by lovi-dev** [comment]
> Támogatom az ötletet, kevesebb strainer lenne a szerveren.

Miért? Áramot nem fogyaszt, miért ütnék ki?

**Comment by Squidmanus** [comment]
Pl amikor odamegyek a strainerek közelébe, egyből lemegy az fpsem 156-ról 30-40re. És nem egy ember mondta már nekem, hogy ők is laggolnak a strainereknél.

**Comment by andris155** [comment]
A Slimefun Discord szerverén az other-addons szobába fogadnak el talán fejlesztéseket ehhez az addon-hoz. A Discord szobában Riley néven van bent az addon fejlesztő. Szóval ha oda megírod angol nyelven, akkor biztosan látni fogja.
https://discord.com/invite/slimefun
