### ISSUE TITLE
eladó láda

### ISSUE THREAD

**Issue by thecopymaster** [TheOld-Crafters/Minecraft-servers#4642]
*survival,savsziget*:

Lehetne behozni egy olyan ládát amibe ha belekerül egy item eladja a shop árai szerint, ezzel elősegítve a slimefunos automatizálást.

**Comment by balazzrthd** [comment]
https://discord.gg/slimefun

**Comment by IciAlex** [comment]
Én már próbáltam, de nem akarják mert nubok.

**Comment by andris155** [comment]
Ezt lehetetlen megoldani a Chestshop-al. A Chestshop sehol sem tárol adatbázisban semmilyen árat sem. A tábla alapján működik az egész. Nem tudná a Slimefun láda, hogy mit és mennyiért lehet eladni sajnos.
De ötletet azért köszi. A Slimefun-nak ha már megírtátok és nem fogadták el, akkor többet én se tudok tenni.

**Comment by UDPSendToFailed** [comment]
https://www.spigotmc.org/resources/jetssellchests-chests-that-sell-holograms-voidchests-boosters-tax-1-8-1-16.64758/
https://www.spigotmc.org/resources/%E2%9A%A1%EF%B8%8F-wildchests-%E2%9A%A1%EF%B8%8F-sell-chests-storage-units-chunk-collectors-%E2%9A%A1%EF%B8%8F-recoded-system.62622/

**Comment by andris155** [comment]
Ehhez valószínűleg valahol máshol is meg kell adnia az adminoknak az árakat amikor módosítják, ami nem egy túl jó megoldás szerintem így.
