### ISSUE TITLE
/shop bővítése

### ISSUE THREAD

**Issue by Tomi321** [TheOld-Crafters/Minecraft-servers#4643]
**Szerver**:Savsziget

Az egyetlen "hely" ahol a játékosok kereskedhetnek a szerverrel úgymond (pénzzel), a /shop. A shopban elég sok itemet meg lehet venni, és el is lehet adni, viszont van rengeteg, amiket vagy csak venni (pl. netherstar)vagy csak eladni (pl. minden fa) lehet. Ezek közül van amit megértek, annak a szempontjából, hogy a kezdőknek fejlődnie kelljen, ne csak pénzt farmolni éjjel-nappal, viszont vannak olyanok amiket nem. 

Összeírtam egy kissebb listát azokról az itemekről, amiknek szerintem lehetne beállítani eladási/vásárlási árat:
Nether Star: Eladási ár, 6000$/db
Nether Quartz: Eladási ár: 80$/8db
Ender Chest: Eladási ár: 2500$/db valamint a vásárlási árát csökkenteni, mivel 5k/db szerintem igen sok egy ilyen könnyen megszerezhető itemért
Az új 1.16-os nether gombák/fák, stb. : hasonló ár, mint a fáké, csak kicsit drágább eladás/vásárlás szempontjából is.
Netherite: Eladási ár: 2000$/db, vásárlási ár szerintem nem kellene neki.

Ha eszembe jut még valami, akkor bővítem a listát.

**Comment by BagdiSandor** [comment]
A játékosok is csinálhatnak boltokat ahol ezek a dolgok szinte megvannak. Nem mondom hogy mind de fát kb alap hogy árulnak. A netheres gombák beszerezhetőek a cserepiacon itemekért.

**Comment by Tomi321** [comment]
Jelenleg alig van aktív játékos bolt, és ami még is, az nagyrészt sf-es itemeket árul. És ha elolvasnád mégegyszer a listát, itt a lényeg az eladáson van, nem pedig azon, hogy megvehesd ezeket az itemeket.

**Comment by andris155** [comment]
Jó lenne valami pontos ár a fákhoz meg gombákhoz is. A kicsit drágább ember függő, hogy mennyit jelent.

**Comment by andris155** [comment]
A többit beállítottam.
