### ISSUE TITLE
Kraftolási gép név hiba

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4644]
**Szerver**: Survival

Amikor az új dolgok közül akarok kraftolni valamit, és megnyitom a SlimeFun guide könyvet, akkor a kraftoláshoz való gép neve "null"-ra van nevezve. Ezt eddig még csak abban az esetben vettem észre, ha a kívánt kraftinghoz smelteryt/enchanced crafting table-t kell használni, de lehet, hogy más esetben is előfordul.
edit: a pressure chamber-t is null-na írja Kép:
![2021-05-07_21 16 05](https://user-images.githubusercontent.com/67922620/117498038-89a30d00-af79-11eb-8eb9-eabbca4338e4.png)

**Comment by andris155** [comment]
Ez annak köszönhető, hogy nincs lefordítva teljesen. Hozzáadom a fordításos jelentéshez a linket hozzá. Ha átállítod angolra a nyelvet, akkor jól fogja addig írni.

**Comment by andris155** [comment]
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4409
