### ISSUE TITLE
McMMO és Jobs

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4646]
**Szerver**: Survival

Végigolvastam a Komja vs. dc vitát, és az érdemben nem sokat tett hozzá a megoldáshoz senki. Arra gondoltam, hogy összhangba lehetne hozni az McMMO-t és a Jobsot is, így hátha segítene valamit azokon, akik a jobs haszontalansága miatt panaszkodnak(bár amíg bentvan az sf, addig a jobs sosem fog tudni igazán feltörni). Arra gondoltam, hogy minél nagyobb szinten vagy McMMO bányászatban, annál több $-t kapsz egy gyémántért. Nyilván nem úgy, hogy 2000res szinten 1 diáért kap az ember 2000 dollárt, csak mondjuk +20% vagy valami, ezt nem én döntöm el(azért írtam le, mert úgyis jön pár ekcsölni ember akiknek az érvelései a szőrszálhasogatásból és az eltúlzásból állnak). Vagy ott a másik, amit úgysem fognak behozni, főleg hogy most jön az új szeró: egy olyan survival, ahol nincs SF(majd egyszer azért én adnám, remélem nem csak én).

**Comment by TothAlbi** [comment]
Tente he

**Comment by UDPSendToFailed** [comment]
#4482, például. Szinttel növekszik a skill időtartama.

**Comment by lovi-dev** [comment]
> bár amíg bentvan az sf, addig a jobs sosem fog tudni igazán feltörni

Nem az SF-el vagy a Jobs-al van a gong, hanem a bolttal. Amíg lehet a boltba eladni, addig arra fogják használni az SF-et, hogy minnél több és minnél drágábban eladható dolgot gyárátsanak vele... 
Amíg könnyebb bármilyen farmnál/gépnél afkolni majd eladni a bolta, addig nem fog előtérbe kerülni a Jobs.

**Comment by MagyarDemon** [comment]
Szerintem csak külön kéne szembe állítani a kettőt egymással. Tehát jobs-al munka van egyszerűbb megérteni, mint a slimefunt. Ezért lehetne szerintem láthatóan növekvő bevétel belőle. Aki meg slimefun-nal foglalkozna e-helyett annak viszont kikéne találni olyan boltot, ahol el is tudná adni magának. Mondjuk erre jön a csinálj boltot válasz, viszont arra lenne nekem kérdésem a következő. Hogyan csaljak vásárlókat magamhoz 1-2 nagy pláza mellett, ahol minden ott van? Tehát nincs esélyem mellettük, ezért lehetne eladni kevesebbért, de biztosan sf cuccot is. Ezáltal szerintem a kettő kb egyensúly ba lehetne.

**Comment by andris155** [comment]
Ennél több dolgot nem nagyon lehet állítani a Jobs-on ami az mcMMO-val kapcsolatos. Amit lehetett azt már beállítottuk.
