### ISSUE TITLE
Savsziget sárkányidézés

### ISSUE THREAD

**Issue by szofogado** [TheOld-Crafters/Minecraft-servers#4647]
Szerver: Savsziget

A /warp end-en nem lehet megidézni a sárkányt. 
Amikor megpróbálod lerakni a kristályokat, azt írja ki, hogy a sziget védelem alatt ál.
Illetve van egy pár dolog amit még letilt a sziget védelem, pl. Tárgy felvétele, XP felvétele stb...
Átkellene nézni, hogy mi az amit letilt, és mi az amit nem, illetve jogot kellene adni a játékosoknak.

**Comment by andris155** [comment]
Javítottam. Köszi a jelentést.
