### ISSUE TITLE
/csn history

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4648]
Lehetne újra /csn history, eléggé hasznos funkció volt annó, és csak azért kivenni, mert pár gigát foglalt, szerintem elég nevetséges.

**Comment by andris155** [comment]
Nem lesz.

**Comment by IciAlex** [comment]
De most csak azért mer 1gb-et foglal?

**Comment by andris155** [comment]
Azért nem kerül be, mert hibásan kezeli az SQL adatbázist. Illetve nagyon durván szemetel a tárhelyre, mivel rengeteg ChestShop vásárlás van napi szinten.
