### ISSUE TITLE
OCD probléma megoldás

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4651]
A jelenlegi helyzet így nem a legjobb, de viszonylag egyszerűen megoldható lenne.

Kell egy, az eventes tokenhez hasonló (**NEM ugyanaz**, semmi köze nem lenne az event tokennek a kredit egyenleghez) rendszer, amit játékon belül lehet elkölteni a weboldalon elérhető tárgyakra, MineMarket-ről, és az új webshopról is feltölthető (azonos áron) kredit egyenleggel. 

- Nem addolható
- Nem kijátszható, mivel csak MineMarket-ről, vagy az új boltból lehet feltölteni az ingame egyenleget
- A hibajelentésekért járó jutalmak megadása is egyszerűbb, egy parancs
- Továbbra is lehet kereskedni, és gyűjteni rangra, egyéb tárgyakra
- Nem veszik kárba a MineMarket-es OCD
- Szabad választás, aki akarja, azonnal megveszi webshopban a cuccokat, aki nem, az feltölti az egyenlegét, és később költi el, vagy eladja másnak
- Pár óra alatt beállítható

**Comment by UDPSendToFailed** [comment]
Akár, vagy ritkább eseményekkor jutalom, sokkal egyszerűbben megoldható lenne játékon belül.

**Comment by andris155** [comment]
Fogok adni ajándékkártyát annak aki tényleg komolyabb hibát jelent. Én nem szeretném mégegy akármilyen rendszert erre. Megváltozott. Nem értem miért ekkora probléma folyamatosan ha valami megváltozik. A MineMarket valószínűleg még sokáig elérhető lesz. Szóval el lehet költeni az OCD-t ott még egy jó ideig. Valószínűleg az Oldblocks rangok is elérhetőek lesznek ott is ha már megcsinátam rá korábban.

**Comment by andris155** [comment]
Lehetséges, hogy megvalósítom ezt ha lesz időm, de nem úgy, hogy az OCD-t lehet ebbe átvinni. Hanem tényleg arra, hogy a hibajelentésekért adjuk majd esetleg. Az OCD mint írtam még sokáig elkölthető. Egyelőre nem akarom ezt átvitetni onnan máshova. Aki akarja eltudja költeni vagy kereskedni vele játékbeli dolgokért továbbra is.
