### ISSUE TITLE
Mézes anticheat

### ISSUE THREAD

**Issue by WolterFox** [TheOld-Crafters/Minecraft-servers#4654]
**Szerver**: Survival... gondolom

Az anticheat miatt a nemrég postolt #ötletekbe írt eventem lehetetlen mert a mézblock széléről kell ugrani de nem lehet mivel anticheat visszadob :c

**Comment by andris155** [comment]
Ezt a hibát pont ma javítottam a fejlesztő. Holnap már jónak kell lennie.
