### ISSUE TITLE
RAD

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4658]
Régen ha Godban voltál akkor nem kaptad meg a radioaktívos effekteket. Szerintem jó lenne ha ez így lenne, tök feleslegesen teszi rád ha godban vagy mert hát sebződni nem fogsz.

**Comment by andris155** [comment]
A Slimefun-hoz a Slimefun Discord szerverén tudsz ötleteket írni: https://discord.com/invite/slimefun
Ezzel kapcsolatban mi nem állítottunk semmin.
