### ISSUE TITLE
Parancs hiba / Ismeretlen parancs - plot flag

### ISSUE THREAD

**Issue by FalconMisery** [TheOld-Crafters/Minecraft-servers#4660]
Survival Szerver

![Plot Flag Hiba](https://user-images.githubusercontent.com/84023001/118166923-615a5900-b426-11eb-9ded-2aa52d8c0738.png)

Segítségnyújtás során lett észrevéve /UnaRkW/ , hogy a Telek Flagek beállítására nincs lehetőség. A /plot flag parancsig Tab sem juttat el, manuális beírást követően Ismeretlen parancs állapotüzenet jelenik meg.

**Comment by andris155** [comment]
Már jónak kell lennie. Köszi a jelentést.
