### ISSUE TITLE
Páncélállvány eltűnés tök random

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4661]
**Szerver**: szurvi

Néha mikor felmegyek, tök random kb az összes páncélállvány eltűnik a boltomban (és ekkora boltban tökömnek sincs kedve heti 1x újra visszarakni mindet)

1 kordinátán 1 van, nem több

**Comment by andris155** [comment]
Ha összeérnek akkor törli. Ha Slimefun hologram, akkor előfordulhat, hogy az is duplikálódik. Bár elvileg már ezt javították.

**Comment by skrisz0101** [comment]
sima páncélállvány amivel ki szoktam írni a részlegek nevét

**Comment by skrisz0101** [comment]
nem ért össze sehol semmi

**Comment by IciAlex** [comment]
nálam is ez van

**Comment by andris155** [comment]
Jó lenne tudni mi volt a páncélállvány neve pontosan színkódokkal. Illetve mikor tűnt el.

**Comment by andris155** [comment]
Ezek nélkül nem tudok vele mit kezdeni. Az, hogy mikor tűnt el pár nap eltéréssel is jó, csak kb.-ra tudjam, hogy benne lehet-e a log-ban. A neve meg értelemszerűen azért kell, hogy tudjam, hogy egyáltalán a plugin törölt-e, vagy nem is az hanem más miatt tűnt el.

**Comment by andris155** [comment]
Sajnos a múlt heti log már nincs meg. Letudod rakni újra valahova és ha eltűnik akkor tudsz írni egyből?
