### ISSUE TITLE
Chipping generator

### ISSUE THREAD

**Issue by ketezerhat** [TheOld-Crafters/Minecraft-servers#4663]
**Szerver**: Surv/Sav

 A favágó android kiszedi ezt a generátort és átváltoztatja sima fává, jó lenne ezt javítani mivel így kb semmi értelme ennek a generátornak.

**Comment by skrisz0101** [comment]
miért szedi ki? xd

**Comment by lovi-dev** [comment]
Lassan semmi értelme a favágó androidnak, ha nem lesz nem fogja kiszedni :)

**Comment by andris155** [comment]
Ne használd arra, hogy kiszedd vele ezt a blokkot. Ennyi a megoldás szerintem erre.
