### ISSUE TITLE
survival jobs event és bolthoz igaztás ötlet

### ISSUE THREAD

**Issue by MagyarDemon** [TheOld-Crafters/Minecraft-servers#4665]
survival

Mivel a jobs alapjáraton minimál bért fizetnek, ezért lehetnének legalább hétvégi eventek pl 2-3-as szórzó xp-re, meg pénzre is. Mert a bolt gyengítése kihat szerintem a jobsra is, mert nézzünk egy favágót például a fa gyengítése miatt fele annyit kap összesen a jobs ból a bányász a kő leárazása miatt ismént kevesebbet kapott. Esetleg belehetne tenni olyan dolgokat boltba jó eladási áron, amik nem autómatizálható például end kő, vagy vas rúd helyett vas érc, arany érc, vagy a többi érc olyan formában, amit gyengéd érintéses csákival szedtél ki, mert azt nem lehet autómatizálni.

**Comment by lovi-dev** [comment]
> vas érc, arany érc
automatizálható

**Comment by Icecroft** [comment]
Ha gyengédes csákival szedsz ki valamit, nem kapsz érte jobs pénzt/pontokat/xp-t

**Comment by andris155** [comment]
Egyelőre nincs olyan szerver, amin lenne munka és event plugin. Ha újra lesz ilyen, akkor biztosan jobban lesz optimalizálva a rendszer ilyen szempontból is.
