### ISSUE TITLE
Strainer base kivétele

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4666]
**Szerver**: szurvi, sav

nagy mennyiségben iszonyúan feltolja az sf timingset, ki kéne venni

**Comment by ketezerhat** [comment]
ez így van

**Comment by andris155** [comment]
A cargo problémás inkább, nem ez.

**Comment by lovi-dev** [comment]
Strainer basehez is kell cargo, ellenben áram nem, így korlátlan számban használható...

**Comment by andris155** [comment]
Valamivel talán jobb lesz, ha letiltom, de nem lesz tökéletes se. Csak páran használják, viszont ők helytelenül túl sokat belőle.

**Comment by andris155** [comment]
Letiltottam majd. Köszi.

**Comment by skrisz0101** [comment]
Ma 1800-as ms volt rá, sokkal nagyobb volt mint a cargo.
Kis mennyiségben nem érezni, de a 300+t már igen
