### ISSUE TITLE
Skin hiba

### ISSUE THREAD

**Issue by UnaRkWfoglaltvolt** [TheOld-Crafters/Minecraft-servers#4668]
A tegnapi leállás óta a játékosok nagy részének, köztük nekem is az adott szerver kiválasztása útán kapunk egy üzenetet
"[SkinRestorer]  Your skin has beeen changed"
Ekkor visszavált az alap Steve vagy Alex skinre.
Pár játékosnál ez nem történik meg de az esetek 95% ban ez van.
![1](https://user-images.githubusercontent.com/80747757/118392382-bf12bf00-b639-11eb-82bf-9c516c5b356e.png)

**Comment by andris155** [comment]
Javítottam. köszi.
