### ISSUE TITLE
Top 1 slimefun survival mentés

### ISSUE THREAD

**Issue by MagyarDemon** [TheOld-Crafters/Minecraft-servers#4671]
Survival fullos reset minden cargot, gyárat eltüntetve ezáltal a fölösleg is eltűnne, amiről azt se tudtuk, hogy van, és mehetne még évekig megint a szerver, és mire ugyan ennyi cargo összegyűlik fejlettebb lesz a technológia és újra lenne configolva a cargo Ez idő tartam alatt 1-2 ember szomorú lenne, sokan boldogok, mert no lagg van slimefun mindenki boldok ellentkező esetben viszlát sf hello építek random vadonban, semmi egyedi, semmi új, és sorolhatnám. Ez ha megoldás lenne a szerver gép számára kéne szavazatot indítani rá szerintem, hogy mekkora része van benne a játékos közösségnek.

**Comment by lovi-dev** [comment]
Romokban a pénzrendszer, a gazdaság. Akinek volt quarryja ott sokezrével van gyámánt, netherit, resdtone, gold/iron minden...

GUI-s bolt? És minek, ugyan úgy farmank csak most épp restoneos lesz, hopperhegyekkel....

**Comment by UDPSendToFailed** [comment]
Azok a cuccok idővel elfogynak, ha nincs utánpótlás.

**Comment by Sizarra** [comment]
> Romokban a pénzrendszer, a gazdaság. Akinek volt quarryja ott sokezrével van gyámánt, netherit, resdtone, gold/iron minden...
> 
Én pl a quarryból kibányászott érceket beleforgattam a szingularitásba, szóval nálam 1 darab érc sincs, ellenben kitörölhetem a színes nevű, lerakhatatlan blokkal.

**Comment by andris155** [comment]
Jelenleg nincs tervben szerver újrakezdés (reset).
