### ISSUE TITLE
Sf helyett: Ötletek egybe mind, reteknek sincs kedve külön

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4672]
**Szerver**: szurvi, sav

Tesztre majd be lehetne rakni mindent h meg legyen lesve előtte h jó-e

Ötletek:
-Járművek: Ami volt régen is
-Spawner kiszedés: ami(k) volt(ak) régen spawneres plugin, asszem pomáé volt. Akár fejlesztjető is lehetne.
-Luckyblock: ami van az új szerón is, az jó.
-Egyedi enchantok: ami van az új szerón is, az jó
-Táska: biztos van valami kis egyszerű táska plugin, de tökömnek sincs kedve keresni.
-Minionok: ha jól tudom erre is van valami plugin.
-Bossok, egyedi mobok: mythicmobs van ehhez, csak mobokat/bossokat kell gyártani
-Még1 mobos plugin. Nem tudom hogy mennyire kompatibilis a mythicmobssal, de ez is egy jó pluginnak néz ki:  https://www.spigotmc.org/resources/levelledmobs-for-1-14-x-1-16-x.74304/
-Boss aréna: nemtom mennyire kivitelezhető, nemtom van-e rá plugin
-Ha lehetséges, valami itemszállító/szelektáló plugin/rendszer. Nemtom van-e, nincs kedvem körbenézni.
-Képességes plugin. Akár Mcmmo mellett, vagy helyett, szerintem ez egy tök jó plugin. Pont szembejött velem máshol is:  https://www.spigotmc.org/resources/aurelium-skills-advanced-skills-stats-abilities-and-more.81069/
-Több érc betétele: jónak néz ki. https://www.spigotmc.org/resources/⛏%EF%B8%8Fmore-ores⛏%EF%B8%8F.77221/?__cf_chl_jschl_tk__
-Favágó plugin. Láttam olyat is valahol, hogy ha kivágtál egy fát, azt imitálja mintha kidőlne és ha alatta vagy, akkor sebződsz.  *Ismét lusta vagyok keresgélni*

-**Pénzért we, oka: Pénznek már nincs értéke. Legnagyobb érték most talán a ,,SKirályi SKorona", amit 50k-ért meg tudtok venni minden /pwarp skrisz01 üzletben! Használjátok a ,,Skirály vagyok" kupont 10% kedvezményért!**

Kicsit ,,nagyobb" ötlet:
-Egyedi receptek: customcrafting-gal sok dolog megoldható. Nem olyan alap 
     receptekre gondoltam mint ami savszigeten is van. Hanem pl spawnerekhez valami 
     bonyolult recept, op szettekhez bonyolult recept, stb.
     Ezt a részt én is szívesen csinálom.    

-Nincs valami megoldás arra, hogy a 34654t54tu654685458347895734985tgurhguihtz54zt74t55 számú storage unitból és barrelből ládákba kerüljenek a cuccok? Többszáz láda is lehet ez akár, és ja. Jó mulatság pakolgatni. (Tudom, dobjuk ki)

-Nem ötlet, inkább csak ajánlás:
Vagy a bolt árakat felvinni, vagy a jobs árakat. (mondjuk sztem senkinek sincs kedve a bolt táblákkal szarakodni, szal max a jobs árakat lehetne növelni.)
-De, mégis van egy ötlet is: Gui-s volt

**-Legjobb ötlet: Slimefun cargo nélkül, köszönöm**

**Comment by IciAlex** [comment]
Elárultad hogy vannak egyedi enchantok OldBlockson

**Comment by MrZero1** [comment]
hajki sk

**Comment by MrZero1** [comment]
Ooo, sk.

**Comment by andris155** [comment]
A járművekhez majd kell csinálnom teljesítménytesztet. Ha megfelelt ezen a teszten, akkor még azt is meg kell csinálnom, hogy a Slimefun hologramokat javító plugin ezeket ne törölje, mivel a játműveknél minden armor stand összeér.

A spawner kiszedés lesz mindenképpen. A fejlesztéses sajnos nem felelt meg a tesztjeinken így olyan sajnos nem lesz.

Lucky Block lesz, de @MrZero1 segítsége nagyon kellene a beállításokhoz.

Az egyedi enchant-okkal a közösség szerint vannak azért bőven problémák. Egyelőre megvárnám vele mik az OldBlock-on a tapasztalatok hosszabb távon ezzel kapcsolatban.

Táskás plugin egyelőre nem lesz. A shulkerbox-ok nagyon jól használhatók erre a célra és azokból messze sokkal kisebb eséllyel is veszik el bármi. Mivel a blokkhoz van társítva, hogy mi van benne.

A Minion-os plugin fizetős. Egyelőre erre most így nem költenék. Később meglátjuk mennyi játékos marad majd hosszabb távon a szerveren, illetve mennyien támogatják a szervert közülük.

A Mythicmobs inkább a későbbiekben kerül be, ha bekerül. Elég bonyolult beállítgatni. Meg úgy emlékszem nem is igazán működik mondjuk az automatikus mob idézés része. poma folyamatos reload-al oldotta meg, de ez nem igazán egy jó megoldás. Sok hiba is van ebben a pluginban. :( Esetleg másképpen pl.: dobhatnak más dolgokat is mobok kerülhetnek be ilyenek. De az egyedi mob dolog elég problémás.

A Levelledmobs első ránézésre jónak tűnik. @MrZero1 neked mi erről a véleményed?

Boss aréna amikor van mobaréna amiben minden konfigurálható? Miért?? :D
A mobarénát kellene beállítani csak valakinek, aki jobban otthon van a Minecraft-os dolgokban a mobokkal kapcsolatban. Arénánként bármi állítható szinte.

Tárgyszállításra én nem tudok jelenleg megoldást ami nem lenne problémás. A hopper az biztosan jó és hozzá meg lehet redstone-al elég sok dolgot építeni. De ha tudtok megoldást ami jól van optimalizálva, akkor szívesen tesztelem.

Az Aurelium Skills-t @MrZero1 az mcMMO helyett rakta be az új OldBlocks szerverre, és szerintem is inkább helyette lenne értelme nem pedig mellé.

A More ores-el az a baj, hogy telerakja fejekkel a világot, amit nem túl szerencsés. Illetve a fejeket nem támogatja az x-ray védelem sajnos.

A timber-es favágás egy mcMMO képesség. Nem lesz erre még egy plugin. :D

A pénzért WorldEdit a staff csapat döntése, hogy lesz-e. Az az egy biztos, hogy **a WorldEdit blokkokat nem védi a kreatív védelem. Így azok kiszedhetők túlélő módban is.**

Az egyedi receptek bekerülhetnek, bár a customcrafting nem egy tökéletes plugin, viszont működik azért általában. :D De itt is kellene valaki aki ezt jól betudja állítani úgy, hogy nem rontja el vele a játékélményt és a pénzrendszert sem. **Lehet benne egyedi tárgyakat is, viszont ezek néha a plugin frissítésével elvesznek és újra be kell állítani.**

A barrel-re sajnos nem tudok megoldást.

A GUI-s boltot nagyon szívesen beállítom, de az árakat a staff csapat tudná csak hozzá. Illetve csak konfiggal módosítható, ami a staffoknak nem előnyös, mert nincs mindenkinek hozzáférése a fájlokhoz. A Jobs árak is konfiggal módosítható. De szintén esetleg a staff csapat tud árakat inkább. Ha szólnak, én szívesen elküldöm a fájlokat nekik és betudják állítani.

**Comment by skrisz0101** [comment]
Ha MOB arénában be lehet állítani azt, hogy saját cuccal menjenek, legyen valami kulcs item/jog különböző arénák belépésére, lehet megadni különleges mobokat, nekem ok.
Nem minigamenek szánnám inkább, hanem játékmenet részének. 
Be lehetne építeni akár az Oldblock-ba is.

More ores helyett esetleg valami más Érces plugin? Nemtom van-e

Pénzért we: ha nem ércet we-ztet az illető, KB értéktelen. De azt a staff meg úgyis tudja nézni hogy mi fér bele és mi nem.

Recepteket én akartam kitalálni leginkább xd
Max kérem King segítségét.

Favágásnál nem az volt a lényeg, Hogy egyben vágja ki a fát, hanem leginkább az élmény, Hogy már az (se)  dögunalmas. Majd lehet küldök egy videót és megértés hogy értem xd

Barrelre valami megoldást magyarázott kernel a we-vel, de már nemtom mi is volt az

**Comment by andris155** [comment]
A továbbiakban MrZeri eldönti, hogy mi legyen majd. Én a nem Slimefun-os szerverre se raknék nagyon sok dolgot már a helyében. Így is rengeteg dolog van már a szerveren.
