### ISSUE TITLE
Pók spawnolás miatti cuccvesztés

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4673]
**Szerver**:OldBlocks

OneBlock skyblockon a blockból spawnol ugye pók, s mivel a póknak 3x3-as terület kell ahhoz, hogy lespawnoljon, így a 3x3-as területen belül levő blockokat ő kiszedi magának, s emiatt ládákból kieshetnek cuccok, amelyek lepotyoghatnak a szigetről.

**Comment by Sizarra** [comment]
Megoldás: Pakold arrébb a ládákat

**Comment by MrZero1** [comment]
Ez nem hiba. Minden mob spawnolásnál hallani egy ellenséges hangot, azt jelenti, jön a mob. Mob spawnoláskor egy pici 'robbanás' lesz, de ez benne van a módban, és nem is akarok ezen változtatni.
Megoldás: Pakolj arrébb. 

Köszönöm a jelentést. :D
