### ISSUE TITLE
Tebex plugin fordítás

### ISSUE THREAD

**Issue by FalconMisery** [TheOld-Crafters/Minecraft-servers#4674]
Minden szerver

Mindössze egy kis esztétikai malőr, a /bolt paranccsal ha haladunk, a Tárgyak --> Minecraft részre, az onnan visszalépésre használatos "gomb" felirata hibás. 

![Esztétika 2](https://user-images.githubusercontent.com/84023001/119176145-03072900-ba6b-11eb-909d-93d84c609b46.png)
![Esztétika 1](https://user-images.githubusercontent.com/84023001/119176150-039fbf80-ba6b-11eb-96b2-1b25ebede8e9.png)

**Comment by MrZero1** [comment]
A /einfo minemarket helyett is lehetne /einfo shop vagy valami.

**Comment by andris155** [comment]
Frissítettem hozzá a fordítást. Majd holnap tölt be. Köszi, hogy írtál.
