### ISSUE TITLE
Kőgenerátor challenge

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4675]
**Szerver**: OldBlocks

Nem lehet teljesíteni a kőgenerátor challenget, ha nem water block, hanem water logged block van lerakva :c

**Comment by andris155** [comment]
Sajnos ez ilyen. De ameddig megcsinálod ezt az egy küldetést szerintem senkinek sem gond lerakni sima egy sima víz blokkot.
