### ISSUE TITLE
OldBlocks rangok, McMMO bónuszok leírása

### ISSUE THREAD

**Issue by FalconMisery** [TheOld-Crafters/Minecraft-servers#4676]
Helló! Az újonnan bekerült OldBlocks-os rangok információi közt lenne probléma. Amennyire tudjuk, nem McMMO már a képességek alapja az új szerveren. Ennek ellenére a leírásban jelen van az McMMO szorzási dolgai és bónuszai. 

![Bolt 1](https://user-images.githubusercontent.com/84023001/119221592-5a9ba800-baf0-11eb-8c12-b6a447cd4a17.png)

![Bolt 2](https://user-images.githubusercontent.com/84023001/119221590-596a7b00-baf0-11eb-82bf-c40cb1fa9e41.png)

**Comment by andris155** [comment]
Javítottam. Köszi.
