### ISSUE TITLE
Anticheat

### ISSUE THREAD

**Issue by Kaszadalom** [TheOld-Crafters/Minecraft-servers#4677]
**Szerver**:Oldblocks --> OneBlock 

 ha futok és a bal kezemben pajzs van és spamelem a jobbkliket akkor visszadobál az anticheat

**Comment by andris155** [comment]
Nekem ezt sajnos nem sikerült reprodukálnom.

**Comment by andris155** [comment]
Esetleg volt rajtad valami effekt? Jó lenne egy videó is erről esetleg.

**Comment by Kaszadalom** [comment]
Nem volt rajtam effekt

András Marczinkó ***@***.***> ezt írta (időpont: 2021. máj.
24., H 21:51):
