### ISSUE TITLE
Survival /warp spawnerek

### ISSUE THREAD

**Issue by lovi-dev** [TheOld-Crafters/Minecraft-servers#4678]
Survival szerveren:
- /warp spawnerek  -nél a beválzó nem vátja be a spawnereket. Csak reinforced cave spidert sikurül beváltani, de abból se mindet fogadja el.
- /warp spawnerek -nél nincs broken spawner beváltó, se megjavítani se lerakni nem lehet.
- reinforced/broken witch spawner hiányzik, nincs a listán.

**Comment by andris155** [comment]
Hát broken spawner-em nincs. Jó lenne ha tudnál esetleg rakni egy ládába nekem és raknál oda mondjuk valami home-t. Azok alapján már megtudok csinálni mindent.

**Comment by andris155** [comment]
Megcsináltam a többi típushoz is a beváltót a spawner-eid alapján. Elvileg most már mindegyiket betudod majd váltani valamelyik beváltóban. Köszi a segítséget.
