### ISSUE TITLE
Survival - SF gépek eladása

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4680]
Melyik gép, milyen áron lehessen eladni?

Én nem tudom, mi mennyit ér, miket lenne érdemes eladni.

**Comment by balazzrthd** [comment]
Andris - "Ki lettek véve a gépek, ergo nincsen értékük."
Ha a főnök azt mondta, az úgy is van. A survival szerver halott, ha milliárdokért lehetne eladni az itemet sem fog semmit érni. A gazdaság egy kuka

**Comment by MrZero1** [comment]
Teljes resit meg senki nem akar.

**Comment by balazzrthd** [comment]
> Teljes resit meg senki nem akar

Ha még lenne is, sem lenne olyan player, aki fel fog oda járni.

**Comment by BagdiSandor** [comment]
Ha  valaki OCD-ért vett sfes dolgokat nem kérhet kupont az új shopban?

**Comment by andris155** [comment]
Hát ha el lehet majd adni játékpénzért, akkor nem.

**Comment by MrZero1** [comment]
Akkor ez nem megvalósítható?
