### ISSUE TITLE
Old és Spawnegg ládakulcs boltba

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4682]
**Szerver**: OldBlocks

Ugyanolyan áron, mint a többi szerveren, Old és Spawnegg (itt nem Spawner a neve) ládakulcs, csomagban is akár. :D

**Comment by MrZero1** [comment]
Shopkeepers tojás is.

**Comment by andris155** [comment]
Bekerült:
https://bolt.oldcrafters.net/category/kulcsokoldblocks
https://bolt.oldcrafters.net/category/targyakoldblocks
