### ISSUE TITLE
Oneblock challenges rosszul van kiírva

### ISSUE THREAD

**Issue by Kaszadalom** [TheOld-Crafters/Minecraft-servers#4684]
**Szerver**:OneBlock

A /obc-n a Kezdőnél a utolsó 4 (kőtégla készítő, vágott kőtégla készítő, repedezett kőtégla készítő, csiszolt kő készítő) A jutalom mind a 4nél rosszul van leírva (Nem azt kapjuk a mi oda van írva).
![Képernyőkép 2021-05-24 090115](https://user-images.githubusercontent.com/84626858/119309454-9e1c2080-bc6e-11eb-87af-ce0af56f3301.png)

**Comment by sweetan1** [comment]
Mit kaptatok?

**Comment by KingDeadZ** [comment]
gondolom az a probléma vele, hogy nem kőtégla, és sima tégla van odaírva, átírtam az összesnél

**Comment by andris155** [comment]
Javítottam a savszigeten is. Köszi a jelentést.
