### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Gabello123** [TheOld-Crafters/Minecraft-servers#4686]
Oldblocks: One Block
ráugrasz egy megkapált földre akkor ugyan ott maradsz de a föld egész block lesz, így a föld blockba bele bugolsz. ha nincs alatta block akkor át is esel rajta

**Comment by andris155** [comment]
Nekem ezt nem sikerült reprodukálni. Esetleg volt rajtad valami effekt? Jó lenne egy videó is erről esetleg.

**Comment by Gabello123** [comment]
Tesztelgetek de bazsaaa is ki esett sweet láttára

**Comment by KingDeadZ** [comment]
https://www.youtube.com/watch?v=bSz-xK7zJcg kicsit laggos a videó, de felvettem

**Comment by andris155** [comment]
Érdekes.

**Comment by andris155** [comment]
Holnap frissül a NoCheatPlus. A jelenlegi verzióval sikerült ezt reprodukálnom. Az újjal nem. Tehát ezt valószínűleg javítani fogja. Köszi a jelentést.
