### ISSUE TITLE
Survival /warp ládák

### ISSUE THREAD

**Issue by lovi-dev** [TheOld-Crafters/Minecraft-servers#4687]
/warp ládák a legendás, a varázslatos és a lucyblock láda is ad Slimefun kulcsot és még a Slimefun láda is még bent van. Paradoxon.

**Comment by skrisz0101** [comment]
Ez csak egyet jelenthet.
Holnap lesz sf

**Comment by andris155** [comment]
Frissítettem a ládákat. Köszi, hogy írtál.
