### ISSUE TITLE
OneBlock átesés

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4688]
**Szerver**: Oldblocks 

A kezdők sokszor írják, hogy átesnek a blokkon, ha kiütik. 
Ezt lehetne úgy megoldani, hogy egy bedrockot tenni alá

**Comment by mangoshell** [comment]
Ha esetleg ez a bedrockos ötlet nem tetszik nektek, bár jó ötlet. Akkor szerintem lehete +1 blokkot adni kezdéskor és egy könyvet amiben le van írva hogy tegye le azt a blokkot és ne álljon a kiütősre. De nekem tetszik skirály ötlete is

**Comment by andris155** [comment]
Holnap frissül a NoCheatPlus, ami ezt lehet megoldja. Ha holnap reggel, vagy utána is tapasztaltok ilyet, akkor kérlek nyissatok egy új jelentést és akkor rakok bedrock-ot a blokk alá. A jelentést köszi.
