### ISSUE TITLE
Több challenge

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4689]
OldBlocks-->

1.Alvás!
Készíts 1 ágyat!
Jutalom: 16 fonál.

2.Farmer.
Készíts egy kőkapát, és 3 komposztálót!
Jutalom: 10 búza mag.

3. Lelombozó.
Szerezz 32-32 levélblockot, minden fafajtából!
Jutalom:  unbreaking 5-ös olló.

4. Álmatlanság.
Legyen a közeledben egy fantom.
Jutalom: 1 fantom spawn egg.

5.Mohás kő...
Craftolj 32 mohás zúzottkövet és 32 mohás kőtéglát.
Jutalom: lávásvödör.

6.Villamos.
Craftolj minden sínből 16 darabot!
Jutalom: 1 Csille, 1 vasblock.

7.Termékszállítás.
Craftolj  minden fajta csilléből 1-et.
Jutalom: 3 szénblock.

8.Piglinek VS Falusiak.
Legyen a közeledbe 2 falusi és 2 piglin!
Jutalom: 1 arany block, 1 smaragd block.

9. Nyári kiruccanás.
Építs egy tavat (20 vízblock), és legyen nálad egy horgászblock!
Jutalom: 20 perces Luck effekt!

10.Állásinterjú.
Készíts minden munkaasztalbol 1-et!
Jutalom:  5 Smaragdérc, Hero of the village effekt 10 perc.

11.Fejetlenség!
Szerezz be egy Creeper, Zombi, Skeleton, Wither Skeleton fejet!
Jutalom: Sharp. 6-os Dia kard.

12.Fekete gyémánt!
Tegyél le egy Netherit blockot.
Jutalom: 1 Netherit rúd.

13.Örök Barátok!
Legyen veled 2 player!
Jutalom:Pipacs (Név: Örök barátok!)

14.NOOB!!!
Szerezz 8 bohóchalt, és 16 szárazkórót!
Jutalom: 20 föld.

15.Ez egy nagy küldetés.
Legyen a közeledben egy Giant.
Jutalom: Névcédula (Neve: &6&lEz egy HATALMAS név!)

16.Vég?
Legyen a közeledbe 2 Endermite, 2 Enderman, 1 Shulker!
Jutalom: Dragon Egg, Dragon head.

17.Varázsló hatalom!
Legyen nálad minden varázspálca!
Jutalom:Unbreaking 7, Protection 7, Enchantkönyv. (Utánna már csak Ub.5, Prot.5 könyvet adna)

18.Az idő múlása!
Legyen nálad egy ép, repedezett és törött üllő!
Jutalom: 9 Vasblock!

19.Üzletember.
Legyen a közeledbe egy Wardering Trader!
Jutalom: 2 Wandering Llama Spawn Egg, 2 Llama Spawn Egg!

————————————————————————————————
Lehetséges, hogy ezek a küldik közül már van bent a játékba (nem tusom, Stage 3-nál járok).
Ha valakinek van még ötlete, írja meg kommentbe!

**Comment by skrisz0101** [comment]
mivel kb king és én vagyunk a legjobban képben a küldikkel, írok én hogy melyikhez van már hasonló küldi, stb.

1:  sztem túl egyszerű
2:  nem rossz, esetleg mehetne az 1. könyvbe
3:  nem rossz, esetleg mehetne a 3. könyvbe
4:  nem rossz, de a fantom tojással semmire se mennek kb. Jutalom lehetne akár éjjellátás bájtal + a szokásos coin (3. könyv)
5:  van már indás/kőtéglás/mohás köves küldi maugli vagy tarzan névvel asszem a 2. könyvben
6:  van már sines küldi asszem a 4. könyvben
7: sztem túl egyszerű
8: van már piglinre épülő küldi, sztem nem szükséges ez (Piglin kereskedelem néven asszem a 4. könyvben)
9: nem látom nagyon hasznát, se értelmét :(
10: nekem is volt ilyen ötletem, nemtom hogy végül be lett-e téve vagy inkább hanyagoltam xd
11: nem rossz, mehetne akár a 4. könyvbe (nemtom milyen eséllyel adnak fejet, azért azt meg kéne nézni)
12: hát ez ilyen semilyen
13: xddddd
14: bohóchalra épülő küldi már van asszem, kórót meg sztem nem is lehet ,,szerezni" (?)
15: oszt honnan lehet szerezni giantot, pandora boxból lehet? Ha lehet, tőlem ok, esetleg 5. könyvben
16: nemtom hogy shulkert lehet-e szerezni oneblockon.
17: ez tetszik, 5. könyvbe mehetne
18: hát, nem látom sok értelmét xd (keveset se)
19: ez tetszik, de ez inkább csak a szerencsén múlik h hozzád spawnol-e. Max 5. könyvbe lenne jó

Asszem most is ad minden küldi coint, szal jutalomba hozzá lehetne adni

**Comment by skrisz0101** [comment]
Amúgy akkor már az én ötleteim is ideírom, legyen egyben

1: Küldetés neve: Cserekereskedő.
Feladat: Craftolj 2 shopkreeper tojást.
Jutalom: 2 harang, 2 falusi. és 4 coin
4. küldetéskönyv

2: Küldetés neve: Üvegház készítő
Feladat: Készíts 1 tölcsért, 1 vasajtót, 64 üveget és 64 csontlisztet.
Már minden megvan, hogy üvegházat készíts!
Jutalom: 32 vasrúd és 2 stray tojás és 4 coin
2. küldetéskönyv

2: Küldetés neve: Pandora szelencéje
Feladat: Készíts 8 pandora's boxot
(Ne vegye el az ehhez kellő cuccokat)
Jutalom: 16 aranyrúd, 16 vasrúd és 2 pandora's box
3. küldetéskönyv

3: Küldetés neve: A láthatatlan... eszközkeret?
Feladat: Készíts 64 invisible Item Framet.
(Segítség: /teleportok -> egyéb dolgok)
Jutalom: 4 coin és 8 gyémánt
4. küldetéskönyv

Hirtelen ennyi jutott eszem

**Comment by DiaGamer321** [comment]
Az 1. kezdő küldetés lenne, azért adna csak 16 fonalat.
5. Csak indás van, de mohástégla nincs. 
 8. Nincs olyan küldi, ahol a piglint kéri, mint mob. 
9. Hamár valaki megcsinálja azt, akkor könnyebben megcsinálná a halászós küldit.
15. Igen, spawnol pandorax box-bol.

**Comment by skrisz0101** [comment]
1: bárány csak OneBlockon spawnol a semmiből.
De amúgy maga a küldi túl egyszerű xd
5: nézd meg a Tarzan és maugli küldit is
8: ok tőlem bekerülhet 
9: sztem akkor is felesleges :(
15: akk kafa
