### ISSUE TITLE
küldi, action bar

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4691]
**Szerver**: oldblocks

amikor a /challenges-ből valami küldi épp folyamatban van (pl a heti vagy havi küldimnél most gránitot kell szednem), akkor az action barban kiírja ha kiütök egy granitot (pl 5/64) 
A szöveg elején kiírja azt, h [ACTION BAR]

**Comment by andris155** [comment]
Elvileg most már jól kell írnia. Köszi a jelentést.
