### ISSUE TITLE
skyblock nether - bekapcsolt end portál

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4693]
**Szerver**: oldblocks

Skyblockon (és gondolom caveblockon is) be van kapcsolva az end portál (le van téve minden enderszem) a portálra. 
Abban úgy nincs semmi kihívás :c

**Comment by andris155** [comment]
Legyen úgy, hogy nincs bekapcsolva és nincsenek benne az ender szemek?

**Comment by skrisz0101** [comment]
szerintem úgy van értelme, így egyből át lehet menni az endbe, ha eljutottál a netherbe
Esetleg bele lehetne rakni 1-2-t

**Comment by andris155** [comment]
![2021-05-29_19 55 32](https://user-images.githubusercontent.com/8324198/120080162-dfba2a80-c0b7-11eb-8721-a8386606ce22.png)
4 db. nincs benne alapból pedig.

**Comment by andris155** [comment]
2-őt hagytam benne végül akkor így.

**Comment by andris155** [comment]
Holnaptól már, amit legenerál abban már 2 ender szemnek kell csak majd lennie.
