### ISSUE TITLE
/voteshop spawnon

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4694]
**Szerver**: OldBlocks

Egy közeli ismerősöm (nem én) vásárolt /voteshop-ból kulcsot és elkezdte nyitni spawnon a ládákat. Spawnon nem nagyon lehet azzal mit kezdeni, mivel nem lehet átvinni másik világba

Szal: Tiltani kéne a vásárlást onnan ha a spawnon vagyunk, hátha valaki elkövet mégegy ilyen balesetet :c

**Comment by MrZero1** [comment]
Milyen paranccsal sikerült venni voteshop-ból?

**Comment by andris155** [comment]
Már a kezdőhelyen nem megy ez a parancs. De jelenleg nincs bent a szavazás.
