### ISSUE TITLE
ocsmány team chat

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4695]
**Szerver**: oldblocks

nagyon ocsmány a team chat /is team chat

**Comment by MrZero1** [comment]
Kép?

**Comment by andris155** [comment]
és milyen legyen?

**Comment by skrisz0101** [comment]
ha lenet benne rgb, akkor sztem a [Team] lehetne valami átmenetes zöld, maga a név maradhatna ugyanaz mint a nick, az írás meg sztem &a

**Comment by KingDeadZ** [comment]
&#69ff00[&#56e101T&#43c401e&#2fa602a&#1c8902m&#096b03] 
![image](https://user-images.githubusercontent.com/38157910/119929953-cc577400-bf7e-11eb-8837-c0fdbb23dbf6.png)

Ez talán lehetne a [Team]hoz, ha lehet benne használni HEX színkódokat, ha van rá lehetőség akkor a nick szerintem is maradhatna az, ami alapból is.

**Comment by andris155** [comment]
Hex színkódokat ez sajnos nem támogat.

**Comment by andris155** [comment]
Ezt egyáltalán mi és hol írja?

**Comment by andris155** [comment]
Ezt egyáltalán hol és mi írja amúgy? Mert a BetterTeams chat nem igazán így néz ki.

**Comment by andris155** [comment]
Hex színkódot sajnos nem támogat, de átszíneztem olyan színűre, amilyet írtatok. Köszi az ötletet.
