### ISSUE TITLE
Csere küldetések

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4696]
**Szerver**: oldblocks

küldetéskönyvben a legfelső 4 küldit 1000 alkalommal lehet teljesíteni.
Szerintem azt lehetne kicsit könnyíteni, hogy jobban megérje. pl 64 kaktuszért 4 homok, hát, ja
Ötlet: Minden blokk amit ad, legyen 24 a 4 helyett

JAVÍTÁS: nem 4et ad most, hanem 1et xdd
64 kaktusz 1 homokért pl

**Comment by MrZero1** [comment]
Szerintem az ilyen sokszor elvégezhető küldetéseknél ilyen magas jutalom elég OP. Az első lehet magasabb, de minden további jutalmat nem növelnék meg.

**Comment by skrisz0101** [comment]
64 kaktusz 1 homokért op? Xd

**Comment by MrZero1** [comment]
Jó, a javítás előtt írtam, ne nézz hülyének kérlek.

**Comment by KingDeadZ** [comment]
> Szerintem az ilyen sokszor elvégezhető küldetéseknél ilyen magas jutalom elég OP. Az első lehet magasabb, de minden további jutalmat nem növelnék meg.

Mennyire rakjam át a legelső elvégzésnél?

**Comment by MrZero1** [comment]
64 kaktusz - 32 homok, a többinél meg 64 kaktusz 10 homok (?)

**Comment by skrisz0101** [comment]
Tegnap javítottam :(

**Comment by KingDeadZ** [comment]
> 64 kaktusz - 32 homok, a többinél meg 64 kaktusz 10 homok (?)

Átraktam, szerintem így jó lesz az embereknek is :D
