### ISSUE TITLE
Oldblocks biome hiba

### ISSUE THREAD

**Issue by szofogado** [TheOld-Crafters/Minecraft-servers#4698]
Szerver: oldblocks 

Ha beállítasz egy chunkot a /ob biome-al nether típusúra, másnapra vissza változik az eredeti biomera. (szerintem szerver restart után) (nem teszteltem a másik két játékmódon, se a többi biome-al)

**Comment by MrZero1** [comment]
Esetleg más biommal is megnéznéd? 😃

**Comment by szofogado** [comment]
Amint haza értem, persze. De mivel egy szerver reset után történt, ezért csak holnap tudom elküldeni az eredményt

**Comment by andris155** [comment]
Fázisonként megvannak adva biome-k is. Gondolom ezek felülírják a manuálisan beállított biome-t. Sőt mondhatni így csalás is hozzá valamilyen szinten a biome váltás.

**Comment by MrZero1** [comment]
A Pokol biomot én raktam be, hogy tudjon működni a fejlesztett pokol generátor. De akkor ez így nem jó 🙁

**Comment by szofogado** [comment]
Most néztem meg, még régebben a tavacskámat átállítottam óceánra, és az megmaradt, úgy hogy a + biome-al lesz a gond.

**Comment by MrZero1** [comment]
Akkor valószínűleg az lesz a baj. 😪

**Comment by MrZero1** [comment]
Kivettem a pokol biomot.

**Comment by szofogado** [comment]
Elfelejtettem írni, de én már nem tapasztaltam ezt a hibát.

**Comment by MrZero1** [comment]
Jó lett volna szólni, és lezárni ezt... majd holnap visszarakom a biomot.

**Comment by andris155** [comment]
Benne van ez a biome már, ahogy láttam.
