### ISSUE TITLE
team prefix

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4700]
**Szerver**: oldblocks

sztem a 3. prefix oda már nem kéne (nem illik oda + csúnya is)
![2021-05-27_19 39 06](https://user-images.githubusercontent.com/29951969/119872035-5540c200-bf23-11eb-8e72-c48ec5ad588b.png)

**Comment by andris155** [comment]
Kikapcsoltam ezt a funkciót benne.
