### ISSUE TITLE
viággyűjtő küldi - kék orchidea

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4702]
**Szerver**: oldblocks

elvileg már csak az a virág kell nekem a küldihez.
Sehonnan se tudok szülni olyan virágot. 
Üvegház + mocsár bioma + csontporozás nem ad
Sziget mocsár biom + csontporozás se ad.

Ha más ötlet nincs a szerzésre, akk sztem ki lehetne venni azt a virágot a küldikből

**Comment by KingDeadZ** [comment]
./is,cb v ob biomes -> mocsár biom, nekem jött csomó :)
