### ISSUE TITLE
nyúl tojás küldi

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4703]
**Szerver**: oldblocks

valamelyik küldihez a 4. könyvben kell nyúl hús, de nyulat nem lehet szerezni.
Küldi ötlet:
Küldetés neve: Nyúl csapda
Ferladat: Készíts 4 botlóhorgot, 32 répát és 16 aranyrépát
Jutalom: 2 nyúl tojás és 4 coin
3. könyvbe mehetne

**Comment by MrZero1** [comment]
@KingDeadZ

**Comment by MrZero1** [comment]
Köszi Sk, bekerült. (Köszi King!)
