### ISSUE TITLE
E-mail címes megerősítés kelljen a regisztrációhoz

### ISSUE THREAD

**Issue by andris155** [TheOld-Crafters/Minecraft-servers#4706]
**Szerver**: Az összes

Szerintem ezzel egyetlen bot sem tudna többet regisztrálni. @MrZero1 beállítsam?

**Comment by MrZero1** [comment]
Megpróbálhatjuk. Legalább aki csak trollkodni akar feljönni, az hátha nem regisztrál csak azért, minden esetben.

**Comment by skrisz0101** [comment]
Amúgy sok helyen láttam olyan botvédelmet, hogy minden belépésnél volt a képernyőn 5 nyíl item
Egyik 23db másik 45db harmadik 57db
És csak akkor engedett be, ha a 23db-re nyomtál pl
Természetesen minden belépésnél más számot generált és más számot kért

**Comment by andris155** [comment]
Sosem láttam még sehol ilyen plugint. Ha küldenél róla linket az nagy segítség lenne.

**Comment by MrZero1** [comment]
Egy két szerveren láttam ilyet, majd nézelődök, melyik lehet az.
