### ISSUE TITLE
OldBlocks sziget lezárás

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4708]
**Szerver**: OldBlocks

Ob szeróról kerüljön ki a sziget lezárása lehetőség. Ha le van zárva a sziget staffok nem tudnak ellenőrizni rendesen. Ha valaki zavar azt ki tudják tiltani /is bannal is, azzal meg staffot ugye nem lehet.
![image](https://user-images.githubusercontent.com/69635280/120123482-67cf2b80-c1af-11eb-9e4f-b3425d7bcb8a.png)
![image](https://user-images.githubusercontent.com/69635280/120123490-71589380-c1af-11eb-80cf-1ecd88de527d.png)

**Comment by andris155** [comment]
Itt megint a bypass jog hiányzik mint előtte a tiltásnál hiányzott. Majd megnézem itt mi a bypass jog és megadom a staffoknak.

**Comment by andris155** [comment]
Adtam hozzá bypass jogot a staffoknak. Most már elvileg betudsz menni a lezárt szigetre is.
