### ISSUE TITLE
Hiba!

### ISSUE THREAD

**Issue by Goldie2000** [TheOld-Crafters/Minecraft-servers#4710]
**Sziasztok!**

_Észre vettem egy hibát a_ https://www.oldcrafters.net/szavazas/ _oldalon._

Azt hogy egy oldalból **2-van** feltűntettve.

![asd](https://user-images.githubusercontent.com/60890921/121411423-e7a18680-c963-11eb-9543-2608f5b20d57.png)

By: **_Goldie2000_**

**Comment by andris155** [comment]
Javítottam. Köszi.
