### ISSUE TITLE
Cave Block fejlesztés.

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4714]
A CaveBlock első hallásra egy izgalmas játékmódnak hallatszik, de amikor tapasztaljuk a megvalósítást, kicsit elszomorít. Egy hatalmas kő kockába spawnolunk, ahol semmi más sincs, mint kő-kő-kőőő!
Sokkal izgalmasabb lenne, ha lennének ércek is benne, bányajáratok, stb.
Pl: Minden player bányájába lenne 128 szén, 64 vas, 64 réz, 32 arany, 16 lapis, 16 redstone és 8 gyémánt érc.

Lehetnének dungeonok is, mint pl egy egyedien kialakított mineshaft, ametiszt geoda, egy spawneres dungeon (Egy zombi spawner), egy csepkő barlang, mohás barlang, egy homokos barlang.

Tudtommal ez egy schematic modellel van megoldva, ezért csak simán átalakítani kellene. 

Ha valakinek van még ötlete, írja le.

**Comment by Ziredus** [comment]
Anno kiprobáltam a CaveBlockot, én találtam szenet is a kövön kivül :D

**Comment by DiaGamer321** [comment]
Ritka mint a fehér holló.

**Comment by DiaGamer321** [comment]
De ott van az a 200×200-as terület, több dolgot lehetne rakni oda

**Comment by MrZero1** [comment]
Olyan sokat azért nem 😃 Az 1.17-es dolgokkal lehet majd jó dolgokat berakni, esetleg lehetne többféle barlang is. 😃

**Comment by SurvivorTheReal** [comment]
Az lenne a legjobb ha úgy generálná a barlangrendszert mintha vanilla minecraft lenne (nyilván vanilla mcről beszélünk de ügye az egész világ egy nagy kődarab). Ezen kívül lehetne nagyobb vagy barlangszinttel növelhető a barlang mérete.
