### ISSUE TITLE
Old blocks enchantok

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4715]
Az Old blockson az újfajta enchantok nem működnek az 1.17 óta. Pl Bunny hop vagy Sonic.

**Comment by MrZero1** [comment]
Ha a Crazy enchants működik 1.17-en, lehet érdemes lenne lecserélni arra

**Comment by andris155** [comment]
A Golden pluginok sajnos nem frissültek még 1.17-re. NMS-t használ, amit elég hardcore az 1.17-ben használni már pont ezért is, hogy ne használják ezt feleslegesen és helytelenül a fejlesztők.

**Comment by andris155** [comment]
Itt tudod követni a frissítés állapotát: https://github.com/TheOld-Crafters/Minecraft-servers/issues/4711
A jelentést köszi.
