### ISSUE TITLE
OldBlocks ötletek

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4716]
**Szerver**: OB 1.17

Sok ötletem van az új verzióval kapcsolatban.

- [x] Mélypalás ércek, rézérc a magic ércgenerátorba. Külön réz kategória (a vöröskő, lapis stb. mintájára.)

- [x] Új kőféle blokkok az ércgenerátorba.

- [x] End biom Oneblockra (/ob biomes gui-ba)
 
- [x] Pokol biom kivétele a biomok közül (/sb biomes, /cb biomes, itt van külön pokol világ)

- [ ] Caveblockra különböző kezdőbányák (#4714)

- [x] Goldenenchants helyett Crazyenchants

- [ ] Új küldetések 1.17-es nyereményekért

- [x] Savsziget mód véglegesítés

- [x] Napi láda (Nexus) mind a 4 játékban. 

Ha van valakinek ötlete, kommentben várom, és berakom ide a listába.

**Comment by SurvivorTheReal** [comment]
Esetleg spawner kiszedés netherite silk touchos csákival?

**Comment by andris155** [comment]
Beraktam a GeldenEnchants helyett a CrazyEnchantments plugint.

**Comment by MrZero1** [comment]
Jó, hogy csak így beraktad, de a pénz helyett coin kéne.. :D

**Comment by andris155** [comment]
Ha nincs benne olyan opció akkor megcsinálom majd. De nem mostanában lesz erre időm.

**Comment by MrZero1** [comment]
Majd ha lesz felesleges időm erre, majd csinálok 1-2 fajta schematicot a caveblock-hoz. Most erre nincs sajnos kapacitásom. Más staff meg nem foglalkozott vele.
