### ISSUE TITLE
No creative védelem

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4717]
Szerver: összes
A GM1-ben letett dripstone ha nő, akkor a növesztett részét kiütve megkapjuk a dripstone-ot.
A GM1-ben letett moha block csontliszttel való terjesztése után a spawnolt mohákat, moha szönyegeket, azáliákat kiütve megkapjuk.
A GM1-ben letett fényszeder csontliszttel való terjesztése után megkapjuk a fényszedert.
A GM1-ben letett fénylő zuzmó csontliszttel való terjesztése, majd kiütése megadja a zuzmót
A GM1-ben lerakott amethyst blockon növő amethyst geódák gyengéd érintéssel kiütve megadja az amethystet.
Ellenörizve Real_Tomi és Ziredus által.
Githubon való megjelenést jóváhagyta: OliverHahn

**Comment by andris155** [comment]
Ezeket sajnos egyelőre le kell tiltanom kreatívban, de ha javítja a fejlesztő ezeket, akkor mindegyik engedélyezve lesz kreatívban.

**Comment by andris155** [comment]
Kérlek írj Discord-on, hogy átadhassam a jelentésért a jutalmat.
