### ISSUE TITLE
Oldblocks csillés bug(?)

### ISSUE THREAD

**Issue by SurvivorTheReal** [TheOld-Crafters/Minecraft-servers#4718]
**Szerver**:Oldblocks

Ha csilléből, úgy hogy gyorsan mész a csillével, és ki akarsz ütni blokkot (esetemben szimplán csak cukornád) akkor valamelyik plugin nem engedi kiütni.

**Comment by SurvivorTheReal** [comment]
Lesz ebből valami vagy csináljak full automata nádfarmot?

**Comment by andris155** [comment]
Kérlek nyiss egy új jelentést videóval együtt, hogy hogyan nem működik pontosan a kiütés illetve, hogy pontosan mivel akarod kiütni a blokkot.

**Comment by andris155** [comment]
Persze csak akkor, ha még van ilyen hiba.
