### ISSUE TITLE
Az 1.17 csodája!

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4719]
Survival -->

Levédésen lehet kiszedni Glow Item Frame-ből itemet, és lelehet szüretelni a Glow Berries-t.

**Comment by andris155** [comment]
A Plotsqured-hez nem hajlandó a Slimefun támogatást írni. Nem valószínű, hogy mostanában lesz védett ott ez. Talán valamikor a távoli jövőben. A WG védésen szerintem védett. A Griefprevention-nak majd utána nézek.

**Comment by andris155** [comment]
A Griefprevention védésen már védettnek kell lennie.

**Comment by andris155** [comment]
Az új Griefprevention-t sem támogatja a Slimefun így ezeken a védéseken is valamikor a távoli messzi jövőben lesznek csak védettek ezek.

**Comment by andris155** [comment]
Griefprevention levédésen már védettek az 1.17-es dolgok.

**Comment by andris155** [comment]
Már védettek mindenhol az 1.17-es dolgok.
