### ISSUE TITLE
Fényszeder arathatósága

### ISSUE THREAD

**Issue by szofogado** [TheOld-Crafters/Minecraft-servers#4720]
Szerver: Oldblock

Oldblockon, azon is belül caveblockon a spawnon lévő Fénynövénynek lelehet szedni a termését, de a block nem frissül, így ezt akár farmolni is lehet.

A többi szerveren nem teszteltem!

Feri12 játékosvolt, aki felhívta a tudomásomat erre a hibára. (ha jár jutalom, kérem hozzá jutassák el)

Csatolok képeket is.

![image](https://user-images.githubusercontent.com/52892955/124283917-be33df00-db4c-11eb-82f1-7ac485f24a1a.png)
![image](https://user-images.githubusercontent.com/52892955/124284070-e6bbd900-db4c-11eb-8168-e21bfcda1990.png)
![image](https://user-images.githubusercontent.com/52892955/124284173-03581100-db4d-11eb-8025-a8e52ea04b5b.png)

**Comment by andris155** [comment]
Javítottam és értesítettem az adminokat is megoldásról. Köszi a jelentést. @MrZero1 eldönti majd, hogy ad-e érte jutalmat.
