### ISSUE TITLE
Old block extra enchantments javaslat

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4721]
Javasolnám, hogy a Golden enchantments kerüljön vissza néhány napra az old blocksra, így mindenki kimentheti a silk chestes ládákban tárolt tárgyait. A Crazy enchantments pedig még úgy sem megy (ill nincs engedélyezve).

**Comment by MrZero1** [comment]
Visszakerül OldBlocks-ra a Golden enchant. A Crazyenchantments pedig az új szerverre kerül be.

**Comment by andris155** [comment]
A ládák tartalma úgy is elveszik, ha bent van a plugin. Egyelőre erre nincs megoldás.

**Comment by MrZero1** [comment]
Lehet érdemes lenne kivenni a Silkchest enchantot

**Comment by andris155** [comment]
Talán az 1.17-ben felvett ládákkal jó. De a régiekkel lehet nem. Le kell tesztelni majd.

**Comment by Icecroft** [comment]
Nem veszett el a ládák tartalma, pedig 1.17 előtt ütöttem ki őket.
Köszi Zero, hogy visszakerült, pakolom is ki a ládákat :)

**Comment by andris155** [comment]
Igazából miattam került vissza, mert nincs időm átírni a másikat olyanra, ami kellene arra a szerverre.
