### ISSUE TITLE
Szimbólum bugok

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4724]
![image](https://user-images.githubusercontent.com/29151964/125132057-1007d680-e104-11eb-857b-4e8b42e6370c.png)

**Comment by Laci444** [comment]
Hupsz most jut eszembe survin nem néztem, hogy mi a helyzet. Ez OB-n van

**Comment by andris155** [comment]
<img width="485" alt="Screenshot 2021-07-09 223611" src="https://user-images.githubusercontent.com/8324198/125133372-1434f380-e106-11eb-898b-72b5425e126f.png">
Nálam jól vannak. Nálad lesz a probléma valamivel. Ha használ forráscsomagot, akkor szerintem az okozhatja a hibát.
