### ISSUE TITLE
Több Challenge 2

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4725]
OldBlocks--->

Küldetések az új 1.17-es cuccokkal, és mások...

1. Szint:

"Váratlan vendég"
Találkozz egy vándor kereskedővel, és annak lámáival!
Jutalom: 3 smaragd, 3 coin!

2. Szint:

"Bazalt generátor"
Készíts egy bazalt generátort!
Jutalom: 8 lapis, 3 coin.

"Bazalt gyüjtő"
Bányássz 2×64 bazaltot és craftolj 2×64 simított bazaltot!
Jutalom: 16 magma block (Megismételhető, ezután 8-át adna), 3 coin.

"Parkour mester"
Szerezz 64 Big Drip leaf-t! (Vándorkereskedő árul)
Jutalom: 4 moha, 4 coin!

3. Szint:

"Pokoli bányász"
Bányássz 2×64 blackstone-t!
Jutalom: 2 hoglin spawn egg, 3 coin.

"Bástyaépítő"
Craftolj le mindent, minden fajta blackstone-bol 8-át!
Jutalom: 1 Pigstep, 6 coin!

"Pokoli farm"
Legyen a közeledbe 4 hoglin, 2 strider!
Jutalom: Piglin orr minta, 4 coin.

"Geoda felfedező"
Legyen nálad 64 tuff és 64 kalcit block!
Jutalom: 16 ametiszt szilánk (ismétléskor 4), 4 coin.

"Fagyasztó"
Legyen közeledbe 2 stray és 2 porhó block!
Jutalom: 8 lapis érc, 4 coin!

4. Szint:

"Réz???"
Bányássz 32 réz rudat! (Ne vegye el!)
Jutalom: 8 réz érc, 3 coin!

""Az idő múlása..."
Legyen közeledben 2-2 Normal,  Exposed, Withered, Oxidized Copper block!
Jutalom 16 réz érc, 1-1 csepkő, csepkő block, 6 coin.

"Az idő megállt..."
Legyen nálad 4 viaszos réz block!
Jutalom: 4 fénylő zuzmó, 6 coin!

"Elektromos feszültség"
Legyen közeledbe egy charged creeper, és 4 villámhárító.
Jutalom: 32 redstone érc, 6 coin.

"Cseppkő bányássz"
Legyen nálad 32 cseppkő!
Jutalom: 8 gyémánt érc,  6 coin.

"Azálea kertész"
Legyen nálad 8 azálea bokor, 8 virágzó azálea bokor.
Jutalom: 8 világító bogyó, 4 coin.

"A kis gyökér...."
Szerezz 32 gyökeret és 16 gyökeres földet!
Jutalom: 20 redstone érc, 4 coin!

5. Szint

"Azála kertész 2"
Legyen nálad 64 azálea levél, 64 virágzó azálea levél.
Jutalom: 1 rózsaszín virág (elfelejtettem a névét xd), 3 coin (ismételhető)

"Fény az éjszakában!"
Szerezz 2×64 világító bogyót!
Jutalom: 1 kecske spawn egg,  3 coin! (Ismételhető)

"Fény a tengerben!"
Legyen közeledbe 4 világító tintahal!
Jutalom: 2 axolotl spawn egg, 4 coin!

"Ametiszt bányász"
Szerezz 64 ametiszt blockot!
Jutalom: 2 budding amethyst (ismétléskor 1), 6 coin!

**Comment by MrZero1** [comment]
@KingDeadZ ?
