### ISSUE TITLE
Slime-Fun finomhangolás

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4728]
2021.05.18.-án discord "hírek" rovatában Andris jelentette be az alábbit:
- [Túlélő és savsziget] Letiltásra került, néhány Slimefun tárgy, ami úgy töltött be chunk-okat, hogy a játékos nincsen ott. (Tesseract, Wireless Item Output, Wireless Item Input, Wireless Energy Point)

Jelenleg azonban ezek az itemek elérhetőek az SF-Guide-ban, szabadon craftolhatóak. Mivel bejelentés azzal kapcsolatban nemtörtént, hogy ismét elérhetőek, feltételezem a plugin visszakerülésekor kerültek vissza véletlenül.

**Comment by andris155** [comment]
A jelenlegi játékosszám mellett szerintem ez nem probléma és nem fog laggot sem okozni.

**Comment by andris155** [comment]
Az észrevételt azért köszi.

**Comment by Ziredus** [comment]
Ez esetben én is használatba venném a cuccokat :)
