### ISSUE TITLE
Oldblocks táblahiba

### ISSUE THREAD

**Issue by delibotond** [TheOld-Crafters/Minecraft-servers#4729]
nincsenek a custom enchantoknál kiirva, hogy mire jok ezek az enchantok

**Comment by MrZero1** [comment]
Időközben módosult a plugin, a /eenchants list paranccsal meglehet nézni az összes extra enchantot, illetve ott van rövid leírás és más hasznos infók. A teleporthelyen azért nagyjából kitábláztam ezt. Köszi a jelentést!
