### ISSUE TITLE
Slimefun Jetpack fall dmg.

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4730]
SF Survival

Ha felrepülök bizonyos magasságba, majd leereszkedek, és gyakorlatilag Electric Jetpack IV-vel lebegek 2 blockra a földtől, mikor földet érek a fall dmg-be meghalok. 2 nappal ezelőtt még nem történt ilyen, bátran lehetett használni a jetpacket, az általa biztosított löket utáni zuhanásból származó fall dmg-t (már ha volt) kapta csak meg az ember, függetlenül attól, hogy milyen magasról indult a löket előtt, vagy milyen hosszú idő után esett le.

**Comment by andris155** [comment]
Javítottam ezt a hibát. Köszi a jelentést.
