### ISSUE TITLE
Hackshield érzékenység

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4731]
Az elmúlt pár napban érzékeltem, hogy relatív gyakran visszadob a kezdőpozíciómra a játék amennyiben Multi Tool IV-et használok Elemental Staff-Wind módban. Egyéb esetekben egyáltalán nem jelentkezik probléma, így nem hiszem, hogy én laggolnék.

**Comment by andris155** [comment]
Sajnos a Slimefun nem támogatja a cheat védelmet és a cheat védelem sem a Slimefun-t. Erre nem tudok sajnos megoldást. De a hibajelentést köszi.
