### ISSUE TITLE
Pigstep cd szerezhetősége

### ISSUE THREAD

**Issue by szofogado** [TheOld-Crafters/Minecraft-servers#4732]
Szerver: Oldblocks

Mondták nekem a játékosok, hogy cave, és skyblockon elég nehéz, szinte lehetetlen megszerezni a pigstep nevű cd-t, ezért arra gondoltam, hogy lehetnek neki csinálni egy szimpla craft receptet. Mellékletként csatoltam egy képet, hogy szerintem körülbelül mi lehetne a receptje. Akinek van ötlete, receptre az ne tartsa magában.

![2021-08-01_16 48 46](https://user-images.githubusercontent.com/52892955/127775349-205db0b3-83b5-4712-bce0-2499dc1c465a.png)

**Comment by DiaGamer321** [comment]
Lehet nyitni egzotikus ládából. Jó nyitogatást!

**Comment by MrZero1** [comment]
Inkább küldetésbe legyen jutalomba, mint recept

**Comment by szofogado** [comment]
Vagy küldetéssel, vagy craft receptel, de valami olyan mód kellene, ami nem 'eventhez' vagy szerencséhez kötött.

**Comment by MrZero1** [comment]
Csináltam rá receptet. Obszidián és netheritdarab kell hozzá.
