### ISSUE TITLE
Levédés flagek

### ISSUE THREAD

**Issue by SurvivorTheReal** [TheOld-Crafters/Minecraft-servers#4735]
**Szerver**:Survival

a /gpflags SetClaimFlag nem működik.

Ennyit ír ki arra hogy /gpflags SetClaimFlag NoEnderPearl false (vagy Off, vagy No)
![2021-08-05_18 40 21](https://user-images.githubusercontent.com/39741913/128388344-7734c4fd-5572-4eb6-925c-68547f073212.png)

**Comment by andris155** [comment]
Javítva + beállítottam, hogy alapból is blokkolja az ender pearl-t azoknak, akik nincsenek hozzáadva.
Köszi a jelentést.

**Comment by SurvivorTheReal** [comment]
Köszönöm mindenki nevében :) enderman farm on the way
