### ISSUE TITLE
Hiba/fejlesztési ötlet

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4736]
**Szerver**: Survival

- [x] Old rangú jelezte, hogy a plottelekhez 1 embert tud hozzáadni, utána hibát ír ki neki.
- [x] Shulker packs-ra nincs joguk.
- [x] ### nem megoldható - Világváltáskor a fly kikapcsol. Direkt? Van, akit zavar ez. Ha megoldható, hogy ne kapcsoljon ki, legyen úgy légyszi, de ha valami hiba/bug miatt van ez, maradjon ahogy van.
- [x] ### nem megoldható - Tab-ra a $ mutatását, ha megoldható.
- [x] Spawnerkiütés
- [x] Az új embereknek 5 perc után van lehetőség írni a chat-re. Valami jelző üzenet lehetne, ha a chat-re akarnának írni, hogy 5 perc után tudják használni a chat-et.

**Comment by andris155** [comment]
A tab egyenleg kiírást nem lehet megoldani. Folyamatosan lekér minden felhasználót, ami komoly RAM problémákat okoz.

**Comment by andris155** [comment]
Sajnos azt nem lehet megoldani, hogy ne vegye el a fly-t világváltáskor.

**Comment by MrZero1** [comment]
Akkor kihúzom azt a kettőt.

**Comment by andris155** [comment]
A spawner kiütésnek már működnie kell.
