### ISSUE TITLE
Survival plothiba

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4737]
Az új survival plotján ha egy birka lelegel egy füves blokkot, az nem változik át dirt blokká. Ezzel a régi ploton nem volt gond.

**Comment by andris155** [comment]
Már változnia kell a blokknak. Majd kérlek teszteld le és írd meg, ha nem jó. Köszi a jelentést.

**Comment by Icecroft** [comment]
Teljesen jól működik, köszi a javítást!
