### ISSUE TITLE
Survival jobs pontok

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4738]
Elértem a vadászatban a 125. szintet és csak 9500 pontom van. Ez azt jelenti, hogy 500 jobs szint teljesítése után sem tudok venni egy 1 órás bonust a jobs shop-ban. Gyakorlati haszna így semmi. Ha kb 50 szintenként kaphatnánk egy 1 órás bonust, ahhoz a kapott pontokat kb a hétszeresükre kellene emelni.

**Comment by UDPSendToFailed** [comment]
Ahogy növekszik a szint, pontból is többet ad, úgy, mint pénzből.
