### ISSUE TITLE
Survival skills sharphook probléma

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4739]
A fishing Sharp hook nem működik survival-en. Régebben Oldblockon ment.

**Comment by andris155** [comment]
Ezt sajnos a cheat védelem blokkolja. Megírtam a fejlesztőnek, de nem hiszem készít hozzá támogatást.

**Comment by andris155** [comment]
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4769
