### ISSUE TITLE
Survival - 64-es vásárlás shifttel

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4740]
Eredetileg a Slimefun miatt lett az beállítva, hogy shifttel eladja az egész invet, vásárlásnál pedig nincs hatása. Az új szerveren nincs SF, szerintem vissza lehetne állítani, hogy shifttel 64-et vegyen / adjon el.

**Comment by andris155** [comment]
Beállítottam, ahogy kérted. Majd kérlek teszteld le és írd meg, ha nem jó. Köszi az ötletet.
