### ISSUE TITLE
Old muzeum poszterek

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4741]
szerver: SF survival

Ahogy jártam keltem az Old Múzeumban, meglepődve láttam, hogy az általam készített radioaktív jel poszter is kiállításra kerül, ami megtisztelő, ellenben valamiért a vízjeles verzió van kinn, ráadásul a vízjel (ami amugy azóta módosítva lett admin kérésre) lehet, hogy sértheti egyes játékosok lelki világát ( FCK ).  Javasolnám, hogy cseréljétek le Vízjel nélküli verzióra. És ha elforgatjátok 180 fokkal a keretben, akkor tökéletes lenne.

Fejlesztési ötlet: Icialex csinált egy irtózatosan menő Konosuba 5x4-es posztert. Szerintem érdemes volna berakni az Old Muzeumba, nagyon szép.

**Comment by MrZero1** [comment]
Ha kapok belőle egy másolatot, vagy lemásolhatom, akkor kirakom illetve módosítom

**Comment by Ziredus** [comment]
a plotomon azt atomerőmünél (elég látványos, nagy kéményei vannak) nyugodtan másold le onnan az egyiket, ha nem találsz fenn engem.

**Comment by IciAlex** [comment]
Vagy a pwarpomon a poszter helyen van belőle
