### ISSUE TITLE
Spawner hiba

### ISSUE THREAD

**Issue by szofogado** [TheOld-Crafters/Minecraft-servers#4742]
Szerver: Survival

Ha spawner ládából szerzel spawnert, majd valahova lehelyezet, akkor az átalakul malac spawnerré: (nem számít, hogy milyen volt elötte, így is átváltozik) (szerintem az összes világra igaz az eset.)

**Comment by MrZero1** [comment]
Ha jól sejtem, az új spawner kiütés miatt lehet ez. Majd kicserélem a spawneres ládában a spawnereket, majd valakivel letesztelem azért, hogy jó lett e.

**Comment by andris155** [comment]
A /pickupspawners give paranccsal létrehozottakat kellene belerakni. A régiek gondolom a másik plugin-nal kerültek létrehozásra, amiket ez nem támogat.

**Comment by MrZero1** [comment]
Kicseréltem. Köszi a jelentést! írok privátba.

**Comment by andris155** [comment]
Esetleg lehetne egy beváltó ahol betudják váltani az új spawnerekre a régieket.
