### ISSUE TITLE
Cheat védelem hiányzó fal oszlop(?) blokk modell

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4743]
**Szerver**: gondolom mindenhol

![image](https://user-images.githubusercontent.com/29151964/128705001-07b2a5db-4312-4612-ad6e-4cf482218b38.png)
az alábbi helyzetben ha rá próbálok menni az alsó kőfalra visszadob

**Comment by andris155** [comment]
Ha van időtök a szerveren nagy segítség lenne, ha keresnétek még ilyeneket, mert biztosan vannak még sajnos. Köszi a jelentést.

**Comment by andris155** [comment]
Erre úgy tűnik sajnos nincs megoldás.
