### ISSUE TITLE
Enchant hiba

### ISSUE THREAD

**Issue by REALTomi** [TheOld-Crafters/Minecraft-servers#4744]
Survival
**Szerver**:

Old kardon lévő enchant kisebb szintre változik ha egy ugyan olyan enchantal rendelkező könyvel vagy kardal üllőbe összerakjuk.Jelen esetben old kardal és egy enchantolt gyémánt kardal(Zsákmányolás II,Exhaus III) próbáltam.
![2021-08-09_21 05 15](https://user-images.githubusercontent.com/88681071/128761632-bc300b67-0d09-404c-822a-e3ea49c0f4d4.png)

**Comment by andris155** [comment]
Jó lenne, ha pontosabban leírnád a hibát. Milyen pontosan a 2 kard amit összeakarsz rakni? Mi történik? Minek kellene történnie?

**Comment by SurvivorTheReal** [comment]
Szerintem arra gondol ha van egy egyedi enchant, de mellé sikerül rakni egy zsákmányolást (vagy más vanilla mc-s enchantot) , akkor azt ha össze akarja pattintani az old karddal, az egyedi enchant rámegy, a minecraftos zsákmányolás pedig visszaesik 3 ra 10 helyett.

**Comment by REALTomi** [comment]
Igen arra gondoltam.

**Comment by andris155** [comment]
Ez sajnos a vanilla játék miatt ilyen. Egyedi enchant nélkül is looting III lesz, ha összeraksz 2 looting X-es kardot.
Ha még nem jelentették ezt a hibát, akkor esetleg itt tudod jelenteni a Mojang-nak: https://www.minecraft.net/en-us/bugs
De szerintem lehet nem foglalkoznak a játékban nem elérhető enchant szintek támogatásával.

**Comment by andris155** [comment]
A jelentést köszi.
