### ISSUE TITLE
Skill bug

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4745]
**Szerver**: Survi, OB (csak survin teszteltem)

Az excavation skill mana abilityje elég bugos :/ kickel a console ReadTimeoutException-el
Azt hiszem az lesz a baj hogy a skill hatására túl gyorsan tudok ütni ami nem tetszik a papernek (maybe)

**Comment by andris155** [comment]
Sajnos ez a cheat védelem miatt van. De ezt a plugint még más cheat plugin se támogatja. Nem nagyon van rá megoldás. A fejlesztőnek írtam már, hogy jó lenne hogy ha kompatibilis lenne azzal amit használunk, de egyelőre nem érkezett rá válasz. Köszi a jelentést.

**Comment by andris155** [comment]
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4769
