### ISSUE TITLE
Extra varázslat

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4748]
**Szerver**: Survivalon néztem.

Nem pontosan tudom, mi lehet a hiba, de aukciósházról vásárolt varázskönyv (képen) eszközre való rárakás után nem rakja rá az extra varázslatot, de a könyvet elveszi.

![kép](https://user-images.githubusercontent.com/29709854/129220681-10180046-747b-4fac-ac88-9c6542c1fdc2.png)

**Comment by MrZero1** [comment]
Érdekesség, ha lekértem a paranccsal könyvet, majd összeraktam az önjavítással, úgy az üllőben rárakja az eszközre.
![kép](https://user-images.githubusercontent.com/29709854/129221089-b741bf66-d990-4175-a43d-aa807cdc3497.png)

**Comment by MrZero1** [comment]
Valószínűleg az aukciósház miatt nem jó, @Sizarra is vett, neki is csak az önjavítást tenné rá

**Comment by andris155** [comment]
Szerintem nem kompatibilis vele, ahogy a Shopkeepers sem.

**Comment by andris155** [comment]
Nekem ezt nem sikerült reprodukálni. Ha esetleg változtattál a fordításon, akkor nem tudom hogy utána ezek a könyvek működnek-e amik a régi fordítást kapták meg esetleg. Más ötletem nincs, hogy miért nem működhet.
Ha továbbra is ilyenek a legújabb fordítással is a könyvek, amik az aukcióra kerülnek, akkor nyissatok mindenképpen egy új jelentést.

**Comment by MrZero1** [comment]
Nem lett változtatva semmin pedig

**Comment by andris155** [comment]
Neked sikerült ezt reprodukálni olyan könyvvel amit te hozttál létre?
