### ISSUE TITLE
Raid hiba

### ISSUE THREAD

**Issue by delibotond** [TheOld-Crafters/Minecraft-servers#4749]
Oldblocks/ Oldcraft
**Szerver**:

 Ha megcsinálom a rabló-s küldetést , mivel közelemben van falusi egyből elindul a raid, viszont amint betölti az első csíkot egyből eltűnik és úgy is marad. 2-szer is próbáltam ugyanez lett. Nem nagyon tudom , hogy hogy lehetne megcsinálni, lehet alap mc-s hiba.

**Comment by andris155** [comment]
Ez sajnos nem egy olyan dolog amin tudnék változtatni. Talán több terület szükséges a raid-hez, ha nem elég nagy a szigeted akkor gondolom nem tudja hova leidézni az entitásokat.

**Comment by andris155** [comment]
Ha másnak se jó sehogy sem lehet érdemes lenne kivenni ezt a küldetést. @MrZero1
