### ISSUE TITLE
Loot vadon fejlesztés

### ISSUE THREAD

**Issue by DiaGamer321** [TheOld-Crafters/Minecraft-servers#4750]
Survival.

A múlt hétvégén bekerült egyedi generálás izgalmassá tette a túlélő szervert, de mégis vannak dolgok amikkel (szerintem) izgalmasabbá lehetne tenni a vándorlást.

1. No /fly a lootvadonba.
 A lootvadon nagy része hamar kilett fosztva a gyors fly miatt, ami a nagyobb rangosoknak van. Szerintem, ha ezt megfosztanátok nagyobb playerektől, ezzel igazságosabb lenne a lootolás, na meg izgalmasabb is számukra. (Amúgy is nem hiszem, hogy valaki emiatt vesz fly-t.)

2. Alvás.
 A lootvadonba senki se fog aludni, ha nincs falu közelében, na meg nincs is ott háza. Lehetne az, hogy alváshoz elég lenne 1 (max 2) player.

3. No home.
 Késöbb elmagyarázom...

4. Bossok.
 Csak mint Oldspace-n volt, lehetne 1-2 kastély a világba ahol egy boss van. Mint oldspace-n lennének loot ládák amik 12 óránként újra töltődnek. A boss adna egy valuta szerü tárgyat, amit a beváltónál átlehetne váltani szettre/eszközökre. A kastélyhoz egy térkép vezetne, amit craftolni lehetne, ezért kellene tiltani a home lerakását. A kastély területén a /god is kikapcsolódna.

**Comment by SurvivorTheReal** [comment]
Na, kötekedjünk egyet:

Az első pont: szted a semmiért vettük a rangot?
A harmadik: miért ne kéne home?, majdnem egy órát bolyongtam repüléssel egy tetves sivatagért

**Comment by DiaGamer321** [comment]
1. Ennyi erővel lehetne az event világba is flyotok, nem?
4 napja került be a világ, de a környéken lévő dungeonok kilettek fosztva, mert a  nagyobb rangosok hátradölve csak nyomták az W gombot. Szerintem senki se halna bele, ha kicsit jobban odafigyelnél elytrázás közben. És ha valaki fly-t vesz, azt általába építkezés céljából.  Meg az első pontra arra akartam kilyukadni, hogy fer legyen a defa játékosokkal szemben a lootolás.

3. Az utolsó pontba leírtam, hogy miért.

+Lehetne finomabban válaszolni, amúgy is ez egy ötlet... Nem tény, se nem aranymondás. Ha Zeri-nek nem tetszik az ötlet, bezárja és kész, nem kell félni. :D

**Comment by andris155** [comment]
Én a támogatóktól nem venném el a fly jogot ott. A támogatás nagy segítség a szervernek. Cserébe persze a támogatónak is nagy segítség a fly jog.

**Comment by mangoshell** [comment]
Az jogos, hogy a fly joggal rendelkezők sokkal jobb helyzetben vannak a "sima" playerekkel szemben, de szerintem teljesen megfosztani őket a flytól ezért elég nagy hülyeség. Én max olyat csinálnék, hogy a vadon, end, nether reset után max 1 hétre tiltanám a fly-t, és akkor mindenki egyenlően fedezhetné fel, mert endben szerintem sokkal gázosabb a fly jog az elytra miatt, de perma elvenni semmiképp nem kellene.

**Comment by DiaGamer321** [comment]
Adom Shryx ötletét, igaza is van. Én is arra akartam utalni, hogy fly-al előnybe vannak a rangosok az elején, de már pár hét múlva igaz felesleges. A home elvételét csak arra az esetre gondoltam, ha zeri jó ötletnek tartaná a bossos dungeont. Ha nem is, akkor a dungeon körül 2000 blockos sugárba nem lehetne home-t rakni. (Persze ha zeri be szeretné hozni a bossos dungeont.)

**Comment by SurvivorTheReal** [comment]
Én andris ötletét adom, ha vkinek sír a kicsi szája semmi akadálya prémiumot venni. Annyi pénz nem rendít meg senkit.

**Comment by DiaGamer321** [comment]
Szerintem nem érted a lényeget. Na de mind1. Nem értem miért kell ennyire agresszívnak lenned, mivel újra elmondom azt, hogy "Ez CsAk EgY öTlEt!!!". Ha Zeri úgy tartja, hogy tényleg nem lenne fer elvenni a jogot (Mintha 0 24-be a lootvadonba lennétek...), akkor nem fogja. Lehetnél finomabb. 😘

**Comment by SurvivorTheReal** [comment]
Jó, finomabb leszek.

Akkor:

Gondolkodtam amúgy én is kicsit.
Endben elvenni a flyt annak lenne értelme.
Mert hiába bandukolok már, repüléssel se találok kifosztatlan end cityt, vagy nem mentem elég messze, de ezt kétlem.

**Comment by MrZero1** [comment]
Igazából amit logikusnak látok én is, az az, hogy ha új világ kerül be, akkor 1 hétig nincs fly abban a világban. Elytrát lehet szerezni, venni, szóval szerintem az adott.

A boss-ok annyi, hogy az infernalmobs volt a legjobb, sok sok loot volt benne, ami mind (majdnem) hasznos volt, nem legyőzhetetlen mobok voltak.. olyasmi jó lenne, erősebb boss-okat nem gondolnám.

Home szerintem maradhat, az alvás is jó ahogy van.
