### ISSUE TITLE
Spawnervétel Survival szerverre

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4752]
**Szerver**: Survival

Lenne igény különféle vásárolható spawnerekre? (webstore-ban)

**Comment by DiaGamer321** [comment]
Spawnerládás spawnerekre, vagy egyéb mobos.

**Comment by Laci444** [comment]
Szerintem a játékmenet alatt nem megszerezhető spawnerek különleges jutalmak maradhatnának (pl. szülinapi eventen), így megmaradna az értékük.
Dia bat spawnere is igazi látványosság sfsen :D

**Comment by MrZero1** [comment]
azok, amik a spawneres ládában vannak, azokat fixen lehetne venni darabra

**Comment by ketezerhat** [comment]
Mindenki elfelejti hogy én adtam diának a spawnert :c

**Comment by DiaGamer321** [comment]
@ketezerhat  mindenki tudja! <3

**Comment by andris155** [comment]
A kérdéseket inkább a ide kellene írni: https://github.com/TheOld-Crafters/Minecraft-servers/discussions/categories/q-a
De a Discord még jobb lenne. A kérdés nem fejlesztési ötlet és nem is hiba.
