### ISSUE TITLE
chc

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4756]
**Szerver**:mindenhol

Tudunk valamit kezdeni azzal hogy nem engedi hogy köszönjek? ._.
![image](https://user-images.githubusercontent.com/29151964/131220200-16b592c9-dfa0-4aa2-8ed1-981b78a4ed6d.png)

**Comment by SurvivorTheReal** [comment]
Ez szimpla spam védelem nem?

**Comment by andris155** [comment]
Várj egy másodpercet azután miután más köszönt, vagy köszönj máshogy.
