### ISSUE TITLE
spawner kiütés

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4757]
**Szerver**: survi

kiütött spawnerek által spawnolt moboknak nincs ai-uk így a nonhostileokat nem lehet szaporítani :c

**Comment by Ziredus** [comment]
Akkor se ha elég közel taszigálod öket egymáshoz? Emlékeim szerint én anno tudtam a spawnolt birkáimat szaporítani.

**Comment by SurvivorTheReal** [comment]
Amúgy ha van állat spawnered, felrakod a tojás adós extra enchantot, és lespawnolsz 1 et, és a nagyra még 2 tojás, és ott a 2 rendes állat.

Viszont nem értem ha van spawner minek szaporítani

**Comment by andris155** [comment]
Már van AI-uk.

**Comment by SurvivorTheReal** [comment]
A hostile moboknak továbbra sincs ügye?

**Comment by andris155** [comment]
Mindennek van.
