### ISSUE TITLE
Moderátor chestshop vásárlás

### ISSUE THREAD

**Issue by mangoshell** [TheOld-Crafters/Minecraft-servers#4758]
**Szerver**: Mind gondolom

Moderátor ranggal nem lehet vásárolni chestshopban, ezt az üzenetet adja ki:
![image](https://user-images.githubusercontent.com/69635280/131230290-7c02611e-e40e-47cd-a718-cc284021356e.png)

**Comment by andris155** [comment]
Javítottam ezt a hibát. Köszi a jelentést.
