### ISSUE TITLE
Telekinesis enchant

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4759]
https://www.youtube.com/watch?v=cNtT-FjVyy8
plusz ha olyan blockot ütsz ki amin valami olyan van amivel együt kiüti akkor azt sem adja oda.
(pl kiütöd a követ és repeater van rajta akkor a repeatert nem adja oda.)

**Comment by UDPSendToFailed** [comment]
Egyszerű, ne olyan enchanttal üsd ki a ládát / kemencét.

**Comment by IciAlex** [comment]
Ez megoldás, de attól még baj hogy eltűnteti.

**Comment by IciAlex** [comment]
Ennyi erővel pl a shulkeres addolásra is lehetne azt mondani hogy: Egyszerű, ne addolj vele.

**Comment by MrZero1** [comment]
Mivel kikerült más okokból az enchant, így ezt lezárom

**Comment by andris155** [comment]
De még visszakerülhet.

**Comment by andris155** [comment]
Javították a hibát. Zeri engedélyezi, ha neki is megfelel így.
