### ISSUE TITLE
A Bunny Hop enchant nem működik

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4760]
**Szerver**: Survival

![kép](https://user-images.githubusercontent.com/29709854/131258917-e0b1d75b-5073-4dd4-9508-6218ed1b9f28.png)

A bunnyhop enchants nem működik (3 fokozatú, egyik sem ad effektet)

**Comment by MrZero1** [comment]
OldBlockson sem jó

**Comment by andris155** [comment]
Ahhoz, hogy működjön nyúllábnak kell nálad lennie.
