### ISSUE TITLE
Láthatatlan eszközkeret

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4762]
A Skills miatt adott szint után már nem lehet olyan láthatatlan potit csinálni ami jó a crafthoz.
![image](https://user-images.githubusercontent.com/74869381/131354874-5911e306-8a9c-4684-8c2a-f7d506fa1e35.png)

**Comment by MrZero1** [comment]
Kicserélhetem más tárgyra a bájitalt. Valami javaslat rá?

**Comment by andris155** [comment]
Talán lehet hozzá több receptet is. Akár ezt is bele lehet rakni (?)

**Comment by MrZero1** [comment]
Egyszerűbb lesz ha másik tárgy lesz. Discordon az aranyrépát javasolták, nekem az tökéletes

**Comment by MrZero1** [comment]
Aranyrépa lett.
