### ISSUE TITLE
Újonc vagyok

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4763]
Fresh Animations miatt letölöttem az optifinet, relogoltam és újoncnak ír.
![image](https://user-images.githubusercontent.com/74869381/131491117-42b089b3-dc8d-4726-93cc-8ed94863bf0b.png)

**Comment by MrZero1** [comment]
Független a forráscsomagtól, moderátorokkal is volt ilyen. Leléptek, majd pár perc múlva fel, és nekik sem engedett írni.

**Comment by IciAlex** [comment]
Gondolom akkor azért van mert verziót váltottam. 1.17.1ről Optifine 1.17.1re

**Comment by TheNandoX** [comment]
Ha az interneteddel van valami akkor történik. PL.: Lekapcsolódsz gyorsan és vissza

**Comment by andris155** [comment]
Ez a plugin nemrég frissült. Lehet a frissítés megoldotta ezt a hibát.
