### ISSUE TITLE
Beváltás

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4764]
SF-Survival

Korábban volt a /warp Beváltó warpon egy npc akinél lehetett SF-es cuccokat beváltani. Mivel a basic machines-ból ki van véve bizonyos okokból a Crucible, így azt nem tudjuk craftolni, és az ebből készíthető elektromos gépet se. A nagy SF-es crach előtt ez úgy volt orvosolva, hogy a beváltó NPC-nél lehetett venni cruciblet (amit lerakni nemtudtunk, de craftolni belőle már igen). Ezt kéne visszahozni.

**Comment by andris155** [comment]
Már sajnos nincs mentésem arról a falusiról. Esetleg ha leírnád, hogy miket kellene újra beállítani az nagy segítség lenne.

**Comment by andris155** [comment]
Találtam mégis mentést róla. Amint lesz időm majd beállítom a falusit.

**Comment by mangoshell** [comment]
Kész van

**Comment by MrZero1** [comment]
Köszi a jelentést @Ziredus!
Köszi @mangoshell neked is ☺
