### ISSUE TITLE
/warp ládák  játékos megmérgezése 

### ISSUE THREAD

**Issue by Aquir-0** [TheOld-Crafters/Minecraft-servers#4765]
szerver: survival 
A /warp ládáknál ha meglősz 1 játékost poisoned arrows enchantos  számszeríj-al vagy íj-al akkor megtudod mérgezni őt és sebződik is tőle. (laci12 vagyok)

**Comment by MrZero1** [comment]
Elvileg már nem mérgez, Oli segítségével megoldva
