### ISSUE TITLE
Slimefun Luckyblock mobspawn

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4766]
SF-Survival
Nyitogatom a Very Lucky Blockokat és irdatlan mennyiségű farkas és macska spawnol. Ha lehetséges jobb volna ha a hadseregnyi macska/farkas helyett csak 2 db spawnolna. Így akinek szüksége van rá annak a számára továbbra is hasznos marad.

**Comment by andris155** [comment]
Ezen a plugin forráskódban vannak. Persze tudok hozzá parancsot beállítani is külön, de ezek valóban hasznosak valakinek, vagy inkább letiltsam?

**Comment by andris155** [comment]
Ezek a plugin forráskódban vannak. Persze tudok hozzá parancsot beállítani is külön, de ezek valóban hasznosak valakinek, vagy inkább letiltsam?

**Comment by Ziredus** [comment]
Igazából nemhiszem, hogy bárkinek hasznos lenne, ha gondolod letilthatod, Azzal viszont növekszik a többi loot esélye nem? Kisebb a szórás.

**Comment by andris155** [comment]
Növekszik, igen.
