### ISSUE TITLE
Nem megfelelő támogatási link.

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4767]
szerver: SF-survival
![2021-09-05_16 33 40](https://user-images.githubusercontent.com/60291809/132130713-303456d3-5c7b-480c-8861-f7c81291026c.png)
A belépéskor chaten kapunk üdvözlésképp pár hasznos linket, mint Weboldal, Támogatás, és Hibajelentés. A Támogatáshoz még a minemarketes url cím van beírva.

**Comment by andris155** [comment]
Frissítettem a linket. Köszi a jelentést.
