### ISSUE TITLE
Jobs bonus hiba survivalen

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4768]
Teljesítettem a jobs questet, ami 50% pénzbónuszt ad fél órára a földműves jobnak.
Ez sajnos nem adódott hozzá a bónuszokhoz, csak a hétvégi 100% pénzbónusz látszódik:

![2021-09-05_21 41 27](https://user-images.githubusercontent.com/19332825/132142063-61cb50d6-c4a6-4b77-8246-0f66cf7e2463.png)

**Comment by andris155** [comment]
Szerintem sajnos ez direkt ilyen.
