### ISSUE TITLE
AureliumSkills cheat védelem kompatibilitás

### ISSUE THREAD

**Issue by andris155** [TheOld-Crafters/Minecraft-servers#4769]
**Szerver**: Survival, OldBlocks

Le kell majd tesztelni, hogy mit nem engedélyez a cheat védelem és ezeket le kell tiltani a plugin-ban addig még nem támogatja a cheat védelmet az AureliumSkills.

**Comment by Laci444** [comment]
Inaktivitás miatt lezárom
