### ISSUE TITLE
UwU

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4771]
![image](https://user-images.githubusercontent.com/74869381/132941323-e9437cce-bec7-4684-84a4-2673ac444a61.png)

**Comment by mangoshell** [comment]
UwU

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/132944687-0b0e7b09-200c-4c21-a283-1ba463a50d75.png)

Javítottam, köszi.
