### ISSUE TITLE
/ghelpop fejlesztés

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4772]
**Szerver**: Mindegyik

A staffcsapattal beszéltük, hogy jó lenne, ha a sima /helpop helyett a /ghelpop lenne elérhető mindenkinek. Ezáltal ha valamelyik szerveren gond van, de nincs fent staff azon a szerveren, akkor használhatja ezt a parancsot.
Tehát, a /helpop parancsot letiltani, helyette lenne  a /ghelpop. Esetleg lehetne rá alias, pl. /segitseg.
És/vagy, ha használni akarja a /helpop parancsot, akkor üzenetbe jelezhetné neki a chat-en, hogy erre nincs joga, használja a /ghelpop parancsot.

**Comment by andris155** [comment]
Meg kell majd csinálnom, hogy amikor elindul a plugin, akkor tiltsa le az EssentialsX api-val a /helpop parancsot majd regisztrálja a plugin a saját parancsaként a /helpop parancsot.

**Comment by andris155** [comment]
A /helpop paranccsal már a bungeehelpop működik. /ghelpop nincs többé, mivel felesleges meg nem is nagyon ismerte senki. A /segitseg is működik hozzá.
