### ISSUE TITLE
UwU2.0

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4773]
![image](https://user-images.githubusercontent.com/74869381/132957072-333797e5-b435-47f9-9d52-93a2e95cf0dd.png)

**Comment by MrZero1** [comment]
Ez így egyszerre?

**Comment by MrZero1** [comment]
20:00-kor elvileg csak hétfőtől péntekig van horgászverseny, akkor nemtudom

**Comment by IciAlex** [comment]
egyszerre

**Comment by IciAlex** [comment]
![image](https://user-images.githubusercontent.com/74869381/132982818-d9ca9bd6-05c7-423a-ba6b-4356a90d209e.png)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/132989645-26ea8de2-97ce-4161-bb33-35ff21bdc781.png)

Most már ilyen.
