### ISSUE TITLE
EMF

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4774]
**Szerver**: survi

![image](https://user-images.githubusercontent.com/29151964/132994665-9615032b-d362-427f-ab03-8417d1e719b0.png)
kicsit bugos :c

**Comment by IciAlex** [comment]
laci laci... már jelentettem

**Comment by IciAlex** [comment]
be is zárták :(

**Comment by MrZero1** [comment]
Annyit tudtam most állítani rajta, hogy kivettem a blacklisted-days közül a szombat, vasárnap napokat, így hétköznap és hétvégente 2 óránként van a verseny, de hétvégén még több féle verseny is van (pl reggel 7, 9, 11 óra) úgy, hogy ne ütközzenek. Ha továbbra se jó, akkor nincs ötletem, majd jelenti megint valaki vagy újranyitjuk ezt.
