### ISSUE TITLE
EliteMobs trollkodási lehetőség

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4775]
Akárhová lerakható a custom npc, védésre, telekre, még spawnra is
Egy idő után despawnol magától, de szerintem más levédésén nem kéne működnie

![image](https://user-images.githubusercontent.com/16057404/133419075-aec25861-e1ff-45ee-8cfa-fa0421101482.png)
![image](https://user-images.githubusercontent.com/16057404/133419118-7d6c476d-f0bb-44ad-89c4-234866ed90fb.png)

**Comment by andris155** [comment]
Ezekkel a flag-ekkel tudják állítani az adminok, hogy WorldGuard régión lehessen-e megidézni EliteMobs elélőnyeket. A többi levédési plugin-t sajnos nem támogatja.
@MrZero1 
Köszi a jelentést.

**Comment by andris155** [comment]
https://github.com/MagmaGuy/EliteMobs/wiki/%5BThird-party-support%5D-Worldguard-flags
