### ISSUE TITLE
Anticheat és event kompatibilitás

### ISSUE THREAD

**Issue by TheNandoX** [TheOld-Crafters/Minecraft-servers#4776]
**Szerver**: Survival

Az Anticheat nagyon zavaró egy-két eventnél és flynál is, ugráláskor esetenként fps dropp van. Fly közben gyors zuhanás szinte nem is lehetséges, folyamatosan viszadob körülbelül 10 blokk zuhanás után. Lenne egy kevés javítanivaló.

**Comment by IciAlex** [comment]
Elytrát nem lehet használni néha, random megáll a levegőben. 
Zuhanás közben jobb kattolsz akkor visszadob.

**Comment by MrZero1** [comment]
Tntrun minigame-n is van ez a drop, ugrásnál. Illetve egy két napieventen elég erőteljesen is

**Comment by andris155** [comment]
> Elytrát nem lehet használni néha + néha random megáll a levegőben.
> Zuhanás közben jobb kattolsz akkor visszadob.

Nyiss erre külön jelentést, ne egy másikhoz írj teljesen más hibákat és kérlek ne uwu névvel, ha lehet. A GitHub nem poénkodásra van.

**Comment by IciAlex** [comment]
Ez az anticheathez tartozik... nyilván azért ide írtam.

**Comment by Laci444** [comment]
Inaktivitás miatt lezárom
