### ISSUE TITLE
Új dolgok

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4777]
**Szerver**: Survival

- [x] HG-ra való belépés után bentmarad az invben a hátizsák, szóval lehet bármi tárgyat kintről bevinni, és az arénából kihozni
- [x] A pvptoggle is használható úgy, hogy a pvp kikapcsolva marad belépés után, viszont harc közben már nem lehet visszakapcsolni.
- [x] A petblock is jön veled a Survivalgames világba, eventekre, minigame-kre.

**Comment by andris155** [comment]
Kikapcsoltam a hátizsákhoz az ItemShortcut-ot így nem marad nálad mindig. Viszont így lehet, hogy csak paranccsal lesz megnyitható.

**Comment by andris155** [comment]
Az event világban letiltottam a hátizsákokat. Ha esetleg egy új világba kerülnek eventek azt majd hozzá kell adni később.

**Comment by andris155** [comment]
A petet is letiltottam az event világban.

**Comment by andris155** [comment]
A pvptoggle parancshoz nincs jelenleg olyan opció, hogy ki lehessen kapcsolni világonként. Írtam egy kérést a fejlesztőnek, de nem biztos, hogy belerakja a plugin-ba ezt.

**Comment by MrZero1** [comment]
A petnek a táskáját meglehet nyitni az eventvilágban.
![kép](https://user-images.githubusercontent.com/29709854/133906817-693bf78b-a66c-4379-8ca9-e4fbf19a7311.png)

/petblock GUI-t megnyitod, és ott a táska.

**Comment by andris155** [comment]
Hát akkor false-ra rakd az event világban ezt a jogot? :D

**Comment by andris155** [comment]
> A petnek a táskáját meglehet nyitni az eventvilágban.
> ![kép](https://user-images.githubusercontent.com/29709854/133906817-693bf78b-a66c-4379-8ca9-e4fbf19a7311.png)
> 
> /petblock GUI-t megnyitod, és ott a táska.

Elvileg már nem tudják.

**Comment by andris155** [comment]
A PvP kapcsolgatás egyelőre kiszedtem, majd le kell cserélni az egész plugint, hogy ezt meglehessen oldani.
