### ISSUE TITLE
Elite Mobs plussz élethiba

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4778]
Felhúztam a karakterem Prestige 1 szintre. Ezek után minden teljesített rank után kellene kapnom plussz életeket, de hiába oldottam fel 2 ranket is, nem kaptam meg. Valószínüleg a skills ezt is felülbírája, mint ahogyan az Old armorok utáni életeket sem kapjuk meg.

Az Elite Mobsnak így semmi értelme, a megszerzett dolgokat másik prestige szinten már nem tudom használni, eladhatatlanok, mivel playerhez kötöttek, az elite coinok törlödnek prestige szintlépéskor, a plussz életeket nem kapjuk meg.

**Comment by MrZero1** [comment]
Ha ezzel ilyen baj van (meg még kitudja mi lesz később) érdemes akkor megválni tőle, aztán keresgélni tovább másik plugint

**Comment by andris155** [comment]
A plusz életeket szerintem megadja. A szívek száma nem nagyon jelent semmit az Aurelium Skills-el.

**Comment by andris155** [comment]
Megadja a plusz életeket. A szívek száma néha random, de azzal nem kell foglalkozni.
Ha engedélyezve lenne az action bar szöveg hozzá, akkor normálisan kiírná a pontos számot. @MrZero1 nem lehetne ezt engedélyezni?
<img width="349" alt="Screenshot 2021-09-25 213719" src="https://user-images.githubusercontent.com/8324198/134784138-84c47a8c-618b-4124-b8ac-6c86366ffe63.png">

**Comment by MrZero1** [comment]
Engedélyeznéd @andris155?

**Comment by andris155** [comment]
Engedélyezhetem, de sajnos az OldBlocks-on ütközik az action bar üzenetekkel, amiket fogalmam sincs, hogy hol állítottatok be.
<img width="400" alt="Screenshot 2021-09-25 214842" src="https://user-images.githubusercontent.com/8324198/134784384-549ab123-dcef-4bff-9103-9bcb15dbcb6f.png">
+ ha valami még használja az action bar-t azzal sem kompatibilis ez.

**Comment by andris155** [comment]
Ja az ultrabar-ban állítottátok be, és erre még toggle sincs benne. Inkább akkor ezt kikapcsolom és akkor lesz helyette a skill menü.

**Comment by andris155** [comment]
A /sk toggle-el ki lehet kapcsolni, ha valakit zavarna.
