### ISSUE TITLE
Közös chat

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4779]
**Szerver**: Összes

Skrisz01 javaslata alapján, lehetne közös chat/tab a szervereken.

**Comment by skrisz0101** [comment]
de ne úgy hogy parancsot kell írni az üzenet előtt h elküldje minden szeróra, hanem rendesen

**Comment by andris155** [comment]
A közös tab megoldható. A közös chat kevésbé megoldható, meg addig ameddig így 10-20 játékos van oké nagyon jó a közös chat. De ha majd 50-60 esetleg még több játékos, akkor egy óriási káosz lesz csak belőle, hogy most akkor ki honnan mit írt. Ha meg minden szerverhez még egy prefix lenne az is nagyon káoszos lenne. Főleg az OldBlocks szerveren ahol így is 2 prefix van.

**Comment by skrisz0101** [comment]
én azt tapasztalom hogy hónapok óta 10-20 a játékosszám, javítsatok ha tévedek. Ha meg esetleg nőne, vissza lehetne csinálni (?)
a +Prefix meg sztem elég egy [S] [SF] [O] [É], nem nézne ki sztem így se rondán a chat. vagy akár nem is kötelező a prefix, nem muszáj megkülönböztetni chaten h ki honnan ír
Azért lenne jó, mert így 1 szerón ,,pörög" a chat, a többin meg mintha temetőben lennénk.

**Comment by andris155** [comment]
Én kifejezetten nem szeretnék ilyet, mert szerintem keveredés lenne csak belőle. @MrZero1 majd írj, ha ennek ellenére is legyen ilyen. A több játékosra meg nem árt tervezni előre, hogy ne akkor kelljen mindent módosítgatni amikor már több játékos van.

**Comment by skrisz0101** [comment]
Amíg ennyi ember van fent, belefér a,,keveredés"
De még 3x ennyinél is

**Comment by MrZero1** [comment]
Ha megoldható lenne, szerintem is beleférne. Ha esetleg meg többen lesznek, akkor visszaállítjuk

**Comment by skrisz0101** [comment]
10 fölé sose megy a játékosszám mostanság.
ez a módszer még 40nél is működne.
(survival szerón annó volt 60 ember is, mégis lehetett látni a chatet)

**Comment by andris155** [comment]
Sajnos ezt nem tudom megoldani. Maximum úgy lehetne, ha saját plugint írnék hozzá. De ahhoz a tudásom se biztos, hogy megvan illetve rengeteg idő és ennél vannak sokkal fontosabb dolgok is, amikkel elvagyok maradva a szerverrel kapcsolatban.

**Comment by andris155** [comment]
A közös tablist-tel az a baj, hogy nem nagyon lehet megoldani rajta a rangok megjelenítését úgy, hogy rendezve is legyen. De szerintem nem annyira fontos, hogy kik vannak a másik szervereken. Ha valakivel játszani akar valaki csak megbeszélik, hogy egy szerverre menjenek. :D

**Comment by andris155** [comment]
Az ötletet azért köszi. Talán a jövőben lesz valami közös chat megoldás.

**Comment by skrisz0101** [comment]
Értem, kár. 
Amúgy az egymással beszélgetés nem függ össze azzal, h együtt játszanak-e
