### ISSUE TITLE
Börtön - Petblock

### ISSUE THREAD

**Issue by TheNandoX** [TheOld-Crafters/Minecraft-servers#4781]
**Szerver**: Survival

Hiba 1 - Bebörtönözve használható a /petblock parancs, így meg lehet szökni a börtönből
Hiba 2 - A spawnon a petblockról leszállva kiesel a világból majd az örök sötétség és feledés felemészt

**Comment by andris155** [comment]
Letiltottam ezeken a helyeken. Köszi a jelentést.
