### ISSUE TITLE
Hátizsák

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4783]
**Szerver**: Survival

Tesztelni kellene, hogy a nagyobb slotos hátizsák tartalma hogy módosul, ha a rang lejárna.

Ha eltűnik belőle, akkor meglehetne adni minden rangnak a legnagyobb slotos hátizsákot.

**Comment by andris155** [comment]
Nekem ez a mostani plugin nagyon nem tetszik. Mindenkinek egy táskája van és még az inventory-ból se lehet kiszedni, vagy lerakni valahova. Folyamatosan elfoglal egy slotot.

**Comment by andris155** [comment]
Nem lehetne valami Slimefun-oshoz hátizsákos megoldáshoz hasonló plugin inkább?

**Comment by andris155** [comment]
Nem lehetne valami olyan plugin inkább, ami olyasmi mint a Slimefun-ban a hátizsákok?

**Comment by andris155** [comment]
Szerintem inkább ez kellene: https://dev.bukkit.org/projects/backpack-item

**Comment by andris155** [comment]
Vagy ez, ha csak egy menü kell, amiben tudnak tárolni dolgokat: https://www.spigotmc.org/resources/playervaultsx.51204/

**Comment by MrZero1** [comment]
Nekem pont az tetszik, hogy nem lehet lerakni, így nem lehet bugoltatni a chestshorttal meg mással (remélem)
Illetve lehet, hogy egy slotot elfoglal, de az 6x9-ig táskát ad pluszba.

**Comment by MrZero1** [comment]
https://dev.bukkit.org/projects/backpack-item

Nekem az nem tetszik, hogy a mellvértet kell lekraftolni.

**Comment by andris155** [comment]
> Nekem pont az tetszik, hogy nem lehet lerakni, így nem lehet bugoltatni a chestshorttal meg mással (remélem)
> Illetve lehet, hogy egy slotot elfoglal, de az 6x9-ig táskát ad pluszba.

De hiába duplázzák, ha egy a hátizsák egy adott menüt nyit meg. Maximum 2 nyitná meg ugyanazt.

**Comment by andris155** [comment]
A Shulkerpacks amúgy a Chestsort miatt nem volt jó. Anélkül működne tökéletesen.

**Comment by andris155** [comment]
Ha kevesebb slotra van joga a játékosnak és több tárgy van benne, akkor a megnyitásnál kidobja belőle a játékos elé a tárgyakat.

**Comment by MrZero1** [comment]
A megbeszéltek alapján: https://www.spigotmc.org/resources/playervaultsx.51204/

**Comment by andris155** [comment]
A plugin bekerült, majd kellene hogy a jogok akkor hogyan legyenek hozzá. Mennyit lehessen venni esetleg, ha lehessen venni jogot több menüre.

**Comment by MrZero1** [comment]
Vásárolható "széf" jogok, hasonlóan, mint az enderchest-nél:
1-4 - 400 ft
5-8 - 400 ft
9-12 - 400 ft
13-16 - 400 ft
17-20 - 400 ft

**Comment by andris155** [comment]
Minden megoldható. :D
