### ISSUE TITLE
Elite Mobs - Charmok szintje hibásan van kiírva

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4785]
A megszerzett charmokon minden esetben Prestige 0 van, hiába szereztem más szinten. Ettől független jól működik az adott Prestige szinten, de hibás a felírat.

**Comment by Denzen08** [comment]
Helló!

Kérlek fejtsd ki bővebben a problémádat!

Üdvözlettel, Denzen

U.I: a témát 2 hét után lezárom ha nem érkezik rá hozzászólás!
