### ISSUE TITLE
Elite Mobs - Hiányzó szintlépés követelmény

### ISSUE THREAD

**Issue by Icecroft** [TheOld-Crafters/Minecraft-servers#4786]
A magyarosítás előtt az /ag parancs után megnézhető volt, hogy mennyi Elite Coin kell a következő szinthez, ez eltűnt, most próbálkozni kell, csak azután írja ki.
A prestige szint ugrásnál viszont próbálkozás után sem írja ki, így egyáltalán nem tudom, hogy mi a coin követelmény a Prestige 3 szinthez. Ez elég kellemetlen, mert felesleges coinokat gyűjteni nem éri meg, mivel a prestige szintugrásnál minden Elit Coin eltűnik.

**Comment by MrZero1** [comment]
Ha rányomok arra, nekem az alábbit kiírja pirossal. Ott írja, mennyi coin kell, és mennyim van. 

![kép](https://user-images.githubusercontent.com/29709854/135723172-e6f738d0-c7bf-40db-b6a0-8ce220ae232b.png)

![kép](https://user-images.githubusercontent.com/29709854/135723163-54230ceb-67f4-468a-9b8f-751b4543d804.png)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/135723195-a66532c3-0026-4ddf-bf47-62ae48139ded.png)

És ott is írja, mennyi pénzem van.

**Comment by Icecroft** [comment]
> 
> 
> Ha rányomok arra, nekem az alábbit kiírja pirossal. Ott írja, mennyi coin kell, és mennyim van.
> 
> ![kép](https://user-images.githubusercontent.com/29709854/135723172-e6f738d0-c7bf-40db-b6a0-8ce220ae232b.png)
> 
> ![kép](https://user-images.githubusercontent.com/29709854/135723163-54230ceb-67f4-468a-9b8f-751b4543d804.png)

Ez az amit mondtam, korábban rányomás nélkül is kiírta a következő szinthez szükséges Elit coinok számát, most már rá kell nyomkodni és bogarászni a bordó betűket. Ha a következő prestige szintre akarsz lépni, ott hiába nyomsz rá, akkor sem mondja meg, hogy mennyi elit coin kell az átlépéshez. (Az utolsó rank teljesítése nem cisz át a következő prestige szintr autómatikusan, hanem ahhoz is Elit coin kell, nem is kevés)

**Comment by MrZero1** [comment]
Hát, nem tudom milyen volt az előző, de a konfigba se látok arra vonatkozó adatot, hogy kiírná, mennyi coin kell ahhoz a ranghoz.

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/135723629-b39a7038-237e-4b03-adae-5a48e6b04ed7.png)

Most feloldottam az összes 'céh' rangot, és rányomtam a presztízs rangra. nyilván úgy látom értelmét, hogy automatikusan nem rak át, hisz van ott fontos infó, amit érdemes elolvasni

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/135723954-1cc9ece9-1ab0-4d14-91b4-e499b55e8ee3.png)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/135724104-30dbb10e-818d-4565-a59b-4f7b719aee70.png)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/135724300-d40b7ae0-27dc-4c85-bfc8-6a99355cf98b.png)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/135724366-0a8ce766-4a89-4cde-aeb5-61384f868a7d.png)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/135724393-0d8d6c99-8581-4c1c-8ed0-290d16158471.png)

**Comment by MrZero1** [comment]
Javítva. Köszi Ice! ☺
