### ISSUE TITLE
anticheat

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4787]
**Szerver**:

![image](https://user-images.githubusercontent.com/29151964/135660073-01a43fc8-b8b9-4559-aaed-afecb01af9ba.png)
Az alábbi ábrán látható hogy mikor közel megyünk a falhoz egy pár pixellel fentebb dob a játék, mivel a fel hozzákapcsolódik a blockhoz, így egy kis fal lesz a block és az oszlop között.
A cheat védelem visszadob, amikor megpróbálok ráállni a kis falrészre

**Comment by andris155** [comment]
Sajnos erre nincs megoldás.
