### ISSUE TITLE
Itemfilter plugin

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4788]
**Szerver**: Surviva, OldBlocks

https://www.spigotmc.org/resources/itemfilter-1-13-filter-pickup.70334/

**Comment by andris155** [comment]
Az SFSurvival-on már van erre Slimefun addon-os tárgy. A többi szerverre akkor berakhatom?

**Comment by MrZero1** [comment]
Igen

**Comment by andris155** [comment]
Beraktam. Működik.
