### ISSUE TITLE
UU-matter automatikus felhasználás

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4790]
SF-Survival
A jelenlegi Autocrafterekkel nem lehet az UU-matterből gyártani semmit. A korábbi Slimefun verzióban használt régi autocrafterrel gond nélkül lehetett gyártatni UU-matterből cuccokat. Így az volna a felvetésem, hogy a régi kódsorból kibogarászni a teljes Autocraftert, és külön +ba berakni (hasonlóan a poma féle androidokhoz) Így ismét lehetne automatizáltan UU-matterből gyártani dolgokat.

**Comment by andris155** [comment]
Amit írtál azt megcsináltam, de nem igazán működik. Meg rengeteg dolog már nincs is meg a Slimefun-ban, ami kell hozzá. Valószínűleg valahogy az új auto-crafter-be lesz inkább megoldva.

**Comment by Ziredus** [comment]
Kár. Azt mondjuk nemtudom mi kell hozzá, de ha alapanyag szintü a probléma azt még egyszerü beváltással meg lehetne oldani :/ Viszont ha tényleg nem kíván megfelelően müködni az szomorú.

**Comment by andris155** [comment]
Sajnos erre nem sikerült megfelelő megoldást találni.

**Comment by andris155** [comment]
Még szánok erre időt, hátha sikerül megoldást találni.

**Comment by andris155** [comment]
<img width="368" alt="Screenshot 2021-10-05 172936" src="https://user-images.githubusercontent.com/8324198/136054546-de4e29b4-33d2-4648-8fd9-fcac0377ac72.png">
Egyelőre visszaállítottam a Slimefun-ba. A barkácsolás biztosan működik benne, a többit majd neked kell tesztelni. Most lehet használni, de ha valami olyan változás történik a Slimefun-ban, ami miatt nem működik majd és nem tudjuk rá frissíteni, akkor sajnos ki fog kerülni.
Remélhetőleg Laci4 megtudja oldani, hogy inkább addon-ban legyen, de az, hogy az addon-ban van vagy a Slimefun-ban az nem változtat a tárgyon elvileg.
