### ISSUE TITLE
Hiányzó warp

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4791]
Old Blocks ---> savsziget

Old Blocks Savsziget játékmódjában a Savsziget spawnja a /ai spawn parancs segítségével elérhetetlen. Azt íja nincs ilyen warp. Abból kiindulva, hogy a Cave Blocks esetén a /cb spawn paranccsal érhető el a Cave spawn, gondolom itt is így kéne müködnie. Jelenleg úgy érhető el a Savsziget spawnja, hogy a /spawn, majd a világ választóban a savsziget npct választjuk.

A Hibát xX_Nando_Xx fedezte fel.
![2021-10-10_03 02 27](https://user-images.githubusercontent.com/60291809/136677678-95c9b962-56e6-428f-8234-1613d5cec45d.png)

**Comment by andris155** [comment]
Beállítottam. Köszi a jelentést.
