### ISSUE TITLE
Login kép frissítés.

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4793]
Login
A nagy kép ami üdvözöl minket már nagyon elavultá vált. Még a Survival Savsziget és Épitész+ felállás látható rajta.
![2021-10-12_23 51 59](https://user-images.githubusercontent.com/60291809/137034176-20986238-17b7-45b3-8d92-418ce2f8f673.png)

**Comment by Denzen08** [comment]
Helló!

Már nincs ott semmi, hamarosan teszünk ki egy újat.

Üdvözlettel, Denzen
