### ISSUE TITLE
NPC/GUI shop

### ISSUE THREAD

**Issue by Laci444** [TheOld-Crafters/Minecraft-servers#4795]
# Bolt reformooooook
#### Ezen felül a boltokat és az NPC-ket ingame is lehet módosítani, így az adminok könnyen tudnak korrigálni az árakon vagy akár a kínálaton config hozzáférés nélkül is. Kicsit meg tudnánk könnyíteni az áruk megtalálását, mivel tematikusan eladókra tudjuk bontani a kereskedelmet, illetve kicsit menőbben is néz ki ha nem egy táblának adod el a felesleges gyémántjaidat.
A boltok elkészítését szívesen vállalom, volt már szerencsém a pluginhoz. Elég macerás és monoton meló mindent egyesével bepakolgatni, de a végeredményért mindenképp megéri!
![image](https://user-images.githubusercontent.com/29151964/137163009-a85d9c56-a648-4792-b650-d393bfdcf17a.png)

**Comment by Laci444** [comment]
Sidenote: a plugin prémium verziója fizetős, de elérhető egy ingyenes (bár kevesebbet tudó) verziója is. Én az ingyeneset próbáltam majdnem minden igényt kielégített az is

**Comment by andris155** [comment]
Már van ilyen plugin a szervereken. Mi értelme ennek így? Ráadásul ez ingyenes is.
https://dev.bukkit.org/projects/shopkeepers

A ShopGUI+-al lehetne jó boltot csinálni, de mivel csak konfiggal lehet beállítani nem valami jó az adminoknak.

**Comment by Laci444** [comment]
Nem releváns
