### ISSUE TITLE
Old Creative Bug

### ISSUE THREAD

**Issue by I3alaa** [TheOld-Crafters/Minecraft-servers#4799]
Szerver: **Survival**

Hiba:
Old Creative módban, ha egy trapdoor-ra (csapóajtóra) rakunk egy táblát, akkor kidob a szerver **Packet Processing Error**-al.
BlackLightniing próbálta, de sima Creative-ban nem re-produkálható, csak a korlátozott Old - Creative módban.

https://youtu.be/_QyyfW48Tk0

**Comment by Denzen08** [comment]
Helló!

Sajnos nem tudtam reprodukálni az esetet, gondolom a Minecraft klienseddel lehetett a probléma.

Üdvözlettel, Denzen

**Comment by Laci444** [comment]
Sajnos ezt a problémát nem tudtam orvosolni. Vagy a Paper vagy a ViaVersion okozza, és csak abban reménykedhetünk, hogy egy jövőbeli verzióban már javítva lesz a hiba
