### ISSUE TITLE
Nem létező warp

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4800]
SF-Survival

A Spawnon az első dolog amibe belefutunk az egy /warp újvadon tábla. Ez nem létezik, mivel vadon és lootvadon warpunk van. Le kéne ütni, módosítani kéne.
A problémát Jegesdi vette észre.
![image](https://user-images.githubusercontent.com/60291809/138590939-ffb94de7-2841-4dfd-876a-a3c3f93675f1.png)

**Comment by MrZero1** [comment]
Javítva, köszi!
