### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4801]
![2021-10-25_14 08 02](https://user-images.githubusercontent.com/74869381/138692288-e4a2090b-1763-4b12-99f3-c4fa62ff925f.png)

Andris csinált valamit hogy vadonból a tüzek elaludjanak, gondolom ez amiatt van.

**Comment by MrZero1** [comment]
Köszi a jelentést! Javítva.
