### ISSUE TITLE
Hibás fordítás/Elírás

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4804]
szerver: Old village
Ha teleportálni akarok (én a /k home parancsot használtam) és megszakítom pl mozgással akkor az alábbi szöveget írja ki:
A teleportlálás megszakadt! "teleportálás" lenne a megfelelő.

**Comment by MrZero1** [comment]
Javítva. Ha van még elírás, jelezd. köszi!
