### ISSUE TITLE
Elásott kincses térkép

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4805]
szerver: Old Village
A probléma, hogy a szerezhető térképen lévő sablon domborzat közel se egyezik meg a valós domborzattal. Emiatt például jelezte olyan helyre az X et, ahol 30 block mélly óceán volt. Én ott elszenvedtem, leáskálódtam, nem találtam semmit. 3 probálkozásból (3 különböző helyen) 1 alkalommal találtam (némi segítséggel) ládát. Alább a térkép sablonos, és részlegesen felfedezett kinézete:

![2021-12-08_01 58 00](https://user-images.githubusercontent.com/60291809/145131370-d1389461-352c-4945-9eb1-e16091179014.png)

![2021-12-08_02 09 19](https://user-images.githubusercontent.com/60291809/145130982-00323eb8-650a-42d5-87c7-04389a81bac5.png)

Ötlet: A hibás kincsestérképek/nemtalálható kincsek pótlására be lehetne rakni mobdrop vendorhoz a "Tenger Szíve" nevü itemet, ritkaságának megfelelően magas áron (korlátozott mennyiségben elérhető). Alapvetően ezért keresik az emberek csak a kincseket.

**Comment by Laci444** [comment]
Ez a hiba fennáll a többi szerveren is? Ha igen, akkor valószínűleg minecraft hiba lesz, ha csak OV-n akkor valamelyik plugin bekavarhat.

**Comment by Ziredus** [comment]
Emlékeim szerint anno SF-survival/Survival szerveren ilyen problémát nem tapasztaltam. Bár utoljára kincset akkor kerestem rajtuk amikor még nem volt loot vadon, szóval egy pár kieggel ezelőtt. Lootvadonban meg ha azóta nem lett módosítva semmi, akkor egyáltalán nincsenek kincses térképek, kincsek.

**Comment by Laci444** [comment]
Bocsi a késői válaszért!
Ha leteszteled a többi szerveren és ott is fellép a hiba, utána nézek, ha csak OV-n tapasztalod, azzal nem szeretnék foglalkozni, mivel annak nem igazán látom át a pluginjait, hamarosan egyénként is búcsúzni fogunk tőle a jelenlegi formájában.

**Comment by Ziredus** [comment]
Ránéztem SF survivalon, A sablon térkép domborzata itt is eltér a tényleges domborzattól mint ahogy a fennti két képen látható.
