### ISSUE TITLE
Nem müködő menüpont a bankban

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4806]
szerver: Old Village
A bankba betehetem az összes pénzem, a pénzem felét, de egy általam megadott random összeget nem. a menüre hiába kattintok nem történik semmi.
![2021-12-08_04 50 35](https://user-images.githubusercontent.com/60291809/145145309-1cba3bcc-6e07-4e63-8d42-d0393c000d7d.png)

**Comment by Denzen08** [comment]
Helló!

Új bankrendszer van már bent azóta.

Üdvözlettel, Denzen
