### ISSUE TITLE
Nem müködő warp parancs

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4807]
szerver: Old Village
A /warp (bank, bánya, etc...) parancsok beírásakor nem dob el a célhelyre, helyette vmi vacak menüt dob fel.
![2021-12-08_04 53 51](https://user-images.githubusercontent.com/60291809/145145527-af44ef18-a429-40a4-993c-5bedf9974ab5.png)

**Comment by UDPSendToFailed** [comment]
A /ewarp működik

**Comment by Ziredus** [comment]
a /warp is müködik már.
