### ISSUE TITLE
Hiba OV

### ISSUE THREAD

**Issue by TheNandoX** [TheOld-Crafters/Minecraft-servers#4808]
1) kiszállás a hajóból kiírja, hogy Your Teleport was a success 
2) Spawnon lehet királyságot csinálni
3) Spawnon van falldamage
4) Spawnon van éhezés
5) Spawnon aukciós bábú nem működik
6) Spawnon hentes bábú nem működik
7) Spawnon a farmon nem lehet állatokból kiverni a sz4rt se
8) Spawnon a bankár se müxik
9) Spawnon a varázsló se müxik
10) Ha túl nagyot esel, vagy belaggolsz kiírja hogy  Your Teleport was a success

**Comment by Denzen08** [comment]
Helló!

A hajós dolog megoldva!
A kezdőhelyen már nem lehet királyságot létrehozni!
A kezdőhelyen nincs már falldamage.
A kezdőhelyen nincs már éhezés.
A kezdőhelyen az aukciós babú már működik.
A kezdőhelyen a hentes előtti block-ra kell kattintatni!
A kezdőhelyen az állatokat most már meglehet ölni.
A kezdőhelyen a bankár már működik.
A kezdőhelyen a varázsló csak dísz, ezért nem is fog működni.
A nagy falldamage után nem írja azt a szöveget.

Üdvözlettel, Denzen
