### ISSUE TITLE
Ov hibák

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4809]
**Szerver**: OldVillage

Valszeg bővülni fog

-/ah-hoz nincs jog, csak a /ahaz-hoz van (barkácsoló rangú vagyok)
-/ranks-hoz nincs jog, csak a /ranks2-höz
-Ha a /warp ládák-nál ki akarsz nyitni egy ládát, de nincs kulcsod, angolul írja ki a cucclit
-Kittinek Lord rangosként nincs joga semmilyen kithez, nekem barkácsolóként van jogom a craftsman kithez (lord ugye sokkal nagyobb rang)

Ami kéne:
-Login szeróra OldVillage NPC
-Tabon kiírni a többi szerón lévő játékost, mint mindenhol máshol

**Comment by Denzen08** [comment]
Helló!

/ah illetve a /warp ládák probléma megoldva!

Az első oldalhoz /rangok paranccsal lehet eljutni, /rangok2 paranccsal pedig a 2. oldalra lehet eljutni

A kites téma hamarosan meg lesz oldva, a rangokat át kell dolgozni (Nem lesz új neve, csak van 1-2 bug benne)

Login szerón már van OldVillage NPC
Tabon is írja már hogy hányan vannak fent

Üdvözlettel, Denzen
