### ISSUE TITLE
Levédés kitiltás ellenére visszajövetel

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4810]
**Szerver**: Survival

Ha egy levédésről a /gpflags SetClaimFlag NoEnterPlayer *player* paranccsal kitiltok egy playert, azaz meggátolom, hogy betegye a lábát a levédésre, akkor is be tud buggolni. Poéldául az egyik levédésemről kitiltottam xX_Nando_Xx játékost, és pár perc múlva újra a házban szaladgált. Csatolom a képet, a saját bevallása szerint így oldotta meg:
![nando](https://user-images.githubusercontent.com/67922620/146686638-44956d3f-7eb9-47da-a871-8bb7faf2b0b6.png)

**Comment by Denzen08** [comment]
Helló!

Sajnos nem tudtuk a buggot reprodukálni, van rá elmélet hogy mi okozhatta, de ha máskor bejön szólni kell egy staff-nak.

Üdvözlettel, Denzen

**Comment by Squidmanus** [comment]
Hali! Sizarrával reprodukáltuk a hibát, elég a levédés szélén spamelni a shiftet és a spaceszt. 
Szerintem úgy lehetne ezt megoldani, hogyha hozzáér a levédés széléhez, akkor hátradobja egy kicsit, mivel a bugnak kell legalább 5mp.

**Comment by Sizarra** [comment]
https://www.youtube.com/watch?v=Gc3x4GLp848

Itt van a videó, remélem normálisan látszik, hogyan kell bejutni. Valamikor shift+space csapkodása (miközben fly be van kapcsolva, fly nélkül nem ment.), valamikor meg elég simán csak a spacet nyomkodni.

**Comment by Denzen08** [comment]
Helló!

Utána néztem máshol is, hogy ez csak nálunk van-e, de sajnos nem. Ha sokat erőlködik az ember, ezek szerint be lehet "törni" egy olyan helyre, ahol ki van tiltva.

Szóljatok egy Staff-nak ha ez megtörténik!

Üdvözlettel, Denzen
