### ISSUE TITLE
Survival szavazói hiba

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4811]
**Szerver**: Survival

Ha a lootvadonban szavazok, megkapom a pontokat, de a pénzt és a fortunakulcsokat nem. 4x szavaztam, nem kaptam se kulcsot, se pénzt, aztán elmentem a sima vadonba lévő homeomra, és kaptam 2 kulcsot.

**Comment by MrZero1** [comment]
Javítva, köszi!
