### ISSUE TITLE
Survival explosive arrows hiba

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4812]
**Szerver**: Survival

Ha egy Explosive Arrows enchanttal ellátott íjjal más területén meglövök egy mobot, ugyanúgy van esély a terület felgyulladására, és ezáltal meg lehet ölni más játékosokat. Példa: egy blazefarm mellett áll a player, meglövöm az épp lefelé érkező blazeket az íjjal, és felgyullad a terület -> meghal a játékos.

**Comment by TheNandoX** [comment]
megérdemled

**Comment by MrZero1** [comment]
Az  explosive_arrows enchant letiltásra került, holnaptól nem lesz elérhető.
