### ISSUE TITLE
Survivalon anticheat hiba

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4816]
**Szerver**: Survival

Ha playerre magasugrás III vagy annál nagyobb effekt kerül, magad alatt nem tudsz blokkot pakolni miközben ugrálsz, visszadobál,
eleve ugrálásnál is visszadobál néha. Ha meg launcholni szeretném magam tűzijátékkal, miközben elytrával repülök, néha nem enged tovább, megállít egyhelyben, amíg tartana a tűzijáték launcholása.

**Comment by Denzen08** [comment]
Helló!

A magasugrásos dolgot leteszteltük, nem dobta vissza a Tesztert. Ez lehetséges hogy akkor laggoltál.

Az "elytrás" dolog viszont sajnos erre nincs megoldás jelenleg, néha megfog állítani, néha nem. Javasolt hogy a tűzjátékot ne spameld és nagyobb eséllyel nem fog megállítani.

Üdvözlettel, Denzen
