### ISSUE TITLE
Survival warp vég struktúra károsodás

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4817]
**Szerver**: Survival
**Hatókör:** Vég dimenzió
Játékosnév: Vdsz

Survival szerveren a */warp vég* struktúrába belegenerál *End Gateway* az Endersárkány megölése után, így károsítva a struktúrát.
Fotók:
![2021-12-21_22 03 57](https://user-images.githubusercontent.com/68443484/147001609-842a196b-b24d-4fd4-8aca-35653a39eb0c.png)
![2021-12-21_22 03 32](https://user-images.githubusercontent.com/68443484/147001640-006be770-f26e-474e-a06b-9abb68a19067.png)
![2021-12-21_22 06 10](https://user-images.githubusercontent.com/68443484/147001658-2206d585-f4e8-478b-856b-7067a060c1c2.png)

**Comment by MrZero1** [comment]
Javítva, köszi! 
Jelentés kulcsot adtam érte.

**Comment by VdszHun** [comment]
Nincs mit és köszönöm! ^^
