### ISSUE TITLE
emf shop elírás

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4818]
**Szerver**: Survival
**Hatókör:** Mindenhol ahol használható a plugin
Játékosnév: Vdsz

Az */emf shop*-ban az *Összes eladása* helyett *Össesz eladása* van írva.
![2021-12-21_22 30 57](https://user-images.githubusercontent.com/68443484/147002453-97b2b6a1-b7bf-491c-9ca3-8fcdfeeaedbe.png)

**Comment by MrZero1** [comment]
Javítva, köszi!

**Comment by VdszHun** [comment]
Nincs mit! ^^
