### ISSUE TITLE
elitemobs rangok stackelhetőségi hiba

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4819]
**Szerver**: Survival
Játékosnév: Vdsz

Ha különböző ranggal szerzel az Elitemobs pluginból egy olyan kincset ami stackelhető, pl. Merchant Scroll (papírok) ezek a stackelhető kincsek nem fognak stackelődni, csak a saját rangjaikkal.
A fotókon lehet látni, hogy van 8 darab **[Tag]** ranggal szerzett Merchant Scrollom, és 4 **[V.I.P.]** ranggal szerzett, de ezek nem tudnak egymással stackelődni.
Fotók:
![2021-12-21_22 21 00](https://user-images.githubusercontent.com/68443484/147003145-f7195205-ba05-48a2-9ac9-81070579a801.png)
![2021-12-21_22 21 03](https://user-images.githubusercontent.com/68443484/147003160-b29fae97-8c5f-411d-af96-e89c84cedb6e.png)

**Comment by MrZero1** [comment]
Ez azért nem vélem hibának, mert különböző NBT tag lesz rajta, attól függően, hogy milyen rangod van, vagy hogy hanyas szintű vagy. Így ezt lezárom.

**Comment by VdszHun** [comment]
Értem és rendben.
