### ISSUE TITLE
Flag, láda levédés ütközés

### ISSUE THREAD

**Issue by Jaffis** [TheOld-Crafters/Minecraft-servers#4820]
Ha táblával lockolunk egy ládát, de a levédésen belül engedélyezve van a viewcontainer flag, akkor a lockoltba ugyanúgy bele lehet nézni, mint a simába.

**Comment by Denzen08** [comment]
Helló!

A ViewContainer flag-el okés hogy beletudnak nézni, de a láda tartalmát módosítani nem tudják, illetve azzal az információval hogy most abban a ládában van valamid nem mennek sokra, mivel nem tudják kivenni.

Üdvözlettel, Denzen
