### ISSUE TITLE
Mobaréna - Hungergames ütközés

### ISSUE THREAD

**Issue by TheNandoX** [TheOld-Crafters/Minecraft-servers#4821]
**Szerver**: Survival

1) Ha belépsz a mobarénába (/ma join (map)), majd kilépsz onnan (/ma leave) és belépsz egy HungerGames pályára amíg a mobaréna lobbyban vagy, majd beírod a /hg leave parancsot, aztán a /lobby parancsot és visszalépsz a szerverre szabadon tudsz mozogni a hungergames pályán anélkül hogy elindult volna.

2) (ugyanez megtörténik  csak a /hg leave parancs használata nem és a /lobby sem) Ha elindul egy hungergames meccs és megölnek, akkor azon cuccaidban, amelyek hg előtt voltak rajtad ugyan azon a helyen ahol megöltek respawnolsz bennük.

**Comment by MrZero1** [comment]
Ezek a lehetetlen hibák, amiket épeszű ember nem próbálgat. Esetleg jelentsd a minigame fejlesztőknek, bár 1.18-ra a jelenlegi HG nem lesz.

**Comment by Laci444** [comment]
Javítva:
> tiltva a hg parancsok hozzáférése az adott helyeken
