### ISSUE TITLE
Nyeremények

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4822]
**Szerver**: Survival

A /eventtopten nyertese kaphatna 512 tokent hó végén.
A top1 havi szavazó kaphatna szavazói pontot, vagy szavazói kulcsot.
A napi eventeken a nyereményes ládából 3 helyett 4 token legyen kapható, jobban lenne kezelhető.

**Comment by Sanszi** [comment]
Esetleg inkább ocd-t.

**Comment by Laci444** [comment]
Inaktivitás miatt lezárom
