### ISSUE TITLE
Láthatatlan ezközkeret hiba

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4823]
**Szerver**: Survival

Hogyha egy láthatatlan ezközkeretből ki szeretnék ütni a tárgyat, van, hogy teljesen elbuggol. Ez történt velem, meg a mini karácsonyfámmal, csengettyűmmel és csúcsdíszemmel(ezek a téli beváltóstól származnak), mikor kiszedtem őket a láthatatlan ezközkeretből.

**Comment by MrZero1** [comment]
Nem sikerült megismételnem, nekem megadta folyamatosan. Videót tudsz esetleg csinálni, vagy valami pontosabb leírást írni.

**Comment by Denzen08** [comment]
Helló!

A probléma megoldva, szimplán csak szét kell bontani mindent. Igaz elég nehézkes egy földalatti bázisban, ott jobban odakell figyelni!
