### ISSUE TITLE
/team warp hiba

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4826]
**Szerver**: Survival

Ha a /team warp után írunk bármit, minden egyes betűre kiírja ezt:
![Képernyőfelvétel (954)](https://user-images.githubusercontent.com/67922620/147680255-2faa151d-772c-4a56-ac6c-0821db144f6f.png)

**Comment by Laci444** [comment]
Szia! Tudnál légyszi küldeni egy pontos időt?

**Comment by Laci444** [comment]
Ez már tisztázódott
