### ISSUE TITLE
Rulett

### ISSUE THREAD

**Issue by Sizarra** [TheOld-Crafters/Minecraft-servers#4828]
**Szerver**: survival

A rulettasztalból kivenni az All-in lehetőséget. Megmaradna a maximum 100k tét, így talán nem fog annyira felszaladni a pénz 1-1 játékosnál.

**Comment by Squidmanus** [comment]
Ezt is csak miattam írtadxdd de amúgy igen, felvetettük már az ötletet.

**Comment by Sizarra** [comment]
> 



> Ezt is csak miattam írtadxdd de amúgy igen, felvetettük már az ötletet.

Nem miattad írtam, magam miatt. Nem tudom, hogy te mondtad-e és ha igen, mikor.

**Comment by Vace04** [comment]
**Meleg sq**

**Comment by Laci444** [comment]
A plugin testreszabhatatlansága miatt nem fog visszakerülni
