### ISSUE TITLE
/vote parancs visszajelzés/timer hiba

### ISSUE THREAD

**Issue by Kiphleee** [TheOld-Crafters/Minecraft-servers#4829]
Survival:

*/vote parancsnál a középső 2 timer nekem nem működik, ződen jelzi de pirosnak kéne jeleznie mert már szavaztam.:*

![2022-01-05_00 24 28](https://user-images.githubusercontent.com/24234342/148137421-e46cdb3c-e942-414d-aec4-218f7c26eaf1.png)
![image](https://user-images.githubusercontent.com/24234342/148137471-d7d260f1-5edb-49ff-9897-ad53ae026fff.png)
![image](https://user-images.githubusercontent.com/24234342/148137502-4e38259e-9cfa-4609-8041-9d897ffba617.png)
Nálam csak a minecraft-mp.comon és minecraftservers.orgon jelentkezett 

> *Dátum és idő:*
2022.01.05 0:23

**Comment by MrZero1** [comment]
Nekem jó a középső kettő, lezárom.
