### ISSUE TITLE
Vote oldalak hiba

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4831]
**Szerver**: Vote oldalak

*Út a hibához:*
Nemtudom ez mennyire hiba, meg mennyire szándékos, de a vote oldalak még mindíg azt írják, hogy MrZeri az owner.

![Képernyőfelvétel (967)](https://user-images.githubusercontent.com/67922620/148283301-45712a1f-f6f2-4615-9b08-9ff806dc0fd6.png)

> *Dátum és idő:*
2022.01.05

**Comment by MrZero1** [comment]
Mivel az én fiókomban lett létrehozva, így nyilván engem ír. És ha esetleg nem térnék vissza, majd átadom a többieknek, de egyelőre csak pihenőn vagyok. 🙂

**Comment by Laci444** [comment]
Reméljük, hogy Zeri visszatér és nem kell ezekkel foglalkozni 😊
