### ISSUE TITLE
Lootvadon fejlesztes

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4832]
**Szerver**: Survival

Nemtudom mennyire módosíthatjátok a plugin tartalmát, de ha van erre lehetőség, akkor a - majd 1.18-as szerverfrissítés után legenerált - lootvadonban a fák NE fa BLOKKBÓL hanem fa RÖNKBŐL épüljenek fel, mivel a jobs a fablokkra nem ad se pontot se xp-t se pénzt, csak a rönkre, és így jelenleg nem nagyon van lehetőség favágó jobsra fejlődni (így is van, de elenyésző).

**Comment by MrZero1** [comment]
Én lootvadonnak 1.18-as világot is el tudnék (majd) képzelni

**Comment by UDPSendToFailed** [comment]
Pro tipp: Favágó munkához sokkal egyszerűbb hozzáadni a hiányzó blokkokat, mint állítgatni a generálást.

**Comment by Laci444** [comment]
Javítva
Köszi a jelentést!
