### ISSUE TITLE
Survival flag hiba

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4833]
**Szerver**: Survival

*Út a hibához:*
Ha be van kapcsolva egy levédésen a ViewContainers flag, és valaki belenéz a ládába, az ő chatjére úgyanúgy minden egyes belenézésnél kiírja a chat, hogy ehhez nincs joga, és hogy kérjen engedélyt xy-tól.
Nemtudom, hogy ez más flageknél jelentkezik-e, de érdemes kipróbálni, elég zavaró ez a floodolás.

> *Dátum és idő:* 2022.01.07 21:34

**Comment by Laci444** [comment]
A DC-n megbeszéltek alapján lezárom, változtatás nem történt.
Köszönöm a jelentést!
