### ISSUE TITLE
Plot letöltés hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4836]
**Szerver**: Survival, SFSurvival

**Út a hibához:**

/p download, normál esetben egy linket kéne adnia, ahol le lehet tölteni a telket .schematic fájlban

![image](https://user-images.githubusercontent.com/16057404/149225604-3c3e10cf-e322-4269-8790-91001c523d67.png)

**Dátum és idő:**

2022-01-12 22:39:23

**Comment by Laci444** [comment]
Utána néztem a hibának, úgy néz ki hogy valami memóriakezelési probléma a weboldalon. A jogoknak semmi köze ehhez, a weboldal nem tudta feldolgozni a feltöltést. Nyitottak egy pull requestet a plugin guthub oldalán, ami megoldja a hibát néhány memóriakezelési javítással és js helyett ts használatával, de még nem fogadták el úgyhogy nem fog megoldódni egyhamar.

Ha ilyen problémát észlel valaki, várjon vele egy kicsit, esetleg következő nap próbálja újra.
