### ISSUE TITLE
Zavaró szövegek

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4837]
Survival/Sfsurvival.

Eventeken és a spawn világban, ha playert ütsz vagy blokkot próbálsz törni, szerintem felesleges kiírnia az "Ezt nem teheted meg", "Sorry, but you can't pvp here" szöveget a chatre.

**Comment by Laci444** [comment]
Javítva
Köszi a jelentést

UI.: Ha a jövőben valahol még lenne üzenet, ahol nem kellene akkor lehet kihagytam. Kérlek jelezzétek ha ilyennel találkoztok!
