### ISSUE TITLE
Kreatívban is működik a skill.

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4838]
**Szerver**: Survival

*Út a hibához:*
Ha az old rangommal gm1-ben vagyok, és például egy vadonban generált követ ütök ki, akkor is ad skillre pontokat.
Ezzel farmolni lehet a skillt, ami elég nagy előnyökhöz vezet, mindezt kb 0 munka befektetésével.

> *Dátum és idő:*
2022.01.17 19:54

**Comment by Laci444** [comment]
Javítva
Köszönöm a jelentést!
