### ISSUE TITLE
Kreatív bolt tábla

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4839]
**Szerver**: Survival

*Út a hibához:*
Ha kretívban teszek le táblát, és boltot csinálok vele, majd az item nevét szándékosan elírom, akkor ugye a tábla kidobódik, és ezzel végtelen mennyiségű táblát tudok addolni.

> *Dátum és idő:*
2022.01.17 19:55

**Comment by Laci444** [comment]
Sajnos semmi ötletem, hogy hogyan lehetne megoldani a problémát! :(
