### ISSUE TITLE
Spleef hógolyó droppolás kikapcsolása

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4840]
**Szerver**: Survival

Ha kiütik a hóblokkot, ne dobjon havat, mert nagyon laggoltató, durva fps droppot kapok tőle, és sztem nem csak én vagyok ezzel így.
(Nyilván ha valami nasa géped van, nem érzed át, én csak egy egyszerű laptopon tolom az mc-t)

**Comment by MrZero1** [comment]
Erre nem igazán van megoldás. Event közben a staff tudja törölni, érdemes neki jelezni hogy törölje.
