### ISSUE TITLE
Mob spawnolás spawnon

### ISSUE THREAD

**Issue by WolterFox** [TheOld-Crafters/Minecraft-servers#4841]
**Szerver**: Survival

*Út a hibához:*Mikor leraksz mob spawneggeket a spawn környékén, először látva a ládák warpon.

Őszintén ötletem sincs miért lehet ez. Talán nem volt kikapcsolva a mob spawning.

nem tudok :(

> *Dátum és idő:*2022.01.18, este 8 óra 14 perc

**Comment by TheNandoX** [comment]
nub

**Comment by MrZero1** [comment]
Kikapcsoltam a mob spawnolást a spawnon, egyedül a farmon spawnolnak az állatok.
