### ISSUE TITLE
Survival jobs oldos jobs hiba

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4842]
**Szerver**: Survival

*Út a hibához:*
Az OLD ranghoz jár minden jobshoz +16% pont és XP. Ám ugye péntektől vasárnapig +100% jár a pénzre és az xp-re.
Na most, ha összeadjuk, akkor nekem az OLD ranggal, péntektől vasárnapig +100% pénz, +16% pont és +116% xp-nek kéne járnia,
viszont a /jobs bonus Bányász az xp-re csak +115%-ot ír.

![image](https://user-images.githubusercontent.com/67922620/150570215-cbddb90c-d7ab-4b8a-a83b-35e9af6cd230.png)

> *Dátum és idő:*
2022.01.21 18:11

**Comment by MrZero1** [comment]
Elvileg a jog megvan adva rendesen Oldnak, így nem tudom mi az oka. Lehet a szöveg hibás. Megkellene nézni, hogy százalékban valóban megadja e a jót, vagy nem. Vagy valami limit, nem tudom pontosan.
