### ISSUE TITLE
Paintball kilépés elveszi az xp szintet

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4844]
**Szerver**: Survival

/pb leave után nem tűnik el a scoreboard, és az xp szintet is nullázza.

Update: Mindig pontosan 7 xp-t ad vissza, ha ennél több van a playernél, jön a hiba kilépéskor.

![image](https://user-images.githubusercontent.com/16057404/150870572-cb6437aa-892d-4852-a59c-3b34943d2a39.png)

```
2022-01-24

[20:10:45] [Render thread/INFO]: [CHAT] A táskád visszaállítva
[20:10:45] [Render thread/INFO]: [CHAT] An internal error occurred while attempting to perform this command
```

**Comment by MrZero1** [comment]
Nekem jó, nem tűnik el az XP. A scoreboard hiba pedig létezik, néha ott marad, nem tudok vele mit csinálni. Relog után elvileg eltűnik.
![kép](https://user-images.githubusercontent.com/29709854/166152782-261df3f7-fdbd-4c49-8e88-164c807377ae.png)
