### ISSUE TITLE
Survival víz, porhó addolása

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4845]
**Szerver**: Survival

*Út a hibához:*
Ha üstbe teszel vizet/porhavat, akkor survivalba ki lehet szedni vödörrel.
Plusz ha sima porhavat teszel le a földre üst nélkül, azt is fel lehet venni survivalba.

> *Dátum és idő:*
2022.01.25 15:58

**Comment by Laci444** [comment]
Köszi a jelentést!
Javítva
