### ISSUE TITLE
Survival portál kreálás levédésen

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4847]
**Szerver**: Survival

*Út a hibához:*
Ha egy másik ember által levédett területen belül lévő koordinátát elosztasz 8-al, és a netherbe megépíted a kapott koordinátára a nether portált, akkor a másik levédésére le fog generálni egy portált, ezzel lehet trollkodni,  belerondítani mindenbe, akár chesteket is szétrombolhat.

> *Dátum és idő:*

**Comment by Laci444** [comment]
Erre a problémára nincs megoldás :(
Köszi a jelentést!
