### ISSUE TITLE
Survival kő addolás

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4848]
**Szerver**: Survival

*Út a hibához:*
Ha Oldos gm1-ben leteszek egy sima követ, majd old csákánnyal kiütöm gm0-ba, megkapom.
Nemtudom, hogy ez a skill miatt van-e, de nemhinném, mivel minden egyes letett sima követ megkaptam

> *Dátum és idő:* 2021.09.29 12:16

**Comment by IciAlex** [comment]
Ez nem hiba.

**Comment by Laci444** [comment]
Nem hiba, a lag és az adatbázim méretének csökkentése érdekében a kreatívban letett dirt és stone blockokat kidobja.
