### ISSUE TITLE
Bolt vásárlás

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4849]
**Szerver**: sfszurvi

*Út a hibához:* 

> *Dátum és idő:*
ahj de sok a csilagozott rész, ki se igazodok.
ma, valaki vásárolt boltomban és amikor kiírja a chat, h xy vásárolt, akkor szar a kiírás.
Kiírja a színkódot. Pl &a[Bolt] Lajos vásárolt

**Comment by MrZero1** [comment]
Képet csatolj már légyszi, nem igazán értem így

**Comment by IciAlex** [comment]
Csak annyi hogy nem működnek a színkódok

&a[Bolt]&f xyz

**Comment by Laci444** [comment]
Nem sikerült reprodukálnom a hibát. Ha esetleg a jövőben újra jelentkezik, nyiss új issuet
