### ISSUE TITLE
Survival sit fly 

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4850]
**Szerver**: Survival

*Út a hibához:*
Ha például egy fallout eventen épp piros alattad a blokk, és te beírod a /sit parancsot, akkor ha eltűnik a blokk, a levegőbe ülve maradsz. Stabil a képernyő, nem buggos, és még be se jelez(tesztelve minden).

Szerintem minden /sit , /spin meg ilyen parancsokat le kéne tiltani eventvilágba.

![2022-02-02_19 48 46](https://user-images.githubusercontent.com/67922620/152219080-1a00d195-adbc-4150-93fb-99537d8b241d.png)

> *Dátum és idő:*

**Comment by Laci444** [comment]
Javítva
Köszi a jelentést!
