### ISSUE TITLE
Survival nyil felvétel

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4853]
**Szerver**: Survival

*Út a hibához:* Player által kilőtt nyilat fel lehet venni kreatívban, és lehet hogy kell még a playernek. 
(ez lehet hogy nem hiba, de vace szólt hogy jelentsem, szóval a károgók ne kommenteljenek köx)

> *Dátum és idő:*

**Comment by Laci444** [comment]
Sajnos ennek a megakadályozására nincs lehetőség a pluginban :(
