### ISSUE TITLE
Nem tudok belépni.

### ISSUE THREAD

**Issue by WolfDatka** [TheOld-Crafters/Minecraft-servers#4855]
Hello kedves support

Én NAGYON régen játszottam oldcrafters-t és most újra szeretnék, de nem tudok belépni mert megváltoztattam a nevem egy ideje és most már nagy d-vel írom és azt mondja hogy nem tudok belépni.
Ki tudnád törölni a serverből az accauntom-at, vagy valami?
ign: WolfDatka

Előre is köszönöm.

**Comment by Laci444** [comment]
Megoldva.

> Driver által
