### ISSUE TITLE
Bedrock/Win10 Edition proxy

### ISSUE THREAD

**Issue by GhostTriggerGT** [TheOld-Crafters/Minecraft-servers#4856]
**Szerver**: Login
**Kliens:** Windows 10 Edition / Bedrock Edition
**Út a hibához:** Szerverhez való csatlakozás.

Csatlakozás után többé már nem jelenik meg a felhasználónév beállítása gomb. Ez eddig működött, de valamilyen oknál fogva nem jön már fel a prompt. _Ez azért lenne fontos, mert sok embernek nem egyezik a java-s neve a más kiadásokkal, főként az Xbox Gamertag végett._

Első csatlakozás után a szerver kidobja a játékost a szerverről Discord megerősítés révén. Ez a kód fent említett klienseken már nem jelenik meg, szöveget levágja.

**Comment by Laci444** [comment]
Javítva
