### ISSUE TITLE
Ha a Bestia Mester nevű boss megöl valakit és felveszi a szettjét, majd maghal a szett eltűnik.

### ISSUE THREAD

**Issue by easymacro** [TheOld-Crafters/Minecraft-servers#4858]
**Szerver**:

*Út a hibához:*

> *Dátum és idő:*

**Comment by MrZero1** [comment]
Jelentettem a fejlesztőnek, majd megmondja, hogy ez normális dolog, vagy esetleg hiba. Keress egy admint, aki a fontosabb cuccokat visszaadja addig is. Köszi!
