### ISSUE TITLE
Survival telekvilág alja

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4859]
**Szerver**: Survival

*Út a hibához:*
  Ha egy embert a /p kick paranccsal kickelek a telkemről, akkor a telekvilágban a spawn alá dobja be.
  Többször is leteszteltük, és mindig oda dobott.

![image](https://user-images.githubusercontent.com/67922620/155218231-3a4d356e-6d89-4476-8668-50131f50de65.png)

> *Dátum és idő:* 2022.02.22 21:57

**Comment by MrZero1** [comment]
Megoldva, bár nem a legjobb megoldással..
