### ISSUE TITLE
Skyblock end portál item duplikálása

### ISSUE THREAD

**Issue by Ftcsabi** [TheOld-Crafters/Minecraft-servers#4860]
.

**Comment by MrZero1** [comment]
A hibát elmentettem, igyekszem utánajárni. A játékosnevedet kérlek írd le, valamint a duplikált itemeket töröld. Köszi!

**Comment by Ftcsabi** [comment]
Tech karakterrel vagyok. Elvileg kidobáltam mindent a voidba. Mondjuk nem emlékszem a pontos itemekre. Esetleg egy mai napi resetet kapok? Mert akkor biztosabb h az marad ami volt.
