### ISSUE TITLE
Jobs bővítés

### ISSUE THREAD

**Issue by Gaborterminator** [TheOld-Crafters/Minecraft-servers#4862]
**Szerver**:Survival

A Sweet berries felvétele a földműves munkához kiütések után.
Az érték lehetne ugyannyi mint a búza, répa stb. esetében.

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/167255068-87afeb9d-1a58-4e9e-bab0-2564eaec72ff.png)
Ha minden igaz, most már elérhető.
