### ISSUE TITLE
A Bunny Hop III enchant a viseléskor nem ad állandó effektet.

### ISSUE THREAD

**Issue by HexonH** [TheOld-Crafters/Minecraft-servers#4863]
**Szerver**: Survival

*Út a hibához:* A gyémánt cipőmön lévő Bunny Hopp aktiválódik 9 mp-re. A számláló letelésekor nagyjából 15-20mp-nek kell eltelnie, hogy újra aktiválódjon az enchant. (Az enchant leírása: Viseléskor állandó jump 3 effektet biztosít) A hibát a lentebbi you tube linken lehet megnézni.

 https://youtu.be/WM9fS4j1onU

> *Dátum és idő:* 2022.03.20 13:43

**Comment by MrZero1** [comment]
Frissítésre kerültek ezek az enchantok. Ha továbbra is fennáll, jelezd kérlek ismételten, ha videót is tudsz, akkor azt is linkelj megint. Köszi! (:
