### ISSUE TITLE
Savsziget ingyenes ládakulcs spawn védelem hiba

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4865]
**Szerver**: OldBlocks - Savsziget

*Út a hibához:* Savsziget láda warpja
Az OldBlocks szerver Savsziget módjának láda warpján nem lehet kinyitni a 8 óránkénti ingyenes Nexus kulcs ládáját mert spawn védelem alatt van. Ezáltal megakadályozva az ingyenes kulcs szerzését.

Valami okból spawn védelem alatt van a láda.

Képek:
![acid_island_chest_bug](https://user-images.githubusercontent.com/68443484/163673687-1b5e8c56-bb93-45c6-976c-3de75a411b07.png)
Helyszín:
![acid_island_chests](https://user-images.githubusercontent.com/68443484/163673695-34f0a791-1b61-4680-9033-ae2332aff73c.png)

> *Dátum és idő:* Sajnos nem tudom mióta állhat fent a hiba, főleg ha eddig senki sem jelentette.

**Comment by MrZero1** [comment]
Ez is megoldva! Köszi. :D
