### ISSUE TITLE
OldBlocks TOC egyedi kaptár

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4866]
**Szerver**: OldBlocks

*Út a hibához:* /receptek parancs vagy advanced crafting table
Az egyedi TOC Kaptár még használja Andris nevét mint tulajdonosét, miközben ő már nincs jelen mint tulajdonos, direkt maradt ott a neve, vagy el lett felejtve a kivétele? Bizonytalan vagyok, ezért jelentem itt.

Kép:
![andris_bee](https://user-images.githubusercontent.com/68443484/163673949-c510514c-48cf-4c1b-bd99-6771db3f60e1.png)

> *Dátum és idő:* Körülbelül fél éve

**Comment by MrZero1** [comment]
Habár nem nagy hiba, de módosítottam. :)
