### ISSUE TITLE
OldBlocks láda warpok duplaláda ötlet

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4867]
**Szerver**: OldBlocks

Az OldBlocks szerveren is van láda warp minden játékmódnál, mint minden más szerveren, viszont nincs egy duplaláda ahova be lehetne tenni azokat a ládás nyereményeket amikre neked nincs szükséged.
Minden más szerveren van egy duplaláda a láda warpnál ahova a játékosok be szokták tenni azt amire nincs szükségük, hogy más elvihesse akinek esetleg szüksége lehet rá.
Egy ilyen ládával megszűnne a szemetelés a láda warpokon és segítené is a játékosokat.

Képek Survivalról és SFSurvivalról:
![survival_doublechest](https://user-images.githubusercontent.com/68443484/163674425-14376ec6-f32b-4301-bd41-cbec8d0000a2.png)
![sfsurvival_doublechest](https://user-images.githubusercontent.com/68443484/163674427-471ffd5e-408f-4dcf-bde5-fcdaaa24c199.png)

Képek az OldBlocks láda warpokról (nincs duplaláda):
Sorrendben Savsziget, CaveBlock, OneBlock és SkyBlock
![acid_island_chests](https://user-images.githubusercontent.com/68443484/163674448-896b3e58-a3aa-46c7-a252-7892d83ed91d.png)
![caveblock_chests](https://user-images.githubusercontent.com/68443484/163674455-5f43b6b1-69de-4da4-bdfe-3405b5e1a23e.png)
![oneblock_chests](https://user-images.githubusercontent.com/68443484/163674471-7f0a5be0-c7c1-4681-a678-59e4a5f2e19d.png)
![skyblock_chests](https://user-images.githubusercontent.com/68443484/163674473-33045714-8158-4ae7-9160-03512e7e5e4c.png)

**Comment by MrZero1** [comment]
Köszi, raktam ki mindenhova közös ládát! :)
