### ISSUE TITLE
ChestTerminal addon kivétele

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4868]
**Szerver**: Teszt és SFSurvival

A ChestTerminal nevű Slimefun addon már nem támogatott és a Slimefun fejlesztői megkértek mindenkit arra, hogy minél hamarabb vegyék ki szervereikről, hogy ne okozzon további gondokat.

_A ChestTerminal addon fejlesztése azért lett abbahagyva, hogy jobb legyen a teljesítménye a Slimefunnak a jövőben. Elsősorban a cargo rendszereknek. Az Addon törlése utat nyit egy stabilabb Slimefunhoz rengeteg régi kód törlése miatt._
-TheBusyBiscuit szövege összefoglalva

Az Addon jelen van a **Teszt szerver**en, viszont nem tudom, hogy jelen van-e **SFSurvival**on is esetleg letiltott formában, meg kéne nézni és törölni mindkét szerverről.

Teszt szerver Slimefun verziója: **RC - 31 (git 0ea16bd1)**
Teszt szerver Minecraft verziója: **1.18.2-R0.1-SNAPSHOT**
SFSurvival szerver Slimefun verziója: **DEV - 1008 (git 020094e0)**
SFSurvival szerver Minecraft verziója: **1.17.1-R0.1-SNAPSHOT**

A **DEV-1014**-es verziótol kezdve nem támogatott és okozhat hibaüzeneteket.

A ChestTerminal addon:
![ChestTerminal_Addon](https://user-images.githubusercontent.com/68443484/166159965-ffd19f8b-db0d-4ab5-9169-7aa140dc34d2.png)
Az addon tartalma:
![ChestTerminal_Addon_Content](https://user-images.githubusercontent.com/68443484/166159970-54688434-deb2-4a5f-98ba-e8c3ecba52ac.png)
Hivatalos bejelentés a Slimefun Discord szerverén, megtalálható az #announcements csatornán.
Üzenet linkje: https://discord.com/channels/565557184348422174/565569425210867715/969548788911984680
![ChestTerminal_Discontinued](https://user-images.githubusercontent.com/68443484/166159971-54787306-d608-4cf1-8418-a6caf5ffd070.png)

**Comment by MrZero1** [comment]
Ezt kivettem.
