### ISSUE TITLE
Crystamae Historia Addon nem működik

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4869]
**Szerver**: Teszt Szerver

*Út a hibához:* Teszt Szerveren a Slimefun Guide használata

Ez az addon nem működik, egyáltalán nem nyitható meg a Slimefun Guideban így nem lehet tesztelni semmilyen formában.
KernelPanic segített nekem tesztelni és kideríteni az okát, nagyon köszönöm a segítséget! :)
Az addon ikonja dupeolható shift használatával, fotó lejjebb.

KernelPanic segítségének köszönhetően kiderült, hogy a Slimefun verziója le van maradva és az addon ez miatt nem tud betölteni.

Az addon:
![Crystamae_Historia_Addon](https://user-images.githubusercontent.com/68443484/166161083-47519bd6-1ec7-4054-848a-f757886d9c14.png)

Az ikonja dupeolható shift használatával:
![Crystamae_Historia_Addon_dupe](https://user-images.githubusercontent.com/68443484/166161108-1543b6ea-9fcf-4b42-ba19-b796ec46515a.png)

> *Dátum és idő:*
Nem tudom mióta lehet jelen a hiba

**Comment by UDPSendToFailed** [comment]
Új verzióhoz link: https://thebusybiscuit.github.io/builds/Sefiraat/CrystamaeHistoria/master/

**Comment by VdszHun** [comment]
Az addon frissítve lett kb egy hete, a gond mostmár megszűnt.
@MrZero1 kérlek lezárod ezt a jelentést?
