### ISSUE TITLE
Teszt szerver fejlesztési ötletek és hibák

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4870]
**Szerver**: Teszt szerver

Ez egy összefoglaló jelentés, hibák és ötletek is vannak benne.

1. Hiba:
A teszt szerveren a jelenlegi szervert az előző szerverként jelzi, ami ez esetben lehet a **Login** vagy **Lobby** szerver.
Mégegy hiba a játékoslistával, hogy nem jelzi a játékosok rangjait.
Fotó a hibákról:
![Present_server](https://user-images.githubusercontent.com/68443484/166165856-7f2ee05a-4864-4c55-84e0-32469343ce4a.png)
![Present_server2](https://user-images.githubusercontent.com/68443484/166165886-7f608700-80cb-41a5-af7d-bf5398a34691.png)

2. Hiba:
A Teszter rang egy színt használ, még minden más rang a szerveren többszínű, ennek az oka az lehet, hogy a teszt szerverre ritkán jár fel bárki és kimaradt a felújítása.
A fotón látszódik, hogy a Tag rang többszínű, még a Teszter egy színt használ.
![Teszter_rang](https://user-images.githubusercontent.com/68443484/166166184-ebee01e0-e28c-4d6f-9b33-40a2e5d95cd3.png)

1. Ötlet:
Minden szervernek van egy parancsos változata, amivel könnyedén át lehet menni egyik szerverről a másikra, de a Teszt szervernek nincs ilyen.
Példák:
/survival
/sfsurvival
/oldblocks
/oldvillage
A teszt szervernek nincs ilyen parancsa. Esetleg lehetne /test vagy /teszt ?
Mivel nincs ilyen parancs minden átlépéskor először a lobby szerverre kell menni, majd onnan a teszt szerverre.

2. Ötlet: 
Teszter rang legyen az alap rang mindenkinek a Teszt szerveren. A fotón lehet látni, hogy van alap Tag és Teszter rang, de a Tag rangnak kevesebb jogai vannak mint egy Teszternek. A Teszt szerverre csak engedéllyel lehet bejutni, így felesleges egy alap Tag rang.
Tesztelés szempontjából ez fontos lehet.
Pl: Ha a Slimefunban találok egy hibát egy addonon belül nem tudom megnézni az addon verzióját, csak ha Teszter vagyok vagy az felett. #4869 -es hibajelentés erre egy példa. Egyedül nem tudtam kideríteni a hiba okát, csak KernelPanic Teszter segítségével.
![Teszter_rang](https://user-images.githubusercontent.com/68443484/166166012-8a720c4d-0821-4b86-953a-58296c68da06.png)

**Comment by MrZero1** [comment]
Egyelőre lezárom.

**Comment by VdszHun** [comment]
:/
