### ISSUE TITLE
SFSurvi teendők

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4877]
- [x] Tojásos mobbefogó - ha lesz, warp
- [x] Bútorok - ha lesz, warp
- [x] Fertőzött mobok - ha lesz, warp
- [x] Struktúra plugin - ha lesz, warp?
- [x] Járművek warp
- [x] Egyéb warp lerakása (ide lehetne a kisebb dolgokat leírni, pl. láthatatlan képkeret, pwarp, team parancsok, mobtojásos)
- [x] OldMúzeum frissítése, új rész kialakítása
- [x] Évszakok warp befejezése
- [x] Skills fordítás befejezése
- [x] GUI shop fordítás
- [x] GUI shop beállítása
- [x] Telkek világba plot út 
- [x] Telkek világ warp átmásolása, beállítása
- [x] Vadon, lootvadon warp átmásolása, beállítása
- [x] Pénz warp frissítése (chestshop, aukciósház stb.)
- [x] NPC-k lehelyezése
- [x] Crate ládák
- [x] Eventek átmásolása, beállítása egyesével (nyitás után)
- [x] Hologramok lerakása
- [x] Teleportok GUI létrehozása
- [x] Új SF warp
- [x] Egyedi plot út létrehozása
 - [x] Webshop GUI-ba leírás
- [x] Horgászversenyes plugin újrafordítása, új halak, stb.

**Comment by skrisz0101** [comment]
/info rgb-hez ezt a linket:
https://rgb.birdflop.com/

**Comment by MrZero1** [comment]
- [ ] Webshop GUI-ba leírás

**Comment by Laci444** [comment]
ömm úgy látom minden pipa akkor lezárom
