### ISSUE TITLE
építész telek

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4878]
**Szerver**: építész

Nincs lefordítva a telekizé építészen
Rendkívül fontos hiba, ráér bőven.
![2022-07-15_15 24 58](https://user-images.githubusercontent.com/29951969/179232166-c674ed54-b62d-43b9-9d66-e8f27058365b.png)

**Comment by MrZero1** [comment]
Lezárom, de csak azért, mert nem nagy gond, és szerintem ráférne egy update az építész szerverre, legalábbis a plot részére, esetleg a rangoknak extra jogokat adni.
