### ISSUE TITLE
SfSurvival észrevételek, hibák, bugok

### ISSUE THREAD

**Issue by MrZero1** [TheOld-Crafters/Minecraft-servers#4879]
SfSurvival hibákat, ötleteket ide, kommentbe írjátok meg.

**Comment by MrZero1** [comment]
- [ ] 2 játékos a plottelkeit nem tudja összekapcsolni. A confirm után nem történik semmi.

**Comment by MrZero1** [comment]
- [ ] Nem folyik a láva, víz, nincs gravitáció

**Comment by MrZero1** [comment]
- [ ] Kemencék nem múködnek

**Comment by MrZero1** [comment]
- [ ] Ládák warpon a legtöbb láda effektje eltűnt.
- [ ] Járművek, képkereteket eltűntek a spawnról.

**Comment by skrisz0101** [comment]
> * [ ]  2 játékos a plottelkeit nem tudja összekapcsolni. A confirm után nem történik semmi.

Mert tagnak Max 3 telke lehet és 3mas telket +másikat akartak összekötni

**Comment by skrisz0101** [comment]
Képkeretek eltűntek warp sfről

**Comment by skrisz0101** [comment]
Mob nem spawnol warp farmra, nem ad lootot

**Comment by skrisz0101** [comment]
Rangok jogairól leírás

**Comment by skrisz0101** [comment]
Oldmúzeum

**Comment by skrisz0101** [comment]
Feltűnőbb  staffchat

**Comment by skrisz0101** [comment]
Bútoroknak gui

**Comment by skrisz0101** [comment]
Vote nem ad Fortuna kulcsot és asszem mást se

**Comment by skrisz0101** [comment]
Telek fordítás

**Comment by skrisz0101** [comment]
/alchemy - > felső sor 2 cuccli nincs leforditva

**Comment by skrisz0101** [comment]
Manuális Eventek cmd-zés

**Comment by MrZero1** [comment]
- [ ] állatfarmon nem spawnolnak az állatok

**Comment by MrZero1** [comment]
- [ ]  lootvadonban nincsenek mobok, állatok

**Comment by MrZero1** [comment]
- [ ] RTP a border mellé rakja az embereket

**Comment by VdszHun** [comment]
1.19.1-ben nem lehet rányomni az **Igen / Nem** gombokra amikor egy NPC-től kapsz küldetést.
Át kellett mennem 1.18.2-be, hogy el tudjam fogadni, a küldetést ez után már el tudtam végezni, a napi limitált küldetésnél figyeltem fel erre.

1.19.1 kliensem (ha számít milyen modjaim vannak):
Forge 42.0.9
Optifine HD U H9 pre1
Just Enough Items 11.2.0.241

**Comment by skrisz0101** [comment]
> 1.19.1-ben nem lehet rányomni az **Igen / Nem** gombokra amikor egy NPC-től kapsz küldetést. Át kellett mennem 1.18.2-be, hogy el tudjam fogadni, a küldetést ez után már el tudtam végezni, a napi limitált küldetésnél figyeltem fel erre.
> 
> 1.19.1 kliensem (ha számít milyen modjaim vannak): Forge 42.0.9 Optifine HD U H9 pre1 Just Enough Items 11.2.0.241

a hibát értem, de amúgy be lehet írni chatre is hogy "igen"
Emiatt ne válts 1.18ra

**Comment by VdszHun** [comment]
> > 1.19.1-ben nem lehet rányomni az **Igen / Nem** gombokra amikor egy NPC-től kapsz küldetést. Át kellett mennem 1.18.2-be, hogy el tudjam fogadni, a küldetést ez után már el tudtam végezni, a napi limitált küldetésnél figyeltem fel erre.
> > 
> > 1.19.1 kliensem (ha számít milyen modjaim vannak): Forge 42.0.9 Optifine HD U H9 pre1 Just Enough Items 11.2.0.241
> 
> a hibát értem, de amúgy be lehet írni chatre is hogy "igen"
> Emiatt ne válts 1.18ra

Nagyon köszönöm a segítséget ^^
Bocsánat, hogy csak most válaszolok, valamiért nem kaptam értesítőt a kommentedről :/

**Comment by skrisz0101** [comment]
exo garden bokrok kiütik a bedrockot

**Comment by skrisz0101** [comment]
ha emojit írunk a mondatba, leveszi az ékezetet

**Comment by Laci444** [comment]
ez borzasztóan átláthatatlan így
láttam hogy sokminden már készen van és ami még maradt az új issueban van írva úgyhogy ezt lezárom
ha különböző hibák vannak akkor külön issuet nyissatok neki

köszönöm
