### ISSUE TITLE
Bútorok Ploton

### ISSUE THREAD

**Issue by TheGamer85** [TheOld-Crafters/Minecraft-servers#4882]
**Szerver**:SfSurvival

*Út a hibához:*Bármilyen többblockos Bútor

> *Dátum és idő:*2022 07 08 2:09

A bútorok képesek a plot környéki blockokat rongálni mégha a felhasználonak ehhez joga nincs

![2022-08-07_02 06 43](https://user-images.githubusercontent.com/110748714/183269700-c9a8b4c3-1dec-485d-8eaa-ade9a087ccf5.png)
![2022-08-07_02 06 47](https://user-images.githubusercontent.com/110748714/183269701-f7932a82-0750-4840-b68b-f5be53a82b80.png)

**Comment by MrZero1** [comment]
Jelentve

**Comment by MrZero1** [comment]
Fejlesztő szerint ez lehetetlen, hiába küldtem a képeket el neki. Lezárom.

**Comment by MrZero1** [comment]
Ne a plot szélére rakjuk a bútort, ha mégis, és rongálja a plotot, jelezni kell adminnak, majd visszaépíti.
