### ISSUE TITLE
sf survival /quest hiba 

### ISSUE THREAD

**Issue by Aquir-0** [TheOld-Crafters/Minecraft-servers#4883]
sf survival

A hajléktalantól felvet "A szomjúság ellenszere" küldetésnél nem írja hogy milyen potion kell a /quest résznél. 
Azt hiszem 2 vizes palackot, 1 méreg meg 1 erő potit, és 2 vizes vödröt kér.
![2022-08-07_01 53 24](https://user-images.githubusercontent.com/73481520/183269749-7c994915-1c05-4a1b-b7e3-17a84a15e449.png)

2022.8.7.  1:58

**Comment by skrisz0101** [comment]
Igen, azt kér.
Majd szerkesztjük, addig nyitva marad a jelentés.

**Comment by skrisz0101** [comment]
elfelejtettem írni, ez egy ideje javítva van már
