### ISSUE TITLE
SF Survival napi event- ragerun piston hiba

### ISSUE THREAD

**Issue by LACI-12** [TheOld-Crafters/Minecraft-servers#4884]
SF Survival 
A napi eventeknél a ragerun-nál az első 3 sor piston nem jön fel ha rá állsz a nyomólapra.

![2022-08-08_00 54 07](https://user-images.githubusercontent.com/110792533/183314839-8bc788eb-885e-4b4e-b9b8-9c2fe6784ee4.png)
![2022-08-08_00 54 00](https://user-images.githubusercontent.com/110792533/183314844-bbe99259-19df-47b9-b849-b982e255b1a8.png)
![2022-08-08_00 54 04](https://user-images.githubusercontent.com/110792533/183314845-4fcce0ea-a97d-4b5c-9d6e-d5c56012b2f7.png)

> *Dátum és idő:* 2022.08.08. 01:00

**Comment by poma123** [comment]
javítva
