### ISSUE TITLE
SF Survival /quest hiba bohóc npc [A bohóc legjobb barátja]

### ISSUE THREAD

**Issue by LACI-12** [TheOld-Crafters/Minecraft-servers#4885]
**Szerver**:SF Survival

*Út a hibához:* /quest és ott nem irja hogy milyen enchant-os kardot kért.

![2022-08-09_04 27 15](https://user-images.githubusercontent.com/110792533/183552000-f366e56d-8aab-445f-b676-6378687925e2.png)
![2022-08-09_04 28 28](https://user-images.githubusercontent.com/110792533/183552104-40c8acc6-7ee9-4228-8f8b-48138e0d4709.png)

> *Dátum és idő:*2023.08.09 4:25

**Comment by poma123** [comment]
Valószínűleg limitált sajnos a beállítás, így az elején kell felírnod/emlékezned rá, milyen itemet kér pontosan.
