### ISSUE TITLE
SF Survival /quest hiba rab npc [szökés]

### ISSUE THREAD

**Issue by LACI-12** [TheOld-Crafters/Minecraft-servers#4886]
**Szerver**:SF Survival

Út a hibához:  /quest és ott nem írja hogy milyen enchant-os csákány kell neki.
Arról nincs képem hogy milyet kért.
![2022-08-09_04 46 29](https://user-images.githubusercontent.com/110792533/183553605-1d7fff25-054b-49fb-9534-72f338098bf4.png)

> *Dátum és idő:*2022.08.09 04:30

**Comment by poma123** [comment]
Valószínűleg limitált sajnos a beállítás, így az elején kell felírnod/emlékezned rá, milyen itemet kér pontosan.
