### ISSUE TITLE
SF Survival /evente- napi eventek- futam hiba

### ISSUE THREAD

**Issue by LACI-12** [TheOld-Crafters/Minecraft-servers#4887]
**Szerver**: SF Survial

*Út a hibához:* Ha az eventen kizuhansz akkor a voidba megállsz és azt írja ki hogy "Hey! You are not permitted to leave this area."
A /spawn-al ki tudsz jutni onnan de amilyen effeck volt rajtad az rajtad marad pl. végtelen lassúság, ha meghalsz elmulik.

![2022-08-09_19 05 29](https://user-images.githubusercontent.com/110792533/183715967-27160bea-705b-457f-9831-96e27f009802.png)

> *Dátum és idő:*2022.08.09. 19:05

**Comment by MrZero1** [comment]
Javítva, köszi!

1 jelentés kulcs
