### ISSUE TITLE
SfSurvival, chestshop

### ISSUE THREAD

**Issue by mnb124** [TheOld-Crafters/Minecraft-servers#4888]
SfSurvival,

Szimplán nem megy a chestshop, probáltam a ládára, láda felé rakni a táblát, akárhogy cserélgetem a szöveget is egyszerűen nem akarja létrehozni a shopot.

Kiprobálható.

2022.08.11, 05:16

**Comment by MrZero1** [comment]
Nem az a Chestshop plugin lesz, ami eddig volt. A GUI shop és az aukciósház pluginja 3in1, a 3. a Chestshop.

Sokkal egyszerűbb lesz a kezelése, és sokkal látványosabb is, de jelenleg nem elérhető, mert restart után bebugol a hologram.

Pénz warpon van róla leírás. Amint engedélyezve lesz, DC-n jelezzük. 

Lezárom ezt a hibajegyet.
