### ISSUE TITLE
Sfsurvival jobs + ce bug

### ISSUE THREAD

**Issue by szofogado** [TheOld-Crafters/Minecraft-servers#4889]
Sfsurvival
Hiba lényege: Ha egy adott eszközre telepátia enchantot teszel, akkor a job nem érzékeli, hogy teütötted ki a blockot így nem kapsz se pénzt se semmit. (ásóval teszteltem és homokkal.)  
Az ásó hat 5 szer 3 tör 3 ön. és telepátia, eddig működött vele a jobs, úgy hogy nagy eséllyel köze van hozzá a ce-nek. 

Ha van kérdés ezzel kapcsolatban, azokra szívesen válaszolok.

**Comment by MrZero1** [comment]
Köszi a jelentést, nincs már telepátia enchant más okból kifolyólag
