### ISSUE TITLE
Login szerver privát üzenetküldés hiba

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4892]
**Szerver**: Login szerver

*Út a hibához:*
Ha privát üzenetet küldesz egy másik játékosnak azt fogja kiírni a chat, hogy magadnak küldtél üzenetet, viszont megkapja az üzenetet az akinek küldted.

A hibát eredetileg **easymacro**-val fedeztem fel még az SFSurvival nyitásának napján, de akkor nem jelentettem, ma pedig újrateszteltem **Squidmanus**-al.
Fotó:

![Login_private_chat_bug_TOC_2022_08_12](https://user-images.githubusercontent.com/68443484/184449727-71df2787-02e7-4900-9818-718721c0e9bf.png)

> *Dátum és idő:*
A hiba jelen van legalább 2022 08. 06. óta

**Comment by MrZero1** [comment]
Azt hiszem, már javítva lett ez is.
