### ISSUE TITLE
Topg kiírás

### ISSUE THREAD

**Issue by NojinElife** [TheOld-Crafters/Minecraft-servers#4893]
Topg weboldalon a kiírásban 1.17.1 van kiírva a jelenlegi helyett
[https://topg.org/minecraft-servers/server-630064](url)

![topg](https://user-images.githubusercontent.com/80846861/184505038-2e54df96-35e5-481e-8214-cbc3030c5c31.PNG)

**Comment by skrisz0101** [comment]
szerintem minden szavazóoldalon az van kiírva még

**Comment by VdszHun** [comment]
Igen, mindegyik oldalon régi adatok vannak

**Comment by MrZero1** [comment]
Javítva, köszi!

**Comment by MrZero1** [comment]
Játékosnevedet írd le Discordon privátba, légyszi. Máskülönben nem tudok adni kulcsot
