### ISSUE TITLE
AH Magyarosítás hiba

### ISSUE THREAD

**Issue by Raava3** [TheOld-Crafters/Minecraft-servers#4894]
Slimefun

*Út a hibához:*
Aukciós ház Rendezés helyett Rendelés van írva

> *Dátum és idő:* A hiba állandó
![image](https://user-images.githubusercontent.com/111230367/184536532-36a2c8ac-e899-4f9f-8a9e-f1b2cc89ba5e.png)

**Comment by poma123** [comment]
Javítva
