### ISSUE TITLE
ŐrültVarázslatok fordítás hiányosság

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4895]
**Szerver**: SfSurvival

*Út a hibához:*

Pl a Tombolás III enchantnál angolul írja hogy hányszoros a damagem. A többi enchantot nem néztem, mivel még nem raktam fel őket, de érdemes a többit is átnézni, ha ez nem szándékos.

> *Dátum és idő:*

**Comment by poma123** [comment]
Konkrétan a fél fájl nincs lefordítva.

**Comment by MrZero1** [comment]
Nem tudom Poma mit nézel, hogy nincs lefordítva a fél fájl, mert a plugin nagyrésze le van fordítva.

**Comment by poma123** [comment]
Így megoldódott, köszi!
