### ISSUE TITLE
Én előbb voltam

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4897]
sfsurvi:

![image](https://user-images.githubusercontent.com/74869381/184679373-7471787e-76d9-4ff5-89ee-055504e12c66.png)

**Comment by poma123** [comment]
Ezt a chatcontrol műveli, kérdés, mi legyen vele.

**Comment by skrisz0101** [comment]
ne legyen

**Comment by Laci444** [comment]
meg lehetne oldani hogy azon a területen kapjanak jogot annak a chc rule bypassára

várom a véleményeket és további ötleteket

**Comment by skrisz0101** [comment]
Nem kell

**Comment by poma123** [comment]
Felesleges ez

**Comment by MrZero1** [comment]
Ha jól tudom, ez is lezárható már.
