### ISSUE TITLE
Crazyenchant

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4899]
Nincs jog a /ce help-re
![image](https://user-images.githubusercontent.com/38157910/184682429-b880694e-a8e2-433f-8088-7e8f6eeabc76.png)

**Comment by poma123** [comment]
Nem tudom, hogy erre szükség van-e

**Comment by skrisz0101** [comment]
nincs lefordítva, lehet azért XD
