### ISSUE TITLE
Sf Position selector hiba

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4900]
**Szerver**: SfSurvival, Teszt

*Út a hibához:*
A position selector (sf-es item) nem jelöli ki az első pozíciót. Sk és én is teszteltük.

> *Dátum és idő:* Állandó

**Comment by skrisz0101** [comment]
még mindig szar

**Comment by MrZero1** [comment]
Köszi a jelentést, ez ilyen marad sajnos.
