### ISSUE TITLE
Sfsurvival - Kreatívban lift használat

### ISSUE THREAD

**Issue by KingDeadZ** [TheOld-Crafters/Minecraft-servers#4901]
![2022-08-16_18 26 11](https://user-images.githubusercontent.com/38157910/184930563-295a7da6-374d-48bb-8d95-0329fc2548bd.png)

Ha kreában jobbkattolok liftre akkor ezt írja ki, és nem csinál semmit.

**Comment by UDPSendToFailed** [comment]
Javítva.
