### ISSUE TITLE
SfSurvi Leopard 2A7 Tank 

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4902]
**Szerver**:

*Út a hibához:*
A tank nem tud lőni, pedig a kezembe van a tűzgolyó és jobbkattolok. A csomagtartót nyitja meg.

Levédésen kívül és belül sem működött.
+1 info, nemtudom hogy hiba-e vagy szándékos, de lootvadonba nincs engedélyezve, nem lehet letenni.

> *Dátum és idő:*

**Comment by UDPSendToFailed** [comment]
Javítva.
