### ISSUE TITLE
SfSurvi napi láda

### ISSUE THREAD

**Issue by mnb124** [TheOld-Crafters/Minecraft-servers#4903]
Minap mikor kinyitottam a 8 óránkénti ládát, felfedezni véltem hogy a szokásos, és igért egy helyett, 2 kulcsot rejtett a láda,
Nem tudom hogy ez szándékos, vagy sem, mindenesetre poma mondta hogy githubon jelentsem.

**Comment by MrZero1** [comment]
Ez teljesen szándékos, 1-2 sloton 2 kulcsot lehet nyitni. 🙂
