### ISSUE TITLE
Vein Miner Rune

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4904]
Teszt

Vein Miner Rune nem működik. 
Az Xp-t úgy adja meg mindha minden ércet kiütött volna, viszon mégsem veinmineolta ki.

**Comment by mnb124** [comment]
Valszeg sfsurvin se megy akkor.

**Comment by KingDeadZ** [comment]
shryx alsóvonallal addoltattam be sfsurvin, aztán teljesen jól működött ott

**Comment by skrisz0101** [comment]
Akkor valaki le is zárhatja

**Comment by Laci444** [comment]
köszi sk
