### ISSUE TITLE
tpaccept

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4905]
sfsurvi

Kiírja hogy valaki aki egyszer 2 órával ezelőtt rámtpzett, hogy ővé már lejárt.
![image](https://user-images.githubusercontent.com/74869381/185051948-11944cf9-76f1-492a-8cfe-676efdf1d2a2.png)

**Comment by poma123** [comment]
Elvileg 120 másodperc a timeout, levittem 60 mp-re.
Ezenkívül mást nem tudok tenni
