### ISSUE TITLE
Wither golem

### ISSUE THREAD

**Issue by kecske12334** [TheOld-Crafters/Minecraft-servers#4906]
SeagullPeti200

**SfSurvival**:

*A wither golem multiblock a dynatech addonból nem működik. Netherben is próbáltam letenni, védett és védetlen területen is valamint a lootvadonban is. Megépítem helyesen és semmit sem csinál.*

> *2022.08.16. du.*

**Comment by skrisz0101** [comment]
elvileg már jó, többen is jelezték. Ha megépíted, jobb klikkelj rá
majd valaki lezárja

**Comment by Laci444** [comment]
köszi sk
