### ISSUE TITLE
Hiányzó Zeneszám név

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4907]
Szerver: SF Survival

a /music paranccsal megnyitható panelen böngészés közben találtam egy olyan zeneszámot amely nem rendelkezik névvel:
![image](https://user-images.githubusercontent.com/60291809/185690244-f386655f-7cbe-4143-8a68-17db841a8242.png)

Elinditás után a "Carol of the Bells" címü számot játszotta le (chatre kiírta)
Nemtudom hogy számít-e de 08.19. 21:00 magasságában futottam bele a hibába.

**Comment by skrisz0101** [comment]
én ahogy néztem már jó, szerintem nem nyúlt hozzá senki se. Majd valaki lezárja

**Comment by Laci444** [comment]
köszi sk zárom
