### ISSUE TITLE
Mindenazegyben csákány

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4908]
**Szerver**: SfSurvival

*Út a hibához:*
A munkás ládából szerezhető Mindenazegyben csákányon még mindig rajta van az Alagút II.
Tudom, hogy már nem működik, viszont ki kellene cserélni a ládában lévőt, mert ez így félrevezető.

> *Dátum és idő:*

**Comment by skrisz0101** [comment]
Ja ezt már néztem azelőtt is, de végül már meg lett oldva.
majd valaki lezárja

**Comment by Laci444** [comment]
köszi sk
