### ISSUE TITLE
Falusi nem arat.

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4909]
**Szerver**:

*Út a hibához:*
lovid_-nál és nálam sem megy.
A falusi nem arat, és nem is vet. Levédésen belül vagyunk, nomobspawns flaggel, de flag nélkül sem arat/vet.
A farmot jól építettem meg, minden lehetséges módot kipróbáltam, sehol sem ment.

> *Dátum és idő:*

**Comment by MrZero1** [comment]
Anno volt ilyen gond Oldblocks-on, valami gamerule-t kellett bekapcsolni asszem.

**Comment by andris155** [comment]
A megoldáshoz a mobGriefing gamerule-t kell hozzá true-ra állítani, ha valóban ez okozza a problémát.

**Comment by UDPSendToFailed** [comment]
Javítva.

https://purpurmc.org/docs/Configuration/bypass-mob-griefing_12
