### ISSUE TITLE
Villager Cure Wand hibás crafting recept

### ISSUE THREAD

**Issue by Ftcsabi** [TheOld-Crafters/Minecraft-servers#4911]
Szerver: SFSurvival

Út a hibához: Villager Cure Wand resepje alapján elhelyezve az oltáron, mikor középen az end rudat kéne rakni azt írja ki hogy "Ismeretlen recept! Ehelyett használd a helyes receptet!".
A recept szerint helyesen csináltam mindent (másik fajta receptnél tudtam craftolni szóval az altar is okés).

Szerintem azzal lehet a gond h a gyengeség potit átnevezi az altar (kivételkor is marad az altaros neve).
A másik lehetséges hiba h lehet nem is ez kell hozzá, keresgéltem slimefun-on belül és a szerint Szintetikus Emerald kéne, viszont azt sem fogadja el.

Dátum és idő: Bármikor

**Comment by skrisz0101** [comment]
Ellenőriztem én is, tényleg így van. Megnéztem egy másik receptet villager utilsban, ott ment.

**Comment by MrZero1** [comment]
Ez sajnos így marad. Köszi a jelentést!
