### ISSUE TITLE
5 helyett 10%

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4912]
**Szerver**: SfSurvival

*Út a hibához:*
A tábla 5% helyett továbbra is 10%-ot ír.

Valamint, megoldható lenne, hogy az adót a vásárlás UTÁN vonja le?
Jelenleg ugye ha fel akarsz tenni valamit ahra, előtte vonja el az adót, nem azután miután megvásárolták.
Ez kis tételben még nem vészes, ám nagyobb tételekben, pl mikor valaki felrak 1M értékben valamit ahra, már elgondolkodtató.

![2022-08-21_15 05 25](https://user-images.githubusercontent.com/67922620/185792465-96a162af-aa09-41a3-ba93-f7a0a4e66e24.png)

> *Dátum és idő:*

**Comment by skrisz0101** [comment]
Javítottam, majd valaki lezárja

**Comment by MrZero1** [comment]
"Valamint, megoldható lenne, hogy az adót a vásárlás UTÁN vonja le?"

Jelentem a fejlesztőnek ötletként, hátha
