### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4915]
Ha a mondatban van emoji, eltűnnek az ékezetek

**Comment by andris155** [comment]
<img width="424" alt="Screenshot 2022-08-25 135440" src="https://user-images.githubusercontent.com/8324198/186657892-1d8d880c-3130-4482-9363-b7100b38c48a.png">
Talán ez a beállítás lehet a megoldás.

**Comment by skrisz0101** [comment]
Köcke Andris

**Comment by UDPSendToFailed** [comment]
Köszi Andris

**Comment by poma123** [comment]
Javítva (köszi Andris)

**Comment by andris155** [comment]
Szívesen.
