### ISSUE TITLE
Hőmérséklet

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4917]
sf

Teljesen feleslegesen van bent, nem ad hozzá semmit. Csak kitakarja lent azt hogy mennyi manád van, meg azt hogy mennyit kapsz jobsból. Nem azt mondom hogy vegyétek ki, de ha lehet valahová máshová átkellene tenni azt hogy hol mutassa a hőmérsékletet.

**Comment by Laci444** [comment]
lehet permet adni egy parancsra, amivel ki lehet kapcsolni mindenkinek magának

direkt nem adtam eddig mert így meg lehet kerülni az időjárási viszonytagságokkal járó extra dologokat (pl megfagyni télen) de ha a többiek is egyetértenek azzal hogy adjunk jogot akkor mehet

várom a véleményeket

**Comment by skrisz0101** [comment]
szerintem ki lett kapcsolva a meghalás időjárás által, mert 2 hét alatt senkivel se történt ilyen sztem xd

**Comment by IciAlex** [comment]
ezzel mivan?
