### ISSUE TITLE
Pvp kreatívba váltás.

### ISSUE THREAD

**Issue by mnb124** [TheOld-Crafters/Minecraft-servers#4919]
Pvp közben müködik a /gmc parancs és átvált kreatívba 
Úgyanugy a /fly, /god, a /fix,
Valószinűleg (avagy ezek nem teszteltek) menni fog a /heal, /feed is.

**Comment by poma123** [comment]
Ezért lett volna jobb egy külső pvp manager mint a griefprevention.
Tiltottam a parancsokat
1 jelentés kulcs

**Comment by poma123** [comment]
Mégse jár kulcs, mert ezt már Squid jelentette kicsivel korábban. (#4918 )
