### ISSUE TITLE
Isteni erőkkel rendelkező csapóajtó.

### ISSUE THREAD

**Issue by mnb124** [TheOld-Crafters/Minecraft-servers#4922]
Sfsurvialon tesztelve.

Ha kreatívban, gugolva, egy csapóajtóra probálsz táblát tenni, akkor a szerver ledob "Packet Processing Error" hibakóddal.
3-man is probáltauk, Én, King2Dead, és Trymadeus.

https://youtu.be/9KhZnkyEO40

2022.08.24

**Comment by mnb124** [comment]
Csak akkor csinálja mikor nyitva van a csapóajtó.

**Comment by MrZero1** [comment]
#4799

**Comment by poma123** [comment]
Valószínűleg akkor még nem lett javítva a hiba a ViaVersion részéről, szerintem ha 1.19.2-ről jössz fel nem kéne problémának lennie.
