### ISSUE TITLE
Irongolem idéző tojás

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4923]
**Szerver**: SfSurvival

*Út a hibához:*
Ha egy tojással ledobok egy iron golemet, ad egy vasrudat, aminek az a neve hogy Vasgólem-idéző tojás. Nem tudom letenni.

> *Dátum és idő:*

**Comment by skrisz0101** [comment]
Xdd

**Comment by UDPSendToFailed** [comment]
Javítva.
