### ISSUE TITLE
Poszterek

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4926]
Új szabály a poszter készítők védelmére.

**A posztereket a tulajdonosa engedélye nélkül nem lehet értékesíteni!**
Discordra egy új szoba ahova az építők beküldik a képet a poszterükről.

- Nekem kifejezetten rosszul esik amikor megépítek egy posztert eladom, majd az a személy olcsóbban profitál belőle, ennek a védelmére lenne.

Itt most akkor jöhetnének a kifogások például hogy "de ezt ki ellenőrni?", de ha azt is tudják figyelni hogy ki lop vagy csal, akkor ez nem jelenthet nagy kihívást. Ha észreveszik akkor szankció, ha nem akkor nincs.

**Comment by skrisz0101** [comment]
Támogatom

**Comment by UDPSendToFailed** [comment]
Van bent plugin, ami megakadályozza a térképek másolását, majd beállítom.

**Comment by IciAlex** [comment]
Az se jó ha a készítő nem tudja lemásolni

**Comment by UDPSendToFailed** [comment]
Megoldva, `/trm` a parancs. Csak az tudja másolni a térképet, aki hozzáadta a védjegyet.

**Comment by IciAlex** [comment]
Szeretlek kernel
