### ISSUE TITLE
Drogon Kincse Fail

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4927]
SF-survival
A mai Drogon Kincse nem aratott osztatlan sikert sajnos a szerveren játszók között. Az élmény javitása érdekében javasolnám a következőket:
-Lávát elfelejteni...
       Bár hangulatos és passzolt a környezethez, de engem pl kifejezetten bosszantott az állandó tüzeffekt (igen sokszor estem a lávába.)

-Nagyobb Map...
       Ugyanazon ládamennyiség nagyobb területen való elhelyezése, illetve olyan helyekre helyezése mely nem szembetűnő a map 
       másik végéről.

-Több belépési pont...
      Hogy növeljük az "élményt" és jobb loot eloszlás érdekében (mely növeli az elégedettséget) javasolnám, egy olyan map 
      kialakítását, ahol 2-4 belépési pont van, így a játékosok 2-4 irányból támadhatnák be a mapot, így a játékosok maguk döntenek, 
      hogy hol szeretnének nekikezdeni.

**Comment by MrZero1** [comment]
Köszi az ötletet. Ha aktuális lesz valaki részéről az új map, majd remélem gondol erre.
