### ISSUE TITLE
Láda addolás

### ISSUE THREAD

**Issue by zsombixx** [TheOld-Crafters/Minecraft-servers#4930]
Ha kreatív módban Ctrl + Egérgörgővel egy ládára kattintasz, majd lerakod, ki tudod ütni túlélőben és megkapod. Tudom hogy nem nagy glitch de akkor is. Lehet más dologra is lehet használni amit nem teszteltem. Ez gondolom azért van, mert van az a mechanika, hogy Ctrl + Görgővel elmented a láda NBT-jét, a plugin úgy érzékeli hogy nem kreatívban szerezted

**Comment by UDPSendToFailed** [comment]
Szándékosan nincs védve a láda, mivel kiütéskor elvesznének belőle a cuccok. Az NBT mentés tiltva van, csak kliens oldalon látszik úgy, hogy rajta marad.
