### ISSUE TITLE
Exotic Garden csemete lerakások

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4931]
SF Survival szerveren
Amennyiben megpróbálok olyan föld platformra csemetét tenni, mely alatt levegőblock van, akkor a csemetét nem engedi letenni. Ha sokat ugrálok és pakolom mint a bolond akkor elöbb utobb lecsapja, valamint ha aláépítek egy bizonyos pont után (még nem sikerült rájönnöm a mikéntjére) engedi lerakni a csemetét. Viszont érdekelne, hogy miért nem engedi a föld platformra letenni.

**Comment by MrZero1** [comment]
Ez olyan dolog, hogy zavaró, de nincs mit tenni vele. SF fejlesztőknek érdemes lenne megírni, kérdés, hogy foglalkoznak e vele vagy sem. (szerintem nem)
