### ISSUE TITLE
Sumo loop

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4932]
**Szerver**: SfSurvival

*Út a hibáhohoz:* Ha sumo event kozben a jatekosok kisorsolasa utan az egyik kilep, folyamat loopolja a resztvevok kijelzojen a "HARC"-ot, es a jatek nem indul el. Veget sem tud erni.
A jatekbol ha mindenki kilep es vissza, ugyanugy spammeli a "HARC"-ot, es a jatek sem tud elindulni a lobbybol. 

> *Dátum és idő:*

**Comment by poma123** [comment]
1 jelentés kulcs
