### ISSUE TITLE
Sumo vesztes új esélyt kap

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4933]
**Szerver**: SfSurvival

*Út a hibához:*
Marci-t lelöktem, majd közvetlen utána beadta még1x párharcra.

> *Dátum és idő:* 2022.09.12.19:52 után
![2022-09-12_19 54 37](https://user-images.githubusercontent.com/67922620/189723646-48167adf-c329-4bbc-a7fe-5e746983ba3e.png)

**Comment by poma123** [comment]
Oda van írva a képre a megoldás, hogy miért :)

"Páratlan játékosszám miatt MarciTheHun ismét játszik, **tét nélkül**"
Ha 2 ember továbbjutott, 1 pedig még hátravan, neki nincs párja akivel mehetne a **nem továbbjutók** közül, így egy továbbjutót dob be random a rendszer, akinek a meccsnek nincs tétje, mivel már továbbjutott.
