### ISSUE TITLE
Ender Dragon Leszummonálása

### ISSUE THREAD

**Issue by Ftcsabi** [TheOld-Crafters/Minecraft-servers#4934]
**Szerver**: SFSurvival

*Út a hibához:* Ender Dargon leszummonálásakor a 4 kristályból visszaad 1et.

> *Dátum és idő:* Bármikor

**Comment by IciAlex** [comment]
elég rég ilyen

**Comment by andris155** [comment]
Erre ha jól emlékszem régen az volt a trükk, hogy a teljes portálhoz hozzáférést kellett adni az építésre és rombolásra. Nem csak a kristály 4 helyéhez.

**Comment by IciAlex** [comment]
ja tényleg, emlékszem hogy ott a portálnál lehetett endstonet szedni

**Comment by poma123** [comment]
Javítva

**Comment by VdszHun** [comment]
> Javítva


Ez a hiba újra megjelent, ma többször is idéztem le sárkányt és idáig mindig kaptam vissza 1db kristályt, nem tudom más jelentette-e korábban ennek a feltűnését.
Dátum: 2023. 02. 03.
