### ISSUE TITLE
Elgépelt név

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4936]
Sf-survival
Amikor a fortune ládából kapok Barackfa csemetét akkor a chatre "Baracka csemetét ír Barackfa helyett.
![image](https://user-images.githubusercontent.com/60291809/190864306-95e23dba-a8b2-4514-8a69-5c0ba4000399.png)

**Comment by MrZero1** [comment]
Köszi, javítva!
