### ISSUE TITLE
Plot redstone cuccok

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4939]
Ha egy telken engedélyezi valaki például a nyomólap, gomb, kar hozzáférést bárki számára, akkor ugye mindenki tudja használni azokat.
De ha lelép a telek tulajdonosa, akkor nem tudnak használni semmit se.
Próbáltuk set és add paranccsal is, egyikkel se ment.
Icialex kapott érte jelentés kulcsot.

Így pl a slimefunos lift se megy, ha nincs fent

**Comment by UDPSendToFailed** [comment]
Javítva.
