### ISSUE TITLE
hiányzó Vote URL

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4940]
Sf survival

A harmadik Vote opció esetében a minestatus_net-re kattintva nem kapjuk meg a linket csak egy VoteURL szöveget.

![image](https://user-images.githubusercontent.com/60291809/192860163-4b7cc343-1e2a-4ecc-9ee9-40a32c60e3d5.png)
![image](https://user-images.githubusercontent.com/60291809/192860463-b0ac203f-6d5b-4cd8-86e7-c8a310255dfa.png)

**Comment by MrZero1** [comment]
Javítva, köszi!
