### ISSUE TITLE
Respawn

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4941]
sfsurvival

Halálkor nem az ágyadhoz dob a respawn, hanem a spawnra.

**Comment by Ziredus** [comment]
Ez mindig így volt mióta világ a világ nem?

**Comment by andris155** [comment]
Elvileg itt lehet ezt engedélyezni az EssentialsX konfigban, ha más plugin nem írja ezt felül: https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/config.yml#L1172

**Comment by UDPSendToFailed** [comment]
Javítva, köszi Andris!
