### ISSUE TITLE
GSit Plugin játékosra ülés hiánya

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4942]
**Szerver**: SFSurvival

*Út a hibához:*
A GSit Plugin egy része az, hogy más játékosok hátára is fel lehet ülni, de tapasztalataim szerint ez a funkció jelenleg ki van kapcsolva, a Spigot oldal szerint toggle parancs is létezik ehhez, de ez sem működik "/sit playertoggle" ki/be kapcsolná ennek a funkciónak a működését, de a szerveren parancsbeírás közben nem ismeri fel a playertoggle kulcsszót.

A Spigot oldal egyik kommentjében olvastam, hogy lehet ki van kapcsolva a Plugin konfigjában ez a funkció, kép lejjebb.

![image](https://user-images.githubusercontent.com/68443484/193130824-f48701de-53a2-4694-a9d7-3f10c36070fe.png)

> *Dátum és idő:* 2022. 09. 29

**Comment by UDPSendToFailed** [comment]
Engedélyeztem, köszi az ötletet!
