### ISSUE TITLE
Szavazási felületeken a szerver leírás frissítése

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4943]
Szavazó oldal

https://serverlist.games/server/5371
Itt a verzió nemjó
![image](https://user-images.githubusercontent.com/60291809/193575744-73bfefee-7ee0-43ac-bced-573ea2cfb588.png)

https://minecraft-mp.com/server-s287615
Verzió és Tagek módosítása (nincs benne a Slimefun pl, de lehetne belerakni EMF Crazyenchantments meg stb tagokat is pl)
![image](https://user-images.githubusercontent.com/60291809/193576281-f082f25b-050e-48cc-b97a-1401079a1385.png)

https://minecraftservers.org/server/616699
Szintén verzió és tagek
![image](https://user-images.githubusercontent.com/60291809/193576725-e6abccf4-a992-4363-9bbb-0ab6b3063d3d.png)

https://topg.org/minecraft-servers/server-630064
Verzió és tagek módosítása itt is!
![image](https://user-images.githubusercontent.com/60291809/193576966-6a5e4ffa-13b6-4f84-84b8-d99bef5a4920.png)

**Comment by MrZero1** [comment]
Köszi, fogom frissíteni ezeket

**Comment by VdszHun** [comment]
Összeköthető a #4893 -as jelentéssel

**Comment by Ziredus** [comment]
Oh, pedig körbe is néztem h van e hibajegy róla, de ezekszerint nem voltam elég alapos :)

**Comment by MrZero1** [comment]
Javítva, frissítve, köszi!

**Comment by MrZero1** [comment]
1 jelentés kulcs Ziredusnak megadva :)

**Comment by Ziredus** [comment]
thanks :D
