### ISSUE TITLE
/spook parancs és a spooky hat addolás

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4944]
SF survival

Ha megrémisztesz 1 játékost a /spook paranccsal a játékos pedig megüt valakit és ki alt+f4-el akkor a spooky hatet droppolja... Ellenörizve Mnb Ici és általam...

**Comment by IciAlex** [comment]
(csak ki kell lépned miközben spookolva vagy és harcban)

**Comment by MrZero1** [comment]
Lezárom, októberben volt ez a feelings.
