### ISSUE TITLE
Hologram kivetítő (slimefunos) és a káromkodás

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4945]
Ha hologram kivetítőbe írnak bármilyen káromkodást, engedi és nem csillagozza ki.
Régebben emlékszem ilyet nem lehetett.

mnb kapott érte kulcsot

**Comment by MrZero1** [comment]
Mivel érdemben válasz nem érkezett rá, valószínűleg nem ez a legfontosabb. Ha ilyennel találkoznánk, majd büntetjük.
