### ISSUE TITLE
Falusi

### ISSUE THREAD

**Issue by IciAlex** [TheOld-Crafters/Minecraft-servers#4946]
sf

Befogtam egy Mester Térképész falusit tojással, majd vissza letettem és csak az utolsó tradet mutatja.

![image](https://user-images.githubusercontent.com/74869381/195503489-ad0d9850-a757-4479-ac46-bfc5f16317a4.png)

**Comment by MrZero1** [comment]
Jelentettem a fejlesztőnek, ha javítja, majd bekerül a módosított verzió. Azért adok egy kulcsot érte. :D
