### ISSUE TITLE
Tojásbefogás

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4947]
Sf Survival

Levédésen belül hozzá nem adott ember gond nélkül befogja a mobjaimat... KeyAllHacker próbálta, és befogta a birkámat és 1 vasgólememet is...

**Comment by MrZero1** [comment]
Jelentettem a fejlesztőnek, már szeptember elején is jelezte Kernel. Ha lesz valami változás, majd frissítjük, lezárom a bejelentést.
