### ISSUE TITLE
Trópusi halas vödör

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4948]
ha gm1-ben lerakják, akkor kiírja hogy ezt nem lenne szabad, de lerakja a halat.

Sztem nem gond ha van joguk halat lerakni gm1-ben, csak ne írja akkor szerintem.

**Comment by mnb124** [comment]
De ha nem írja akkor kiuriti a vodroot :c 🤣
Engem amugy nem zavar, meg szerintem lehetme vele pl vodrot addolni ha betellik a krea inventoryd akkor a foldre dobja le a bodrot szerintem..

**Comment by MrZero1** [comment]
A különböző halas vödör lerakása tiltva lett.
