### ISSUE TITLE
/ásás /bányászat stb. parancs eltűnt

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4950]
Eddig volt a skillekhez /mining helyett /bányászat, ásás, stb. Eltűntek ezek a parancsok.

Valamint a /skill mellé volt /képességek parancs is, az is eltűnt.

+1: /skills-nél a skillek neve angol, ha jól rémlik eddig magyar volt.

**Comment by MrZero1** [comment]
#4970 a friss, lezárom ezt. Hátha valaki tudja mi a baja
