### ISSUE TITLE
Horgászverseny pénzjutalom

### ISSUE THREAD

**Issue by skrisz0101** [TheOld-Crafters/Minecraft-servers#4951]
Vdsz jelentette, hogy nem igazán kap a 2. helyezett Pénz jutalmat, pedig kellene, (?)
Erről mit lehet tudni?

**Comment by VdszHun** [comment]
Néhány infó, ha esetleg tud segíteni a helyzeten:

Az horgászverseny végén teljesen meg volt telve az eszköztáram, a versenyes halak miatt. A 2. helyezethez járó 8 gyémántot se kaptam meg ez miatt, általában ha tele van az eszköztár kidobja elém a gyémántokat.

A verseny végén az 1. játékos, feri22 épp nem volt fent a szerveren.

Ha jól tudom így van a nyereményosztás a versenyek végén:
1. Játékos 10000$ + 10 gyémánt + 2 netheritrúd
2. Játékos 8000$ + 8 gyémánt
3. Játékos 6000$

A versenyen emlékeim szerint 4-en vettünk részt, de panaszt nem hallottam mástól.

**Comment by MrZero1** [comment]
Én most teszteltem, és kaptam pénzt is meg gyémántot is. 
Első kép, pénzösszegek: 
![kép](https://user-images.githubusercontent.com/29709854/200081463-7e927f85-04f6-4380-9410-503d12a534da.png)


Második kép, szintén pénz:
![kép](https://user-images.githubusercontent.com/29709854/200081490-6ba78e23-53f3-4146-b2a6-bad52c8fdb6a.png)

A 8 gyémántot is megkaptam.

**Comment by MrZero1** [comment]
Mivel nem jött elő a hiba, lezárom.
