### ISSUE TITLE
Bridge Event

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4952]
SF Survival
Bridge eventen start elött be lehet ugrani a voidba, és az ember ilyenkor meghal... ezt ki kéne küszöbölni, pl a torony szélére körbe barriert rakni, ami a kezdéskor eltünik.

**Comment by skrisz0101** [comment]
Sztem nincs gond ezzel.

**Comment by poma123** [comment]
javítva
