### ISSUE TITLE
Spawn labirintus kitinszárny elírás

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4953]
**Szerver**: SFSurvival

*Út a hibához:* A Spawnon található labirintus egyik nyereménye egy különleges kitinszárny, a nevében találtam egy kis elírást, lásd fotó:

![image](https://user-images.githubusercontent.com/68443484/197557804-aa95521f-1ae6-4085-a059-ae30828659d9.png)

> *Dátum és idő:* 2022 10. 22.-én vettem észre, de szerintem azóta jelen van, hogy ez a nyeremény bekerült.

**Comment by MrZero1** [comment]
Javítva, köszi! 

_sk meg nub_

**Comment by MrZero1** [comment]
@VdszHun sk majd jelentés kulcsot
