### ISSUE TITLE
Slimefun warp gyárak láda

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4954]
**Szerver**: SFSurvival

*Út a hibához:* A Slimefun warpon található "SF gyárak napi 1x" láda kinyitásához nincs jog, lásd fotó:

![image](https://user-images.githubusercontent.com/68443484/197559104-9b37a430-80bf-45c1-8d25-b571cbdfce9b.png)

> *Dátum és idő:* 2022. 10. 23.-án fedeztem fel a hibát.

**Comment by MrZero1** [comment]
Javítva, megoldva.
