### ISSUE TITLE
Virtuális kulcsok hiba

### ISSUE THREAD

**Issue by Ziredus** [TheOld-Crafters/Minecraft-servers#4955]
Sf survival szerver

a /kulcsok parancs beirásakor a megjelenő kulcs listában 2x is szerepel az eventek kulcs...

![image](https://user-images.githubusercontent.com/60291809/198083796-7ac1f669-4be9-4612-89b9-b83d29b4d718.png)

**Comment by skrisz0101** [comment]
Az egyik a sima, amit kézbe kapsz eventeken.
A másik az, amit automatikus eventeken kapsz. (virtuális kulcs) ott külön inv van, azért kellett ez.

**Comment by poma123** [comment]
Így van, ez nem hiba, sajnos így lehetett csak megoldani.
