### ISSUE TITLE
ChangeBiome nem működik megfelelően

### ISSUE THREAD

**Issue by Ftcsabi** [TheOld-Crafters/Minecraft-servers#4958]
**Szerver**: SFSurvival vadon és vadon2 szerverén

*Út a hibához:*
A levédésemen belül ha /gpflags SetClaimFlag ChangeBiome parancsot használom akkor a régi build limitig változtatja meg csak a biomot.

Teszteltem és a ploton viszont működik rendesen a /plot setbiome, szóval a két vadonban nem megy rendesen csak.

> *Dátum és idő:* Bármikor

**Comment by MrZero1** [comment]
Talán a fejlesztőnek lehetne jelenteni. Én ezt lezárom.
