### ISSUE TITLE
Sárkányölő láda Pajzs elírás

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4960]
**Szerver**: SFSurvival

*Út a hibához:* Az új Sárkányölő ládában a Sárkányölő Pajzs neve el van írva, lásd fotó

![image](https://user-images.githubusercontent.com/68443484/201187075-0be7786f-b0e8-41ee-8039-51819da4cee4.png)

> *Dátum és idő:* 2022. 11. 10.

**Comment by skrisz0101** [comment]
javítva, adok majd jelentés kulcsot
