### ISSUE TITLE
Pap NPC hibás quest

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4962]
SfSurvivalon a Pap npc nem fogadj el a zombifalusi tojást az egyik küldinél, pedig azt kéri.
Azt írja, a neve rossz, ebből tudok következtetni, hogy valami el lett írva.

![pap](https://user-images.githubusercontent.com/67922620/202749720-c86a11b8-41d1-4f6d-9e72-d1523fc2cbf9.png)

**Comment by skrisz0101** [comment]
Minden mást odaadtál már neki?

**Comment by skrisz0101** [comment]
javítva, elfelejtettem írni.
