### ISSUE TITLE
Rang hiba

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4963]
**Szerver**: SfSurvival

*Út a hibához:*
Ha pl van old rangom, de nyitottam tag+-t, ugyanúgy telik mindkét rang.

![2022-11-19_19 10 58](https://user-images.githubusercontent.com/67922620/202865454-1179ef50-84fd-4315-96e7-9ef146efc344.png)
> *Dátum és idő:*

**Comment by poma123** [comment]
Javítva.
Mostantól ha megkaptok ládából egy rangot akkor kiírja chatre, hogy eltárolva a "termékek" listára. /termékek list
Itt tetszőleges időpontban lekérhetitek és aktiválhatjátok az adott "terméket" jelen esetben a rangot.

**Comment by skrisz0101** [comment]
Imádunk Pom!
