### ISSUE TITLE
Rangok parancs fejlesztése

### ISSUE THREAD

**Issue by VdszHun** [TheOld-Crafters/Minecraft-servers#4964]
**Szerver**: SFSurvival

A rangok parancson belül jelenleg nincs kiírva, hogy melyik rangnak mennyi _aukciós ház_ férőhelye van, az ötletet azért hoztam fel, hogy mindegyik ranghoz ki legyen írva az adott rang limitje.

Egy elírás pedig, hogy a **V.I.P.** és **Elit** rangnál is jelezve van, hogy egyszerre 3 munkád is lehet, de a V.I.P.-től lép érvénybe, így felesleges kiiratni az Elit rangnál, hisz az elején ott van, hogy a "V.I.P. rang jogai, plusz:".

![image](https://user-images.githubusercontent.com/68443484/203160864-500f8ca7-01b5-421e-b54e-e6b9350f2c1c.png)

**Comment by MrZero1** [comment]
Beleírtam az aukciósház mennyiséget. A 3 munka direkt van feltüntetve, így egyértelmű(bb).
