### ISSUE TITLE
Italos hordók átalakultak

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4965]
**Szerver**: SfSurvival

*Út a hibához:*
Az italos hordók is átalakultak nálam sima blokká, bennük volt évszázadokon át érlelt old tonicok.... Már nem lehet azokat a hordókat megnyitni.

> *Dátum és idő:*

**Comment by MrZero1** [comment]
Adtam tonicot Squidnak, lezárom.
