### ISSUE TITLE
Évszak

### ISSUE THREAD

**Issue by Sanszi** [TheOld-Crafters/Minecraft-servers#4968]
Sfsurvival: Az évszak pluginban jelenleg tél van, de a nyír (birch) fa levelének a színe nem változik az évszaknak megfelelően.

**Comment by MrZero1** [comment]
Jelentve a fejlesztőnek.

**Comment by MrZero1** [comment]
Fejlesztője ezt írta:

"The color of these leaves is hard coded into the game, I can't change them sadly"
