### ISSUE TITLE
Nem működik a /M

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4971]
**Szerver**: SfSurvival

*Út a hibához:*
Eddig működött akkor is a privát üzenetküldés, ha nagy M-el írtam a parancsot, most viszont ismeretlen parancs.
Ugyanez vonatkozik a /R és /WARP parancsokra.

> *Dátum és idő:*

**Comment by MrZero1** [comment]
Szerintem ez nem nagy gond. Nem kell kiabálni senkinek:(
