### ISSUE TITLE
Egy tojás néha 2 mobot tesz le

### ISSUE THREAD

**Issue by Squidmanus** [TheOld-Crafters/Minecraft-servers#4972]
**Szerver**: SfSurvival

*Út a hibához:*
Elkaptam egy szamarat hógolyóval, majd otthon letettem a tojást, viszont a tojásból 2 felnőtt szamár született 1 helyett.
Ugyanez megtörtént lóval is.

> *Dátum és idő:*

**Comment by MrZero1** [comment]
Köszi a jelentést, a fejlesztő rá fog nézni napokon belül.

**Comment by MrZero1** [comment]
Javítva, köszi!
