### ISSUE TITLE
Hibás Facebook link

### ISSUE THREAD

**Issue by andris155** [TheOld-Crafters/Minecraft-servers#4973]
A webshop oldalon https://bolt.oldcrafters.net/ hibás a Facebook linkje.

<img width="280" alt="Screenshot 2022-12-20 175117" src="https://user-images.githubusercontent.com/8324198/208721591-677220f3-31e5-46ac-b65b-974d560b2861.png">

<img width="323" alt="Screenshot 2022-12-20 175230" src="https://user-images.githubusercontent.com/8324198/208721828-b127b2d9-c9da-4338-bbf0-2e57e5dbbb76.png">

**Comment by MrZero1** [comment]
Köszi Andris, javítottam a linket!

**Comment by andris155** [comment]
Nincs mit.
